### ISSUE TITLE
Failed to parse CPU profile error on Performance tab

### ISSUE THREAD

**Issue by cihadturhan** [GoogleChrome/developer.chrome.com#1001]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
I wanted to see CPU profile after running performance recording but it throws error.

**To Reproduce**
1. Open Devtools
2. Click Performance Tab
3. Click save icon and stop it after a few seconds
4. It throws "Failed to parse CPU profile."

**Expected behavior**
It shouldn't happen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser: Chrome
 - Version: Version 91.0.4472.164 (Official Build) (x86_64)

**Additional context**
It happens on the following link [https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=US&q=editor](https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=US&q=editor)

**Comment by samthor** [comment]
> ⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

Sorry, if there is a problem with Chrome, please file it on crbug.com.
