### ISSUE TITLE
[extensions] [docs] How can I link to the source code ? (please help me)

### ISSUE THREAD

**Issue by CarsonSlovoka** [GoogleChrome/developer.chrome.com#1007]
I prepared to answer a question: https://stackoverflow.com/q/5345435/9935654

And I want to share how I get that information from the documentation.

But if I provide the link, for example

> https://developer.chrome.com/docs/extensions/reference/windows/#type-WindowType

This is not a good idea since the GitHub page may change such that the link is not found anymore.

So I want to show the link with sha1 linked to the source code, for example

> https://github.com/GoogleChrome/developer.chrome.com/blob/0210c012571ab40323fc6f6414b93e276b841090/site/en/docs/extensions/reference/windows/index.md#the-current-window

but docs seem is not to show all content in the markdown file.

for example, I need to show

| | |
| ---- | ---- |
![image](https://user-images.githubusercontent.com/17170765/126197271-b70c0228-6c5c-43bb-be88-d2919da900dc.png) | ![image](https://user-images.githubusercontent.com/17170765/126197700-3bd1986a-a31c-4eba-8c45-41686f8b63ba.png) 

but I can't find the TOC from the markdown file [en/docs/extensions/reference/windows/index.md](https://github.com/GoogleChrome/developer.chrome.com/blob/0210c012571ab40323fc6f6414b93e276b841090/site/en/docs/extensions/reference/windows/index.md#the-current-window)

Can anyone teach me how I can achieve it? <sup>I want to get any link from the table of contents</sup> Thank you so much.

----

## update 2

It seems the key point is 

![image](https://user-images.githubusercontent.com/17170765/126200321-91a755dc-df32-45d0-9949-c22c6a260cda.png)

Where can I found the API?

**Comment by samthor** [comment]
We generate this from Chromium's source code. If you wanted to link canonically to that API, you need to link to the original JSON, e.g.:
https://chromium.googlesource.com/chromium/src/+/2d4a97f1ed2dd875557849b4281c599a7ffaba03/chrome/common/extensions/api/windows.json#201

I appreciate that's not a very user-friendly display. Sorry, we don't have a better answer here.

**Comment by CarsonSlovoka** [comment]
@samthor Thank you. I didn't notice that there was already a reply. Although the display is not friendly, I can [clone](https://github.com/chromium/chromium/blob/2d4a97f1ed2dd875557849b4281c599a7ffaba03/chrome/common/extensions/api/windows.json#L194-L247) <sup>It's so huge...</sup> the project to find all I'm looking for.

**Comment by samthor** [comment]
For what it's worth, we fetch the `[tgz]` link from this URL to get the latest snapshot just of certain folders:
https://chromium.googlesource.com/chromium/src/+/2d4a97f1ed2dd875557849b4281c599a7ffaba03/chrome/common/extensions/api
So in building the documentation site, we don't have to fetch all of Chromium.

**Comment by CarsonSlovoka** [comment]
> For what it's worth, we fetch the `[tgz]` link from this URL to get the latest snapshot just of certain folders:
> https://chromium.googlesource.com/chromium/src/+/2d4a97f1ed2dd875557849b4281c599a7ffaba03/chrome/common/extensions/api
> So in building the documentation site, we don't have to fetch all of Chromium.

Hi @samthor, It's cool! It made me want to explore the git command a little further.

finally, I try
```js
git init
git sparse-checkout init
start .git\info\sparse-checkout   👈 open the "sparse-checkut" file
/* .git\info\sparse-checkout 
chrome/common/extensions/api/
*/

git remote add Github https://github.com/chromium/chromium.git
start .git\config
/* .git\config
[core]
    // ...
[extensions]
    // ...
[remote "Github"]
    url = https://github.com/chromium/chromium.git
    fetch = +refs/heads/*:refs/remotes/Github/*
    partialclonefilter = blob:none  // 👈 Add this line
*/
git pull --depth 1 Github 2d4a97f1ed2dd875557849b4281c599a7ffaba03
```
👆  You can found it at [How do I clone a subdirectory only of a Git repository?](https://stackoverflow.com/a/68794769/9935654)

**Comment by CarsonSlovoka** [comment]
It may help to use the link with ``version|tags``, that users know what version of chrome is, for example:

93.0.4577.70
> https://github.com/chromium/chromium/blob/93.0.4577.70/chrome/common/extensions/api/i18n.json#L32-L64
