### ISSUE TITLE
Enums missing documentation

### ISSUE THREAD

**Issue by karan173** [GoogleChrome/developer.chrome.com#1008]
Consider the RuleActionType enum (https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#type-RuleActionType). It has no associated documentation for the action types. 

The source code however does have documentation on these: https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/api/declarative_net_request.idl;l=62?q=declarative_net_request.idl. 

This also seems to be true for other enums, e.g. https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#type-HeaderOperation.

**Comment by samthor** [comment]
This has no simple representation in TS, seemingly unless we break out every possible value of the enum to a unique type. That doesn't mean we can't document them properly here, but that's the context of why it wasn't done.

Thanks for filing, I'll think about this and come up with a solution ASAP.

**Comment by samthor** [comment]
This is the same as #809 actually.
