### ISSUE TITLE
contentSecurityPolicy page missing

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#101]
@dotproto commented on [Thu Dec 03 2020](https://github.com/GoogleChrome/dcc-private/issues/399)

**Describe the bug**
The old [contentSecurityPolicy](https://developer.chrome.com/extensions/contentSecurityPolicy) page did not make it over in the initial migration.

**To Reproduce**
1. Search the repository for a file named "contentSecurityPolicy"
2. Search the repository for a file named "content-security-policy"
3.  Search the repository for a file named "content_security_policy"  

Note that no matches are found.

**Expected behavior**
A content security policy page should be included in our doc set.

---

@dotproto commented on [Thu Dec 03 2020](https://github.com/GoogleChrome/dcc-private/issues/399#issuecomment-738603535)

I came across 2 other missing pages: autoupdate and activeTab

**Comment by samthor** [comment]
These pages all exist now.
