### ISSUE TITLE
Chrome Developer Console - Doesn't Print New Line Character “\n” 

### ISSUE THREAD

**Issue by sv-vmh-dev** [GoogleChrome/developer.chrome.com#1022]
This is an annoying thing that happens every few updates. Somewhere in your settings the newline character ( '\n' ) is chosen to be escaped instead of printing a new line. Attached are screenshots. I did once find a blog post that described how to change this functionality, unfortunately I cannot find it and do not remember how to do this. Can you add a toggle, under console in the console settings, to change the functionality of escaping special characters in the console.

```js
// Code pasted into Chrome DevTools
Array(10).fill().map((x,i)=>i).join('\n');

// Expected Output
0
1
2
3
4
5
6
7
8
9

// Actual Output
"0\n1\n2\n3\n4\n5\n6\n7\n8\n9"

// Fix to use to get correct result
console.log( Array(10).fill().map((x,i)=>i).join('\n') );
```
![chrome-devtools-newline-print-issue](https://user-images.githubusercontent.com/87779580/126545067-c05ad953-b71b-47e0-8796-c5103c0e461b.png)

![chrome-devtools-settings](https://user-images.githubusercontent.com/87779580/126545084-6b37565c-0b96-42ec-bbc9-bb987717a2ef.png)

**Comment by robdodson** [comment]
Hey @sv-vmh-dev, this repo is only for the documentation on developer.chrome.com. Bugs and feature requests should be filed at crbug.com.
