### ISSUE TITLE
Grid layout bug on the main page

### ISSUE THREAD

**Issue by NovakVed** [GoogleChrome/developer.chrome.com#1029]
**Describe the bug**
On the main page, https://developer.chrome.com/ there is a bug where html <div> elements are in each other while using desktop device (resolution 1920 x 1200).

**To Reproduce**
1. Go to 'https://developer.chrome.com/'
2. Scroll down below card with title 'Welcome!'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/9297079/126862154-bd4933ef-3fdc-49d1-81a5-abe6bf2f9f6f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by samthor** [comment]
Thanks! I suspect you're viewing a "translated" page which has this bug. We
intend to introduce translations soon, and just have English callbacks for
now, but this occurs because we're missing content for certain cards.
