### ISSUE TITLE
"View, edit, and delete cookies" article is out of date

### ISSUE THREAD

**Issue by sbingler** [GoogleChrome/developer.chrome.com#1036]
**Describe the bug**
The ["Fields" section](https://developer.chrome.com/docs/devtools/storage/cookies/#fields) is an incomplete list of the cookie fields. The ["SameParty"](https://www.chromestatus.com/feature/5280634094223360) field has been added since the article was written.

This new cookie attribute is still underdevelopment but it feels worthwhile to acknowledge in the article.

**To Reproduce**
1. Open DevTools
2. Go to Application tab
3. Select Cookies (specifically select a site under "Cookies")
4. Find the "SameParty" field between "SameSite" and "Priority"

**Expected behavior**
The article should mention SameParty

This is the case for the latest Stable version of Chrome (92)

**Comment by robdodson** [comment]
@chybie would you be the right person to take a look at this?

**Comment by samthor** [comment]
or cc @rowan-m
