### ISSUE TITLE
Salvage self-hosting information from old apps docs

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#104]
@awfuchs commented on [Wed Dec 09 2020](https://github.com/GoogleChrome/dcc-private/issues/506)

@awfuchs, I wanted to highlight that 718cf949c343e1c9e62a96d3ffcf9aee50fd48fe removes 2 rows from the devguide table that referenced an `autoupdate` and `packaging` page. Based on the Wayback Machine, it looks like both of these pages redirected to the existing [hosting](https://developer.chrome.com/docs/extensions/mv2/hosting) page.

- [Wayback Machine January 18, 2020 crawl of /extensions/autoupdate](https://web.archive.org/web/20200709032658/https://developer.chrome.com/extensions/autoupdate)
- [Wayback Machine November 17, 2020 crawl of /extensions/packaging](https://web.archive.org/web/20201117101320/https://developer.chrome.com/extensions/packaging)

The apps pages for these topics ([autoupdate](https://developer.chrome.com/docs/apps/autoupdate/), [packaging (wayback)](https://web.archive.org/web/20161107175045/https://developer.chrome.com/apps/packaging)) may contain some useful data worth repurposing for a "self hosting" section. This is an area that we don't currently cover well.

_Originally posted by @dotproto in https://github.com/GoogleChrome/dcc-private/issues/505#issuecomment-742225637_

**Comment by jpmedley** [comment]
Addressed in #505
