### ISSUE TITLE
MV3 doc debugging tutorial needs samples fixed

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#106]
@awfuchs commented on [Fri Dec 11 2020](https://github.com/GoogleChrome/dcc-private/issues/517)

The sample files associated with /docs/extensions/mv3/tut_debugging/ are outdated and have not been MV3ized.
The screenshots on that page also need to be updated once the samples are updated.

**Comment by jpmedley** [comment]
Fixed by #1452
