### ISSUE TITLE
When using extensions that use sidebar panels with content set with `sidebarPane.setExpression` an error is thrown.

### ISSUE THREAD

**Issue by emilianionascu** [GoogleChrome/developer.chrome.com#1060]
**Describe the bug**
When using extensions that use sidebar panels with content set with `sidebarPane.setExpression` an error is thrown.

**To Reproduce**
1. Go to 'any extension that uses setExpression, e.g. https://chrome.google.com/webstore/detail/knockoutjs-context-debugg/oddcpmchholgcjgjdnfjmildmlielhof'
2. Click on 'Add to Chrome'
3. Load the dev tools with `Ctrl + Shift + I`
4. Load the extension dev tools by hitting `Ctrl + Shift + I`
5. See the error in the console. 

**Expected behavior**
Extensions should still work even after the v92 upgrade. It worked until v91.

**Screenshots**
![image](https://user-images.githubusercontent.com/1982577/127494065-5bf58948-1657-4c30-aa85-8a1e8447196e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 92.0.4515.107

**Additional context**

**Comment by robdodson** [comment]
@emilianionascu is this related to any of our documentation? This repo is only for docs work. If you've found a bug in Chrome it should be filed at crbug.com

**Comment by emilianionascu** [comment]
@robdodson I'm not sure. It could be that the API changed and we're supposed to use setExpression differently. That is a documentation issue. It could be that the API itself has a bug and then it's not a documentation issue.

**Comment by initplatform** [comment]
I believe I've hit this too with my extension: 
https://chrome.google.com/webstore/detail/sb-angular-inspector/lapcbklolihkkijaemmlbkpibgghhioh?hl=en

I thought it might be related to manifest 3, so I upgraded.

Still seem to be having an issue with setExpression.

**Comment by robdodson** [comment]
OK, tentatively assigning to @awfuchs to take a look

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll address this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312784415
