### ISSUE TITLE
MV3 Import external libraries (Documentation)

### ISSUE THREAD

**Issue by Mathie01** [GoogleChrome/developer.chrome.com#1072]
**Is your feature request related to a problem? Please describe.**
Today, with Manifest V3, we don't know how to import an external library to use it in the `content-script.js`

Example: I would like to use SocketIO in a chrome extension and be able to call the functions in `content-script.js`. I download the socket.io.min.js file but how do I import it into my extension?

It's probably possible, but the documentation doesn't say anything about it.

**Describe the solution you'd like**
A section in the documentation on how to import an external library

**Describe alternatives you've considered**
Go through a packet manager (npm) but it is a heavy solution

**Additional context**
I'm creating this issue because there are several developers who can't find any information about it (for MV3). My apologies if we didn't see the information on the documentation

**Comment by dotproto** [comment]
Thanks for filing an issue for this. This topic isn't covered as comprehensively as it could be. I'm not sure when we'll be able to fix this, so I'd like to share a couple quick pointers.

1. To [declarative inject](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#static-declarative) a 3rd party library, you can add the the library's JS file to your content script declaration's `js` array.
2. To [programmatically inject](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#programmatic) a 3rd party library, you can use [scripting.executeScript](https://developer.chrome.com/docs/extensions/reference/scripting/#method-executeScript). At the moment the files array [does not accept more than one entry](https://developer.chrome.com/docs/extensions/reference/scripting/#type-ScriptInjection), so you will have to make one `executeScript` call per file.
3. If you want to inject a file into a web page (e.g. append it to the page's DOM), the file must be exposed via [web accessible resources](https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/). From there, you can use [document.createElement('script')](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement), set the script's `src` using [runtime.getURL()](https://developer.chrome.com/docs/extensions/reference/runtime/#method-getURL), and [document.append()](https://developer.mozilla.org/en-US/docs/Web/API/Element/append) (or another appropriate DOM method) to add the script to the page.
4. If you want to include a library in a service worker, you have different options depending on the type of service worker.
    1. For standard service workers (no `type` specified), use [importScripts()](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) to include and other scripts.
    2. For module service workers (SW with `"type": "module"` declared as a property of your [background declaration](https://developer.chrome.com/docs/extensions/mv3/background_pages/#manifest)), you can use [static import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) statements to include other [modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).
5. If you want to include a library in your extension's popup or in a page you open as a tab, include the library as you would on a typical web page.

**Comment by Mathie01** [comment]
Thanks @dotproto for your response!

The first technique seems to be the best solution in my opinion.
But if I include an external library in `js`, I can't use it in my `content-script.js`.

Currently I have :

`"js": ["content-script.js", "socket.io.min.js"],`

I would like to use the content of socket.io.min.js in content-scripts
The declarative inject doesn't allow me to do that

**Comment by dotproto** [comment]
This may be an order of operations issue. Have you tried reversing the order of your scripts in the JS array?

**Comment by Mathie01** [comment]
Okay, that was the problem, hours of research for that

Thank you very much for your answer!

**Comment by samthor** [comment]
Consider also the wide array of developer tools available to you to compile your code down to a single file.

Also @dotproto do you know if `"content_scripts"` supports being injected as `"type": "module"` yet, like SW loading is?

**Comment by iatienza-uz** [comment]
> Thanks for filing an issue for this. This topic isn't covered as comprehensively as it could be. I'm not sure when we'll be able to fix this, so I'd like to share a couple quick pointers.
> 
> 1. To [declarative inject](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#static-declarative) a 3rd party library, you can add the the library's JS file to your content script declaration's `js` array.
> 2. To [programmatically inject](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#programmatic) a 3rd party library, you can use [scripting.executeScript](https://developer.chrome.com/docs/extensions/reference/scripting/#method-executeScript). At the moment the files array [does not accept more than one entry](https://developer.chrome.com/docs/extensions/reference/scripting/#type-ScriptInjection), so you will have to make one `executeScript` call per file.
> 3. If you want to inject a file into a web page (e.g. append it to the page's DOM), the file must be exposed via [web accessible resources](https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/). From there, you can use [document.createElement('script')](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement), set the script's `src` using [runtime.getURL()](https://developer.chrome.com/docs/extensions/reference/runtime/#method-getURL), and [document.append()](https://developer.mozilla.org/en-US/docs/Web/API/Element/append) (or another appropriate DOM method) to add the script to the page.
> 4. If you want to include a library in a service worker, you have different options depending on the type of service worker.
>    
>    1. For standard service workers (no `type` specified), use [importScripts()](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) to include and other scripts.
>    2. For module service workers (SW with `"type": "module"` declared as a property of your [background declaration](https://developer.chrome.com/docs/extensions/mv3/background_pages/#manifest)), you can use [static import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) statements to include other [modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).
> 5. If you want to include a library in your extension's popup or in a page you open as a tab, include the library as you would on a typical web page.

Hi Simeon,

about the fifth point, we could import javascripts in HTML popups from a CDN? or we need to compile these javascripts and add them into the extension as a resources?

Thanks in advance.

**Comment by iatienza-uz** [comment]
> > Thanks for filing an issue for this. This topic isn't covered as comprehensively as it could be. I'm not sure when we'll be able to fix this, so I'd like to share a couple quick pointers.
> > 
> > 1. To [declarative inject](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#static-declarative) a 3rd party library, you can add the the library's JS file to your content script declaration's `js` array.
> > 2. To [programmatically inject](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#programmatic) a 3rd party library, you can use [scripting.executeScript](https://developer.chrome.com/docs/extensions/reference/scripting/#method-executeScript). At the moment the files array [does not accept more than one entry](https://developer.chrome.com/docs/extensions/reference/scripting/#type-ScriptInjection), so you will have to make one `executeScript` call per file.
> > 3. If you want to inject a file into a web page (e.g. append it to the page's DOM), the file must be exposed via [web accessible resources](https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/). From there, you can use [document.createElement('script')](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement), set the script's `src` using [runtime.getURL()](https://developer.chrome.com/docs/extensions/reference/runtime/#method-getURL), and [document.append()](https://developer.mozilla.org/en-US/docs/Web/API/Element/append) (or another appropriate DOM method) to add the script to the page.
> > 4. If you want to include a library in a service worker, you have different options depending on the type of service worker.
> >    
> >    1. For standard service workers (no `type` specified), use [importScripts()](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) to include and other scripts.
> >    2. For module service workers (SW with `"type": "module"` declared as a property of your [background declaration](https://developer.chrome.com/docs/extensions/mv3/background_pages/#manifest)), you can use [static import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) statements to include other [modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).
> > 5. If you want to include a library in your extension's popup or in a page you open as a tab, include the library as you would on a typical web page.
> 
> Hi @dotproto ,
> 
> about the fifth point, we could import javascripts in HTML popups from a CDN? or we need to compile these javascripts and add them into the extension as a resources?
> 
> Edit: As we saw in the documentation CSP to other domains are not allowed so we tried and seems that is not possibel to load resources from other domains (CDN, etc).
> 
> Anyone can say something more clear on that point? anyone test that approach too?
> 
> Thanks in advance.

Any update on that?
