### ISSUE TITLE
"Can I host my own extension?" FAQ entry has dead links

### ISSUE THREAD

**Issue by nathan-osman** [GoogleChrome/developer.chrome.com#1084]
**Describe the bug**

The "Can I host my own extension?" section of the FAQ contains two links that both lead to 404 pages:  
https://developer.chrome.com/docs/webstore/faq/#faq-dev-03

**To Reproduce**
1. Go to https://developer.chrome.com/docs/webstore/faq/#faq-dev-03
2. Try to click on either of the two links
3. A 404 page is displayed

**Expected behavior**
The correct pages are displayed

**Screenshots**

![awsnap](https://user-images.githubusercontent.com/1253444/127941085-a79c1bc0-017d-48c3-9be5-db726d02a6de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H1
 - Browser: Google Chrome
 - Version: 92.0.4515.107

**Comment by samthor** [comment]
@dotproto @awfuchs One of the links should end up here: https://developer.chrome.com/docs/apps/autoupdate/

This content is only under /apps/, but feels relevant to extensions generally. Can we move it?
