### ISSUE TITLE
API permissions are not accurately specified.

### ISSUE THREAD

**Issue by karan173** [GoogleChrome/developer.chrome.com#111]
Checkout https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/. The Permissions section lists the permission as "declarativeNetRequest". 

Compare this with the old documentation at https://3-72-0-dot-chrome-apps-doc.appspot.com/extensions/declarativeNetRequest which lists the permissions as 

> declarativeNetRequest
> declarativeNetRequestFeedback
> host permissions
> 
> Note that declarativeNetRequestFeedback and host permissions should only be specified when necessary.

The permission section was pulled in from the template at [link](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/extensions/docs/templates/private/intro_tables/declarative_net_request_permissions.html?q=%22declarativeNetRequestFeedback%22%20file:html) in this case. This is likely also a bug for the other html template files in that directory.

**Comment by samthor** [comment]
Thanks, seems like there's just a number of manual additional permissions. I'll migrate these over to this repo's content next week rather than trying to embed them in the .D.TS files.
