### ISSUE TITLE
https://crbug.com/

### ISSUE THREAD

**Issue by arda2525-byte** [GoogleChrome/developer.chrome.com#1113]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [iPhone12Pro]
 - OS: [iOS14.7.1]
 - Browser [duckduckgo, stock browser, safari]
 - Version [18G82]

**Additional context**
Remove all data and personal information and delete all data related to Arda Yeremian from chrome and google.

**Comment by dotproto** [comment]
Closing as this request is not related to the developer.chrome.com repository. I'd encourage you to perform a web search to look for guidance on how to delete your Google account, ask Google to remove specific search results, or otherwise request data deletion.
