### ISSUE TITLE
Outdated Documentation for CCT tutorial

### ISSUE THREAD

**Issue by AlexMitraChromium** [GoogleChrome/developer.chrome.com#1114]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The newSession method's return type differs in the chrome developer documentation and the android documentation.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/android/custom-tabs/integration-guide/#create-a-new-tab-session
2. Observe the return type is listed as boolean
3. Click on the method (takes you to https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsClient#newSession(androidx.browser.customtabs.CustomTabsCallback)
4. Observe the return type is listed as CustomTabsSession

/cc @andreban

**Comment by dstmarthe** [comment]
Thanks for raising this. We’ve moved to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324323234
