### ISSUE TITLE
can't use alert() through scripting ReferenceError: alert is not defined

### ISSUE THREAD

**Issue by Tyrowo** [GoogleChrome/developer.chrome.com#1119]
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#executing-arbitrary-strings

the example on this page states that through use of the new .scripting API you can use alert in your extensions.
Is that true? I tried implementing it on my extension and it gave me a ReferenceError, the same error that usually comes up when you try to use the alert() function.

**Comment by dotproto** [comment]
Hm, looks like there are a couple things wrong with the snippets shared in that section. I'm updating them now to provide functional code. Long story short, though, `alert` should work.
