### ISSUE TITLE
Deprecated API functions/events are not marked as such.

### ISSUE THREAD

**Issue by karan173** [GoogleChrome/developer.chrome.com#113]
Check out https://3-72-0-dot-chrome-apps-doc.appspot.com/extensions/extension#method-sendRequest. The function is marked deprecated and the corresponding Chrome milestone is also mentioned. On the [new documentation](https://developer.chrome.com/docs/extensions/reference/extension/) however, the sendRequest function is not marked deprecated. The deprecation status can be inferred from the deprecated property in API schema files. [Example](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/extensions/api/extension.json;l=40;bpv=1;bpt=0;drc=ec6e924f84b07de2270ebc8cddfea12297dd0cd0).

**Comment by samthor** [comment]
We are emitting `@deprecated` in the d.ts files so this looks a problem with this siet.
