### ISSUE TITLE
Requesting Reopen Closed Tab Feature when R+Click on a tab

### ISSUE THREAD

**Issue by shusingh** [GoogleChrome/developer.chrome.com#1131]
**Problem**
The "Reopen Closed Tab" feature in Chrome comes in handy when you accidentally close an open tab, but I face difficulty when you have a bunch of tabs opened and you have to find a space on the Chrome Bar.

**Describe the solution you'd like**
It would be really helpful if there was an additional option of "Reopen Closed Tab" when you *right-click any tab* in the open window. This feature is currently available in the Brave browser.

**In Addition**
I am sorry if there is an option in the setting where you can turn this feature on. I don't know of this. I just wanted to point it out. It would really be helpful.

**Comment by dotproto** [comment]
This issue appears to describe a Chrome feature rather than a bug report or feature request for the developer.chrome.com repository. Please visit https://crbug.com/new to file a feature request on the Chromium project.
