### ISSUE TITLE
Native Messaging pages 404

### ISSUE THREAD

**Issue by joshuasfisher** [GoogleChrome/developer.chrome.com#114]
**Describe the bug**
When I try to read the documentation for Native Messaging for extensions, all of the pages return 404. Is this still supported?

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv2/messaging/#native-messaging
2. Click on can exchange messages, native messaging host or Native messaging links
3. See error

**Expected behavior**
I expected to be able to read this content.

**Screenshots**
![Screenshot from 2020-12-17 23-09-19](https://user-images.githubusercontent.com/43461677/102585264-f1d17f00-40bc-11eb-93aa-239dcd984702.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 87.0.4280.88

**Comment by dotproto** [comment]
Still supported, but it looks something went wrong during the migration and the extension version of that document was dropped. In the meantime, you can find the same information the apps doc set: https://developer.chrome.com/docs/apps/nativeMessaging/

**Comment by robdodson** [comment]
The 404s should be fixed now
