### ISSUE TITLE
Better Group Options - Feature Requests

### ISSUE THREAD

**Issue by ElectronEsq** [GoogleChrome/developer.chrome.com#1141]
# Better Group Options - Feature Requests

* These are not bugs.

The new group option is great, but it's feels a little pointless at times. It's too basic.
I think if the following features were included, it would really be a ground-breaking tool that really helps productivity.
```md
1. Save groups. At the moment, if you close the browser, you lose your groups and have to set them all up again.
2. Have an option to make defined URLs a permanent member of a defined/saved group.
3. Auto sort option, that when clicked, groups all current open tabs in to a group the domain is already a part of.
4. Auto sort in to groups based on predefined list of known URLs via a Google/Community lists.
5. Align closed group icons to the left (optional in settings).
6. An "End Process" right click menu option for all tabs in a group. This can be useful for managing memory issues.
```

**Comment by MichaelSolati** [comment]
@ElectronEsq what group feature are you discussing?

**Comment by samthor** [comment]
This is a feature request that should be filed on crbug.com. We're not the bug, feature or issue tracker for Chromium or Chrome in general—we're for documentation issues only.

> ⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

If you want to file a FR on the way tabs are managed in Chrome, please file on https://crbug.com.
