### ISSUE TITLE
Change numbered links to text links for /docs/webstore/faq/

### ISSUE THREAD

**Issue by AmySteam** [GoogleChrome/developer.chrome.com#1157]
Links in https://developer.chrome.com/docs/webstore/faq/ should be text links, not numeric ones. And listed at the end alphabetically.

@AmySteam will take care of this during her [CUJ CWS] project

**Comment by samthor** [comment]
To be clear it's not worth going through old files *just* to fix numbering,
but any time you interact with those old links, feel free to name them.
