### ISSUE TITLE
Error in manifest.json in the Getting Started Example

### ISSUE THREAD

**Issue by TildenWinston** [GoogleChrome/developer.chrome.com#116]
**Describe the bug**

The extension does not load properly with the manifest provided. I would expect the assignment to load, but instead it gives me an error about scripts. The manifest version can be down graded to 2, or the manifest can be changed to use the new service_worker instead of scripts and persistent.

New manifest:
```
{
    "name": "Getting Started Example",
    "version": "1.0",
    "description": "Build an Extension!",
    "permissions": ["activeTab", "declarativeContent", "storage"],
    "background": {
        "service_worker": ["background.js"]
      },
    ....
    },
    "manifest_version": 3
  }
```

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/getstarted/
3. Scroll down to https://developer.chrome.com/docs/extensions/mv3/getstarted/#background
4. See error in manifest.json

**Expected behavior**
I expect that when I load the unpackaged expansion into

**Screenshots**
![image](https://user-images.githubusercontent.com/16418557/102666040-0ad93f00-4154-11eb-9da6-fb101579ec99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 87.0.4280.88

**Comment by amitsingh-007** [comment]
I think it is throwing the error because `background.service_worker` takes a string as a value, not an array

**Comment by vapier** [comment]
the file format document also has errors related to `service_worker` as it doesn't show the example format ... it's just been left blank

https://developer.chrome.com/docs/extensions/mv3/manifest/
```
"background": {
  // Optional
  "service_worker":
},
```

**Comment by riccardomessineo** [comment]
Thus, if you manage to load it to chrome, a warning saying MV3 is not supported is shown.
That's a terrible onboarding in my opinion... :|

**Comment by zls88** [comment]
Links on this page are also broken left and right: https://developer.chrome.com/docs/extensions/mv3/getstarted/

**Comment by victorbjorn** [comment]
Just wanted to report this and broken links. I'm surprised that the official guide from Google is just a mess.

**Comment by dotproto** [comment]
@victorbjorn, in retrospect launching a new site right before the holidays may not have been the best idea 😓 .
