### ISSUE TITLE
Docs: webRequestBlocking in Manifest V3 ?

### ISSUE THREAD

**Issue by tf42src** [GoogleChrome/developer.chrome.com#1163]
I assume this [documentation](https://developer.chrome.com/docs/extensions/reference/webRequest/) is for Manifest v3. It does mention `webRequestBlocking` which when added to the manifest file results in `'webRequestBlocking' requires manifest version of 2 or lower.`

![Screen Shot 2021-08-15 at 10 51 44 am](https://user-images.githubusercontent.com/9712861/129463707-bda3b1c3-f656-4278-86c0-82f6a76bd46e.png)

**manifest.json**
```
{
    "name": "",
    "manifest_version": 3,
    ...
    "permissions": [
        ...
        "webRequest",
        "webRequestBlocking"
    ]
...
}
```

Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64)

**Comment by tf42src** [comment]
@awfuchs did you have a chance to look at it? Would be much appreciated!

**Comment by Rononoa13** [comment]
The new `declarativeNetRequestWithHostAccess` permission allows extensions to use the [chrome.declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/) API on sites the extension has host permissions for. This also enables existing Manifest V2 extensions that use `webRequest`, `webRequestBlocking`, and site-specific host permission to migrate to the [chrome.declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/) API without requiring the user to approve new permissions.

via official docs: https://developer.chrome.com/docs/extensions/whatsnew/

Does this help?

**Comment by jeffposnick** [comment]
CC: @dotproto, as I believe @awfuchs is no longer working on Chrome Extensions.

**Comment by femvc** [comment]
I try to use declarativeNetRequest to instead of webRequestBlocking.

In manifest.json
  "manifest_version": 3,
   "permissions": [
      "declarativeNetRequest",
   ]

In background.js or devtool.js 
chrome.declarativeNetRequest.updateDynamicRules({
  addRules: [{
    'id': 1001,
    'priority': 1,
    'action': {
      'type': 'block'
    },
    'condition': {
      'urlFilter': 'twitter.com',
      'resourceTypes': [
        'csp_report', 'font', 'image', 'main_frame', 'media', 'object', 'other', 'ping', 'script',
        'stylesheet', 'sub_frame', 'webbundle', 'websocket', 'webtransport', 'xmlhttprequest'
      ]
    }
  }],
  removeRuleIds: [1001]
})

**Comment by DetachHead** [comment]
> I assume this [documentation](https://developer.chrome.com/docs/extensions/reference/webRequest/) is for Manifest v3.

yeah that page doesn't mention anything about the changes in manifest v3. it needs a big red warning [like the one here](https://developer.chrome.com/docs/extensions/mv2/declare_permissions/).

**Comment by solomonkinard** [comment]
webRequest blocking for MV3 policy installed extensions is being tracked in crbug.com/1024211.

**Comment by ghostwords** [comment]
@solomonkinard I think you meant to link to a different issue.

**Comment by AmySteam** [comment]
Fixed in new [Migration guide](https://developer.chrome.com/docs/extensions/#migrate-from-manifest-v2-to-manifest-v3)
and PR's https://github.com/GoogleChrome/developer.chrome.com/pull/5473 and https://github.com/GoogleChrome/developer.chrome.com/pull/4603
