### ISSUE TITLE
support FORM elements validation state in dev tools

### ISSUE THREAD

**Issue by sashafirsov** [GoogleChrome/developer.chrome.com#1167]
When tried to utilize FORM input validated state, have not found `:invalid` and other related CSS modifiers in Dev Tools Element State panel
![image](https://user-images.githubusercontent.com/3978089/129505104-95ed0d58-f0f8-48fe-a4dc-431052ebdcbe.png)

While exploring the DOM styling I need to 
* see what validation state is applied to element. Unfortunately it is not immediately available in styles explorer, only Element property `validationMessage` and `validity` give the state info. It is quite inefficient when trying to crawl over DOM and see the FORM states. The "accessibility" tab gives some info as `invalid user entry` property which is not a much help when troubleshooting `:invalid" css states in DOM.

* mock the state for `:invalid` and other related pseudoclasses is not click-accessible. Have to use JS API instead. During styling a page/form it is not a convenient method.

**Describe the solution you'd like**
* In "Toggle Elements State" panel ^^ add the form validation pseudo classes to trigger the state.
* add the `form validation` tab or section in computed styles with checkboxes against matching pseudostyles.
* add the form state pseudo styles into css inspector panel. Seems it is not working at the moment, but needs validation, may be a bug.

**Describe alternatives you've considered**
As styling of native form fields state/fieldset/form is not easy, most are using custom classes like `.invalid` or `.error` which actually duplicating the native form elements state API and styling. 

Visual styling of constraint validation:
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Constraint_validation#visual_styling_of_constraint_validation
https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid
https://developer.mozilla.org/en-US/docs/Web/CSS/:required
...

**Comment by samthor** [comment]
Thank you for the very well-written bug; unfortunately, this is for bugs with our documentation, not a missing feature of Chrome/Chromium itself.

Please file this bug on crbug.com. (In a few minutes of quick searching, I can't seem to find an existing matching issue.)

**Comment by sashafirsov** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1240019
