### ISSUE TITLE
Document frontmatter and format for blog posts

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/developer.chrome.com#1171]
I followed links in the handbook and got to https://developer.chrome.com/docs/handbook/how-to/add-a-blog-post/, but I can't find any details on the frontmatter that required/supported for blog posts.

It leaves me having to copy-paste from a previous article and hope I'm not missing stuff.

**Comment by robdodson** [comment]
Did you clone the example post? The frontmatter is documented in there.
![image](https://user-images.githubusercontent.com/1066253/129586810-65ece143-0140-4ad2-92e7-4ca01493dd8f.png)

![image](https://user-images.githubusercontent.com/1066253/129586819-803119aa-b233-430f-afa7-5d66474f4ff2.png)

**Comment by jakearchibald** [comment]
Perfect! I'll add something to the docs for that.
