### ISSUE TITLE
Guidance on videos in articles

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/developer.chrome.com#1173]
I'm finding it hard to figure out:

- When I should use YouTube vs the media uploader.
- If I'm using the media uploader, how should I prepare the media? It seems like, unlike the image uploader, that the uploaded file is just used, so care should be taken over the size.
- If I'm using YouTube, where and how should I upload the video?

**Comment by jpmedley** [comment]
@mihajlija This seems like something the handbook should cover. Would you like to take this on?
