### ISSUE TITLE
Completed extension link in getting started is broken (no zip)

### ISSUE THREAD

**Issue by HandsomeCoder** [GoogleChrome/developer.chrome.com#118]
Most of the links related to example assets in the documentation are broken

Steps to reproduce are as follow:
- In the "[Getting Started](https://developer.chrome.com/docs/extensions/mv3/getstarted/)" section
- Click on the link given in "The completed extension can be downloaded here"

**Comment by krave1986** [comment]
And this is also broken:
[declarative API](https://developer.chrome.com/docs/extensions/events) in [this page](https://developer.chrome.com/docs/extensions/reference/declarativeContent/#rules).
