### ISSUE TITLE
Proposal: Remove requirement to manually wrap lines in markdown

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/developer.chrome.com#1183]
I think we should remove the requirement to manually line-break in markdown files.

As advocates for the web, we promote responsive design for its usability and accessibility benefits. We should allow markdown prose to adapt to the viewport width of the editor for the same reasons, offering an editing/viewing experience that  works for a range of devices and users.

GitHub used to handle diffs badly in these cases, as in it wouldn't wrap lines. This is no longer the case, the diff wraps correctly:

<img width="857" alt="Screenshot of diff view, that shows lines wrapping correctly" src="https://user-images.githubusercontent.com/93594/129690187-726f2a16-5aab-4762-8c34-8820dccf5b0d.png">

In fact, when manual wrapping is used, a single word change can look like multiple changes:

![Github showing multiple changes, but some of them are just changes to wrapping](https://user-images.githubusercontent.com/93594/129690389-8aefe89c-ae75-45da-9643-eecc3aa8f681.jpg)

In the above example, some of the highlighted changes aren't 'real' changes, they're just changes in wrapping caused by other changes. Compare to a version that doesn't enforce manual wrapping:

![](https://user-images.githubusercontent.com/93594/129690683-0ddec8e7-ba2a-4eaf-b725-abe28bd924f0.jpg)

In this case, each highlighted change is an actual change.

In https://github.com/GoogleChrome/developer.chrome.com/pull/1175#issuecomment-899676902, @jpmedley said that manual wrapping makes it easier to scope a comment in a PR. It's true that PR comments can't be more granular than a line, but GitHub's suggestion feature, or just a quote:

> like this

…makes it easy to identify part of a line. Also, we should be keeping our paragraphs pretty short for readability.

In fact, GitHub's suggestion feature becomes much harder to use when a document is manually wrapped. It's hard to identify the hard wrapping point without manually counting characters.

And that brings me onto the worst thing about manual wrapping, _it's manual_. Yes, there are tools to help, if you're working somewhere with access to those tools, but you still need to use those tools somewhat manually to ensure it's wrapping the right parts of the document. This is extra work for authors and editors with seemingly very little benefit and a load of downsides.

Can we stop it? _Edit:_ By 'it' I mean the lint rule that says we should perform manual wrapping.

**Comment by samthor** [comment]
I am happy with this proposal, can turn off the lint rules, and will add a document to /docs/handbook/ with this guidance. @robdodson might want to do the same for web.dev.

- I don't want to enforce either style; authors can wrap wherever they like (although I have preference for _sentence per line_)
- We're not going to update old files unless there's a major reason to
- Ideally we are consistent on a per-file basis, but for long files, I imagine rewrites might lead to some sections being unwrapped—that's fine but a whole section should be done at once

**Comment by jpmedley** [comment]
As explained elsewhere this limits to the point of nearly eliminating discussions about multiple changes occurring in the same feedback thread. GitHub currently has trouble with word wrap. Your choice to have your lines cut off:

![image](https://user-images.githubusercontent.com/8204171/129743499-8b56d549-169a-47e1-b205-e683adcd969c.png)

Or to use only half the available space:

![image](https://user-images.githubusercontent.com/8204171/129743565-357b9a18-e5a1-4860-871c-246fb50f6be2.png)

**Comment by jakearchibald** [comment]
@jpmedley where are you seeing that kind of wrapping? It isn't what I'm seeing in markdown PRs (see the screenshot I posted above)

**Comment by jpmedley** [comment]
>It's hard to identify the hard wrapping point without manually counting characters.

You make the hard wrap point 20 characters beyond where you actually wrap. (I use 100 and 80, but it could be 120 and 100.) They you just eyeball it. You rarely go beyond the hard wrap, and the extra space means that small changes rarely require rewrapping.

I also have a habit of selecting multiple lines when I make suggestions, rewrapping in my suggestion. Yes, it tends to show things as corrections that I didn't touch. In the vast majority of cases, those false changes are part of the sentence I touched. You should, if you're doing due diligence on my edits reread the complete sentence. 

@jakearchibald That's every MDN PR I've looked at in the last two years.

**Comment by jakearchibald** [comment]
> You make the hard wrap point 20 characters beyond where you actually wrap. (I use 100 and 80, but it could be 120 and 100.) Then you just eyeball it. You rarely go beyond the hard wrap, and the extra space means that small changes rarely require rewrapping.

This makes the process even more complicated, and harder to apply tooling to the problem.

> @jakearchibald That's every MDN PR I've looked at in the last two years.

Ah, I'm not talking about MDN, I'm talking about this repo. Can you give me an example from this repo?

**Comment by jpmedley** [comment]
>This makes the process even more complicated, and harder to apply tooling to the problem.

I don't see how.

>Ah, I'm not talking about MDN, I'm talking about this repo. Can you give me an example from this repo? (as I did)

I misspoke. It's not just MDN. As far as I can tell, it's a GitHub problem, not an MDN problem.

**Comment by jakearchibald** [comment]
> > This makes the process even more complicated, and harder to apply tooling to the problem.
> 
> I don't see how.

Because now it's even more of a manual process, as it's "eyeballed" and down to human subjectivity rather than actual rules.

> As far as I can tell, it's a GitHub problem

Can you give me a link to a PR where this happens? My understanding is that GitHub used to have an issue here but they [fixed it back in 2013](https://github.blog/2013-12-03-soft-wrapping-on-prose-diffs/). Note that I'm only proposing dropping the hard-wrapping rule for markdown.

For example, here's a link https://github.com/GoogleChrome/developer.chrome.com/pull/1175/files, but it doesn't show the problem you're describing. It seems to work rather well!

**Comment by rachelandrew** [comment]
I'm not a huge fan of breaking lines arbitrarily. However, if we turn it off, I'd love to encourage folk to use [semantic line breaks](https://sembr.org/). It's an approach that I think works well when collaborating on prose in GitHub and is essentially what I do when moving things to PR, as it's another way for me to consider each phrase while doing so.

**Comment by robdodson** [comment]
Tagging in @mihajlija because she was asking about this the other day.

**Comment by jakearchibald** [comment]
Semantic line breaks are better than column breaks, but it's still a burden on authors/editors. In fact, the rules are even more complicated. My goal with this thread was to make it easier to contribute to web.dev / developer.chrome.com, not harder.

**Comment by mihajlija** [comment]
As a writer, I also have a wrapping preference and a workflow. I'm not gonna go into that, as it just goes to show that we all have different preferences.

Many authors haven't been following the wrapping rule so far, and for me as a reviewer, resizing the window for better readability is no more of a hassle than calling out authors to enforce the wrapping rule. 

I second the downsides that Jake mentioned, incorrect diffs and eyeballing line breaks when making changes are annoying. I also agree that semantic line breaks require extra work which people are already not happy about doing. 

I support abandoning wrapping rules, as it will make the authoring process easier for many, while reviewing annoyances affect only a few of us and only sometimes.

**Comment by samthor** [comment]
We've made the changes to the reviewbot, which is what's making noise right now. Unfortunately @kaycebasques still owns it so we're getting access to deploy it. If he's MIA after a few days we can deploy it at a new Glitch project instead.

**Comment by jakearchibald** [comment]
@mihajlija I wonder if we could create a Chrome extension or something to handle the reviewing annoyances?

**Comment by samthor** [comment]
This is implemented now, and the reviewbot will no longer complain about >100 char lines.

For what it's worth, I'm not actually sure we need the external linter, and we could move this back to a proper GitHub action or something that can be run locally. But it's not broken for now and the benefit of the current approach is a giant PR comment making it very clear about other failures (not using inclusive language, for example).
