### ISSUE TITLE
chrome.scripting API needs host permissions

### ISSUE THREAD

**Issue by bangseongbeom** [GoogleChrome/developer.chrome.com#1185]
[The current chrome.scripting page](https://developer.chrome.com/docs/extensions/reference/scripting/) is saying only about `scripting` permission. But, in order to use `scripting.executeScript()` and `scripting.insertCSS()`, you need to declare host permissions also for the targets.

If not, you got an error message "Cannot access contents of the page. Extension manifest must request permission to access the respective host."

You can find the tests about `scripting.executeScript()` and `scripting.insertCSS()` without appropriate host permissions in Chromium source code:

https://github.com/chromium/chromium/blob/6644dfa666809b1727f77bf96dd934c68567802b/chrome/test/data/extensions/api_test/scripting/main_frame/manifest.json

```json
{
  "name": "Scripting API Test",
  "manifest_version": 3,
  "version": "0.1",
  "permissions": ["scripting", "tabs"],
  "background": {"service_worker": "worker.js"},
  "host_permissions": ["http://example.com/*"]
}
```

https://github.com/chromium/chromium/blob/6644dfa666809b1727f77bf96dd934c68567802b/chrome/test/data/extensions/api_test/scripting/main_frame/worker.js#L319-L337

```js
  async function disallowedPermission() {
    const query = {url: 'http://chromium.org/*'};
    let tab = await getSingleTab(query);
    const expectedTitle = 'Title Of Awesomeness';
    chrome.test.assertEq(expectedTitle, tab.title);
    await chrome.test.assertPromiseRejects(
        chrome.scripting.executeScript({
          target: {
            tabId: tab.id,
          },
          func: injectedFunction,
        }),
        `Error: Cannot access contents of url "${tab.url}". ` +
            'Extension manifest must request permission ' +
            'to access this host.');
    tab = await getSingleTab(query);
    chrome.test.assertEq(expectedTitle, tab.title);
    chrome.test.succeed();
  },
```

https://github.com/chromium/chromium/blob/e6a6223105cf1e5b05bb4530b46157824e457b51/chrome/test/data/extensions/api_test/scripting/css_injection/manifest.json

```json
{
  "name": "Scripting API Test",
  "manifest_version": 3,
  "version": "0.1",
  "permissions": ["scripting", "tabs", "webNavigation"],
  "background": {"service_worker": "worker.js"},
  "host_permissions": [
    "http://example.com/*",
    "http://subframes.example/*",
    "http://b.com/*"
  ]
}
```

https://github.com/chromium/chromium/blob/e6a6223105cf1e5b05bb4530b46157824e457b51/chrome/test/data/extensions/api_test/scripting/css_injection/worker.js#L149-L167

```js
  async function disallowedPermission() {
    const query = {url: 'http://chromium.org/*'};
    const tab = await getSingleTab(query);
    chrome.scripting.insertCSS(
        {
          target: {
            tabId: tab.id,
          },
          css: CSS_CYAN,
        },
        results => {
          chrome.test.assertLastError(
              `Cannot access contents of url "${tab.url}". ` +
                  'Extension manifest must request permission ' +
                  'to access this host.');
          chrome.test.assertEq(undefined, results);
          chrome.test.succeed();
        });
  },
```

**Comment by AmySteam** [comment]
Fixed in https://github.com/GoogleChrome/developer.chrome.com/pull/5424
