### ISSUE TITLE
[Workbox content] Automated testing

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/developer.chrome.com#1197]

**Comment by rachelandrew** [comment]
@malchata these five Workbox modules are still something we are going to do, is that right?

**Comment by malchata** [comment]
Yep, in fact, I think @jeffposnick may be developing some material of his own on this. If not, though, I have no immediate plans to work on this type of content.

**Comment by jeffposnick** [comment]
Yes, I'm planning on some written content to go along with a revamp of Workbox's integration test suite.

**Comment by rachelandrew** [comment]
Cool - just checking they were still valid issues.
