### ISSUE TITLE
Packaging page 404's

### ISSUE THREAD

**Issue by Yash-Singh1** [GoogleChrome/developer.chrome.com#121]
**Describe the bug**

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/themes/
2. Click on `packaged`
3. Page doesn't exist

**Expected behavior**

Page exists. I couldn't find a page for packaging extensions

**Screenshots**

[![Screenshot from 2020-12-20 21-58-40](https://user-images.githubusercontent.com/53054099/102744373-8c74cc80-430e-11eb-8d4b-c8b554ca74d4.png)](https://developer.chrome.com/docs/extensions/packaging/)

**Comment by samthor** [comment]
We lost this in the migration, Simeon will take a look.

**Comment by samthor** [comment]
Fixed

**Comment by elhardoum** [comment]
That URL is throwing a 404 again.

**Comment by Yash-Singh1** [comment]
It seems to be working for me: https://developer.chrome.com/docs/extensions/mv3/linux_hosting/#packaging.
