### ISSUE TITLE
public docs have a broken link to developer/dashboard.

### ISSUE THREAD

**Issue by SimplGy** [GoogleChrome/developer.chrome.com#122]
**Describe the bug**

public docs have a broken link to developer/dashboard.

Later in the page, the link works. I think the trailing slash is the problem.

https://screenshot.googleplex.com/7xiDSHWxPGg5RVe

**Comment by SimplGy** [comment]
page url: https://developer.chrome.com/docs/extensions/mv3/hosting/

**Comment by robdodson** [comment]
I think this should be fixed now
