### ISSUE TITLE
Document test flow for adding new permissions to an extension

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#1239]
**Is your feature request related to a problem? Please describe.**
The [Declare permissions and warn users](https://developer.chrome.com/docs/extensions/mv3/permission_warnings) page does not include instructions on how to emulate permissions upgrades

**Describe the solution you'd like**
As a developer, I want to understand how to test what happens when I add new permissions to my extension.

**Describe alternatives you've considered**
At the moment the most obvious way to test new permissions is to publish an update to the beta version of my extension in CWS, wait for it to get approved, and eventually download it on my machine. This flow is not well suited to the typical development iteration flow.

**Additional context**
The page contains information on how to [view permissions warnings](https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#view_warnings), but does not follow that information up by showing that you can modify the permissions, change the version number, and repeat the same process to see upgrade permission prompts.

**Comment by oliverdunk** [comment]
We now have a section on this including manual testing and the update testing tool: https://developer.chrome.com/docs/extensions/develop/concepts/permission-warnings#update_permissions
