### ISSUE TITLE
Chore: Make sure the CWS violation troubleshooting guide has up-to-date policy snippets

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#1240]
The CWS developer program policy has been updated at least once since the Troubleshooting guide was first published. For the sake of providing developers with clear, accurate, actionable guidance, we should ensure that the policy snippets included in the [Troubleshooting guide](https://developer.chrome.com/docs/webstore/troubleshooting/) match the text in the program policies page itself.

Longer term, we may want to consider ways to automate this work.

**Comment by dstmarthe** [comment]
I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312792661
