### ISSUE TITLE
JavaScript debugging reference: "Step" not documented

### ISSUE THREAD

**Issue by Chealer** [GoogleChrome/developer.chrome.com#1248]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
[The _Step through code_ section of the _JavaScript debugging reference_](https://developer.chrome.com/docs/devtools/javascript/reference/#stepping) once documented the various stepping functions of Chromium DevTools. This documentation is unfortunately no longer complete following [the introduction of a _Step_ (period) variant in Chromium 65](https://developer.chrome.com/blog/new-in-devtools-65/#stepping).

Beyond obviously adding documentation for the new variant, presumably the documentation for existing ones should also be updated, as the release notes indicate that an existing variant's effect changed.

**To Reproduce**
Steps to reproduce the behavior: This does not report a behavioral bug.

**Expected behavior**
This does not report a behavioral bug.

**Desktop (please complete the following information):**
This does not report a behavioral bug.

**Smartphone (please complete the following information):**
This does not report a behavioral bug.

**Additional context**
Note that the _Stepping into asynchronous code_ section of the release notes linked above is fairly broken, as the 2 captures are in fact the same.

While I am reporting this as a documentation issue, this can certainly be considered from a wider perspective. Labeling the new button just _Step_ certainly creates ambiguity, and it should have a tooltip in any case.

**Comment by Chealer** [comment]
Indeed, the documented _Step over line of code_ no longer exists, replaced with _Step over next function call_.

**Comment by dstmarthe** [comment]
I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312784428
