### ISSUE TITLE
Add support for anchor redirects

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#1249]
**Is your feature request related to a problem? Please describe.**
The Chrome Web Store FAQ is filled with miscellaneous information. As we continue to expand and update Chrome Web Store documentation, we are occasionally identifying FAQ entries that would be better addressed in a more specific page. When migrating a section from one page to another, we would also like to create a redirect to migrate links that point to an element ID in the FAQ to the new page.

For example, I want to redirect https://developer.chrome.com/docs/webstore/faq/#how-can-i-raise-p2b-concerns to https://developer.chrome.com/docs/webstore/complaint-faq/.

We cannot use [redirects.yaml](https://github.com/GoogleChrome/developer.chrome.com/blob/main/redirects.yaml) for this because fragment identifiers aren't sent to the server when navigating to a URL that contains a fragment identifier. As such, in order to support anchor redirects, we would need to implement client side redirects for fragment identifiers.

**Describe the solution you'd like**
Page authors should be able to declare anchor redirects using one of the following options: redirect declarations in redirects.yaml or in a page's frontmatter. 

Regardless of which approach is used to declare the redirects, the set of redirects for a given page will need to be exposed in a page script. The below snippet is a first attempt at a page script that redirects anchor links both on initial page load and when the user follows internal page links to a redirected header.

```js
// Map of page-specific redirects populated from either the page's YAML
// frontmatter or declarations in redirects.yaml
let pageHashRedirects = {};

// Execute eagerly in order minimize navigation time
handleHashRedirect(window.location.href);

// Handle links inside the page that point to redirected anchors
window.addEventListener('hashchange', (event) => handleHashRedirect(event.newURL));

// Given a URL (assumed to be the current page) with an optional hash, redirect
// navigation to another URL
function handleHashRedirect(targetURL) {
  let {hash} = new URL(targetURL);
  if (pageHashRedirects[hash]) {
    window.location.replace(pageHashRedirects[hash]);
  }
}
```

**Comment by jpmedley** [comment]
@devnook We are about to land an update to our getting started doc that could really use this. Any chance of implementing this soon?
