### ISSUE TITLE
Update the Manifest V3 migration guide to more clearly state how webRequest is changing

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#1263]
**Describe the bug**
The  [Manifest V3 migration guide](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#when-use-blocking-webrequest)'s description of the changes to the webRequest API in Manifest V3 is a little confusing. The current text implies that the webRequest API is only available when force installed, does not note that the observational capabilities of the API remain, and does not comment on the `webRequestBlocking` permission.

This description should be updated to more clearly state how webRequest works in Manifest V3.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#when-use-blocking-webrequest
2. Read the description of how this API is changing in Manifest V3
3. Based on this information, attempt to answer the following questions

- Can standard extensions use webRequest to monitor network requests?
- Can standard extensions use webRequest to modify network requests?

**Expected behavior**
The text should clearly indicate that non-force installed extensions can use webRequest to observe network requests, but only force-installed Manifest V3 extensions can use the webRequestBlocking permission to modify network requests. This section should also explain how a Manifest V3 extensions that tries to use webRequestBlocking to modify network requests will behave.

**Additional context**
I was specifically looking at our migration guidance, but we should also take a look at the webRequest API docs to make sure they clearly communicate what's different between Manifest V2 and Manifest V3 extensions.

**Comment by tophf** [comment]
It should also say in a huge bright yellow plaque that currently webRequest is unusable for most practical purposes in a service worker as it won't wake up for webRequest listeners. And judging by https://crbug.com/1024211 it's even unclear if this is actually fixable...

**Comment by DetachHead** [comment]
there is also no mention of these changes on the [`webRequest`](https://developer.chrome.com/docs/extensions/reference/webRequest/) page.

there should be a big red warning [like the one here](https://developer.chrome.com/docs/extensions/mv2/declare_permissions/)

**Comment by AmySteam** [comment]
Fixed in new [Migration guide](https://developer.chrome.com/docs/extensions/#migrate-from-manifest-v2-to-manifest-v3)
and PR's https://github.com/GoogleChrome/developer.chrome.com/pull/5473 and https://github.com/GoogleChrome/developer.chrome.com/pull/4603
