### ISSUE TITLE
View and search for translated blog posts

### ISSUE THREAD

**Issue by chybie** [GoogleChrome/developer.chrome.com#1267]
**Is your feature request related to a problem? Please describe.**
Not able to view or search translated blog posts. 

**Describe the solution you'd like**
An easy way to view and search translated bog posts.

**Comment by chybie** [comment]
tested with Russian and Chinese. Both works now. Guess it's fixed with previous PR on localized blog list page.

**Comment by samthor** [comment]
It's worth noting that on web.dev, we also include the English text in any indexed article that is not in English.

The idea is that if you're in e.g., PT but can't find any articles, it will _also_ include the English too.
I don't nessecarily think this is the right idea, it depend on how much coverage we can get, just documenting how it's done.
