### ISSUE TITLE
sidebar TOC should always expand by default

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#128]
whenever you're looking at a page with multiple sections, there's a "Table of Contents" widget on the right side.  but it's easy to miss in its (default) collapsed state, and you have to manually click it to expand.  considering that space is never used for anything else, it really should be expanded by default if not all the time.

for example, visit https://developer.chrome.com/docs/extensions/reference/ and look at the RHS for the TOC widget.

**Comment by robdodson** [comment]
I'd be ok making this change. I think we'd want the desktop one to be open, but the mobile one to be collapsed.
