### ISSUE TITLE
lots of broken links to extension APIs

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#129]
this page:
https://developer.chrome.com/docs/extensions/mv3/manifest/event_rules/

has broken links to declarativeWebRequest & declarativeContent.  searching the site, we have a lot of these.  is the plan to fix them or add redirects or something else ?

just grepping the tree shows these ... i cut the results since there's so many ;)

/docs/extensions/activeTab
/docs/extensions/alarms
/docs/extensions/api_index
/docs/extensions/app_external
/docs/extensions/app_lifecycle
/docs/extensions/autoupdate
/docs/extensions/bookmarks
/docs/extensions/branding
/docs/extensions/browserAction
/docs/extensions/browsingData
/docs/extensions/certificateProvider
/docs/extensions/contentSettings
/docs/extensions/contextMenus
/docs/extensions/cookies
/docs/extensions/debugger
/docs/extensions/declarativeContent
/docs/extensions/declaratively
/docs/extensions/declarativenetrequest
/docs/extensions/declarativeNetRequest
/docs/extensions/declarativeWebRequest
/docs/extensions/desktopCapture
/docs/extensions/displaySource
/docs/extensions/dns
/docs/extensions/documentScan
/docs/extensions/downloads
/docs/extensions/enterprise.deviceAttributes
/docs/extensions/enterprise.hardwarePlatform
/docs/extensions/enterprise.networkingAttributes
/docs/extensions/enterprise.platformKeys
/docs/extensions/enterprise_platformKeys
/docs/extensions/events
/docs/extensions/experimental
/docs/extensions/extension
/docs/extensions/extensions/manifest
/docs/extensions/fileSystemProvider
/docs/extensions/fontSettings
/docs/extensions/gcm
/docs/extensions/history
...

**Comment by samthor** [comment]
We should look for 404s in that folder and send them to ./reference/X. We can do that.

**Comment by robdodson** [comment]
I think these should all be fixed now
