### ISSUE TITLE
The `update_url` field of Chrome Extensions should have been deprecated. 

### ISSUE THREAD

**Issue by iam-frankqiu** [GoogleChrome/developer.chrome.com#132]
**Describe the bug**
The `update_url` field of Chrome Extensions should have been deprecated. But it still exists on the Chrome Extensions manifest page. 

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/mv3/manifest/'
2. Scroll down to the bottom of the page.
3. See the `update_url` field.

**Expected behavior**
The `update_url` field shouldn't exist on the Chrome Extensions manifest page.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Catalina 10.15.6
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 86.0.4240.198

**Comment by dotproto** [comment]
This field is still relevant for "self hosted extensions" – extensions that are hosted outside of the Chrome Web Store. While use of this capability is limited, it's not deprecated.

**Comment by iam-frankqiu** [comment]
> This field is still relevant for "self hosted extensions" – extensions that are hosted outside of the Chrome Web Store. While use of this capability is limited, it's not deprecated.

It will be better if add some remarks to the document.

**Comment by dotproto** [comment]
@iam-frankqiu Agreed. It also seems the update URL document is missing. I just opened #163 for that page & called out the need to better describe where & when this property should be specified.
