### ISSUE TITLE
Dead links on the Getting Started page

### ISSUE THREAD

**Issue by MMK21Hub** [GoogleChrome/developer.chrome.com#134]
**Describe the bug**
<https://developer.chrome.com/docs/extensions/mv3/getstarted/> is full of links to download stuff, but they all 404.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the [finished extention](https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started_complete.zip)
    - ❌ 404
2. Go to the [icons set](https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/images.zip)
    - ❌ 404

**Expected behaviour**
Well, I'd have been able to download the zipfile. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87

**Comment by avm99963** [comment]
Thanks for reporting! This seems like a duplicate of #60.

**Comment by MMK21Hub** [comment]
oops
