### ISSUE TITLE
Please re-test these steps

### ISSUE THREAD

**Issue by msampathkumar** [GoogleChrome/developer.chrome.com#1341]
Issues
- I see the icon links are not working
- instructions to update chrome extensions are not working(outdated ?)

Request: Please retest these steps. Thank you for the articles & explanation included!

⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AmySteam** [comment]
Hi @msampathkumar . Can you include the link to the docs where the icon links are not working? Also which specific instruction to update chrome extensions is not working? Thanks!

**Comment by msampathkumar** [comment]
Hi @AmySteam 

URL Issue
- Open https://developer.chrome.com/docs/extensions/mv2/getstarted/#background
- With the Page - Search for: `downloading it here, and placing it inside the extension directory.`
- Click the the url link attached to `here` keyword

Last week when I check I think I had troubles with instructions(did not feel updated), links to Icons & other url links like above were not working! Now when I check, now they seem to be fine.  Sorry for the trouble, please just fix above link!

**Comment by AmySteam** [comment]
@msampathkumar Good catch on the MV2 docs for getting started! Have you tried following the [MV3 getting started](https://developer.chrome.com/docs/extensions/mv3/getstarted/) yet? 😃 

> Now when I check, now they seem to be fine. Sorry for the trouble & please just look for above link!

No trouble, feedback is always welcome! 👍
