### ISSUE TITLE
Error in Google Chrome Webstore 404 title

### ISSUE THREAD

**Issue by cheparsky** [GoogleChrome/developer.chrome.com#1344]
When I go to the webpage https://chrome.google.com/webstore/detail/appspector/homgcnaoacgigpkkljjjekpignblkeae?hl=en I see 404 error - it is OK (I think so), but title of page is: _Error 404 (Not Found)!!1_, with the 1 on the end, what I think is potential error and it should be changed to ! -> _Error 404 (Not Found)!!!_

Error was found on Brave 1.29.77 and reproduced on Microsoft Edge 93.0.961.38

![image](https://user-images.githubusercontent.com/47715790/132116935-bb7ceaee-d286-40cf-84b3-4e8ddd6489e0.png)

**Comment by jpmedley** [comment]
Thank you for submitting this. Unfortunately, this is not the place to report issues with that particular web site. [Go here](https://support.google.com/chrome/?hl=en&rd=3#topic=7438008). Scroll to the bottom of the page and click "Send feedback about our Help Center".
