### ISSUE TITLE
Can't pay developer registration fee to create chrome developer account.

### ISSUE THREAD

**Issue by HashamSabir** [GoogleChrome/developer.chrome.com#1347]
Can't pay developer registration fee to create chrome developer account.
⚠️
I tried different cards (VISA/union-pay) even different locations (Pakistan/UK) but nothing worked.

**To Reproduce**
1. Go to 'https://chrome.google.com/webstore/devconsole/register'
2. Click on 'try to pay registration fee for developer account'
3. The payment will not proceed and get an error.

**Expected behavior**
After successful payment deduction, chrome developer account should be created .

**Comment by jpmedley** [comment]
Thank you for submitting this. Unfortunately, this is not the place to report issues with that particular web site. [Go here](https://support.google.com/chrome/?hl=en&rd=3#topic=7438008). Scroll to the bottom of the page and click "Send feedback about our Help Center".
