### ISSUE TITLE
Quota limits for chrome.storage are missing

### ISSUE THREAD

**Issue by tophf** [GoogleChrome/developer.chrome.com#135]
https://developer.chrome.com/docs/extensions/reference/storage/#property-sync is missing the quota limits, [previously present](https://3-72-0-dot-chrome-apps-doc.appspot.com/extensions/storage#properties):

### chrome.storage.sync

Items in the sync storage area are synced using Chrome Sync.

Number | Name | Description
-|-|-
102,400 | QUOTA_BYTES | The maximum total amount (in bytes) of data that can be stored in sync storage, as measured by the JSON stringification of every value plus every key's length. Updates that would cause this limit to be exceeded fail immediately and set runtime.lastError.
8,192 | QUOTA_BYTES_PER_ITEM | The maximum size (in bytes) of each individual item in sync storage, as measured by the JSON stringification of its value plus its key length. Updates containing items larger than this limit will fail immediately and set runtime.lastError.
512 | MAX_ITEMS | The maximum number of items that can be stored in sync storage. Updates that would cause this limit to be exceeded will fail immediately and set runtime.lastError.
1,800 | MAX_WRITE_OPERATIONS_PER_HOUR | The maximum number of set, remove, or clear operations that can be performed each hour. This is 1 every 2 seconds, a lower ceiling than the short term higher writes-per-minute limit. Updates that would cause this limit to be exceeded fail immediately and set runtime.lastError.
120 | MAX_WRITE_OPERATIONS_PER_MINUTE | Since Chrome 40. The maximum number of set, remove, or clear operations that can be performed each minute. This is 2 per second, providing higher throughput than writes-per-hour over a shorter period of time. Updates that would cause this limit to be exceeded fail immediately and set runtime.lastError.
1,000,000 | MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE | Deprecated since Chrome 40. The storage.sync API no longer has a sustained write operation

### chrome.storage.local

Items in the local storage area are local to each machine.

Number | Name | Description
-- | -- | --
5,242,880 | QUOTA_BYTES | The maximum amount (in bytes) of data that can be stored in local storage, as measured by the JSON stringification of every value plus every key's length. This value will be ignored if the extension has the unlimitedStorage permission. Updates that would cause this limit to be exceeded fail immediately and set runtime.lastError.

### chrome.storage.managed

Items in the managed storage area are set by the domain administrator, and are read-only for the extension; trying to modify this namespace results in an error.

**Comment by dotproto** [comment]
Thanks for the report. I'm not sure how that information got lost in the migration.

**Comment by samthor** [comment]
This is the same as #110.
