### ISSUE TITLE
A possible need to correct MV3's Manifest Sandbox page

### ISSUE THREAD

**Issue by avi12** [GoogleChrome/developer.chrome.com#1351]
In the [Manifest v3 - Sandbox](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/extensions/mv3/manifest/sandbox/index.md) page, the value of `content_security_policy` (string) does not follow the [actual value that is expected](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#content-security-policy), a dictionary that looks like:
```json
{
  "content_security_policy": {
    "sandbox": "..."
  }
}
```
In addition, the mentioned [default value](https://developer.chrome.com/docs/extensions/mv3/manifest/sandbox/#:~:text=the%20default%20content_security_policy%20value) should possibly be corrected as well.

**Comment by ajain-bst** [comment]
In addition, the example seems to not be working:
the example is given as:
```
{
  ...
  "content_security_policy": {
    "sandbox": "sandbox allow-scripts; script-src 'self' https://example.com"
  },
  "sandbox": {
    "pages": [
      "page1.html",
      "directory/page2.html"
    ]
  },
  ...
}
```

But when you actually try this, the browser issues an error:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/37684378/186415960-c939c158-9534-4ab1-bb5e-0ed850093667.png">

Or is it me who is doing something incorrectly?

**Comment by dstmarthe** [comment]
Can this can be closed? @ajain-bst did you include the code examples surrounding the example you mentioned?
The three dots "..." means that the code block is a snippet of a larger part.

**Comment by oliverdunk** [comment]
We've updated the structure here, but it looks like we still need to remove example.com.

**Comment by dstmarthe** [comment]
I've moved this issue to the new tracker here: https://issuetracker.google.com/issues/324483263
