### ISSUE TITLE
/getstarted.html should be a redirect

### ISSUE THREAD

**Issue by sumitbhagwani** [GoogleChrome/developer.chrome.com#137]
**Describe the bug**
Open the website https://developer.chrome.com/getstarted.html and see a 404 error message 

**To Reproduce**
1. Go to https://developer.chrome.com/getstarted.html
2. See error

**Expected behavior**
Page should load without any 404 error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios
 - Browser : chrome 
 - Version : 87.0.4280.88 (Official Build) (x86_64)

<img width="1673" alt="Screen Shot 2020-12-26 at 4 01 08 PM" src="https://user-images.githubusercontent.com/995649/103161251-d25ce500-4793-11eb-9c4e-cba92b8bc99c.png">

**Comment by dotproto** [comment]
https://developer.chrome.com/getstarted.html is not a valid URL for the new site and I don't believe it worked on the old one either. Where did you find this link?

**Comment by robdodson** [comment]
@sumitbhagwani I'm going to close the issue but happy to reopen if you can share where you go the original link that ended in .html
