### ISSUE TITLE
Suggest cloning into users organization fork instead of remote/upstream repository

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/developer.chrome.com#1385]
**Describe the bug**
The README suggests we clone the remote repository: 

```bash
git clone https://github.com/GoogleChrome/developer.chrome.com.git
```

but if we fork the repository to our own user organization, clone the remote repo as shown above, and then perform some git tasks. Like creating a branch, committing changes and pushing those branches changes to `origin`, we will see permission denied. To avoid this, the user should `git clone <URL_TO_USERS_FORK>` so then their `origin` is tracking their local copy of the project and they can use `git remote add upstream https://github.com/GoogleChrome/developer.chrome.com.git` to add the remote repo as an "upstream" for any fetching or pulling to sync with the latest changes.

**To Reproduce**
1. Fork this repository
2. Clone using the URL provided in README.md e.g. git clone https://github.com/GoogleChrome/developer.chrome.com.git
3. Create a new branch, `git checkout -b 123-demo`
4. Make some changes and commit them - `git commit -S -m "some commit"`
5. Push changes to `origin` (which will be the remote repository that we cloned from) - `git push origin 123-demo`
4. See access denied error

**Expected behavior**
I expected the cloning suggestions to recommend cloning the SSH URL of our users local fork of the project `git clone https://github.com/@<username>/developer.chrome.com.git` instead of the remote repository (https://github.com/GoogleChrome/developer.chrome.com.git). 

I say this because if we clone the remote repo SSH URL like suggested, that means our `origin` will be the remote repository and not our users organization fork ie `https:://github.com/tannerdolby/developer.chrome.com`. That means pushing to `origin` will most likely result in permission errors. 

Therefore having to remove `origin` as a remote with `git remote rm origin` and then add our users fork as the new origin `git remote add origin git@github.com:tannerdolby/developer.chrome.com.git` when all of this could have been handled from the get-go by simply cloning our users fork instead of the upstream repo.

**Screenshots**
<img width="803" alt="Screen Shot 2021-09-11 at 1 10 40 AM" src="https://user-images.githubusercontent.com/48612525/132941430-f0f5a483-abe7-4c50-93ca-1c7bd10e9b59.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [92]

**Comment by samthor** [comment]
I appreciate the long report but I think this can be summed up or fixed by adding a line under "Clone the repo" in the README which says...

"⚠️ If you'd like to contribute (and you're not a member of the core team), be sure to fork the repo first, and clone the fork."

Or even removing this section, since most projects don't say this at all.

If you'd like to send a PR adding that line, I'll accept it.

**Comment by tannerdolby** [comment]
Ok that works for me. I will submit a PR adding that line, thanks!
