### ISSUE TITLE
[devtools-translate] duplicated url in the latest blog (94)

### ISSUE THREAD

**Issue by TORU0239** [GoogleChrome/developer.chrome.com#1391]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Users can't navigate to the translated page links when they click the links (Both Portuguese and Spanish)

**To Reproduce**
1. Go to the latest article (94)
2. Click on 'Español', or 'Português' 
3. See error that it redirects to the current webpage itself

**Expected behavior**
1. User should be able to be redirected to see the translated blog.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 92

**Additional context**
The inserted links are wrong, so it have to be replaced correctly.

**Comment by samthor** [comment]
Thanks for the bug! We fixed this about the same time as you found this.
