### ISSUE TITLE
Chrome WebStore search not returning any results byr any search

### ISSUE THREAD

**Issue by mhauzirek** [GoogleChrome/developer.chrome.com#1392]
**Describe the bug**
The search functionality in Google Chrome Web Store no longer works. No matter what term is searched, no results are returned.

**To Reproduce**
1. Go to https://chrome.google.com/webstore/
2. Write anything (i.e. "keep") to the "Search the store" field
3. Press enter
4. See the search result display: 'No results for "keep" Make sure all words are spelled correctly, or try a different search.'

**Expected behavior**
Extensions / themes matching the search term are displayed. (In case of searching "keep" at least the "Google Keep Chrome Extension" should be found).

**Screenshots**
(attached)
![image](https://user-images.githubusercontent.com/1830015/132981507-537e5130-569b-4825-99e5-cd85d664c76f.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 92.0

Also replicated on completely different computer and profile with Windows 10 in chrome.
Also replicated in incognito mode without any extensions.

**Additional context**
I've been noticing this behavior for a few days now. Before it for sure worked.

**Comment by samthor** [comment]
<img width="842" alt="Screen Shot 2021-09-13 at 16 22 45" src="https://user-images.githubusercontent.com/119184/133033752-1a7bf8cb-9531-44e2-8f18-ad2693557e27.png">

This isn't really the issue tracker for the Chrome Web Store but I appreciate that something was broken for you. I can't repro this though.
