### ISSUE TITLE
Manifest v3 host permissions haven't shipped

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#140]
i don't understand why we're pushing manifest v3 & its updated permission model when it hasn't shipped yet.

the guide says to move host settings from `permissions` to `host_permissions`:
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#host-permissions

but when you try that, Chrome rejects it:
`'host_permissions' requires dev channel or newer, but this is the beta channel.`

i'm running Chrome 88.0.4324.37 (Official Build) beta (64-bit) here.  i don't know if things are better in R89, but that isn't hitting beta channel until Jan 28th at the earliest.  so telling extension authors to use functionality that requires ToT Chrome versions (assuming it's even available there now) when uploading extensions to the CWS seems inadvisable.

**Comment by dotproto** [comment]
This doesn't appear to be a documentation bug. Rather, I think the underlying issue here is that we had several capabilities related to MV3 flagged to be exposed in Canary, but not in Beta. The current M88 beta _should_ allow you to use the `host–permissions` field in your extension. I've opened a bug on the chromium project for this issue: crbug.com/1162860

**Comment by vapier** [comment]
there is certainly a bug in the documentation if we're telling extension authors to use functionality that isn't widely available, and we don't warn them as to the general availability of said features.  normally the docs call out the specific version when the feature shipped in stable channel, and highlight things that are restricted to channels before that.  these docs do neither.

mv3 is clearly not ready for people to use in their extensions beyond early experimentation.  yet the mv3 docs make no mention of any of this.

**Comment by dotproto** [comment]
I agree with the concerns you're rasing, @vapier. Compounding this is the fact that shortly before holiday break we shipped it change that made the MV3 doc set the default set of docs that developers see. That was a mistake and I will jump on it shortly (#164).

I'm going to reopen this issue for the moment as the feedback you raised touches on other issues that I'm not quite sure how to break down into actionable tasks at the moment.

**Comment by jpmedley** [comment]
Manifest V3 has been around for a few years now. I don't think this is an issue any more.
