### ISSUE TITLE
Document how to get content script work with optional permissions

### ISSUE THREAD

**Issue by pd4d10** [GoogleChrome/developer.chrome.com#1414]
Not quite sure if it is a bug with Chromium, so submit it here for further confirmation

**Describe the bug**

Try to work with optional permissions following [this guide](https://developer.chrome.com/docs/extensions/reference/permissions/#step-2-declare-optional-permissions-in-the-manifest), but it seems not work

**To Reproduce**
1. Create a `manifest.json` file as follows, and two empty files `background.js` and `content-script.js`:
```json
{
  "manifest_version": 3,
  "name": "test",
  "version": "0.0.1",
  "host_permissions": ["https://*/"],
  "background": {
    "service_worker": "background.js"
  },
  "content_scripts": [
    {
      "matches": [
        "https://github.com/*",
      ],
      "js": ["content-script.js"]
    }
  ]
}
```
2. Open the devtools of background service worker, and run 

```js
chrome.permissions.getAll(({ origins }) => {
  console.log(origins) // ['https://*/*', 'https://github.com/*']
  chrome.permissions.request({ origins: ['https://www.google.com/*'] }, (granted) => {
    // Click allow with the popup
    console.log(granted) // true
    chrome.permissions.getAll(({ origins }) => {
      console.log(origins) // ['https://*/*', 'https://github.com/*']
    })
  })
})
```

After doing this, the content script still doesn't work with `https://www.google.com`

**Expected behavior**
The content script should work with `https://www.google.com` after permissions granted

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 93.0.4577.63

**Comment by tophf** [comment]
Indeed, such an article will be useful. Currently optional permissions aren't implemented in MV3, but it will have all permissions optional by default in the future. When it happens we will probably do essentially the same thing we were doing in MV2: listen to chrome.permissions.onAdded and register a new content script. In MV2 it was chrome.declarativeContent + RequestContentScript action, in MV3 it'll be chrome.scripting API once https://crbug.com/1054624 is fixed.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312790946
