### ISSUE TITLE
Image asset not found on 'docs/devtools/dom/' page

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/developer.chrome.com#1447]
**Describe the bug**
The "Inspect" icon isn't being displayed.

Invalid image `src`: https://developer.chrome.com/web/tools/chrome-devtools/images/shared/inspect.png

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/devtools/dom/'
2. Scroll down to 'https://developer.chrome.com/docs/devtools/dom/#inspect'
3. Scroll down a bit more to where it says "Click the Inspect icon in the top-left corner of DevTools."

**Expected behavior**
For the `inspect.png` image asset to load and display on the page.

**Screenshots**
<img width="1032" alt="Screen Shot 2021-09-16 at 10 53 38 PM" src="https://user-images.githubusercontent.com/48612525/133732613-b7b6688b-98b3-41ac-8869-68cedd675852.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [92]

**Additional context**
I couldn't find anywhere where `inspect.png` existed in the codebase using git grep and vs codes search, maybe this asset no longer exists at all in the project? I did see an `{% Img .. %}` shortcode being used in other templates to display images but it seemed this was mostly used for larger images and not icons.

L38-42 in `docs/devtools/dom/index.md`
```
[inspect]: /web/tools/chrome-devtools/images/shared/inspect.png

1. Click the **Inspect** ![Inspect][inspect]{: .inline-icon } icon in the top-left corner of
   DevTools.
```

**Comment by devnook** [comment]
This is fixed now.
