### ISSUE TITLE
Various extension/app APIs are missing from the API reference

### ISSUE THREAD

**Issue by mlcui-google** [GoogleChrome/developer.chrome.com#149]
A diff of the old site via archive.org and the new one shows some APIs missing from the new site:

- [x] idle
- [ ] networking.config
- [x] tabGroups
- [x] browser (app only)
- [x] mediaGalleries (app only) - see #148
- [x] serial (app only)
- [x] socket (app only)
- [x] syncFileSystem (app only)

**Comment by dotproto** [comment]
Whoops, misread this issue & thought it was fixed by PR #151. Reopening.

**Comment by samthor** [comment]
This also include tabGroups.

**Comment by robdodson** [comment]
@samthor is this still an issue now that #225 has been merged?

**Comment by samthor** [comment]
This will be fixed shortly with an update to `chrome-types`. However, `networking.config` was just a blank page so we won't bring it across.
