### ISSUE TITLE
This website has to be verified and to make me access my documents database

### ISSUE THREAD

**Issue by joshbrandy** [GoogleChrome/developer.chrome.com#1515]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jpmedley** [comment]
I don't see a bug described here. Please provide more information.

**Comment by samthor** [comment]
This is spam.
