### ISSUE TITLE
the new API for favicon

### ISSUE THREAD

**Issue by Benbinbin** [GoogleChrome/developer.chrome.com#1541]
**Is your feature request related to a problem? Please describe.**
Refer to the [documentation](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#other-features) updated at [November 9, 2020](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/), a new api for favicon, it's already provided?

**Describe the solution you'd like**
If a new API for favicon already provided or not? I can use 'chrome://favicons' to get some website favicon in manifest V2, but after I upgrade to manifest V3 this method don't work.

**Describe alternatives you've considered**
If a new API for favicon already provided, update the documentation maybe help the developers a lot.

**Additional context**

**Comment by tannerdolby** [comment]
<img width="670" alt="Screen Shot 2021-10-03 at 9 12 55 PM" src="https://user-images.githubusercontent.com/48612525/135792713-25024ac3-eeee-4399-8334-12450ed79b6f.png">

 _Screenshot from https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#other-features_

The above is referring to the [Scripting API](https://developer.chrome.com/docs/extensions/reference/scripting/) in MV3 which can be used via `chrome.scripting`. You can read more about the Scripting API introduced in MV3 here - [Chrome Blog - Scripting API](https://developer.chrome.com/blog/crx-scripting-api/)

However, I do agree that maybe having atleast one link on [/mv3/intro/mv3-overview/](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#other-features) to the [chrome.scripting](https://developer.chrome.com/docs/extensions/reference/scripting/) API reference would be nice.

**Comment by myakura** [comment]
looks like there's no such new API yet.
https://bugs.chromium.org/p/chromium/issues/detail?id=104102

**Comment by tannerdolby** [comment]
ya, looks like your right. thanks for sharing the chromium bug issue link!

**Comment by ligdy7** [comment]
There seems to be no good way now

**Comment by Code-Victor** [comment]
I think this should help out
https://developer.chrome.com/docs/extensions/mv3/favicon/

**Comment by Benbinbin** [comment]
> I think this should help out https://developer.chrome.com/docs/extensions/mv3/favicon/

Thx
