### ISSUE TITLE
Broken Links on https://developer.chrome.com/docs/extensions/mv3/manifest/

### ISSUE THREAD

**Issue by dkokic** [GoogleChrome/developer.chrome.com#155]
**Describe the bug**
Broken links in the documentation of the manifest.json v3 schema.

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/mv3/manifest/'
2. Click on 'background'

**Expected behaviour**
Documentation of the 'background' property.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robdodson** [comment]
I think this is fixed with the exception of `chrome_url_overrides` which tries to link to /overrides and I'm not sure where it's actually supposed to go. Assigning to @dotproto
