### ISSUE TITLE
TOC layout looks broken

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/developer.chrome.com#1554]
**Describe the bug**
TOC layout looks broken

**To Reproduce**
1. Go to https://developer.chrome.com/blog/chromium-chronicle-25/
2. Scroll down to the bottom
4. The TOC appears at the bottom left corner with no margins

**Screenshots**

![Screenshot 2021-10-06 at 17 36 42](https://user-images.githubusercontent.com/17127567/136236610-af44e5b7-eef9-42f2-976c-5309f532e889.png)

**Comment by tannerdolby** [comment]
So that sidebar ToC is only appearing for viewport widths greater than 1440px (on chrome)
