### ISSUE TITLE
The Declarative Content API Rules sample not working after quit Chrome

### ISSUE THREAD

**Issue by sytranvn** [GoogleChrome/developer.chrome.com#1564]
**Describe the bug**
Extension cannot change status after quit chrome.
I followed [this sample](https://developer.chrome.com/docs/extensions/reference/declarativeContent/#rules) but it only works the first time I install the extension. After quitting Chrome, extension stays active and never be disabled.

**To Reproduce**
1. Install extension
2. Go to https://developer.chrome.com/
3. Observe extension is enabled 
4. Go to other tab
5. Observe extension is disabled
6. From menu click Chrome -> Quit Google Chrome 
7. Open Google Chrome
8. Repeat step 2 to 5

**Expected behavior**
Extension should be enabled and disabled based on matching rule.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google chrome / Brave
 - Version 94.0.4606.71 /  94.0.4606.71 

**Additional context**

```json
// manifest.json
{
  "manifest_version": 3,
  "name": "Sample Ext",
  "version": "1.0.1",
  "description": "Sample extension",
  "icons": {
    "16": "/icon_16.png"
  },
  "action": {
    "default_title": "Sample Ext",
    "default_popup": "popup.html"
  },
  "background": { "service_worker": "/background.js" },
  "permissions": ["declarativeContent"]
}
```
```js
// background.js

// Wrap in an onInstalled callback in order to avoid unnecessary work
// every time the background script is run
chrome.runtime.onInstalled.addListener(() => {
  // Page actions are disabled by default and enabled on select tabs
  chrome.action.disable();

  // Clear all rules to ensure only our expected rules are set
  chrome.declarativeContent.onPageChanged.removeRules(undefined, () => {
    // Declare a rule to enable the action on example.com pages
    const rule1 = {
      conditions: [
        new chrome.declarativeContent.PageStateMatcher({
          pageUrl: {hostSuffix: '.chrome.com'},
        })
      ],
      actions: [new chrome.declarativeContent.ShowAction()],
    };

    // Finally, apply our new array of rules
    const rules = [rule1];
    chrome.declarativeContent.onPageChanged.addRules(rules);
  });
});
```

```html
// popup.html
Hello world!
```

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312968810
