### ISSUE TITLE
chrome dev tools: cannot take heap snapshot, gets disconnected

### ISSUE THREAD

**Issue by jeffschulzusc** [GoogleChrome/developer.chrome.com#1565]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
sometimes can not take heap snapshot of loaded site

**To Reproduce**
1. open chrome browser
2. go to ex. developer.chrome.com/docs/devtools
3. open dev tools
4. try take heap snapshot ... get disconnected

**Expected behavior**
should be able to take a heap snapshot

**Screenshots**
included

**Desktop (please complete the following information):**
 - OS: mac os 10.13.6
 - chrome (did not happen on edge)
 - chrome 94.0.4606.71 (Official Build) (x86_64)

 
![Screen Shot 2021-10-08 at 8 47 11 AM](https://user-images.githubusercontent.com/91924637/136587245-90cd64d3-0a79-4fec-bf71-fd85aad90227.png)

**Comment by chuckntaylor** [comment]
Same. Cannot take any heap snapshots

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
