### ISSUE TITLE
chrome.storage.sync max properties not documented

### ISSUE THREAD

**Issue by Yash-Singh1** [GoogleChrome/developer.chrome.com#158]
The following are not documented:
- `MAX_ITEMS`
- `MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE`
- `MAX_WRITE_OPERATIONS_PER_HOUR`
- `MAX_WRITE_OPERATIONS_PER_MINUTE`

At https://developer.chrome.com/docs/extensions/reference/storage/#property-sync

**Comment by dotproto** [comment]
Duplicate of #135.
