### ISSUE TITLE
CentOS 7 - Can't install google-chrome-stable v.95

### ISSUE THREAD

**Issue by asphalter** [GoogleChrome/developer.chrome.com#1598]
I run a fully updated CentOS 7 system:

cat /etc/redhat-release 
  CentOS Linux release 7.9.2009 (Core)
 

I'm running the google-chrome-stable v94 without any kind of problem, but when I try to update to the latest v95 from http://dl.google.com/linux/chrome/rpm/stable/x86_64:

---> Package google-chrome-stable.x86_64 0:94.0.4606.71-1 will be updated
---> Package google-chrome-stable.x86_64 0:95.0.4638.54-1 will be an update
--> Processing Dependency: libc.so.6(GLIBC_2.18)(64bit) for package: google-chrome-stable-95.0.4638.54-1.x86_64

Error: Package: google-chrome-stable-95.0.4638.54-1.x86_64 (google-chrome)
           Requires: libc.so.6(GLIBC_2.18)(64bit)

CentOS 7 runs with glibc 2.17 and it will never update to newer glibc versions.
Could you please recompile with the a version of glibc that is also compatible with the "older" but still maintained CentOS 7, please?

Name        : glibc
Arch        : x86_64
Version     : 2.17
Release     : 325.el7_9

Regards,
Matteo

**Comment by jpmedley** [comment]
Thank you for letting us know. Unfortunately this is a feedback channel for a web site, not for the Chrome product. 

Can you still run Chrome 94? If so, there is a **Send Feedback to Google** dialog box. To reach it, find the three vertical dots in the upper right corner of Chrome. Click it, then select **Help** then **Report an issue**.

If you can't, please visit [Google Chrome Help](https://support.google.com/chrome/community?hl=en).
