### ISSUE TITLE
Normalize links in declare_permissions doc to absolute paths

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#162]
**Describe the bug**
And the extension docs we typically link to other extension resources using absolute paths, but the following document 

site/en/docs/extensions/mv2/declare_permissions/index.md
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robdodson** [comment]
I think the rest of the bug got cut off but I think this may be fixed now. Going to close but happy to reopen if it's still busted
