### ISSUE TITLE
manifest/update_url page is missing

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#163]
**Describe the bug**
Generalizing this for all missing manifest properties so that I can consolidate a bunch of tickets. Here's the original description:

>The doc page for the `update_url` property in manifest.json is missing. As mentioned in the discussion of #132, this page should clearly describe what this property is for and in what situations it is relevant. 

The pages covered by the various GitHub issues are listed below. If the original ticket includes information that it would be good to have in the documentation, its link is in parentheses after the URL.

- [ ] https://developer.chrome.com/docs/extensions/mv3/manifest/chrome_url_overrides/
- [ ] https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/ (Here's a [previously deleted page in the internet archive](https://web.archive.org/web/20210505021356/https://developer.chrome.com/docs/apps/contentSecurityPolicy)
- [ ] https://developer.chrome.com/docs/extensions/mv3/manifest/input_components/ (#250)
- [ ] https://developer.chrome.com/docs/extensions/mv3/manifest/natively_connectable/ (#2050)
- [ ] https://developer.chrome.com/docs/extensions/mv3/manifest/offline_enabled/
- [ ] https://developer.chrome.com/docs/extensions/mv3/manifest/optional_host_permission/
- [ ] https://developer.chrome.com/docs/extensions/mv3/manifest/type/
- [x] https://developer.chrome.com/docs/extensions/mv3/manifest/update_url/

**Comment by jpmedley** [comment]
@dotproto I looked at `update_url` on the [manifest page](https://developer.chrome.com/docs/extensions/mv3/manifest/). It links to [Extension hosting](https://developer.chrome.com/docs/extensions/mv3/hosting/), which doesn't explain how the two are related.

How are the two related?

**Comment by jpmedley** [comment]
@IanStanion-google I think this is related to what you're doing.

**Comment by AmySteam** [comment]
@jpmedley I added the correct link for for `update_url` in PR #4255, which is https://developer.chrome.com/docs/extensions/mv3/linux_hosting/#update_url

**Comment by jpmedley** [comment]
Thanks for letting me know. I don't think you need to make a comment for every item. Just reference this ticket in further PRs and check off items at the top as you do.
