### ISSUE TITLE
chrome extensions hover button

### ISSUE THREAD

**Issue by Danyhug** [GoogleChrome/developer.chrome.com#1633]
Now I'm making a browser extension. I want to suspend it in the browser when I'm not in use. I can't find the content I want in the document. Please help me😊

**Comment by oliverdunk** [comment]
This is quite old and I'm not sure the specific request, so I'm going to close for now. If you see this and would still like some more documentation here, feel free to file an issue in the new tracker: https://issuetracker.google.com/issues/new?component=1400036&template=1897236
