### ISSUE TITLE
MV2 doc set should be the default until MV3 ships

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#164]
**Describe the bug**
The extensions docs currently default to MV3, but MV3 has not yet shipped. These docs should default to the current state of the platform in order ensure that the material we're showing developers matches matches what they should expect when creating extensions today.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/
2. Visit one of the sub-pages linked by this document
3. Note that the URL of the page visited begins with `https://developer.chrome.com/docs/extensions/mv3`

**Expected behavior**
The linked document should be in the `mv2` path, not `mv3`.

**Screenshots**

![Screen Shot 2021-01-04 at 9 24 25 AM](https://user-images.githubusercontent.com/1047763/103561665-ad8cff80-4e6e-11eb-9b6d-c1aa0e91f91b.png)

**Comment by robdodson** [comment]
@dotproto y'all should be able to change this in your toc.yml

**Comment by samthor** [comment]
@dotproto how does this relate to #464?

**Comment by dotproto** [comment]
@samthor, 164 was invalidated once MV3 reached stable with the release of M89.
