### ISSUE TITLE
Latest 'Progress in the Privacy Sandbox' contains missing or incomplete origin trial information

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#1649]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The newly-published [Progress in the Privacy Sandbox](https://developer.chrome.com/blog/progress-in-the-privacy-sandbox-2021-10/) has incorrect or incomplete origin trial information. There are multiple issues:

_I found the following issues:_
* [Reduce User Agent string information](https://developer.chrome.com/origintrials/#/view_trial/-7123568710593282047) is described as an an "early opt-in" origin trial. All origin trials are early and opt-in. There aren't different types of origin trials. Should just say, 'origin trial'.
* [Attribution Reporting](https://www.chromestatus.com/feature/6412002824028160): At the time the article was published, and at the time I'm submitting this ticket, there is [no approval to extend](https://groups.google.com/a/chromium.org/g/blink-dev/c/DdjaFmsb4fA/m/c6z-TGLKDQAJ) the origin trial. As a consequence, it is not currently on the [origin trial dashboard](https://developer.chrome.com/origintrials/#/trials/active). The article says, "you will need to apply for updated tokens to continue testing". There is currently no way to do this.
* If the authors intent is for readers to sign up for the origin trial, references to them should link to dashboard entries.
* Instead of say there's an [intent to prototype on _User-Agent Client Hints GREASE Update_](https://groups.google.com/a/chromium.org/g/blink-dev/c/ueudFsZzT1M), it would be more useful to say something like, "Pending approval, we hope to soon be running an origin trial for User-Agent Client Hints GREASE Update." Many Chrome developers struggle with the minutiae of the Chrome intent process. I wouldn't expect readers who aren't Chromium developers to make the connection between intents to prototype and origin trials.

**Comment by jpmedley** [comment]
@rachelandrew FYI

**Comment by heyawhite** [comment]
The Attribution Reporting API is also known as the Conversion API and was approved for an [extended origin trial](https://developer.chrome.com/origintrials/#/view_trial/3411476717733150721). It's probably best to update that state-of-work in this coming month's post.

I'll address the remaining comments in an upcoming PR.
