### ISSUE TITLE
When the alert window is closed with the "esc" key, the input window temporarily fails to enter the key.

### ISSUE THREAD

**Issue by kangTaehee** [GoogleChrome/developer.chrome.com#1682]
When the alert window is closed with the "esc" key, the input window temporarily fails to enter the key.

**Desktop (please complete the following information):**
 - OS: window(kr)
 - Browser chrome
 - Version 95.0.4638.69

1. Alert occurred.
2. Press Esc.
3. Input element click key input

**Comment by devnook** [comment]
This is not related to developer.chrome.com website. Please consider filing a bug at http://crbug.com instead.
