### ISSUE TITLE
Incredibly slow, must restart every 5-10min to regain functionality

### ISSUE THREAD

**Issue by jo-finndian** [GoogleChrome/developer.chrome.com#1689]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Dev Tools across the board are incredibly slow (10-15sec on average) with every interaction after 5-10 minutes of use. Even navigating simply within "Elements" is slow like this, let alone switching to another tab.

**To Reproduce**
Not sure how to reproduce this error. None of my colleagues are having the same problem. I have turned off all of my plugins, clear my cache each time Chrome is shut down, and keep tabs to a minimum (4 or 5). 

**Expected behavior**
Not having to wait 10+ seconds to do anything, or having to restart every 10minutes to regain some speed.

**Desktop (please complete the following information):**
 - MacOS Big Sur v11.6
 - Chrome
 - Version 95.0.4638.69 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Comment by devnook** [comment]
Please submit this issue on https://crbug.com/ instead.
