### ISSUE TITLE
Lossy WebP used for images that should be compressed with lossless WebP

### ISSUE THREAD

**Issue by vrabaud** [GoogleChrome/developer.chrome.com#1694]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The site displays lossy WebP images at quality 90 while they could be lossless WebP.

**Desktop (please complete the following information):**
 - OS: gLinux
 - Browser: Chrome
 - Version: 95.0.4638.69

**Additional context**
Using lossy WebP increases the size of the images and deteriorates the quality of screenshot images. The following pages would be smaller in size if using lossless WebP:
https://developer.chrome.com/docs/webstore/publish/
https://developer.chrome.com/docs/webstore/register/

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
