### ISSUE TITLE
user-agent at emulation mode go back to default when redirect

### ISSUE THREAD

**Issue by taichi-yzrh** [GoogleChrome/developer.chrome.com#1699]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
when using 'emulation mode' for testing pc and mobile phone website, emulated user agent seems to be replaced to original one at redirection.

This is my web server's log.
```
(ok, you're mobile, go to mobile page)
localhost:443 172.18.0.1 - - [08/Nov/2021:11:43:31 +0900] "GET /pc/ HTTP/1.1" 301 641 "" "Mozilla/5.0 (Linux; U; Android 4.0.2; en-us; Galaxy Nexus Build/ICL53F) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"

(oh, you're not mobile, go to pc page)
localhost:443 172.18.0.1 - - [08/Nov/2021:11:43:31 +0900] "GET /sp/ HTTP/1.1" 301 641 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

(yes, you're pc, go ahead)
localhost:443 172.18.0.1 - - [08/Nov/2021:11:43:31 +0900] "GET /pc/ HTTP/1.1" 200 4472 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
```

**To Reproduce**
1. open developer tool
2. Click the mobile phone icon and get into emulation mode
3. browse web site that has redirection by use-agent
4. no mobile page...

**Expected behavior**
Emulated user agent should be kept even when redirection

**Desktop (please complete the following information):**
 - OS:  mac OS 11.6
 - Browser: chrome
 - Version: 95.0.4638.69（Official Build） （x86_64）

**Comment by myakura** [comment]
(Next time use https://crbug.com to send a bug report.)

It looks like https://bugs.chromium.org/p/chromium/issues/detail?id=1264251 ; good news is it's already fixed in Canary (and Beta).

**Comment by taichi-yzrh** [comment]
Thank you for all of your effort.
