### ISSUE TITLE
Can't read the properties while selecting the units on dark theme

### ISSUE THREAD

**Issue by s4ntosbruno** [GoogleChrome/developer.chrome.com#1725]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
low contrast ratio while listing the units

**To Reproduce**
1. inspect a text element
2. Scroll down to font-size
3. Click on the unit (pt, em, vh...)
4. See the list with unreadable values

**Expected behavior**
readable values of units in the list

**Screenshots**
![image](https://user-images.githubusercontent.com/43258154/141645907-7ebd261d-76a3-49a9-bab9-e080165a98b9.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: lastest

**Additional context**
love you guys work <3

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
