### ISSUE TITLE
Manifest file download link doesn't work anymore (https://developer.chrome.com/docs/extensions/mv2/getstarted/)

### ISSUE THREAD

**Issue by Reichmann-M** [GoogleChrome/developer.chrome.com#173]
**Describe the bug**
On the getting started page the link for downloading the ready manifest file doesn't work.

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/mv2/getstarted/'
2. Click on '[here](https://developer.chrome.com/docs/extensions/mv2/getstarted/examples/tutorials/get_started/manifest.json)' under 'Create the manifest'
3. No page found

**Expected behavior**
The page for download doesn't exist

**Desktop (please complete the following information):**
- Chrome version 87.0.4280.88 (Official Build) (64-Bit)

**Comment by robdodson** [comment]
I think this should be fixed now
