### ISSUE TITLE
TabGroup link Broken

### ISSUE THREAD

**Issue by donatj** [GoogleChrome/developer.chrome.com#176]
**Describe the bug**

Links to TabGroups docs 404

https://developer.chrome.com/docs/extensions/reference/tabGroups/

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv2/declare_permissions/
2. Click on `chrome.tabGroups` under `"tabGroups"` permission
3. See 404 error

**Expected behavior**
Some sort of tab group documentation

**Screenshots**

![image](https://user-images.githubusercontent.com/133747/103734771-44160980-4fb2-11eb-9a92-0d1774dce549.png)

**Desktop (please complete the following information):**

I'm sure this isn't applicable but

 - OS: macOS Mojave
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**

**Comment by pyoner** [comment]
same bug here https://developer.chrome.com/docs/extensions/mv3/declare_permissions/

**Comment by samthor** [comment]
Merged with #149.
