### ISSUE TITLE
404 page not available!

### ISSUE THREAD

**Issue by ChrisJohDev** [GoogleChrome/developer.chrome.com#1760]
Following "Learn more" link in the Highligts from the Chrome 97 update you get a 404 in Chrome on the Windows 10 platform!

Not really what I expect. Maybe you need me in the WebDev Insights Community after all despite my age.

-Chris

⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelSolati** [comment]
@ChrisJohDev which of the following articles are you seeing this issue on?

https://developer.chrome.com/blog/new-in-devtools-97/

or

https://developer.chrome.com/blog/deps-rems-97/

I'm not finding a broken link... I'm wondering if it was an page/URL that was supposed to go live around the same time as the page you clicked on it, but it wasn't live yet...
