### ISSUE TITLE
[Privacy Sandbox] Update with origin trial dashboard

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/developer.chrome.com#1761]
**Is your feature request related to a problem? Please describe.**
We should be consistent in how we link to origin trials in blog posts and docs.

**Describe the solution you'd like**
Per @jpmedley:

Origin trial dashboard links are the entry point to better information than is in an intent to experiment, regardless of whether the reader signs up. An article or `/privacy-sandbox` page (if it exists) would be a better link, if we have one. If we don't, we should be consistent across our sites, which means linking to the dashboard.

Additionally, links should be consistent within the status of origin trials at the top of any article/doc.

**Additional context**
This request was initially raised in https://github.com/GoogleChrome/developer.chrome.com/pull/1737

**Comment by jpmedley** [comment]
Here's some additional context. A previous article linked to an intent to ship on the blink-dev@ discussion group. The information in the intent to ship is intended to help Chromium owners determine whether a feature has met all the requirements for shipping. Consequently, it's low on information designed to help web developers use the feature.

**Comment by heyawhite** [comment]
Closing this out as we resolved this in 2022.
