### ISSUE TITLE
Expired code and Broken links at the "Overview -> What are extensions?" Page

### ISSUE THREAD

**Issue by Benbinbin** [GoogleChrome/developer.chrome.com#177]
**Describe the bug**
at the artile *[What are extensions?](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/)* show a Hello extensions example

* the `mainfest.json` set `"manifest_version": 3` but using `browser_action` it make mistake

  ```json
  "browser_action": {
    "default_popup": "hello.html",
    "default_icon": "hello_extensions.png"
  }
  ```

* there are two broken links at this page: 
  * [browser_action](https://developer.chrome.com/docs/extensions/browserAction/)
  * [hello_extensions.png here](https://developer.chrome.com/static/images/index/hello_extensions.png)

**Expected behavior**
* In MV3 [action api has unification](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#action-api-unification), it should be change to

```json
"action": {
  "default_popup": "hello.html",
  "default_icon": "hello_extensions.png"
}
```

**Comment by robdodson** [comment]
> there are two broken links at this page:

> browser_action
> hello_extensions.png here

these should be fixed now.

assigning to @dotproto to handle the manifest updates

**Comment by samthor** [comment]
This is fixed on both the linked page and the page named what the link is going to.
