### ISSUE TITLE
A typo in chome.scripting, ScriptInjection section

### ISSUE THREAD

**Issue by TueeNguyen** [GoogleChrome/developer.chrome.com#1771]
**Describe the bug**
It's just a small typo `curry into` in [chrome.scripting, ScriptInjection](https://developer.chrome.com/docs/extensions/reference/scripting/#type-ScriptInjection)

**To Reproduce**
1. Go to [chrome.scripting, ScriptInjection section](https://developer.chrome.com/docs/extensions/reference/scripting/#type-ScriptInjection)

![image](https://user-images.githubusercontent.com/58532267/143096866-8ee1c65e-c28e-4ae4-a028-006294566aaa.png)

**Comment by tophf** [comment]
It's not a typo, but a term used incorrectly: [currying](https://en.wikipedia.org/wiki/Currying). The correct term would be a simple `pass into`.

**Comment by TueNguyen2911** [comment]
My apologies! I'll look into `currying` and close the issue

**Comment by tophf** [comment]
The documentation still contains a mistake.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310290537
