### ISSUE TITLE
No samples for Context Menus API Manifest V3

### ISSUE THREAD

**Issue by AntonStrickland** [GoogleChrome/developer.chrome.com#1785]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The documentation for the Context Menus API does not have any sample code, making it difficult to learn and use

**To Reproduce**
1. Go to [https://developer.chrome.com/docs/extensions/reference/contextMenus/#examples](https://developer.chrome.com/docs/extensions/reference/contextMenus/#examples)
2. The text says "You can find samples of this API on the sample page."
3. If you click on the link in "sample page" it takes you to [this page](https://developer.chrome.com/docs/extensions/mv2/samples/#search:contextMenus) which shows a warning message in red: "The page you're viewing describes extensions using Manifest V2. Now that Manifest V3 has launched, we strongly recommend that you use it for any new extensions that you create." rather than actually showing you any samples
4. If you click the link inside the red box, it will take you to the intro to V3 docs, which will inevitably bring you back to step 1.  If you instead click the link to the GitHub repo below the red box, you will find code for V2, which goes against what the red box warns you (and from my experience, none of the V2 code examples worked either)
5. Thus, there is no way to actually find any samples for the Context Menu API Manifest V3

**Expected behavior**
What I expected was seeing sample code for the Context Menus API just like there is for [the Storage API](https://developer.chrome.com/docs/extensions/reference/storage/). That link on step 3 above eventually let me to [this repo](https://github.com/GoogleChrome/chrome-extensions-samples) and found some examples inside several different directories (Should I be looking in the apps folder or the mv2 folder??? What is the difference between the two? Where do I go to learn the difference?). I don't think building with an older version is ideal, I would rather learn V3 than V2 for obvious reasons. Tutorials I find online are for V2 but the official docs are all V3. That repository says that V3 examples are not yet finished, but the V2 stuff was archived 9 months ago, so where are they? I just want a working example of the V3 Context Menus API.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.45

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
You need to make an easier way to report issues like this. I shouldn't need to open a Github issue just for giving this type of feedback on the site. Provide something like "did this page answer your question?" and then I select "no" and type the above description into a textbox and click a button to send it over from within that page.

**Comment by AmySteam** [comment]
@IanStanion-google can you add a links to the basic context menu sample and also the global_context_search? can you make two separate list items linked individually? Thanks!

**Comment by AmySteam** [comment]
Fixed in #6682
