### ISSUE TITLE
Typo in /popup.js file in extension example

### ISSUE THREAD

**Issue by aleksbelic** [GoogleChrome/developer.chrome.com#1793]
**Describe the bug**
Zipped example of the extension used in the tutorial contains a typo.

**To Reproduce**
1. Go to [Getting started page](https://developer.chrome.com/docs/extensions/mv3/getstarted/)
2. Click on "The completed extension can be downloaded [here](https://storage.googleapis.com/web-dev-uploads/file/WlD8wC6g8khYWPJUsQceQkhXSlv1/SVxMBoc5P3f6YV3O7Xbu.zip)".
3. Open downloaded file `/popup.js`
4. See typo in line 1: `// Initialize butotn with users's prefered color`

**Expected behavior**
It should be `button` instead of `butotn`.

**Screenshots**
![image](https://user-images.githubusercontent.com/8314231/143932527-504f32c8-3197-4f17-aad2-2b66279857fc.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Comment by jpmedley** [comment]
@AmySteam, please confirm that your new getting started content replaced this content.

**Comment by AmySteam** [comment]
@jpmedley Correct. I'm closing this issue because it is no longer relevant.
