### ISSUE TITLE
Clarify "How can I push an update" in CWS FAQ

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#1794]
**Describe the bug**

**To Reproduce**
1. Go to https://developer.chrome.com/docs/webstore/faq/#faq-dev-02
2. Read the description

**Current behavior**

The description does not mention review times. Worse, it implies that it will only be a few hours between when a developer submits an updated extension and when it goes live.

**Expected behavior**

This FAQ entry should be updated to answer the question more directly. We should either remove the note about the publishing timeline since it's out of scope for this question or link to other docs that answer it more directly and in more detail.

**Screenshots**

<img width="746" alt="Screen Shot 2021-11-29 at 4 12 08 PM" src="https://user-images.githubusercontent.com/1047763/143962467-18f33c3b-57e9-4022-95b7-e81b3aec5962.png">

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/310281008
