### ISSUE TITLE
 Issue between the device toolbar and NavigatorUAData

### ISSUE THREAD

**Issue by abitwhy** [GoogleChrome/developer.chrome.com#1823]
**Describe**
The device toolbar does not fully support the navigator.userAgentData property.

**Screenshots**
![reproduce bug](https://user-images.githubusercontent.com/68452982/144953445-3a47220d-c90f-4173-b590-962274016e4e.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 96.0.4664.45

**Comment by Semaerdem3536** [comment]
Yazılım\İlkeler\Google\Chrome\ExtensionInstallSources

**Comment by dstmarthe** [comment]
I notice that now it works for android devices, but says nothing about Apple. 
<img width="1522" alt="Screenshot 2024-02-07 at 4 41 20 PM" src="https://github.com/GoogleChrome/developer.chrome.com/assets/72896959/178d2d12-8c43-40c2-9070-af3a53281bcc">

I'd urge you to recreate this issue in the [Chromium](https://issues.chromium.org/issues?q=status:open&p=1) issue tracker, as this repo and the new dcc issue tracker are for issues with the content of the site specifically, not devtools code/functionality. Thanks.
