### ISSUE TITLE
extended parse of is statement without curly brackets

### ISSUE THREAD

**Issue by kmorte** [GoogleChrome/developer.chrome.com#1824]
Hi, I think I found a bug;

I use use this code in a class statement. It is a class constructor that checks for the existance of certain elements and accordingly invokes some logic. Look at the 3 if(this.tableElem).

This is invalid. And it is because Chrome is parsing as the body of the last if(this.tableElem) not only the setAttribute method, but also the .after invokation method altogether.

```
    constructor() {

        super({
            module: 'customers'
        });

        // FORM
        (this.formElem).setAttribute('module', 'customers');
        // this.root.appendChild(this.formElem);
        (this.formTemplate).after(this.formElem)

        // BUTTONS
        if(this.isButton) this.isButton.remove();
        (this.buttonsElem).setAttribute('module', 'customers');
        // this.root.appendChild(this.buttonsElem);
        this.btnTemplate.after(this.buttonsElem)

        // TABLE
        // Check for existance is necessary.
        if(this.tableElem) (this.tableElem).setAttribute('module', 'customers')
        if(this.tableElem) (this.tableElem).setAttribute('columns', JSON.stringify(['name','surname', 'id', 'phone', 'mail']))
        if(this.tableElem) (this.tableElem).setAttribute('params', JSON.stringify(['firstName', 'lastName1', 'idDocNbr', 'phoneNbr', 'email']))

        // this.root.appendChild(this.tableElem);
        (this.tblTemplate).after(this.tableElem)

        // ELEMENTS
        // this.state = this.state['customers']

        // GRAPH
        this.setCharts('customers')


        // VIEW
        // this.applyView();
        // this.mechanics('customers')
    }
```

If we focus on the Sources of the devtools, I can see what Google Chrome is interpretting. which is: 
![image](https://user-images.githubusercontent.com/57625775/144978136-b263be95-67f1-455f-bb6f-3b38b3b5f731.png)

But I believe, that an if statement without brackets should stop parsing as the body of the statement after the first element.

By the way, I usually use this approach on one liners and I think not everywhere I have the ; in placed (which fixes the problem)
Also, the first two if(this.tableElement) statement, in my code don't have the ; but as we can we, the chrome engine puts them. But not to the last one.

I think it's a bug.

My chrome version is Versión 96.0.4664.45 (Build oficial) (64 bits)

Thank you,
Kevin

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
