### ISSUE TITLE
[Translate] Translate articles on the Chrome Developers into Korean

### ISSUE THREAD

**Issue by techhtml** [GoogleChrome/developer.chrome.com#1829]
# Purpose
Some documents (e.g., What's new in Chrome Devtools) are translating to Korean.
But other docs are does not translated, So When Korean developers accessing the English contents, the sites are changing to English site.

some Korean developers want to translate the contents into Korean.
If there are some contents that can translate, I will control it with Korean volunteers.

**Comment by rachelandrew** [comment]
Closing as the new platform has translations and we are closing this repo.
