### ISSUE TITLE
chrome.events is undefined

### ISSUE THREAD

**Issue by sineway** [GoogleChrome/developer.chrome.com#183]
According to API documentation [chrome.events](https://developer.chrome.com/docs/extensions/reference/events/) should provide utility classes, but unfortunately it does not.

 - OS: Linux
 - Browser: Chromium
 - Version: 87.0.4280.88

**Comment by samthor** [comment]
The way we describe these types hasn't changed with an upgrade to this site.

The reality is that every "class" you see in the documentation is really an interface that is only accessible via a property or a getter—there is no case in Chrome's extensions APIs where you run `new chrome.foo.ClassName`.

Is there a way we can make this clearer? It's made clear from within the .d.ts files.

**Comment by dotproto** [comment]
@samthor, I'm closing this issue as it appears to be resolved and hasn't' had any discussion on it in ~2 months. Please re-open if you wanted to keep it active.

**Comment by samthor** [comment]
Sounds good. I am honestly happy to make this clearer if we can, but I'm not sure how.
