### ISSUE TITLE
Finish MV3ization for page: Content scripts

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#184]
The page [Content scripts](https://developer.chrome.com/docs/extensions/mv3/content_scripts/) page is not compliant with MV3. It needs to be checked and updated for manifest contents, API use, etc.

**Comment by dotproto** [comment]
Quick brainstorm before beginning to look at the article. What topics do I want to address or what issues do I expect to address?

- [ ] Call out that content 
- [ ] Document how to use the scripting API to register content scripts
- [ ] Replace references to chrome.tabs.executeScript with chrome.scripting.executeScript
- [ ] Look for references to manifest_version or other modified APIs
