### ISSUE TITLE
How does chrome extension take over Chrome's "prompt to save password" feature?Description not found in the Chrome extension documentation

### ISSUE THREAD

**Issue by wangmeijian** [GoogleChrome/developer.chrome.com#1852]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
How does chrome extension take over Chrome's "prompt to save password" feature?Description not found in the Chrome extension documentation

**To Reproduce**
1. install [chrome extension](https://chrome.google.com/webstore/detail/microsoft-autofill/fiedbfgcleddlbcmgdigjgdfcggjcion) then login
2. Open the chrome with chrome: / / Settings/passwords
3. see this
![image](https://user-images.githubusercontent.com/9384140/146342361-eb825085-9391-4f54-90ec-3f873c4a4d46.png)

**Expected behavior**
This is explained in the Chrome extension developer documentation

**Screenshots**
In the above

**Desktop (please complete the following information):**
 - OS: [macOs Monterey]
 - Browser [chrome]
 - Version [96]

**Additional context**

**Comment by Zevgon** [comment]
FWIW there is a way to accomplish this using the `chrome.privacy` api, see an [example here](https://developer.chrome.com/docs/extensions/reference/privacy/#usage).

But it would still be nice if [these docs](https://developer.chrome.com/docs/extensions/mv3/settings_override/) mentioned that, as well as clarify whether it's possible to do it in the manifest.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’ve moved to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324349152
