### ISSUE TITLE
Documentation > Extensions > "Debugging extensions" page, "Popup" section has different 'popup.js' code than what the chrome-extensions-samples Github has

### ISSUE THREAD

**Issue by varunmathuria** [GoogleChrome/developer.chrome.com#1856]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
On documentation page: https://developer.chrome.com/docs/extensions/mv3/tut_debugging/
In "Popup" section,
the code from 'popup.js' that is shown is different from what's in the Github chrome extensions sample "broken_background_color" folder (https://github.com/GoogleChrome/chrome-extensions-samples/tree/e716678b67fd30a5876a552b9665e9f847d6d84b/mv2-archive/tutorials/broken_background_color). This Github folder is what is linked to at the beginning of https://developer.chrome.com/docs/extensions/mv3/tut_debugging/.

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/mv3/tut_debugging/'.
2. Scroll down to 'Popup' section.
3. Scroll down to the included code, starting with "let changeColor = document.getElementById('changeColor');".

**Expected behavior**
Expect to see code matching what's in the Github chrome extensions sample "broken_background_color" folder:
```changeColor.onclick = function(element) {
  let color = element.target.value;
  // The extension must query the active tab
  // before it can injected a content script
  chrome.tabs.executeScript(
      tabs[0].id,
      // Scripts injected with tabs.executeScript() will not have access to
      // variables from this context, leaving |color| undefined.
      {code: 'document.body.style.backgroundColor = color;'});
};```

**Actual behavior**
Instead I see:
```  changeColor.addEventListener('click', () =>
    chrome.tabs.query({active: true, currentWindow: true}, function(tabs) {
      chrome.scripting.executeScript(
          tabs[0].id,
          { function: setColor });
    });
  );
  
  async function setColor() {
    let {color} = await chrome.storage.sync.get(['color']);
    document.body.style.backgroundColor = color;
  };```

**Screenshots**
<img width="743" alt="actual_code_on_Debugging_extensions_page" src="https://user-images.githubusercontent.com/16373449/146638112-9ab14a73-376a-4731-9d9c-5991453f853a.png">
<img width="855" alt="expected_code_from_broken_background_color_github" src="https://user-images.githubusercontent.com/16373449/146638114-3fd429d4-efd4-4c2e-b17e-d76f33577445.png">

If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version 95.0.4638.69

**Additional context**
Add any other context about the problem here.

**Comment by AmySteam** [comment]
Fixed in #6072
