### ISSUE TITLE
Chrome Extensions Manifest v3: offline_enabled docs missing 

### ISSUE THREAD

**Issue by code-reaper08** [GoogleChrome/developer.chrome.com#1859]
**Describe the bug**
Missing documentation for the mv3's offline_enabled. 

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/mv3/manifest/'
2. Click on 

![image](https://user-images.githubusercontent.com/64256342/146816383-d422e0dc-99f6-42ef-b126-70a78430c746.png)

3. Open the link 'https://developer.chrome.com/docs/extensions/mv3/manifest/offline_enabled/'
4. See error **(404)**

**Expected behavior**
_**"offline_enabled"**_ should be documented in mv3 docs.

**Additional context**
I would like to work on this issue.

**Comment by AmySteam** [comment]
Related PRs [#4308](https://github.com/GoogleChrome/developer.chrome.com/pull/4308) and [#4369](https://github.com/GoogleChrome/developer.chrome.com/pull/4769)
