### ISSUE TITLE
Punto de interrupción no toma el evento onclick

### ISSUE THREAD

**Issue by 3P4R4** [GoogleChrome/developer.chrome.com#1869]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

** DEV Tools no se detiene en el breakpoint tal como dice el tutorial**
En el tutorial siguiente: 
https://developer.chrome.com/docs/devtools/javascript/

en el punto numero #4 del (**Paso 3: pausa el código con un punto de interrupción**) dice que al crear un punto de interrupción con el evento **mouse / click** en el ejercicio al darle al boton **Agregar el número 1 y el número 2** este debe detenerse precisamente en la función `function onClick() {` cosa tal que no hace; también dice que si esto no sucede es posible a las extensiones que en este momento debemos tener instaladas o en uso y que para ello es recomendable hacer uso de la *ventana incógnita de chrome** y que de igual manera los pasos anteriores no funcionan tal como dice el tutorial, es decir el **breakpoint** no se detiene en la linea de código  `function onClick() {` sino que se detiene en la linea de codigo siguiente, es decir en `if (inputsAreEmpty()) {` anexare imagen para ilustrar mejor, espero y esta primer issue sea comprendido y explicito

![image](https://user-images.githubusercontent.com/19245726/147171943-d9220461-8980-4fad-ad03-098344a2b101.png)

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
