### ISSUE TITLE
chrome.dom API is not listed

### ISSUE THREAD

**Issue by tophf** [GoogleChrome/developer.chrome.com#1880]
Source: https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/dom.json
Stable since Chrome 88: https://chromiumdash.appspot.com/commit/f4f2db0e91928a0efff817e7c2156ca7ae614ef8
Available in content scripts and normal extension scripts.
MV2/MV3.

**Comment by jpmedley** [comment]
Thank you for the submission. Can you please tell us where the API is not listed? We have a lot of documentation. We can't really do anything with this unless we know which page you think is incorrect.

cc: @dotproto

**Comment by tophf** [comment]
`chrome` is an API for chrome extensions so you already cc'd the relevant person. The page is the [API reference](https://developer.chrome.com/docs/extensions/reference/). BTW, you could make your site preserve the URL automatically where the `File a bug` link was pressed - maybe there's a github action for that or you could write it.

**Comment by jpmedley** [comment]
@dotproto I thought this content was autogenerated. Am I correct and do you know anything about that?

**Comment by dotproto** [comment]
@jpmedley, you are correct, reference API docs are generated off of type information automatically extracted from Chromium using [chrome-types](https://github.com/GoogleChrome/chrome-types). Beyond simple type conversions, that project also has some business logic to massage Chromium data into something more consumable by DCC. That doesn't appear to be the point of failure here, though. 

In order generate an API reference page, we also need an MD file in this repo that exposes the API docs. That's the part we're currently missing. The good news is this is a very quick fix. I'll create a PR to address this in just a moment.
