### ISSUE TITLE
text-wrap for title 

### ISSUE THREAD

**Issue by imblsm** [GoogleChrome/developer.chrome.com#1883]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by imblsm** [comment]
set text-wrap for title

**Comment by jpmedley** [comment]
Thanks for the submission. Do you have an example of where the lack of text-wrap is a problem?

**Comment by jeffposnick** [comment]
Closing due to lack of response from the original author.
