### ISSUE TITLE
Chrome DevTools: How about mobile app?

### ISSUE THREAD

**Issue by davidhcefx** [GoogleChrome/developer.chrome.com#1894]
**Describe the bug**
On the [Chrome DevTools][1] main page, it reads
> Chrome DevTools is a set of web developer tools built directly into the **Google Chrome browser**.

However, it’s not for the mobile version of *Google Chrome browser*, but only for the desktop app. The instructions in [Open Chrome DevTools][2] are also for the desktop app. The document hadn’t  distinguish between the two, so I think it is somehow misleading.

**To Reproduce**
1. Visit the above links.

**Expected behavior**
Change the sentences to something like
> Chrome DevTools is a set of web developer tools built directly into the Google Chrome browser **on desktop**.

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: safari
 - Version: 15.2

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS15.2
 - Browser: safari
 - Version: 15.2

**Additional context**

[1]: https://developer.chrome.com/docs/devtools/
[2]: https://developer.chrome.com/docs/devtools/open/

**Comment by gwhizoftv** [comment]
HI, apparently console.log has different specs on iOS Chrome than on desktop Chrome. Where can I read about these differences?

**Comment by jpmedley** [comment]
iOS Chrome is a fork of WebKit, not Chromium. There are differences between how Webkit behaves in a fork versus in Safari. I don't know if that applies to console. I would start with WebKit/Safari developer documentation.

**Comment by dstmarthe** [comment]
Thanks for raising this issue. Gotta close it because it's stale by all now.
