### ISSUE TITLE
[samples] Existing links to .../samples -- verify and fix/update

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#190]
There are various links in the extensions docs that refer to samples at .../samples/...

These links may be 404 or point to the MV2 rather than MV3 version of the example. Or other badness.
Check and fix these links as necessary.

**Comment by robdodson** [comment]
I think this should be resolved now with sam's new redirect code. @awfuchs do you want to verify?

**Comment by awfuchs** [comment]
Tested a lot with this and seems like all the links work. Did a minor reword of a couple of links' intro text in https://github.com/GoogleChrome/developer.chrome.com/pull/315 but otherwise all seems good. Closing.
