### ISSUE TITLE
Add support for tagging placeholder values with `<var>` inside code snippets

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#1902]
**Is your feature request related to a problem? Please describe.**

The [Google developer documentation style guide](https://developers.google.com/style)'s guidance for [placeholders](https://developers.google.com/style/placeholders) recommends the use of `<var>` and notes that DevSite-hosted sites can use a Jinja expression to escape var elements in [inline text](https://developers.google.com/style/placeholders#placeholders-in-inline-text) and code blocks.

As far as I can tell we don't have a way of injecting`<var>` or other HTML in code blocks.

**Describe the solution you'd like**

The following applies to both DCC and web.dev.

1. Add styling for content wrapped in `<var>` tags. Our sites currently use default browser styles.
2. Create a tag that can insert arbitrary HTML inside code blocks.

Arbitrary HTML is desirable because it would also allow us to insert links and otherwise style code blocks in ways that we cannot to today. For example, in order to add links to the large code block in the [extensions manifest.json docs](https://developer.chrome.com/docs/extensions/mv3/manifest/) we had to render the base JSON object, copy the generated HTML with the appropriate syntax highlighting classes, and manually insert new HTML tags in the HTML ([source](https://raw.githubusercontent.com/GoogleChrome/developer.chrome.com/main/site/en/docs/extensions/mv3/manifest/index.md)). This approach is brittle to syntax highlighting changes and is much more difficult for us to maintain.

If there are concerns related to allowing arbitrary HTML to be injected, I have two possible alternative suggestions

1. Create a tag that can be used to render markdown inside code blocks. This would allow us to do some basic `**bold**` and `_italic_` decoration inside a code block while retaining all the escape handling of normal markdown.
2. Create a tag that allows us to insert `<var>` tags inside code blocks. While this approach is less full featured, it would at least enable us to more meaningfully decorate code samples.

**Describe alternatives you've considered**

I noted the main adaptation strategy above: use markdown to syntax highlight a code block on a local dev server, copy the decorated HTML from the page, replace the markdown code block with the syntax highlighted HTML, and adjust the raw HTML as needed to achieve the desired outcome.

**Comment by jeffposnick** [comment]
Here's what seems to be doable right now—but it assumes that you are okay with giving up syntax-aware colors in favor of support for `<var>` (and `<kbd>`, `<mark>`, etc.).

If you switch from the <code>\`\`\`js</code> fence syntax to an explicit `<pre><code>` combo, you can add arbitrary HTML tags to your code sample. Unfortunately, doing this won't trigger the 11ty Prism integration that is responsible for tokenizing the source and wrapping things like strings or comments with `<span>`s that will render them in different colors. If you're working with a language format that doesn't have meaningful syntax highlighting (I'm thinking <code>```json</code> for instance), but you really want manual highlighting, maybe that's a good tradeoff?

Here's a smallish JS code snippet from a d.c.c. article, with syntax and screenshots to compare:

## Fence Tags

### Markup

<pre><code>```js
function setAutoDarkClass() {
  const isAutoDark = backgroundColor != <var>'rgb(255, 255, 255)'</var>;

  // remove the detection element from the DOM.
  document.body.removeChild(detectionDiv);

  // Set the marker class on the body if in Auto Dark Theme.
  if (isAutoDark) {
    document.body.classList.add(<mark>'auto-dark-theme'</mark>);
  }
}
document.addEventListener("DOMContentLoaded", setAutoDarkClass);
```</code></pre>

### Rendered

Note the syntax highlighting, but verbatim `<mark>` and `<var>`:

<img width="713" alt="Screen Shot 2022-02-16 at 2 49 56 PM" src="https://user-images.githubusercontent.com/1749548/154344564-833dca7b-ee64-484a-ab2d-7091e4a0789d.png">

## pre + code

### Markup

```
<pre><code>function setAutoDarkClass() {
  const isAutoDark = backgroundColor != <var>'rgb(255, 255, 255)'</var>;

  // remove the detection element from the DOM.
  document.body.removeChild(detectionDiv);

  // Set the marker class on the body if in Auto Dark Theme.
  if (isAutoDark) {
    document.body.classList.add(<mark>'auto-dark-theme'</mark>);
  }
}
document.addEventListener("DOMContentLoaded", setAutoDarkClass);</code></pre>
```

### Rendered

Note the interpreted `<mark>` and `<var>`, but lack of syntax highlighting:

<img width="710" alt="Screen Shot 2022-02-16 at 2 45 29 PM" src="https://user-images.githubusercontent.com/1749548/154343790-7c22161d-99b0-40dc-a583-96fa9f2e60f6.png">

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
