### ISSUE TITLE
'Account alias' and the 'App grid' disappear when on 'spreadsheets template gallery'

### ISSUE THREAD

**Issue by roneykuntz** [GoogleChrome/developer.chrome.com#1918]
**Describe the bug**
On the spreadsheet page, when I click on the 'template gallery', the 'account alias' and the 'apps grid' disappear, but it looks like they are under some layer as you can partially see the account alias.

**To Reproduce**
1. Go to '[https://docs.google.com/spreadsheets/](https://docs.google.com/spreadsheets/)'
2. See the 'account alias' and the 'apps grid'
3. Click on the 'template gallery'
4. See error, the 'account alias' and the 'apps grid' disappear

**Expected behavior**
See my default 'account alias' and 'application grid'

**Screenshots**
![printscreen_2022 01 07_11h24m52s](https://user-images.githubusercontent.com/26967626/148560608-67af40c2-c44b-4c83-a983-746437fa73fc.png)
![printscreen_2022 01 07_11h23m54s](https://user-images.githubusercontent.com/26967626/148560633-99c2ef5a-c10f-490b-acb2-48f2528923dd.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 97.0.4692.71

**Comment by rachelandrew** [comment]
@roneykuntz this is the repository for the developer website at developer.chrome.com. To get help with Google sheets try the following link https://support.google.com/a/answer/1047213
