### ISSUE TITLE
Typo on colrv1-fonts article

### ISSUE THREAD

**Issue by rsheeter** [GoogleChrome/developer.chrome.com#1923]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The author of the Reem Kufi Ink font notes that there is a small typo in the Reem Kufi sample text on https://developer.chrome.com/en/blog/colrv1-fonts/ , the current text reads طوفي ريم but it should be كوفي ريم (the first letter is wrong).

**To Reproduce**
Go to https://developer.chrome.com/en/blog/colrv1-fonts/#artistic-expression

**Expected behavior**
Sample text needs to be different as noted above

**Additional context**
I will provide an updated image, just want to confirm my fixed version is correct as I cannot read the text :)

Article originally merged in #1862

**Comment by rsheeter** [comment]
Fixed image:

![image (10)](https://user-images.githubusercontent.com/6466432/148696704-94858c6f-86fd-49fe-a958-fd995e30f7ec.png)

**Comment by rachelandrew** [comment]
@drott can you confirm this change as correct?

**Comment by drott** [comment]
Yes, this is right. I'll make a PR.
