### ISSUE TITLE
Improve documentation regarding `chrome.runtime.MessageSender`

### ISSUE THREAD

**Issue by ylemkimon** [GoogleChrome/developer.chrome.com#1931]
Ref: https://crbug.com/1285217

**Is your feature request related to a problem? Please describe.**
`chrome.runtime.MessageSender` doesn't explicitly state the type of its source, and its documentation is unclear. These may lead extension developers to write insecure code in extensions. (I've found several vulnerabilities in published extensions and reported them to respective vendors.)

1. Messages from a page, content script, and extension share the same listener, `chrome.runtime.onMessageExternal`. However, `MessageSender` doesn't have an explicit property that denotes its type. Furthermore, the documentation[1][2][3] is unclear and doesn't provide an example of identifying it.

For example,

`manifest.json`
```json
{
  "background": {"scripts": ["background.js"]},
  "content_script": [...],
  "externally_connectable": {"id": ["B", "C"], "matches": ["*://D/*"]}
}
```
`background.js`
```js
chrome.runtime.onMessageExternal.addListener((message, sender, sendResponse) => {
  if (sender.id === "B") // (1)
  if (sender.url === "D") // (2)
  if (sender.origin === "D") // (2)
}
```

(1) The message may come from B's content script when a message from the extension is expected, and vice versa.
(2) The message may come from B's content script when a message from the external page D is expected.

2. A compromised renderer can spoof the `MessageSender.id` and `url` (https://crbug.com/982361 and https://crbug.com/1038996). However, both bugs are not fixed nor public, and the documentation [1] doesn't say they are not trustworthy. [4] doesn't state the URL can be spoofed. [2] and [3] have examples where they use 'id' or 'url' to verify the message.

For example,

`manifest.json`
```json
{
  "background": {"scripts": ["background.js"]},
  "content_script": [...],
  "externally_connectable": {"id": ["B", "C"], "matches": ["*://D/*", "*://E/*"]}
}
```
`background.js`
```js
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (checkUrl(sender.url)) // (2)
}

chrome.runtime.onMessageExternal.addListener((message, sender, sendResponse) => {
  if (sender.id === "B" && checkUrl(sender.url)) // (1), (3)
  if (checkUrlIsD(sender.url)) // (1), (3), (4)
}
```

(1) The message may come from a compromised renderer that hosts extension B.
(2) The message may come from a compromised renderer with A's content script.
(3) The message may come from a compromised renderer with C's content script.
(4) The message may come from a compromised renderer of E.

[1] https://developer.chrome.com/docs/extensions/reference/runtime/
[2] https://developer.chrome.com/docs/extensions/mv3/messaging/
[3] https://developer.chrome.com/docs/extensions/mv3/security/
[4] https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/compromised-renderers.md#Messaging

**Describe the solution you'd like**
* State `chrome.runtime.onMessageExternal` and  `onConnectExternal` listener can accept messages from a page, content script, or extension in https://github.com/GoogleChrome/developer.chrome.com/blob/023de02780afe73a48e43a6aaebdf1fe81cdb831/site/en/docs/extensions/reference/runtime/index.md#L7-L14 and https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/api/runtime.json;l=557;drc=df76446c6f2a16cdb754fe1bc45fa179dc79b7da
* Provide an example of identifying and verifying the source, e.g.:
```js
chrome.runtime.onMessageExternal.addListener((message, sender, sendResponse) => {
  if (sender.tab == null) {
    // message from another extension
    if (checkExtensionId(sender.id)) {
      performAction();
    }
  } else if (sender.id != null) {
    // message from a content script
    // a compromised renderer may have spoofed the id, so it may not be actually coming from the content script
    // it also may have spoofed the url, so use sender.origin or sender.tab.url instead
    if (checkExtensionId(sender.id) && checkOrigin(sender.origin)) {
      performAction();
    }
  } else {
    // message from an externally connectable page
    // a compromised render may have spoofed the url, so use sender.origin instead
    if (checkOrigin(sender.origin)) {
      performAction();
    }
  }
}
```
* State the URL can be spoofed in https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/api/runtime.json;l=70;drc=df76446c6f2a16cdb754fe1bc45fa179dc79b7da and/or https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/compromised-renderers.md#Messaging.
* Improve the description of the `origin` in https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/api/runtime.json;l=73;drc=df76446c6f2a16cdb754fe1bc45fa179dc79b7da ("[origin] is useful for identifying if the origin can be trusted if we can't immediately tell from the URL." may imply the URL is the primary source to trust.)
* Mention the message may come from the content script in https://github.com/GoogleChrome/developer.chrome.com/blob/023de02780afe73a48e43a6aaebdf1fe81cdb831/site/en/docs/extensions/mv3/messaging/index.md#L160-L163
* Use `origin` instead of `url` in https://github.com/GoogleChrome/developer.chrome.com/blob/023de02780afe73a48e43a6aaebdf1fe81cdb831/site/en/docs/extensions/mv3/messaging/index.md#L237-L241
* https://github.com/GoogleChrome/developer.chrome.com/blob/023de02780afe73a48e43a6aaebdf1fe81cdb831/site/en/docs/extensions/mv3/security/index.md#L220-L231 it has the old API `runtime.onRequestExternal` -> `runtime.onMessageExternal`/`connectExternal` and the example may imply `sender.id` is not spoofable. Add a note that the id may have been spoofed, and it should also verify the `origin`.

**Describe alternatives you've considered**
- Introduce a property in MessageSender, e.g., `type`, that denotes the message source type.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at:
https://issuetracker.google.com/issues/311491887
