### ISSUE TITLE
[Content feedback] Full accessibility tree blog post does not describe when the feature will become available, or how to enable it

### ISSUE THREAD

**Issue by luiszugasti** [GoogleChrome/developer.chrome.com#1935]
**Describe the bug**
What version of Chrome will the full accessibility tree be released in? Or, how can it be enabled in the current version?
I'm making reference to this article:
https://developer.chrome.com/blog/full-accessibility-tree/

**To Reproduce**
1. See in the link I provided above that the version this feature is available in is not available

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by luiszugasti** [comment]
Hehe - it can be enabled under settings -> experiments -> enable full accessibility tree view in the elements panel.

![image](https://user-images.githubusercontent.com/11198457/148979427-4238dede-e190-47ed-85b0-6ba68bf3eb4f.png)

**Comment by dstmarthe** [comment]
As you may know there is a gif showing how to enable the full accessibility tree view [on the article](https://developer.chrome.com/blog/full-accessibility-tree/#full-accessibility-tree-in-devtools). One could argue that this isn't adequate enough direction. Either way if you still have an issue, you can enter an issue on the [new issue tracker](https://issuetracker.google.com/issues?q=componentid:1400036%20status:open&s=modified_time:desc). Closing this issue out as we are in the process of migrating to a new paltform.
