### ISSUE TITLE
Update Imgix to allow ARIA parameters

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/developer.chrome.com#1947]
**Describe the bug**
The Imgix API implementation does not currently allow for ARIA related parameters, such as `aria-hidden`. This is particularly helpful to follow the Google Developer Documentation Style Guide for [icons and buttons](https://developers.google.com/style/ui-elements?hl=en#buttons). 

For example, when referencing the Settings icon, displaying the image next to settings would cause a screenreader to say "Settings Settings", which is a poor user experience. This is already the case in some of the [DevTools documentation](https://developer.chrome.com/docs/devtools/device-mode/#viewport).

**Screenshots**
![The icon name, "Toggle Device Toolbar," is repeated twice for screen readers as evidenced by the code](https://user-images.githubusercontent.com/2766281/149210205-bd08b5d4-0766-4be6-8b8b-f542dc4a9667.png)
In this example, "Toggle Device Toolbar" is repeated twice.

```
// Markdown represented for this image
Click **Toggle Device Toolbar** 
{% Img 
   src="image/admin/9FiBHFCzfPgP8sy6LMx7.png", 
   alt="Toggle Device Toolbar",
   width="30", height="32" 
%}
```

**Additional context**
It may be possible there is a plugin to solve this problem: https://docs.imgix.com/libraries/statamic

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
