### ISSUE TITLE
Missing type information for some callbacks

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#195]
**Describe the bug**
The type information for some types is missing.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/reference/webNavigation/#method-getAllFrames
2. Try to figure out type of object passed to the callback

**Expected behavior**
See the type (which is an array of frames)

**Screenshots**
![image](https://user-images.githubusercontent.com/1915693/104063019-5eb5d180-51b0-11eb-99d3-e855d56cea3a.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 88

**Additional context**

**Comment by samthor** [comment]
I think we're not expanding inline object types within an array type. Technically the rendering code renders a small inner type before wrapping it with a suffix `[]`.

We should add an escape hatch that looks to see if we can render the inner part of an array in the expanded way.

There's a few cases of this throughout the source.
