### ISSUE TITLE
Document CSP in Manifest V3

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#1976]
**Describe the bug**

The extensions documentation does not currently have a good reference page for how content security policies work in Manifest V3 extensions. At the moment the relevant link on the manifest page points to the migration documentation.

**Expected behavior**

- Cover the `content_security_policy` key in manifest.json
- Describe how CSP works for content scripts
- Describe how CSP works for sandboxed pages

**Additional context**

https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/manifest_handlers/csp_info.cc?q=default_isolated_world_csp&ss=chromium

**Comment by dotproto** [comment]
Related to #1351.

**Comment by mom998** [comment]
Good

**Comment by AmySteam** [comment]
Fixed in PR https://github.com/GoogleChrome/developer.chrome.com/pull/3837
