### ISSUE TITLE
Web-accessible resources section broken UI in V3 migration page

### ISSUE THREAD

**Issue by tuanddd** [GoogleChrome/developer.chrome.com#1978]
**Describe the bug**
Currently, the layout in Web-accessible resources is broken due to all the elements being wrapped inside a Columns block, the fix is to unwrap it. See image for more information.

**To Reproduce**
1. Go to [Manifest V3 migration, web-accessible resource section](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#web-accessible-resources)

**Expected behavior**
The elements are laid out in a way that ensures readability for users.

**Screenshots**
<img width="847" alt="Screen Shot 2022-01-19 at 16 44 40" src="https://user-images.githubusercontent.com/25856620/150108177-6c42d8cf-87dd-42ff-a9f0-f8ed86023a18.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 96.0.4664.110 (Official Build) (arm64)

**Smartphone (this bug is not present on mobile view):**

**Comment by dotproto** [comment]
Thanks for the report. It looks like I broke this when I merged PR #1953. I'll try to get a patch in shortly.
