### ISSUE TITLE
[Lighthouse content] Migrate Accessibility Audits

### ISSUE THREAD

**Issue by malchata** [GoogleChrome/developer.chrome.com#1997]

**Comment by brendankenny** [comment]
closed by https://github.com/GoogleChrome/developer.chrome.com/pull/3768 and https://github.com/GoogleChrome/web.dev/pull/8695 and

**Comment by thibaudcolas** [comment]
👋 is there information somewhere about the rationale for those changes? I regularly linked people to web.dev pages for Lighthouse accessibility audits, as I found their content tended to be more approachable than equivalent Axe documentation.

I see some of the audits are now on https://developer.chrome.com/docs/lighthouse/accessibility/ – it would be nice to better understand why things are moving around like this, and whether the final state will indeed be that different Lighthouse audits link to different websites.
