### ISSUE TITLE
Most of the links on the declare_permissions page are broken.

### ISSUE THREAD

**Issue by eliastheis** [GoogleChrome/developer.chrome.com#200]
In line 42:
Requests that the extension be granted permissions according to the [activeTab](activeTab) specification.

**Comment by robdodson** [comment]
I just looked at the page in question and it looks like most of the links are broken.
https://developer.chrome.com/docs/extensions/mv2/declare_permissions/

It looks like there's a bunch of markdown links at the bottom of the file but none of them are used. Instead there's an html table that's using relative links but those are all broken.

**Comment by robdodson** [comment]
this should be fixed now.
