### ISSUE TITLE
BackgroundFetch throws TypeError for chrome-extension: protocol

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#2001]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Neither the README.md https://github.com/WICG/background-fetch#readme, specification https://wicg.github.io/background-fetch/, MDN documentation https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API, nor https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/ explains that background fetch will throw for browser extension protocol (not HTTPS or HTTP).

**To Reproduce**

In an MV3 extension page (or in the `ServiceWorker` itself, substituting `self.registration` for `await navigator.serviceWorker.ready`) run the following code

```
try {
    const registration = await navigator.serviceWorker.ready;
    console.log(registration);
    const bgFetchReg = await registration.backgroundFetch.fetch('test', ['./stream']);
  } catch(err) {
    console.error(err);
  }
```
observe the `TypeError`
```
TypeError: Failed to execute 'fetch' on 'BackgroundFetchManager': Refused to fetch 'chrome-extension://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/stream' because only the https: scheme is allowed, or http: for loopback IPs.
```

**Expected behavior**
Documentation "only the https: scheme is allowed, or http: for loopback IPs.".

Alternatively, modify Chromium source code to allow chrome-extension: protocol for BackgroundFetch.

**Screenshots**
![background-fetch-type-error](https://user-images.githubusercontent.com/4174848/150691660-4796513b-cf43-4ba6-ae59-26022e5e00f5.png)

**Desktop (please complete the following information):**
Chromium 100.0.4847.0 (Developer Build) (64-bit) Revision 6c4a1b2ffb7f34ba6c5a9c34181bf72e1ac25e8d-refs/heads/main@{#962257}

**Smartphone (please complete the following information):**
N/A

**Additional context**
I could not find any documentation about "only the https: scheme is allowed, or http: for loopback IPs." in any BackgroundFetch documentations.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/324475531
