### ISSUE TITLE
Required components for feature parity with web.dev

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/developer.chrome.com#2007]
The following components are missing from developer.chrome.com when compared to web.dev or require different markup. I've ordered these in terms of priority.

1. Codelab callout `{% CodelabsCallout 'codelab-fix-sneaky-404', lang %}`
2. Figure - dcc requires the classes, web.dev now does not. Would be great to have these the same.
3. [CodePen](https://web.dev/handbook/web-dev-components/#codepen)
4. [Banners](https://web.dev/handbook/web-dev-components/#banners) 
5. [Blockquote with shortcode](https://web.dev/handbook/web-dev-components/#block-quotes)
6. [Columns](https://web.dev/handbook/web-dev-components/#columns) - on dcc these use a shortcode, web.dev uses the `switcher` class.
7. [Instructions](https://web.dev/handbook/web-dev-components/#instructions)
8. [Compat](https://web.dev/handbook/web-dev-components/#browsercompat) - lower priority on dcc as a lot of stuff on dcc this won't work on as we don't have compat data yet for experimental things. Though if we could design a good way to show this status so we could use the same widget that would be cool.

There are other components that don't exist on dcc but I'm not sure if they need to right now:

- [Self assessments](https://web.dev/handbook/self-assessment-components/)
- [Patterns](https://web.dev/handbook/web-dev-components/#codepattern)

**Comment by devnook** [comment]
A tracker list for prioritized components:

- [ ] Codelab callout {% CodelabsCallout 'codelab-fix-sneaky-404', lang %}
- [ ] Figure - dcc requires the classes, web.dev now does not. Would be great to have these the same.
- [ ] CodePen
- [ ] Banners
- [ ] Blockquote with shortcode
- [ ] Columns - on dcc these use a shortcode, web.dev uses the switcher class.
- [ ] Instructions

**Comment by mihajlija** [comment]
Adding thumbnails to the wishlist 🙏
