### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by mysterytony** [GoogleChrome/developer.chrome.com#201]
**Describe the bug**

A lot of links in chrome developer extension documentation are broken. E.g. 

>The completed extension can be downloaded *here*. <----

right above https://developer.chrome.com/docs/extensions/mv3/getstarted/#manifest

This is also true in many places in API references, e.g.: https://developer.chrome.com/docs/extensions/reference/windows/#manifest the `tabs.Tab` links are broken.

**Comment by robdodson** [comment]
> A lot of links in chrome developer extension documentation are broken. E.g.

> The completed extension can be downloaded here. <----
> right above https://developer.chrome.com/docs/extensions/mv3/getstarted/#manifest

@dotproto could you take a look at this one?

> This is also true in many places in API references, e.g.: > https://developer.chrome.com/docs/extensions/reference/windows/#manifest the tabs.Tab links are broken.

Assigning to @samthor

**Comment by mysterytony** [comment]
hey, thanks for looking into it

there are quite a few links broken for the extension documentation, I just run into them randomly 😕 

e.g. beneath https://developer.chrome.com/docs/extensions/mv2/getstarted/#manifest

>Extensions start with their *manifest*. <-- broken

e.g. beneath https://developer.chrome.com/docs/extensions/reference/storage/#overview

> This API has been optimized to meet the specific storage needs of extensions. It provides the same storage capabilities as the *localStorage API* <-- broken

e.g. beneath https://developer.chrome.com/docs/extensions/reference/storage/#manifest

>You must declare the "storage" permission in the *extension manifest* <-- broken

I don't have a strong clue to the pattern 🤷 , links to a section within the same page seem fine.
