### ISSUE TITLE
Breakpoints page has unrendered markup

### ISSUE THREAD

**Issue by mvdobrinin** [GoogleChrome/developer.chrome.com#2012]
**Describe the bug**
[A clear and concise description of what the bug is.](https://developer.chrome.com/docs/devtools/javascript/breakpoints/) has undrendered markup.

**To Reproduce**
Go to https://developer.chrome.com/docs/devtools/javascript/breakpoints/.

See `**Figure 8**: The **Pause on exceptions** button`

**Expected behavior**
Markdown is fully parsed and rendered to HTML.

**Screenshots**
![image](https://user-images.githubusercontent.com/1854768/150860387-a9656dc8-ccdd-4bbf-bb7d-77f6e97ab736.png)

**Comment by devnook** [comment]
This is fixed now.
