### ISSUE TITLE
Hyperlink is a localhost link

### ISSUE THREAD

**Issue by carsonsaldanha** [GoogleChrome/developer.chrome.com#2019]
**Describe the bug**
A hyperlink is set to localhost:8080 rather than the actual URL.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/privacy-sandbox/topics/#why-do-we-need-this-api
2. Click on the hyperlink "Privacy Sandbox" in the sentence "The Topics API is a Privacy Sandbox proposal for a mechanism to enable interest-based advertising, without having to resort to tracking the sites a user visits."
3. See error since the hyperlink is set to http://localhost:8080/docs/privacy-sandbox/overview/

**Expected behavior**
https://www.privacysandbox.com/ might be the correct URL.

**Comment by jeffposnick** [comment]
Thanks for reporting. This was fixed by #2123.
