### ISSUE TITLE
icon and locale fields in example not specified, do not work. This tutorial is not up to date.

### ISSUE THREAD

**Issue by GeordanKrahn** [GoogleChrome/developer.chrome.com#2028]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jpmedley** [comment]
@GeordanKrahn Thank your for submitting this. We need to know where the error is before we can fix it. Can you please provide a link?

**Comment by jeffposnick** [comment]
Closing, as it's not clear what content this issue refers to.
