### ISSUE TITLE
chrome.browserAction.openPopup exists in document, but it does not exist

### ISSUE THREAD

**Issue by hanguokai** [GoogleChrome/developer.chrome.com#204]
**Describe the bug**
For chrome.browserAction, in "old documents", I know there are getPopup and setPopup apis, but I don't remember there is an openPopup api. Now, openPopup in the "new document", and in my test it does not exist on stable chrome.

Is it a new feature in next chrome version? or a bug in document?

**To Reproduce**
1. visit https://developer.chrome.com/docs/extensions/reference/browserAction/#method-openPopup
2. Or see screenshot
<img width="795" alt="Screen Shot 2021-01-12 at 12 03 22 AM" src="https://user-images.githubusercontent.com/776467/104205788-c480b280-5469-11eb-8f42-cd5168613e63.png">

**Comment by hanguokai** [comment]
Find this https://bugs.chromium.org/p/chromium/issues/detail?id=436489 .
Looks like this api has never been available on stable chrome.

**Comment by samthor** [comment]
This is fixed but we need to do a new deploy.

**Comment by chen99-long** [comment]
at present, i am using the v3 version, and there is no way to use this api

**Comment by connorlindsey** [comment]
What's the status of this api? Completely understand any security concerns or other issues delaying it. 

In the meantime, what would be the best way to implement the same behavior? Currently thinking that instead of having a popup, using a content script which renders the same content in a modal. The service worker could open it when required, including when the browser action is clicked, but this loses out on the built-in behavior of the modal like closing when clicking outside.

**Comment by philippb** [comment]
This is till a problem. https://developer.chrome.com/docs/extensions/reference/action/#method-openPopup

<img width="753" alt="image" src="https://user-images.githubusercontent.com/374326/157882546-73759f8a-6012-44dc-8100-e60898977d69.png">

I'm testing this on Chrome `99.0.4844.51`

<img width="710" alt="image" src="https://user-images.githubusercontent.com/374326/157882602-3a00df1a-453b-46ef-813e-47e0e0e8ae3b.png">

and get the error

    Error handling response: TypeError: chrome.action.openPopup is not a function

Reading the documentation my understanding is that this should work with `version >= 99`.

thank you

**Comment by datgrog** [comment]
+1

**Comment by xde013** [comment]
@dotproto following the proposal document  [here](https://docs.google.com/document/d/1xzuw1dMuf5Lub8UPME2zjxyp3nCKXk-3jtSY2kdI-FQ/edit#) ` action.openPopup()` and Chrome documentation, it should be available but it's not available, even from a user action.

 It is quite confusing.  Do you have any ideas what can cause this? is it related to any of the following issues?
 [](https://bugs.chromium.org/p/chromium/issues/detail?id=1245093)
[](https://bugs.chromium.org/p/chromium/issues/detail?id=436489)

**Comment by Nick9499** [comment]
+1

**Comment by zycoJamie** [comment]
this problem has not resolved, now.
TypeError: chrome.action.openPopup is not a function.
