### ISSUE TITLE
Document natively_connectable

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#2050]
**Describe the bug**
`"natively_connectable"` is mentioned exactly once on the site at https://developer.chrome.com/docs/extensions/mv3/manifest/

**To Reproduce**
1. Visit https://developer.chrome.com/ 
2. Search "natively_connectable"

**Expected behavior**
A clear and concise description of what `"natively_connectable"` is, and how it works.

**Screenshots**
![Screenshot_2022-01-30_09-36-13](https://user-images.githubusercontent.com/4174848/151710590-66eafc9f-67cb-4aa3-9d6a-ec412ea770cb.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 100

**Additional context**

Source code: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/extensions/api/messaging/native_messaging_launch_from_native.cc

**Comment by jpmedley** [comment]
Consolidating this under #163
