### ISSUE TITLE
Should "Devtools > Console" cover JavaScript errors?

### ISSUE THREAD

**Issue by mpchadwick** [GoogleChrome/developer.chrome.com#2059]
**Is your feature request related to a problem? Please describe.**

I'm reviewing the Chrome dev tools documentation for training materials for a team of junior web developers. I noticed that under the Console Overview there's no mention to the fact that the console is the area to check for JavaScript errors on the page. This is one of the most common use cases for the Console in my experience. Should this not be covered in that document?

**Describe the solution you'd like**

Add a section to the Console Overview about viewing JavaScript errors

**Describe alternatives you've considered**

I checked if there was anywhere else that JavaScript errors were covered, but am not finding anywhere.

**Additional context**

N/A

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311789155
