### ISSUE TITLE
Footnote plugin and design

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/developer.chrome.com#2067]
**Is your feature request related to a problem? Please describe.**
We have a specific request around incorporating existing footnotes into the Privacy Sandbox site (#1952), and there are almost certainly other use cases for content footnotes.

**Describe the solution you'd like**
A [plugin for footnotes](https://www.npmjs.com/package/eleventy-plugin-footnotes) already exists for Eleventy.

**Describe alternatives you've considered**
It would be a valid choice to develop our own, non-plugin solution, or to use a kind of snippet.

**Comment by rachelandrew** [comment]
How would these display? What would be different about this content that makes it unsuitable for an aside for example? 

Not saying we shouldn't do them, just trying to understand the content requirement.

**Comment by devnook** [comment]
@heyawhite Can you provide examples asked for above?

**Comment by heyawhite** [comment]
I'm unsure this is needed anymore. We can address with asides. Will reopen if the request resurfaces from our stakeholders.
