### ISSUE TITLE
https://twitter.com/i/topics/1291673117010534401?s=20&t=BFuUt7KgIcfkA2G_I1_nKA

### ISSUE THREAD

**Issue by VictorBatta** [GoogleChrome/developer.chrome.com#2072]
### 
![Captura de pantalla 2022-02-02 - 13 59 50-fullpage](https://user-images.githubusercontent.com/80987400/152259778-eaa1ac34-ceb9-4dcd-8018-95175ef1e6d9.png)
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dotproto** [comment]
Closing as this issue does not contain a bug report.
