### ISSUE TITLE
Chrome Apps WebView tag URLs are redirecting to the wrong place

### ISSUE THREAD

**Issue by chasephillips** [GoogleChrome/developer.chrome.com#2077]
**Describe the bug**
Multiple Chrome Apps WebView tag URLs are redirecting to the Android WebView documentation.  This is wrong.. Chrome Apps WebView isn't related to Android WebView, and requests for that info need to be redirected to the right site at:
https://developer.chrome.com/docs/extensions/reference/webviewTag/

**To Reproduce**
URLs that show this problem and need to be fixed:
https://developer.chrome.com/apps/tags/webview
https://developer.chrome.com/docs/extensions/reference/webview/

An external site that used to be fine but is now going to the wrong site:
https://stackoverflow.com/questions/39087838/chrome-app-webview-alternative-in-html5

1. Go to either of the above URLs that I mention above.
2. Get redirected to Android WebView documentation.

**Expected behavior**
The browser should be redirected to one of these:
https://developer.chrome.com/docs/extensions/reference/webviewTag/
https://developer.chrome.com/docs/apps/app_external/ (but likely not this URL since it's about external content in general)

**Comment by petele** [comment]
I dug into this a bunch, and I think there may be a couple of issues here:

1. The word `tags` in the first URL isn't meant to 'tag' the content, but is a special HTML tag/element used in Chrome Apps a developer can include in their page. 
1. I suspect there's a complex redirect path that's happening, but I couldn't quite figure it out. After hitting any of the URLs Chase mentioned, the page is redirected several times before it finally lands on the Android webview content.
1. Some content was not migrated from the old site to the new site. Specifically the Chrome Apps `<webview>` tag docs. 
    * Compare the content from [archive.org](https://web.archive.org/web/20180114092251/https://developer.chrome.com/apps/tags/webview) with the [current content](https://developer.chrome.com/docs/extensions/reference/webviewTag/), only the API details appear. We've lost the Usage, Examples, Tag Attributes, etc. 
    * There's a [`<!-- TODO(samthor): Apps API only -->`](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/extensions/reference/webviewTag/index.md) in this source for this doc, I suspect Sam meant to insert the content before he left
    * This should be under `/docs/apps/` not `/docs/extensions/` as this is specifically a Chrome Apps tag

**Comment by dstmarthe** [comment]
Thanks for raising this, it's still relevant to this day. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324285774
