### ISSUE TITLE
saveAsMHTML's callback data type incorrectly listed as ArrayBuffer

### ISSUE THREAD

**Issue by erikbrinkman** [GoogleChrome/developer.chrome.com#2080]
**Describe the bug**
The documentation for [`pageCapture.saveAsMHTML`](https://developer.chrome.com/docs/extensions/reference/pageCapture/#method-saveAsMHTML) specifies that the callback receives an `ArrayBuffer`, but at least on 64-bit chrome 97 on windows, the callback actually receives a `Blob` object.

I'm not sure how the typing documentation is generated, since it seems like external pulls the json from a random s3 bucket. Looking over the chromium source, the result is a little mixed, but all seems to confirm the above behavior.
1. [this](https://source.chromium.org/chromium/chromium/src/+/main:third_party/closure_compiler/externs/chrome_extensions.js;l=5343-5348?q=saveAsMHTML) compiled version of the api lists it as a Blob,
2. [this](https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/data/extensions/api_test/page_capture/test.js) doesn't enforce it's a blob, but uses apis consistent with one
3. [this](chrome/common/extensions/api/page_capture.json) api page lists it as "binary" which may be what it's being pulled from, and may require a change to chromium source somewhere to parse correctly, but that's another rabbit hole I want to confirm first.

If it turns out that the s3 bucket is populated from 3, and "binary" is ambiguous, I'm happy to close this and submit a chromium bug report.

**To Reproduce**
- [ ] browse [here](https://developer.chrome.com/docs/extensions/reference/pageCapture/#method-saveAsMHTML) and notice it's wrong
- [ ] call `chrome.pageCapture.saveAsMHTML({ tabId }, blob => console.log(blob));` and see that it outputs `Blob {size: ..., type: ''}`

**Expected behavior**
Should specify that it takes a Blob.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 97

**Comment by nicolas377** [comment]
+1 to this, the docs are contradicting themselves. I'm happy to send a PR for this.

**Comment by tophf** [comment]
Judging by the [other jsons](https://source.chromium.org/search?q=%5C%22type%5C%22:%5Cs*%5C%22binary%5C%22%20file:json%20file:extension) `binary` type encompasses a lot of types. 

In [declarative_content.json](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/declarative_content.json) there's an additional `isInstanceOf` field to indicate the actual type.
It's [used by the official chrome-types parser](https://github.com/GoogleChrome/chrome-types/blob/4b6ac3a8e2b60061884261e9ea501e07a04493c2/tools/lib/render-context.js#L389), so I guess it can be used here as well.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324322292
