### ISSUE TITLE
Broken link in the "New in Chrome 98" announcement

### ISSUE THREAD

**Issue by rsocol** [GoogleChrome/developer.chrome.com#2081]
**Describe the bug**
In the page https://developer.chrome.com/blog/new-in-chrome-98/ there is a broken link to https://v8.dev/blog/v8-release-98

**To Reproduce**
1. Go to the "Further reading" section
2. Click on the fourth link ("[What's new in JavaScript in Chrome 98](https://v8.dev/blog/v8-release-98)")

**Expected behavior**
If there is no 9.8 release for v8, the link should be removed

**Comment by jeffposnick** [comment]
This was fixed by #2086.
