### ISSUE TITLE
New Issue Lacks types for content updates

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#2085]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**
The only issue types currently configured on this repo are for code: bug and feature request. Most of what comes it is for content.

![image](https://user-images.githubusercontent.com/8204171/152556932-2d34ae53-6b71-4d73-b143-b634aa974daa.png)

**Describe the solution you'd like**
web.dev has bugs for both proposing new content and correcting existing content.

**Comment by rachelandrew** [comment]
I'll figure out how to add these to this site as well.

**Comment by dstmarthe** [comment]
This seems like it can be applied to the new tracker too?

**Comment by rachelandrew** [comment]
We're using a different process, we can just close this.
