### ISSUE TITLE
Chrome extension docs search not working

### ISSUE THREAD

**Issue by wiscat** [GoogleChrome/developer.chrome.com#2094]
**Describe the bug**
Search over documentation not working

message: "Invalid Application-ID or API key"
status: 403

Request URL: https://0ppzv3ey55-1.algolianet.com/1/indexes/prod_developer_chrome/query?x-algolia-agent=Algolia%20for%20JavaScript%20(4.6.0)%3B%20Browser%20(lite)&x-algolia-api-key=f08cd9d7ead266781a7c2455b5f4a7b2&x-algolia-application-id=0PPZV3EY55
Request Method: POST
Status Code: 403 Forbidden

**To Reproduce**
1. Go to the https://developer.chrome.com/docs/extensions/reference/
2. Click on the search input
3. Type something to search
4. See empty screen

**Expected behavior**
Search works

**Screenshots**
<img width="1618" alt="2022-02-05 в 12 24 53" src="https://user-images.githubusercontent.com/16239030/152636519-22c5589b-488f-40ab-aed4-abb3db2f0438.png">

<img width="1629" alt="2022-02-05 в 12 35 28" src="https://user-images.githubusercontent.com/16239030/152636538-48d25d5d-f4e4-49ee-86cc-e9b1a65a2d54.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Version 97.0.4692.99

**Comment by rachelandrew** [comment]
@wiscat thanks for reporting this, it's now fixed.
