### ISSUE TITLE
YouTube shortcode should be the same as web.dev

### ISSUE THREAD

**Issue by petele** [GoogleChrome/developer.chrome.com#210]
**Describe the bug**
web.dev uses `{% YouTube 'video-id' %}` where as dcc uses `{% youtube id='NCKMMzVn1c8' %}`

**Comment by robdodson** [comment]
I'm kind of feeling like migrating the d.c.c. shortcode over to web.dev as the named arguments are a lot easier to manage. I bet it wouldn't be tooooo hard, just a bit of find and replace.

**Comment by petele** [comment]
I'm fine either way, just want consistent capitalization and params please! :)

**Comment by samthor** [comment]
Fixed now.
