### ISSUE TITLE
chrome 98 preflight negatively affected our operations

### ISSUE THREAD

**Issue by Maxhodges** [GoogleChrome/developer.chrome.com#2110]
https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/blog/private-network-access-preflight/index.md

This article could benefit by telling us how to report issues. It seems like they want to know about websites affected by this change (preflight) but they don't tell us how to reach them.

**Comment by agektmr** [comment]
Hi @Maxhodges,

Thank you for your feedback and this is a very good point. We should fix the article.
In the past we have put up a guide to report issues on crbug.com: https://web.dev/cors-rfc1918-feedback/#feedback-wanted

@letitz if you agree with this idea, I can add a section that describes how developers can send feedback.

**Comment by letitz** [comment]
I agree, adding such a section is a good idea!

@Maxhodges please feel free to file a bug against Chromium using the `Blink>SecurityFeature>CORS>PrivateNetworkAccess` component.
