### ISSUE TITLE
Add DevTools Issue details to user-agent reduction article

### ISSUE THREAD

**Issue by rowan-m** [GoogleChrome/developer.chrome.com#2116]
https://developer.chrome.com/docs/privacy-sandbox/user-agent/#prepare-and-test

DevTools will show an Improvement type Issue on access to `navigator.userAgent`. We should improve the article to highlight this and explain what the developer should do.

**Comment by rowan-m** [comment]
Also strengthen the message on high-entropy methods on first request being an extremely rare need.

**Comment by rowan-m** [comment]
Note: https://groups.google.com/a/chromium.org/g/blink-dev/c/JQ68cvYuiQU/m/S_33YSqxCwAJ
Meta tag option aiming for M100.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at:  https://issuetracker.google.com/issues/311272284
