### ISSUE TITLE
Show which Chrome version added support for returning promises from an extension methods

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#2117]
**Is your feature request related to a problem? Please describe.**

As Chrome's extensions APIs progressively gain promise support, extension developers are tripping over the gap between when a feature lands in Canary (what our documentation is generated off of) and when a feature lands in Stable (what the developer is targeting ([example](https://bugs.chromium.org/p/chromium/issues/detail?id=1291914)). 

Not having this information also creates issues for both developers and end users and developers are not able to determine the correct [minimum_chrome_version](https://developer.chrome.com/docs/extensions/mv3/manifest/minimum_chrome_version/) to use with their extension.

**Describe the solution you'd like**

The generated extensions API documentation should clearly state which Chrome version Promises support was added.

I'd suggest that we expose this in the "return value" section of a method's documentation. 

![suggestion](https://user-images.githubusercontent.com/1047763/153651208-d42e20ad-6859-4fb6-b54d-ab4350236287.png)

**Additional context**

This will likely require work in the chrome-types repo as I don't believe this information is currently exposed. The IDL and JSON files we crawl to extract type information from Chromium's source do not explicitly state which stable release added promise support. As such, we may need to diff against historical chrome-type output to determine when support was added.

**Comment by tophf** [comment]
FWIW, the [example](https://bugs.chromium.org/p/chromium/issues/detail?id=1291914) you've linked is about a different thing: supporting Promise internally inside executeScript's handler of the last executed result, so diffing chrome-types won't help with this particular example.

**Comment by dotproto** [comment]
Oh shoot, you're totally right, @tophf. Thanks for calling that out.

**Comment by MichaelSolati** [comment]
@dotproto hi there, left some thoughts/insight in GoogleChrome/chrome-types#35 let me know if that helps and if there is anything else I can help you out with.

**Comment by AmySteam** [comment]
Fixed in https://github.com/GoogleChrome/chrome-types/pull/45
