### ISSUE TITLE
missing links

### ISSUE THREAD

**Issue by Nosense363** [GoogleChrome/developer.chrome.com#2130]
https://github.com/WICG/trust-token-api/commit/4102d816fed05dff140b9736759951ea0daf5189

**Comment by Nosense363** [comment]
missing links

**Comment by jeffposnick** [comment]
Could you please clarify what links are missing? You've shared a commit to the `trust-token-api` repo, but it's not clear how that relates to missing links on `developer.chrome.com` content.
