### ISSUE TITLE
Need aside from web.dev

### ISSUE THREAD

**Issue by petele** [GoogleChrome/developer.chrome.com#214]
https://web.dev/handbook/web-dev-components/#asides

**Comment by robdodson** [comment]
ah, these are available but poorly documented.

We don't use shortcodes for these anymore, instead you do:

```md
!!!.aside.aside--caution
your text goes here
!!!
```

This allows you to do markdown reference links like

```md
!!!.aside.aside--caution
your link[1]
!!!

[1]: http://google.com
```

**Comment by robdodson** [comment]
assigning to myself to document this better

**Comment by samthor** [comment]
These are available as `{% Aside %}` now, same as web.dev, and documented here: developer.chrome.com/docs/handbook/components/#asides
