### ISSUE TITLE
Support dates for Chrome Apps don't match those communicated on Chromium blog

### ISSUE THREAD

**Issue by alexhutcheson** [GoogleChrome/developer.chrome.com#2141]
The Chromium blog [posted an announcement on 2021-10-14](https://blog.chromium.org/2021/10/extending-chrome-app-support-on-chrome.html) that stated:

> Based on feedback from our Enterprise and Education customers and partners, we have made the decision to extend [Chrome app](https://developer.chrome.com/docs/apps/) support for those users on Chrome OS until at least January 2025.

However, this does not appear to be reflected on developer.chrome.com.

https://developer.chrome.com/docs/apps/ states:

> Chrome Apps provided Chrome-specific APIs on top of standardized web technologies to enable you to create experiences that had more access to the underlying operating system. They were deprecated in 2020. Support for all platforms will end in June 2022.

https://developer.chrome.com/docs/apps/migration/ also links to the [older blog post](https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html) (from 2020-08-10, rather than the most up-to-date one from 2021-10-14).

**Comment by dstmarthe** [comment]
This has been fixed now.
