### ISSUE TITLE
Support timeline for NaCl is unclear

### ISSUE THREAD

**Issue by alexhutcheson** [GoogleChrome/developer.chrome.com#2142]
https://developer.chrome.com/docs/native-client/migration/ says:

> we plan to focus our native code efforts on WebAssembly going forward and plan to remove support for PNaCl in Q4 2019 (except for Chrome Apps)

https://developer.chrome.com/docs/native-client/ says:

> It was deprecated in 2020 and support will end in June 2021.

https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html says:

> June 2022: End support for Chrome Apps, NaCl, PNaCl, and PPAPI for all platforms.

https://blog.chromium.org/2021/10/extending-chrome-app-support-on-chrome.html says:

> Based on feedback from our Enterprise and Education customers and partners, we have made the decision to extend [Chrome app](https://developer.chrome.com/docs/apps/) support for those users on Chrome OS until at least January 2025.

But it's unclear if the extended support window for Chrome Apps also applies ot NaCl or PNaCl.

Ideally, developer.chrome.com would have a support matrix detailed expected end-of-support dates for NaCl and PNaCl, sliced by the following dimensions:

- Chrome Extension vs. Chrome App
- Operating system
- Enterprise/Education user vs. general public

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311237037
