### ISSUE TITLE
[DNR] Update declarativeNetRequest documentation page

### ISSUE THREAD

**Issue by Celsius273** [GoogleChrome/developer.chrome.com#216]
Update the declarativeNetRequest page so it includes the documentation for the global rule limit that were updated in chromium but were not ported over to developer.chrome.com

**Comment by dotproto** [comment]
@Celsius273, are the global rule limit values defined in IDL or are they hand-written? If it's an IDL issue, I believe that @samthor is working on including missing consts in the API docs. If it's hand-written content, then we may have had a situation during the migration where an update was made to Chromium but not this repo causing the loss of information.

**Comment by Celsius273** [comment]
the per-extension guaranteed minimum is defined in idl, the shared global limit is defined in C++ and its value should not be known to extensions
