### ISSUE TITLE
setIcon() doesn't work in service worker context

### ISSUE THREAD

**Issue by thdoan** [GoogleChrome/developer.chrome.com#2165]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The alarm example as given in https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#alarms doesn't work in a service worker context -- getting "Uncaught (in promise) TypeError: failureCallback is not a function" error.

I believe this is a known bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1262029&q=setIcon&can=2

**To Reproduce**
Use the code as provided in the example:
```
// background.js
chrome.alarms.create({ delayInMinutes: 1 });

chrome.alarms.onAlarm.addListener(() => {
  chrome.action.setIcon({
    path: {
      '16': 'images/icon2.png',
      '24': 'images/icon2.png',
      '32': 'images/icon2.png'
    }
  });
});
```

**Expected behavior**
Icon should be updated a minute later.

**Screenshots**
![image](https://user-images.githubusercontent.com/4110567/155244666-a8d0e4bb-492b-420f-b2c5-b0a1a1c5fe92.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 98.0.4758.102 (Official Build) (64-bit)

**Comment by guest271314** [comment]
Are you trying to set the icon on the toolbar?

**Comment by guest271314** [comment]
The toolbar icon does update, the extensions management page (chrome://extensions) icon does not update.

**Comment by guest271314** [comment]
The documentation is incomplete re `setIcon()` https://developer.chrome.com/docs/extensions/reference/action/#method-setIcon.

When the `path` is a directory prepend a forward slash `/` to the string.

```
function handleAlarm(alarm) {
  chrome.action.setIcon({
    path: {
      '16': '/images/icon-white.png',
      '24': '/images/icon-white.png',
      '32': '/images/icon-white.png'
    }
  });
}
```

**Comment by guest271314** [comment]
There are two problems. 

1. The documentation is incomplete.
2. The `extensions::setIcon:35 Uncaught (in promise) TypeError: failureCallback is not a function` is not caught by `try..catch`
```
async function handleAlarm(alarm) {
  try {
    await chrome.action.setIcon({
      path: {
        16: 'images/icon-white.png',
        24: 'images/icon-white.png',
        32: 'images/icon-white.png',
      },
    });
  } catch (err) {
    console.error(err);
  }
}
```

> but is this a bug or a design change?

Obvious bug(s).

> Also, if this is a design change, then this bug ticket stands -- Google should update all the documentation to reflect the requirement of the leading slash.

Yes.

You can file a PR to fix the documentation relevant to prepending forward slash(es) for directories in the extension.

Extension authors need to fix their broken source code relevant to handling errors.

**Comment by guest271314** [comment]
By 

> Extension authors need to fix their broken source code relevant to handling errors.

I mean Chromium/Google Chrome source code authors, not developers in the field.

**Comment by tophf** [comment]
In MV3 the current path of the background script is the script's path i.e. `js/` in your case, which is why you need to use an absolute path. In MV2 when you declare `scripts` the background page is auto-generated at the root of the extension which is why relative paths worked.
