### ISSUE TITLE
chome-extension documention  - omnibox.onInputChanged Event

### ISSUE THREAD

**Issue by wzddl** [GoogleChrome/developer.chrome.com#2175]
**Describe the bug**

**chrome.omnibox.onInputChanged** EventListener throw error...

**Screenshots**

![code](https://pic.imgdb.cn/item/6218a5202ab3f51d91c1af11.png)
![error](https://pic.imgdb.cn/item/6218a5202ab3f51d91c1af18.png)

URL： 
https://developer.chrome.com/docs/extensions/reference/omnibox/#event-onInputChanged

I don't know whether there is a problem with the document description or chrome has changed the extension API
This problem points to that **ServiceWorker** does not have a **DOMParser** object

**Desktop:**

 - OS: Windows
 - Browser chrome, edge ... etc...
 - Version: 98.0.4758.102

**Comment by tophf** [comment]
It's a [bug in Chrome](https://crbug.com/1186804). The documentation should mention that until it's fixed and shipped in stable Chrome (100 or 101 probably) this API is dysfunctional in ManifestV3.

**Comment by wzddl** [comment]
> It's a [bug in Chrome](https://crbug.com/1186804). The documentation should mention that until it's fixed and shipped in stable Chrome (100 or 101 probably) this API is dysfunctional in ManifestV3.
thanks, I got it...

**Comment by wzddl** [comment]
> It's a [bug in Chrome](https://crbug.com/1186804). The documentation should mention that until it's fixed and shipped in stable Chrome (100 or 101 probably) this API is dysfunctional in ManifestV3.
The bug fixed on chromium **100.0.4896.20** 
![testScreenShot](https://pic.imgdb.cn/item/6222f5215baa1a80ab326b22.png)

**Comment by mituBarua** [comment]
how did you solve it? can you share?

**Comment by tophf** [comment]
You need to use Chrome 100 or newer.

**Comment by wzddl** [comment]
> how did you solve it? can you share?
solved by use Chromium 100+ 's browser

**Comment by oliverdunk** [comment]
It looks like this is fixed now, closing.
