### ISSUE TITLE
Icon not rendering on docs/privacy-sandbox/#measure-digital-ads

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/developer.chrome.com#2190]
Little notes icon is not rendering in `measure-digital-ads` section and the TOC is displaced due to that. Likely some yaml formatting issue or something about the type of posts that are in that section. 

cc @heyawhite @maudnals 

<img width="980" alt="Screenshot 2022-02-28 at 10 27 38" src="https://user-images.githubusercontent.com/17127567/155958596-af56bf98-7629-4ee5-ad57-419cc3c35a60.png">

**Comment by myakura** [comment]
it looks like the structure of the section is slightly different from others.

https://github.com/GoogleChrome/developer.chrome.com/blob/38be041cde9c8ffbd7cfa41db48fa968137bbad9/site/_data/docs/privacy-sandbox/toc.yml#L28-L44

**Comment by rowan-m** [comment]
Site layout isn't really set up for deeper levels of TOC entries. I can quickly tweak to look like this instead:
![Screenshot 2022-02-28 10 21 00](https://user-images.githubusercontent.com/108052/155966699-9bfec733-7a39-4f58-a233-42eae472c9ac.png)

**Comment by rowan-m** [comment]
Fixed in #2202
