### ISSUE TITLE
DevTools Post contains hard-to-read text.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#2210]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
A look at the current blog page shows the problem.  The screen capture below doesn't quite convey this because it increases the size. The text is nearly unreadable and it's not at all accessible.

![image](https://user-images.githubusercontent.com/8204171/156404451-ebdcd5c8-78a6-4708-b3e3-7d1d96cad43d.png)

**Expected behavior**
I suggest conveying this information in the article introduction.

**Comment by jeffposnick** [comment]
I believe this was fixed in https://github.com/GoogleChrome/developer.chrome.com/pull/2247, as https://developer.chrome.com/en/blog/new-in-devtools-99/ no longer has that hero image.
