### ISSUE TITLE
Improve docs for onConnectExternal

### ISSUE THREAD

**Issue by mikob** [GoogleChrome/developer.chrome.com#2225]
**Describe the bug**
https://developer.chrome.com/docs/extensions/reference/runtime/#event-onConnectExternal
Currently docs say: "Fired when a connection is made from another extension (by [runtime.connect](https://developer.chrome.com/docs/extensions/reference/runtime/#method-connect))."

**Expected behavior**
Should say "Fired when a connection is made from another extension, or externally connectable website...

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311270319
