### ISSUE TITLE
Broken Markdown: Bold text not been properly displayed in breakpoints section

### ISSUE THREAD

**Issue by ssolunna** [GoogleChrome/developer.chrome.com#2227]
**Describe the bug**
The document is showing the markdown syntax instead of displaying the text in bold.

**To Reproduce**
1. Go to [Pause your code with breakpoints](https://developer.chrome.com/docs/devtools/javascript/breakpoints/)
2. Scroll down to 'Exception breakpoints'
3. See bug in `**Figure 8**: The **Pause on exceptions** button` (below the figure)

**Expected behavior**
The text between `**` should be displayed in bold:
> **Figure 8**: The **Pause on exceptions** button

**Screenshots**
![Screenshot_2022-03-03_23-53-20](https://user-images.githubusercontent.com/65374099/156702952-639dcf0e-2737-4d96-b2f1-a45d7a314690.png)

**Desktop:**
 - OS: Linux
 - Browser: Chrome
 - Version: 98.0.4758.102

**Comment by sofiayem** [comment]
Fixed by #3251
