### ISSUE TITLE
Extension icon "WebKit" support text invalid - SVG doesn't work in Web Store

### ISSUE THREAD

**Issue by OllieJC** [GoogleChrome/developer.chrome.com#2240]
**Describe the bug**
Text about extension icon support is incorrect.

The incorrect text `any format supported by WebKit` can be found here: (https://developer.chrome.com/docs/extensions/mv3/manifest/icons/) https://github.com/GoogleChrome/developer.chrome.com/blob/acb3a831c2a37623d3a912bf56598e086fb657ac/site/en/docs/extensions/mv3/manifest/icons/index.md?plain=1#L15

SVG isn't supported once the package is published to the Web Store. The developer portal displays an SVG icon fine with no errors but after successful publication an install attempt fails.

**To Reproduce**
1. Create an extension with an SVG icon
2. Upload extension to `Chrome Web Store Developer Dashboard` (no error)
3. Publish extension (again, no error)
4. View the published extension (also no error)
5. Go to install extension from `Chrome Web Store` extension page
6. See error

**Expected behavior**
SVG icons are supported, or an error is raised at the point an extension is uploaded to the `Chrome Web Store Developer Dashboard`

**Screenshots**
_Didn't get one from the `Chrome Web Store` extension page on install unfortunately_

**Desktop (please complete the following information):**
_N/A_

**Smartphone (please complete the following information):**
_N/A_

**Comment by AmySteam** [comment]
@OllieJC Thanks for pointing this out! :) 👍  I added a caution note to [mv3/manifest/icons/](https://developer.chrome.com/docs/extensions/mv3/manifest/icons/)
