### ISSUE TITLE
chrome API don't have attribute instanceID

### ISSUE THREAD

**Issue by shaoshenchen** [GoogleChrome/developer.chrome.com#2241]
hello! I want to get the chrome extension instance id such as 

<img width="422" alt="image" src="https://user-images.githubusercontent.com/45918719/156960853-96d8352b-62e3-43b4-9957-6916dda8ea18.png">

howerer, when I found that the api `chrome.instanceID.getID` can do this. I try to use [this api](https://developer.chrome.com/docs/extensions/reference/instanceID/#method-getID), but it cannot work!

Looking forward to your help! Thanks~☺️

**Comment by guest271314** [comment]
Try using `chrome.runtime.id;`
