### ISSUE TITLE
Text in code block is too big, results in 80 char lines being cut off

### ISSUE THREAD

**Issue by petele** [GoogleChrome/developer.chrome.com#226]
**Describe the bug**
I would expect to be able to have an 80 character line and have it fit within a code block without needing to scroll.

**To Reproduce**
1. Create a markdown code block wrapped in triple backticks
2. 80 characters to the line

**Expected behavior**
I'd expect to see all 80 characters, no horizontal scroll

**Screenshots**
The commented line below is exactly 80 characters, and the last 3.5 characters are outside the viewport.

<img width="787" alt="Screen Shot 2021-01-12 at 11 49 59 AM" src="https://user-images.githubusercontent.com/718038/104345889-d21b5400-54cc-11eb-921e-6bce432ea33d.png">

I ran across this in several of the Chromium Chronicle posts (#215), and suspect we'll see it else where.

**Comment by robdodson** [comment]
yeah i've been meaning to bump the code font size down a tad.
