### ISSUE TITLE
Broken links on '/docs/extensions/reference/runtime/' page

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/developer.chrome.com#2277]
**Describe the bug**
Two links have their Markdown syntax displaying and are not rendering as links. And both of the links in discussion lead to 404

- https://developer.chrome.com/docs/extensions/options
- https://developer.chrome.com/docs/extensions/optionsV2

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/reference/runtime/#method-openOptionsPage'
2. See error

**Expected behavior**
Links to render as `<a>` tags. I'd expect `[options_ui](https://developer.chrome.com/docs/extensions/optionsV2)` to be linking to the equivalent MV3 options page and I'm not sure about https://developer.chrome.com/docs/extensions/options

**Screenshots**
<img width="766" alt="Screen Shot 2022-03-10 at 9 22 33 PM" src="https://user-images.githubusercontent.com/48612525/157807375-e8101165-55a3-434c-b5b0-cefb28b17150.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [Version 99.0.4844.51 (Official Build) (x86_64)]

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by jeffposnick** [comment]
The underlying source for this HTML is https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/api/runtime.json;l=173-183?q=Open%20your%20Extension%27s%20options%20page&ss=chromium%2Fchromium%2Fsrc:extensions%2F

I'm not sure how this gets updated, though. @dotproto, do you know who to ping about this?

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://buganizer.corp.google.com/issues/310709341

**Comment by tannerdolby** [comment]
@dstmarthe You're welcome. Sounds good, thanks for the heads up!
