### ISSUE TITLE
Document background.service_worker location requirements

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#228]
Update the getting started guide and manifest.json documentation to indicate that the service worker must be located in the extension's root directory.

**Comment by robdodson** [comment]
@dotproto would you mind creating assignees for these tickets. Also I don't know if they need to use the `bug` label if they aren't bugs. Maybe we either have them be unlabled or add a `chore` label?

**Comment by dotproto** [comment]
Generally I'm on board with using `chore` as a cleanup, but right now this requirement is undocumented and trying to load a service worker from another directory will cause your extension to silently fail to load. That gap feels more like a bug to me.
