### ISSUE TITLE
[manifest.content_security_policy] Invalid value for 'content_security_policy.sandbox'.

### ISSUE THREAD

**Issue by HomyeeKing** [GoogleChrome/developer.chrome.com#2280]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

as the [docs](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#content-security-policy) refers, 
there's a `sandbox` option

**Screenshots**
![image](https://user-images.githubusercontent.com/49113249/157841011-3d0115bf-e3ab-4142-9dd6-0580589cbd08.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  : macOS
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 99.0.4844.51 arm64

**Comment by oliverdunk** [comment]
It's unclear exactly what value was tried. We have an issue at https://github.com/GoogleChrome/developer.chrome.com/issues/1351 tracking updating what we suggest in the documentation, so closing this in favor of that.
