### ISSUE TITLE
Can't see language-select elements

### ISSUE THREAD

**Issue by mbiesiad** [GoogleChrome/developer.chrome.com#2281]
**Describe the bug**
At this moment, the items of the list Choose language (language-select) are not visible using dark mode.
Appearance improvement for the list of languages. More informations below.

**To Reproduce**
1. Go to https://developer.chrome.com/en/
(important! using **dark mode** for OS and/or Chrome browser)
3. Scroll down to 'Choose language'
4. Click on the mentioned element to see the available languages.
5. See issue

**Expected behavior**
The list is visible regardless of the mode light/dark/etc.

**Screenshots**

Basic view (the list is not expanded):
![image](https://user-images.githubusercontent.com/18367606/157872783-f6da4d84-8abe-480e-be76-01e3b266fc58.png)

Expanded list view:
![image](https://user-images.githubusercontent.com/18367606/157872986-53eb1e70-95e7-4dcf-a2c4-48316f1e77db.png)

Other example of the issue:
![image](https://user-images.githubusercontent.com/18367606/157873117-c2cdadaa-c11a-4d16-8fac-b59d1bc5cd26.png)

![image](https://user-images.githubusercontent.com/18367606/157873986-47bbecb3-6416-4c01-9af9-4f1cf34298e5.png)

View with light mode looks like here (correct):
![image](https://user-images.githubusercontent.com/18367606/157877986-8952367e-b4b7-4c97-9a88-e001ff3e5f85.png)

Example with correct view (with dark mode; for site https://developers.google.com/web/tools/chrome-user-experience-report/)
![image](https://user-images.githubusercontent.com/18367606/157879831-8afe44f3-35e2-41a3-81fc-4e770a1be656.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 99

Best wishes,
Michal

**Comment by jeffposnick** [comment]
This appears to be a Windows-specific issue, as the text appears correctly on a Mac in dark mode:
![Screen Shot 2022-03-14 at 11 36 05 AM](https://user-images.githubusercontent.com/1749548/158207195-aa41274a-7de8-4d0f-bd4d-29cd9bf6634b.png)

**Comment by mbiesiad** [comment]
Thank you for your comment & update here.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.

**Comment by mbiesiad** [comment]
Thanks for update here. I can confirm - looks fine now.
