### ISSUE TITLE
当我开发插件时，页面被屏蔽！

### ISSUE THREAD

**Issue by ittking** [GoogleChrome/developer.chrome.com#2282]
访问内置页面：chrome-extension://piceipoopikneajaopihamhgcfhkkfha/pages/options.html

error：piceipoopikneajaopihamhgcfhkkfha 已被屏蔽此页面已被 Chrome 屏蔽
ERR_BLOCKED_BY_CLIENT

刷新页面即可正常访问，但通过window.open打开第一次就会被屏蔽，请问是什么原因导致的呢？

**Comment by jeffposnick** [comment]
Unfortunately, this GitHub issue tracker can't be used to ask questions or report issues with Chrome Extensions.

**Comment by xiaolushuo** [comment]
> 组合访问页面：chrome-extension://piceipoopikneajaopihamhgcfhkkfha/pages/options.html
> 
> 错误：piceipoopikneajaopihamhgcfhkkfha 已被屏蔽 此页面已被 Chrome 屏蔽 ERR_BLOCKED_BY_CLIENT
> 
> 打开页面可以正常访问，但通过窗口打开第一次发现被屏蔽，请问是什么原因导致的呢？

你好，请问解决了吗，我也遇到了同样的问题

**Comment by leacoleaco** [comment]
同问

**Comment by herbphilpsh** [comment]
Yikes
