### ISSUE TITLE
Update payment deprecation docs with more detail on what to expect

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#229]
I drafted the following information for a post in the [chromium-extensions Google Group](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-extensions). Integrate this information with the payment deprecation docs and iterate as appropriate.

> So, let's get into what will happen on Feb 1st, 2020. Starting on this day, users will not be able to acquire items that require an upfront payment. The item's listing will still be visible in CWS, but users will not be able to purchase it. Chrome instances that already have the extension installed will not be affected. Users that have licenses for this item will still be able to download and install it, and they will continue to be able to do so until the licensing API is deprecated "at some future time." That point no one will be able to download the item as there will be no way to determine who should have access.
> 
> In order for your extensions to be available to all users, you will need to change the extension's payment settings from CWS Payments to either 'free' or 'third party payments'. Apologies, I can't remember the exact strings in the developer dashboard offhand. Note that when you make this change the extension will be available to all users. As such, before you make this change you should make sure that your extension has been updated to integrate with the third-party payment system and that premium features are gated on appropriate license checks.

**Comment by jpmedley** [comment]
This is for something that's long past, so closing.
