### ISSUE TITLE
links redirects are broken, cannot open old articles

### ISSUE THREAD

**Issue by kaczor6418** [GoogleChrome/developer.chrome.com#2291]
**Describe the bug**
I cannot find old articles which I could read at https://developers.google.com/web platform. For example, I cannot find Jake Archibald article about service-workers lifecycle. When I try to open this url: https://developers.google.com/web/fundamentals/primers/service-workers, I will be redirected to https://developer.chrome.com/docs/workbox/service-worker-overview/ what is different. What's more If I open https://developer.chrome.com/docs/workbox/service-worker-lifecycle/ in the end I can find such information:

>For those interested in a deeper dive into this subject, it's worth checking out [this article by Jake Archibald](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle). There's tons of nuance in how the whole dance around the service lifecycle goes, but it is knowable, and that knowledge will go far when using Workbox.

But this article by Jake Archibald is not available, if I click this link it points to the same page (https://developer.chrome.com/docs/workbox/service-worker-lifecycle/)

**To Reproduce**
1. Go under this link https://developer.chrome.com/docs/workbox/service-worker-lifecycle/
2. Scroll to the bottom (just the end of the article)
3. click [this article by Jake Archibald](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle)
4. Page has been refreshed, I am redirected to the same page

**Expected behavior**
Be able to find and open old articles. Links should redirect to correct source

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [chromium]
 - Version [99.0.4844.51 (Official Build) Arch Linux (64-bit)]

**Additional context**
I really don't like  that I cannot find old articles. I also have prepared a presentation for GDSC workshops where I was showing this article, and now it is impossible, so it breaks my presentation some way.

**Comment by kaczor6418** [comment]
If think this PR https://github.com/google/WebFundamentals/pull/9528 is the reason of this issue.
I have created a PR which in my opinion should solve this problem. You can find it here:
https://github.com/google/WebFundamentals/pull/9536

**Comment by rachelandrew** [comment]
Hi - the team assessed the articles and decided to redirect that one to newer content, we are closing down the old site so creating a PR to put the content back isn't helpful as it will be removed again.

There will be some internal links that need fixing once all this redirecting has been completed (things linking to older content) which I'll be tidying up as we go.

cc: @jpmedley as this was one you flagged to delete and redirect to the new content.

**Comment by jeffposnick** [comment]
CC: @malchata, as I think Jake's service worker lifecycle doc was one of the ones we had discussed porting over independently from the Workbox docs?

**Comment by kaczor6418** [comment]
Thanks, @malchata. Is there anything I can do about this to help you, or you will take care of this?

Yesterday I have created a PR https://github.com/google/WebFundamentals/pull/9536/files, but I think this is not the way you want to go, although  maybe we could revert changes only for:
```
- from: /web/fundamentals/primers/service-workers/lifecycle
  to: https://developer.chrome.com/docs/workbox/service-worker-lifecycle/
```
> And revert all files related to this redirect
Then redirect shouldn't be a trigger and users like me will be able to find this article much easier.

This is kind of work-around solution but maybe until you will not prepare appropriate port to web.dev it can stay. What do you think of this?

**Comment by malchata** [comment]
@kaczor6418, this article is now migrated to https://web.dev/service-worker-lifecycle/ and https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle now redirects to the migrated version.
