### ISSUE TITLE
Update extensions documentation on using Google Analytics 

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#2292]
**Describe the bug**
Update the Chrome Web Store documentation to provide guidance for setting Google Analytics. 

**To Reproduce**
1. Go to the webstore docs on [Google Analytics](https://developer.chrome.com/docs/webstore/manage/#google-analytics)
2. Note that these docs do not describe how to get a working `UA-*` value.

**Expected behavior**
This seciton should link to the relevant Google Analytics [support article](https://support.google.com/analytics/answer/10269537) to properly guide developers.

**Additional context**

- [chromium-extensions thread](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/nFTf2E9K7jw/m/kqGExBDNAgAJ)
- [MV2 docs](https://developer.chrome.com/docs/extensions/mv2/tut_analytics/) 
- [Webstore docs](https://developer.chrome.com/docs/webstore/manage/#google-analytics)

**Comment by AmySteam** [comment]
Fixed in #6799
