### ISSUE TITLE
Clarify interest-cohort Feature Policy directive in Browser Topics API

### ISSUE THREAD

**Issue by bershanskiy** [GoogleChrome/developer.chrome.com#2296]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The Topics API documentation mentions the `interest-cohort` directive, even though it does not work anymore.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/privacy-sandbox/topics/#opt-out
2. See mention of `interest-cohort`
3. Try to use it and see the following error:
![image](https://user-images.githubusercontent.com/45960703/158348439-328cf7df-7aaf-4004-887d-f406c5d3c8fc.png)

**Expected behavior**
Since `interest-cohort` was removed from Chromium, documentation should not mention it either.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

**Additional context**
Chromium removed interest-cohort Feature Policy directive in this commit:
https://github.com/chromium/chromium/commit/9255aecd4114c0b3da4016f641316367112adb53

**Comment by jeffposnick** [comment]
@samdutton, that appears to be your doc. Can you take a look?

**Comment by samdutton** [comment]
Hi @bershanskiy! Thanks for the issue and PR.

The article describes the proposal for the Topics API, which hasn't yet been implemented in a browser, so the aside about `interest-cohort=()` is really only relevant in that context: 'The Topics explainer also proposes ...' from the previous paragraph. 

Is there a way we can make this clearer?

**Comment by bershanskiy** [comment]
> Essentially, they get merged as an OR. That is, if EITHER the interest-cohort OR the browsing-topics directive turns off the API, then the API is off. In terms of interaction, these are separate, independent directives. They both forbid topic calculation on a page, but they don't affect each other. As you suggest, we should probably explain that somewhere.

Is there a documentation anywhere about this? Could you clarify what happens in the following cases?
```
Permissions-Policy: interest-cohort=(), browsing-topics=(self "https://example.com")
Permissions-Policy: interest-cohort=(self "https://example.com"), browsing-topics=()
```

**Comment by samdutton** [comment]
If either directive turns off the API, then topic calculation is forbidden for the page.

So: topic calculation is forbidden in both of these cases.
