### ISSUE TITLE
Change keyboard shortcut for increment by 100 (Windows, Linux)

### ISSUE THREAD

**Issue by Porphyrogennitos** [GoogleChrome/developer.chrome.com#2300]
[`Shift` + `Page Up` won't increment value by 100 but by 10 (4th bullet point, Windows and Linux)](https://developer.chrome.com/docs/devtools/css/reference/#values-shortcuts).

1. Inspect an element
2. Change a number declaration value with the above shortcut

It should add 100, not 10.

 - Linux
 - Chrome
 - 99

**Comment by jeffposnick** [comment]
This appears to be a bug report related to the functionality of Chrome's DevTools, not with the documentation. Please use https://crbug.com/new to report bugs in DevTools.
