### ISSUE TITLE
Force print preview mode

### ISSUE THREAD

**Issue by kamranx** [GoogleChrome/developer.chrome.com#2308]
https://developer.chrome.com/docs/devtools/css/print-preview/

in the link above:
3. Under "**Emulate CSS media**" select **print**. -----> has changed the name to "**Emulate CSS media _type_**" and even doesn't work.

[Chrome 99 on Linux](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have)

![Screenshot from 2022-03-16 11-40-18](https://user-images.githubusercontent.com/99621930/158554840-0678b77c-76f3-44de-8a61-f6af18497ff7.jpg)

**Comment by jeffposnick** [comment]
It sounds like this is a two part issue:

- There's a slightly out of date screenshot and text in https://developer.chrome.com/docs/devtools/css/print-preview/. I can file a PR to get the article text updated, but generally speaking, we're not able to adjust screenshots whenever small changes are made to the UI of Chrome.

- You're experiencing a bug in Chrome's DevTools related to accurately emulating the `print` media type. For that, we unfortunately can't help you in this issue tracker. Please use https://crbug.com/new to report that to the Chrome DevTools team.
