### ISSUE TITLE
How to remove transparent circles that show up when i drag on the Dev tools

### ISSUE THREAD

**Issue by canlucilleluna** [GoogleChrome/developer.chrome.com#2325]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
I need help, I am doing a designs simulation on the Mobile version of Canva using Google chrome's Dev tools.
When I drag the circle handles of an element, these semi-transparent circles show up and I think based on touch/hold.
how can I prevent these semi-transparent circles from showing? it shows up when I drag the circle handles.
I tried making a custom device and switching to no-touch but when we do, the lower menu of Canva doesn't scroll like how we do on a Mobile phone. and we want to emulate that like scrolling sideways to see the menu.

**To Reproduce**
1. have a design open in Canva (canva.com)
2. then switch to Developer tools and we use a preset, Iphone 6/7/8 plus
3. Add an element (graphics) by going to the purple button at the lower right. click Elements tab. then add any element (graphics)
4. when its added in the design, select it and there should be handles that show up for you to be able to resize the element (graphics)
5. click one of the white circle handles and try to resize.
6. when you use the preset (mobile touch) the transparent circle appears while moving the circle handles. and you can go to the lower menu and try to swipe to left like how fingers does on mobile phone.
7. But when we try to create a custom device, with Mobile (no touch) as settings. we cant recreate or simulate the swipe to left at the menu. but the transparent circle does not show up anymore.
We just need the transparent circle not showing because we are also recording the simulation.

**Expected behavior**
We just need the transparent circle not showing because we are also recording the simulation.

**Screenshots**
![Scre
![Screen Shot 2022-03-18 at 11 03 02 AM](https://user-images.githubusercontent.com/101693067/158930971-6cef7b04-9da5-401a-905c-3204881c0f3b.png)
en Shot 2022-03-18 at 11 02 43 AM](https://user-images.githubusercontent.com/101693067/158930969-998a2efc-bbf5-4100-8898-e904f6429ec3.png)

**Desktop (please complete the following information):**
 - OS: Macbook Pro and Windows 11 (we have a mix team)
 - Browser: Chrome
 - Version: Version 99.0.4844.74 (Official Build) (x86_64)

**Additional context**
we need this fix/solution asap. our content recording is needed for our learning management system.
please help.

**Comment by jeffposnick** [comment]
Please use https://crbug.com/new to report issues with Chrome's DevTools. Unfortunately, the engineering team responsible for DevTools does not monitor this issue tracker.
