### ISSUE TITLE
Tooltip stopped working on Request Name in Fetch/XHR pages inspect tab

### ISSUE THREAD

**Issue by BarbosaWagner** [GoogleChrome/developer.chrome.com#2329]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
When inspecting a page displaying Fetch/XHR, when hovering over the Name of the request, the Tooltip stopped being displayed only in the Name column.

**To Reproduce**
1. Go to any page with requests
2. Press F12 to access the page inspector
3. Select the Network and Fetch/XHR options.
4. Refresh the page.
5. Hover over the request name in the Name column.
6. BUG: The tooltip is not only displayed in this column. It stopped working since the last update.

**Expected behavior**
Display tooltip when mouse cursor over Name column in Fetch/XHR.

**Screenshots**
https://prnt.sc/EO6d36J7586v

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Versão 99.0.4844.74 (Versão oficial) 64 bits

**Comment by jeffposnick** [comment]
Please use https://crbug.com/new to file bugs related to the functionality of Chrome DevTools.
