### ISSUE TITLE
Google Meet Screen Recording

### ISSUE THREAD

**Issue by ajporter67** [GoogleChrome/developer.chrome.com#2341]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
While trying to use google meet on Chrome, I was presented with a permission required notice that I needed to allow screen recording for Chrome.  However my permissions were already set to allow this.  I had to disable permissions and re-enable the permissions, which also meant cycling Chrome a couple times as well.  This seems to have affected other Mac users on Chrome.

**To Reproduce**
Not reproducable, as I have already cycled through the process.

**Expected behavior**
Fix the browser so it recognizes that the permission settings are already granted to record the screen.

**Screenshots**
unable to provide now

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Browser Chrome 
 - Version Version 99.0.4844.74 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by jeffposnick** [comment]
Please do not use this issue tracker to report issues with Google Chrome. If you feel like you've found a bug in Chrome, you can report it via https://crbug.com/new
