### ISSUE TITLE
Translating Chrome in to Kurdish Kurmanji

### ISSUE THREAD

**Issue by amedcj** [GoogleChrome/developer.chrome.com#236]
**Chrome Localization**
Hello.
I am a member of a volunteer translation group. We are known also as *Kurdish Crowdsource*. We want to translate Chrome into Kurdish Kurmanji.
Unfortunalety we don't kn ow how to do it. Please help us about that.

Best regards

**Comment by cleytontiagosorinho** [comment]
Bom

**Comment by robdodson** [comment]
Hi @amedcj. Thanks for reaching out. We're not currently accepting community translations for this documentation website but we appreciate the offer.
