### ISSUE TITLE
Styles for compare not appearing

### ISSUE THREAD

**Issue by petele** [GoogleChrome/developer.chrome.com#237]
**Describe the bug**
The correct styles for the Compare component aren't appearing, it's missing the left-side green/red border.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/handbook/components/
2. Look at the compare component

Also missing on article pages: https://developer.chrome.com/blog/chromium-chronicle-2/

**Comment by petele** [comment]
A little quick investigation, it looks like the `.compare` classes are added in `dist/css/main.js`, but aren't included in the CSS that's inlined into the actual file.

**Comment by robdodson** [comment]
yeah purgeCss is deleting the attribute selectors when we do a prod build for some reason.
