### ISSUE TITLE
[High priority] Non-translated articles return 404

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#2398]
When you go to a localized page such as https://developer.chrome.com/ja/docs/privacy-sandbox/
The links work as expected as long as the destination is also localized. However, when they are *not* localized, d.c.c returns 404 - Awe snap!. For example: https://developer.chrome.com/ja/docs/privacy-sandbox/chips/

Redirecting them to the original English page is preferable.

**Comment by jeffposnick** [comment]
C.f. https://github.com/GoogleChrome/web.dev/pull/7283 that attempts to do something similar for web.dev.

**Comment by jeffposnick** [comment]
This should be resolved—e.g., https://developer.chrome.com/ja/docs/privacy-sandbox/chips/ redirects to https://developer.chrome.com/docs/privacy-sandbox/chips/

Please let me know if you hear about any issues where this is not working as expected.

**Comment by agektmr** [comment]
They work perfectly now. Thank you Jeff for the quick turn around!
