### ISSUE TITLE
Content typing

### ISSUE THREAD

**Issue by FrankyGolang** [GoogleChrome/developer.chrome.com#2406]
I am developing an api for the browser and I would like the browser to type my content that would then be accessible from javascript.

![image](https://user-images.githubusercontent.com/69035383/159895813-864bee22-1a0c-4872-823e-4955bc952c2e.png)

The contents are accessed as if they were class properties and a header would be sent to type this data.

In this case it would be typestrict: string, but you could use content-type

The fetch function could be extended so that it could obtain this data directly by assigning it to variables directly and typed as well, I think it would increase the security of the internet in general.

Something like response.int() , response int64() or response string which would be equivalent to response.text() but typed

**Comment by jeffposnick** [comment]
Apologies, but this issue tracker is not the place to submit that sort of feature request. If you're asking for new functionality in Chrome DevTools, please use https://crbug.com/new

**Comment by FrankyGolang** [comment]
> Apologies, but this issue tracker is not the place to submit that sort of feature request. If you're asking for new functionality in Chrome DevTools, please use https://crbug.com/new

Thanks
