### ISSUE TITLE
Chrome App OAuth 2.0 Client saying "Sorry, something went wrong there, try again."

### ISSUE THREAD

**Issue by jmh626** [GoogleChrome/developer.chrome.com#242]
**Describe the bug**
I developed a chrome extension called "Dreamliner" (ID: onecfblfkogkdafofgpkgdldahgmbiom). It is currently published - unlisted and using a Google OAuth 2.0 Client that is in testing and not verified. All my test users have been whitelisted/added to in the console to have access. The app upon first time opening it has the consent screen come up and the users needs to hit allow to get their Chrome Token with `chrome.identity.getAuthToken`. However, a few users are reporting that a Google popup appears and will ask them to choose their Google Account and then once they choose it the screen then just says "Sorry, something went wrong there, try again.", and `chrome.identity.getAuthToken` is returning undefined. This should not be happening. 

**To Reproduce**
1. Go to https://chrome.google.com/webstore/detail/dreamliner/onecfblfkogkdafofgpkgdldahgmbiom/related?hl=en
2. Install and go to a new tab
3. Try to authenticate and click allow (this will only work if I add you as a test user for my OAuth client)
4. Make a new tab again
5. Google popup will appear to select account as shown in screenshots
6. User will click account and then the Google popup will show an error message as shown in the screenshots

**Expected behavior**
The user should select account and ``chrome.identity.getAuthToken` should return their chrome token and they should not be prompted again for this unless they sign out or delete account etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/48734395/104679830-8a5b1f00-56bc-11eb-9523-e4af2820b41f.png)
![image](https://user-images.githubusercontent.com/48734395/104679837-8cbd7900-56bc-11eb-8b06-be23222fb667.png)

**Desktop (please complete the following information):**
 - OS: Catalina and Windows 10
 - Browser: Chrome
 - Version: Not sure

Please reach out to my developer contact email at jameshenderson626@gmail.com. This seems like a problem on Google's OAuth side and not mine. Thanks

**Comment by davecook88** [comment]
I'm having the same issue with a Google Data Studio Community Connector that I've made. I added users as "test users" in GCP prior to publishing and they are met with this screen.

**Comment by robdodson** [comment]
Hey folks, this issue tracker is only for bugs relating to the developer.chrome.com site.

For developer questions I'd recommend asking either on the [extensions google group](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-extensions) or on [StackOverflow](https://stackoverflow.com/)
