### ISSUE TITLE
Please, answer support questions at CWS

### ISSUE THREAD

**Issue by marcis** [GoogleChrome/developer.chrome.com#244]
I got in touch with the Chrome Web Store support 2 weeks ago and still didn't get an answer. 

My extension is retired but don't understand why. I did several changes trying to fix it, but now it's rejected every time I publish it. PLEASE, HELP!

**Comment by robdodson** [comment]
Hi @marcis, for support issues you'll need to use this form https://support.google.com/chrome_webstore/contact/one_stop_support

Sorry but we only manage the docs for various products here. We don't handle support requests.
