### ISSUE TITLE
Read PrintData failed (PrinterProvider API) in Chrome Extension Manifest V3

### ISSUE THREAD

**Issue by the-little-penguin** [GoogleChrome/developer.chrome.com#2472]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.

**Describe the bug**
[Chrome Extension Manifest V3] 
Listening for "chrome.printerProvider.onPrintRequested", get a printJob, and then get the print data (printJob.document).
However, sometimes it stuck in blob's reading, the promise stuck in pending.
It work well in MV2.

**To Reproduce**
1. Trigger the "onPrintRequested" event
2. Get a printJob from the callback function, and get printJob.documet (blob containing the document data to print)
3. Read blob data, calling "printJob.document.arrayBuffer()", get a promise
4. Somtimes, the promise stuck in pending state, and never trigger "promise.then(function(){...})"

**Expected behavior**
The promise should be to fullfilled, it work well in Manifest V2 every time, but not in MV3.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.82

**Comment by jeffposnick** [comment]
Please use https://crbug.com/new to file bug reports related to Chrome's functionality, including Chrome Extensions.
