### ISSUE TITLE
This device cannot read NFC.

### ISSUE THREAD

**Issue by dfe3jad** [GoogleChrome/developer.chrome.com#2482]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeffposnick** [comment]
I don't believe that this is a valid issue report for developer.chrome.com content.

**Comment by dfe3jad** [comment]
![Screenshot_٢٠٢٢٠٣٣١-١١١٦٣٤_Chrome](https://user-images.githubusercontent.com/50896596/161009966-03a2602d-f9e8-4383-a747-191474f436a9.jpg)
