### ISSUE TITLE
DevTools workspace problem

### ISSUE THREAD

**Issue by marcbernier** [GoogleChrome/developer.chrome.com#2492]
Chromium Version 100.0.4896.60
In Devtools, when I add a local folder in Filesystem workspace it disappears when I restart Chrome. I think the problem comes from windows because on another computer everything is ok. Is there a new Windows permission setting to change?

**Comment by jeffposnick** [comment]
Please use https://crbug.com/new to report issues with Google Chrome or Chrome's DevTools. Thank you!
