### ISSUE TITLE
Search doesn't work if the user is on non-English locale

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#2494]
**Describe the bug**

**To Reproduce**
1. Go to https://developer.chrome.com/ja/
2. Put your cursor at the search box at the top
3. Enter a search query (e.g. "otp")

**Expected behavior**
Search results are displayed below the search box.

**Actual behavior**
Nothing will be displayed.

This is requested by our business team to meet their partner's expectations.

**Comment by jeffposnick** [comment]
Thanks for reporting this, @agektmr.

Looking at the page's behavior with a debugger attached, I can see that there are localized `ja` results returned from the Algolia search, but they are being filtered out by the following:

https://github.com/GoogleChrome/developer.chrome.com/blob/f23cddd677be58eedf315a9887c38bc6cf28e727/site/_js/web-components/search-box.js#L323-L325

None of the `ja`-specific results have a `type` field set at all, so nothing gets included in the `this.docsResults` or `this.blogResults` arrays that are used when rendering the page.

I'll take a closer look into why the Algolia index might be missing those fields for `ja` (and potentially other non-`en`) content.

**Comment by jeffposnick** [comment]
Further examination of our `algolia.json` file that's ingested for indexing shows that we do properly set `type: blogPost` for blog posts. If you visit https://developer.chrome.com/ja/ and search for "new in devtools", you'll see a number of results.

`algolia.json` shows that we're not setting `type: doc` for non-`en` documentation pages, though, so those don't end up in our search results.

I believe that metadata is set by

https://github.com/GoogleChrome/developer.chrome.com/blob/f23cddd677be58eedf315a9887c38bc6cf28e727/site/en/docs/docs.11tydata.js#L1-L3

in `site/en/docs/docs.11tydata.js`. There is no corresponding `docs.11tydata.js` file in any of the non-`en` localized `docs/` directories.

I'll add those missing files, and then hopefully the localized docs will be indexed and show up in search results as expected.

**Comment by jeffposnick** [comment]
I just did a few test searches and confirmed that both docs and blog results are coming back for our `ja` locale now.
