### ISSUE TITLE
Missing documentation for manifest field input_components

### ISSUE THREAD

**Issue by hickford** [GoogleChrome/developer.chrome.com#250]
https://developer.chrome.com/docs/extensions/mv2/manifest/ and  https://developer.chrome.com/docs/extensions/mv3/manifest/  list a manifest field **input_components**, but it is missing any documentation.

**Comment by hickford** [comment]
Here are some examples of the field I found around https://github.com/search?q=input_components+user%3AGoogle+user%3AGoogleChrome++filename%3Amanifest.json&type=Code&ref=advsearch&l=&l=

**Comment by hickford** [comment]
If it helps anyone else, here are some examples of the field in use https://github.com/search?q=input_components+user%3AGoogle+user%3AGoogleChrome++filename%3Amanifest.json&type=Code&ref=advsearch&l=&l=

**Comment by hickford** [comment]
@bderrly Do you have any insights from your experience on https://github.com/google/extra-keyboards-for-chrome-os ?

**Comment by bderrly** [comment]
The lack of documentation has been frustrating. As you pointed out, we have some working examples in that repository. The most difficult to figure out are the language and layout fields. These two have caused the most annoyance as people attempt to use layouts already available in xkeyboard-config or create a new layout based on an existing one.

- `name`: free-form text and is what is shown in the input picker in Chrome OS.
- `type`: I've never used anything but 'ime' for this field and I don't know what else would be valid.
- `id`: a (presumably) unique value across all other IME components.
- `description`: free-form text describing what the layout is though I'm not sure where it is displayed.
- `language`: I believe this uses the style defined in [BCP 47](https://tools.ietf.org/html/bcp47)
- `layout`: A layout provided in [xkeyboard-config](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/tree/master/symbols).

As I mentioned the two most difficult to get correct are `language` and `layout`.

The layout is the name of one of the files in the `symbols` directory, e.g. `us`. Within that file are variants such as dvorak. If you want the Dvorak variant of the us layout you use `us(dvorak)`. The variants are named as `xkb_symbols "dvorak"`.

The `language` is a combination of the language and possibly the region of use. For example, Spanish can be `es` for basic Spanish language support or it can be `es-ES` for Spanish (spoken in Spain) or `es-MX` for Mexican Spanish. I found a few tools to check that a given string is valid: https://r12a.github.io/app-subtags or https://schneegans.de/lv/. Where this gets really fuzzy though is I do not know if every conceivable valid string is actually valid. One person raised an issue asking about Kurdish in Iraq. I would think that means `ku-IQ` which is valid but it didn't seem to work. It's possible that instead we should use `ckb-IQ` which is more specific.

**Comment by hickford** [comment]
Thanks Brian!

I found some relevant comments about the language and layout fields. For the language field ["Both string and list of string are allowed"](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/extensions/api/input_ime/input_components_handler.cc;l=85;drc=aace0cfef2d51e7f038b07d5df26d126e4160f70). Whereas ["CrOS IME extension manifests should therefore specify one and only one layout per input method"](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/extensions/api/input_ime/input_ime_api_chromeos.cc;l=552;drc=94e457276df130575423e518181ece753734d6b9).

The most recent committer @tranbaoduy may have more insights https://source.chromium.org/chromium/chromium/src/+/e5caacef0a5d161e83f4eb98ccc5f90457ba84ec

**Comment by hickford** [comment]
> layouts already available in xkeyboard-config

For completeness, I generated a manifest with all 500+ XKB layouts in one extension https://github.com/hickford/all-xkb-layouts

**Comment by hickford** [comment]
Presumably, the input_components field only applies in Chrome OS and does nothing on other platforms?

**Comment by bderrly** [comment]
Nice! One thing that you should be aware of (and maybe document in your
repo & extension) is that the version of xkeyboard-config often lags the
public release version for quite some time. I have seen some success in
filing a bug against the input team to bump the version.

**Comment by jpmedley** [comment]
Consolidating under #163
