### ISSUE TITLE
unsafe-eval CSP directive throws.

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#2502]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
```
{
  "name": "...",
  "version": "1.0",
  "manifest_version": 3,
  "background": {
    "service_worker": "background.js",
    "type": "module"
  },
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'unsafe-eval'; object-src 'self';"
  }
}
```

throws 

```

'content_security_policy.extension_pages': Insecure CSP value "'unsafe-eval'" in directive 'script-src'.
Could not load manifest.
```

**To Reproduce**
Include 
```
'unsafe-eval'
```

in `content_security_policy` directive for `extension_pages`.
**Expected behavior**
No error to be thrown. Ability to use `eval()` in MV3 `ServiceWorker`.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jpmedley** [comment]
@guest271314,

Thank you for submitting this. Unfortunately, this repo is for reporting issues with a specific web site. To report an issue with Chrome:
1. Click the Setting menu. (It looks like three vertical dots and is located in the upper right of the browser window.)
2. Select **Help**, then **Report an issue**.

**Comment by guest271314** [comment]
@jpmedley Chromium authors banned me from filing issues at crbug.com. Perhaps you can file the issue?
