### ISSUE TITLE
Typo in extension introduction page

### ISSUE THREAD

**Issue by Arthur-Milchior** [GoogleChrome/developer.chrome.com#2503]
On https://developer.chrome.com/docs/extensions/mv3/getstarted/#user_interface
The sentence 
> Extensions can have many forms of a [user interface](https://developer.chrome.com/docs/extensions/mv3/user_interface/)

seems to be a typo. I'm not native English speaker, but I assume something such as 
> Extensions' user interfaces can have many forms.

**Comment by AmySteam** [comment]
@dotproto @jpmedley @jeffposnick  I'm going to assign this to Mike(@mikesg1t), our Chrome Extension tech writer.

**Comment by mikesg1t** [comment]
Thanks. Who's dotproto?

**Comment by AmySteam** [comment]
@mikesg1t dotproto is Simeon! 😄

**Comment by mikesg1t** [comment]
I thought that might be him.
