### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Arthur-Milchior** [GoogleChrome/developer.chrome.com#2512]
On https://developer.chrome.com/docs/extensions/mv3/manifest/ the links "[offline_enabled](https://developer.chrome.com/docs/extensions/mv3/manifest/offline_enabled/)" to https://developer.chrome.com/docs/extensions/mv3/manifest/offline_enabled/ and "[chrome_url_overrides](https://developer.chrome.com/docs/extensions/mv3/manifest/override/)" to https://developer.chrome.com/docs/extensions/mv3/manifest/override/ are broken

I have no idea what they should be, so no PR to correct them

**Comment by jpmedley** [comment]
Rolling this into #163

**Comment by jpmedley** [comment]
Rolling this into #163
