### ISSUE TITLE
IPL to List breaks links

### ISSUE THREAD

**Issue by Arthur-Milchior** [GoogleChrome/developer.chrome.com#2534]
In https://developer.chrome.com/docs/extensions/reference/ you'll find plenty of literals `{@link foo}`. E.g. `see {@link vpnProvider chrome.vpnProvider}`.

Here are my investigations. You probably already know it, but it showed me that I can't just send an easy PR to correct the broken link.

The text and link originally come from https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/platform_keys.idl;l=1-9?q=%22managed%20by%20the%20platform%22 and the link break somewhere during the processing. (At least, I can't find this text anywhere else in the source code of the documentation nor of chromium)

Note that those links are not broken on https://developer.chrome.com/docs/extensions/reference/platformKeys/ for example. So the link in IPL files are valid, it's the processing that breaks something.

**Comment by oliverdunk** [comment]
This still appears to be an issue on https://developer.chrome.com/docs/extensions/reference/api.

**Comment by dstmarthe** [comment]
Hi, thanks for raising this. It may have been fixed recently? Not sure, either way I've moved this issue to the new issue tracker here: https://issuetracker.google.com/issues/324150379
