### ISSUE TITLE
Allow YouTube video in hero image

### ISSUE THREAD

**Issue by petele** [GoogleChrome/developer.chrome.com#255]
**Is your feature request related to a problem? Please describe.**
For posts like New in Chrome where an important part of the content is a YouTube video, it would be awesome if instead of specifying a hero image in the front matter, I could specify a YouTube video ID

**Describe the solution you'd like**
If a YouTube video ID is provided in the front matter...

* On the listing/index page - the hero image would come from the YouTube thumbnail
* In the actual article, instead of showing the hero image, the top image would be the embedded YouTube video.

**Describe alternatives you've considered**
Right now, my New in Chrome posts have a big hero image, the title of the post, then the full width video. That's a lotta screen real estate. The video at the top of the page is what's important. This would be great for things like DevSummit or IO videos as well.

**Comment by devnook** [comment]
We need to keep in mind accessibility issues with this request, like respecting reduced motion, don't play by default, sound etc.

**Comment by mollietokyo** [comment]
**Estimate:**

Design - 4hrs
Dev -  1.5 days

**Comment by tokyodanj** [comment]
Design approved

**Comment by mollietokyo** [comment]
Estimate = 1.5 days (dev)
