### ISSUE TITLE
chrome.webRequest documentation should update

### ISSUE THREAD

**Issue by superbartman** [GoogleChrome/developer.chrome.com#2551]
**Is your feature request related to a problem? Please describe.**
In chrome extensions version 3 [webRequest]( https://developer.chrome.com/docs/extensions/reference/webRequest/#examples) should replace to [declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/), but documentation not note this change.

**Describe the solution you'd like**
This change needs to be prompted. [webRequest]( https://developer.chrome.com/docs/extensions/reference/webRequest/#examples)  documentation modifications are required.

**Comment by AmySteam** [comment]
Fixed #5473
