### ISSUE TITLE
Re-evaluate our PurgeCSS approach

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/developer.chrome.com#2556]
I've found that running [PurgeCSS](https://purgecss.com/) against each HTML document we generate contributes to about 25% of our total production build time on my M1 Macbook:

https://github.com/GoogleChrome/developer.chrome.com/blob/e55c39d577eeb468ebf25721f49616afb4614be6/site/_transforms/purify-css.js#L37-L63

At the same time, using PurgeCSS serves an important purpose, as there's approximately 200kb of total CSS in our `main.css` file, and most of that is unused on any given page.

I'm new to the project, so I am probably missing some important context about why this approach was adopted. If we're interested in optimizing our production build speed, I think we need to revisit some alternatives that don't rely on PurgeCSS, like:

- Generating a more targeted subset of styles for each logical section of the site (`/blog/`, `/docs/`, etc.) and just using that subset, without PurgeCSS, on each of those pages. If we went with that approach, we should also consider loading this CSS from a versioned URL in a `<link>` instead of inlining it in each page's `<style>`, and take advantage of cacheability.

- Creating a single, site-wide CSS file that also gets loaded via a `<link>` instead of inlined, but which is significantly smaller than 200kb. I.e., find all the styles that are not currently being used anywhere on the site, and just remove them from our sources completely.

**Comment by jeffposnick** [comment]
@devnook and I discussed this a bit, and we wanted to see whether the size of the input CSS (`dist/css/main.css`) had a substantial effect on the build time, or whether just using `purgeCSS` at all was always going to be slow, given the number of documents we have. I also wanted to evaluate the performance impact of using `csso` optimization, even though we can switch to a Rust-based alternative in #2555.

Here's a table showing the build time for `NODE_ENV=production npm run eleventy` given various combinations of purgeCSS and csso being enabled/disabled, both using our full 200kb CSS file as input as well as passing in a truncated set of CSS roughly 100kb in size.

(The big caveat is that I ran this on my M1 Macbook Pro, and in most scenarios, only ran a single build instead of averaging multiple builds.)

|purgeCSS?|csso?|Size in kilobytes of main.css|Build time in ms per file|
|---------|-----|-----------------------------|-------------------------|
|Yes      |Yes  |200                          |72                       |
|Yes      |No   |200                          |61                       |
|No       |Yes  |100                          |53                       |
|Yes      |Yes  |100                          |47                       |
|Yes      |No   |100                          |47                       |
|No       |No   |n/a                          |28                       |

So... the fastest we could get things to, if we could do away with per-file CSS manipulation and just used one or more shared CSS files per page, is a build time of 28ms per file, which is an improvement of 61%.

If we were at least able to cut down the complexity of our `main.css` set of rules in half, we would see a build time improvement of about 33%, getting things down to around 47ms per file. At that point, it doesn't matter quite as much whether or not we use purgeCSS, since the cost of running it seems to be outweighed by the benefit of passing in a smaller payload to `csso` for optimization.

**Comment by jeffposnick** [comment]
This episode of HTTP 203 with @jakearchibald and Ada is an interesting discussion that directly relates to this topic: https://www.youtube.com/watch?v=3sMflOp5kiQ

**Comment by jeffposnick** [comment]
The 200kb CSS file is the result of running @hankchizljaw's [`gorko`](https://github.com/hankchizljaw/gorko), driven by [this config](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_scss/globals/gorko/_config.scss), to produce the maximal set of styles. This is then whittled down via `purgeCSS` to per-page inline `<style>` for each HTML document on the site.

I understand the conceptual appeal of this setup, but the current process does not scale well as the number of pages on the site grows.

When we find time to optimize this further beyond #2620, we'll explore simplifying the initial `gorko` config to cut down on the maximal set of styles, as well as seeing if we can get away with generating a shared set of styles for everything under `/blog/`, `/docs/`, etc. once per build, instead of once per page.

**Comment by matthiasrohmer** [comment]
Working on #4048 I did some further digging.

So one quick win is instead of using the JavaScript source files for Purge CSS, use the built files in dist/js. As they are read from disk for every call, that's shaving a few seconds (about 10s) of the build as it's 6 files vs 40 files to read. Reading them once on our own and passing them to Purge CSS might be even quicker, will test it out.

Another one might be minifying the input CSS (the 200KB one) once, instead of calling csso after purging. This carves 1m52s of the build but comes with a slight increase in output size. Example sizes for a page for how it's currently done:

Full CSS (dist/css/main.css): 211.619KB
Purged CSS: 39.546KB,
Purged CSS, minified by csso: 28.211KB

And here example sizes for the updated, faster run order:

Full CSS, minified by csso: 162.368KB,
Purged CSS: 28.254KB,
Purged CSS, minified by csso (second pass): 28.214KB

I would omit the second csso pass, that's just to illustrate the difference. So pages would get bigger by around 0.043KB. I think that's neglectable.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
