### ISSUE TITLE
I can't authorize chrome web store publish API client with OAuth 2 - redirect_uri does not comply with google policies

### ISSUE THREAD

**Issue by rafek1241** [GoogleChrome/developer.chrome.com#2562]
**Describe the bug**
I can't authorize chrome web store publish API client with OAuth 2

**To Reproduce**
Follow guide: https://developer.chrome.com/docs/webstore/using_webstore_api/
step: [test-oauth](https://developer.chrome.com/docs/webstore/using_webstore_api/#test-oauth)

**Expected behavior**
As in guide:
![image](https://user-images.githubusercontent.com/9272027/162577413-6a93ef85-9cf5-41a4-a2d9-c35b23413b5b.png)

**Screenshots**
Link that I used (client id is anonimized):
```
https://accounts.google.com/o/oauth2/auth?response_type=code&scope=https://www.googleapis.com/auth/chromewebstore&client_id=XXXX.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob
```
![image](https://user-images.githubusercontent.com/9272027/162577439-d6b81892-1c0c-4c10-9295-ae0250dc73a1.png)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: edge
 - Version: latest

**Additional context**

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll address this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312298812
