### ISSUE TITLE
chrome.action.onClicked does not fire when ServiceWorker is inactive

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#2590]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
`chrome.action.onClicked` does not fire when `ServiceWorker` is inactive.

**To Reproduce**
1. Click extension icon when MV3 `ServiceWorker` is inactive.

**Expected behavior**
https://developer.chrome.com/docs/extensions/reference/action/#event-onClicked
> Fired when an action icon is clicked. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 102.0.4997.0 (Developer Build) (64-bit)
Revision 6fe492053c42a087d05890335bb335a55760423b-refs/heads/main@{#990839}

**Additional context**
a) Documentation should state some other action is required for `chrome.action.onClicked` to be fired when `ServiceWorker` is inactive; or b) this is a bug.

**Comment by joisig** [comment]
Might be related to https://bugs.chromium.org/p/chromium/issues/detail?id=1316588 (although that is for an MV2 extension, not MV3). I think it's a bug rather than a desired new behavior.
