### ISSUE TITLE
Handbook: research and document how to use `clang-format` on code samples

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#2596]
We currently have a section of the handbook docset dedicated to extensions-specific concerns. At the moment we briefly touch on [code formatting](https://developer.chrome.com/docs/handbook/extensions/#code-formatting) and say that code should be formatted with the Chromium project's `git cl format` command. At the moment using this prohibitively onerous because it essentially requires that contributors set up Chromium's tools and clone the entire project ([Mac guide](https://chromium.googlesource.com/chromium/src/+/main/docs/mac_build_instructions.md#install)). 

Under the hood `git cl format` uses `clang-format` and parts of Chromium's [`buildtools` directory](https://source.chromium.org/chromium/chromium/src/+/main:buildtools/clang_format/). We should investigate how feasible it is to get `clang-format` working with Chromium's config without having to clone dozens of GB of data. Items to consider include:

* git's [sparse-checkout](https://git-scm.com/docs/git-sparse-checkout) feautre
* the standalone stand-alone git mirror of [buildtools](https://chromium.googlesource.com/chromium/src/buildtools/)
* the [`download_from_google_storage.py`](https://source.chromium.org/chromium/chromium/tools/depot_tools/+/main:download_from_google_storage.py) script in depot_tools

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
