### ISSUE TITLE
The `default_state` manifest key for actions is undocumented

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#2597]
**Describe the bug**
The extension documentation does describe the `default_state` property. 

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/reference/action/
2. Search the page for "default_state"

**Expected behavior**
The API documentation should note the existence and describe the functionality of the `default_state` key. 

**Screenshots**
![Screen Shot 2022-04-13 at 5 56 46 PM](https://user-images.githubusercontent.com/1047763/163293220-96b90264-470f-4af8-97c6-794233982821.png)

**Additional context**
- https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/extension_action.h;drc=4d8c978b723a34b83e164be886ed2a6122d01b42;bpv=1;bpt=1;l=282
- https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/manifest_constants.cc;l=18

**Comment by jpmedley** [comment]
@IanStanion-google It seems like it fits with your manifest work. Can you take this?

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311276515
