### ISSUE TITLE
The `openPopup` method is `undefined` in Chrome `100.0.4896.75` yet the doc says otherwise.

### ISSUE THREAD

**Issue by nibble0101** [GoogleChrome/developer.chrome.com#2602]
**Describe the bug**
According to the [documentation](https://developer.chrome.com/docs/extensions/reference/action/#method-openPopup), the `openPopup` method should be available in Chrome 99+ but I get the  `Uncaught TypeError: chrome.action.openPopup is not a function` error when I run the code below.
```js
chrome.runtime.onInstalled.addListener(() => {
  console.log("Immediately");
  setTimeout(() => {
    console.log("After 10s");
    console.log(chrome.action.openPopup); // undefined
    chrome.action.openPopup();
  }, 10000);
});
```
Below is my `manifest.json` file.
```json
{
    "name": "dewall",
    "description": "Removes paywall on select websites",
    "version": "1.0",
    "manifest_version": 3,
    "background": {
        "service_worker": "background.js"
    },
    "permissions": [
        "storage",
        "notifications"
    ],
    "action": {
        "default_popup": "popup.html",
        "default_icon": {
            "16": "/images/get_started16.png",
            "32": "/images/get_started32.png",
            "48": "/images/get_started48.png",
            "128": "/images/get_started128.png"
        }
    }
}
```
I am using `100.0.4896.75 (Official Build) (64-bit) `. Either the way I am using the `openPopup` method is incorrect or the documentation is incorrect.

**To Reproduce**
1. Create a basic extension using `MV3`
2. Add the code above in `background.js`

**Expected behavior**
The extension will throw the `Uncaught TypeError: chrome.action.openPopup is not a function` error after 10s. I would have expected `openPopup` to not be `undefined`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS:  Pop!_os
 - Browser: Chrome
 - Version: 100.0.4896.75 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by jeffposnick** [comment]
CC: @dotproto to confirm whether this is a documentation issue or something else.

**Comment by xde013** [comment]
To avoid any bad surprises, I believe the `openPopp()` is only available inside of a user triggered event handler as [explained here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions). Also MDN documentation seems to have very good explanation about Chrome API usage.

**Comment by nibble0101** [comment]
> ```js
> chrome.action.openPopup
> ```

Have you tried this in chrome? Because I still get `undefined` even in `chrome.action.onClicked`.

```js
chrome.action.onClicked.addListener((tab) => {
  console.log(chrome.action.openPopup);
});
```

**Comment by xde013** [comment]
@nibble0101 I was wrong on my last statement. After doing some research it appears that Chrome's action.openPopup() is supposed to be more relaxed about user actions than Mozilla's browserAction.open(). Currently action.openPopup() seems to be missing from stable channel.  See [comment](https://github.com/w3c/webextensions/issues/15#issuecomment-1110925194)

**Comment by WagnerMoreira** [comment]
this is really weird, the function is listed in the [docs](https://developer.chrome.com/docs/extensions/reference/action/#method-openPopup) but it's not available yet. how is that possible?

**Comment by robbi73** [comment]
I made some tries with canary and it seems that second parameter (windowId) is useless.
it'd seem that only focused tab can open the popup

**Comment by myersgm** [comment]
Just tried this again in both stable versions of Edge and Chrome. The openPopup function is still undefined.

Is there any official update on this? Is this even the proper place to report such a bug? If not, please advise on where to report this so that it can be addressed.

**Comment by shaokeyibb** [comment]
Same issue, anything new now?

**Comment by elijaholmos** [comment]
also having this issue... is there any other way to programmatically trigger a popup opening?

**Comment by myersgm** [comment]
Just checked again a couple months later and this is still happening.

Some transparency on the status of this bug would be much appreciated.

**Comment by DarkEye123** [comment]
Still present. Is there no other way?

**Comment by stefanvd** [comment]
Are there any updates here? Because this prevents me from publishing my Chrome extensions, _chrome.action.openPopup()_ is not available in the Chrome stable (version 106.0.5249.119):
- Turn Off the Lights [https://chrome.google.com/webstore/detail/turn-off-the-lights/bfbmjmiodbnnpllbbbfblcplfjjepjdn](https://chrome.google.com/webstore/detail/turn-off-the-lights/bfbmjmiodbnnpllbbbfblcplfjjepjdn)
- Zoom [https://chrome.google.com/webstore/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd](https://chrome.google.com/webstore/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd)
- Full Screen [https://chrome.google.com/webstore/detail/full-screen-for-google-ch/gmimocjjppdelmhpcmpkhekmpoddgima](https://chrome.google.com/webstore/detail/full-screen-for-google-ch/gmimocjjppdelmhpcmpkhekmpoddgima)

I did the test on my Manifest V3 Print Chrome extension that is already on the Chrome Web Store:
https://chrome.google.com/webstore/detail/print-for-google-chrome/idfnpgjblkahngbondojabhffkkdekbd
But my "double click" menu does not work on the Chrome stable channel, but it does work on the Chrome Dev channel.

I want to publish my Chrome extensions before the end of this year.

**Comment by robbi73** [comment]
on 7 Jun I wrote: "... it'd seem that only focused tab can open the popup ..."
You have to put first the focus on the right window (no devtools windows).
A good workaround could be this:
chrome.tabs.getCurrent(tab => {
    chrome.windows.update(tab.windowId, {focused:true}, _ => chrome.action.openPopup())
})

**Comment by anilf01** [comment]
`chrome.action.openPopup() ` work in chromium browser Version 106.0.5249.91 and chrome dev Version 108.0.5343.2.
but don't work on brave browser( chromium version Version 106.0.5249.103).

**Comment by itskaiway** [comment]
> `chrome.action.openPopup() ` work in chromium browser Version 106.0.5249.91 and chrome dev Version 108.0.5343.2. but don't work on brave browser( chromium version Version 106.0.5249.103).

Still not working on stable version (107.0.5304.88)

**Comment by chuanqisun** [comment]
This is also broken for Edge 107.0.1418.42

**Comment by TomVoxsen** [comment]
> > `chrome.action.openPopup() ` work in chromium browser Version 106.0.5249.91 and chrome dev Version 108.0.5343.2. but don't work on brave browser( chromium version Version 106.0.5249.103).
> 
> Still not working on stable version (107.0.5304.88)

Seconded. Works in Chromium Version 108.0.5359.71 but not Chrome Version 107.0.5304.110.

Calling from an onMessage listener within the Service Worker

`chrome.runtime.onMessage.addListener(
  // Open extension popup
  if (typeof chrome.action.openPopup === 'function') {
    console.log("Open the popup");
    chrome.action.openPopup({}, function() {
      console.log("Popup opened");
    });
  }
  else {
    console.log("chrome.action.openPopup() not supported");
  }
);`

**Comment by adeopura4** [comment]
Seeing the same issue on Chrome Version 108.0.5359.94 (Official Build) (arm64)

**Comment by oscarcalderonc** [comment]
I'm having the same issue in Chrome Version 108.0.5359.124 (Official Build) (arm64) this doesn't make sense. How could you publish documentation about something that doesn't exist?

**Comment by oscarcalderonc** [comment]
Is there another way to open the chrome extension other than use the extension icon? I have a project of an extension where the webpages get buttons injected that send messages that reaches background script, and then I need to open the chrome extension programmatically. This is the final piece that is missing to build this user experience flow.

**Comment by oscarcalderonc** [comment]
@dotproto It seems it was discussed on [April's public meeting](https://github.com/w3c/webextensions/issues/201). Was there an outcome for this, like updating the documentation or adding the actual functionality in a stable release?

**Comment by creasy2010** [comment]
Seeing the same issue on Chrome Version 109.0.5414.87 (Official Build) (arm64)  
on. mac m1

**Comment by vu0tran** [comment]
> Is there another way to open the chrome extension other than use the extension icon? I have a project of an extension where the webpages get buttons injected that send messages that reaches background script, and then I need to open the chrome extension programmatically. This is the final piece that is missing to build this user experience flow.

Did you find any way to open up the popup?

**Comment by chan-kh** [comment]
Same issue with Chrome Version 110.0.5481.77  (Official Build)

**Comment by oscarcalderonc** [comment]
@vu0tran nah, we had to descope the feature that would make use of this function. I know we can do a workaround like "painting" stuff by injecting HTML code in the webpage to show some small window but that sucks.

I mean if the documentation says something it has several consequences. We got involved in this project of building a chrome extension promising something that could be done based on what we researched and found in the documentation, to later back off with that feature.

If there's no intention of enabling such functionality then just update the documentation by removing the reference to it. Is that so difficult?

**Comment by merouanezouaid** [comment]
baliz make things clear for us :)

**Comment by nsantos16** [comment]
Still without this functionlity

**Comment by addeective** [comment]
@oliverdunk  can you please advise ? this is a really key feature for many addons.

**Comment by oliverdunk** [comment]
Hey all 👋 

Sorry for the confusion here - this API is currently only available in the dev channel. It's showing on https://developer.chrome.com/ because we automatically generate certain parts of the documentation from the features available in Chromium, and it seems like that tool doesn't yet have handling for a situation like this. I'll try to get that fixed.

If you want to track work on the API in general, you can star https://crbug.com/1245093. I don't have any updates to share but we're aware this is something that's in demand and I would personally really love to see it!

**Comment by aghwotu** [comment]
A workaround for anyone still looking: 

``` javascript
// here we check if we are on the Google home page or not
function setPopupForTab(tab) {
  if (tab.url.startsWith('https://www.google.com/')) {
    chrome.action.setPopup({ tabId: tab.id, popup: 'popup.html' });
  } else {
    chrome.action.setPopup({ tabId: tab.id, popup: 'errorPopup.html' });
  }
}

chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (changeInfo.status === 'complete') {
    setPopupForTab(tab);
  }
});

chrome.tabs.onActivated.addListener((activeInfo) => {
  chrome.tabs.get(activeInfo.tabId, (tab) => {
    setPopupForTab(tab);
  });
});
```

**Comment by celebritydeveloper** [comment]
> Is there another way to open the chrome extension other than use the extension icon? I have a project of an extension where the webpages get buttons injected that send messages that reaches background script, and then I need to open the chrome extension programmatically. This is the final piece that is missing to build this user experience flow.

I can help if you want.

**Comment by carloshpds** [comment]
Hi guys,
If in your case you're using same app/popup for options page, you can use `runtime.openOptionsPage()` in your service worker for manifest v3 (or background script in manifest v2).

`In your content script` you will use `sendMessage`:
```javascript
window.browser.runtime.sendMessage({ type: 'OPEN_OPTIONS_PAGE' })
```

And `in your service worker`:
```javascript
self.chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if(message.type === 'OPEN_OPTIONS_PAGE'){
       self.chrome.runtime.openOptionsPage().then(() => {
         sendResponse('OPENED')
       }).catch((e) => {
        sendResponse('FAILED_TO_OPEN', e)
       })
    }
})

```

**Comment by LuisSantosColman** [comment]
> > Is there another way to open the chrome extension other than use the extension icon? I have a project of an extension where the webpages get buttons injected that send messages that reaches background script, and then I need to open the chrome extension programmatically. This is the final piece that is missing to build this user experience flow.
> 
> I can help if you want.
> 
> chrome.runtime.onInstalled.addListener(() => { chrome.action.setPopup({ popup: "popup.html" }); })
> 
> Make sure you remove the default_popup from the action object in manifest.json else it will not work.

The above doesn't seem to be opening the popup programmatically, it only sets it silently without opening it. Users still must actively click on the extension icon. Is there any workaround to open the extension popup programmatically at all? (without using `chrome.windows.create`)?

**Comment by oliverdunk** [comment]
> Is there any workaround to open the extension popup programmatically at all?

Hi Luis, we recently shipped the API for policy-installed extensions, so if your extension is always installed by enterprise policy you can use `chome.action.openPopup()`. Beyond that, I'm afraid this isn't currently possible. We would still like to ship the API but have some outstanding issues to address first.

**Comment by cpakken** [comment]
> > Is there any workaround to open the extension popup programmatically at all?
> 
> Hi Luis, we recently shipped the API for policy-installed extensions, so if your extension is always installed by enterprise policy you can use `chome.action.openPopup()`. Beyond that, I'm afraid this isn't currently possible. We would still like to ship the API but have some outstanding issues to address first.

This API does not work in developer mode using unpacked loaded extensions. I assume I need Chrome from the DEV channel?

**Comment by oliverdunk** [comment]
> @oliverdunk This API does not work in developer mode using unpacked loaded extensions. I assume I need Chrome from the DEV channel?

You can use Chrome from any channel but your extension must be force installed by policy. You can use the update testing tool to do this locally: https://github.com/GoogleChromeLabs/extension-update-testing-tool

**Comment by DanielRuf** [comment]
@oliverdunk I see no information regarding the channel, only `m118+` and I'm using Chrome 119.

![grafik](https://github.com/GoogleChrome/developer.chrome.com/assets/827205/3c8131a0-364f-47ef-82a7-5c52a2f9d7f4)

**Comment by DanielRuf** [comment]
@oliverdunk I see no information regarding the channel, only `Chrome 118+` and I'm using Chrome 119.

![grafik](https://github.com/GoogleChrome/developer.chrome.com/assets/827205/3c8131a0-364f-47ef-82a7-5c52a2f9d7f4)

**Comment by DanielRuf** [comment]
> You can use Chrome from any channel but your extension must be force installed by policy. 

That is very confusing. The `Requires policy` provides no further context for new developers. Why not add a link + popup on hover for this badge?

**Comment by oliverdunk** [comment]
> Why not add a link + popup on hover for this badge?

There should be a tooltip if you hover for a few seconds - unfortunately we can't add a link or reduce the delay, but hopefully that helps somewhat. I definitely appreciate that the state of this is slightly confusing - I really hope we can release this to everyone soon because that would be the best fix 🙂

**Comment by oliverdunk** [comment]
@DanielRuf, this is referring to the ability admins have to force-install extensions within an enterprise. An example would be the steps here: https://support.google.com/chrome/a/answer/6306504?hl=en

Releasing something for policy-installed extensions is independent of any release timeline, and unfortunately there aren't any updates there at the moment. I'd love for us to release this for everyone, and I think the whole team would, but we have some open issues to address beforehand.

**Comment by justingolden21** [comment]
Hoping to use this with context menus so I can add a context menu option to send data to the extension and open the extension.

**Comment by alyshae** [comment]
> Hoping to use this with context menus so I can add a context menu option to send data to the extension and open the extension.

@justingolden21 have you had any luck implementing this with context menus?

**Comment by justingolden21** [comment]
I use this to send data to my notes app from right click to get the current selection and page title:

background script:

```js
const CONTEXT_MENU_ID = 'addToNewNote';
// Register context menu option
chrome.contextMenus.create({
	title: 'Add "%s" to new note',
	contexts: ['selection'],
	id: CONTEXT_MENU_ID,
});

// Listen for context menu option clicked
chrome.contextMenus.onClicked.addListener(function (info, tab) {
	if (info.menuItemId === CONTEXT_MENU_ID) {
		// Create new tab of Chrome Notes
		chrome.tabs.create(
			{
				url: chrome.runtime.getURL('index.html'),
				active: true,
			},
			// Callback after creating tab to make sure it loaded before sending message
			function (newTab) {
				chrome.tabs.onUpdated.addListener(function (tabId) {
					if (tabId !== newTab.id) return;
					// If tab is loaded, send message
					chrome.runtime.sendMessage({
						action: 'new_note',
						title: tab.title,
						selection: info.selectionText,
					});
				});
				chrome.tabs.update(newTab.id, { active: true });
			}
		);
	}
});

```

script:

```js
chrome.runtime.onMessage.addListener(function (message) {
	if (message.action === 'new_note') {
		// my code
	}
});
```

@alyshae hope this helps you and/or others!

**Comment by vdemcak** [comment]
Any plans on releasing this feature to the general public? It has been more than 5 years since it was hidden under the `#extension-apis` flag

**Comment by sofent11** [comment]
waiting for this api can be public availabe

**Comment by Plentywolf** [comment]
I'm just about done with this an it should be ready for launch
I'm working on it right now

**Comment by oliverdunk** [comment]
> Any plans on releasing this feature to the general public?

There aren't any updates I'm afraid. We're still tracking this internally though.
