### ISSUE TITLE
Rewrite the extensions UI overview

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#2607]
**Path:** `/docs/extensions/mv3/user_interface`

The current version of the extensions documentation's "Design the user interface" page is a bit unruly. This document has organically evolved over the years, which has resulted in a large document with inconsistent levels of detail and duplicated content between this and other pages.

We should take a step back and ask whether our current approach is the right one. 

* How does this page fit into the extensions documentation corpus?
* What is the objective of this article?
* How well does it accomplish that objective?
* What information in this page would be more appropriate in another document?
* What content on other pages would be more appropriate in this document?

At the moment I'm leaning towards either:

1. Refocusing this document to provide a general overview of the UI surfaces extensions can expose and moving more content to other sections (e.g. let the Action API docs cover popup size constraints)
2. Converting this page into a collection of child documents that are the canonical resources for specific aspects of extension UI and updating other content to link into these pages

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://buganizer.corp.google.com/issues/311771568
