### ISSUE TITLE
The description of `index` property of the `createProperties` object passed to `chrome.tabs.create` is incomplete/inaccurate

### ISSUE THREAD

**Issue by nibble0101** [GoogleChrome/developer.chrome.com#2608]
**Describe the bug**
I am still learning how to create chrome browser extensions. When I wanted to create a browser tab, I came across the [chrome.tabs.create](https://developer.chrome.com/docs/extensions/reference/tabs/#method-create) method. According to the documentation, this method takes the `createProperties` object as first argument. One of the properties of the `createProperties` object is `index` and this is how the documentation describes it.

>  The position the tab should take in the window. The provided value is clamped to between zero and the number of tabs in the window.

At first sight without probing what the default value does, I thought I would use the code below to create a new tab and add it to the end. I thought `Infinity` would be clamped to `tabs.length`.
```js

  const githubLink = document.getElementById("github-link");
  githubLink.addEventListener("click", async () => {
    await chrome.tabs.create(
      {
        index: Infinity,
        url: "https://www.github.com/nibble0101",
      },
      () => {}
    );
  });
```
But the code above throws the error below. I realized I could have relied on the default by just omitting `index` to achieve what I wanted.
```js
Uncaught (in promise) TypeError: Error in invocation of tabs.create(object createProperties, optional function callback): Error at parameter 'createProperties': Error at property 'index': Invalid type: expected integer, found number.
Context
```
If the [wikipedia definition of clamp](https://en.wikipedia.org/wiki/Clamping_(graphics)#:~:text=In%20computer%20graphics%2C%20clamping%20is,to%20the%20nearest%20available%20value.) is anything to go by, I think the documentation's description of the `index` property is inaccurate or incomplete. If it really clamps `index` as described in the Wikipedia article, then the following should work but apparently they don't.

- `index: -1` clamped to `index: 0`
- `index: -Infinity` clamped to `index: 0`
- `index: Infinity` clamped to `index: tabsArray.length`

From what I have observed, it throws an error except if the value of `index` is an integer in the range `[0, Infinity)`. 

Not that I have found any use-case for the above cases. I just wish more information is added to the docs to describe how the `chrome.tabs.create` really "clamps" `index` instead of just leaving it the way it currently is.

**To Reproduce**
1. Create a simple chrome extension
2. Try using `chrome.tabs.create` passing an object with `index` set to one of the values described above.

**Expected behavior**
You should see a `TypeError` in the console.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Pop!_os
 - Browser: Chrome
 - Version: 100.0.4896.75 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/a

**Additional context**
N/A

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311479902
