### ISSUE TITLE
Websites getting scrolled automatically

### ISSUE THREAD

**Issue by narayanvaze** [GoogleChrome/developer.chrome.com#2609]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Some websites get auto scrolled down or up. One cannot predict how it will jumo to any section of the content without using mouse scroll. Checked the running same sites with firefox and they work fine. Checked ubuntu system settings - there is no option related to autoscroll. Checked using a different mouse. Same isuue persists. So, device is not an issue. 
Serached for scroll anchoring options at chrome://flags. It is not available there.

**To Reproduce**
1. Go to sites e.g. 'stackoverfow' or 'youtube' etc.
2. Keep the mouse idle.
3. Do not scroll down or up.

**Expected behavior**
1. Site may get scrolled up or down by itself. 
 2. If you scroll down, it might automatically get scrolled up or vice versa.

**Desktop (please complete the following information):**
 - OS: Linux-Ubuntu 20.04
 - Browser : Google Chrome 
 - Version : 100.0.4896.88 (Official Build) (64-bit)

**Comment by jeffposnick** [comment]
Apologies, but this is not an issue related to the content on https://developer.chrome.com/

If you think you've found a bug in the Chrome web browser, please use https://crbug.com/new to report it.
