### ISSUE TITLE
Chrome browser Crashes android 

### ISSUE THREAD

**Issue by wainsw** [GoogleChrome/developer.chrome.com#2610]
**Describe the bug**
A clear and concise description of this bug on android OPPO mobile phone. 
Chrome crashing, cleared cache cleared stored files and closed all apps or chrome pages that were open. 
No new update from play store. 
Chrome new tab opens and opens AA Web page it then when this bug happens as your scrolling Down the page it's appears to load slow and very slow loading other tabs. 

**To Reproduce**
1. None as seen on my own device 

2 Not entirely sure if it's chrome itself or if it's my phone or webdev problem. 

Big also is playstore 
When I click on the play store button it always comes up with a screen with the words 
Try again this will stay on for 10 seconds and then go straight on to the play store main page. 

Haven't seen a proper guide on fixing this either? 

*
 - OS: Android 12
 - Browser. chrome, 
 

**Smartphone 
 - Device: OPPO 
 - OS: 12
 - Browser [e.g. stock browser, chrome 
 - Version 22

![Screenshot_2022-04-15-07-48-55-29_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/87285765/163532873-98814a99-7420-4465-9da1-bc9c235c77da.jpg)

**Comment by dotproto** [comment]
This issue appears to describe a Chrome bug rather than a bug report or feature request for the chrome-extensions-samples repository. Please visit https://crbug.com/new to file a bug report.
