### ISSUE TITLE
Change language for chrome indentity popup

### ISSUE THREAD

**Issue by Hector-Mina-98** [GoogleChrome/developer.chrome.com#2616]
I am using the chrome.identity API to authenticate users in my application. The problem is that the login popup always appears in English. There is an option at the bottom to change the language, but it would be much better if when calling the 
`chrome.identity.getAuthToken()` method there was a parameter to force the language, but I haven't found this option in the documentation (https://developer.chrome.com/docs/extensions/reference/identity).
Is there any other alternative to force the language?
I also tried to change the browser language but the popup still shows in English.

**Comment by jeffposnick** [comment]
My understanding is that this functionality is related to the OAuth 2 flow that's being triggered by the Chrome Extensions API, and is not something that directly is related to incorrect or missing documentation, which is what this GitHub issue tracker is for.

I would recommend using, e.g., https://stackoverflow.com/ to ask general questions about the functionality of Chrome Extensions.
