### ISSUE TITLE
Change the way how an i18n index page shows its contents

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#2639]
Currently, index pages are displayed based on the contents in `tos.yaml`. For example, privacy sandbox page is rendered based on `/site/_data/i18n/docs/privacy-sandbox.yml` and it's at https://developer.chrome.com/docs/privacy-sandbox/

When a user goes to an i18n page, in the above case https://developer.chrome.com/ja/docs/privacy-sandbox/, they see articles that are already translated (the translated markdown exists) but without `title` property specified in the `tos.yaml`.

Issue 1: I would like to see all articles regardless of translation status. This will help the audience not to miss important contents but not translated yet.

Issue 2: By looking at the current behavior, titles displayed in https://developer.chrome.com/ja/docs/privacy-sandbox/ are translated even if the entry in `tos.yaml` doesn't have a `title` property. I presume this is because 11ty can extract the translated title from the markdown and apply that to the index page. If that is possible, I would not provide string resources as much as possible. This will help:

* Avoid duplicate translation
* It's a good indicator for the audience whether it's translated or not. If the title is in English, they can guess that it's not translated yet.
* Reduce amount of effort to translate

**Comment by devnook** [comment]
@andreban @PaulKinlan FYI - we urgently need resources to solve issues like this one

**Comment by matthiasrohmer** [comment]
Probably related to #2004.

**Comment by matthiasrohmer** [comment]
#3686 tries to fix both issues.

Issue 2 is something we all need to be aware of when authoring for d.c.c: as you already describe, the platform indeed falls back to what is in the frontmatter. The YAMLs could be used to overrule this content which might not make sense in every language. Then the translation keys can simply be removed from the YAML.

**Comment by agektmr** [comment]
Comparing the Privacy Sandbox landing page betwee English and Japanese, I noticed the issue 1 hasn't been addressed yet.
- https://developer.chrome.com/docs/privacy-sandbox/
- https://developer.chrome.com/ja/docs/privacy-sandbox/

For example, the "Get started" section starts with "Relevance and measurement unified origin trial" in English version, but it's missing in Japanese version. My expectation was to show the content in the Japanese page in English even if it's not translated yet.

**Comment by matthiasrohmer** [comment]
Not ideal, but unfortunately for now landing pages still need manual work to show English original content. Follow-up work tracked in #4268.
