### ISSUE TITLE
[Docs] Typo in chrome.runtime.connect docs

### ISSUE THREAD

**Issue by WagnerMoreira** [GoogleChrome/developer.chrome.com#2652]
**Describe the bug**
There is a typo in the documentation for chrome.runtime.connect(), [here](https://developer.chrome.com/docs/extensions/reference/runtime/#:~:text=to%20connect%20to%20connect)

**To Reproduce**
1. Go to [the page](https://developer.chrome.com/docs/extensions/reference/runtime/#:~:text=to%20connect%20to%20connect) 
2. verify that the text is "to connect to connect" and should be just "to connect"

**Expected behavior**
The text should be 
"Attempts to connect listeners within an extension/app"
instead of 
"Attempts to connect to connect listeners within an extension/app"

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX, but OS is not related
 - Browser Chrome Desktop OSX
 - Version 100.0.4896.127
 
 I'd be happy to help but it seems the docs come from an external source/cms/etc, so it seems it's not something I can fix with a PR, or is it?

**Comment by jeffposnick** [comment]
Ultimately, this comes from https://chromium.googlesource.com/experimental/src-pruned-refs/+/refs/heads/main/extensions/common/api/runtime.json#198

(I'm not sure what the process is for getting that JSON file updated, given that it's part of the Chromium source.)

**Comment by AaronForinton** [comment]
I've opened a ticket on chromium.googlesource.com requesting they change the Chromium source: https://bugs.chromium.org/p/chromium/issues/detail?id=1385416

**Comment by AaronForinton** [comment]
Closing this because it has been complete over at bugs.chromium.org 

<img width="753" alt="Screenshot 2022-11-18 at 13 17 29" src="https://user-images.githubusercontent.com/89849359/202714080-acdbf0e2-3f4e-4ead-9c0d-a1251ba10f39.png">
