### ISSUE TITLE
BUG From Google Merchant Center

### ISSUE THREAD

**Issue by guilherme69086** [GoogleChrome/developer.chrome.com#2655]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Hello Good Afternoon, i would like to tell you about a bug regarding the google merchant center, where a store is managing to clone large stores like magazine and casa bahia to deceive people and steal them

**To Reproduce**
1. Go to search bms45cr from google
2. Click on bms45 magazine luiza
3. View lojavirtualecommerce.com

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![BUG](https://user-images.githubusercontent.com/104098315/164304020-18d72d2a-dbb7-430f-9c0f-f4588b55fd7a.jpeg)

**Comment by dotproto** [comment]
Closing as this issue does not contain a bug report or feature request related to the developer.chrome.com project.
