### ISSUE TITLE
Document extension installation flow

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#2657]
At the moment we don't have a page that describes the end user experience for installing an extension. This information would be useful for both extension developers in order to better understand the experience that Chrome provides and how to work with it. It may also be useful for helping end users better understand Chrome's behaviors and operations.

Consider how best to integrate this information in our documentation. Some initial options include:

* Expand the "Design the User Interface" page 
* Create a new extension onboarding document

This issue is related to [a discussion](https://github.com/GoogleChrome/developer.chrome.com/pull/2384#discussion_r851556014) in PR #2384.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311272300
