### ISSUE TITLE
Chrome Extension Error Page is Blank

### ISSUE THREAD

**Issue by cyberjj999** [GoogleChrome/developer.chrome.com#2676]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
While developing several chrome extensions, there bound to be some syntax errors, invalid URL error etc.

In chrome://extensions, such errors are usually flagged out under the 'Errors' button with the erroneous code highlighted. However, recently I realized clicking on the 'Errors' button lead to a blank page without any message at all. Refreshing, updating, or reloading the chrome extension doesn't seem to fix this issue all the time.

**To Reproduce**
1. Enable developer mode on chrome://extensions
2. Load unpacked extension folder (ensure your javascript files have some errors)
3. Errors will occur when you interact with the chrome extension (i.e. when you click on your chrome extension)
4. Click on the 'Errors' button in chrome://extensions

**Expected behavior**
The error message should be shown clearly along with the highlighted line of code that caused the error

**Screenshots**
Error detected by Chrome
![image](https://user-images.githubusercontent.com/51283594/164874604-eef96c16-a9be-4387-a74d-9f81194df38d.png)
No error message showing up - only a blank screen
![image](https://user-images.githubusercontent.com/51283594/164874626-23a4e05b-b4e4-4d0b-be36-ac7e3fb5798e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.127 (Official Build) (64-bit)

**Additional context**
This error occurred to numerous chrome extensions, so it is unlikely a code issue.

**Comment by jeffposnick** [comment]
Please use https://crbug.com/new to file issues related to the Chrome browser's behavior or developer interfaces. This repo is just for content issues related to the https://developer.chrome.com/ website.

**Comment by 1g0rrr** [comment]
This is the only page I found on Google, that described this bug. Why not just post a solution?

**Comment by pkolenic** [comment]
I don't know about everyone else, but in my case it was because one of the errors didn't have a source url set.
I found this by looking at the console while on the error page.
I then set a breakpoint on the code at the point of error, and supplied a dummy url for the source.
This allowed the page to load so that I could clear that bad error message.

**Comment by redcrayonn** [comment]
Still occuring.

**Comment by Ephellon** [comment]
Been happening since I last updated to a `Version 103.0.5060.134 (Official Build) (64-bit)` few days ago

**Comment by Chillszz** [comment]
found a temporary solution, if you have any background.js file  type anything that will make an obvious error like "auksgaksbd/" and update the extension, and press error button and it should show all the errors now :)

**Comment by Smileek** [comment]
@Chillszz thank you!

Looks like after that you can just keep the error page opened and you don't need "auksgaksbd/" anymore.

**Comment by m32b64** [comment]
I have been suggesting that it is an Invalid URL in the source code but the devs won't try a simple edit to see if that will fix it. Will anyone who would like to see this issue resolved, please, help me out? If so, access the Chromium bugs page at:

https://bugs.chromium.org/p/chromium/issues/detail?id=1257170

Scroll to the bottom of the page. Read my post, [Comment 35] 

Click on Star this issue instead of commenting "+1 Me too!" to add a vote and get notifications.

Thanks

**Comment by huihuahuang** [comment]
According to my experience, I just simply restarted my computer and it worked!

**Comment by pmarks-net** [comment]
woxxom's workaround from https://bugs.chromium.org/p/chromium/issues/detail?id=1257170#c13 works by monkey-patching the URL class to not throw an exception when `href` is empty:

0. if you already clicked Errors, close this tab as it's unusable now
1. open chrome://extensions
2. open devtools console
3. paste this in console and press Enter key:
   `URL=class extends URL { constructor(href, ...rest) { super(href || 'dummy://', ...rest) } }`
4. click **Errors** in your extension's card

**Comment by Chillszz** [comment]
> woxxom's workaround from https://bugs.chromium.org/p/chromium/issues/detail?id=1257170#c13 works by monkey-patching the URL class to not throw an exception when `href` is empty:
> 
> 0. if you already clicked **Errors**, close this tab because its script has already crashed
> 1. open `chrome://extensions`
> 2. right-click > `Inspect` > `Console`
> 3. Paste this into the console and press the Enter key:
>    `URL=class extends URL { constructor(href, ...rest) { super(href || 'dummy://', ...rest) } }`
> 4. click **Errors** in your extension's card

do you know how this works?
