### ISSUE TITLE
The claim "Chrome 100: native messaging port keeps service worker alive" is untrue when connect(), onConnectExternal() used

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#2688]
**Describe the bug**
[Chrome 100: native messaging port keeps service worker alive](https://developer.chrome.com/docs/extensions/whatsnew/#m100-native-msg-lifetime)

> February 9, 2022
> 
> Connecting to a native messaging host using `chrome.runtime.connectNative()` in an extension's service worker will keep the service worker alive as long as the port is open.

**To Reproduce**
1. Use `chrome.runtime.connectNative()` to create a Native Messaging port connected to a Native Messaging host.
2. Use `"externally_connectable"` in manifest.json, `chrome.runtime.connect()` on Web page and `chrome.runtime.onConnectExternal()` in MV3 `ServiceWorker` to verify `SeviceWorker` remains active; that `chrome.runtime.connectNative()` "will keep the service worker alive".

**Expected behavior**
Per the article entry the MV3 `ServiceWorker` will be kept alive as long as the port is open.

**Screenshots**
![Screenshot_2022-04-25_06-27-36](https://user-images.githubusercontent.com/4174848/165101872-58c29ced-59b7-4df5-890d-a4568f8b1fa4.png)

![Screenshot_2022-04-25_06-49-39](https://user-images.githubusercontent.com/4174848/165102679-c2e9cca5-90f1-4f30-88d7-9267671b1870.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 103.0.5016.0 (Developer Build) (64-bit) Revision 4cf0333ecd4eb0c6b78b4e903f698ca5635a1be2-refs/heads/main@{#994410}

**Additional context**
- https://bugs.chromium.org/p/chromium/issues/detail?id=1152255#c107
- https://bugs.chromium.org/p/chromium/issues/detail?id=1189678#c87

What actually happens is the `ServiceWorker` becomes inactive in between 5 minutes and 6 minutes - when `chrome.runtime.connectNative()` is called in `ServiceWorker` 
 _**and**_ `chrome.runtime.connect()` is called on Web page and `chrome.runtime.onConnectExternal()` is used in MV3 `ServiceWorker`.

background.js

```
chrome.runtime.onInstalled.addListener(async(e)=>{
    console.log(e);
    var input = `von Braun believed in testing. I cannot
emphasize that term enough - test, test,
test. Test to the point it breaks.

- Ed Buckbee, NASA Public Affairs Officer, Chasing the Moon`;
    input = new String(input);

    (async()=>{
        self.port = chrome.runtime.connectNative('nm_bash')

        port.onMessage.addListener((message)=>{
            if (chrome.runtime.lastError) {
                console.log(chrome.runtime.lastError.message)
            }
            console.log(message);
        }
        )

        port.onDisconnect.addListener(()=>{
            if (chrome.runtime.lastError) {
                console.log(chrome.runtime.lastError.message)
            }
            console.log('Disconnected')
        }
        )

        port.postMessage(input);
    }
    )();
}
);
const start = new Date();
async function handleConnectExternal(_) {
  const externalPort = _;
  const time = new Date();

  function handleMessage(e) {
    console.log(e);
  }
  function handleDisconnect(e) {
    console.log(e);
    externalPort.onMessage.removeListener(handleMessage);
    externalPort.onDisconnect.removeListener(handleDisconnect);
    externalPort = null;
  }

  externalPort.onMessage.addListener(handleMessage);
  externalPort.onDisconnect.addListener(handleDisconnect);

  while (true) {
    const now = new Date();
    externalPort.postMessage({
      start,
      now,
      time,
      active: (new Date() - time) / 60000 < 1,
      minutes: (now - start) / 60000,
    });
    await new Promise((resolve) => setTimeout(resolve, 1000*30));
  }
}

chrome.runtime.onConnectExternal.addListener(handleConnectExternal);
```

Web page

```
p = chrome.runtime.connect('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
p.onMessage.addListener((msg) => console.log(msg));
p.onDisconnect.addListener((e) => console.log(e));
```

manifest.json

```
{
  "name": "nm-bash",
  "version": "1.0",
  "manifest_version": 3,
  "permissions": ["nativeMessaging"],
  "background": {
    "service_worker": "background.js",
    "type": "module"
  },
  "action": {},
  "externally_connectable": {
    "matches": ["*://*.github.com/*"],
    "ids": ["*"]
  },
  "author": "guest271314"
}
```

**Comment by dotproto** [comment]
Thanks for calling this out, @guest271314. I updated the relevant crbug issue ([1189678](https://bugs.chromium.org/p/chromium/issues/detail?id=1189678#c89)) with a reference to this bug and followed up with the engineer.

We'll need to get the What's New page updated to reflect the fact that things are still not working as expected.

**Comment by guest271314** [comment]
@dotproto Re 

>  This issue contains a demo extension, but does not include a native messaging host.

I don't think the Native Messaging host matters in this case - as long as the host does not exit. I tested using Node.js, Bash, and C++ Native Messaging hosts. I suspect Python, and any other language will produce the same result. I can post all host code for all 4 languages above, for you, or anyone else to test for themselves.

Re https://bugs.chromium.org/p/chromium/issues/detail?id=1189678#c90

> does not send any unacknowledged message to the serviceworker 

Whether the `ServiceWorker` and/or Web page "acknowledges" the message is irrelevant. Simply creating the `Port` via `chrome.runtime.connect()` and using `onConnectExternal.addListener()` produces the issue. I have reproduced the issue several times, before the publication of the claim this issue is about https://github.com/guest271314/persistent-serviceworker/issues/1.

**Comment by guest271314** [comment]
@dotproto Since I linked to an issue in the repository I created for examples of keeping MV3 and non-extension `ServiceWorker` active indefinitely, which I achieved using several different approaches, it is informative to quote one of the authors of `ServiceWorker` specification re extensions in [Background Fetch API throws for extension protocol](https://github.com/mdn/content/issues/12370):

https://github.com/mdn/content/issues/12370#issuecomment-1020220649

> The service worker is not supposed to stay alive, and attempts to make it stay alive will be buggy.

> Shared workers however do stay alive.

> If you think extensions should be able to use shared workers, that's something to propose to extension folks.

We have `onmessage` in `ServiceWorker`, yet the only means I am aware of to use that API is using `"web_accessible_resources"` and embedding an `<iframe>` wit `src` set to an extension page in the target Web page. That procesure can be simplified to allow setting any Web page as a `WindowClient`, programmatically; avoiding use of `ServiceWorker` at all, because chrome.* API's are exposed/defined in the `<iframe>` and we can use `postMessage()` to `parent` and utilize Transferable Streams - which is what this FUGU proposes https://bugs.chromium.org/p/chromium/issues/detail?id=1214621.

Clearer still is this FUGU allowing connection to Native Messaging host from any origin directly - without an intermediate extension process https://bugs.chromium.org/p/chromium/issues/detail?id=1250936.

**Comment by guest271314** [comment]
A Native Messaging host in Python 3.x can be found here https://github.com/guest271314/chrome-extensions-samples/blob/guest271314-patch-1/api/nativeMessaging/native_messaging_example_host_python.py for testing and verification.

**Comment by rtobkes** [comment]
Hi, I am currently seeing this issue as well on Chrome: Version 101.0.4951.64 (Official Build) (arm64). I have an extension that I am converting to manifest V3, and it uses chrome.runtime.connectNative to connect to my native messaging host. I can confirm that the service worker + native messaging host gets terminated every 5 minutes.

I see this bug is opened under Chromium, is it opened for Chrome as well? @dotproto

**Comment by David-Buyer** [comment]
I experiment the same issue and tried all attempts and possible configurations; regardless each of them, there's nothing to prevent the service worker to persist on connectNative() and within 5-6 minutes it becomes inactive and is disposed. This issue - and so V3 manifest extension model service worker based - heavily breaks every long-live persistent connection model realated to Native Messaging API. There could be scenarios where long-live persistent connections using NM, are pretty useful and better choice as there already are a lot of applications out there which using NM extension API in this way and V3 manifest migration, will destroy heavily any implementation model on it based.

I think it would the case to official fix this issue ASAP as it's not so a new one, and many and many developers beginning to experiment troubles.

**Comment by guest271314** [comment]
@David-Buyer 

> There's nothing to prevent the service worker to persist on connectNative() and within 5-6 minutes it becomes inactive and is disposed.

There are workarounds.

You can use define HTML and JavaScript files in `"web_accessible_resources"`, append an `<iframe>` to the target Web page, which is an uncontrolled `WindowClient` of the `ServiceWorker`, where `postMessage()` and `onmessage` (and `BroadcastChannel` between `<iframe>` and `ServiceWorker`, at the same origin, `chrome-extension://<id>/index.html`) communicate with the Web page and `ServiceWorker`. That is, re this issue, do not use `connect()` in Web page orand `onConnectExternal` at all, since timers are embedded in the Chromium and Chrome source code; instead use - it is also not necessary to use `ServiceWorker` at all due to chrome.* API's exposed and defined in the embedded `<iframe>`. 

We define `"externally_connectable"` in the manifest, though we do not use that API, and thus are able to keep the `ServiceWorker` active indefinitely.

Something like

manifest.json

```
{
  "name": "nm-cpp",
  "version": "1.0",
  "manifest_version": 3,
  "permissions": ["nativeMessaging", "tabs", "activeTab", "scripting"],
  "host_permissions": ["file:///*", "<all_urls>"],
  "background": {
    "service_worker": "background.js",
    "type": "module"
  },
  "web_accessible_resources": [{
      "resources": ["*.html", "*.js"],
      "matches": ["<all_urls>"],
      "extensions": [ ]
  }],
  "externally_connectable": {
    "matches": [
      "*://*.github.com/*"
    ],
    "ids": [
      "*"
  ]},
  "action": {},
  "author": "guest271314"
}
```

background.js
```
// Persistent data
const start = new Date();
// BroadcastChannel for communication with <iframe>
// self.bc = new BroadcastChannel('sw');
// bc.onmessage = (e) => console.log(e);
chrome.runtime.onInstalled.addListener(async(e) => {
  console.log(e);
});

async function persistServiceWorker(src) {
  console.log(src);
  // Remove all embedded <iframe>'s, if any
  return new Promise(async (resolve) => {
    const removeFrames = (close = false) => {
      for (const frame of document.querySelectorAll(
        `[src="${src}index.html"]`
      )) {
        frame.parentNode.removeChild(frame);
      }
    };
    removeFrames();
    onbeforeunload = (e) => {
      removeFrames(true);
    };
    // Create variable self.source on Web page
    self.source = null;
    onmessage = async (e) => {
      if (!self.source) {
        // Set self.source to web accessible resource (chrome-extension:) <iframe>
        self.source = e.source;
      }
      if (e.origin === new URL(src).origin) {
        console.log(e.data);
        if (e.data === 'close') {
          if (iframe.parentNode) {
            iframe.parentNode.removeChild(iframe);
            onmessage = null;
            port = null;
          }
        }
      }
    };

    iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    iframe.name = location.origin;
    document.body.appendChild(iframe);
    iframe.onload = () => resolve();
    iframe.src = `${src}index.html`;
  });
}

async function handleClickedOrExternalMessage(tab) {
    await chrome.scripting.executeScript({
      target: {
        tabId: tab.id,
      },
      world: 'MAIN',
      args: [chrome.runtime.getURL('')],
      func: persistServiceWorker,
    });
    // self.source in ServiceWorker is web acccessible resouce (chrome-extension:) <iframe>
    ([self.source] = (await self.clients.matchAll({includeUncontrolled: true})));
    self.port = chrome.runtime.connectNative('nm_cpp');
    self.port.onMessage.addListener((message)=>{
        if (chrome.runtime.lastError) {
            console.log(chrome.runtime.lastError.message)
        }
        self.source.postMessage({message, start});
    });

    self.port.onDisconnect.addListener(()=>{
        if (chrome.runtime.lastError) {
            console.log(chrome.runtime.lastError.message)
        }
        console.log('Disconnected')
    });
    // Test
    /*
    while (true) {
       self.source.postMessage({start:`${start}`, now:`${new Date()}`});
       await new Promise((resolve) => setTimeout(resolve, 30000));
    }
    */
}
// We don't use this, to avoid Chromium, Chrome internal timers
chrome.runtime.onConnectExternal.addListener(async (p) => {
  self.p = p;
  p.onMessage.addListener((msg) => {
    p.postMessage({start, now:`${new Date}`});
  });
  p.onDisconnect.addListener((e) => {
    console.log(e);
  });
});
// We don't use this, to avoid Chromium, Chrome internal timers
chrome.runtime.onMessageExternal.addListener(async (message, sender, sendResponse) => {
  console.log(message, sender, sendResponse);
  sendResponse('Ok');
  handleClickedOrExternalMessage(sender.tab)
});

chrome.action.onClicked.addListener(handleClickedOrExternalMessage);

oninstall = async (event) => {
  console.log(event);
  event.waitUntil(self.skipWaiting());
};

onactivate = async (event) => {
  console.log(event);
  event.waitUntil(self.clients.claim());
};

onfetch = (e) => console.log(e);

onmessage = async (e) => {
  console.log(e);
  self.port.postMessage(e.data);
  // Disconnect Native Messaging host from Web page or <iframe>
  if (e.data === 'disconnect') {
    self.port.disconnect();
  }
}
```

index.html

```
<script type="module" src="./index.js"></script>
```

index.js

```
function closeMessageChannel() {
  parent.postMessage('close', name);
}
navigator.serviceWorker.oncontrollerchange = async (e) => {
  console.log(e);
  closeMessageChannel();
};
navigator.serviceWorker.onmessage = async (e) => {
  parent.postMessage(e.data, name);
};

// const bc = new BroadcastChannel('sw');
// bc.onmessage = (e) => parent.postMessage(e.data, name);

onload = () => parent.postMessage(null, name);
// Message from Web page to ServiceWorker to Native Messaging port
onmessage = async (e) => {
  (await navigator.serviceWorker.ready).active.postMessage(e.data);
}
console.log(chrome.runtime);
```

At `console` on a GitHub page

```
self.source.postMessage('test', '*')
undefined
VM70:21 {message: Array(3), start: Mon May 16 2022 17:42:20 GMT-0700 ()}message: (3) ['test', '/path/to/nm-cpp/nm_cpp', 'chrome-extension://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/']start: Mon May 16 2022 17:42:20 GMT-0700 () {}[[Prototype]]: Object
self.source.postMessage('test', '*')
undefined
VM70:21 {message: Array(3), start: Mon May 16 2022 17:42:20 GMT-0700 ()}
new Date()
Mon May 16 2022 17:57:03 GMT-0700 ()
```

Note the `start` variable defined in the `ServiceWorker` `17:42:20` and the value of `new Date()` run in the `console` `17:57:03`, at over 14 minutes active, persisting data; once more

```
self.source.postMessage('test', '*')
undefined
VM70:21 {message: Array(3), start: Mon May 16 2022 17:42:20 GMT-0700 ()}
new Date()
Mon May 16 2022 18:02:33 GMT-0700 ()
```

`ServiceWorker` `17:42:20` (variable `start` value still persisting), Web page `18:02:33`, over 20 minutes.

There are other ways to keep extension and non-extension `ServiceWorker` active persistently as well, e.g., https://github.com/guest271314/persistent-serviceworker/.

**Comment by guest271314** [comment]
To reproduce the result described at previous comment you can use this Native Messaging host written in C++, though the same output can be achieved using Python, Node.js, PHP, even Bash host.

nm_cpp.cpp
```
// C++ Native Messaging host
// https://browserext.github.io/native-messaging/
// https://developer.chrome.com/docs/apps/nativeMessaging/
// https://discourse.mozilla.org/t/webextension-with-native-messaging-c-app-side/30821
// guest271314, 2022
#include <iostream>
using namespace std;

void sendMessage(string message) {
  uint32_t size = uint32_t(message.size());
  char *length = reinterpret_cast<char *>(&size);
  fwrite(length, 4, sizeof(char), stdout);
  fwrite(message.c_str(), message.length(), sizeof(char), stdout);
  fflush(stdout);
}

string getMessage() {
  char length[4];
  fread(length, 4, sizeof(char), stdin);
  uint32_t len = *reinterpret_cast<uint32_t *>(length);
  // Uncomment to exit when message length is 0.
  // if (!len) { exit(EXIT_SUCCESS); }
  char message[len];
  fread(message, len, sizeof(char), stdin);
  string content(message, message + sizeof(message) / sizeof(message[0]));
  return content;
}


int main() {
  while (true) {
    string message = getMessage();
    sendMessage(message);
    // Exclude double quotation marks from beginning and end of string
    /*
    string input = message.substr(1, message.length() - 2);
    FILE* pipe = popen(input.c_str(), "r");
    while (true) {
      unsigned char buffer[4096];
      int count = fread(buffer, 1, sizeof(buffer), pipe);
      string output;
      output += "[";
      for (int i = 0; i < count; i++) {
        output += to_string((int)buffer[i]);
        if (i < count - 1) {
          output += ",";
        }
      }
      output += "]";
      sendMessage(output);
      break;
    }
    */
  }
}
/*
int main(int argc, char *argv[]) {
  while (true) {
    string message = getMessage();
    //sendMessage(message);
    // Build JSON array   
    string data = "[";
    // Remove double quotation marks from beginning, end of string.
    // .substr(1, message.length() - 2);
    data += message; 
    data += ", ";
    for(int i = 0; i < argc; i++) {
      string arg = string(argv[i]);
      data += "\"";
      data += arg;
      data += "\"";
      if (i < argc -1) {
        data += ", ";
      }
    }
    data += "]";
    sendMessage(data);   
  }
}
*/

```

**Comment by David-Buyer** [comment]
@guest271314 , thank you. I've seen your code before answering and i was trying a test. It would good to patch, in order getting a good continuity to the standard implementation that me and other developers while migrating to V3. I will reply here to confirm on my side your code in my environment, hoping this issue will be fixed in order getting a more standard approach and backward compatibility consistent model.

Stay tuned and thank you so much!

**Comment by TheToughGuy** [comment]
I have found the service worker is not persistent simply by adding a call to runtime.connect, replacing these calls with a implemtation that only uses runtime.sendMessage along with a native messaging host proves to be persistent (I had a three day old service worker at one point!) my application does not make use of onConnectExternal so I cannot speak to its effect on persistence of a service worker

**Comment by guest271314** [comment]
@TheToughGuy You must hae used `onMessageExternal` in the `ServiceWorker`? How did you verify the same `ServiceWorker` was active?

**Comment by David-Buyer** [comment]
Following the example of @guest271314 and modifying it to adjust to my application, i confirm the SW persistence. I tested by removing **external_connectable** from manifest.json and it seems to keep its state without any issue. In my case i needed connectNative() API to mantain my app architecture; using the iframe as client and avoiding calling the API told before ( eg: `onMessageExternal` ) it runs without dropping after any time span. The workaround suggested by @guest271314 works good.

**Comment by TheToughGuy** [comment]
@guest271314 I do not have onMessageExternal. I simply monitored the serviceworker by observing the PID of the native messaging host as this changes when the serviceworker recycles, also by checking the registration in serviceworker-internals

**Comment by guest271314** [comment]
@TheToughGuy  What do you mean by 

> replacing these calls with a implemtation that only uses runtime.sendMessage

?

**Comment by TheToughGuy** [comment]
@guest271314 we have two implementations of our extension, one uses native messging to communicate with our product and the olde one uses web sockets. The content scripts injected into the pages have traditionally used log lived ports (runtime.connect) to maintain comms with the background.js. in chrome 100 we assumed that the version using native messaging would be OK and the web sockets one needed a ‘dummy’ native messaging host, so we added it. Removing the runtime.connect and using sendMessage as and when required has made the web socket version persistent, the native messaging version is currently being worked on, but so far is still recycling despite removing the runtime.connect.

**Comment by guest271314** [comment]
Did you try the code I posted above?

**Comment by TheToughGuy** [comment]
@guest271314 I am communicating with a desktop application, originally through WebSockets, more recently through NMH and the service worker. there is a degree of co-ordination needed and the NMH very much does this in the recent version of the software.

**Comment by guest271314** [comment]
@TheToughGuy Depending on how the application is started/stopped embedding an `<iframe>` is not even necessary. Again, not using `ServiceWorker` at all, it is possible to remove CSP headers from the target Web page and communicate directly with the desktop application using `fetch()` (or, if you prefer, `WebSocket`).

**Comment by guest271314** [comment]
If you are using `sendMessage`, somewhere in the code is a handler to handle the message. Based on the tests I have run, `onMessageExternal` and `onConnectExternal` handlers impact the active state of the `ServiceWorker`. 

I am not sure how you are using `sendMessage` and not encountereing the `ServiceWorker` becoming inactive between 5-6 minutes.

**Comment by TheToughGuy** [comment]
@guest271314 I was not refuting your claim, just offering additional circumstances where the claim for persistence was inaccurate, and how I had worked around it.

**Comment by guest271314** [comment]
I am just talking about how you kept the `ServiceWorker` active while simultaneously using `sendMessage`. You can strip the rest of your code out, and certainly the desktop application is not necessary to reproduce how you kept `ServiceWorker` active - while `sendMessage` was also being used.

**Comment by guest271314** [comment]
@TheToughGuy This issue is about `onMessageExternal` in `ServiceWorker` making the claim 

> chrome.runtime.connectNative() in an extension's service worker will keep the service worker alive as long as the port is open.

untrue.

Your code does not appear to use `onMesageExternal`.
