### ISSUE TITLE
CSS shape-outside not working on Chrome but in Firefox

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/developer.chrome.com#269]
Basically I'm unable to remove the padding around the shape-outside image wich in turn causes the left green balls not to surround/wrap around that shape. I think this image explains better:
![image](https://user-images.githubusercontent.com/32283036/104869889-e5437f00-5925-11eb-9150-69d08219af3e.png)

Here is a codepen with simplified code:
https://codepen.io/Snippet/pen/vYXVjXz

This is how it should look
![image](https://user-images.githubusercontent.com/32283036/104870497-6fd8ae00-5927-11eb-873f-e04795c207b8.png)

**Comment by myakura** [comment]
@tomasts248 you might want to post that question to https://stackoverflow.com , or file a bug against Chromium at https://crbug.com/new if you think that's a bug in Chrome.

this repository is about tracking issues or discussing about the https://developer.chrome.com *website*, but about the Chrome browser (or its rendering engine) itself...

**Comment by tomasts248** [comment]
Okey, thank you I apologize, I did ask in Stackoverflow as well as in Freecodecamp forum before with no luck. Is there any toher place I should ask? Thanks!
