### ISSUE TITLE
Image upload behaviour unclear

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/developer.chrome.com#270]
It's unclear to me how I should be using the image uploader after reading https://developer.chrome.com/docs/handbook/how-to/add-media/.

Does the service re-encode the image? If so, does this mean I should upload a lossless copy, or extremely high quality version to avoid generational loss? If I upload a photo as a PNG (to avoid loss), will the service convert it to jpeg/webp for me, or assume that I want the image to remain lossless?

Or should I be uploading a well compressed version of the image, as it may be used as-is on the site?

**Comment by robdodson** [comment]
I can update the handbook.

But some quick answers here:

> Does the service re-encode the image? If so, does this mean I should upload a lossless copy, or extremely high quality version to avoid generational loss?

yes, upload a high quality version

> If I upload a photo as a PNG (to avoid loss), will the service convert it to jpeg/webp for me, or assume that I want the image to remain lossless?

I believe it will convert to webp automatically. But if the browser doesn't support webp and you uploading and request a png, then I think you'll get a png.

**Comment by jakearchibald** [comment]
Feels like there should be a way to control that, so a png can be uploaded, but it's lossy compressed, especially if it doesn't have an alpha channel.

**Comment by jakearchibald** [comment]
Eg output format:
🔘 Auto
⚪ Lossy
⚪ Lossless

**Comment by robdodson** [comment]
I need to read up on it a tad more but here's what we're setting https://docs.imgix.com/apis/rendering/auto/auto#format

https://docs.imgix.com/tutorials/improved-compression-auto-content-negotiation

It looks like we could maybe expose the fm property (https://docs.imgix.com/tutorials/improved-compression-auto-content-negotiation#graceful-fallback-with-fmfm) to authors to let them set a fallback.

**Comment by samthor** [comment]
I think @MichaelSolati has updated this handbook page enough now.
