### ISSUE TITLE
Missing webpack in source panel

### ISSUE THREAD

**Issue by kellySmi** [GoogleChrome/developer.chrome.com#2703]
**Describe the bug**
When viewing the Source tab in the Dev console the webpack entry should be available to view the original source code. 

**To Reproduce**
1. Build an app using webpack with the sourcemaps enabled. 
2. Open the Dev console
3. Click on the Source tab and the page sub tab 
4. View the sources in the sidebar.
5. See that the webpack option is missing

**Expected behavior**
Expected to see webpack entry to view source maps of the minified code.

**Screenshots**
The console on the left is Chrome canary v101 the right is Chrome v100
![Screen Shot](https://user-images.githubusercontent.com/38441299/165302888-6a4f0865-6f9d-41cd-80a4-f0e6ab91ee0a.png)

**Desktop (please complete the following information):**
 - OS: OSX 12.3.1
 - Browser Chrome
 - Version 100

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser and Chrome's DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
