### ISSUE TITLE
CSS not being injected into the popup script in Manifest3

### ISSUE THREAD

**Issue by Rebooting-Me** [GoogleChrome/developer.chrome.com#2709]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The CSS script linked to the popup html script is not being called when the extension icon is clicked. On clicking the icon, instead of the desired popup, it is popping-up a little white blank box. Moreover, if I remove the CSS link from the HTML file itself and then load the extension the desired popup is shown but of course without any styling. This means that there is a bug with CSS specifically. 

**To Reproduce**
1. Create a basic website with html, javascript and css styling
2. Load it into manifest under action> default_popup> index.html
3. Unpack the extension
4. Click on the extension icon.

**Expected behavior**
The desired output behavior of the website along with the styling should be expected.

**Screenshots**

1. This is the end user website application which gives a definition of the word :
![image](https://user-images.githubusercontent.com/96843549/165379771-7358f967-4586-46f9-b34f-92cd7daec682.png)

2. But instead it is giving this with the inclusion of CSS script
<img width="107" alt="Capture" src="https://user-images.githubusercontent.com/96843549/165379965-33cce56a-5fcd-410d-b2c4-f21fed03b9ed.PNG">

3. And this with the exclusion of the CSS script 
<img width="152" alt="n" src="https://user-images.githubusercontent.com/96843549/165380224-0da65d25-a4cb-48b1-aa80-8737991b0bd6.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome, Brave
 - Version 100.0.4896.127 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
