### ISSUE TITLE
embedded YouTube video is Private in "History API - Scroll restoration"

### ISSUE THREAD

**Issue by JohnGlassmyer** [GoogleChrome/developer.chrome.com#2744]
https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/blog/history-api-scroll-restoration/index.md

embeds YouTube video DFBXl8NNQyk, which is Private.

**Comment by jpmedley** [comment]
@rachelandrew This is so old, I'm thinking we might just remove the video. 

The paragraph above needs to go as well.

**Comment by AaronForinton** [comment]
@jpmedley @rachelandrew Happy to go ahead with removing the video.

**Comment by jpmedley** [comment]
@rachelandrew Paul Lewis isn't here any more and I don't work in this area any more. He might as well work on this.

**Comment by rachelandrew** [comment]
@AaronForinton yeah let's just remove it.

**Comment by AaronForinton** [comment]
PR is open - @jpmedley by removing the paragraph above did you mean just the lines I've snipped or the para above that?
