### ISSUE TITLE
js notifiction can't  appear in desktop in macos

### ISSUE THREAD

**Issue by whwh656** [GoogleChrome/developer.chrome.com#2748]
1 env:
os:macos Catalina
chrome: 101.0.4951.41
js notifiction can't  appear in desktop in macos although i open chrome notifications settings
<img width="960" alt="image" src="https://user-images.githubusercontent.com/20383505/166434879-5e14aaf9-a918-4e7b-9502-7d2987f68472.png">

2 source code :

function notifyMe(message, options = {}) {
  if (Notification.permission === 'granted') {
    const notification = new Notification(message, options);
    notification.onclick = () => {
      notification.close();
      window.parent.focus();
    };
  } else if (Notification.permission === 'default') {
    Notification.requestPermission().then((permission) => {
      if (permission === 'granted') {
        notifyMe(message, options);
      }
    });
  } else {
    alert(message);
  }
}

notifyMe('JavaScript Notification', {
  icon: 'https://app.modaiyun.com/damf/download-asset/ccddd.jpg/8559163',
  body: 'Message to be displayed'
});

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
