### ISSUE TITLE
Example domains in the article are mixed

### ISSUE THREAD

**Issue by adamread** [GoogleChrome/developer.chrome.com#2771]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The TLDs in the article, new.com & shoes.com vs. news.example & shoes.example, seem mixed. It should be one or the other, likely *.example.

**To Reproduce**
Open the page and scroll to the privacy section.

**Expected behavior**
All of the example domain should use the .example TLD.

**Screenshots**
![Screenshot 2022-05-06 at 11 03 27](https://user-images.githubusercontent.com/751759/167101754-7310437b-8773-4543-99e5-f0df001959d4.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by heyawhite** [comment]
This appears to be in https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting/#privacy

**Comment by heyawhite** [comment]
Thank you @adamread for catching this. It will be updated shortly.
