### ISSUE TITLE
dev tool shows the wrong computed Grid track size

### ISSUE THREAD

**Issue by melon0w0** [GoogleChrome/developer.chrome.com#2791]
**Bug description**
When inspecting grid containers using the "show track size" option, wrong computed track sizes are shown, with always half of the value of the correct computed track sizes.

**Screenshots**
![image](https://user-images.githubusercontent.com/67121466/167463548-66c9bf4c-d426-49a2-813a-8c42583805c4.png)

**To Reproduce**
1. create a grid layout and open dev tools
2. go to "Layout" => "Show track sizes"
3. grid track sizes should be shown next to the tracks. If there are 2 numbers for a track, the second number should be the computed track size. It doesn't match up the real computed track size.

I've discussed this issue with other developers. They couldn't replicate the issue despite we were using the same grid layout (same HTML and css).

**Desktop**
 - OS: macOS 12.3.1
 - Browser: Chrome
 - Version: 101.0.4951.54 (Official Build) (arm64)

**Comment by miloslavH** [comment]
I have very similar issue on Windows, probably related, and I have found out that the ratio between the calculated and specified size is given by scaling of display I am using. (125% of 80px = 100px)

**Screenshot**
![image](https://user-images.githubusercontent.com/103172607/169550534-38f78662-c6ef-410c-b492-495a5503b74e.png)

**Desktop**

OS: Windows 10 Enterprise - 20H2 - 19042.1645
Browser: Chrome
Version: Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
