### ISSUE TITLE
Googlebot / Google Chrome Device Tools not rendering meta viewport initial-state=1 properly with table

### ISSUE THREAD

**Issue by sleepybjr** [GoogleChrome/developer.chrome.com#2792]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
I'm using the following meta tag in my HTML:
`<meta name="viewport" content="width=device-width, initial-scale=1">`

When I use Google Chrome Device Tools / Googlebot mobile to make sure the page renders properly, it shows the incorrect result. It does not properly set the initial scale to 1. Instead, the scaling is zoomed out. See Image 1 below.

When I use my actual mobile devices, Firefox Emulator tool and Lighthouse, it renders the page correctly. See Image 2 below.

If I switch to using minimum-scale=1, it will render correctly as Image 2:
`<meta name="viewport" content="width=device-width, minimum-scale=1">`

However, I do not want to minimize the scaling, I just want the initial-scale to be 1.

I think this might due to a fixed table that expands far horizontally that causes this issue because if I remove it, it renders correctly as Image 2 as well.

If I go into the HTML source and remove the initial-scale=1, then click out of the selection, then re-add it again, it correctly renders the page as Image 2.

**To Reproduce**
1. Create a web page with a fixed table and meta viewport code.
2. Open it in Device Tools.
3. Open the webpage on a mobile device.
4. Observe that they are rendered differently.

**Expected behavior**
Google Chrome Device Tools / Googlebot mobile should render the page as Image 2, not Image 1.

**Screenshots**
Image 1 (wrong):
![image1](https://user-images.githubusercontent.com/22383876/167526584-c0dd2a90-9e88-4ffc-90bd-0a59107e963a.png)

Image 2 (correct);
![image2](https://user-images.githubusercontent.com/22383876/167526569-4802f4d2-4c38-4e99-a32c-d17143c9c812.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 101.0.4951.54

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
