### ISSUE TITLE
Remove note about missing support for multiple files in chrome.scripting API

### ISSUE THREAD

**Issue by Juraj-Masiar** [GoogleChrome/developer.chrome.com#2811]
Chrome now support injecting multiple files in the scripting API:
https://bugs.chromium.org/p/chromium/issues/detail?id=1219788

Please remove the legacy note from the docs:
> Note: Currently, a maximum of a single file is supported. 

https://developer.chrome.com/docs/extensions/reference/scripting/#injected-code

Thanks!

**Comment by AmySteam** [comment]
@Juraj-Masiar Thanks for this 👍
