### ISSUE TITLE
Incomplete error message when using Chrome Web Store Publish API to publish extension

### ISSUE THREAD

**Issue by wdzeng** [GoogleChrome/developer.chrome.com#2819]
### Describe the bug

When publishing chrome extension onto Web Store using API, the server responses with error message `Publish condition not met: `&nbsp;without any reason.

I was publishing [my own chrome extension](https://chrome.google.com/webstore/detail/the-content-farm-terminat/chhekpgdckchblnfdelceaigmlfbakgn) onto Web Store using the [Chrome Web Store Publish API](https://developer.chrome.com/docs/webstore/using_webstore_api/#publishpublic) to public users. The server responded 400 with the following response body:

```json
{
  "error": {
    "code": 400,
    "message": "Publish condition not met: ",
    "errors": [
      {
        "message": "Publish condition not met: ",
        "domain": "chromewebstore.access",
        "reason": "badRequest"
      }
    ]
  }
}
```

The extension was in pending review on Web Store then. When I viewed the extension on Web Store website, the "Upload new package" button was disabled for some reason, which means the extension could not be updated at that moment. The API failed as expected when I tried to publish the extension, but a detailed reason should be provided with the error message.

### To Reproduce

1. Have an extension in pending review on Web Store and in the state that new package cannot be uploaded.
2. Upload a new version to public using API.
3. Publish the extension using API.
4. The request in step 3. fails and causes the response with incomplete error message.

### Expected behavior

The expected error message should be `Publish condition not met: <detailed reason>`.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, this repo is for issues with d.c.c content specifically. If you need help with extensions or Chrome Web store, see this page: https://developer.chrome.com/docs/extensions/support-feedback/getHelp/#for-chrome-web-store
