### ISSUE TITLE
Event docs missing from declarativeContent API docs

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#285]
**Describe the bug**
The old site contained additional information on API-specific event handlers and this information appears to have been lost in the migration to the new site.

**To Reproduce**
1. Visit the old [declarativeContent API docs](https://3-72-0-dot-chrome-apps-doc.appspot.com/extensions/declarativeContent)
2. Look for information on the "Declarative Event API". This info appears at the bottom of the document.
3. Visit the new [declarativeContent API docs](https://developer.chrome.com/docs/extensions/reference/declarativeContent/)
4. Look for information on the "Declarative Event API". Note that the page does not contain any reference to this information.

**Expected behavior**
The new site should also contain the same information about the onPageChanged events.

**Screenshots**
<img width="961" alt="Screen Shot 2021-01-21 at 12 53 59 AM" src="https://user-images.githubusercontent.com/1047763/105327316-9bf06b00-5b83-11eb-821c-1a8744bfa814.png">

**Comment by samthor** [comment]
Thanks, we're just not parsing this at all.

I _think_ we could template the `chrome.event.Rules` interface to actually make this friendly to TS folks too. It has two `any` types:

```ts
    export interface Rule {
      /**
       * List of conditions that can trigger the actions.
       */
      conditions: any[];

      /**
       * List of actions that are triggered if one of the conditions is fulfilled.
       */
      actions: any[];
    }
```

...these could be template types `C` and `A` respectively, and be something that could be passed through: `onPageChanged` could be defined as...

```ts
export const onPageChanged: chrome.events.Event<() => void, PageStateMatcher, RequestContentScript | SetIcon | ShowPageAction | ShowAction>;
```

**Comment by samthor** [comment]
Closing in favor of #310.
