### ISSUE TITLE
Dev Tools: Context menu for html elements is broken 

### ISSUE THREAD

**Issue by cronoklee** [GoogleChrome/developer.chrome.com#2851]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Right clicking a node in chrome dev tools should show a menu with options to edit etc. This has been broken for the last few versions of Chrome. It's also not possible to drag & drop nodes around any more.

**To Reproduce**

1. Inspect any element
2. Right click it in the dev tools "elements" tab
3. Try to drag it above or below another element

**Expected behavior**
The context menu should appear when right clicked.
It should move when dragged

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 101.0.4951.67

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
