### ISSUE TITLE
Video Autoplays after a while even when paused manually

### ISSUE THREAD

**Issue by gsharma84** [GoogleChrome/developer.chrome.com#2854]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The issue is that if I'm watching a video on youtube or sites like udemy and I pause the video and move over to another tab to do some other work, the video in the previous tab starts playing automatically. 

I have performed the following:
1. Reset all my chrome cache, deleted browser history still the issue happens
2. Tried the same in incognito and it still behaves the same

**To Reproduce**
1. Open Chrome browser
3. open youtube and play a video
4. pause the video and move over to another tab and perform some work
5. The video in the previous tab starts playing automatically

**Expected behavior**
The video should not autoplay when paused manually

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 101.0.4951.67 (Official Build) (64-bit)

**Additional context**

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
