### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by nickchamel** [GoogleChrome/developer.chrome.com#2873]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Service Worker demo not working

**To Reproduce**
From https://developer.chrome.com/docs/workbox/caching-strategies-overview/
> To see this strategy in action, [check out this demo](https://service-worker-cache-only.glitch.me/) with your console open.

**Screenshots**
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/28347933/169519839-45428488-cc40-4fae-9e86-21932a1eb454.png">

**Additional context**
<img width="530" alt="image" src="https://user-images.githubusercontent.com/28347933/169519943-d092c41c-40e6-4e02-b2e8-503a68d18a7d.png">
I think because of the redirects the images are cached from `glitch.me` even though the array contains `glitch.com` so the condition is never met.
Didn't check other demos

**Comment by jeffposnick** [comment]
Thanks! I've tweaked the sample to prevent the redirects.
