### ISSUE TITLE
Error with video .play() in Chrome Mobile WebView 101.0.4951

### ISSUE THREAD

**Issue by cr3spo9** [GoogleChrome/developer.chrome.com#2877]
I have an application built in React JS that reproduces some videos after a user interaction. The problem we are having is that it is being triggered by our Sentry many times the same error coming always from Chrome Mobile WebView 101.0.4951 that says "Error: NotAllowedError: play() can only be initiated by a user gesture." It is happening only with this version of Chrome Mobile and it is happening to many of our users, and not in other browsers or versions. 

What I have seen is that I have a native app with a WebView, I can set the property webViewSettings.setMediaPlaybackRequiresUserGesture(false); to the WebView to handle it, but here is Chrome who is setting the WebView so it is out of our hands.  

Here you can see that is happening every time in the same version and to different users and always the same error
<img width="1147" alt="Screenshot 2022-05-23 at 09 09 18" src="https://user-images.githubusercontent.com/43613261/169816128-996612fc-b7ed-47de-8423-9304b058af30.png">

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7, Poco M3 Pro, Redmi Note 8 Pro, ...
 - OS: Android 10, Android 11
 - Browser Chrome Mobile WebView 
 - Version 101.0.4951

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
