### ISSUE TITLE
Biggest mistake to remove ruler. You can give any alternative for ruler  because whever we create any website we measure that using tool like rular we are facing too much issues

### ISSUE THREAD

**Issue by Anoopkumarseth** [GoogleChrome/developer.chrome.com#2888]
Biggest mistake to remove ruler. You can give any alternative for ruler  because whenever we create any website we measure that using tool like ruler we are facing too much issues

**Comment by myakura** [comment]
@Anoopkumarseth I'm assuming that you're talking about the ruler in Chrome DevTools. If so, you might want to file a bug against Chromium via https://crbug.com/new . This repository is for the [developer.chrome.com](https://developer.chrome.com) _website_, not Chrome itself.

**Comment by myakura** [comment]
@Anoopkumarseth Hmm I see the ruler work in my Chrome DevTools. Maybe it's just hidden.
Could you try re-showing it? https://developer.chrome.com/docs/devtools/device-mode/#rulers

**Comment by jeffposnick** [comment]
This discussion should be moved to a different forum, as suggested.
