### ISSUE TITLE
Extension unloaded when handling webRequest.onBeforeRequest

### ISSUE THREAD

**Issue by dmitriyyepishin** [GoogleChrome/developer.chrome.com#2914]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
When extension registers a listener chrome.webRequest.onBeforeRequest, the extension gets unloaded of event fires on chrome launch. Everything works fine if chrome is already open before the listener is invoked.

**To Reproduce**
1. Load this sample extension into chrome: https://github.com/dmitriyyepishin/webRequestTester
2. Close Chrome
3. Launch Chrome from command line: `chrome.exe https://kuku.com`
4. Notice that a new tab is not opened.
5. Go to `chrome://extensions/` and observe that it says "service worker (Inactive)"
6. Reload the extension
7. Navigate to "https://kuku.com"
8. Observe that a new tab is opened indicating that the event handler executed succesfully.

**Expected behavior**
Extension should work when chrome is launched from command line

**Desktop (please complete the following information):**
Windows 10.0.19o44
Chrome 102.0.5005.62 (Official Build) (64-bit)

**Comment by dotproto** [comment]
This issue appears to describe a Chrome bug rather than a bug report or feature request for the developer.chrome.com repository. It looks like [crbug.com/1024211](https://crbug.com/1024211) may cover the issue you're trying to report. If you would like to file a new bug report, visit https://crbug.com/new.
