### ISSUE TITLE
Documentation for bookmarks

### ISSUE THREAD

**Issue by kospl** [GoogleChrome/developer.chrome.com#292]
**Describe the bug**
https://developer.chrome.com/docs/extensions/reference/bookmarks/#type-BookmarkTreeNode

`dateGroupModified`
> When the contents of this folder last changed, in milliseconds since the epoch.

needs to be changed to

> When the contents of this folder last changed, in milliseconds since the epoch. **Omitted for the root node.**

**Comment by samthor** [comment]
This is an issue with the underlying Chromium source: https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/api/bookmarks.json#66

This isn't really a good answer, but can you consider filing a bug on crbug.com?
