### ISSUE TITLE
Make non-translated articles appear in the i18n index pages

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#2925]
**Describe the bug**
When you visit an index page such as /docs/privacy-sandbox in non-English language, only translated articles appear. For example, [Spanish version](https://developer.chrome.com/es/docs/privacy-sandbox/) doesn't have an equivalent of "Proposal lifecycle in the Privacy Sandbox" in [the English version](https://developer.chrome.com/docs/privacy-sandbox/).

You can display one in the index by adding an `title` to `_data/docs/privacy-sandbox/toc.yml` and add an i18n entry to `_data/i18n/docs/privacy-sandbox.yml`. For example, "Shared Storage" is displayed in [Japanese version](https://developer.chrome.com/ja/docs/privacy-sandbox/) despite the translation is not available.

However, this is problematic, because:
* If the article is translated, one must also provide both title and description in the i18n entry as well. Also needs to continue adding translated strings to the i18n entry (`_data/i18n/docs/privacy-sandbox.yml`). Considering when without an 18n entry, it automatically fetches the title and description, this is an unnecessary burden.
* The reader won't find the articles unless we do above.

Can we please display all entries in the TOC by default, translated version if available, English version if not?

**Comment by agektmr** [comment]
Related pull request #2926

**Comment by jeffposnick** [comment]
I believe this is the same issue as https://github.com/GoogleChrome/developer.chrome.com/issues/2639. Assuming that's the case, let's close this in favor of that issue.

I'm sorry that we haven't had a chance to address this yet—I'll talk to @devnook about prioritization.

**Comment by agektmr** [comment]
lol. I completely forgot that I've already filed the same issue. My apologies for the confusion.
