### ISSUE TITLE
Google chrome should have delete cookie shortcut key 

### ISSUE THREAD

**Issue by dassusovan** [GoogleChrome/developer.chrome.com#2936]
Google chrome should have the delete cookie shortcut key. Every time open the Dev tool then click on application and delete the cookie. If there is an shortcut then it would be better for all the developers and tester.

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/

**Comment by dassusovan** [comment]
its showing
