### ISSUE TITLE
Extensions API: platformKeys permission is not allowed for specified platform, documentation issue or bug?

### ISSUE THREAD

**Issue by whyamiroot** [GoogleChrome/developer.chrome.com#2941]
**Describe the bug**
[Enterprise Platform Keys](https://developer.chrome.com/docs/extensions/reference/enterprise_platformKeys/) specifically mentions that this API is available only for extensions pre-installed by policy. There's also [Platform Keys API](https://developer.chrome.com/docs/extensions/reference/platformKeys/), which doesn't mention any requirements other than `platformKeys` permission and Chrome 45+.

When I tried to load an unpacked extension (manifest v3) with `platformKeys` permission, I've got the following error: `'platformKeys' is not allowed for specified platform.`. 

**To Reproduce**
1. Load unpacked extension with the following manifest
```json
{
  "manifest_version": 3,
  "version": "1.0.0",
  "name": "name",
  "description": "",
  "permissions": [
    "platformKeys"
  ]
}
```
2. See the warning. The extension details page doesn't list any permissions. `chrome.platformKeys` is undefined in popup and background. Moving `platformKeys` to `optional_permissions` doesn't change anything.

**Expected behavior**
The documentation should mention requirements for using `chrome.platformKeys` API (if there are any).

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6
 - Browser: Google Chrome 64-bit (official build)
 - Version: 102.0.5005.61

**Comment by cvalka2** [comment]
Any updates?
@whyamiroot does it work on non Chrome OS devices?

**Comment by whyamiroot** [comment]
> Any updates? @whyamiroot does it work on non Chrome OS devices?

I wasn't able to make it work on Ubuntu so I dropped this approach and used Node.js built-in certificates

**Comment by martonlederer** [comment]
Same here

**Comment by chromatim** [comment]
This seems to be a wider issue in general as the platform restrictions don't show up for other platform restricted APIs also e.g. https://developer.chrome.com/docs/extensions/reference/enterprise_deviceAttributes/ and several other similar chrome.enterprise APIs

The platform information is however making it to the chrome-types package (see https://unpkg.com/chrome-types@0.1.185/index.d.ts).
