### ISSUE TITLE
the Debug JavaScript article and its video contains outdated information

### ISSUE THREAD

**Issue by amjedomar** [GoogleChrome/developer.chrome.com#2947]
**Describe the bug**
the [Debug JavaScript](https://developer.chrome.com/docs/devtools/javascript) article and its youtube video contains outdated/wrong information

**To Reproduce**
1. Go to [Debug JavaScript](https://developer.chrome.com/docs/devtools/javascript/#event-breakpoint) article
2. Play the youtube video
3. go to `2:34` time
4. You'll see that the DevTools will pause on the first line of the function definition

![sp](https://user-images.githubusercontent.com/40240660/171650176-6c86bdd5-9216-4ec9-9515-f1c7cf233db5.PNG)

ALSO

1. go to  [Debug JavaScript](https://developer.chrome.com/docs/devtools/javascript/#event-breakpoint) article
2. click *Step 3: Pause the code with a breakpoint* from table of content
3. scroll until you reach to "DevTools should be paused on this line of code" phrase
4. you'll see the outdate information:

![gd1](https://user-images.githubusercontent.com/40240660/171651053-481e8281-a25f-45ad-a875-85e4ea8485f7.PNG)

**Expected behavior**
telling people in both the article and its video that the Mouse Event Listener `click` breakpoint will pause on the second line of the function definition (not the first line)

 As if you:

1. open [the demo](https://googlechrome.github.io/devtools-samples/debug-js/get-started) that is provided in the article in default or incognito mode either in Chrome, Edge or FireFox
2. then open Devtools then go to `Sources` panel
3. go to `Event Listener Breakpoints` > `Mouse` then check the `click` breakpoint.
4. click the button in the page (i.e. "Add Number 1 and Number 2" button)
5. you'll notice that the DevTools will pause on the second line of the function definition (not the first line as the article and its video described)

![sp2](https://user-images.githubusercontent.com/40240660/171652622-c9eb97bd-3272-47fd-bd7f-b946716d2a9a.PNG)

**Desktop**
 - OS: windows 10
 - Browser: Chrome 102, Microsoft Edge 102, FireFox 101

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311795729
