### ISSUE TITLE
Document how chrome.runtime.sendMessage behaves when an extension isn't installed

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#2950]
**Describe the bug**
Extensions documentation doesn't sufficiently describe the anti-fingerprint features of the extension platform. In particular, the message passing doc does not describe what happens when an extension is not installed or does not include a matching host pattern in the `externally_connectable` manifest field.

**To Reproduce**
1. Go to ['...'](https://developer.chrome.com/docs/extensions/mv3/messaging/#external-webpage)
2. Look for a description of what site authors should expect when the extension isn't installed.

**Expected behavior**
The page should explain that `chrome.runtime` is only exposed on a page if an extension has a matching `externally_connectable` host pattern. 

```js
async function isExtensionInstalled(id) {
  if (!chrome || !chrome.runtime)
    return false;
  let reply;
  try {
    reply = await chrome.runtime.sendMessage(id, 'Are you installed?');
  } catch (e) {
    return false;
  }
  return reply == 'yes';
}
```

**Additional context**
Also consider whether we should expand other parts of our documentation to include a reference page that details the extensions platform features and capabilities that limit a site's ability to identify the extensions a user has installed.

**Comment by guest271314** [comment]
> **Expected behavior**
The page should explain that chrome.runtime is only exposed on a page if an extension has a matching externally_connectable host pattern.

I don't think that is true.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/311236771
