### ISSUE TITLE
Storage partition explanation mentioned in Fenced Frames article is wrong

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#2951]
**Describe the bug**
In https://developer.chrome.com/docs/privacy-sandbox/fenced-frame/ it says

```
Chrome teams are working on storage partitioning, which separates browser storage per-site. This means iframes embedded on sites with the same eTLD+1, such as frame.example and site.example, could share browser storage. Iframes embedded on sites that have different hostnames, such as frame.example and site.other, won't share browser storage.
```

This sounds wrong. It reads like frame.example and site.example are same-sites, but I guess it tries to say if two domains such as frame.example and frame.example, **or** site.example and site.example can share the storage?
Anyways, frame.example and site.example are not same-sites. Please fix.

**Comment by kevinkiklee** [comment]
Hmm, I've updated the description here: 
* Preview site: https://deploy-preview-2955--developer-chrome-com.netlify.app/docs/privacy-sandbox/fenced-frame/#strengthen-cross-site-privacy-with-storage-partitioning
* PR: https://github.com/GoogleChrome/developer.chrome.com/pull/2955

Is that going too in-depth?  Let me know how it looks.

**Comment by agektmr** [comment]
I like this better. However since the diagram and the text use different domains, it's a bit confusing. Can you align the text?

**Comment by heyawhite** [comment]
I've updated the example copy to match the diagram.

**Comment by agektmr** [comment]
LGTM!
