### ISSUE TITLE
Fix behavior or description of Chrome notifications on macOS

### ISSUE THREAD

**Issue by douglaslassance** [GoogleChrome/developer.chrome.com#2956]
Using Chrome 102.0.5005.61 on macOS 12.3.1, notifications do not behave as described in [this](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/blog/native-mac-os-notifications/index.md#notification-center) paragraph. They do not end up in the Notification Center. They also do not respect the native alert style and always behave like banners.
Hopefully, this gets addressed but in the meantime, the documentation should be updated.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311785108
