### ISSUE TITLE
Some property description of DownloadQuery is wrong.

### ISSUE THREAD

**Issue by MW1Z4RD** [GoogleChrome/developer.chrome.com#2958]
**Describe the bug**
In https://developer.chrome.com/docs/extensions/reference/downloads/#type-DownloadQuery
The description of the following properties is wrong :

> **endedAfter**
> string optional
> Limits results to DownloadItem that ended after the given ms since the epoch.

> **endedBefore**
> string optional
> Limits results to DownloadItem that ended before the given ms since the epoch.

> **startedAfter**
> string optional
> Limits results to DownloadItem that started after the given ms since the epoch.

> **startedBefore**
> string optional
> Limits results to DownloadItem that started before the given ms since the epoch.

**To Reproduce**
Go to the background page console of some extensions and execute some javascript statement, you can find that the time string in ISO format is actually used and ms since the epoch do not work.

![image](https://user-images.githubusercontent.com/104913036/172017833-a7b11623-e9f7-4176-a911-5663b4058e95.png)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310739629
