### ISSUE TITLE
After run locally, can't see any doc link in doc section.

### ISSUE THREAD

**Issue by MrLee66** [GoogleChrome/developer.chrome.com#2964]
**Describe the bug**
I wanna run this locally,but after i did everything follow README.md step by step ,i cloud not see the doc page.
**To Reproduce**
1. Clone project.
2. Install dependency.
3. Execute ```npm run dev```.

**Expected behavior**
Should see doc link in doc section.

**Screenshots**
![Dingtalk_20220606124714](https://user-images.githubusercontent.com/43867549/172097091-60733961-c1ef-46a1-9059-19a484be0244.jpg)

**Desktop:**
 - OS: Windows 10
 - Browser: Chome

**Additional context**
- Here is my ```.env```
```# # Ignore ALL /docs/
# #ELEVENTY_IGNORE_DOCS=true

# # Only ignore /docs/android/
# ELEVENTY_IGNORE_ANDROID=true

# # Only ignore /docs/apps/
# ELEVENTY_IGNORE_APPS=true

# # Only ignore /docs/devtools/
# ELEVENTY_IGNORE_DEVTOOLS=true

# # Only ignore /docs/extensions/
# #ELEVENTY_IGNORE_EXTENSIONS=true

# # Only ignore /docs/handbook/
# ELEVENTY_IGNORE_HANDBOOK=true

# # Only ignore /docs/lighthouse/
# ELEVENTY_IGNORE_LIGHTHOUSE=true

# # Only ignore /docs/multidevice/
# ELEVENTY_IGNORE_MULTIDEVICE=true

# # Only ignore /docs/native-client/
# #ELEVENTY_IGNORE_NACL=true

# # Only ignore /docs/privacy-sandbox/
# ELEVENTY_IGNORE_PRIVACY_SANDBOX=true

# # Only ignore /docs/versionhistory/
# #ELEVENTY_IGNORE_VERSIONHISTORY=true

# # Only ignore /docs/webstore/
# ELEVENTY_IGNORE_WEBSTORE=true

# # Only ignore /docs/workbox/
# ELEVENTY_IGNORE_WORKBOX=true

# # Ignore BLOG /blog/
# ELEVENTY_IGNORE_BLOG=true
```

**Comment by matthiasrohmer** [comment]
Hey @MrLee66! So far this project has been developed and maintained using Unix machines without ever having been tested on Windows. My wild guess is that we are building collections using any of `path.join/resolve` and friends and that fails on Windows.

One thing to work around this might be using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install) which should provide the same path matching as on a native Unix platform. Let us know if that would work for you and feel free to reopen if it doesn't.
