### ISSUE TITLE
Show localized content when the browser sends a `Accept-Language` header and it's available

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#2989]
When I visit https://developer.chrome.com/docs/privacy-sandbox/ with a browser that sets Japanese as the primary language, the website still shows English contents. I hope it displays localized content when no particular language is specified in the path (`/ja/`) and the translation is available.  
This is also not consistent with the behavior on web.dev. web.dev works as I describe above.

Here is the header my browser sends for example.

```
accept-language: ja,ja-JP;q=0.9,en;q=0.8
```

**Comment by jeffposnick** [comment]
I believe that we get this "for free" (I'm sure it was actually a lot of work to get this set up initially, but you know what I mean) on web.dev by virtue of Firebase hosting's [support for i18n](https://firebase.google.com/docs/hosting/i18n-rewrites).

d.c.c. uses a custom [App Engine server](https://github.com/GoogleChrome/developer.chrome.com/tree/main/server) based on Express, and while I'm sure it's technically possible to implement what you're describing, I'm not sure what the path forward there would be, as it we would not be able to take advantage of what web.dev is doing.
