### ISSUE TITLE
<link rel=preload> must have a valid `as` value

### ISSUE THREAD

**Issue by MadShura** [GoogleChrome/developer.chrome.com#2999]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
its not a but just want to know the all supported value for `as` attritube in chrome 
here is the demo file which show the warning :

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="preload" href="../material/1.pdf" as="object">
</head>

<body>
  <object data="../material/1.pdf" type=""></object>
</body>

</html>
```

thanks for your help.

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 101.0.4951.67（正式版本） （64 位）
 -   System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.75 GB / 15.85 GB

**Comment by MadShura** [comment]
here is the demo : 
`
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="preload" href="../material/1.pdf" as="object">
</head>

<body>
  <p> link 设置 rel 为 preload ,再加上 as 为 object 即可预加载 object 元素需要的内容，比如PDF等。作用是更早地发起请求和获得数据。</p>
  <p>谷歌浏览器上 as 为 object 被判断为不正确的配置。</p>
  <object data="../material/1.pdf" type=""></object>
</body>

</html>
`

**Comment by MadShura** [comment]
well ,some wrong with the demo.
so you can see this :  https://paste.ubuntu.com/p/Gywypwvmmx/

**Comment by tunetheweb** [comment]
These are listed here:

https://github.com/chromium/chromium/blob/d7498ed4d927da2cc042285e232d3de63975a524/third_party/blink/renderer/core/loader/preload_helper.cc#L138-L147

So no currently we don't support `object` if that is your question. Though that doesn't seem to be one of the `as` types listed in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement/as), thought [the full list from the HTML spec](https://fetch.spec.whatwg.org/#requestdestination) does include it.

There are also [WebPlatformTests](https://wpt.fyi/results/preload/reflected-as-value.html?label=experimental&label=master&aligned), which shows Chrome supports all [the listed values](https://github.com/web-platform-tests/wpt/blob/ee30029d47/preload/reflected-as-value.html) except `video`.
