### ISSUE TITLE
Internal links in new extensions docs

### ISSUE THREAD

**Issue by haydnba** [GoogleChrome/developer.chrome.com#30]
Some links need to be updated e.g. links to the overview of 'message passing' are currently incorrect as `https://developer.chrome.com/docs/messaging/` -> should be `https://developer.chrome.com/docs/extensions/mv2/messaging/`

**Comment by samthor** [comment]
This page: "https://developer.chrome.com/docs/messaging/" is a 404, but e.g. "/messaging/" is redirected correctly.

**Comment by robdodson** [comment]
I did a quick search and can't find any usage of /docs/messaging or https://developer.chrome.com/docs/messaging/ in the code so I'm going to close this. @haydnba feel free to reopen the issue if you're still seeing broken links and can tell us which page they're appearing on.

**Comment by haydnba** [comment]
Hi @robdodson - Sorry, it's my mistake 😄 the broken link is actually "https://developer.chrome.com/docs/extensions/messaging/" and an example can be found at the first link ('Message Passing') of page https://developer.chrome.com/docs/extensions/reference/extension/

But I guess as this is a deprecated API this may not be being maintained?

**Comment by samthor** [comment]
All of the listed links work now.
