### ISSUE TITLE
downloads.open documentation fails to mention that a user gesture is required

### ISSUE THREAD

**Issue by ericlaw1979** [GoogleChrome/developer.chrome.com#3035]
**Describe the bug**

https://developer.chrome.com/docs/extensions/reference/downloads/#method-open

**Expected behavior**
Documentation mentions this limitation.

**Screenshots**
![image](https://user-images.githubusercontent.com/4192774/173949908-bc2407ec-c4eb-4b56-8291-d709f2d21be9.png)

![image](https://user-images.githubusercontent.com/4192774/173949083-9fa564a2-a79b-435e-bc13-e9a8d069ed13.png)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311789150
