### ISSUE TITLE
Word Wrap Option for Snippets

### ISSUE THREAD

**Issue by jvlimos** [GoogleChrome/developer.chrome.com#3042]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

Not a bug, but a feature request for adding a word-wrap option for Chrome DevTools Snippets.

**To Reproduce**
Just the Snippets in general.

**Expected behavior**
Code in Snippets to "wrap" after reaching the end of the screen to eliminate the horizontal scrollbar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version latest as of this date

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
