### ISSUE TITLE
Update `chrome.gcm` to reference Firebase Cloud Messging

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#3047]
**Describe the bug**
The `chrome.gcm` documentation currently refers to Google Cloud Messaging ([deprecated in 2018](https://developers.google.com/cloud-messaging)) rather than Firebase Cloud Messaging (current).

**To Reproduce**
1. Go to the [`chrome.gcm`](https://developer.chrome.com/docs/extensions/reference/gcm/) API docs.
2. Read through the content.

**Expected behavior**
The documentation should reflect the fact that this API is backed by Firebase Cloud Messaging.

https://developers.google.com/cloud-messaging/chrome/client

**Screenshots**
![fekLzZnbjgjyqUa](https://user-images.githubusercontent.com/1047763/174363643-6013ad2b-4544-4ef9-959a-d4ca386f1d53.png)

**Additional context**
I've opened [crbug.com/1337382](https://crbug.com/1337382) to a suggestion that we rename this API.

Links on the page also need to be updated to reference FCM docs. For example…

* The page currently link to https://developer.chrome.com/docs/extensions/cloudMessaging#send_messages. This URL doesn't exist.
* Per the Wayback Machine, that URL link used to point to [https://developer.chrome.com/extensions/cloudMessaging](https://web.archive.org/web/2016*/https://developer.chrome.com/extensions/cloudMessaging).
* At the time that that page existed, it redirected to https://developers.google.com/cloud-messaging/chrome/client. At the moment this redirects to https://developers.google.com/cloud-messaging. This page only notes that GCM is deactivated and replaced by FCM.
* Per the Wayback Machine, if the previous redirect worked, it would have taken the reader to [https://developers.google.com/cloud-messaging/chrome/client](https://web.archive.org/web/20161228215534/https://developers.google.com/cloud-messaging/chrome/client), which provided detailed guidance on setting up messaging in an app or extension. 
* The modern equivalent to that reference page is https://firebase.google.com/docs/cloud-messaging/js/client

**Comment by IanStanion-google** [comment]
Issue is being addressed via this PR: https://chromium-review.googlesource.com/c/chromium/src/+/4288548

**Comment by oliverdunk** [comment]
This one looks resolved :)
