### ISSUE TITLE
New headshot

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/developer.chrome.com#3069]
Hi, could someone update my headshot to the following asset?

![image](https://user-images.githubusercontent.com/3453258/174897737-0d66ce1c-b7a1-4628-822f-8acd043db4a3.png)

**Comment by heyawhite** [comment]
@chrishtr I'd be happy to. Do you have a square version of this photo? Also, author images should be a 384px square per our [handbook](https://web.dev/handbook/markup-media/).

**Comment by chrishtr** [comment]
Attached.

![headshot crop](https://user-images.githubusercontent.com/3453258/176729872-d5ec01c9-a990-4fa1-8338-f026a4f03271.png)

**Comment by heyawhite** [comment]
@chrishtr your headshot has been updated
