### ISSUE TITLE
Articles Converted from WebFu Have Wrong Authors

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#3084]
Here are some that were send to me, but there are probably others.

- Mustaq Ahmed and Joe Medley are the authors of [this user activation post](https://developer.chrome.com/blog/user-activation/) 
- Same with [this post](https://developer.chrome.com/blog/passive-event-listeners/): Dave Tapuska was a (co-)author, now he is not mentioned.
- Mustaq Ahmed is [coauthor of this](https://developer.chrome.com/authors/).  Both Dave and Joe are there though.

We make it easy to contact the authors of articles with questions. Any of our content that's still relevant will send questions to the wrong authors.

**Comment by dstmarthe** [comment]
I've moved this issue here:  https://issuetracker.google.com/issues/324323510
