### ISSUE TITLE
> https://apps.samsung.com/appquery/appDetail.as?appId=kr.co.lylstudio.unicorn

### ISSUE THREAD

**Issue by tunsira** [GoogleChrome/developer.chrome.com#3088]
> https://apps.samsung.com/appquery/appDetail.as?appId=kr.co.lylstudio.unicorn

@tunsira @ajichiban66
@google-oss-bot 

_Originally posted by @tunsira in https://github.com/firebase/quickstart-android/issues/1389#issuecomment-1166421120_

**Comment by rachelandrew** [comment]
Closing as this doesn't appear to have anything to do with the website at developer.chrome.com.
