### ISSUE TITLE
Broken Link: PWA

### ISSUE THREAD

**Issue by hikalium** [GoogleChrome/developer.chrome.com#3089]
**Describe the bug**
"Progressive Web App" link in https://developer.chrome.com/docs/apps/migration/#build-pwa is 404

**To Reproduce**
1. Go to https://developer.chrome.com/docs/apps/migration/#build-pwa
2. Click on [Progressive Web App](https://developers.google.com/web/progressive-web-apps/)
3. 404 page is shown up

**Expected behavior**
A page about PWA is opened (maybe https://web.dev/progressive-web-apps/ ?)

**Comment by AaronForinton** [comment]
Closing this as I can't replicate it.
