### ISSUE TITLE
Broken links on /docs/webstore/branding

### ISSUE THREAD

**Issue by oscarmattsson** [GoogleChrome/developer.chrome.com#31]
I went to https://developer.chrome.com/docs/webstore/branding/ and it seems that all links that start with https://developer.chrome.com/docs/ from the branding page are broken. This includes for example links to the branding icons and terms of service.

**Comment by dotproto** [comment]
Thanks for the bug report. I have a PR out to fix the /docs/ links – that will hopefully be deployed before the end of the day. I also opened #36 to track the broken asset links on that page.
