### ISSUE TITLE
Show dynamic meta image (social media thumbnail) according to hash in url 

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#3124]
When sharing this url https://developer.chrome.com/blog/new-in-devtools-103/#inline-preview to social media, I would like to have the option to :

1. Use the 1st image AFTER THE HASHTAG as thumbnail, instead of the default meta image. This help to provide more context to the audiences and make the sharing more useful.
2. Preferably it is optional and configurable (via query param maybe, to specify which image), I can foresee it is not useful in other scenario.

**Comment by jeffposnick** [comment]
I don't think that providing a share image that is customized based on a hash or query parameter is going to be possible. It would likely server-side dynamic responses, and we pre-render everything as a static site.

What I was thinking when I suggested filing a feature request is that we could consider adding in an additional, optional field in the YAML frontmatter for a post that could be used to override the social sharing image for the entire post. This would be useful if you need the social sharing image to be different than the thumbnail or hero images.

But It sounds like I may have misunderstood your goal.

**Comment by mollietokyo** [comment]
@devnook I think we need to clarify what the desired outcome is - can we switch out the OG images based on the querystring?

**Current estimate (TBC)** - 2 days
