### ISSUE TITLE
Requesting for dark mode toggle on the website

### ISSUE THREAD

**Issue by gssakash** [GoogleChrome/developer.chrome.com#3128]
**Is your feature request related to a problem? Please describe.**
It would be really cool for the website to have a dark mode toggle for better UX

**Describe the solution you'd like**
A toggle similar to the toggle on the video below would be a really good addition to the website. 

![Imgur Image](http://i.imgur.com/IB2slah.gif)

P.S. This toggle is from the web[.]dev website

**Additional context**
I was initially shocked to see why the website doesn't have a toggle considering the fact that subsidiary websites of Google Chrome like web[.]dev etc already have their own toggles for light to dark mode and this toggle will definitely be a nice addition to the website.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
