### ISSUE TITLE
Have a "What's New" page for Extensions

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#316]
**Is your feature request related to a problem? Please describe.**
There's no single place for us (Chromium) to highlight recent changes to the platform, or for extension developers to see what's coming up in the latest releases.

**Describe the solution you'd like**
We should add a "What's new" style page for extensions, highlighting new APIs + API changes, etc.  As a first step, this can be a hand-crafted page updated periodically.  Future improvements could include automating some aspects (automatically identifying new APIs?), supporting RSS feeds, etc.

**Describe alternatives you've considered**
- A what's new across dcc.  This scope would be too large.
- Other platforms (e.g. chromium blog).  Better to centralize here.

**Comment by robdodson** [comment]
What about using developer.chrome.com/blog for this? Our team already publishes [What's new in Chrome](https://developer.chrome.com/tags/new-in-chrome/) and [What's new in DevTools](https://developers.google.com/web/updates) posts (soon to be migrated to d.c.c./blog) with every new release of Chrome.

**Comment by rdcronin** [comment]
I'd personally like to have an extension-specific area, too - I think it's likely we'd want to update it more frequently than every milestone, and I'd like developers to be able to bookmark the page (or subscribe with RSS) to see relevant extension-y updates.

That said, I'd be all for having a "digest" version every Chrome mstone posted to dcc/blog too : )

Of course, that's just my $0.02.  I'd be interested in Simeon's thoughts on this, as well.
