### ISSUE TITLE
chrome.downloads.download starts but doesn't download any files

### ISSUE THREAD

**Issue by Cyclip** [GoogleChrome/developer.chrome.com#3161]
**Description**
Using [chrome.downloads.download](https://developer.chrome.com/docs/extensions/reference/downloads/#method-download) runs the function but no downloads take place. No errors are given, nor is the the download shelf displayed, and nothing changes in download history. A downloadId is returned though.

**To Reproduce**
`manifest.json`:
```
{
    "name": "Example",
    "description": "Example",
    "version": "1.0",
    "manifest_version": 3,
    "background": {
      "service_worker": "background.js"
    },
    "permissions": [
        "downloads"
    ]
}
```
somewhere in `background.js`:
```
chrome.downloads.download({
    url: url, // url defined
    saveAs: true,
}, function(res) {
        chome.downloads.show(res); // show
    }
);
```

**Expected behavior**
Save as dialog opens, download starts from that path, download completes, and the folder is shown through `chrome.downloads.show`.

**Desktop**
OS: Windows 11
Browser: Chrome 103.0.5060.114 (64-bit)

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
