### ISSUE TITLE
Content script docs should describe how dynamic registrations behave during updates

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#3198]
**Describe the bug**
Currently, neither the content scripts documentation nor the Scripting API documentation describes how dynamic content script registrations behave across browser updates or extensions updates. 

See [this thread](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/ZM0Vzb_vuIs) for additional context.

**To Reproduce**
1. Open the [Scripting API](https://developer.chrome.com/docs/extensions/reference/scripting/) docs.
2. Search for references to dynamic content scripts

**Expected behavior**
The documentation includes high level guidance for dynamic content script registrations behave, when they're appropriate to use, notes on when Chromium will unregister them, and any other critical information developers should be aware of when using this feature.

**Comment by rendomnet** [comment]
If scripts are not registered correctly during an update, users will need to manually re-register them after each update. This action requires a user gesture.
Is there a way to re-register this scipts without user gesture?

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005446
