### ISSUE TITLE
Expand "platform vision" page to describe the role of an event-based background context

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#3200]
**Is your feature request related to a problem? Please describe.**
Extension developers often ask why Chrome's extension platform is moving from background pages to service workers in Manifest V3. Our extensions documentation does not address this question. 

**Describe the solution you'd like**
We should directly address this question (or the underlying motivations for it) in a static document that can be easily referenced and shared.

At the moment, the two primary options I see are to either expand the [Extensions platform vision](https://developer.chrome.com/docs/extensions/mv3/intro/platform-vision/) page or writing a blog post on this topic. In either case,  we should update other pages in the extensions documentation to link to this material.

**Additional context**
This request is motivated in part by a [recent thread](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/YtkZMtKcdhE/m/PgWhMlPTAQAJ on the chromium-extensions group.

**Comment by AmySteam** [comment]
@jpmedley Was this already addressed in the most recent update to MV3 Platform Vision or the service worker collection?

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/310727958
