### ISSUE TITLE
content: Automated testing workflows with Recorder panel in Chrome DevTools

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/developer.chrome.com#3202]
Proposed title: Automated testing workflows with Recorder panel in Chrome DevTools
Proposed by: @ergunsh 
Related areas: Chrome DevTools
Content type: Explanation (https://documentation.divio.com/explanation/)
[Draft](https://docs.google.com/document/d/1erBJ6R9C7QO1ecdklcgJp1w8LOEsat5eX0bFk4fJF0s/edit?resourcekey=0-nha1my99ch06_hX007BYHA#)
Content summary: This is a blog post talking about how you can use Recorder panel in your automated testing workflows. It explains the libraries, gives an example and introduces a new way of exporting the recordings using Chrome extensions

**Comment by jecfish** [comment]
Ready for copyediting and review @rachelandrew @sofiayem.

**Comment by rachelandrew** [comment]
I have just requested the doc is shared with the copyeditor.

**Comment by ergunsh** [comment]
Hey @rachelandrew, I didn't see the request yet; do you still need access to the doc?
