### ISSUE TITLE
[devtools-tips] 10 - User Adaptive emulation

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#3203]
Details: b/228176071
Deadline: July 14
Notes: Do not merge the PR when ready, tag @jecfish to merge in time with video publish
Also refresh relevant docs, and include the video

**Comment by jecfish** [comment]
Update https://web.dev/new-responsive/. The update could be as minor mention and include a link to point them to DevTools https://web.dev/learn/design/micro-layouts/ @sofiayem

**Comment by sofiayem** [comment]
Fixed in https://github.com/GoogleChrome/web.dev/pull/8628
