### ISSUE TITLE
Broken links and examples in getstarted mv3 for Chrome Extensions

### ISSUE THREAD

**Issue by elgreg** [GoogleChrome/developer.chrome.com#321]
**Describe the bug**

Trying to follow the docs here https://developer.chrome.com/docs/extensions/mv3/getstarted and it's basically impossible.

**To Reproduce**

#### Issue 1

1. Go to https://developer.chrome.com/docs/extensions/mv3/getstarted
2. Click on the "here" link in "The completed extension can be downloaded here." https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started_complete.zip
3. It is a 404
4. The [manifest file link](https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/manifest.json) is also a 404
5. [Background script link](https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/background.js) is also a 404

**Expected behavior**

It should be the zip

**Screenshots**

n/a

**Comment by robdodson** [comment]
these should be fixed now
