### ISSUE TITLE
Broken link on tabs documentation

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#324]
**Describe the bug**
The documentation for the tabs API under executeScript links to the content scripts docs, but points to "https://developer.chrome.com/docs/extensions/content_scripts/#pi", which is a broken link.

More broadly - do we have any detection for broken links today?  If not, should we?

**Comment by robdodson** [comment]
> More broadly - do we have any detection for broken links today? If not, should we?

Not currently but we've kicked around the idea
https://github.com/GoogleChrome/developer.chrome.com/issues/100

Many of the tools I've seen attempt to check every link across the entire site but at 1500+ pages that's probably too long for us to run on every pull request. We've recently been doing entire crawls of /docs/extensions/ to generate lists of broken links that we've been fixing and writing redirects for.

Likely we want something that looks at the links in incoming PRs so we don't introduce _new_ broken links. And maybe we'd also do an occasional total site crawl on a less frequent cadence?

**Comment by samthor** [comment]
This is today's task now that the better basename redirect is in.

**Comment by rdcronin** [comment]
> Likely we want something that looks at the links in incoming PRs so we don't introduce new broken links. And maybe we'd also do an occasional total site crawl on a less frequent cadence?

That sounds great to me!  I'd be especially interested in finding something we can run across the full site at least once (even if it takes O(hours)) to highlight links that were broken in the migration.

**Comment by samthor** [comment]
I'll update this with the link checker I built yesterday. It takes 10
seconds for the entire site.

**Comment by samthor** [comment]
This is actually no longer a broken link.
