### ISSUE TITLE
SVG with white background, instead of transparant

### ISSUE THREAD

**Issue by tminei** [GoogleChrome/developer.chrome.com#3243]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
[Here](https://developer.chrome.com/docs/), one of the side-menu buttons uses an svg icon with a white background, and all the others have a transparent.
Another buttons display correctly.

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/'.
2. Hover cursor on 'Article' button on side menu.

**Expected behavior**
I should have seen a gray background highlighting below the outline of the icon. Instead it shows a white svg background

**Screenshots**
![Img](https://user-images.githubusercontent.com/34548743/179467435-b9c16153-cf69-44c8-a134-ae6067abcd0f.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

**Additional context**
if the 'article' item is menu a active - it does not reproduce on hover.

**Comment by mollietokyo** [comment]
**Estimate:**

Dev -  5 hours
