### ISSUE TITLE
mv3 content scripts docs have wrong "updated" date

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#325]
**Describe the bug**
https://developer.chrome.com/docs/extensions/mv3/content_scripts/ lists the update date as "Monday, March 11, 2019", but this is clearly wrong (they were updated in https://github.com/GoogleChrome/developer.chrome.com/commit/0671ca5b402fb302da4cbcadf1a29fbc377cef91, six days ago).

Are these "updated" tags supposed to be manual, or auto-generated?  If they are manual, _can_ they be autogenerated? : )

**Comment by robdodson** [comment]
Looks like someone accidentally copied it from the mv2 content_scripts doc. It should be fixed now and will go live in about an hour.

**Comment by rdcronin** [comment]
Thanks, Rob!

> Are these "updated" tags supposed to be manual, or auto-generated? If they are manual, can they be autogenerated? : )

Friendly ping on this question : )
