### ISSUE TITLE
Code parts in headings are strangely small

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/developer.chrome.com#326]
URL: https://developer.chrome.com/blog/new-in-chrome-88/

The `<code>` element in the heading has a much smaller text size. See the image below.

```css
.type code {
    font-size: .9375rem;
}
```

You probably want to use `em` instead of `rem` here. Personally, I also use negative `letter-spacing` on code in headings to make the monospace text a bit less wide. A different color for `<code>` may also look good.

<img width="710" alt="Screen Shot 2021-01-27 at 2 13 54 AM" src="https://user-images.githubusercontent.com/716405/105928742-6c8ba380-6046-11eb-8683-14ad954af512.png">

**Comment by robdodson** [comment]
ah this was my mistake. I recently added that `type code` style to make code snippets look nicer in the body, https://github.com/GoogleChrome/developer.chrome.com/pull/233

Good call on using em instead of rem there.
