### ISSUE TITLE
Usage of Favicon API needs to be documented

### ISSUE THREAD

**Issue by calidion** [GoogleChrome/developer.chrome.com#3286]
currently we can see that chrome can use site favicons by the pattern:
`chrome://favicon2/?size=24&scale_factor=1x&show_fallback_monogram=&page_url=xxx`
in the default new tab page.
But as i go through the API document, I don't find information on how to use favicon in chrome extension using manifest v3.

**Comment by hut8** [comment]
https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/api/favicon
Those examples are wrong but I have a PR to fix them: https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/api/favicon
Short answer: don't use `chrome://favicon2` , use the `_favicon/` URL. You can see [in the source](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/url_data_source.cc;l=141-142;drc=0b4c01de4879deb0e3b288e3732641d1d9e343c9) that the `chrome://favicon2` can only be used in very limited contexts.

**Comment by calidion** [comment]
@hut8 

Thanks for the update. 

It is great to have the ability to use favicon url in v3.

As I read the example, I would like to suggest:

instead of using a general function getUrl:
```js
const url = '_favicon/?page_url=https://www.google.com&size=64';
  img.src = chrome.runtime.getURL(url);
``` 
providing a more specific and unerstandable api like
```js
const siteURL = "https://www.google.com/android";  // better able to distinguish sub paths
const dimension = "64x64";     // default , optional "512x512", "128x128", "32x32", "16x16"
const faviconURL = chrome.runtime.favicon.getURL(url); 
const src = chrome.runtime.favicon.getSrc(url);    // base64 
const dimensions = chrome.runtime.favicon.getDimensions(url);   // [ "512x512", "128x128", "64x64", "32x32", "16x16"]
```
for further development.

**Comment by calidion** [comment]
@hut8 

Seems not working.

it produces urls like this:
```
chrome-extension://ciogdmlkkfdpfcmdgplmhmjeadmkpkgb/_favicon/?page_url=https://app.circleci.com&size=64
```

But this url is not accessible.

**Comment by hut8** [comment]
Are you talking about my pull request? That url was not produced by my code. Look at the capitalization of the query string parameters.

**Comment by calidion** [comment]
@hut8 

Neither works.

Message received:
```
This site can’t be reachedThe webpage at chrome-extension://ciogdmlkkfdpfcmdgplmhmjeadmkpkgb/_favicon/?pageUrl=https%3A%2F%2baidu.com%2F%2F&size=32 might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED
```

**Comment by calidion** [comment]
@hut8 

I have solved by this format:
```
chrome://favicon/size/32@1x/${url}
```

**Comment by calidion** [comment]
@hut8 

I found it only works in v2. 
But the browser tells me that v2 is going to be removed in 2023.
While I did figure out how to migrate to v3 with favicon api still not working.

**Comment by calidion** [comment]
v3: 
url format = chrome-extension://aglmepmfibmokigfgakpbcimgkkkklia/_favicon/?pageUrl=https%3A%2F%2Fvideo.twimg.com&size=64
![Screenshot from 2022-12-02 20-01-04](https://user-images.githubusercontent.com/131776/205310838-fb197737-b15c-40e1-9f26-793d9f5869e6.png)

v2:
url format = chrome://favicon/size/32@1x/https://google.com/
![Screenshot from 2022-12-02 19-07-30](https://user-images.githubusercontent.com/131776/205311605-e67c1dc5-9660-4b30-9afd-525879ba60a0.png)


but v2 is forbidden to be published.
