### ISSUE TITLE
use one svg image as the default favicon image instead of fix-sized multiple png images

### ISSUE THREAD

**Issue by calidion** [GoogleChrome/developer.chrome.com#3288]
Chome Extensions development should use only one favicon image file in svg format  as the default image setting instead of a lot of files in png format.

**Comment by myakura** [comment]
You might want to star this issue https://bugs.chromium.org/p/chromium/issues/detail?id=29683

**Comment by calidion** [comment]
@myakura 
Not the same thing.
This is is not about support of svg,  but as default favicon format.
to be used in different areas without create additional files.
As not chrome extension examples creates about four files as favicon for different needs.

**Comment by myakura** [comment]
@calidion Oh. My bad.

Either way, you want to file a bug against Chromium via https://crbug.com/new . This repository is about https://developer.chrome.com _website_, not Chrome browser itself.

**Comment by jpmedley** [comment]
@myakura is correcting. Closing the issue.
