### ISSUE TITLE
404 link on puppeteer doc

### ISSUE THREAD

**Issue by LN-T** [GoogleChrome/developer.chrome.com#3297]
**Describe the bug**
Link 404 in documentation

**To Reproduce**
1. Go to [puppeteer doc](https://developer.chrome.com/docs/puppeteer/)
2. Click on [Try Puppeteer!](https://try-puppeteer.appspot.com/)
3. Page is 404

**Comment by myakura** [comment]
Looks like the app is gone https://github.com/GoogleChrome/developer.chrome.com/pull/3134

**Comment by rachelandrew** [comment]
This link has now been removed.

**Comment by OrKoN** [comment]
The Try Puppeteer website is no longer supported by us, so we removed the link from the documentation. Thanks for flagging the broken link!
