### ISSUE TITLE
Chrome Extension tutorial instructions yield an error

### ISSUE THREAD

**Issue by GeorgeSchafer** [GoogleChrome/developer.chrome.com#3302]
**Describe the bug**
I am following the steps laid out in the [Chrome Extension tutorial](https://github.com/GoogleChrome/developer.chrome.com/blob/6a56f1e8b3878dd9c743ced993dcc2e2f4239953/site/en/docs/extensions/mv3/getstarted/index.md) when I get to [this step](https://github.com/GoogleChrome/developer.chrome.com/blob/6a56f1e8b3878dd9c743ced993dcc2e2f4239953/site/en/docs/extensions/mv3/getstarted/index.md#inspect-the-background-script--inspect-background-:~:text=Inspect%20the%20background%20script%20%7B%3A%20%23inspect%2Dbackground%20%7D) and load the unpacked extension, the red error button appears but I get a blank screen when I try to view the error.

**To Reproduce**
1. Go to the [Chrome Extension tutorial](https://github.com/GoogleChrome/developer.chrome.com/blob/6a56f1e8b3878dd9c743ced993dcc2e2f4239953/site/en/docs/extensions/mv3/getstarted/index.md)
2. Follow the steps outlined in the tutorial
3. When you come to the section [Inspect the background script](https://github.com/GoogleChrome/developer.chrome.com/blob/6a56f1e8b3878dd9c743ced993dcc2e2f4239953/site/en/docs/extensions/mv3/getstarted/index.md#inspect-the-background-script--inspect-background-:~:text=Inspect%20the%20background%20script) follow the instructions
4. See an error
5. Click on "Errors"
6. User is presented with a blank screen.

**Expected behavior**
Users should see the result of the code in the tutorial.

**Screenshots**
![image](https://user-images.githubusercontent.com/77408854/180835433-08fa7a59-37a1-449c-ae39-5d0586a959f6.png)

This is what I get when I click on "Errors".
![image](https://user-images.githubusercontent.com/77408854/180836141-5b9c2f9d-faba-4288-8d8c-dcc3f6e1a2c7.png)

**Desktop:**
 - OS: macOS 12.4 (21F79
 - Browser Chrome
 - Version: {Chrome: `103.0.5060.134 (Official Build) (x86_64)`} 

**Additional context**
I checked with my organization manager and they said they do not have a setting to prevent unpacked Chrome extensions from functioning.

**Update 1**
- From what I read on the internet, it looks like the tutorial is written with manifest v2 and we are on manifest v3.  Once I figure out what is wrong, I would gladly update the tutorial.

**Update 2**
- I downloaded the finished example and that doesn't seem to work either, although I am able to get to the console to pop up from the extension menu. 
- When I click on the icon from the extension menu I get a chrome URL error in the extension manager.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/77408854/180844978-73296af3-d68d-495f-8fbe-d25c0529de6a.png">

**Update 3**
- Interestingly,  if `background.js` is empty, there doesn't seem to be a problem.  It only becomes a problem when you add some kind of code to it.  I cleared and added `const a = "a";` and received the error.

**Update 4**
- I seem to have fixed it in my intended project, but I have no idea how. I emptied out my background.js files and moved the script to content.js. You can view [the code](https://github.com/GeorgeSchafer/srdm-dark-mode).

**Comment by GeorgeSchafer** [comment]
Update 3 added.

**Comment by GeorgeSchafer** [comment]
> **Update 4**
> I seem to have fixed it in my intended project, but I have no idea how. I emptied out my background.js files and moved the script to content.js.

**Comment by ZGStuff** [comment]
the Background.js thing doesnt work. it shows this on reload
![Screenshot 2022-07-25 6 07 12 PM](https://user-images.githubusercontent.com/95325264/180895269-70c6ef50-4b7c-4358-872e-3bb1babcd119.png)
any reason WHY?

**Comment by jadedrakerider** [comment]
@ZGStuff You are missing a comma after the manifest_version value.

**Comment by jpmedley** [comment]
@AmySteam Did one of your new tutorials replace the one that's causing this error?

**Comment by AmySteam** [comment]
@jpmedley This example was removed in favor of the new [Getting Started guides tutorials](https://developer.chrome.com/docs/extensions/mv3/getstarted/#tutorial). This Issue is no longer relevant.
