### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Abhaytiwari9706** [GoogleChrome/developer.chrome.com#3308]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
>  When I was type chrome://net-internals/#dns. I select the DNS . Then I click on clear data but this is no working pls fix this issue ![Screenshot_2022-07-26-14-27-37-570_com.android.chrome.jpg](https://user-images.githubusercontent.com/109356157/180967077-1bba5eaa-ad79-4c4e-8028-001425e37d3e.jpg)

**Comment by rachelandrew** [comment]
This does not appear to be an issue with the website developer.chrome.com. If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com/.
