### ISSUE TITLE
More details on preloading modules

### ISSUE THREAD

**Issue by pavlovp** [GoogleChrome/developer.chrome.com#3319]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**

I have small confusion when reading [Preloading modules](https://developer.chrome.com/blog/modulepreload/#but-what-about-modules-dependencies) - the section about preloading dependencies.
I could not achieve this behavior in Chrome (104.0.5112.57).

**Describe the solution you'd like**

It would be great to have few more words about the potential autodiscovery of recursive dependencies that you are mentioning:

- Is Chrome implementing this now?
- Can this be triggered/enforced
- What is the status of this (sub) feature (can I track this somewhere?)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310741211
