### ISSUE TITLE
Clarify how dynamic registrations in extensions are handled

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#3324]
**Describe the bug**
The extensions documentation does not currently describe how dynamic content scripts and dynamic dNR rules are handled. Specifically, we do not highlight that dynamic registrations are cleared when an extension is updates. This ends up surprising and confusing developers ([crbug.com/1343367](https://crbug.com/1343367)).

**To Reproduce**
1. Go to the [content scripts](https://developer.chrome.com/docs/extensions/mv3/content_scripts/), [Scripting API](https://developer.chrome.com/docs/extensions/reference/scripting/), and [Declarative Net Request API](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/) pages.
2. Look for guidance on dynamic registrations, the lifecycle of a registration, or notes on when a registration to be cleared/removed.

**Expected behavior**
The documentation clearly explains the situations in which dynamic registrations will be cleared. Alternatively, there is dedicated section that describes the lifecycle of a dynamic registration.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311787421
