### ISSUE TITLE
Content feedback

### ISSUE THREAD

**Issue by nosacodes4fun** [GoogleChrome/developer.chrome.com#3334]
In Step 1 of the article, Under the sub heading # Set Up . [Open the source code for the site](https://glitch.com/edit/#!/tony). This tab will be referred to as the editor tab. The link (https://glitch.com/edit/#!/tony)) is not working as the tutorial says. Kindly update.

**Comment by jpmedley** [comment]
The link he's referring to is in the devtools instructions.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll resolve this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324137160
