### ISSUE TITLE
Misplaced brackets on console.table example

### ISSUE THREAD

**Issue by ahgilak** [GoogleChrome/developer.chrome.com#3341]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
There is a small issue on `console.table` example.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/devtools/console/api/#table
2. Scroll down to the second example.

**Expected behavior**
It should be
```js
console.table(people, ['last', 'birthday']);
```
instead of
```js
console.table(people, ['last'], 'birthday');
```

**Desktop (please complete the following information):**
 - OS: fedora
 - Browser firefox
 - Version 102

**Comment by sofiayem** [comment]
@ahgilak Thank you for catching that!
