### ISSUE TITLE
Includes are not internationalized

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#3346]
For example this article: https://developer.chrome.com/ja/docs/privacy-sandbox/attribution-reporting-experiment/

Everything is translated except "Join the discussion" and "Get updates".

Looking at the markdown, they are included by:

```
{% include 'content/privacysandbox-partials/ar-join-discussion-long.njk' %}

{% include 'content/privacysandbox-partials/ar-get-updates.njk' %}
```

We need to internationalize things under `_includes/contents`.

**Comment by matthiasrohmer** [comment]
I fear the way that's implemented is not ideal in the first place... all content in `_includes` or in other words all templates are actually language agnostic, with interface copy being translated via the `i18n` filters. That filter pulls data from the YAMLs living at /site/_data/i18n.

But that's not feasible for the mentioned type of content partials. For example ar-join-discussion-long.njk is 27 lines of Markdown, including linebreaks and links. 

Hence my suggestion is: move all the content that currently lives at /site/_includes/content to a new directory /site/en/partials. This makes sense after all as it's content. Then I'd create a new custom tag `{% partial '<includePath>' %}` which tries to find a translated partial for the current language or falls back to the English default. By setting `permalink: false` for the source files we make sure they don't get built as invdividual pages.

/cc @devnook for feedback.

**Comment by matthiasrohmer** [comment]
Tom's proposed Project Fugu and and SSPI widgets would also make use of that probably.

**Comment by agektmr** [comment]
+1 to your suggestion. I like the idea.

**Comment by devnook** [comment]
You can also name it _partials, and I think the underscore will have the same effect as permalink:false, plus it shows clearly that these are not full pages / urls. You can see _example folder to compare.

**Comment by agektmr** [comment]
Amazing. Thank you Matthias!
