### ISSUE TITLE
Provide a way to subscribe to blog posts (RSS Feed)

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#335]
**Is your feature request related to a problem? Please describe.**
I see a few developers still rely on RSS Readers and lacking RSS is a missed opportunity for them to subscribe to developer.chrome.com/blog/

**Describe the solution you'd like**
Provide RSS Feed.

**Describe alternatives you've considered**
Newsletter?

**Comment by myakura** [comment]
There's one since the launch of the new site.
https://developer.chrome.com/feeds/blog.xml
(It's an Atom feed so technically not an RSS feed though 😉)

Perhaps it should indicate it's for Chrome Developers blog in the title. Right now it's just `<title>Blog</title>`.

**Comment by agektmr** [comment]
Ohhhhh I was overlooking it. Thanks, this is helpful!
