### ISSUE TITLE
Improve Getting Started article to fix some bugs and standards

### ISSUE THREAD

**Issue by aziz-shafique** [GoogleChrome/developer.chrome.com#3353]
Found some issues while following the step by step getting started article for developing my first chrome browser extension, following the below article.
https://developer.chrome.com/docs/extensions/mv3/getstarted/

**Fixes:**
- script `popup.js` should be executed inside `window.onload`, otherwise the extension throws a runtime exception for `changeColor` element null or undefined
- script `options.js` should be executed inside `window.onload`, otherwise the extension throws a runtime exception for `page` element null or undefined

**Improvements:**
- script files `popup.js` and `options.js` should be part of HTML `<head>` section
- minor change to swap line 380 and 381, for code to look a bit more readable

**Comment by jpmedley** [comment]
@AmySteam Does this apply to your new getting started material, or can we close this as obsolete?

**Comment by AmySteam** [comment]
@jpmedley Correct, this will no longer be relevant. We can close it 👍 .

**Comment by jpmedley** [comment]
Closing because this will be replaced by a new getting started section within a week or two.
