### ISSUE TITLE
audio-worklet-design-pattern doc flaws

### ISSUE THREAD

**Issue by wothke** [GoogleChrome/developer.chrome.com#3355]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

The AudioWorklet related blogs published here: 

https://developer.chrome.com/blog/audio-worklet-design-pattern/

which seem to originate from this repository here (this is why I am posting the issue here):

https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/blog/audio-worklet-design-pattern/index.md
use incorrect information/flawed reasoning. Obvisously the flaws in the documentation should be fixed but more importantly I fear that the flawed reasoning may already have lead to flawed designs in the respective AudioWorklet infrastructure.

**To Reproduce**
Call the above doc page.

The page claims that: "This pattern is useful when replacing ScriptProcessorNode (SPN) with AudioWorkletNode. Since SPN allows the developer to pick a buffer size between 256 and 4096 frames.."

As a matter of fact the maximum ScriptProcessorNode buffer size that can be picked by a developer is 16k frames (not 4096)! Obvisouly the acutually used buffer sizes are MUCH larger that the 128 frames that are currently available in the AudioWorklet design (i.e. potentially 128x larger!).

Consequently the MickeyMouse example (used on the blog page) of a WASM function that uses a buffer 4x the size of the 128 frames is completely unrealistic. But more importantly, with regard to its "Handling Buffer Size Mismatch" suggestions the doc completely misses the main problem, i.e. the processing time that it takes (the existing, to be reused) WASM logic to actually produce the audio output: Suppose the respective logic is "expensive" and it takes 50% of the playback time to actually produce the respective audio data. It should be obvious that AudioWorklet's fixed 128 frames design can never work with that existing WASM code unless that code already uses a buffer smaller than 2x128 frames. (Supposing that existing WASM code produced 4096 frames at a time, at 48kHz sample rate each respective initial buffer calculation would take 0.0853sec and even if the resulting audio data was cached and later served to WebAudio in little 128 frame chunks, each time the respective new data is calculated, that calculation would NOT fit into the 0.00266sec windows that AudioWorklet.process() allows for the expected "128 frame processing" - it seems reasonable to assume that audio glitching would be the inevitable consequence). Given the fact that existing SPN code may be using buffers that are 128 times the size of what AudioWorklet is offering, respective WASM code may not even need to be "that expensive" and still run into the problem illustrated above.

As it currently stands, AudioWorklet is obviously unsuitable as an easy (i.e. without demanding major/expensive redesign of existing WASM application code) replacement for ScriptProcessorNode. AudioWorklet may have its advantages for some applications and I have no problems if it is the recommended API for those cases. However it should be *one* option but NOT the only alternative. I would demand that the "deprecated" status should be removed from the ScriptProcessorNode API immediately and that both APIs should continue to be offered to developers. (I am putting this here since it seems to me that the Chrome developers involved here have been driving respective developments and are in a position to ensure that this keep going into a *reasonable* direction.)

The respective blog (see https://developer.chrome.com/blog/audio-worklet/ ) motivates use of the new API by listing perceived design flaws of the old ScriptProcessorNode API. Unfortunately the blog fails to mention the big advantages of the old API, i.e. that in spite of its flaws it is perfectly "good enough" for many applications (e.g. my page here http://www.wothke.ch/websid_stereo/ ) and that it comes at a significantly lower cost with regard to code complexity and application development cost (and without the silly random limitation to no longer support http, etc).

**Comment by AaronForinton** [comment]
Hi there! Thanks for getting in touch with your issue. 

> The page claims that: "This pattern is useful when replacing ScriptProcessorNode (SPN) with AudioWorkletNode. Since SPN allows the developer to pick a buffer size between 256 and 4096 frames.."

I'm going to open a PR to fix this and acknowledge that it goes up to 16,000 frames.

> Obvisouly the acutually used buffer sizes are MUCH larger that the 128 frames that are currently available in the AudioWorklet design (i.e. potentially 128x larger!).

I've found an open issue and discussion on this point [here](https://github.com/WebAudio/web-audio-api/issues/2450), in case you'd like to jump in and voice your support.

> As it currently stands, AudioWorklet is obviously unsuitable as an easy (i.e. without demanding major/expensive redesign of existing WASM application code) replacement for ScriptProcessorNode. 

My understanding is that the flaws in ScriptProcessorNode were severe and it wasn't feasible to update it. I don't think the deprecation was done lightly. Obviously it remains in use to this day, and likely won't be _obsolete_ for a while longer, but considering it has not been officially deprecated since 2014 it's unlikely that there will be in any change in that.

**Comment by wothke** [comment]
> My understanding is that the flaws in ScriptProcessorNode were severe and it wasn't feasible to update it.

Obviously the ScriptProcessorNode has been working "good enough" for all these years (for many usecases) and and it still is up to this day! I am aware of one instance of a "severe securly related ScriptProcessorNode flaw" that was successfully fixed (I think it was in 2021) - which proves that it is perfectly feasible to still update/maintain that API without leaving any critical issues in the infrastructure.  

I am sure that the ScriptProcessorNode API has known limitations and that it may be unfeasible/undesirable to invest extra efforts to fix those - and I am perfectly fine with that. Call it a dead end - nobody expects that additional features should ever be added to that legacy API.

It is clear that even basic maintenance of any legacy API takes time (e.g. see above mentioned security fix). But from what I see the codebase of the ScriptProcessorNode related infrastructure is very tiny as compared to the extisting application codebase that has grown over the years. Migration of all that existing application code to a new API takes many orders of magnitude more effort than the effort it takes to regularly maintain the legacy ScriptProcessorNode API. (And I am glad that until now the developers of the infrastructure are making that investment and have kept support for that legacy API.) 

I think it should be kept that way and removal of this legacy API would send a very worrying message, i.e. how little the time of application developers is valued as compared to the time of the core WebAudio engine developers.  Like the WebAudio engine developers I (as an application developer) also prefer to write new stuff rather than spend my time maintaing my old stuff. I totally get it.. nobody likes to waste his time with maintenance.

But continued support for the legacy API is the best way to make sure that *overall* the least amount possible of ppls time is wasted. That's the important leverage you have in the infrastructure and you should not let that go to waste! 

(I find it quite worrying to have the threat of "ScriptProcessorNode removal" hanging over my head and it makes me wonder if I should just abandon the "browser stuff" and better direct my application development efforts to a different more stable environment. I just cannot afford to rewrite my existing code base every few years.)

**Comment by AaronForinton** [comment]
Thanks for sharing your thoughts. I think the best way to make these concerns heard would be to email [public-audio@w3.org](mailto:public-audio@w3.org?subject=%5Bwebaudio%5D%20YOUR%20TOPIC%20HERE) with subject line [webaudio]. They'll have more information about the status of the deprecation.

As I said, I'll be opening a PR to update the buffer size. Once that's merged this ticket will automatically be closed, and I'd suggest conveying your concerns about functionality to the relevant teams over on the development side using that email.

**Comment by wothke** [comment]
thanks for the email address
