### ISSUE TITLE
Change the syntax highlight colour of comments

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/developer.chrome.com#3357]
For example: https://developer.chrome.com/blog/shared-element-transitions-for-spas/

<img width="709" alt="Screen Shot 2022-08-02 at 12 28 28" src="https://user-images.githubusercontent.com/93594/182364126-0375433f-0db2-459e-b1b3-3b0b3aa63f36.png">

The syntax highlighting for comments seems to suggest they're not important. I generally disagree with this, but I particularly disagree with it on educational content – comments are just as important as the code around it.

I think we should change the colour so these stand out more. I'm happy to do a PR for this if there's agreement.

Fwiw, I did the same thing [on my blog](https://jakearchibald.com/2021/dom-cross-fade/#why-doesnt-it-work). The default highlighting was 'faded out', so I changed it to something stronger.

**Comment by jakearchibald** [comment]
I'm not a designer, but `#d06b00`?

<img width="711" alt="Screen Shot 2022-11-18 at 11 27 49" src="https://user-images.githubusercontent.com/93594/202695277-31d18d2c-f4bd-4fd5-96dd-91d034e74b73.png">

**Comment by jakearchibald** [comment]
Alternatively, have some system of documenting lines of code that isn't comment based. Again, I'm not a designer, but:

<img width="716" alt="Screen Shot 2022-11-18 at 11 48 58" src="https://user-images.githubusercontent.com/93594/202698795-b59bf36c-864a-446d-87ea-13082c3800a2.png">

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
