### ISSUE TITLE
Typo in Getting Started

### ISSUE THREAD

**Issue by justanotheranonymoususer** [GoogleChrome/developer.chrome.com#336]
"An extension's components"
https://developer.chrome.com/docs/extensions/mv2/getstarted/

**Comment by dotproto** [comment]
@justanotheranonymoususer, can you clarify the issue? What about the phrase "An extension's components" do you consider a typo?

**Comment by justanotheranonymoususer** [comment]
It's probably a combination of my poor English and my tiredness that day. Sorry for wasting your time.
