### ISSUE TITLE
[devtools] Document why Console format %c not working for url

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#3386]
Refer to https://crbug.com/1350078

**Comment by leobenkel** [comment]
what is the alternative way to display an image in dev console ?

**Comment by sofiayem** [comment]
> what is the alternative way to display an image in dev console ?

Try this:
```
background: url(data:image/png;base64,iVBORw…);
```
Where `iVBORw…` is a base64-encoded PNG image. You can use an online encoder such as [this one](https://www.base64-image.de/).
