### ISSUE TITLE
Fix range media queries example

### ISSUE THREAD

**Issue by mfluehr** [GoogleChrome/developer.chrome.com#3387]
https://developer.chrome.com/blog/new-in-chrome-104/#mq-math

The range queries example fails to apply styles between 600px and 601px.

The code should be more like this:
```
@media (width < 400px) {
  /* Styles for viewports less than 400px. */
}
@media (400px <= width < 600px) {
  /* Styles for viewports at least 400px and less than 600px. */
}
@media (600px <= width < 1000px) {
  /* Styles for viewports at least 600px and less than 1000px. */
}
```

**Comment by rachelandrew** [comment]
Yes that's correct (as in it's correct that it does not) it's an example following up on the statement before explaining the precision that the new syntax allows.

**Comment by heyawhite** [comment]
Looks like this was addressed, so closing out.
