### ISSUE TITLE
Missing type annotations for some properties of API reference

### ISSUE THREAD

**Issue by bethge** [GoogleChrome/developer.chrome.com#34]
Great website! 🥳

It seems for some API references the top-level properties have missing type annotations. E.g.:
- https://developer.chrome.com/docs/extensions/reference/extension/#property-inIncognitoContext
- https://developer.chrome.com/docs/extensions/reference/runtime/#property-id
- https://developer.chrome.com/docs/extensions/reference/sessions/#property-MAX_SESSION_RESULTS
- https://developer.chrome.com/docs/extensions/reference/tabs/#property-TAB_ID_NONE
- https://developer.chrome.com/docs/extensions/reference/windows/#property-WINDOW_ID_CURRENT

**Comment by samthor** [comment]
`inIncognitoContext` is actually an enum of either `boolean` or `undefined` (don't ask, that's what it is in the source).

But the others—you're right, thanks for pointing that out!
