### ISSUE TITLE
Suboptimal author experience with the new landing pages

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/developer.chrome.com#3405]
Related to https://github.com/GoogleChrome/developer.chrome.com/pull/3391.

- The frontmatter `description: foo bar` must appear on a single line, the usual `description: >\nfoo\nbar` does introduce weird line breaks.
- The author is forced to look up the argument order in `macros/cards/hero-card.njk`, `macros/cards/blog-card.njk`, `macros/landing-section.njk` and possibly others.
- The Workbox landing page seems to hard-code features that don't seem overridable like the orange background for the icon and a simple reduced version of the page (https://github.com/GoogleChrome/developer.chrome.com/blob/6cb1f8859b38e6036dd72ec88a92843bcb1f7108/site/en/capabilities/index.md) doesn't look as expected:
   - The icon is not displayed in the "box" and the headline appears as regular text: 

      <img width="1269" alt="Screenshot 2022-08-08 at 12 08 06" src="https://user-images.githubusercontent.com/145676/183394312-30159376-4832-402a-85fe-0700a76209a9.png">
   - The second card appears full width and not immediately under the hero card:

      <img width="1444" alt="Screenshot 2022-08-08 at 12 10 02" src="https://user-images.githubusercontent.com/145676/183394747-d60dbc57-6da6-44a7-8b31-abb5da01e8a5.png">

**Comment by devnook** [comment]
Hi @tomayac , thanks for trying out landing pages feature:) I'm sorry we don't have yet a full set of documentation for these, it would allow to avoid some of your issues (work in progress)!

Please bear in mind that this is a web development task, not purely authoring content experience. If you want to use some of the components dcc provides, you indeed need to look up their syntax. You can also use custom markup and styles if needed by your project. 

Also, this means you write an **.njk template**, not an .md file. If you **change the file extension to .njk**, your page will render correctly.

Re: hardcoded orange workbox values - bad variable name! - will fix!

**Comment by tomayac** [comment]
> Hi @tomayac , thanks for trying out landing pages feature:) I'm sorry we don't have yet a full set of documentation for these, it would allow to avoid some of your issues (work in progress)!

No worries, note that this is not to complain, just to discover where docs are needed. Documenting my findings and struggling was encouraged by @rachelandrew. 

> Please bear in mind that this is a web development task, not purely authoring content experience. If you want to use some of the components dcc provides, you indeed need to look up their syntax. You can also use custom markup and styles if needed by your project.

Understood, full freedom.

> Also, this means you write an **.njk template**, not an .md file. If you **change the file extension to .njk**, your page will render correctly.

Ah, I see. Corrected in https://github.com/GoogleChrome/developer.chrome.com/pull/3391/commits/0b9779cb109e9039489b1427b17ffab184959dc8.

> Re: hardcoded orange workbox values - bad variable name! - will fix!

Thank you!

**Comment by tomayac** [comment]
Looks a lot better already `:-)` https://deploy-preview-3391--developer-chrome-com.netlify.app/capabilities

**Comment by rachelandrew** [comment]
I like it :)

I think these are going to be really great entry points for people.
