### ISSUE TITLE
Pressing Space on the <details> element is causing page to scroll in Firefox

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/developer.chrome.com#3410]
Steps to reproduce:
1. Open Firefox release on macOS
2. Navigate to https://developer.chrome.com/en/blog/progress-in-the-privacy-sandbox-2022-06/
3. Press Tab repeatedly until the Table of contents is focused
4. Press Space

What happened: 

The table of contents opened, but the page also scrolled down. 

When I disabled JavaScript on the page (via devtools), the issue does not occur, so it seems that some JavaScript code related to focus management is causing this issue.

I have also noticed that it is not possible to move the sequential focus navigation starting point by clicking the page. Normally, when you click somewhere and then press Tab, the browser will focus the first element after the position that you clicked. But on your website, no matter where I click, pressing Tab always focuses the “Blog” link at the top of the page. So the website is definitively messing with focus navigation. 

https://user-images.githubusercontent.com/716405/183597450-ae0bcb94-7c5d-4973-8b0d-8fbd06774d64.mp4

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
