### ISSUE TITLE
Green Blocker is blocking a Website I need to access to earn Money

### ISSUE THREAD

**Issue by auntbarbie** [GoogleChrome/developer.chrome.com#3416]
Green Blocker has attacked the SilverClix PTC Website Offerwalls without even installing the Extension!  Basically, in order to even view the SilverClix PTC Website Offerwalls,the Green Blocker webpage completely covers the Offerwalls, forcing me to install the Green Blocker Extension!  I make money clicking on Ads and Green Blocker is NOT allowing me to access those Ads I need to click on to get PAID ... Even after Green Blocker is installed, whenever I try to open the SilverClix Offerwalls to earn money by clicking on Ads, the Green Blocker screen pops up, completely covering the screen with its Join Green Blocker Page  ... This is interfering with me being able to even access the SilverClix Offerwall Screen.  This is where I make money by completing Offers, Surveys, Clicking on Ads.
  
**_POSSIBLE RESOLUTION:  IS THERE A WAY I CAN BLOCK GREEN BLOCKER WHILE USING ONE SPECIFIC WEBSITE?_**

⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rachelandrew** [comment]
This is for issues related to the website at developer.chrome.com, so isn't a good place to get help with your problem.
