### ISSUE TITLE
Document how to get a persistent extension ID during development

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#3419]
**Describe the bug**
We need an easily accessible, canonical reference that describes how to get a persistent extension ID during development. Currently, the best resource for this lives in the Chrome App docset: https://developer.chrome.com/docs/apps/app_identity/#copy_key

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions
2. Look for documentation that describes how to use a static extension ID for a local extension

**Expected behavior**
The extension docs clearly describe this process. This information should near guidance on using a CWS-published extension ID for local development.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312280602
