### ISSUE TITLE
Gateway Connection Issue

### ISSUE THREAD

**Issue by onlinemarketingconnection** [GoogleChrome/developer.chrome.com#3451]
![Screenshot 2022-08-12 9 41 37 PM](https://user-images.githubusercontent.com/100047387/184464174-a3ee8c21-7ff1-4b7f-8c60-72ae756a4e12.png)
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by onlinemarketingconnection** [comment]
![Screenshot 2022-08-08 1 29 19 AM](https://user-images.githubusercontent.com/100047387/184464320-f410cbe4-0c0b-467e-8d83-e9ee2479bbd3.png)
![Screenshot 2022-08-12 10 03 29 PM](https://user-images.githubusercontent.com/100047387/184464444-91bc17ee-82a4-4a45-b52b-2038fe3b527c.png)
Please advise.

**Comment by rachelandrew** [comment]
This does not appear to be an issue with the developer.chrome.com website.
