### ISSUE TITLE
Document how extension updates are handled

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#3469]
**Is your feature request related to a problem? Please describe.**
As an extension developer, I want to understand how Chrome extension updates are distributed and installed.

**Describe the solution you'd like**
Add a new document to the Extensions or Web Store documentation that explains details update process in detail. 

**Additional context**
This request was originally reported on the Chromium project issue tracker: https://crbug.com/1280699

> Chrome Version       : 96.0.4664.110 (Official Build) (64-bit)
>
> This is for the Chrome Extension Update algorithm:
> 
> I have read thru the Chrome Extension docs, and Google Workspace Admin's view of 'auto update' and the policies,  but I am still looking for info on the actual algorithm (so to speak) for how Extensions are either 'checked/pulled/updated' to  the Chrome browser,  or how updates are 'pushed' or made available from the Chrome webstore. I suspect its more of the browser's job to update the extensions. but its unclear.   
> 
> For example, I have seen a chrome extension added after it was removed from the browser, and its added back a few days later. (windows box),  and the Extension removed twice on my Chromebook. Just trying to track down whether these are bugs ? or something else going on.
> 
> This may not be a bug at all, I simply cannot find a definitive guide on the Chrome Extension Update Algorithm.  It seems when a new version of a Chrome Extension is available in the Chrome Webstore, at some point within  a 2 week span, the extension 'may' get updated.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll address this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/312278901
