### ISSUE TITLE
Declare Permissions page missing `declarativeNetRequestWithHostAccess`

### ISSUE THREAD

**Issue by alesandroortiz** [GoogleChrome/developer.chrome.com#3470]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The page at https://developer.chrome.com/docs/extensions/mv3/declare_permissions/ does not list `declarativeNetRequestWithHostAccess` as a permission despite it being implemented since Chrome 96: https://chromium.googlesource.com/chromium/src.git/+/a0ab02487c55c8e4955227d5ec6e0d1cfc77bbce

Docs: https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#:~:text=declarativeNetRequestWithHostAccess%20(available%20since%20Chrome%2096)

`Declare permissions` page source: https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/extensions/mv3/declare_permissions/index.md

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/declare_permissions/
2. Search page for `declarativeNetRequestWithHostAccess`

**Observed behavior**
Page is missing `declarativeNetRequestWithHostAccess`.

**Expected behavior**
Page lists `declarativeNetRequestWithHostAccess` alongside other `declarativeNetRequest*` permissions

**Screenshots**
N/A

**Additional context**
I thought Edge was missing the permission on its list, but then realized they derive their list from Chrome's list, and it was also missing here. For cross-reference, bug filed in Edge docs repo: https://github.com/MicrosoftDocs/edge-developer/issues/2131

**Comment by jpmedley** [comment]
Since you just did `declarativeNetRequest`, you should probably do this one too (assuming it wasn't already on your list.)

**Comment by IanStanion-google** [comment]
This has been addressed as part of this PR for dNR documentation
[#4603 ](https://github.com/GoogleChrome/developer.chrome.com/pull/4603)
