### ISSUE TITLE
chrome.runtime.getPackageDirectoryEntry is  a undefined property

### ISSUE THREAD

**Issue by daodaolee** [GoogleChrome/developer.chrome.com#3495]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
chrome.runtime.getPackageDirectoryEntry is not a function

**Expected behavior**
The documentation has an API called `chrome.runtime.getPackageDirectoryEntry`，but I couldn't find `getPackageDirectoryEntry` property, It is normal in manifest 2, but manifest 3 is a `undefined` property.
So I wonder if the documentation is wrong, or if there is something wrong with the API itself

**Screenshots**
![](https://i.stack.imgur.com/rNWsI.png)
![](https://i.stack.imgur.com/JC02C.png)

**Desktop (please complete the following information):**
 - OS: [Macbook M1 Pro]
 - Browser [chrome]
 - Version [104.0.5112.79  arm64]

**Additional context**
I also posted this question to the s platform: [stackOverflow](https://stackoverflow.com/questions/73419407/upgrade-to-the-manifest-v3-chome-runtime-getpackagedirectoryentry-is-not-a-func
)

**Comment by AmySteam** [comment]
@daodaolee Thanks for this! This method does not work for a service worker. We are working on updating the Runtime API docs to reflect these changes.

You can migrate by [passing messages](https://developer.chrome.com/docs/extensions/mv3/messaging/) between other contexts and the service worker.

**Comment by daodaolee** [comment]
ok i got it, thanks for your feedback
