### ISSUE TITLE
Chrome DevTool Rendered Fonts Display

### ISSUE THREAD

**Issue by karisP** [GoogleChrome/developer.chrome.com#3527]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

When inspecting an element, and going to the computed styles, there is a fixed bar covering some of the computed styles that says "Rendered Fonts".

**To Reproduce**

1. Inspect a text element. Right now I have a custom font called "Inter".
2. With the Chrome Inspector open, Elements tab, Computed Styles
3. Scroll down to see a bar that says "Rendered Fonts" overlaying the computed information

**Expected behavior**

The "Rendered Fonts" bar should not be covering up other styles.

**Screenshots**

<img width="452" alt="Screen Shot 2022-08-23 at 2 08 40 PM" src="https://user-images.githubusercontent.com/42557377/186233068-ec280550-d98c-43eb-8d64-7cd9bb80c34a.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Monterery 12.2.1
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 104.0.5112.101 (Official Build) (x86_64)

**Comment by devnook** [comment]
Please report this issue on https://crbug.com
