### ISSUE TITLE
Returning to Google Chrome after extended period causes page to reload at the top

### ISSUE THREAD

**Issue by cvanvlack** [GoogleChrome/developer.chrome.com#3535]
**Describe the bug**
Open an article in Chrome. Read halfway through and then switch to another app. Come back to the article tomorrow. Chrome refreshes and puts the view at the top of the article, rather than where I left off.

**Expected behavior**
When I come back to a tab after an extended period of time, it should be at the same location on the tab.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.6
 - Browser [e.g. stock browser, safari]: Google Chrome
 - Version [e.g. 22]: 1.04.0.5112.99

**Additional context**

**Comment by rachelandrew** [comment]
This is for issues with the https://developer.chrome.com site, not Chromium itself.

If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.
