### ISSUE TITLE
[DEV TOOLS] How to Customize Default Colors in Console for log, error , warning. 

### ISSUE THREAD

**Issue by jay-p-b-7span** [GoogleChrome/developer.chrome.com#3539]
It is clear from the title itself. No need to describe the issue in detail.

**Comment by dstmarthe** [comment]
Thanks for suggesting this. We’ve moved to a new platform and so we’ll address this over there. I’ve moved the issue to our new tracker and you can see it at:
https://issuetracker.google.com/issues/324323290
