### ISSUE TITLE
Background hover on title link is broken.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#358]
Try hovering the featured article on this preview: https://deploy-preview-345--developer-chrome-com.netlify.app/

![image](https://user-images.githubusercontent.com/1066253/106538696-7d5a7000-64b1-11eb-81c7-94ebfbfb66c8.png)

This is because the `.surface` class is trying to use a `::before` element to do the background hover and it doesn't wrap properly. I think we should consider just ditching this class as it's consistently been broken.

**Comment by samthor** [comment]
I've ad-hoc fixed this for now by making more elements `display: block`.
