### ISSUE TITLE
tabGroups API not available on Stable channel

### ISSUE THREAD

**Issue by tconfrey** [GoogleChrome/developer.chrome.com#359]
The latest [API documentation](https://developer.chrome.com/docs/extensions/reference/)  lists [tabGroups](https://developer.chrome.com/docs/extensions/reference/tabGroups/) as Stable. However adding "tabGroups" to my manifest yields an error:
- 'tabGroups' requires dev channel or newer, but this is the stable channel.

I commented on an [earlier issue](https://github.com/GoogleChrome/developer.chrome.com/issues/39) reporting that the docs don't list 'since' or 'deprecated' information however I think this case warrants a separate issue listing since the docs are explicitly wrong and misleading. 

I'd like to see the docs page updated, but also any information you have on when I can expected tabGroups support to hit the Stable channel.

**Comment by samthor** [comment]
Thanks. We now correctly mark this as being stable from Chrome 89.
