### ISSUE TITLE
Many new apis listing as Stable APIs. Is it a bug?

### ISSUE THREAD

**Issue by hanguokai** [GoogleChrome/developer.chrome.com#360]
Sorry, I don't use issue template. I just want to confirm the situation first.

I find there are `app.runtime`, `app.window`,  `socket`, `sockets.tcp`, `sockets.tcpServer`, `sockets.udp` (maybe more) listing on the [API Reference](https://developer.chrome.com/docs/extensions/reference/) page. Is these a bug? I remember they are chrome app api, not extension api.

In addition, I find `processes` api listing as Stable APIs, but I remember it is Dev APIs in the past. Is this a bug?

**Comment by kospl** [comment]
Some of extension APIs also marked as deprecated app APIs, may be related to this bug, like `i18n`, `identity`:

![image](https://user-images.githubusercontent.com/26386660/107851486-06a76600-6e13-11eb-9b9d-0f2a5d0d04c4.png)

![image](https://user-images.githubusercontent.com/26386660/107851495-16bf4580-6e13-11eb-9d8c-96ab45368ead.png)

Are you guys kidding?

**Comment by hanguokai** [comment]
> Some of extension APIs also marked as deprecated app APIs, may be related to this bug, like `i18n`, `identity`:

It looks like these extension APIs are considered as chrome app APIs, so they're marked as "Deprecated". In fact, these apis are available on both extensions and apps. So these are obvious documentation errors.

**Comment by kospl** [comment]
Marking important APIs in documentation as deprecated is *just temporary error*. Last time I heard this not so long ago about payments API. So I am really hope this is an error and be fixed ASAP. 

This may be confusing for seasoned developers, but can be totally frustrating for anyone starting developing extensions. How do they know official documentation has become playground with *some errors*?
