### ISSUE TITLE
Document how to test permission prompts between extension versions

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#3605]
_Note: When this issue is resolved, also close [crbug.com/602191](https://crbug.com/602191)_.

**Describe the bug**
The extensions documentation describes how to check the permissions that the user will see at install time, but it does not currently describe how to test permissions upgrades. 

The documentation should be updated to include a section that describes the process for testing what end users will see when modifying permissions between extension versions. 

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#view_warnings 
2. Look for guidance on how to test permissions upgrades

**Expected behavior**
This document should describe how an extension developer can test permissions changes across extension versions.

**Current behavior**
Testing permissions changes across versions is not described. The [View warnings](https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#view_warnings) section describes how to view install time warnings, but does not describe the additional steps required to test changes across versions.

**Comment by AmySteam** [comment]
Fixed in #6372
