### ISSUE TITLE
Add recommended security headers

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#3618]
**Describe the bug**
We can follow our own security best practices to keep the website safer. I'm not sure if it really makes sense to apply some of them to static sites, but let's see.

- `X-Frame-Options: DENY`: Prevents other sites to embed. This can be applied to all pages except ones that expects to be embedded.
- `X-Content-Type-Options: nosniff` effective only for IE, but won't harm.
- `Cross-Origin-Opener-Policy: same-origin-allow-popups`: Prevents other sites to communicate over `postMessage` when opened with `window.open`. This can be applied to all pages except ones that expects to be communicated.
- `Content-Security-Policy`: Looks like this is already applied.
- `Strict-Transport-Security`: Looks like this is already applied.

https://web.dev/security-headers/

**Comment by agektmr** [comment]
`CSP: frame-ancestors 'self'` was already set so `X-Frame-Options: DENY` is needed.

**Comment by matthiasrohmer** [comment]
Thanks for flagging this! 

Are there any pages currently embedded somewhere? Would want some clarity on this before applying `X-Frame-Options`.

For CSP things are a little more involved... the policy that is currently deployed is report-only, so it doesn't enforce anything. But I also wouldn't want to use it as-is. For example it would be nice to only allow nonced inline scripts, but that involves some 11ty/Nunjucks fun.

**Comment by matthiasrohmer** [comment]
By the way, the [Mozilla Observatory](https://observatory.mozilla.org/analyze/developer.chrome.com) is quite useful for evaluating (existing) security measures.

**Comment by agektmr** [comment]
Sorry, it was typo. `X-Frame-Options: DENY` is **NOT** needed. So, please don't worry about it. It's already blocking being embedded.

Mozilla Observatory looks a bit outdated. https://securityheaders.com/ is also a good one.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
