### ISSUE TITLE
Chrome Extension API chrome.tabGroups is Stable but not accessible in Stable Channel 

### ISSUE THREAD

**Issue by Jonny1003** [GoogleChrome/developer.chrome.com#362]
When attempting to load an extension into the Stable build of Chrome with the manifest permissions including "tabGroups", an error stating "'tabGroups' requires dev channel or newer, but this is the stable channel." occurs. However, the Chrome extension API lists "tabGroups" as stable [here](https://developer.chrome.com/docs/extensions/reference/). Shouldn't the tabGroups API be accessible in the stable build?

**To Reproduce**
1. Build a chrome extension as shown [here ](https://developer.chrome.com/docs/extensions/mv3/getstarted/)
2. In the manifest.json of a chrome extension, under "permissions" include ["tabGroups"].
3. At [chrome://extensions/](chrome://extensions/), click Load Unpacked and select the application just created. 
4. Click "Errors" under the newly loaded extension.
5. One of the reported errors should be a warning stating "'tabGroups' requires dev channel or newer, but this is the stable channel."

**Expected behavior**
Any calls to the chrome.tabGroups API should be valid according to https://developer.chrome.com/docs/extensions/reference/tabGroups/ because the API should be stable. Currently, any calls to the chrome.tabGroups API are undefined.

There should not be a warning that tabGroups requires the dev channel because according to the documentation, the tabGroups API should be included in the stable channel already.

**Screenshots**
![image](https://user-images.githubusercontent.com/55709135/106680955-5ca71e80-6574-11eb-99e8-f68d52b052eb.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome 
 - Version 88.0.4324.146 (Official Build) (x86_64)

**Comment by benmeiri** [comment]
Any update on this one?

**Comment by jeanlucaslima** [comment]
Any updates on this? I'm following the developer portal and this is not working.

**Comment by stephenhandley** [comment]
@jeanlucaslima Yeah i'm seeing the same thing trying to follow these [docs](https://developer.chrome.com/docs/extensions/reference/tabGroups/#method-get) but getting `Cannot read properties of undefined (reading 'get')` when trying to call `chrome.tabGroups.get(id)`:

<img width="729" alt="Screenshot 2023-10-31 at 00 56 02" src="https://github.com/GoogleChrome/developer.chrome.com/assets/3257/8e32c8dc-3fd3-4e42-a46d-36362fe84bba">
