### ISSUE TITLE
Document chrome.systemPrivate.getApiKey()

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#3637]
**Is your feature request related to a problem? Please describe.**
`chrome.systemPrivate.getApiKey()` is used in neajdppkdcdipfabeoofebfddakdcjhd.
**Describe the solution you'd like**
Document how `chrome.systemPrivate.getApiKey()` works and how to use the function in extensions other than neajdppkdcdipfabeoofebfddakdcjhd shipped with Chrome.

**Describe alternatives you've considered**
Navigating to the generated HTML page to get the API key.
**Additional context**
neajdppkdcdipfabeoofebfddakdcjhd uses Google voices for Web Speech API and creates an HTML `<audio>` element on the extension page to output audio fetched over the network. 

When the user wants to record Web Speech API audio output where multiple voices are used, including Google voices and other speech sythesis engine voices it becomes problematic to create a virtual device that outputs Google voices played on Chrome and pseech synthesis engine output played through `speech-dispatcher`.

Documenting how `chrome.systemPrivate.getApiKey()` works will provide a means to fetch Google voice output and other speech synthesis voice output, and merge the audio into a single audio stream, which is currently challenging given output for each voice respectively uses two different sink inputs, where neither is output via the Tab.

**Comment by AaronForinton** [comment]
cc: [https://groups.google.com/a/chromium.org/g/chromium-discuss/c/FJ6ZZ2nlbbE](https://groups.google.com/a/chromium.org/g/chromium-discuss/c/FJ6ZZ2nlbbE)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/312275380
