### ISSUE TITLE
FR(i18n) Anyone would like to translate all `blog/*` in French language with me?

### ISSUE THREAD

**Issue by thomasbnt** [GoogleChrome/developer.chrome.com#3642]
**Is your feature request related to a problem? Please describe.**

I noticed that there is no French translation on the whole website at https://github.com/GoogleChrome/developer.chrome.com/tree/main/site/fr. So I would like to help translate, but due to the amount of files to catch up on, I am asking for help.

**Comment by heyawhite** [comment]
Hi @thomasbnt. For now, we don't support user-submitted translation. But, we hear you asking for French language support. Our team is looking at the future for translation and localization. More will come soon, and we appreciate your patience.

**Comment by thomasbnt** [comment]
> Hi @thomasbnt. For now, we don't support user-submitted translation. But, we hear you asking for French language support. Our team is looking at the future for translation and localization. More will come soon, and we appreciate your patience.

Hello @heyawhite, sad to read that! ok!
