### ISSUE TITLE
explain the error

### ISSUE THREAD

**Issue by rungrotArunon** [GoogleChrome/developer.chrome.com#3643]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Conspiracyslayer** [comment]
[deviceinfo_20220905-03_53_07.txt](https://github.com/GoogleChrome/developer.chrome.com/files/9493313/deviceinfo_20220905-03_53_07.txt)
