### ISSUE TITLE
DevTool crash while loading wasm file (150M)

### ISSUE THREAD

**Issue by aharondavid** [GoogleChrome/developer.chrome.com#3645]
**Describe the bug**
DevTools with extension debugging for c++ ,is crash while it loading wasm file (150M).
it is not happening in the former chrome version.

**Screenshots**
![image](https://user-images.githubusercontent.com/41375082/188624356-68efff14-60f7-4183-ae49-19816e07a642.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by matthiasrohmer** [comment]
Thanks for reporting that issue! Chromium uses their own bug tracker at https://bugs.chromium.org/p/chromium/issues/list

This repository here only holds documentation around dev tools. If your problem persists, please manually transfer it to Chromium's bug tracker if it hasn't been reported yet. 🙂

**Comment by aharondavid** [comment]
Ok, Thanks a lot.
