### ISSUE TITLE
Incorrect match pattern documentation.

### ISSUE THREAD

**Issue by karan173** [GoogleChrome/developer.chrome.com#366]
Go to https://developer.chrome.com/docs/extensions/mv2/match_patterns/ and https://developer.chrome.com/docs/extensions/mv3/match_patterns/. 

See the section after "Here's the basic syntax:". It is:

>  := ://
>  := '*' | 'http' | 'https' | 'file' | 'ftp'
>  := '*' | '*.' +
>  := '/' 

It should be (as seen at https://3-72-0-dot-chrome-apps-doc.appspot.com/extensions/match_patterns):

`<url-pattern> := <scheme>://<host><path>`
`<scheme> := '*' | 'http' | 'https' | 'file' | 'ftp'`
`<host> := '*' | '*.' <any char except '/' and '*'>+`
`<path> := '/' <any chars>`

We probably just need to escape < and > to display them,

**Comment by spiroskarathanassis** [comment]
Thanks to @karan173,

Also you should to include sub-domain matching in requests url filtering.
Or make it filtering with js regex syntax as String.
