### ISSUE TITLE
Need an easy way to handle inline images

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/developer.chrome.com#367]
Expected (from the old site):

![image](https://user-images.githubusercontent.com/4713486/108292463-fa8c1300-7148-11eb-8e3d-c3c29943d177.png)

Actual (on the new site):

![image](https://user-images.githubusercontent.com/4713486/108292502-05df3e80-7149-11eb-942a-6f5caf162c96.png)

My preferred approach would be to use the `{% Img %}` shortcode in both scenarios, passing some sort of flag when we need the image inline.

**Comment by samthor** [comment]
This happens because there's an `{% Img ...` inline with text.

Since there's literally no other reason to do this aside from the fact that you want an inline image, I think we should just make this do that.

**Comment by kaycebasques** [comment]
Hey @samthor we also need it for `li > img`. I'll start a PR.

![Screen Shot 2021-02-27 at 11 07 57 AM](https://user-images.githubusercontent.com/4713486/109397559-1d0df100-78ec-11eb-8ce8-1bbda0496963.jpg)
