### ISSUE TITLE
Add hover effect to social media links on author page

### ISSUE THREAD

**Issue by Vansh-Baghel** [GoogleChrome/developer.chrome.com#3682]
* Could add CSS in _https://developer.chrome.com/authors/rachelandrew/_ section like hovering the social medias , hovering the cards , also the **size of cards** aint same , which doesnt look good .
* The language part **doesn't have** options to select other languages in the authors section , which could be fixed.
* Could add amazing **overlay** effect on the image with changed cursor.

**Comment by matthiasrohmer** [comment]
Thanks for reporting! We'll consider adding a hover effect for the social links on the author pages. We do not offer options in the language dropdown if the page is not localized, but we'll discuss this. The overlay effect for the image is currently out of scope.

A quick tip for your next contribution: create three separate issues instead, that makes discussing suggestions easier.

**Comment by Vansh-Baghel** [comment]
Oh ok got it! :)
 @matthiasrohmer Can I work and add those changes to raise a PR?

**Comment by matthiasrohmer** [comment]
The social media links are currently made up of utility classes. So there unfortunately is no existing component where you could just add a `:hover` rule.

**Comment by tokyodanj** [comment]
Design approved - Option 1A

Ready to reassign for development @mollietokyo

**Comment by Vansh-Baghel** [comment]
@matthiasrohmer @simgobb Why wasn't I able to create branch and contribute?

**Comment by Vansh-Baghel** [comment]
@matthiasrohmer @simgobb isn't it possible for me to make PR related to such issues? I didn't find the code to make such changes when I raised the issue and decided to work. 🤔

**Comment by matthiasrohmer** [comment]
@Vansh-Baghel, thanks for being open to contribute! Unfortunately we currently don't have any good first issues in this project. There are occasionally some over at web.dev: https://github.com/GoogleChrome/web.dev/labels/good%20first%20issue
