### ISSUE TITLE
Investigate AppEngine custom handler viability

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#3707]

**Comment by devnook** [comment]
PR: https://github.com/GoogleChrome/developer.chrome.com/pull/3632

The approach of using GAE handler for the preview generally works, but it is very slow atm. We'd need to find ways to speed up the handler to make it viable option.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
