### ISSUE TITLE
Set up dynamic content publishing data flow

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#3709]
- [ ] Investigate Firebase functions / Cloud functions webhook option
- [ ] Set up webhook to sanity to post into
- [ ] Secure the webhook with api secret
- [ ] generate an .md template out of PortableText (basic content only, no serializers)
- [ ] Make sure 11ty is fast enough to not timeout on webhook invocation #3708 
- [ ] Add call to Github to store canonical/backup data
- [ ] Add call to Some Storage Service (TM) to store dynamic file for quick publishing 
- [ ] Resolve scheduling conflicts between dynamic content and staticly build files
- [ ] Come up with a solution for conflict resolution between Sanity and Github
- [ ] Add security checks to not leak unpublished data / files accidentally

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
