### ISSUE TITLE
Native Messaging Article and Example Outdated

### ISSUE THREAD

**Issue by tandersonzorus** [GoogleChrome/developer.chrome.com#3718]
**Describe the bug**
There is outdated documentation on Chrome Extension's use of Native Messaging. Additional information or examples may make it easier/clearer for future developers.

**To Reproduce**
1. Go to [Native Messaging docs](https://developer.chrome.com/docs/apps/nativeMessaging/) OR [Native Messaging.md file](https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/docs/apps/nativeMessaging/index.md)
2. Click on [Connect to native application section](https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-client) and then click the [declared link in the first paragraph](https://developer.chrome.com/docs/apps/nativeMessaging/declare_permissions).  The link is dead.
3. Clicking the [Examples section](https://developer.chrome.com/docs/apps/nativeMessaging/#examples) and the corresponding [example repo](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/mv2-archive/api/nativeMessaging), nothing indicates that this requires a specific version of Python and requires changes for the latest release nor need for the TKinter package. I personally was unsuccessful to get it to work even when fixing references and installing TKinter.
4. The example uses Manifest version 2 instead of 3.

**Expected behavior**
- Documentation to be up to date to the latest version of manifest and links to work.
- Example to be using latest manifest version, at least indicate what version of Python is needed, and the required dependencies either added to the install script or called out.
- It would be helpful if you call out in documentation with a warning that there are frameworks, languages and runtimes that will automatically write to stdin/stdout/stderr that have to be sure they're disabled. Example: using Console.Writeline() or other logging methods in .NET apps will break the extension communication. I saw others run into this issue through help requests online.
- If _would_ be lovely to have other languages for examples on communicating with extension. Your documentation of example [Native messaging host JSON](https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-host) even has the path to an exe file but does not have a .NET example of the host being a .NET app; just the Python version. While I am biased towards .NET it would be nice to have more host examples. 😃 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A - its your documentation

**Smartphone (please complete the following information):**
 N/A - its your documentation

**Additional context**
Maybe take a look at [Firefox's documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) to see if there is anything else that would be helpful to call out or add.

**Comment by guest271314** [comment]
I'm happy to work on this. I filed this https://github.com/GoogleChrome/chrome-extensions-samples/pull/617 some time ago. And filed this https://github.com/mdn/webextensions-examples/pull/490 re dropping support for Python 2x, which Python itself suggests doing.

The `TKinter` example _does_ work when using Python 2x.

I composed Native Messaging hosts in C, C++, PHP, JavaScript using QuickJS, and Bash which you are welcome to incorporate as samples

- https://github.com/guest271314/native-messaging-quickjs
- https://github.com/guest271314/native-messaging-c
- https://github.com/guest271314/native-messaging-php
- https://github.com/guest271314/native-messaging-cpp
- https://github.com/guest271314/native-messaging-bash

Node.js Native Mesaging host can be found here
- https://github.com/simov/native-messaging

Python 3x Native Messaging host from MDN pull request
- https://github.com/mdn/webextensions-examples/pull/157

**Comment by guest271314** [comment]
Deno Native Messaging host

- https://github.com/guest271314/native-messaging-deno

**Comment by guest271314** [comment]
Node.js Native Messaging host
- https://github.com/guest271314/native-messaging-nodejs

**Comment by AmySteam** [comment]
Fixed in #6406 and #5433

**Comment by tandersonzorus** [comment]
Awesome! Thanks y'all!
