### ISSUE TITLE
Content feedback: "Updated" & "Last updated" Date Didn't Update After Manifest V3 Requirements Were Added

### ISSUE THREAD

**Issue by bnakamoto** [GoogleChrome/developer.chrome.com#372]
https://developer.chrome.com/docs/webstore/program_policies/ as of 2021-02-04 still claims to have been "Updated on Tuesday, November 17, 2020" (1 in attached screenshot) and "Last updated: Tuesday, November 17, 2020" (3) despite presumably being updated recently with the addition of a new "Additional Requirements for Manifest V3" section (2), which was recently announced via email to Chrome Web Store developers by Chrome Web Store Communications. Archive.org took this snapshot of the page on 2021-01-21 that does not contain the new policy section – https://web.archive.org/web/20210121162246/https://developer.chrome.com/docs/webstore/program_policies/
![image](https://user-images.githubusercontent.com/1360066/106966806-e41e9a00-66fa-11eb-9928-3ad8e31e177b.png)

**Comment by dotproto** [comment]
Oh my, sorry it's taken so long to get to this. I just found this issue while Googling something barely related. I'll make a quick PR to address this now.
