### ISSUE TITLE
[devtools] Missing docs in WNDT 105 - new sourcemap setting

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#3725]
Since 105 is already in stable, we won't backfill the WNDT post, but we need to add it in the documentation.

<img width="408" alt="Screen Shot 2022-09-16 at 3 15 17 PM" src="https://user-images.githubusercontent.com/5917927/190650685-ebfbc772-a100-4089-91ec-f0f0dfe754d1.png">

Refer to https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3784603

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/312268332
