### ISSUE TITLE
Manifest v3 'optional_permissions' does not allow any URLs

### ISSUE THREAD

**Issue by whalderman** [GoogleChrome/developer.chrome.com#374]
Sorry to put more on your plate.

**Describe the bug**
`optional_permissions` in manifest v3 does not allow any type of URL (e.g. `"*://*/*"`,  `"https://*/*"`, `"https://www.example.com/"`, `<all_urls>`, etc.).

**To Reproduce**
1. Add `"https://*/*"` to `optional_permissions` in a v3 manifest and reload extension.
2. The following error should be reported: "Permission 'https://\*/\*' is unknown or URL pattern is malformed."

**Expected behavior**
Thought this would be fine, it's recommended in the docs [here](https://github.com/GoogleChrome/developer.chrome.com/blame/c928d5d07e1387400a31c21d779b24bcf90b0365/site/en/docs/extensions/reference/permissions/index.md#L42-L44).

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome (+other chromium flavors)
 - Version: 88.0.4324.150 (current stable)

**Comment by whalderman** [comment]
Similar to #140

**Comment by Pentiado** [comment]
@dotproto That PR doesn't solve the issue. It tells us to add https://*/ to "host_permissions" but it doesn't make it optional, but required. Does it mean that in MV3 it is and will be impossible to have hosts as optional?
