### ISSUE TITLE
The video player pauses itself

### ISSUE THREAD

**Issue by KVPV** [GoogleChrome/developer.chrome.com#3744]
The player pauses each time when watching a video (HTML5 and more).

Those. I mean that I open any site with video.
1. I press play.
2. After a few seconds I get a pause.

It happens like an endless loop.. I tested it in incognito mode.

I want to see the video in its entirety, instead I get a pause every time it plays.

   - Browser: Chrome 105.0.5195.136
   - Device: Android 12; SM-G998B Build/SP1A.210812

**Comment by jpmedley** [comment]
Hi,

This is not the place to report bugs in Chrome or with web pages. If the playback problems only happen on one site, it's not a problem with Chrome. If you're seeing the problem on multiple sites, then please report it through Chrome. Click the icon with three vertical dots, select 'Help & feedback' (at the bottom of the menu), then click 'Send feedback' and follow the on screen instructions. 

You should also try the video again when you get a chance. If there was a lot of cell phone usage in your area (network conditions), that can also cause playback problems. Unfortunately, browsers can't solve that.

Thanks
