### ISSUE TITLE
Add documentation of chrome.declarativeNetRequest behavior on cached requests

### ISSUE THREAD

**Issue by datvm** [GoogleChrome/developer.chrome.com#3748]
**Describe the bug**

`declarativeNetRequest` (`declarative_net_request`) is not applied when the requests are already cached by Service Worker.

See: [my question on StackOverflow](https://stackoverflow.com/questions/73770764/declarativenetrequest-declarative-net-request-does-not-work-on-cached-requests) and [discussion on crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=1175349) with [confirmation that it won't be fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=1175349#c23).

**To Reproduce**

Consider the following example that simply add a header to all responses from `example.com` and `www.google.com/maps`. `example.com` is used to show that the code is correct and works well, and for the Google Maps page, a cached version is served that bypass this rule. Note that to reproduce the issue, please access Google Maps before side-loading this extension so it can cache the page.

**`manifest.json`**:

```json
{
    "version": "3.0",
    "manifest_version": 3,
    "permissions": [
        "declarativeNetRequest"
    ],
    "host_permissions": [
        "*://*.example.com/*",
        "*://www.google.com/maps*"
    ],
    "declarative_net_request": {
        "rule_resources": [
            {
                "id": "rule",
                "enabled": true,
                "path": "rule.json"
            }
        ]
    },
    "name": "Test Net request"
}
```

**`rule.json`**:

```json
[
    {
        "id": 1,
        "priority": 1,
        "action": {
            "type": "modifyHeaders",
            "responseHeaders": [
                {
                    "header": "my-header",
                    "operation": "set",
                    "value": "my-header-value"
                }
            ]
        },
        "condition": {
            "urlFilter": "*.google.com/maps*",
            "resourceTypes": [
                "main_frame",
                "sub_frame"
            ]
        }
    },
    {
        "id": 2,
        "priority": 1,
        "action": {
            "type": "modifyHeaders",
            "responseHeaders": [
                {
                    "header": "my-header",
                    "operation": "set",
                    "value": "my-header-value"
                }
            ]
        },
        "condition": {
            "urlFilter": "*.example.com*",
            "resourceTypes": [
                "main_frame",
                "sub_frame"
            ]
        }
    }
]
```

When accessing https://www.example.com, the header is there as intended:

[![enter image description here][1]][1]

However when accessing Google Maps that has been accessed before, the header is not found because a cached version is served:

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/uBgNP.png
  [2]: https://i.stack.imgur.com/LTHmP.png

**Expected behavior**

Google Maps should add the modified header. But since it won't be fixed, I expect it to be documented on [`chrome.declarativeNetRequest` doc page](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/)

**Screenshots**

See above

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Chromium Edge
 - Version 105.0.1343.42

**Smartphone (please complete the following information):**

-

**Additional context**

-

**Comment by guest271314** [comment]
What happens when you run `chrome.runtime.reload()` between the steps?

**Comment by jpmedley** [comment]
@IanStanion-google This also feels like your swim lane. Can you please take this.
