### ISSUE TITLE
[DevTools] Add missing error types to Issues doc

### ISSUE THREAD

**Issue by sofiayem** [GoogleChrome/developer.chrome.com#3772]
iirc, the Issues tab now support more than the listed types, we don't announce all the new issue types in WNDT because it's not significant changes.

Check with the team on the types or "and more.."

_Originally posted by @jecfish in https://github.com/GoogleChrome/developer.chrome.com/pull/3613#discussion_r973539094_

**Comment by Pradeepsankhwar** [comment]
Pradeep Kumar

**Comment by sofiayem** [comment]
It's updated: https://developer.chrome.com/docs/devtools/issues/
