### ISSUE TITLE
[CSS] CSS Nesting Survey Results

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/developer.chrome.com#3788]
Proposed title: CSS Nesting Survey Results
Proposed by: argyle
Related areas: CSS
Content type: Explanation (https://documentation.divio.com/explanation/)
[Draft](https://docs.google.com/document/d/1pJ9H0I3gkvu4kAtaKJLWJRUQCbO0yEVWjQ-mvkRUm-s/edit#)
Content summary: a follow up to the survey we deployed https://developer.chrome.com/blog/help-css-nesting/

**Comment by Shasmita** [comment]
Hi, Can you assign this issue to me if available?

**Comment by argyleink** [comment]
this is still waiting for review 🙂

**Comment by argyleink** [comment]
this one is low hanging.. it's very bite size

**Comment by rachelandrew** [comment]
Thanks for your patience, this can go to PR.
