### ISSUE TITLE
Make webserver's TLS certificate verification status and certificate data available in DOM as an object

### ISSUE THREAD

**Issue by majorisgit** [GoogleChrome/developer.chrome.com#3838]
Make TLS certificate verification status and certificate data available in DOM as an object.
It will help sites to do their own display of connection status in rendered pages, and improve security visibility. 

⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by devnook** [comment]
This is not related to developer.chrome.com website. Please consider raising issue in https://crbug.com/.
