### ISSUE TITLE
Support for Media Recorder or an alternative for Media Recorder in manifest v3

### ISSUE THREAD

**Issue by Thycotic123** [GoogleChrome/developer.chrome.com#3846]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Desktop (please complete the following information):**
 - OS: Windows and MAC os
 - Browser: Chrome, Microsoft Edge, Firefox And Safari
 - Version: Latest chrome version

**Additional context**
We have a web extension Called Web Password Filler, where we have a feature called session recording. For recording purpose we use media recorder. Now in manifest v3 media recording is not supported. So our feature is not in use and are trying to find an alternative for media recorder. Can any one please suggest alternative for media recorder in manifest v3?

**Comment by dstmarthe** [comment]
Hi, I gotta close this issue since we are migrating to a new platform and this issue isn't specific to the d.c.c website. But I would suggest you ask this on the Chromium group: https://groups.google.com/a/chromium.org/g/chromium-extensions
