### ISSUE TITLE
Intensive throttling is not achieved by chrome flags on Version 88.0.4324.146 or with Google Chrome Beta Version 89.0.4389.40

### ISSUE THREAD

**Issue by abhayp505** [GoogleChrome/developer.chrome.com#385]
Intensive throttling is not achieved by chrome flags and Google Chrome Beta Version 89.0.4389.40, even youtube, Linkedin videos are playing at same speed.

**Enabling with command line.**
1. Open terminal application 
2. Run the command :- /Applications/Google\ Chrome.app/Contents/MacOS/Google\ ChromeBeta.app --enable-features="IntensiveWakeUpThrottling:grace_period_seconds/10,OptOutZeroTimeoutTimersFromThrottling,AllowAggressiveThrottlingWithWebSocket". 
3. Play any long length (30 minutes) video in HD (1080 p).
4. Minimise the tab for 10 or more minutes.
5. Check if throttling happening and impact on video.

OR
**Enabling with Chrome//flags.**
1. Open Google Chrome.
2. Go to chrome://flags/
3. Search for #intensive-wake-up-throttling
4. Select option "Enable" or "Enabled 10 second after tab is hidden"
5. Play any long length (30 minutes) video in HD (1080 p).
6. Minimise the tab for 10 or more minutes.
7. Check if throttling happening and impact on video.
8. Check if throttling happening and impact on video.

OR
**Chrome Beta Version**
1. Go to https://www.google.com/chrome/beta/
2. Download and install Chrome Beta Version 89.0.4389.40
3. Repeat the steps mentioned in above scenarios.

Throttling should happen after the tab is minimised for more than 30 seconds and either video quality played should reduce or video should not play at normal speed. The impact of throttling should be observed on Chrome.

**Desktop** 
 - OS: macOS Catalina, Version 10.15.6
 - Browser: Chrome Version 88.0.4324.146
 - Browser: Chrome Beta Version 89.0.4389.40

The purpose of the bug is to check the effect of throttling on some videos and display Ads. But as couldn't see any throttling is happening and no effect is observed on the HD videos played.

Please suggest if there is any other way to do throttling.
The dev tools options is tried with different network bandwidth selection like 3G or slow 3G and custom. But to test performance of the Ads on default "Intensive Throttling" in Chrome.

For reference:- https://developer.chrome.com/blog/timer-throttling-in-chrome-88/

**Comment by dotproto** [comment]
This repo is for Chrome's developer documentation, but it appears that you're attempting to report a bug with Chrome itself. For Chrome/Chromium bugs, please file bug reports on [crbug.com/new](https://crbug.com/new).
