### ISSUE TITLE
Update logo on blogposts

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#3860]
From Harleen:
Some of the blogs with no headers have a fallback image with the old chrome logo (for example: https://developer.chrome.com/blog/storage-partitioning-dev-trial/) 

Could you please add an issue to get the logo updated to the [new one](https://drive.google.com/file/d/1VX_2NNfeTkzlLfq0EPd89heLYGnGmgbp/view?usp=sharing&resourcekey=0-4AOjLMbTx0fwGLk2feMkTw)?

**Comment by Niamhtokyo** [comment]
@devnook John has requested access to the new logo.
