### ISSUE TITLE
CPU Utilization is not captured with Compute Pressure API

### ISSUE THREAD

**Issue by sudhrao** [GoogleChrome/developer.chrome.com#3867]
**Describe the bug**
https://developer.chrome.com/docs/web-platform/compute-pressure API should be supported in Chrome browser version > 92 as per document but when I click on try demo here https://googlechrome.github.io/samples/compute-pressure/index.html I see the status as 'Not Available' so does this mean this API is still not ready yet?
PS: I'm using chrome browser version 106

**To Reproduce**
1. Go to https://googlechrome.github.io/samples/compute-pressure/index.html from a chrome browser with version 106
2. Notice the API Status as 'Not Available' as shown in the screen shot

**Expected behavior**
API should provide upto-date CPU utilization information when the API is available

**Screenshots**
Attached below.

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browserchrome
 - Version 106.0.5249.61 
<img width="663" alt="Screen Shot 2022-09-28 at 4 00 56 PM" src="https://user-images.githubusercontent.com/114625613/192904365-cef86feb-d9e7-4217-a7a2-fbdd26cc4693.png">

**Additional context**
Are there any alternate ways to capture CPU utilization on Chrome/Web broswer?

**Comment by sudhrao** [comment]
Could you someone from chromium also verify ASAP if this is no longer supported?

**Comment by dstmarthe** [comment]
Hey, been a while. I'm not sure what the article said before it was updated, but I'm assuming it has only been working if you register for the origin trial. The status is accurate as of now., still in trial phase, which means you need to register to use it. The article has been updated with information on how to try it out. 

Hope this clears things up.
