### ISSUE TITLE
self signed certificate used to work with chrome extension Manifest v2 after accepting it, chrome extension Manifest v3 keeps on giving same certificate error

### ISSUE THREAD

**Issue by avinashdixit** [GoogleChrome/developer.chrome.com#3868]
self signed certificate used to work with chrome extension Manifest v2 after accepting it, 
chrome extension Manifest v3 keeps on giving same certificate error, is there any security policy that we need to add or any workaround for it?

**Comment by guest271314** [comment]
Can you provide more details?

**Comment by dstmarthe** [comment]
Hi, I have to close this because this repo is for d.c.c content issues. you may want to visit https://bugs.chromium.org/p/chromium/issues/list
