### ISSUE TITLE
Enabling devtool debugger to redo changes

### ISSUE THREAD

**Issue by farzan-dehbashi** [GoogleChrome/developer.chrome.com#3883]
Currently, the debugger works in one direction. Starts and shows the variables values at each step. But, if the developer wants to see the values in previous step, she should start once again from the scratch. I was thinking of a mechanism to either save all the values at each stage so that later on it can be accessed. Or, enabling the debugger to go reverse and redo the progress.

**Comment by rachelandrew** [comment]
This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.
