### ISSUE TITLE
DevTool is crash on loading wasm file

### ISSUE THREAD

**Issue by aharondavid** [GoogleChrome/developer.chrome.com#3888]
**Describe the bug**
During debugging c++, after a few steps, DevTool is loading wasm file and crash!
What is the trigger for wasm loading and who can I avoid it ?

**Screenshots**
![image](https://user-images.githubusercontent.com/41375082/193512055-e54823c9-36c2-4773-bb1b-751b831cb4c1.png)

**Desktop (please complete the following information):**
 - OS:Windows 11
 - Browser chrome 
 - Version 106.0.5249.91 (Official Build) (64-bit)

**Comment by matthiasrohmer** [comment]
Thanks for reporting! As this repo is for reporting bugs and problems with the site developer.chrome.com we unfortunately can not provide you with more support here. Please raise your issue again in the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list).
