### ISSUE TITLE
mv3 optional_host_permissions are not documented

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#3894]
**Describe the bug**
the mv3 `optional_host_permissions` manifest field is not documented

the manifest mv3 docs show:
https://developer.chrome.com/docs/extensions/mv3/manifest/#overview
```
  "optional_host_permissions": ["..."],
```

which links to:
https://developer.chrome.com/docs/extensions/reference/permissions/

but there is no mention of "optional_host_permissions" in that page anywhere.

**Comment by jpmedley** [comment]
Rolling this into #163
