### ISSUE TITLE
Demo site is unsafe

### ISSUE THREAD

**Issue by afinzel** [GoogleChrome/developer.chrome.com#3913]
**Describe the bug**
on https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/blog/referrer-policy-new-chrome-default/index.md the demo site that is linked is unsafe according to chrome, https://site-one-dot-referrer-demo-280711.ey.r.appspot.com/stuff/detail?tag=red&p=p0

**To Reproduce**
Go to page click demo

**Expected behavior**
I would expect any demo sites to not be flagged in chrome as dangerous and a phishing site.

**Screenshots**
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/565023/194104262-2d406268-d078-4d63-a393-7e60a9c0c57e.png">

**Comment by samdutton** [comment]
@maudnals FYI
