### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by spencer-easton-ait** [GoogleChrome/developer.chrome.com#3927]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Can not open https://developer.chrome.com/docs from chrome or firefox. 

**To Reproduce**
1. Go to (https://developer.chrome.com)
2. Click on the docs icon OR browse directly to https://developer.chrome.com/docs
3. Get too Many redirect errors

**Comment by matthiasrohmer** [comment]
Thanks for reporting! The issue is now resolved and was due to corrupt language redirects.
