### ISSUE TITLE
generated API docs lack channel limitations

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#3934]
let's look at `chrome.action` APIs:
* [isEnabled](https://developer.chrome.com/docs/extensions/reference/action/#method-isEnabled)
* [openPopup](https://developer.chrome.com/docs/extensions/reference/action/#method-openPopup)

These docs make it sound like these APIs are readily available which is def not the case.  both are only available in dev channel:
> https://source.chromium.org/chromium/chromium/src/+/refs/tags/108.0.5311.0:chrome/common/extensions/api/_api_features.json;l=65
> ```
> "action.openPopup": {
>   // TODO(https://crbug.com/1245093): Upgrade to stable channel.
>   "channel": "dev"
> },
> ```

the API docs really should surface all these channel limitations so people don't waste time trying to use things that aren't yet available in the dev channel.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker. Didn't include the mention because it's not relevant to solving the issue. You can see the moved issue at: https://issuetracker.google.com/issues/311471189
