### ISSUE TITLE
[content] Add a note to getDisplayMedia documentation to clarify systemAudio

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#3957]
#### Provide a brief title for your content proposal

In spite of `getDisplayMedia()` controls having the name `systemAudio` `getDisplayMedia()` *_does not_* capture entire system audio, at best only capture Tab, and does not capture audio output by Web Speech API `speechSynthesis.speak(new SpeechSynthesisUtterance())` called on the same Tab.

#### Provide a brief summary of your content proposal

Informative blog post/article explaining the above, to avoid confusion about what `systemAudio` means, and doesn't mean.

#### What content already exists on this topic?

None.

#### Who will be authoring the content?

guest271314

#### Are there any stakeholders who should be informed when this content changes?

[eladalon1983](https://github.com/eladalon1983)
[beaufortfrancois](https://github.com/beaufortfrancois)

#### What area is your content related to?

Accessibility.

#### What kind of content are you creating?

Other.

**Comment by rachelandrew** [comment]
I don't think we need a whole post about this. If you wish to propose a clarification to the existing one then please do so. Or, write your post on your own platform, and we can review and see if it makes sense to link to it. In general, the content of this blog is very much about what the Chrome team are doing, rather than posts from third parties.

**Comment by guest271314** [comment]
> If you wish to propose a clarification to the existing one then please do so. 

I tried that.

You locked the issue.

Google invests substantial resources into TTS/SST.

However, if an individual is vision impaired and want to send the output of `speechSynthesis.speak()` to a peer there is no way to do so.

That is important. Not an acessibility issue to be set aside.

**Comment by guest271314** [comment]
Your form "Propose new content" template:

> * Use this template to propose new content.
> * Delete any fields that aren't relevant to your issue.
> * Update the title of this issue with a brief summary of the work to be done.

> ### Content proposal form for contributors who don't have access to Googlers

Now, when we read `systemAudio` constraint there is no note or indication that `speechSynthesis.speak()` will not be captured, even though the audio is output at the system level.


If an individual is vision and speech impaired there is no way to comunicate using Web API's - even though the technology exists to do so. That is a (deliberate) failure to address accessibility.

**Comment by rachelandrew** [comment]
> > If you wish to propose a clarification to the existing one then please do so.
> 
> I tried that.
> 
> You locked the issue.
> 
> Google invests substantial resources into TTS/SST.
> 
> However, if an individual is vision impaired and want to send the output of `speechSynthesis.speak()` to a peer there is no way to do so.
> 
> That is important. Not an acessibility issue to be set aside.

I locked a merged PR that you were commenting on, because a merged PR is not a good place to discuss anything.

In addition, writing a blog post doesn't help with your issue, as I mentioned when locking the issue you have a mixture of suggestions for the spec and for content here. If I were you I'd raise your spec concerns as an issue with the spec, rather than in this repo which is purely about the content of the developer.chrome.com site.

Also, please do check out our [code of conduct](https://opensource.google/documentation/reference/releasing/template/CODE_OF_CONDUCT), people are generally helpful here, but we ask for and expect respectful discussion.

**Comment by guest271314** [comment]
I have not been not "respectful".

I use direct communication.

I am proposing notifying users that `systemAudio` does not mean system audio. That is not a specification matter, that is advising users of what is actually happening, and what is not.

I don;t get the resistence to notifying users of the facts.

**Comment by rachelandrew** [comment]
An update to the article will not make the situation you raise better though? For example, it won't change:

> However, if an individual is vision impaired and want to send the output of speechSynthesis.speak() to a peer there is no way to do so.

I'm trying to point you to a way to get your actual concerns addressed. 

I can retitle the issue to say that you want a note added to clarify what `systemAudio` means, which I'll do now and the author can take a look.

**Comment by rachelandrew** [comment]
@beaufortfrancois can you take a look at this issue and the related PR https://github.com/GoogleChrome/developer.chrome.com/pull/3947/files

**Comment by guest271314** [comment]
> I'm trying to point you to a way to get your actual concerns addressed.

I already filed multiple specification and vendor issues re this matter. 

I am not trying to "get" anything. The point of the note is to notify/advise users in the filed that nothing has changed re failure to employ the technologies available to make Web Speech API and `getDisplayMedia()` function as expected.

> I can retitle the issue to say that you want a note added to clarify what systemAudio means, which I'll do now and the author can take a look.

That is all this is for. A note. The facts are specifications and implementations have not written it out to capture `speechSynthesis.speak()`. and `getDisplayMedia()` doesn't do that either, in spite of the fact the term `systemAudio` constraint is used.

I think code demonstrates why notification about limitations of `systemAudio` constraint is important.

Do you expect for audio output of `speechSynthesis.speak()` called on the same captured Tab, with `audio` constraint, and `systemAudio` constraint to be captured?

If not, why?

```
var utterance = new SpeechSynthesisUtterance('Test, test, test. Test to the point it breaks.');
var stream = await navigator.mediaDevices.getDisplayMedia({
  audio: {echoCancellation: false},
  video: {displaySurface: 'browser'},        // Ask to capture audio; caveat follows.
  systemAudio: "include", // Do not offer to capture *system* audio.
  surfaceSwitching: "include"
});
var recorder = new MediaRecorder(stream);
recorder.ondataavailable = (e) => { console.log(URL.createObjectURL(e.data)); }
utterance.onstart = (e) => { recorder.start(); }
utterance.onend = (e) => { recorder.stop(); }
speechSynthesis.speak(utterance);
```

**Comment by beaufortfrancois** [comment]
@rachelandrew FYI We've closed https://github.com/GoogleChrome/developer.chrome.com/pull/3947/

**Comment by guest271314** [comment]
@beaufortfrancois This proposes new content re the two questions posed at the end of https://github.com/GoogleChrome/developer.chrome.com/issues/3957#issuecomment-1273938931. Independent of https://github.com/GoogleChrome/developer.chrome.com/pull/3947.

**Comment by dstmarthe** [comment]
Hi, thanks for bringing this to our attention. I have to close this because we are migrating d.c.c. issues and it looks like the authors have made their decision on this issue.
