### ISSUE TITLE
Implement playlist component for Landing Pages

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#3959]
![Image](https://user-images.githubusercontent.com/1914261/194893630-c6695f31-a550-4c86-b6d1-14d12026fe51.png)

https://www.figma.com/file/koVhYNpf2SXKuqm2yJ8qkj/Workbox?node-id=413%3A29491

**Comment by simgobb** [comment]
03.02 / Submitted Data Fetching Plan doc. Suggested that the data fetching would happen through an external data flow as opposed to the solution implemented originally in the PR. 

CC @mollietokyo

**Comment by mollietokyo** [comment]
Estimate = 3 days remaining (SPR-3)

**Comment by simgobb** [comment]
The external data flow fetching the data has been approved and merged.

The component part needs extra work as it was originally thought of as a shortcode, but to keep things consistent with the rest of the landing page components, it needs to be refactored in a macro.

To keep the macro simple, a lot of the logic will need to be moved in the data-fetching part of the PR. 

CC @mollietokyo @matthiasrohmer

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
