### ISSUE TITLE
Extract common styles of DCC to create a minimalistic theme

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#3962]
The theme would be used as a basic css for demos and samples written by the team.
Must be:

- lightweight
- compatible with DCC / web.dev look&feel
- versioned

**Comment by Truemedia** [comment]
An example could be @webdev-infra/shortcode-video for the name of the package containing the video shortcode and @webdev-infra/iframe for the iframe shortcode package

**Comment by Truemedia** [comment]
@devnook Yes I thought that might be a case I just saw it as a potential prerequisite to be able to efficiently have a base to build these extracted styles on and clean up dependencies in general. I'll open a seperate ticket

**Comment by Truemedia** [comment]
On the DCC site collect 10 examples of external demos, gather a list of native and none native HTML/web components used

**Comment by Truemedia** [comment]
Link to expose created stylesheet on DCC domain as externally included stylesheet (demo.css)

**Comment by matthiasrohmer** [comment]
Closing in favour of https://github.com/GoogleChrome/webdev-infra/issues/48.
