### ISSUE TITLE
Revamp CSP policy for DCC / web.dev

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#3964]
We need to:

- set up proper CSP policy for DCC
- provide way to enable external and inline scripts compliant with the policy on DCC
- review policy for web.dev
- consider performance implications of sending big CSP headers payload on each request
- write up documentation on the final solution

**Comment by matthiasrohmer** [comment]
CSP headers should also go per route to prevent bloating headers with nonces for scripts not used on every page. For web.dev we ship roughly 2.8KB of CSP headers for every request right now.

**Comment by devnook** [comment]
Related: #3618

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
