### ISSUE TITLE
Implement `{% ImplementationStatus %}` shortcode to get rid of manual table maintenance

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#3965]
Throughout the site we use [manually maintained tables](https://developer.chrome.com/docs/web-platform/launch-handler/#current-status) to communicate the progress a feature has made so far. While the tables are currently labeled as "Current Status" it has been internally discussed that simply stating "Status" in this context makes it apparent to readers that it is current. The relabeling can be done when replacing the manually maintained tables with the new shortcode.

While the current implementations use a table to summarise the data described in more detail below, a visually more appealing solution is preferred, for example using some sort of a timeline.

Keeping those tables up-to-date manually is tedious, while the data could actually be pulled in automatically by querying the same data source chromestatus.com uses with [GoogleChromeLabs/status-query](https://github.com/GoogleChromeLabs/status-query) (Node.js 18 required). For example consider the following command and response querying [chromestatus.com](https://chromestatus.com/feature/5722383233056768) for the [Launch Handler API](https://developer.chrome.com/docs/web-platform/launch-handler/#current-status):

```sh
$ node main.js status 5722383233056768

================================================================================
Web app launch handler
================================================================================
If not launched:
----------------
The Web app launch handler is part of the capabilities project and is currently in development. This post will be updated as the implementation progresses.

Else:
----------------
The Web app launch handler was part of the capabilities project and has now been shipped.

Explainer: https://github.com/WICG/sw-launch/blob/main/launch_handler.md
Specification: Not started
Origin trial: Origin trial
Launch: Not started
```

This text is constructed from an even richer JSON (see status-query source for details) which holds all the data that we want to surface in the DCC status table rows for **Create Explainer** and **Create initial draft of specification**.

For the **Gather feedback & iterate on design** row: If Launch status is launched, "Complete", else "In progress" linking to the #feedback anchor on the bottom of the page. Chrome version number info with release dates is available via the [Chrome version history API](https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/dev/versions/all/releases?filter=channel%3C=dev,fraction=1)
 
Info for the **Origin trial** row is available via a [the Chrome Origin Trial API](https://developer.chrome.com/origintrials/).: If the origin trial is over, "Complete", else "Started" linking to `https://developer.chrome.com/origintrials/#/view_trial/<TRIAL_ID>`.

**Launch**: If launched, "Complete (Chromium <VERSION>)", else, "Not started". The (projected) launch version will also be available from the status-query result.

In the end the existing tables should be able to be replaced with `{% ImplementationStatus '<FEATURE_ID>' %}`.

**Comment by jpmedley** [comment]
Benefits of using Chrome Status data to DevRel:
* Faster updates of Status tables. DevRel members will be able to update status tables by editing the underlying status entry. Updates will appear in the next deployment of the site, which happens in a matter of hours. Currently opening a PR to update this data can take several days to a week.
* Improved accuracy of the Chrome Status data. The [beta announcement](https://developer.chrome.com/blog/chrome-107-beta/) is now generated by a script. Since there is no human reviewing the content, that material is only as good as the underlying Chrome Status data.

**Comment by jpmedley** [comment]
Given that this is such a simple project and that revenues are down, why would we not just do this ourselves instead of hiring someone. I'm willing to collaborate if anyone is interested in working on this. (Our existing macros were all done by DevRel members who just thought it needed to be done.)

**Comment by devnook** [comment]
Thanks for volunteering your time, Joe! I'm sure eng working on this would appreciate having a contact person to consult the design of the macro and to test the feature prior to the release. I'll keep you in the loop.

**Comment by tokyodanj** [comment]
@devnook - design ready for review - link added to [google doc](https://docs.google.com/document/d/1W_iFdCLmgm1CjC26xCB4AUC11k9neNmR-XQB5bckPu4/edit?usp=sharing)

**Comment by jpmedley** [comment]
Am I missing something? I don't see anything about the new shortcode.
Joe Medley | Technical Writer, Chrome DevRel | ***@***.*** |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by tokyodanj** [comment]
Hey @jpmedley - we mocked up a design in response to the following request on this ticket:

> While the current implementations use a table to summarise the data described in more detail below, a visually more appealing solution is preferred, for example using some sort of a timeline.

@Truemedia will be handling the shortcode implementation following approval of the design.

**Comment by jpmedley** [comment]
Thanks. Your previous message implied that the design for the shortcode was
contained in the materials you supplied. I do not see a mock up for the
shortcode.
Joe Medley | Technical Writer, Chrome DevRel | ***@***.*** |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by devnook** [comment]
@Truemedia - Hi Wade, design is ready in figma, you can continue with implementation.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
