### ISSUE TITLE
Focus Mode sample extension tutorial is missing two consts

### ISSUE THREAD

**Issue by Jakedalus** [GoogleChrome/developer.chrome.com#3991]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
[Step 4](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/#step-4) of the Focus Mode tutorial is missing the consts `extensions` and `webstore` which are used in the `addListener`

**To Reproduce**
1. Go to [Step 4](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/#step-4)
2. See that the two consts aren't defined anywhere in the tutorial writeup

**Expected behavior**
The consts should be defined above the `addListener` call

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AmySteam** [comment]
@Jakedalus Thanks for catching this! 🙂 👍

**Comment by azigler** [comment]
@AmySteam Related to this issue, the tutorial instructions you to make your `manifest.json` look like this:

```json
{
  "manifest_version": 3,
  "name": "Focus Mode",
  "description": "Enable reading mode on Chrome's official Extensions and Chrome Web Store documentation.",
  "version": "1.0",
  "icons": {
    "16": "images/icon-16.png",
    "32": "images/icon-32.png",
    "48": "images/icon-48.png",
    "128": "images/icon-128.png"
  }
}
```

But without an `actions` property in your `manifest.json`, `onClicked` will be undefined for `chrome.action` in `background.js` with this error:

```sh
Uncaught TypeError: Cannot read properties of undefined (reading 'onClicked')
```

Looking at the [example code](https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/tutorials/focus-mode/manifest.json), it has this in the `manifest.json`:

```
...
"action": {
  "default_icon": {
    "16": "images/icon-16.png",
    "32": "images/icon-32.png",
    "48": "images/icon-48.png",
    "128": "images/icon-128.png"
  }
},
...
  ```

I added `"action": {}` to my `manifest.json` and was able to finish the tutorial successfully (after adding the two `const`s mentioned in this this PR).

Great tutorial! Really enjoying learning about V3! 🎉

**Comment by AmySteam** [comment]
@azigler Glad to hear you are enjoying the tutorial! 😄 

Looks like I added the `action` key in [Step #3](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/#step-3). 🤔 I tried to explain the different keys in separate steps, but I may have to tweak it a bit so that other developers don't have this problem.

I'm happy you were able to complete it in the end! 🎉

**Comment by azigler** [comment]
> @azigler Glad to hear you are enjoying the tutorial! 😄
> 
> Looks like I added the `action` key in [Step #3](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/#step-3). 🤔 I tried to explain the different keys in separate steps, but I may have to tweak it a bit so that other developers don't have this problem.
> 
> I'm happy you were able to complete it in the end! 🎉

Oops, I didn't catch that part. Thanks for pointing it out!
