### ISSUE TITLE
chrome.printerprovider page does not display it's information properly

### ISSUE THREAD

**Issue by pEJipE** [GoogleChrome/developer.chrome.com#40]
The chrome.printerprovider event don't display the event passed parameters making it unusable. 
When callback function are used there is no description of the expected input parameter nor number of parameter. 

I had to look at the Google search cached page (old page) to get event desciption. 

I don't look at other API but it seems the issue is for all event.

**Comment by samthor** [comment]
Hi, this will be fixed soon—it was a bug that slipped into production.
We've already fixed it in our internal repository. Sorry for the
inconvenience!

**Comment by samthor** [comment]
This is now fixed. Apologies again: https://developer.chrome.com/docs/extensions/reference/printerProvider/#event-onGetCapabilityRequested
