### ISSUE TITLE
Add a different mechanism to ignore external docs than env flags

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#4000]
Right now we use env variables to control whether external docs sources should be processed by eleventy on a given run. This leads to awkward use of process.env in cases, where we need to exclude these docs as an exception at runtime:

process.env.ELEVENTY_IGNORE_EXTENSIONS = 'true';

We should add a different mechanism to ignore these docs than env flags.

**Comment by devnook** [comment]
See https://github.com/GoogleChrome/developer.chrome.com/pull/3932

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
