### ISSUE TITLE
Debugging native messaging is incomplete, lacks details

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#4028]
**Describe the bug**
[Debugging native messaging](https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-debugging) states

> When the native messaging host fails to start, writes to `stderr` or when it violates the communication protocol, output is written to the error log of Chrome. On Linux and OS X, this log can easily be accessed by starting Chrome from the command line and watching its output in the terminal. On Windows, use --enable-logging as explained at [How to enable logging](https://www.chromium.org/for-testers/enable-logging).

The paragraph does not state 

1. What to look for in `chrome_debug.log` when Chrome is launched with `--enable-logging` flag relevant to Native Messaging errors;
2. `--enable-logging` quickly becomes voluminous, e.g., before `chrome.runtime.sendNativeMessage()` or `chrome.runtime.connectNative()` are called the log file `chrome_debug.log` could easily contain greater than 9KB of errors unrelated to Native Messaging

**To Reproduce**
1. Launch Chrome with `--enable-logging` flag
3. Observe error message `chrome_debug.log` in Chrome configuration/user data directory folder

**Expected behavior**
A clear and concise description of what you expected to see in `chrome_debug.log` relevant to Native Messaging errors.

**Additional context**
As far as I can tell there is no way to log **_only_** error messages generated by Native Messaging implementation.

For example, when launching Chrome with

```
chrome --enable-logging=stderr --v=0 --vmodule=native_message*=0
```

then running the following code which sends a message from client to host greater than 1024*1024

```
port = chrome.runtime.connectNative('nm_c');
port.onMessage.addListener((m) => console.log(m));
port.onDisconnect.addListener((e) => console.log(chrome.runtime.lastError));
port.postMessage(new Array(458*458));
```
in `onDisconnect()` handler this will be printed at `console`

```
{message: 'Error when communicating with the native messaging host.'}
```
however, that same message will not be printed in `chrome_debug.log`.

We will have to search among over 9KB of error messages to locate

```
[...:...:...:ERROR:native_message_process_host.cc(300)] Native Messaging host tried sending a message that is 1048821 bytes long.
```
corresponding to 
```
[ process_id : thread_id : ticks_in_microseconds : log_level : file_name(line_number) ]
```

"Debugging native messaging" should contain the details

1. `chrome_debug.log` will generate error messages (or all messages depending on the log-level set) completely unrelated to Native Messaging; 
2. The error message output by `chrome.runtime.lastError` is not the same as the one generated by `LOG()` at https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/extensions/api/messaging/native_message_process_host.cc;l=299-304 written to `chrome_debug.log`
    ```
    if (message_size > kMaximumNativeMessageSize) {
      LOG(ERROR) << "Native Messaging host tried sending a message that is "
                 << message_size << " bytes long.";
      Close(kHostInputOutputError);
      return;
    }
    ```

As far as I can tell there is no way to log _only_ errors generated by Native Messaging with `--vmodule` flag.

Users need to be aware that depending on the log level set `chrome_debug.log` can easily grow to 40MB or greater, just to get a single error message from Native Messaging host implementation; and that they need to look for `native_message_process_host.cc` in the log file.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310764458
