### ISSUE TITLE
Manifest 3 - Generate links and save file

### ISSUE THREAD

**Issue by SupraWaza** [GoogleChrome/developer.chrome.com#4042]
Hello,

Have you an example who automatically saves it to a file on the hard drive.

Thanks

**Comment by dstmarthe** [comment]
Hi , thanks for raising this. I see that it's been a while since this was posted, but we've moved to a new issue tracker and this might be good to have, so we'll resolve it over there.  You can see it here: 
https://issuetracker.google.com/issues/324133447

**Comment by jpmedley** [comment]
@SupraWaza, can you please provide more information. I'm not sure what you're asking.
