### ISSUE TITLE
Expose IDs on landingSection macros

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#4053]
**Is your feature request related to a problem? Please describe.**

At the moment it's not possible to link directly to given section on a landing page because sections do not have IDs. Currently, the closest thing we can do is use a text link to reference the title of a section. For example: https://developer.chrome.com/workbox/#:~:text=what%20you%20need%20to%20know

**Describe the solution you'd like**

IDs for section titles should be automatically assigned similar to how headers are automatically given IDs. Ideally, content authors would also be able to manually provide IDs to account for string changes.

**Describe alternatives you've considered**

At the moment, the only workaround I can think of is to manually embed an anchor with an ID before a section (e.g. `<a id="example">`). That said, I haven't experimented with this approach.

**Additional context**

N/A

**Comment by mollietokyo** [comment]
**Estimate** - 4hrs

**Comment by mollietokyo** [comment]
Estimate for dev = 1.5 days (SPR-3)
