### ISSUE TITLE
Do not register unused shortcodes

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#4056]
For code cleanliness and less confusion we should not register unused shortcodes and fix documents that potentially used them, though a quick search showed none do.

https://github.com/GoogleChrome/developer.chrome.com/blob/711a79e65ea0cfcfeae153da2ac70b4bd47bf5da/.eleventy.js#L151-L155

**Comment by devnook** [comment]
This was a temporary solution to provide compatibility with web.dev when we were in the stage of intense moving of documents between the sites. I would not remove them until @rachelandrew confirms this work is completed.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
