### ISSUE TITLE
Add documentation for webRequest.onAuthRequired in MV3

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#4064]
We need to add documentation for how webRequest.onAuthRequired works in MV3.

The short version for this is that MV3 extensions can request the `webRequestAuthProvider` permission in their manifest.  If they have this permission, the extension can register a blocking or asyncBlocking listener for the onAuthRequired event (but may still not register blocking listeners for any other event).  Policy-installed extensions can already request webRequestBlocking, so do not need to request this additional permission.

This permission does not have an associated permission warning, so adding it to the manifest will not disable the extension on users' machines.

As with the rest of the webRequest API, whether an extension is allowed to intercept a given call is determined by the extension's granted host permissions.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311464492
