### ISSUE TITLE
Provide extension docs on the CSP manifest field

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#4068]
Currently:
* developer.chrome.com/extensions/contentSecurityPolicy redirects to https://developer.chrome.com/docs/apps/contentSecurityPolicy/, which documents the CSP for chrome apps (deprecated).
* Navigating to the field via the manifest in https://developer.chrome.com/docs/extensions/mv3/manifest/ navigates to https://developer.chrome.com/docs/extensions/mv3/mv3-migration/#content-security-policy, which describes the migration path.

We should have a separate doc for the CSP applied to (MV3) extensions, and have that be the default from developer.chrome.com/extensions/contentSecurityPolicy (and /extensions/content_security_policy, etc).

**Comment by AmySteam** [comment]
@rdcronin Here's a related PR [#3837](https://github.com/GoogleChrome/developer.chrome.com/pull/3837)

**Comment by dstmarthe** [comment]
Moved this to the new issue tracker here: https://issuetracker.google.com/issues/311462701
