### ISSUE TITLE
Table of contents does not break for Russian language

### ISSUE THREAD

**Issue by solarrust** [GoogleChrome/developer.chrome.com#4071]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
In Russian version of devtools 104 blog post the aside is too big!
I think that because the titles are long. Some CSS fixes needs.

Link: https://developer.chrome.com/ru/blog/new-in-devtools-104/
Screen: 1440px
Browser: Safari 16.1
Hardware: MacBook M1 Pro

**To Reproduce**
1. Go to https://developer.chrome.com/ru/blog/new-in-devtools-104/
1. See error

**Expected behavior**
I see two of three possible fixes:
1. Limit the width of aside and give to titles `nowrap`. Then the end of titles will be under the horizontal scroll. Not the best/
2. Give `text-overflow: ellipsis;` to the titles. Looks good, but can make some difficulties with Ctrl + F search through the page.
3. Limit the width and allow titles to wrap to the next line.

**Screenshots**

<img width="1512" alt="CleanShot 2022-10-20 at 13 08 32@2x" src="https://user-images.githubusercontent.com/13676514/196913130-a36393bd-58c8-448d-b365-5de8d85f3ff0.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0
 - Browser Safari 
 - Version 16.1

**Additional context**

**Comment by tokyodanj** [comment]
@Truemedia I'd recommend option 2 - giving the TOC a max-width with `text-overflow: ellipsis;`. The single lines with equal spacing will make it much easier to scan, and the full titles still existing on the page itself so Ctrl + F search won't be an issue.

Wrapping (option 3) would also work, but you'd end up with three or four lines for some of those titles, making the TOC very long and potentially difficult to read at a glance.
