### ISSUE TITLE
Input methods no longer work

### ISSUE THREAD

**Issue by dheera** [GoogleChrome/developer.chrome.com#4077]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

Yes, I know, the problem is the bug happens ONLY in Chrome and not Chromium. I have both browsers open side by side, one has IME working, the other doesn't.

**Describe the bug**
Upgraded to 106.0.5249.119 on Ubuntu 22.04.
Input methods no longer work. I can switch to e.g. Chinese input using the hotkey, but inputting chracters doesn't work.

It worked in 96.0.4664.110-1.

Apologies for reporting the bug here, but I don't see any other bug report or support channels on google.com/chrome/

**To Reproduce**
1. Install Ubuntu 22.04 and Chinese input (via IBus)
2. Install Chrome 96.0.4664.110-1
3. Verify Chinese input works.
4. Upgrade to Chrome 106.0.5249.119
5. Chinese input does NOT work

**Expected behavior**
That upgrading Chrome to 106 should not break my input method.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Browser [Chrome]
 -  - Version [106.0.5249.119]

**Smartphone (please complete the following information):**
 No

**Additional context**

**Comment by matthiasrohmer** [comment]
Unfortunately we can only offer support for the https://developer.chrome.com/ site here, not Chromium itself.
Please file this bug with Chromium at https://crbug.com/.
