### ISSUE TITLE
Move webRequest.onAuthRequired and webRequest service worker issue to a new section for "fixed, not yet on stable" in MV3 known issues page

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#4085]
webRequest.onAuthRequired is supported in MV3 (see related issue #4064 ) and the bug for service workers not being started for webRequest events ([crbug.com/1024211](https://crbug.com/1024211)) is also fixed.  We should move each of these to a new section on the known issues page.

**Comment by rdcronin** [comment]
After discussing with @dotproto , he flagged that we currently say that the issues "will be removed from this page at roughly the same time the change lands in Chrome's Stable channel".  We discussed, and think a good plan here would be to add a new section for items that are fixed, but not yet on Stable (in order to better convey the amount of items that we're still working on, compared to those that are addressed but just not fully rolled out).

**Comment by jpmedley** [comment]
When will this be on stable?

**Comment by tfinlay** [comment]
I believe that the webRequests fix is now in stable as of release 107:
- https://chromiumdash.appspot.com/commit/4473d3c4a8548c8f027e5e66369b896cf261318a
- https://bugs.chromium.org/p/chromium/issues/detail?id=1024211#c86

I assume that the way forward is to remove the webRequest bug notice entirely, or perhaps mark it as "resolved in 107" if we want to wait until 107 becomes the dominant version?

**Comment by jpmedley** [comment]
Almost everything else [on that page](https://developer.chrome.com/docs/extensions/mv3/known-issues/) has an estimated release date of Canary in October 2022. That's clearly not true anymore. Who can tell me what the new estimates are?

**Comment by jpmedley** [comment]
I should have stated yesterday, that as long as I'm updating this item, I need to change all the references to Canary in October 2022. Who would know that information?

**Comment by dotproto** [comment]
@jpmedley, this came up in a meeting so I quickly threw together an initial PR.
