### ISSUE TITLE
Content feedback(extensions):  `manifest.json` code snippets contain trailling commas

### ISSUE THREAD

**Issue by Ngoakor12** [GoogleChrome/developer.chrome.com#4086]
I've been going through the browser extensions tutorials and the `manifest.json` code snippets in:
- [Reading time](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-reading-time/)
- [Tabs manager](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-tabs-manager/)

contain trailling commas.

I realised this while copying and pasting and my current vscode setup removes everything on save. It's not a huge problem but it wouldn't hurt to modify the content in the file to be as accurate as possible, just in case people's editors are not setup the way mine is

Please assign me, I'm down to open a PR for the issue if you believe it's worth addressing

**Comment by AmySteam** [comment]
@Ngoakor12 Thanks! 👍  Feel free to open a PR for this.

**Comment by oliverdunk** [comment]
There are still some instances of this in https://developer.chrome.com/docs/extensions/get-started/tutorial/popup-tabs-manager.

**Comment by jpmedley** [comment]
Our new publishing platform allows copying code samples with a single click. We need to start considering how much editing readers need to do  after pasting our samples.

**Comment by dstmarthe** [comment]
I've moved this issue to the new tracker here: 

https://issuetracker.google.com/issues/324331441
