### ISSUE TITLE
migrating to service workers page: links gets 404

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/developer.chrome.com#41]
Affected page:
https://developer.chrome.com/docs/extensions/mv2/migrating_to_service_workers/

What's going wrong?:
The following URLs on the page linked from the article give 404 on access.

- https://developer.chrome.com/migrating_to_manifest_v3/
- https://developer.chrome.com/docs/extensions/events/
- https://developer.chrome.com/docs/extensions/workers/

**Comment by Mewel** [comment]
All subpages of https://developer.chrome.com/docs/extensions/mv2/devguide/ have the same problem.

**Comment by dotproto** [comment]
> All subpages of https://developer.chrome.com/docs/extensions/mv2/devguide/ have the same problem.

I'm going to open a new bug for this comment

**Comment by robdodson** [comment]
I believe this should all be fixed now
