### ISSUE TITLE
Getting started mention the extension only works on developer.chrome.com

### ISSUE THREAD

**Issue by ElieDeBrauwer** [GoogleChrome/developer.chrome.com#410]
**Describe the bug**

https://developer.chrome.com/docs/extensions/mv3/getstarted/ mentions on two occasions:

_-> Near the intro_ 

This tutorial will build an extension that allows the user to change the background color of **any page on developer.chrome.com.** It will use many core components to give an introductory demonstration of their relationships.

_-> In the paragraph 'Layer logic'_

The extension **now knows the popup should be available to users on developer.chrome.com** and displays a colored button but needs logic for further user interaction.

The text in ( https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/extensions/mv3/getstarted/index.md  )  should either be rephrased the this extension works on any webpage, or text should be added that it only works on developer.chome.com.

**To Reproduce**
1. Create the extension as proposed in the tutorial 
2. Go to any other website (e.g. google.com)
3. Trigger the extension
4. It is expected that this will only work on developer.chrome.com however it works on any website.

**Comment by dotproto** [comment]
Ah, I see what went wrong. The previous version of the page _did_ only work on developer.chrome.com, but when I updated it I migrated it to use the `activeTab` permission (which allows an extension to run on the current page when the extension is invoked) and forgot to update the page copy.

I'll update this to clearly state that it works on the current page.
