### ISSUE TITLE
108 Beta post typo

### ISSUE THREAD

**Issue by michaelwasserman** [GoogleChrome/developer.chrome.com#4142]
The Chrome 108 beta blog post's [Deprecations and removals](https://developer.chrome.com/blog/chrome-108-beta/#deprecations-and-removals) says "This release of Chrome deprecates one feature.", then lists 5 entries, and [the first one](https://developer.chrome.com/blog/chrome-108-beta/#deprecate-and-remove-windowdefaultstatus-and-windowdefaultstatus) says "This release of Chrome removes four features.".

**Comment by rachelandrew** [comment]
That seems correct, there is one deprecated feature under the sentence "deprecates one feature" and four features removed, under the sentence "removes four features". I'm about to push a tidy of heading levels and have added separate deprecation and removal headings which hopefully makes it clearer.
