### ISSUE TITLE
108 Beta post - Missing new JavaScript features

### ISSUE THREAD

**Issue by andylima** [GoogleChrome/developer.chrome.com#4145]
The [Chrome 108 Beta blog post](https://developer.chrome.com/blog/chrome-108-beta/) is missing what's new in JavaScript like Array grouping.

**Comment by rachelandrew** [comment]
Features are only included if they appear on the Chrome Status roadmap: https://chromestatus.com/roadmap please file an issue there if you think these features should be included.

**Comment by rachelandrew** [comment]
Closing as the reason these aren't in the post is that they aren't in the data used to create the post.
