### ISSUE TITLE
[BUG] Focus-Mode tutorial has broken code

### ISSUE THREAD

**Issue by sunipan** [GoogleChrome/developer.chrome.com#4152]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Focus-mode tutorial code has errors and needs parameter fixes and function changes in ***Step 4***

**To Reproduce**
1. Go to the [Focus-Mode tutorial](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/)
2. Scroll down to [Step 4](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/#step-4)
3. Notice in the initial if statement, inside the `.startsWith()` function that `extensions` and `webstore` are used as variables here (which are undefined) when analyzing the current tab URL which is a string.
4. Using `.startsWith()` will always return false since the url property of the `tab` object is full length (i.e. https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/) therefore the extension won't run the logic.

**Expected behavior**
1. `extensions` and `webstore` should be surrounded by quotes to make them strings for comparison with the URL.
2. Replace `.startsWith(extensions)` and `.startsWith(webstore)` with `.includes("extensions")` and `includes("webstore")`

**Screenshots**
![image](https://user-images.githubusercontent.com/62723323/198848760-f9d13e94-4aa0-424f-b73c-6516765568f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave

**Comment by AmySteam** [comment]
@sunipan Thanks for letting us know! 👍 🙂  We just merged a fix ([PR#3993](https://github.com/GoogleChrome/developer.chrome.com/pull/3993))
