### ISSUE TITLE
I found a spelling mistake in the UI page Where the word "acceppts"  instead of "accepts" Below the warning

### ISSUE THREAD

**Issue by ValanGracious** [GoogleChrome/developer.chrome.com#4162]
![bug](https://user-images.githubusercontent.com/111484772/199205574-9690ac34-2f26-48f0-a152-f90882ec6d84.png)

**Comment by AmySteam** [comment]
@ValanGracious Thanks for the heads up! 👍  Just pushed a fix for this [PR#4167](https://github.com/GoogleChrome/developer.chrome.com/pull/4167)
