### ISSUE TITLE
Feedback: Uniquely identifying PWAs with the web app manifest id property

### ISSUE THREAD

**Issue by alancutter** [GoogleChrome/developer.chrome.com#4177]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Corrections needed for article: https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/blog/pwa-manifest-id/index.md
- https://developer.chrome.com/blog/pwa-manifest-id/#determine-id
  - DevTools no longer shows the (!) icon, instead it has a **Note:**, screenshot needs updating.
  - Setting the id should only be done once, it's unsafe to set it to anything other than the first start_url. Developers may change their start_url then follow these steps which would be incorrect and fragment their install base.
- https://developer.chrome.com/blog/pwa-manifest-id/#how-do-i-test-this-today
  - We should not direct site developers to go to about://web-app-internals/, this page is intended for Chrome developers and bug reports.
    The site developer can see the Computed App Id in DevTools.
  - Step 6 is incorrect, the manifest_id should have changed at this point.
  - After step 9 the site developer should be checking that the computed app id hasn't changed from before they updated their start_url.
- https://developer.chrome.com/blog/pwa-manifest-id/#additional-resources
  - Update the link to the editor's draft to the real spec:
https://www.w3.org/TR/appmanifest/#id-member

Recommendations:
- Add a section or warning box called "Never change your app ID". It should explain that once you have set an ID, you should not change it, and if you have not set an ID, it should be set to the first published value of start_url before any changes are made to it. If it ever changes then a cohort of users will cease receiving manifest updates.
- https://developer.chrome.com/blog/pwa-manifest-id/#determine-id
  - Add step at the end to check DevTools that the computed app id is still set to the previous value and the "note: id is not specified" is gone.
- Add a section called "How do I change my start_url?" explaining how to do this safely:
  - Ensure manifest id is set.
  - Update start_url.
  - Verify computed app id hasn't changed and start_url has changed.
- Remove the "How do I test this today" section as it's covered by the previous section suggestions.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’ve moved to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324331428
