### ISSUE TITLE
cisco

### ISSUE THREAD

**Issue by mitchfeinberg** [GoogleChrome/developer.chrome.com#418]
background images from cell phone tower 

![Screenshot_20210210-183448](https://user-images.githubusercontent.com/2412336/107642909-7bc44100-6c43-11eb-98c5-14b042152977.png)
![Screenshot_20210211-073340](https://user-images.githubusercontent.com/2412336/107642952-87b00300-6c43-11eb-8ee4-c92476b9045f.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robdodson** [comment]
@mitchfeinberg if you'd like to file a browser bug you can do so at crbug.com
