### ISSUE TITLE
Export group (tabs) and fully sync tabs across devices

### ISSUE THREAD

**Issue by XinyueZ** [GoogleChrome/developer.chrome.com#4183]
I hope that one day we can. 😝

1. Export groups like bookmarks.
2. In the flag section we can toggle "save group" (experimental feature). Hopefully that the saved groups can be synced across devices.

**Comment by matthiasrohmer** [comment]
Unfortunately this issue tracker is only for issues and request related to the site developer.chrome.com, not for feature requests for Chrome as a product. 🙂

**Comment by XinyueZ** [comment]
where can I go now ? @matthiasrohmer

**Comment by matthiasrohmer** [comment]
@XinyueZ, you can go to the [Chromium Google Group](https://groups.google.com/a/chromium.org/g/chromium-discuss) and further discuss your idea there. If you feel something that is already there is not working as intended you can go to the [Chromium Bug Tracker](https://bugs.chromium.org/p/chromium/issues/list) and raise an issue there.
