### ISSUE TITLE
TOC for supernested docs

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/developer.chrome.com#4195]
**Is your feature request related to a problem? Please describe.**
The FLEDGE API now has substantial documentation which needs to live on DCC (and not MDN). These docs will be merged in https://github.com/GoogleChrome/developer.chrome.com/pull/4172

The growing list of API references are exposed in a section at the bottom of the article, rather than in the side navigation.

![All FLEDGE API references](https://user-images.githubusercontent.com/2766281/199742173-0064fbe9-85f4-43e2-80b5-e2e0956954b4.png)

The side navigation already has three levels of docs, and these would fit in a fourth level of nesting. I believe that would be a bad user experience, and look messy.

#### Current navigation
![Privacy Sandbox nested navigation](https://user-images.githubusercontent.com/2766281/199741625-7e8f7af4-a251-4ec3-87e0-5204946147ba.png)

1. **CMA commitment and Privacy Sandbox use case**.
  1. Proposal overview (in the proposal stage, no additional docs needed.
  2. **Description of an API use case**
    1. Proposal overview (in the experiment phase)
    2. Developer API guide
    3. Experiment & participate
    4. Updates
  3. **Description of an API use case**
    1. Proposal overview (in the experiment phase)
    2. Developer API guide
    3. Experiment & participate
    4. Updates

**Describe the solution you'd like**
The current navigation suffices for all of the top level docs. In practice, the full navigation structure works as follows.

1. **CMA commitment and Privacy Sandbox use case**.
   1. Proposal overview (in the proposal stage, no additional docs needed.
   2. **Description of an API use case**
      1. Proposal overview (in the experiment phase)
      2. Developer API guide
          1. API method 1
          2. API method 2
          3. [...]
          4. API method x
      3. Experiment & participate
      4. Updates
   3. **Description of an API use case**
      1. Proposal overview (in the experiment phase)
      2. Developer API guide
      3. Experiment & participate
      4. Updates

When we get to a Developer API guide, it would be terrific if sidebar TOC could shift to focus on the second, third and fourth level. 
If you're looking at an API method for FLEDGE, you don't currently need to care about an API method for a different use case or even a different CMA commitment.

1. **Description of an API use case**
   1. Proposal overview (in the experiment phase)
   2. Developer API guide
      1. API method 1
      2. API method 2
      3. [...]
      4. API method x
   3. Experiment & participate
   4. Updates

**Comment by matthiasrohmer** [comment]
Thanks for the work on this, @tokyodanj! Looking forward to a quick walkthrough on call with @devnook and me on 12/7 🙂

**Comment by heyawhite** [comment]
!!!!

@samdutton @rowan-m FYI

**Comment by tokyodanj** [comment]
Page design approved. Ready for implementation.

**Comment by mollietokyo** [comment]
**Remaining dev estimate** - 1 day

**Comment by mollietokyo** [comment]
Estimate for dev = 1 day (SPR-3)

**Comment by heyawhite** [comment]
Hey folks, looks like the style is now affected on the main landing page for the documentation. The nested nav is inheriting the style of a single article, and nesting isn't reflected on this main page.
![image](https://user-images.githubusercontent.com/2766281/221211686-fc6919db-f615-4bbd-96dc-11487fa634ed.png)

**Comment by matthiasrohmer** [comment]
Regression on the overview pages fixed, thanks to @heyawhite!
