### ISSUE TITLE
Cannot specify setSelfAsOpener Service Worker extension.

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#4200]
**Describe the bug**
Documentation does not disclose `setSelfAsOpener` https://developer.chrome.com/docs/extensions/reference/windows/#property-create-createData-setSelfAsOpener set to `true` throws in MV3 by default
```
Cannot specify setSelfAsOpener Service Worker extension.
```
**To Reproduce**

```

  ({ id } = await chrome.windows.create({
    type: 'popup',
    url,
    setSelfAsOpener: true
  }));
```

**Expected behavior**
A clear and concise description of what you expected to happen when the above is executed `ServiceWorker` extension.

**Additional context**

**Comment by jpmedley** [comment]
@guest271314, the actual problem is that the windows interface can't be accessed from a service worker. We'll get this noted in the help. Have you found a workaround, or can I help you with that?

**Comment by guest271314** [comment]
Well, the `window` interface _can_ be accessed from a `ServiceWorker`, the `WindowClient` interface. The problem is nobody has spelled out a way to set arbitrary Web sites as a `WindowClient`, which would solve a great number of issues, including https://github.com/GoogleChrome/chrome-extensions-samples/issues/766.

We have `"externally_connectable"` already, however, we cannot _transfer_ transferables using that API.

We have to create an `iframe` with `src` set to a chrome-extension: URL and use `"web_accessible_resources"` to establish communication between the MV3 `ServiceWorker` and the `iframe` and from the `iframe` to the Web page. 

As pointed out by @tophf, that `iframe` can be removed by the Web page, and/or other extensions.

- `"externally_connectable"` _can_ be modified to establish a direct communication channel with the `ServiceWorker`, similar to how `AudioWorkletProcessor` constructor creates a `MessagePort` for direct communication with the main thread; that means using a `MessageChannel`, which provides a means to actually transfer data, not JSON serialized data only.
- Since we are dealing with extensions here, `WindowClient` _can_ be set by the extension, in fact, using the same process as now, just defined in manifest.json, listing the sites which will be set to `WindowClient` of the MV3 extension `ServiceWorker`.

Right now the process is too fragile. And we, developers in the field, should not be in the laboratory trying to come up with **_workarounds_** for _extensions_.

The above is just the gist of the subject matter that lead to me filing this.

I am actually considering filing feature requests for the above two list items. I just don't want to file them only to have some moderator say this or that venue is not the place to file the feature requests, kicking the can down the raod.

You asked, so I will not be overly verbose here. You should get the gist of the issue above. If you do not, do not hesitate to ask for specific clarification.

**Comment by guest271314** [comment]
@jpmedley It looks like `setSelfAsOpener` is obsolete in MV3.

`chrome.windows` is not exposed in content scripts. The error  

```
Cannot specify setSelfAsOpener Service Worker extension.
```

is thrown when calling `chrome.windows.create()` with `setSelfAsOpener` set.

**Comment by jpmedley** [comment]
Sorry about the window thing. I'm a bit new to extensions. We'll get the docs updated to reflect that `selfAsOpener` is not available in MV3.

**Comment by guest271314** [comment]
Can you simultaneous notify whoever in Google Chrome/Chromium who owns the blame so they at least have the opportunity to update the source code so we can set whatever we want to `opener`?

**Comment by guest271314** [comment]
@jpmedley Note, there is also no way to set `opener` for a `Window`  `chrome.offscreen.createDocument()`.

**Comment by dstmarthe** [comment]
I've moved this issue here: https://issuetracker.google.com/issues/324481608
