### ISSUE TITLE
chrome.action.isEnabled  is not a function

### ISSUE THREAD

**Issue by Arce0406** [GoogleChrome/developer.chrome.com#4211]
**Describe the bug**
Here is the method：[https://developer.chrome.com/docs/extensions/reference/action/#method-isEnabled](https://developer.chrome.com/docs/extensions/reference/action/#method-isEnabled)

Although has list on docs, but it seems no support.

**Comment by oliverdunk** [comment]
This method is supported. If you're not seeing it, perhaps you hadn't yet registered an `action` in the manifest?
