### ISSUE TITLE
launch multiple taps - not working

### ISSUE THREAD

**Issue by adrianpfeiffer** [GoogleChrome/developer.chrome.com#4212]
**Describe the bug**
Chrome extension doesn't launch multiple websites on tap, just one (the first one). 

F.e. I am looking for free stock pics of "cars". I open multiple pages (unsplash, pexels, etc.) and search for "cars". In my chrome extension, I only type in "cars" once, click on search and it opens pre-defined pages already searching for "cars". 

When I run the app in test mode, it totally works. But when installed and used as chrome extension, it only opens the first pre-defined website (and not the other pre-defined ones).

**To Reproduce**
share the package if needed... 

**Expected behavior**
It should totally open all pre-defined websites in chrome taps. 

**Screenshots**
Added two videos: 
1. Run-mode, where it works
https://user-images.githubusercontent.com/50270471/200134271-5abac279-8e94-4728-be46-7c4831f8de4c.mov

2. using the chrome extension -> not working 

https://user-images.githubusercontent.com/50270471/200280131-07da7ae4-5391-450a-9287-0a55d86c41b6.mov

**Additional context**
Extention was built with FlutterFlow: https://www.youtube.com/watch?v=NH52jzJg7SY

I think chrome is naturally preventing "spam". Like a

utomatically open multiple taps.

.. Is there a workaround?

**Comment by guest271314** [comment]
The videos show multiple tabs opening. What is not working?

**Comment by adrianpfeiffer** [comment]
@guest271314 thanks for your response!!! 

I uploaded two videos: The first one (which I think you mean) is in run-mode working -> opening multiple tabs. 
The second one is where I use the chrome extension and it only opens one tab.

**Comment by guest271314** [comment]
I am sure I tested your claim after watching the videos and opened multiple tabs using extension code.

**Comment by adrianpfeiffer** [comment]
@guest271314 how could you have tested it without having the code? Do you mean with a different extension?

**Comment by dstmarthe** [comment]
Hey Adrian, thanks for raising this. I know it's been a while but this repo is for issue with d.c.c content specifically. I recommend you raise this issue at https://groups.google.com/a/chromium.org/g/chromium-extensions

Or see the other resources we recommend: https://developer.chrome.com/docs/extensions/support-feedback/getHelp/#for-extensions-development
