### ISSUE TITLE
[eng] Rendering issue in Korean, Russian and Chinese page 

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#4249]
Probably related to changes in #3692 .

1. Go to an English, Spanish, Japanese or Portuguese content page, for example: https://developer.chrome.com/es/blog/new-in-devtools-107/ on laptop. The page rendered nicely with table of content on the side, bottom list of previous version and footer menu.
2. Open a Korean, Russian or Chinese page, for example: https://developer.chrome.com/ru/blog/new-in-devtools-107/. Missing table of content on the side, bottom list of previous version and footer menu.

**Comment by matthiasrohmer** [comment]
That's very interesting, especially as it's working for ES, which I used to test partials. Thanks for reporting, will look into this!

**Comment by matthiasrohmer** [comment]
The culprit seems to be somewhere in the what's new partial. At least when debugging the Russian language - disabling that one renders the page fine. Further investigating...

**Comment by matthiasrohmer** [comment]
Further tracked it down to be related to HTML comments and whitespace. The English page renders correctly, but the Spanish version is also missing versions down to Chrome 96, with the last closing comment tag being in Chrome 96:

https://github.com/GoogleChrome/developer.chrome.com/blame/main/site/es/_partials/devtools/whats-new.md#L160
