### ISSUE TITLE
chrome.scripting.registerContentScript is not a function

### ISSUE THREAD

**Issue by Patrickctyyx** [GoogleChrome/developer.chrome.com#4263]
**Describe the bug**
The `chrome.scripting.registerContentScript` shown in [doc](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#programmatic) is not a function. 
Maybe `chrome.scripting.registerContentScripts` instead? According to [scripting api](https://developer.chrome.com/docs/extensions/reference/scripting/#method-registerContentScripts).

**To Reproduce**
```
chrome.scripting.registerContentScript({
  id: 1,
  matches: ["https://*.nytimes.com/*"],
  exclude_matches: ["*://*/*business*"],
  js: ["contentScript.js"]
});
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18365594/201254079-4e440a77-966b-4e67-8e39-fcfbae8c8cda.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser Chrome
 - Version 107.0.5304.110 (arm64)

**Comment by Patrickctyyx** [comment]
Besides, [`run_at`](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#run_time) should be `runAt` according to [scripting api](https://developer.chrome.com/docs/extensions/reference/scripting/#type-RegisteredContentScript).

**Comment by dstmarthe** [comment]
Thanks for raising this issue. We’re moving to a new platform and it looks like the runAt part still needs to be changed. I’ve moved the issue to our new tracker and you can see it at  https://issuetracker.google.com/issues/312577071
