### ISSUE TITLE
Improve translation workflow for landing pages

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#4268]
The work for https://github.com/GoogleChrome/developer.chrome.com/issues/2639 improved landing pages as links/articles that haven't been translated yet also show up, linking to the original (English) version of the page.

Still, translating landing pages requires manual effort of keeping up with changes to the English template and syncing that to the translated template like in https://github.com/GoogleChrome/developer.chrome.com/pull/4267.

Maybe we find a solution that cascades the translated page with the original one, merging in potentially missing sections...?

**Comment by mollietokyo** [comment]
**Estimate** - 3.5 days

**Comment by mic4aelx504** [comment]
- [ ]

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
