### ISSUE TITLE
The download links for Native Messsaging Examples don't work

### ISSUE THREAD

**Issue by jdv85** [GoogleChrome/developer.chrome.com#428]
**Describe the bug**
The "Examples" section on [Native Messaging](https://developer.chrome.com/docs/apps/nativeMessaging/#examples) has links for downloading a sample app and a sample host. Unfortunately, none of the download links work.

**To Reproduce**
1. Go to [Examples](https://developer.chrome.com/docs/apps/nativeMessaging/#examples)
2. Click on [sample app](https://developer.chrome.com/extensions/examples/api/nativeMessaging/app.zip)
3. You now get a zero byte file

**Expected behavior**
A proper ZIP file should be downloaded.

**Comment by oliverdunk** [comment]
Closing this as the examples section no longer exists.
