### ISSUE TITLE
Document how dNR replaces webRequestBlocking in MV2

### ISSUE THREAD

**Issue by Hames0024** [GoogleChrome/developer.chrome.com#4286]
Hi,
"webRequestBlocking" is supported in manifest v3?
How can I declare it on "manifest.json"

**Comment by jpmedley** [comment]
In V3, blocking web requests are placed with [declarative net requests](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/#modifying-network-requests). I know the documents are less than perfect, but we're working on them. In the meantime, feel free to send me questions. They'll help me with the improvement work. You can contact me through [my GitHub profile](https://github.com/jpmedley).

**Comment by Hames0024** [comment]
Thank you, Can you send me declarative net request example code?
Add, update and remove rule...

I want to learn more from you.

Are you using telegram?
I want to meet you on telegram. My id @S_Halli

**Comment by Hames0024** [comment]
Is it possible modify post requestbody by using declarativeNetRequests?
WebRequestBlocking is alived in several Extensions like "Tamper Extension".
Do you know what their plan?

**Comment by jpmedley** [comment]
I don't use Telegram. I'd prefer you contact me through email. My address is on my GitHub profile. 

It is not possible to modify requestbody using declarativeNetRequest. Can you tell me more about your use case? There might be another way to solve your problem.

I don't know the upgrade timelines for any specific extension. If a particular extension still uses webRequestBlocking, it's still on V2. Developer have until January 2024 to upgrade according to [our timeline](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/).

**Comment by jpmedley** [comment]
@IanStanion-google, can you please add a reference to the PR where you fixed this?

**Comment by AmySteam** [comment]
Fixed in #5473
