### ISSUE TITLE
Extended screen coordinate system problem

### ISSUE THREAD

**Issue by guoyanfeng** [GoogleChrome/developer.chrome.com#4287]
The chromebook has an extended screen, and the coordinate system of the two screens is continuous on Android 9，But on android 11 the coordinate system of both screens starts from 0, 0。Is this the way it is designed, is there any documentation to see this change? Can you help me reply, because we are developing multi-screen operation, there will be the problem of mouse sliding between two screens. My email is 349596624@qq.com

**Comment by Eikyarkway** [comment]
labels

**Comment by devnook** [comment]
This is not related to developers.chrome.com website. Please consider raising an issue with http://crbug.com instead
