### ISSUE TITLE
Reprovisioned device empty ID chrome.enterprise.deviceAttributes.getDirectoryDeviceId()

### ISSUE THREAD

**Issue by august-at-goguardian** [GoogleChrome/developer.chrome.com#43]
We have a lot of used chromebooks that was enrolled previously. We enrolled it again and it is now a managed device in Google Admin Console. However, when using the API chrome.enterprise.deviceAttributes.getDirectoryDeviceId(), that function returns empty. Not sure why it only happens with previously enrolled chromebooks.

**Comment by samthor** [comment]
It seems like [the method](https://developer.chrome.com/docs/extensions/reference/enterprise_deviceAttributes/#method-getDirectoryDeviceId) returns empty in a bunch of cases.

Unfortunately this isn't the right forum to help you. I think maybe you want e.g. an [Enterprise help community](https://support.google.com/chrome/a/community?hl=en).
