### ISSUE TITLE
DCC site search for messaging returns results for deprecated or defunct products

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4301]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Searching for 'messaging` on dcc returns links to pages about Native Client or Apps instead of the [expected page for extension message passing](https://developer.chrome.com/docs/extensions/mv3/messaging/).

![image](https://user-images.githubusercontent.com/8204171/201746058-a8af1d15-4fed-4099-8bb9-38ad348c4faa.png)

**Comment by matthiasrohmer** [comment]
Related to https://github.com/GoogleChrome/developer.chrome.com/issues/81, which asks for better results weighting.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS with completely different Search that we can likely not influence anyway..
