### ISSUE TITLE
Chrome Webstore API Guide needs to be updated for new Developer Console UI

### ISSUE THREAD

**Issue by jackmac92** [GoogleChrome/developer.chrome.com#431]
**Describe the bug**
I followed the guide in the past with success a few years ago, but I can't figure it out with the new UI.

Specifically steps 7-8 I think need to be updated
```
7) Find the lines labeled Client ID and Client secret. Note that there may be a client ID without a client secret for use with Compute Engine and App Engine. In that case, create a new client ID and client secret.
8) To create the client ID and client secret, click on Create New Client ID, select Installed Application, and Other under Installed application type.
```

For 7 I don't see the "lines labeled Client ID and Client secret", but tried creating an "Oauth client ID" view "CREATE CREDENTIALS +" at the top

For 8, the suggested options are no longer available

**Comment by anikmrrito** [comment]
> yhcbb

>

**Comment by blimmer** [comment]
We just played around with this, and it appears that "Installed Application" now maps to "Desktop Application".
