### ISSUE TITLE
Update chrome.commands documentation on _execute_action

### ISSUE THREAD

**Issue by oliverdunk** [GoogleChrome/developer.chrome.com#4311]
In the [chrome.commands](https://developer.chrome.com/docs/extensions/reference/commands/#verify-commands-registered) documentation, a comment mentions that `_execute_action` is not returned from `commands.getAll()`:

<img width="723" alt="Screenshot 2022-11-15 at 18 07 51" src="https://user-images.githubusercontent.com/6097064/201993876-38d0a25d-808d-4654-a2f9-a97073e0685d.png">

I was able to fix this as part of https://crbug.com/1375790 in https://chromium.googlesource.com/chromium/src/+/4464f977da2eb9e8e1e0eb9775d71d20e845eb52. This means that the comment is no longer accurate from Chrome 110 (currently in Canary).

There were two suggestions made in the [comments](https://chromium-review.googlesource.com/c/chromium/src/+/4020384/comments/359f20ac_cb460ec4) of that review:

- The callout should be updated and eventually removed.
- It may make sense to include this on https://developer.chrome.com/docs/extensions/whatsnew/.

I could also see an argument for adding it to https://developer.chrome.com/docs/extensions/mv3/known-issues/.

**Comment by dotproto** [comment]
I agree that we should add this to the [what's new page](https://developer.chrome.com/docs/extensions/whatsnew/). I think it's out of scope for the [Known Issues](https://developer.chrome.com/docs/extensions/mv3/known-issues/) page, as that tracks issues blocking migration to Manifest V3. 

That means we currently have two work items associated with this issue:

- [ ] Update Commands API docs to reflect that `_execut_action` is returned by `commands.getAll()`
- [ ] Note this platform change on the What's New page

**Comment by jpmedley** [comment]
The [`getAll()` entry](https://developer.chrome.com/docs/extensions/reference/commands/#method-getAll) should state that `_execute_action` isn't returne before 110. Is there a standard way to indicate this in the generated reference?
