### ISSUE TITLE
Redirects for old reference documentation missing 

### ISSUE THREAD

**Issue by eps1lon** [GoogleChrome/developer.chrome.com#4338]
**Describe the bug**
https://developer.chrome.com/docs/extensions/storage.html returns 404 ([was previously available](https://web.archive.org/web/20220000000000*/https://developer.chrome.com/docs/extensions/storage.html))

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/storage.html
4. See 404

**Expected behavior**
Redirects to new page. Would https://developer.chrome.com/docs/extensions/reference/storage/ work?

**Additional context**

Linked from https://stackoverflow.com/a/21066312/3406963 originally (now fixed)

**Comment by jpmedley** [comment]
@eps1lon, thank you for letting us know. I did some poking in our commit history. I'm convinced this is merely a typo in the StackOverflow answer. The SO link has been fixed so I don't see a reason to set up a redirect.
