### ISSUE TITLE
Migrate the DevTools docs

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/developer.chrome.com#434]
- [ ] Make sure that migrated docs are transferred faithfully
- [ ] Make sure that deprecated docs are redirected
- [ ] Rationalize the directory structure of the new docs
- [ ] Verify that all links in the new docs work
- [x] Replace `TL;DR` with `Summary` in the new docs
- [ ] Update the old redirects in `redirects.yaml`
- [ ] Redirect /web traffic to DCC
- [ ] Run script on /web to make sure all redirects are set up correctly

**Comment by SyfiMeal** [comment]
> * [ ]  Make sure that migrated docs are transferred faithfully
> * [ ]  Make sure that deprecated docs are redirected
> * [ ]  Rationalize the directory structure of the new docs
> * [ ]  Verify that all links in the new docs work
> * [x]  Replace `TL;DR` with `Summary` in the new docs
> * [ ]  Update the old redirects in `redirects.yaml`
> * [ ]  Redirect /web traffic to DCC
> * [ ]  Run script on /web to make sure all redirects are set up correctly
