### ISSUE TITLE
Optional shortcut to include/exclude 'shadow root' elements when using 'select element in this page'

### ISSUE THREAD

**Issue by gomarcus** [GoogleChrome/developer.chrome.com#4347]
Optional shortcut (e.g. pressed Shift) to include/exclude 'shadow root' elements when using 'select element in this page' chromium tool, to select the closest non shadowroot element. + adding it to the shortcut list on developer.chrome.com/docs/devtools/shortcuts/ :D

PS: sorry to post it here. don't have google user account so can't post it on chromium site.

**Comment by matthiasrohmer** [comment]
Sorry, feature requests towards Chromium need to be raised in https://bugs.chromium.org/p/chromium/issues/list.
