### ISSUE TITLE
Design: Redesign /fugu-showcase page on web.dev

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#4362]
Provide a design for a gallery-style page like fugu-showcase:

Original webpage: https://googlechromelabs.github.io/fugu-showcase/data/

Inlined iframe: https://developer.chrome.com/blog/fugu-showcase/

Preview URL: https://deploy-preview-2887--developer-chrome-com.netlify.app/fugu-showcase

**Comment by devnook** [comment]
Related filters design: https://github.com/GoogleChrome/developer.chrome.com/pull/4232

**Comment by matthiasrohmer** [comment]
Done by Dan, walkthrough on call on 12/7.

**Comment by tokyodanj** [comment]
Page design and hero illustration approved. Ready for implementation.

**Comment by devnook** [comment]
Design delivered in figma and implemented in this PR: https://github.com/GoogleChrome/developer.chrome.com/pull/4818

The PR will get merged when real data is available for integration.
