### ISSUE TITLE
Support specifying <title> via frontmatter

### ISSUE THREAD

**Issue by sebastianbenz** [GoogleChrome/developer.chrome.com#4389]
### Problem

I've noticed that many docs have incomplete `<title>` tags. The problem is that the document title is also used for the `<title>` element. 

For example for Custom Tabs, the page title is "Overview" which is fine given the doc hierarchy, but that's less helpful for the title tag. I've noticed this with titles in SERPs being confusing: 

![7PFyPuTQJ5249oR](https://user-images.githubusercontent.com/380472/203632350-1cee99ac-edf0-4fd3-81f7-d9ec3b977303.png)

On the other end, the CrUX docs avoid this problem by prefixing every title with CrUX. The downside is, that this makes the sidebar unnecessarily noisy:

<img width="426" alt="Screenshot 2022-11-23 at 20 37 45" src="https://user-images.githubusercontent.com/380472/203632679-23b0f692-16ae-41fa-97b9-e91569f7546b.png">

### Proposal

Enable specifying the `title` tag content via an optional frontmatter property `titleTag`. This way document authors can provide a better title tag if the document title is not sufficient. 

### Alternativs considered

1. Include hierarchy in the title tag (`project > parent > doc`), however this does not work well in cases where the document title is already sufficient (e.g. "[What's new in DevTools](https://developer.chrome.com/tags/new-in-devtools/)"). 
2. Specify document title via toc.yml (e.g. https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_data/docs/lighthouse/toc.yml). This makes it possible to provide a different title for the sidebar, but does not solve the problem that document title and title tag need to be different.

Happy to create a PR for this if folks agree that this makes sense.

**Comment by matthiasrohmer** [comment]
I did like the initial proposal of `seoTitle` better, but agree to the general approach.

**Comment by matthiasrohmer** [comment]
@sebastianbenz, briefly synced with @rachelandrew on this and we both like this. Feel free to go ahead with a PR if you have time to, otherwise mention me and we'll add it to the backlog.

It would be good to give this new feature a mention in the handbook then, probably in https://developer.chrome.com/docs/handbook/how-to/add-a-doc/
