### ISSUE TITLE
Web Share Target API hyperlink returns 404

### ISSUE THREAD

**Issue by sdkdeepa** [GoogleChrome/developer.chrome.com#4392]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Failed to load resource: the server responded with a status of 404 ()

**To Reproduce**
1. Go to ['https://developer.chrome.com/articles/file-handling/'](https://developer.chrome.com/articles/file-handling/)
4. 2. Click on "Web Share Target API"
5. See error 404

**Expected behavior**
Navigates to the Web Share Target API page

**Screenshots**
<img width="1448" alt="Screenshot 2022-11-23 at 9 56 22 PM" src="https://user-images.githubusercontent.com/19764585/203706115-e25823fa-796b-4fde-8e40-7c5c8ec585fa.png">

<img width="2448" alt="Screenshot 2022-11-23 at 10 00 00 PM" src="https://user-images.githubusercontent.com/19764585/203708222-9c78df6d-7ad9-4253-8550-d4f0733a48fc.png">

**Desktop (please complete the following information):**
 - OS: Mac mini M1 - OS Ventura
 - Browser - Chrome 
 - Version 107.0.5304.110 (Official Build) (arm64)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro max
 - OS: iOS 16.1.1
 - Browser: safari and chrome (107.0.5304.101)

**Additional context**

**Comment by rachelandrew** [comment]
Thanks @sdkdeepa looks like this link was broken by our recent content move. I've just made a PR to fix it.
