### ISSUE TITLE
Document how MV3 provides a way to supply credentials for auth requests

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4442]
Source material:
* [Issue 1135492](https://bugs.chromium.org/p/chromium/issues/detail?id=1135492)
* [Design doc](https://docs.google.com/document/d/1iNonK6pgl9U5BTELR3iumfOU6TbirmC--a3GkIjUbfc/edit#heading=h.uoiyzkmb4b5l)
* [Code review](https://crrev.com/c/3923277)

**Comment by dotproto** [comment]
This issue was originally raised in [a comment thread](https://github.com/GoogleChrome/developer.chrome.com/pull/4240/files/d4f1b416d1417051af541660ec9c39e55e57ffbf#r1019516681) on PR #4240.
