### ISSUE TITLE
Update terminology in Chrome Web Store Documentation

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4444]
Some interface text in the Chrome Web Store help does *not* match the text used in the Developer Dashboard. For example, the dashboard itself is referred to as the 'developer console'.

The work for this item is to compare each page of the web store help with the dashboard page it describes and change names in the former to conform to what appears in the latter.

**Comment by dstmarthe** [comment]
Issue migrated here: https://issuetracker.google.com/issues/312577074
