### ISSUE TITLE
Snippets Editor inside VSCODE and run code directly

### ISSUE THREAD

**Issue by locdhthtb** [GoogleChrome/developer.chrome.com#4455]
I often code directly the snippet in this tab
run some javascript embed features
Hope someone who will integrate vscode in this module can write commands more easily

Sorry For My Bad English 
I hope everyone can understand my idea

![chrome_2022-11--29__220910](https://user-images.githubusercontent.com/26026818/204566349-7ae0e5b2-4154-4840-a53c-052ef993afe8.png)

**Comment by rachelandrew** [comment]
This repo is for issues with the website at developer.chrome.com, your issue doesn't seem to relate to that site.
