### ISSUE TITLE
Open multiple pages from History page

### ISSUE THREAD

**Issue by Woozyman** [GoogleChrome/developer.chrome.com#447]
**Is your feature request related to a problem? Please describe.**
In the History Page i often need to open multiple older visited pages (about 5-15 pages).
Now I have to right click open all the older links i need one by one and having to jump back and forth in the panes one by one because it openes the pane and it takes focus and therfor hiding the History page.

**Describe the solution you'd like**
In the history page I'm again and again missing an 'Open' or 'Open all' button.
When I have selected multiple history element check-boxes the header only gives me 'x', 'Delete' and 'Cancel' buttons.
Here i would like an 'Open' button so that I can open multiple history elements at once. (See screenshot)

**Describe alternatives you've considered**
That when right clicking and openeing a page i a new pane it won't take focus and i have to shift pane to go back.
the other solution with adding a button instead makes it easyer to see what I am planning to open.

**Screenshots**
![image](https://user-images.githubusercontent.com/11155637/108165568-12d14300-70f3-11eb-88ce-1711229a5989.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.150

**Comment by robdodson** [comment]
Hi @Woozyman, this repo is only for filing bugs against the documentation at developer.chrome.com. If you have a Chrome bug or feature request you can file it at crbug.com
