### ISSUE TITLE
Mv3 Samples landing page

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4487]
Update with list of Mv3 samples or link into the MV3 sampels repo, it's confusing to dump people into the top level

**Comment by Natee9969** [comment]
> อัปเดตด้วยรายการตัวอย่าง Mv3 หรือลิงก์ไปยังที่เก็บตัวอย่าง MV3 ซึ่งทำให้สับสนที่จะถ่ายโอนผู้คนไปยังระดับบนสุด

https://github.com/GoogleChrome/developer.chrome.com/issues/4487#issue-1472070142
