### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by hemingyang** [GoogleChrome/developer.chrome.com#4491]
GoogleChrome  ：Version 108.0.5359.71 (Official Build) (64-bit) 
os ：win11

Open IntelliJ IDEA 2022.1.1 and Google Chrome,  i ma computer stuck   。Is it caused by too many plug-ins？

 [![ioIxa.md.png](https://i.328888.xyz/img/2022/12/02/ioIxa.md.png)](https://imgloc.com/i/ioIxa)

**Comment by AaronForinton** [comment]
Hi there! To get an answer on this question, I'd suggest raising an issue with [Chromium Bugs](https://bugs.chromium.org/p/chromium/issues/list). Thank you.
