### ISSUE TITLE
web app version asymmetry

### ISSUE THREAD

**Issue by Ziyan-Cheng** [GoogleChrome/developer.chrome.com#4492]
**Describe the bug**
when web app was updated, some page will stay at old version≤and som is already at new version.

**Expected behavior**
when deploy success, all web app should be upgrade to new version

 - Device: MacBook pro
 - OS: macOS13.0.1
 - Browser chrome
 - Version 108.0.5359.71 (Official Build) (arm64)

**Comment by AaronForinton** [comment]
Hi there! To get an answer on this question, I'd suggest raising an issue with [Chromium Bugs](https://bugs.chromium.org/p/chromium/issues/list). Thank you.
