### ISSUE TITLE
favicons can't be properly shown with v3

### ISSUE THREAD

**Issue by calidion** [GoogleChrome/developer.chrome.com#4494]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

v3: 
url format = chrome-extension://aglmepmfibmokigfgakpbcimgkkkklia/_favicon/?pageUrl=https%3A%2F%2Fvideo.twimg.com&size=64
![Screenshot from 2022-12-02 20-01-04](https://user-images.githubusercontent.com/131776/205310838-fb197737-b15c-40e1-9f26-793d9f5869e6.png)

v2:
url format = chrome://favicon/size/32@1x/https://google.com/
![Screenshot from 2022-12-02 19-07-30](https://user-images.githubusercontent.com/131776/205311605-e67c1dc5-9660-4b30-9afd-525879ba60a0.png)

but v2 is forbidden to be published.

how should I get the same result from v3?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AaronForinton** [comment]
Hi there! To get an answer on this question, I'd suggest raising an issue with [Chromium Bugs](https://bugs.chromium.org/p/chromium/issues/list). Thank you.

**Comment by calidion** [comment]
It is not a bug of chromium, but the api v3 issue.
