### ISSUE TITLE
Content Scripts: Injecting programmatically: code example incomplete

### ISSUE THREAD

**Issue by NV** [GoogleChrome/developer.chrome.com#4510]
**Describe the bug**
https://developer.chrome.com/docs/extensions/mv3/content_scripts/#programmatic

If I use the code from manifest.json and background.js, it fails with:
> Uncaught TypeError: Cannot read properties of undefined (reading 'onClicked')
chrome.action.onClicked.addListener((tab) => {

That's because manifest.json missing:
```
    "action": {}
```

The 2nd error is 
> Error in event handler: TypeError: Cannot read properties of undefined (reading 'executeScript') at chrome-extension://.../background.js:2:20

Because "scripting" isn't included in the permission.

manifest.json with these 2 issues resolved:
```
{
  "name": "My extension",
  ...
  "permissions": [
    "scripting",
    "activeTab"
  ],
  "action": {},
  "background": {
    "service_worker": "background.js"
  }
}
```

Note that the example code on https://developer.chrome.com/docs/extensions/reference/action/#injecting-a-content-script-on-click works fine.

**Comment by oliverdunk** [comment]
Fixed by https://github.com/GoogleChrome/developer.chrome.com/pull/5032. Thanks!
