### ISSUE TITLE
Reading time example is greyed out in my list of extensions

### ISSUE THREAD

**Issue by Davo2153** [GoogleChrome/developer.chrome.com#4511]
Hi, I have Windows 10 64-bit using Chrome Version 108.0.5359.73

I followed through the example for Reading Time, copied and pasted all code from GitHub libraries and installed the extension.  Unfortunately when I go to the list of extensions the reference is greyed out so clicking on it does nothing.

I am brand new to writing extensions so I have probably overlooked something basic.

Any help would be appreciated.

Thanks.
Regards,
Christopher.

**Comment by AmySteam** [comment]
Hi @Davo2153! I'm happy to hear you are starting your Chrome extension developer journey 🙂

If the extension icon is greyed out, you are probably on a site where the extension cannot run. 

Reading time only displays the total reading time on https://developer.chrome.com/docs/webstore/ and https://developer.chrome.com/docs/extensions/ pages.

Try following the instructions under [Test that it works](https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-reading-time/#try-out) and let me know if you can see the reading time under the date.

Happy to help with any other questions. 
Amy
