### ISSUE TITLE
Force Cache Url For Browser

### ISSUE THREAD

**Issue by sawacrow** [GoogleChrome/developer.chrome.com#4516]
When I update the JS or CSS files, the client or product manager cannot see the new things when he enter the URL with Chrome for control. Because Browser Cache works. one needs to do ctrl + f5. of course It is possible to solve this problem on the developer side,  if there is a URL for Chrome, for example: google.com?cacheForce and it refreshes all caches when users connect with this url. Everything will be very easy. Because users forget to refresh the cache and we developers are wasting a lot of time.

**Comment by ferhatatagun** [comment]
@sawacrow 

Your suggestion makes a lot of sense.
For now, you can solve your problem with "?v=" queries.

https://dnnsupport.dnnsoftware.com/hc/en-us/articles/360017743254-Clearing-the-cache-of-CSS-and-JavaScript-files-in-DNN

**Comment by AaronForinton** [comment]
Because this is an application feature request (rather than a documentation one), it's not going to be handled on this board. I suggest you feedback [in application](https://www.google.com/tools/feedback/intl/en/) to get your info over to the devs.
