### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by pjwin** [GoogleChrome/developer.chrome.com#453]
**Describe the bug**
Broken link

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/tut_debugging/
2. Click on Download a broken extension [here](https://github.com/GoogleChrome/chrome-extensions-samples/blob/master/tutorials/broken_background_color.zip)
3. See error

**Comment by samthor** [comment]
@dotproto the MV2 page for this is updated, but it seems like the extension needs recreating for MV3.
