### ISSUE TITLE
Document extension_features flags and usage

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#4587]
**Describe the bug**
Document extension_features flags and usage.

**To Reproduce**

Go to https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/extension_features.cc. 

**Expected behavior**
A clear and concise description of how to use the flags.

**Additional context**
I am trying to enable `"StructuredCloningForMV3Messaging"` (https://bugs.chromium.org/p/chromium/issues/detail?id=248548#c44) for testing.

**Comment by jpmedley** [comment]
@guest271314, Thank you for your request. We do not document these flags and their usage.
