### ISSUE TITLE
proxi hide debug class name verbosity

### ISSUE THREAD

**Issue by djmisterjon** [GoogleChrome/developer.chrome.com#4588]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Hi, if you are able to do something for help us to use proxi and to keep class name + proxi when debugging ? 
Proxi make lost the full name of the instances constructor and make more hard the visual debug.

**To Reproduce**
1. create a Maps of instances with proxi and without proxi
2. console log this Maps collections

**Expected behavior**
A clear and concise visual identification of the class, it nice we can see it a proxified instance, but maybe mix both name ? 
so maybe find a trick to expose something like this
```ts
Proxy {position: Proxy, proxyBehavior: 2, dirties: Set(0), zeroMap: undefined, signalDirty: ƒ} //current

Proxy(PositionComponent) {position: Proxy, proxyBehavior: 2, dirties: Set(0), zeroMap: undefined, signalDirty: ƒ} //expected
```

**Screenshots**
The first look, we cant know what kind of class handled by this maps ! proxi mask the name.
![image](https://user-images.githubusercontent.com/24865815/206883204-582d0aac-ca09-43e1-93e0-90762bef5f1d.png)

**Comment by matthiasrohmer** [comment]
For feature requests towards Chromium and its developer tools please use https://crbug.com/.

**Comment by djmisterjon** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1400253
