### ISSUE TITLE
Aside with 'important' doesn't render

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4622]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Asides with the 'important' label don't render. This came from a test build on a PR. I can't find an instance of this in production to.

```
{% Aside 'important' %}
Use the important aside to indicate a common problem that the reader wouldn't know
without specialized knowledge of the topic.
{% endAside %}
```

![image](https://user-images.githubusercontent.com/8204171/207418002-fa031947-a143-4db1-981b-f39744e154e5.png)

**Comment by jpmedley** [comment]
If I'm understanding the code correctly, this correct text is [in the configuration](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_data/i18n/common.yml#L85). It's just not getting rendered.

**Comment by jpmedley** [comment]
All I have to look at is the preview build. Would I need to open a fresh PR to see that? Regardless, I'm inclined to taking your word that this works.

**Comment by devnook** [comment]
I think it was a case of missing locale translate and got fixed in the meantime. Please reopen if you find another instance of this bug.
