### ISSUE TITLE
Emulate Prefers-Color-Scheme not applying on dev tool panel

### ISSUE THREAD

**Issue by xkeshav** [GoogleChrome/developer.chrome.com#4628]
**Describe the bug**
Dev Tool Command 
Emulate CSS Prefers-Color-Scheme not being applied to Dev tool Custom Panel which is developed as a Chrome extension.

It was working earlier and now it runs only when we open devtool of devtool and run the command in child devtool panel

**To Reproduce**
1. Open Dev Tools using Inspect 
2. Ctrl+P > Run Emulate Css prefers color scheme 
3. This is being applied to main window but not on devtool panel itself

**Expected behavior**
When we run CSS emulate then it should be applied to dev tool panel also.

**Screenshots**

https://imgur.com/gallery/HAsMAeW

**Desktop (please complete the following inf
ormation):**
 - OS: Windows 11 Pro
 - Browser Chrome
 - Version 108.0.5359.99

**Additional context**
https://stackoverflow.com/questions/74786311/css-emulate-prefer-color-scheme-command-does-not-work-for-chrome-extension-added

**Comment by devnook** [comment]
This is not related to developer.chrome.com website. Please consider raising an issue at http://crbug.com
