### ISSUE TITLE
Cover domain matching in materials related to declarativeNetRequest

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4636]
This was announced last March, but we don't seem to have anything about it in our documentation. Details here: https://groups.google.com/a/chromium.org/g/chromium-extensions/c/4971ZS9cI7E/m/jnUfCtGUAQAJ

**Comment by jpmedley** [comment]
@IanStanion-google, apologies for not finding this earlier.

**Comment by IanStanion-google** [comment]
Addressed in #6123
