### ISSUE TITLE
expression preview in console is not updated when the context (window) is changed

### ISSUE THREAD

**Issue by alirezamirian** [GoogleChrome/developer.chrome.com#4640]
**Describe the bug**
When a side-effect-free expression is typed in the console, before pressing Enter, a preview is shown with the result of the expression, which is very useful:
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/3150694/207864314-f665389b-8209-44ea-9d2b-b91e517d14f2.png">

There is a context selector, which lets you change the active window, on which the console operates:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/3150694/207864517-a1ddec85-7f84-4c93-99a3-109b5799dc8b.png">

When the context (active frame) is changed, the expression may need to be re-evaluated, but it's not at the moment. Obviously, any change in the expression results in the preview getting updated.

**To Reproduce**
1. In a page with iframes, go to console tab
2. Type `window.location.href`, for preview to show.
3. Change the context to some other frame with a url.
4. See the expression preview, not updated.

**Expected behavior**
Expression preview should be reactive with respect to execution context.

**Desktop (please complete the following information):**
 - OS: Probably N/A, but tested on Mac
 - Browser Probably N/A, but tested on Chrome
 - Version 108.0.5359.71

**Comment by devnook** [comment]
Hi,

This seems a bug in Chrome devtools rather than developer.chrome.org website. Please follow this steps to submit issue in the right place: https://support.google.com/chrome/answer/95315
