### ISSUE TITLE
Broken link in 'Manifest - Sandbox'

### ISSUE THREAD

**Issue by EmiliaPaz** [GoogleChrome/developer.chrome.com#4644]
**Describe the bug**
[Link](https://developer.chrome.com/docs/extensions/mv3/contentSecurityPolicy/) in 'Documentation > Extensions > Develop extensions and themes > Manifest - Sandbox' is broken

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/manifest/sandbox/
2. Click on [default Content Security Policy](https://developer.chrome.com/docs/extensions/mv3/manifest/sandbox/#:~:text=default%20Content%20Security%20Policy) on the second to last paragraph
3. Broken link

**Expected behavior**
Links opens

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version: 108.0.5359.98 (Official Build) (x86_64)

**Comment by jpmedley** [comment]
@EmiliaPaz The file this wants to link to doesn't exist. I poked around in our git history and can't find that this ever existed. I also greped our repo and can't find any content we can link to.

We'll need to write this. Do you have anything on the default CSP I could read?

**Comment by AmySteam** [comment]
[PR#3837](https://github.com/GoogleChrome/developer.chrome.com/pull/3837) to adds a [manifest-CSP page](https://deploy-preview-3837--developer-chrome-com.netlify.app/docs/extensions/mv3/manifest/content_security_policy/). When this is merged, we can fix the link in the Manifest - Sandbox page.

**Comment by EmiliaPaz** [comment]
The link provided by @AmySteam is good for CSP. Thanks!
