### ISSUE TITLE
manifest.json on the chrome extension cannot have a trailing comma after the last key:"value" but in tutorial it has

### ISSUE THREAD

**Issue by badaszszsz** [GoogleChrome/developer.chrome.com#4656]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
manifest.json on the chrome extension cannot have a trailing comma after the last key:"value" but in tutorial it has

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-reading-time/'
2. Do first step manually
3. Try to load manifest.json
4. See error in Chrome

**Expected behavior**
This file should be correct and be parsable by Chrome, so remove trailing comma.

**Screenshots**
![image](https://user-images.githubusercontent.com/86535475/208269470-3964fec2-c135-452a-a602-e5cf0258e248.png)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Thanks for your tutorials ;)

**Comment by shivam-bit** [comment]
Hi @AaronForinton ,
I am working on this, raising PR in next 5 mins.

**Comment by shivam-bit** [comment]
Fixed https://github.com/GoogleChrome/developer.chrome.com/pull/4666
