### ISSUE TITLE
No way to write to clipboard in offscreen document

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#4660]
**Describe the bug**
Reason in [`chrome.offscreen`](https://developer.chrome.com/docs/extensions/reference/offscreen/#type-Reason) includes `CLIPBOARD`. However, there is no way to use `navigator.clipboard.writeText()`, nor the other `navigator.clipboard` methods such as `write()`, `read()`, `readText()`.
**To Reproduce**
1. Call `await navigator.clipboard.writeText(location.href)` in a module script loaded from a document created with 

```
await chrome.offscreen.createDocument({
   url: 'offscreen.html',
   justification: 'ignored',
   reasons: ['CLIPBOARD'],
});
```
2. See error

```
DOMException: Document is not focused.
```

**Expected behavior**
Some means to override the document being focuced requirement for non-extension code to be able to use `navigator.clipboard`, given `CLIPBOARD` is a listed reason for offscreen document usage.

**Screenshots**
![Screenshot_2022-12-18_08-14-27](https://user-images.githubusercontent.com/4174848/208308393-940c0a96-9db1-44cc-9cea-d20ae10442a9.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 110

**Comment by rachelandrew** [comment]
This repo is for the website at https://developer.chrome.com and not for bug reports or feature requests for Chrome itself. 

If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com

**Comment by guest271314** [comment]
> This repo is for the website at https://developer.chrome.com/ and not for bug reports or feature requests for Chrome itself.

Yes, I understand that.

Your documentation is obviously incomplete where there is a Reason named `CLIPBOARD` yet no explanation about how to use that reason in practice.

**Comment by guest271314** [comment]
@rachelandrew This same documentation issue put another way: How to use the `CLIPBOARD` reason https://developer.chrome.com/docs/extensions/reference/offscreen/#type-Reason? Is that explained in the documentation?
