### ISSUE TITLE
Implement filter to cast dates from Chrome milestone numbers

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#4663]
In the context of the WebSQL deprecation there was a request to @tomayac to update the date in the deprecation post. This could actually be automated by using the data from the [Chrome Release Schedule](https://chromiumdash.appspot.com/schedule) that is also powering the release widget on the homepage.

To achieve this, the task to sync the external data from the respective API needs to be updated at: [/external/build/lib/chrome-release.js](https://github.com/GoogleChrome/developer.chrome.com/blob/main/external/build/lib/chrome-release.js) to not only output the `beta` and `stable` channel information to external/data/chrome-release.json, like this

```json
{
  "channels": {
    "beta": {
      "mstone": 108,
      "key": "beta",
      "stableDate": "2022-11-29T00:00:00.000Z"
    },
    "stable": {
      "mstone": 107,
      "key": "stable",
      "stableDate": "2022-10-25T00:00:00.000Z"
    }
  }
}
```

But contain an additional key `milestones` like this:

```json
{
  "milestones": {
    "m121": {
      "branch_point": "2023-11-16T00:00:00",
      "earliest_beta": "2023-12-07T00:00:00",
      "earliest_beta_ios": "2023-11-29T00:00:00",
      "feature_freeze": "2023-11-02T00:00:00",
      "final_beta": "2024-01-03T00:00:00",
      "final_beta_cut": "2024-01-02T00:00:00",
      "late_stable_date": "2024-01-11T00:00:00",
      "latest_beta": "2023-12-14T00:00:00",
      "stable_cut": "2024-01-02T00:00:00",
      "stable_date": "2024-01-09T00:00:00",
    }
  },
  "channels": {
    ...
  }
}
```

This information could then be used in a new filter `chromeDate`, which could be used in templates like this:

```md
## Web SQL deprecation and removal steps

- [✅ Done.] Web SQL was deprecated and removed for **third-party contexts** in
  **Chromium 97** ({{ 'm97'|chromeDate:'stable_date' }}).
- [✅ Done.] Web SQL access in **insecure contexts** was deprecated as of
  **Chromium 105** ({{ 'm105'|chromeDate:'stable_date' }}) at which time a warning message was shown in the Chrome DevTools Issue
  panel.
```

`stableDate` could also be considered the default date.

**Comment by tomayac** [comment]
Small additional feature when implementing this: Please make sure this doesn't split day and moth by inserting an `&nbsp;` (example: `"March&nbsp;1"`, which avoids unfortunate line breaking like `"March\n1"`).
