### ISSUE TITLE
GIF Image in memory-101 documentation might be wrong

### ISSUE THREAD

**Issue by MangoPomelo** [GoogleChrome/developer.chrome.com#4684]
https://developer.chrome.com/docs/devtools/memory-problems/memory-101/#dominators

In the last image of the section that has an alt attribute "Animated dominator illustration".

At first, when the cursor is hovering over the GC root, it shows the GC root dominates #11. However, after a while, when the cursor is hovering over #11, it shows the dominator is #1 which should be wrong I guess.

The dominator of #11 should be GC root.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312582250
