### ISSUE TITLE
Differentiate footer headings from links

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/developer.chrome.com#4685]
On pages like https://developer.chrome.com/blog/early-stable it would be nice to visually differentiate the column headings (Contribute, Related content, Connect) more strongly from the links below them. 

At present, each column just looks like a list of items. I inadvertently clicked on the Connect heading — it took me a moment to realise that the items below it are the links. 

How it is now:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/205226/208886841-a9e6bd7f-7483-460d-a98e-ecae1e18e263.png">

Possible alternative:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/205226/208887969-e3195350-a63b-4fc2-9374-570a92670dcf.png">

**Comment by nerdy-nakul** [comment]
Hello @samdutton 
Can i work on this issue?
