### ISSUE TITLE
Correct link in Chrome Dev Insider December blog post

### ISSUE THREAD

**Issue by harleenkbatra** [GoogleChrome/developer.chrome.com#4691]
Hi, the link to the words "advances in machine learning", in the blog post - /blog/insider-dec-22 is incorrect. It should point to https://blog.google/products/chrome/building-a-more-helpful-browser-with-machine-learning/

Could you please help me get that updated? thanks

**Comment by rachelandrew** [comment]
@harleenkbatra will be fixed within the next hour (once the site rebuilds).
