### ISSUE TITLE
Manifest reference doesn't link to APIs properly (uses relative links)

### ISSUE THREAD

**Issue by alozta2** [GoogleChrome/developer.chrome.com#47]
**Describe the bug**
Some of the pages under https://developer.chrome.com/docs/extensions cannot be accessed. It will result with 404.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv2/manifest/background/
2. You will see "Aw, Snap! We couldn't find that page." error. In developer console you can see "Failed to load resource: the server responded with a status of 404 ()"

**Comment by samthor** [comment]
This will be fixed by #141
