### ISSUE TITLE
Text is being rendered inside of the secondary side menu

### ISSUE THREAD

**Issue by chihabhajji** [GoogleChrome/developer.chrome.com#4703]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.

**Describe the bug**

Text is being rendered inside of the secondary side menu

**To Reproduce**
1. Go to ['this link'](https://developer.chrome.com/docs/extensions/mv3/single_purpose/#three)
2. Scroll down
3. See error

**Expected behavior**

Text should be rendered either nested in the ToC using accordions or below it normally

**Screenshots**

![image](https://user-images.githubusercontent.com/35853327/209210362-d9cd75c7-8ccc-4da2-a082-476a6f9ac5eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browsers : Chrome / Opera / Brave

**Comment by chihabhajji** [comment]
md file seems to be valid, i'm not familiar with the project structure enough to dig any further

**Comment by chihabhajji** [comment]
might be something related to
[navigation-tree.njk](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_includes/partials/navigation-tree.njk)

**Comment by rachelandrew** [comment]
It's CSS, there is `white-space: nowrap` on the `<li>`, so the flex layout is doing exactly what one would expect.

**Comment by mollietokyo** [comment]
**Estimate** - 2hrs

**Comment by matthiasrohmer** [comment]
Should be fixed by https://github.com/GoogleChrome/developer.chrome.com/pull/4831. Please verify and close if that's the case.

**Comment by chihabhajji** [comment]
LGTM!
