### ISSUE TITLE
Investigate and improve response times

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#4705]
With App Engine running on a single instance in `us-east`, response times are not ideal, especially for users not in the us. Waiting for response and content download can take up to 400ms:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/12857772/209216725-300cd0c4-b3a5-4ce4-90d7-cf81cecae847.png">

With the new setup introduced in #4527 things change: generally computing time increases, as requesting meta data from the bucket to set the correct content-type on the response costs a request roundtrip. Download time though decreases, though it's not quite clear why yet, as the instance is still in `us-east`.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/12857772/209217909-ed3f9b49-a2b1-4470-86aa-cc6f36795d5f.png">

A possible action might be to store the content-types of every file in the instance and only look it up if it can't be found (for new files for example). Another alternative might be a CDN, though that would require mechanics for cache purging.

However Netlify offers response times of around 50ms, which is what we should also aim for on App Engine.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/12857772/209218143-d84a2052-9904-4bcc-828c-b71a9cb52480.png">

**Comment by matthiasrohmer** [comment]
Looping in @tunetheweb, who also has some background on how App Engine is setup for the HTTP Archive, which performs better but still not as good as Netlify.

Anyway one good recommendation Barry already had was to set a proper cache-control header for the HTML as well.

**Comment by tunetheweb** [comment]
So AFAIK Google Cloud includes a CDN. So the app engine instance location only really impacts if the request has to go all the way back to the origin.

For example running a WebPageTest from three locations for developer.chrome.com gives the following:
- [Germany](https://www.webpagetest.org/result/230110_BiDcNZ_C3X/1/details/#waterfall_view_step1) - 142.250.186.145 - which is [apparently in Germany](https://ipinfo.io/142.250.186.145)
- [Ireland](https://www.webpagetest.org/result/230110_BiDcZA_C44/1/details/#waterfall_view_step1) - 74.125.193.141 - which is [apparently in Ireland](https://ipinfo.io/74.125.193.141)
- [Virginia](https://www.webpagetest.org/result/230110_BiDcQY_C45/1/details/#waterfall_view_step1) - 142.251.163.141 - which is [apparently in Mountain View](142.251.163.141)

So it IS using a CDN.

However, with the current `cache-control: public, max-age=0` heading we set on our HTML doc, that means ALL those requests need to go back to the origin - that one App Engine instance in the USA 😔

Setting even a small `max-age` time (e.g. 10 mins) should mean only 6 requests per instance location need to go back and should have two immediate effects:

1. The majority of requests should be served from the CDN edge (assuming we get more than 1 request every 10 mins!)
2. The over-worked single instance should have much less to do, and so respond faster for the much fewer requests that end up going back to origin.

But I can't explain why fonts (which do have decent cache control header) also are so much slower then the Netlify preview. I see the same for httparchive.org, and almanac.httparchive.org (also on App Engine), despite serving them using [`static_dir: static`](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/app.yaml). 🤔 Maybe Netlify just has a better CDN?

Either way I think it's worth experimenting with a small Cache Control on the HTML and checking out the TTFB times (that we already measure in CWV). FYI @philipwalton

**Comment by tunetheweb** [comment]
@matthiasrohmer are we using GCP or Firebase hosting?

Apparently with Firebase hosting (which uses Fastly) there's some hidden, magic [Surrogate-Control](https://developer.fastly.com/reference/http/http-headers/Surrogate-Control/) logic (basically the same as `s-maxage`), which is stripped before sending to the browser. It basically caches it at CDN edge automatically and then invalidates it on each release.

So if we're using Firebase hosting it IS caching at the CDN.
However, if you've moved (or are moving) to GCP then we will need to update `maxage` above 0 (or use s-maxage if we only want to set CDN caching) as it doesn't have that funky logic.

**Comment by matthiasrohmer** [comment]
Thanks a lot for digging in, @tunetheweb!

It's Firebase for web.dev, which indeed is Fastly fast compared to d.c.c, which is raw App Engine. So updating the Cache-Control headers for the HTML seem like a good start before trying to improve things on infrastructure side. 🙂

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
