### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Parikshit-Hooda** [GoogleChrome/developer.chrome.com#472]
**Describe the bug**
Youtube links to 'techincal videos' and 'developer snapshots' are broken in documentation.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/overview/#Featured-videos
2. Click on 'Technical videos' and 'Developer snapshots' link in the the section visited using the link in point 1.
3. Notice that they route to the YouTube homepage and not to a specific accurate playlist.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by samthor** [comment]
@dotproto I'm going to remove these rather than try to bring back the old playlists. I find some of the videos on there but they're literally from 2009 or so.
