### ISSUE TITLE
The reason(s) the extension is creating the offscreen document.

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/developer.chrome.com#4720]
**Describe the bug**

The documentation for offscreen uses plural language

> The reason(s) the extension is creating the offscreen document.

```
Uncaught (in promise) Error: Only a single `reason` is currently supported.
```

**To Reproduce**

Write more than one "reason" in `CreateParameters` when constructing an offscreen document.

```
await chrome.offscreen.createDocument({
  url: 'offscreen.html',
  justification: 'ignored',
  reasons: ['CLIPBOARD', 'WEB_RTC'],
});
```

**Expected behavior**
No error to be thrown.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 111

**Additional context**
It is currently _**impossible**_ to use `navigator.clipboard.writeText()` and `navigator.clipboard.readText()` in an offscreen document anyway, even when `clipboard_read` and `clipboard_write` permissions are `"granted"` because this error will be thrown in the offscreen document:

```
DOMException: Document is not focused.
```

**Comment by oliverdunk** [comment]
I'm going to close this one for now. While I agree that the description could be clearer, these comments currently come directly from the Chromium source: https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/api/offscreen.idl;l=37.

Given that the value is an array type, I don't think it makes sense to remove the plural there.
