### ISSUE TITLE
Suggestion (low priority): chrome.privacy usage example uses deprecated property

### ISSUE THREAD

**Issue by EmiliaPaz** [GoogleChrome/developer.chrome.com#4724]
**Is your feature request related to a problem? Please describe.**
chrome.privacy documentation uses `chrome.privacy.services.autofillEnabled.get()` as the [usage example](https://developer.chrome.com/docs/extensions/reference/privacy/#usage)
`autofillEnabled` is deprecated since Chrome 70

**Describe the solution you'd like**
Use another property (e.g `passwordSavingEnabled`)

**Describe alternatives you've considered**
This is not a mistake, since `autofillEnabled` can be used up to Chrome 70. However, it is nice when examples use properties that can be used with the latests versions. This is of low priority

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/311072505
