### ISSUE TITLE
Allow to specify the sharing image of a post

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#4734]
via @rachelandrew, https://github.com/GoogleChrome/developer.chrome.com/pull/4555: the sharing image of a post (`og:image`) currently is inferred from either `hero` or `thumbnail` frontmatter keys. That's not ideal as those keys are also used to set an image for any of the card layouts that link to an article.

Therefore it would be good to have a separate frontmatter key that allows to only set the sharing image.

**Comment by matthiasrohmer** [comment]
Stretch goal: https://github.com/GoogleChrome/developer.chrome.com/issues/4735.

**Comment by devnook** [comment]
Related: #3124

**Comment by mollietokyo** [comment]
**Estimate** - 3hrs
