### ISSUE TITLE
Icons are not converted to dark mode version when a dark theme is used

### ISSUE THREAD

**Issue by RakhithaRR** [GoogleChrome/developer.chrome.com#4750]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
When a dark theme is enabled in Chrome, the thumbnail/icon for a website does not change into the correct color. When multiple tabs are open, its hard to recognize the tab using the icon since its blended into the dark theme.

**To Reproduce**
1. Go to Settings > Appearance
2. Enable GTK+ or any dark theme for Chrome
3. Go to a website with dark thumbnail (eg: Github)
4. The icon will not be changed to the appropriate color even though the dark theme is enabled.
5. Same can be seen with the bookmarks toolbar as well

![image](https://user-images.githubusercontent.com/25485273/210127672-b19bc0c2-ec21-44cc-94a0-f389260ed3ba.png)

![image](https://user-images.githubusercontent.com/25485273/210127683-be8e6360-1565-4425-b2e1-a431a76117a9.png)

**Expected behavior**
The icons/thumbnails should change their color according to the theme used.

For example, this is how the icon is shown in Firefox

![image](https://user-images.githubusercontent.com/25485273/210127723-e6fe3a6d-8748-420e-a40b-9d8a05480b2d.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04/20.04
 - Browser: Chrome
 - Version: 108.0.5359.124

**Comment by devnook** [comment]
This is an issue with Chromium itself and not the developer.chrome.com website. Please raise issue at https://crbug.com/.
