### ISSUE TITLE
MV3 Extension Lifecycle Summary Page

### ISSUE THREAD

**Issue by Christoph142** [GoogleChrome/developer.chrome.com#4752]
#### Sections like https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/extensions/mv3/service_workers/index.md#initialize-the-extension--initialization- do raise a lot of questions to me. What's the longevity of registered items and listeners of mv3 service workers?

There are a lot of related issues I'm having trying to properly develop my extension, e.g. according to above mentioned example it sounds like if I create a context menu item it sticks for my extension until the extension gets uninstalled or updated or until the browser gets updated...?
On the other hand if I want to listen to events stemming from these menu items I have to add a listener to chrome.contextMenus.onClicked each and every time the service worker starts up...?
But then again if I e.g. follow the documentation and register a listener for chrome.downloads.onDeterminingFilename at top level of the MV3 service worker the only thing I get out of it are "suggestCallback may not be called more than once." errors yet calling removeListener immediately followed by addListener does not solve the issue hence there have to be multiple unrelated instances...?
Still my basic assumption was and still is that the service worker script is a singleton...?
Oftentimes when reloading or updating an extension I see "Could not establish connection. Receiving end does not exist." and so on and so forth.

**Long story short: I do not have the slightest idea how lifecycle management for extensions is supposed to work and how it's properly done and I (and looking at StackOverflow et. al. trying to find some pieces of information it's not only me) hence need some guidance.**

#### What content already exists on this topic?

rarely any hints

#### Who will be authoring the content?

I don't know. How about someone who knows about these topics in the first place?

#### Are there any stakeholders who should be informed when this content changes?

I don't know. How about someone who knows about these topics in the first place?

#### What area is your content related to?

Other

#### What kind of content are you creating?

Should be part of https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/extensions/mv3

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll resolve this over there. I’ve moved the issue to our new tracker and you can see it at
https://issuetracker.google.com/issues/324131055
