### ISSUE TITLE
Heading hash anchors can overflow and create extra whitespace

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#476]
**Describe the bug**
If there isn't enough room on a line for a heading's hash anchor then it will overflow to the next line.

![image](https://user-images.githubusercontent.com/1066253/109400312-e9879280-78fc-11eb-8480-baa2ffee1e87.png)

**To Reproduce**
Take a look at this article https://developer.chrome.com/blog/hardware-accelerated-animations/ on a laptop screen.

Possible solutions would be to have the hash anchor be absolutely positioned next to the heading, or change its icon and move it over to the left using negative margin. That's what css-tricks does:
![image](https://user-images.githubusercontent.com/1066253/109400352-25baf300-78fd-11eb-90ae-809520a720a3.png)

**Comment by dotproto** [comment]
I'm a fan of the absolutely positioned negative margin approach.

**Comment by samthor** [comment]
As a side-note, this happens on web.dev too. I think we just have more space there so it's not as obvious.
