### ISSUE TITLE
Document how to use Sandboxed Pages in Manifest V3

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#4771]
>⚠️ _This issue has been migrated from https://crbug.com/1334970_

**Does this work in other browsers?**  Not sure - I don't know

**Steps to reproduce the problem:**
There is no official described way to create a sandbox in MV3 extensions.

**Problem Description:**
The documentation on how to create sandbox (https://developer.chrome.com/docs/extensions/mv3/sandboxingEval/) is obsolete for MV3. It does not work because it requires loading the sandbox.html page within the eventpage.html page. In MV3, we cannot have eventpage.html as it is a service worker.

The samples on GitHub are similarly obsolete ([sample1](https://github.com/GoogleChrome/chrome-extensions-samples/tree/e716678b67fd30a5876a552b9665e9f847d6d84b/apps/samples/sandbox), [sample2](https://github.com/GoogleChrome/chrome-extensions-samples/tree/e716678b67fd30a5876a552b9665e9f847d6d84b/apps/samples/sandboxed-content))

There is no other resource provided in any docs on Chrome on how to create sandbox in MV3. There are two threads on Chromium extensions which still remain unanswered ([thread1](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/W2A5NrYBnIA/m/G5ZWtqE7CAAJ), [thread2](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/G8jq4vIog0A)).

**Requested action:** add documentation/samples on how to create and run a sandbox in MV3.

**Additional Comments:**

**Chrome version:** 103.0.5060.42 (Official Build) beta (64-bit) (cohort: Beta) Channel: Beta

**OS:** Windows

**Comment by AmySteam** [comment]
@oliverdunk @IanStanion-google I thought you might want to know about this when updating this doc.

**Comment by AmySteam** [comment]
Fixed in #6546 and https://github.com/GoogleChrome/chrome-extensions-samples/pull/994
