### ISSUE TITLE
Clarify how service workers are 'registered' (or not) in Extensions

### ISSUE THREAD

**Issue by yangjiao111** [GoogleChrome/developer.chrome.com#4800]
Hello.
When I register the service worker in my extension, report an error:
registerServiceWorker.js:54 Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('chrome-extension://iobioojjnbolcpccoincgijngmmlpoen/') with script ('chrome-extension://iobioojjnbolcpccoincgijngmmlpoen/sw.js'): The user denied permission to use Service Worker.
I want to know that  if it is supported to register the service worker in the extension?

**Comment by guest271314** [comment]
Yes. Navigate to chrome-extension://<id>/index.html

manifest.json

```
{
  "name": "register-service-worker-in-the-extension",
  "version": "1.0",
  "description": "Register ServiceWorker in the extension",
  "manifest_version": 3,
  "action": {
    "default_title": "Register ServiceWorker in the extension"
  }
}
```

script.js

```
try {
  const sw = await navigator.serviceWorker.register(
    './sw.js?' + new Date().getTime(),
    {
      scope: './',
    }
  );
} catch(e) {
  console.error(e);
}
```

sw.js

```
console.log(globalThis);

addEventListener('install', (e) => {
  console.log(e);
  skipWaiting();
});

addEventListener('activate', (e) => {
  console.log(e);
  skipWaiting();
});

addEventListener('fetch', (e) => {
  console.log(e);
});

addEventListener('message', (e) => {
  console.log(e);
});
```

index.html

```
<body>Register ServiceWorker on chrome-extension: protocol</body>
<script src="script.js" type="module"></script>
```

**Comment by jpmedley** [comment]
It does not need to be registered in any of the extension documents. Just put it in the root of your project folder.

**Comment by jpmedley** [comment]
@AmySteam This may be related to your Architecture work. I've made a comment as such in the draft.

**Comment by AmySteam** [comment]
@yangjiao111 
Please see the migration guide that explains [how to register a service worker](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/#man-sw) in manifest version 3. For more details, check out [Migrating from background pages to service workers](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/). Hope this helps! :)
