### ISSUE TITLE
chrome.history.search Unable to get the history records from the same step of the account

### ISSUE THREAD

**Issue by DeBug-Bug** [GoogleChrome/developer.chrome.com#4832]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

chrome.history.search method Unable to get the history records from the same step of the account, only the history records of the local machine

**To Reproduce**
1. call  chrome.history. method
 chrome.history.search({
        'text': '',                // Return every history item....
        'maxResults': 1000000000,  // Have to specify something, so why not a billion?
        'startTime': syncStartTime
    }

**Comment by rachelandrew** [comment]
@DeBug-Bug This is for issues with the https://developer.chrome.com/ site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com/.
