### ISSUE TITLE
Document CLI for using TESTING reason in createDocument()

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4844]
Source in code: https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/api/offscreen/offscreen_api.cc;l=98;drc=d1782ed06b0ccf7a60726c16d99161fb044b2d27

**Comment by dstmarthe** [comment]
I've moved this issue here: https://issuetracker.google.com/issues/324157695
