### ISSUE TITLE
TOC takes over entire page content in a wide window

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#4858]
**Describe the bug**
Content pages contain a `<toc-active>` custom element is not visible unless a window is >= 1440 pixels wide. When visible, page content and the table of contents are displayed as flex columns with the TOC appearing on the right. `.toc__wrapper li` has `white-space: nowrap;`, but this TOC does not have any maximum width defined.

These settings combine so that a page with sufficiently long section titles will cause the TOC to take up nearly all of the horizontal space on the page. 

**To Reproduce**
1. Visit https://developer.chrome.com/docs/extensions/mv3/single_purpose/#five
2. Make sure your browser window is at least 1440 pixels wide.

**Expected behavior**
The page content is legible and the TOC content takes up a reasonable amount of space on the right side of the window.

**Screenshots**

Content of the [Single Purpose FAQ](https://developer.chrome.com/docs/extensions/mv3/single_purpose/) page is compressed into a tube of a few pixels on the left side of the window.
<img width="1120" alt="Screenshot 2023-01-11 at 5 13 25 PM" src="https://user-images.githubusercontent.com/1047763/211953402-33cc7fae-01bc-4bda-ab29-23559b42550e.png">

The [Manifest V3 Migration Checklist](https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/) page is constrained by the TOC, but still legible.
<img width="1120" alt="Screenshot 2023-01-11 at 5 13 43 PM" src="https://user-images.githubusercontent.com/1047763/211953612-568f4e24-358e-4c7f-9d1d-67a6997d6dee.png">

The extensions [FAQ](https://developer.chrome.com/docs/extensions/mv3/faq/) page also has some unusual layout issues related to TOC width.
<img width="1120" alt="Screenshot 2023-01-11 at 5 18 09 PM" src="https://user-images.githubusercontent.com/1047763/211953758-acc7710e-3bad-4ea6-8901-bb37ff57cfa3.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.1
 - Browser: Chrome
 - Version: 108.0.5359.124 (Official Build) (arm64) 

**Additional context**

As a naive solution, I experimented with adding `max-width: 40vw;` to the `toc-active` block. It lead to some TOC entries being truncated by an ellipsis, but fixed the immediate problem with the Single Purpose FAQ.

**Comment by rachelandrew** [comment]
This will be fixed once https://github.com/GoogleChrome/developer.chrome.com/pull/4831 is merged.

**Comment by rachelandrew** [comment]
This is now fixed by the PR mentioned previously.
