### ISSUE TITLE
Content doesn't match tag

### ISSUE THREAD

**Issue by MichaelSolati** [GoogleChrome/developer.chrome.com#486]
Heya, so by chance I was skimming through articles on DCC and came across a small issue.

On the article "Improving Progressive Web App offline support detection" a tag in the front matter is `chrome-92`, however Chrome 92 is never referenced in the article, only Chrome 93. I'm not sure which one is correct, but since @petele  and @jpmedley have edited this file I'm guessing one of you can fix this?

File path for the markdown is => [site/en/blog/improved-pwa-offline-detection/index.md](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/blog/improved-pwa-offline-detection/index.md)

**Comment by samthor** [comment]
I just fixed this directly [here](https://github.com/GoogleChrome/developer.chrome.com/commit/8895fcf11de60bd95861a6d9589fbeba54044359) by removing `chrome-92`, which was not referenced whatsoever. I meant to make a PR but hit the wrong button; I'm happy to close anyway.
