### ISSUE TITLE
Incorrect function call in pop-ups-theyre-making-a-resurgence blog post

### ISSUE THREAD

**Issue by cdrapes** [GoogleChrome/developer.chrome.com#4866]
**Describe the bug**
In the blog post [pop-ups-theyre-making-a-resurgence](https://developer.chrome.com/blog/pop-ups-theyre-making-a-resurgence) the popoverhovertarget polyfill example calls `showPopOver` rather than `showPopover`.

**To Reproduce**
Visit this link to see the incorrect function call: https://developer.chrome.com/blog/pop-ups-theyre-making-a-resurgence/#styling-a-popover:~:text=)%20popover.-,showPopOver(),-%3B%0A%20%20%20%20%7D%2C

**Expected behavior**
The popover element should call `showPopover`.

**Screenshots**
![Screenshot 2023-01-12 at 14 44 44](https://user-images.githubusercontent.com/62894397/212099720-94353e33-189b-4fdd-b4f1-b7358991b865.png)
![Screenshot 2023-01-12 at 14 44 37](https://user-images.githubusercontent.com/62894397/212099726-24b1bd04-5687-4709-b54b-575aca1f0f64.png)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324117900
