### ISSUE TITLE
Remove redundant "Short Name" section from "Name" manifest field documentation

### ISSUE THREAD

**Issue by oliverdunk** [GoogleChrome/developer.chrome.com#4882]
**Describe the bug**
https://github.com/GoogleChrome/developer.chrome.com/pull/4309 adds a new page documenting the `short_name` field of extension manifests, but there is already documentation at https://developer.chrome.com/docs/extensions/mv3/manifest/name/#short_name. We should remove the latter and just include a "See also" link instead.

**Comment by hanminshin** [comment]
fake

**Comment by jpmedley** [comment]
Is there a PR to remove the information from the `name` page?
