### ISSUE TITLE
Snippet in article about setSinkId() may cause a memory leak

### ISSUE THREAD

**Issue by chrisguttandin** [GoogleChrome/developer.chrome.com#4894]
**Describe the bug**
The article about `setSinkId()` (https://developer.chrome.com/en/blog/audiocontext-setsinkid/) contains a snippet which may cause a memory leak.

The article recommends to trigger the permission to view all audio output devices by calling `getUserMedia()` like this:

```js
await navigator.mediaDevices.getUserMedia({ audio: true });
```

As far as I can tell this will keep the returned stream alive indefinitely in Chrome (tested in v109 and v111). Firefox for example will garbage collect the stream.

**To Reproduce**
1. Run the line of code from above.
2. Observe that the microphone indicator of the operating system (tested on macOS) will never go away again.

**Expected behavior**
I think the stream should be stopped immediately when `getUserMedia()` is only used to trigger the permission to view more devices.

```js
const mediaStream = await navigator.mediaDevices.getUserMedia({ audio: true });

mediaStream.getTracks().forEach((track) => track.stop());
```

I'm happy to provide a PR to update the article.

**Additional context**
By coincidence there is currently a spec discussion if garbage collecting an unused stream like that should be allowed or not. https://github.com/w3c/mediacapture-main/issues/910

**Comment by beaufortfrancois** [comment]
You're absolutely right @chrisguttandin
Thank you for raising this issue. I've started https://github.com/GoogleChrome/developer.chrome.com/pull/4982 to address it.
