### ISSUE TITLE
Broken links on https://developer.chrome.com/docs/extensions/mv2/devtools/

### ISSUE THREAD

**Issue by davinsoftware** [GoogleChrome/developer.chrome.com#49]
**Describe the bug**
This docs page has several broken links (404's): 
https://developer.chrome.com/docs/extensions/mv2/devtools/

**To Reproduce**

- Click "devtools.panels" link which points to https://developer.chrome.com/docs/extensions/mv2/devtools.panels - HTTP 404
Should point to https://developer.chrome.com/docs/extensions/reference/devtools_panels/

- Click on "Dev Tools Extension Gallery" - https://developer.chrome.com/docs/devtools/docs/extensions-gallery/ - HTTP 404
I think the gallery is old and gone. Perhaps should point this to https://developers.google.com/web/tools/chrome-devtools/

**Comment by dotproto** [comment]
I have a PR out to fix these and several other issues with links on devtools pages. This should get deployed later today.
