### ISSUE TITLE
Extensions - on specific site filter functionality does not match the documentation

### ISSUE THREAD

**Issue by VRolandFIN** [GoogleChrome/developer.chrome.com#4908]
**Chrome version**
Chrome Version 109.0.5414.75 (Official Build) (64-bit)

**Issue**
Documentation and functionality mismatch in extension specific site match patterns

**Description**
"On specific site" selection in the extensions site access filter is not functioning as mentioned in the documentation.

https://developer.chrome.com/docs/extensions/mv3/match_patterns/ 

The following patterns mentioned in the above example do not work.
https://*/*
https://*/foo*
https://*.google.com/foo*bar
file:///foo*

Instead when trying to add these you get the following warning
Not a valid web address

![image](https://user-images.githubusercontent.com/8825221/212658815-0cdeccab-39bd-4f4b-948e-e5cfa384779b.png)

**Comment by AmySteam** [comment]
@VRolandFIN Can you share your `manifest.json`?

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/312773388
