### ISSUE TITLE
RSS feed for articles

### ISSUE THREAD

**Issue by bramus** [GoogleChrome/developer.chrome.com#4924]
The blog has a RSS feed set up on https://developer.chrome.com/feeds/blog.xml. Would be nice if [the articles section](https://developer.chrome.com/articles/) also had a feed, to make them more easy to follow.

**Comment by emanruse** [comment]
I see this is closed but the previously existing RSS feeds are not there any more.

**Comment by rpodric** [comment]
Yes, vanished several days ago. Surely an oversight.

**Comment by bramus** [comment]
The new publishing platform we migrated to does not offer RSS out of the box. As I understand @matthiasrohmer  is working on a solution for this.

In the meantime you can use these unofficial feeds https://github.com/bramus/chrome-for-developers-rss#live-endpoints
