### ISSUE TITLE
Poor Translation for Portuguese in Google Lighthouse

### ISSUE THREAD

**Issue by matias2018** [GoogleChrome/developer.chrome.com#4935]
**Summary**
I have noticed that the Portuguese translation in Google Lighthouse is of poor quality. Many phrases and words are mistranslated, making it difficult for Portuguese speakers to understand and use the tool effectively. This is a significant issue that needs to be addressed as soon as possible, as it may discourage or exclude Portuguese-speaking users from using the tool.

I kindly request the Google Lighthouse development team to review and improve the Portuguese translation in order to provide a better user experience for Portuguese-speaking users. 
Additionally, I would like to contribute to translating and propose creating a rule to only translate descriptions but not action titles. This would allow users to easily identify and understand the action they are performing while still providing translated descriptions for better understanding.

Thank you for your attention to this matter.

![Screenshot 2023-01-17 at 12 00 46](https://user-images.githubusercontent.com/36554761/212893718-fed3704b-0b0d-459d-bed7-cd2312b951c2.png)

**Comment by brendankenny** [comment]
Thanks for filing, @matias2018. I've transferred to this repo where the docs reside.

I believe we would welcome a PR, but I'm not exactly sure how the translation process usually works. @rachelandrew @malchata do you have advice here? Do we have contributing docs for translations?

**Comment by AaronForinton** [comment]
cc @jecfish

**Comment by matias2018** [comment]
I was just wondering if there have been any updates on the issue?

**Comment by jecfish** [comment]
There are no official process on working with translation. As I have regular volunteer translators working on What's New in DevTools, see https://developer.chrome.com/pt/tags/new-in-devtools/, whenever there are public PR on translations, it get route to me, and I will ask if my regular volunteer translators able to help reviewing those.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at:  https://issuetracker.google.com/issues/312778375
