### ISSUE TITLE
Chrome password import bug

### ISSUE THREAD

**Issue by mixalis1987** [GoogleChrome/developer.chrome.com#494]
**Describe the bug**
Importing of CSV passwords not functioning
**To Reproduce**
1. Go to 'chrome://settings/passwords'
2. Click on 'More menu (3 dots) and click import. '
3. Select the CSV password file, exported from chrome before.
4. Selection box will close and then chrome does nothing and passwords are not imported.

**Expected behavior**
Add passwords that are in the CSV file.

**Screenshots**
No screenshot available as of yet.

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux]
 - Browser [Chrome]
 - Version [89.0.4389.72] (Official Build) (64-bit)

**Comment by samthor** [comment]
Hi, please file Chrome bugs on crbug.com. This is for documentation bugs only.
