### ISSUE TITLE
Discuss how to identify filenames in documentation

### ISSUE THREAD

**Issue by oliverdunk** [GoogleChrome/developer.chrome.com#4948]
In some docs, we use the `{% Label %}` shortcode to identify filenames: https://developer.chrome.com/docs/extensions/mv3/content_scripts/#programmatic.

It came up in a call recently that we want to agree on a better way of doing this. Ideas could be:

- Adding additional style to the label shortcode to make it more appropriate for this usecase.
- Deciding on an alternative, such as a `// filename.js` comment at the top of a code snippet.

Opening this issue from https://github.com/GoogleChrome/developer.chrome.com/pull/1984 to discuss.

**Comment by AmySteam** [comment]
Here's a few links to add more context:

- Handbook [labels section](https://developer.chrome.com/docs/handbook/components/#labels)
- PR that added the label shortcode [#1450](https://github.com/GoogleChrome/developer.chrome.com/pull/1450/)

**Comment by jpmedley** [comment]
Maybe I'm remembering wrong, but I thought that it was formatting bold, which was competing with the headings. That seems to have been solved. Let's use these.

**Comment by oliverdunk** [comment]
Since we have a decision here I'm closing this one out :)
