### ISSUE TITLE
add MV2,MV3 or ALL flags to API Reference

### ISSUE THREAD

**Issue by hanguokai** [GoogleChrome/developer.chrome.com#495]
**Problems faced by developers**

Some extension APIs are MV2 only or MV3 only, and some APIs are available on both MV2 and MV3. For example:

- chrome.scripting is MV3 only vs chrome.tabs.executeScript is MV2 only.
- chrome.tabGroups is MV3 only
- chrome.browserAction is available on both MV2 and MV3

There is no flags to identify these characteristic.

**Describe the solution you'd like**

Like https://packagecontrol.io/ , there are flags to show which Sublime Text version can use a plugin, e.g. `ST2`, `ST3`, `ALL`. There are more similar examples like package control.

The document don't need to add flags to all APIs, but it should add flags to some new and some old APIs which are only available on specific Manifest version.

**Additional context**
Here are two discussions on the forum:
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/2fyCMDhVgQY/
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/q8E56RrWpo4/

**Comment by samthor** [comment]
Thanks for calling this out. This data is available in the raw feature files inside the Chromium source code. I'll attempt to bring this across today.
