### ISSUE TITLE
[DevTools] Broken image in WNDT 65

### ISSUE THREAD

**Issue by wolfib** [GoogleChrome/developer.chrome.com#4951]
The first image in the description of local overrides (https://developer.chrome.com/blog/new-in-devtools-65/#overrides) returns a 422 - unprocessable entity. The URL is https://wd.imgix.net/image/BrQidfK9jaQyIHwdw91aVpkPiib2/pPRYEcOzEloITwitsHRd.gif?auto=format&w=1600. I tried removing the query params and indeed https://wd.imgix.net/image/BrQidfK9jaQyIHwdw91aVpkPiib2/pPRYEcOzEloITwitsHRd.gif works. The link contains an animated gif, maybe that's why automatic resizing does not work.

@jecfish Could you PTAL? I'd like to link to this from the header overrides RFC and a broken image would not leave a good impression.

**Comment by jecfish** [comment]
@sofiayem PTAL

**Comment by wolfib** [comment]
Awesome, thanks for the fast fix!
