### ISSUE TITLE
Images Not Visible after Google Chrome Update to Version 109.0.5414.75

### ISSUE THREAD

**Issue by ErKarangoel** [GoogleChrome/developer.chrome.com#4960]
I have updated Google Chrome to the latest version (official build) 109.0.5414.75 and a few images are not visible also after the system reboot images got impacted in edge as well, this is really very annoying because these are impacting the work performance.
![missing image](https://user-images.githubusercontent.com/117480089/213446763-3344e21f-183f-43aa-91c9-af3038a920e6.png)

**Comment by matthiasrohmer** [comment]
This repository only tracks issues directly related to the site developer.chrome.com. For issues around Chrome itself, please use the Chromium Bug Tracker at https://bugs.chromium.org/p/chromium/issues/list.

**Comment by ErKarangoel** [comment]
> This repository only tracks issues directly related to the site developer.chrome.com. For issues around Chrome itself, please use the Chromium Bug Tracker at https://bugs.chromium.org/p/chromium/issues/list.

@matthiasrohmer you mean to say the team who is handling the bug is not using GitHub. This is strange reply
