### ISSUE TITLE
Add CSP info to content scripts page

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#4969]
Currently the content scripts documentation does not describe how content security policies interact with isolated world scripts and main world scripts. This documentation should be expanded to describe

* The CSP applied to isolated world scripts
* What this CSP prevents extensions from doing
* How CSP applies to content scripts injected in the main world

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://buganizer.corp.google.com/issues/311045997
