### ISSUE TITLE
'Table of contents' should be 'Contents'

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4970]
There are two reasons:
* Minor noise reduction on a page.
* Application of the best practice to omit needless words.

![image](https://user-images.githubusercontent.com/8204171/213569687-28624c37-cd71-4f41-a511-16271a6fc383.png)

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
