### ISSUE TITLE
Gradual Performance Selection (Dev Tools)

### ISSUE THREAD

**Issue by PhilippElhaus** [GoogleChrome/developer.chrome.com#4984]
Currently it is only possible to select a Speed reduction of 4x & 6x in the Performance Tab. 

This is a great way to simulate a website on slower devices. However it is arbitrary based on the individuals developer machine and has only these two limited options to choose from- that are strangely set at these 2 values; probably due to technical background reasons.

It'd be great if instead of these two selections there'd be a slider OR dropdown menu that allows the selection of the speed as a multiple of a reference CPU e.g. a 1Ghz chip from 2010 (or something similar).

Or to select depending on a hardcoded list of devices, e.g. Iphone6, Iphone8,Ipad4th Gen, Quad Core 2.8Ghz i7 etc.

Or a mix of these two solutions, which would probably be the optimum.

**Comment by matthiasrohmer** [comment]
Thanks for sharing your idea on dev tools, Philipp! This repository (and the team maintaining it) really only works on the site developer.chrome.com, not Chrome or Chromium as a product. For feature requests towards those please use the Chromium Bugtracker: https://bugs.chromium.org/p/chromium/issues/list

Unfortunately we do not have the capacity to forward the requests on our side.
