### ISSUE TITLE
Fix broken link on '/docs/lighthouse/overview/'

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/developer.chrome.com#4992]
**Describe the bug**
Reference-style link isn't rendering correctly due to the `desktop` reference not being defined in the Markdown file `site/en/docs/lighthouse/overview/index.md`.

```
Download [Google Chrome for Desktop][desktop].
```

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/lighthouse/overview/#extension'
2. See error in the first list item of 'To install the extension'

**Expected behavior**
Link to render properly.

**Screenshots**
<img width="1100" alt="Screen Shot 2023-01-21 at 9 06 33 PM" src="https://user-images.githubusercontent.com/48612525/213902256-d73e919a-810c-41fd-b20e-e33ab127cede.png">

**Desktop (please complete the following information):**
 - OS: [High Sierra]
 - Browser [chrome]
 - Version [10.13.6]

**Comment by Mayuresh0072** [comment]
@tannerdolby @twifkak @rik @bbbrrriiiaaannn @technohippy Hello, I want to fix this issue. Please Assign it to me. Thanks.
