### ISSUE TITLE
Black Border Around Search in Chromium  Version (87.0.4280.66) 

### ISSUE THREAD

**Issue by al-chaudhari** [GoogleChrome/developer.chrome.com#50]
A Black Border Around the Search Bar in Chromium Version 87.0.4280.66 But Looks Normal in Mozilla Firefox [developer.chrome.com](https://developer.chrome.com/)
![bug](https://user-images.githubusercontent.com/30781942/101864206-ffa57280-3b99-11eb-9f47-6b7010963c27.png)

**Comment by myakura** [comment]
@al-chaudhari that's the updated focus ring style in Chromium. See https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html for more details.

I kinda agree it should tweak the outline style a bit (like updating outline-radius to match the input).

**Comment by samthor** [comment]
Not an issue; we're surprisingly fine with the default focus styles, whatever they happen to be for your browser. 👍
