### ISSUE TITLE
Inconsistent staging experience when PR rebased to main

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#5034]
The Pr https://github.com/GoogleChrome/developer.chrome.com/pull/5006 tried to use BrowserCompat widget, but it rendered "this shortcode is not supported" instead on taging environment.

I think what happened is that Pr was created BEFORE widget was available, cloud instance was created, and next updates to the PR (including updating to main) did not trigger a full rebuild but only a static deploy. This led to inconsisten state where staging instance didn't have all the code pulled from main and therefore the widget rendered as not supported.

Netlify preview rendered as expected, first with "shortcode not supported" and then after merge of main with correct widget rendered.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
