### ISSUE TITLE
port disconnect in MV3

### ISSUE THREAD

**Issue by shenghuowang** [GoogleChrome/developer.chrome.com#504]
**Describe the bug**
when website connect to a chrome extension(use MV3),port disconnect after several minutes

**To Reproduce**
1. create a chrome extension use MV3, code as follow；
           chrome.runtime.onConnectExternal.addListener((port) => {

            port.onMessage.addListener((msg) => {
              // handle msg
            });
            port.onDisconnect.addListener(() => {
                //handle disconnect
            });
        });
2. add extension in chrome browser
3. in my website, connet to this extension, code as follow:
     let port = chrome.runtime.connect(extensionId, { name: id });
    this.port.onMessage.addListener((msg) => {
         // handle msg
    });
    port.onDisconnect.addListener(() => {
       // handle disconnect
    });
    after several minutes(about 5-6 minutes),my website receive port disconnect

**Expected behavior**
   port not disconnect, keep live connection

**Additional context**
  when extension  change to MV2, this bug not happen, it seems to be a bug in MV3

**Comment by robdodson** [comment]
@shenghuowang is this related to a specific doc on developer.chrome.com? If not, it might be better to ask this on https://stackoverflow.com/

**Comment by dotproto** [comment]
Closing as this is a Chromium issue ([1146434](https://bugs.chromium.org/p/chromium/issues/detail?id=1146434), not a documentation bug.

**Comment by alex2snikers** [comment]
Okey, but where to turn for help ?

**Comment by ShaoboLiu** [comment]
The same issue happened in my project of MV3. 

runtime.connect successfully, and postMessage a few times successfully. However, after 5 minutes, onDisconnect event triggered. Looks like automatically lost connection. I don't know what is the reason.

**Comment by qhkm** [comment]
I'm having this issue right now with my chrome extension. Would appreciate an update on the issue I am experiencing. Thank you.
