### ISSUE TITLE
Errors in Build Stage of CI 

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#5045]
Our source files are accumulating errors that are causing the Build stage of our CI to not pass. (See the image below.) This means that only commiters with Admin access can merge pull requests. (That's how it appears to me.)

![image](https://user-images.githubusercontent.com/8204171/214884242-9345fcf1-e96a-462d-a0a4-03300eca7b61.png)

**Comment by giambilos** [comment]
Giambilos
