### ISSUE TITLE
Size limits should be noted in extensions documentation

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#5060]
Specifically: 

* No hard limits for on CRX size. (Needs confirmation).
* 500MB max for a single script.
* 1 GB for all content scripts together within a single extension.

Limits don't block installation, but do cause API errors during script injection.

Should this be in /Extensions, Web Store, or both.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311019872
