### ISSUE TITLE
Page Lifecycle API guide does not mention 'frozen' as possible previous state for 'active', 'passive' or 'hidden'

### ISSUE THREAD

**Issue by rejhgadellaa** [GoogleChrome/developer.chrome.com#5062]
**Describe the bug**

Both the [Page Lifecycle states](https://wd.imgix.net/image/eqprBhZUGfb8WYnumQ9ljAxRrA72/1mN2saGWo57O6vIOdcGy.svg) and the table in chapter [States](https://developer.chrome.com/blog/page-lifecycle-api/#states) indicate that the 'frozen' state has the following possible next states:

* active (via the resume event, then the pageshow event)
* passive (via the resume event, then the pageshow event)
* hidden (via the resume event)
* discarded (no events fired)

While 'frozen' is listed as possible previous state for 'discarded', it's not mentioned for 'active', 'passive' or 'hidden'.

**Expected behavior**

If state A is listed under possible next state under B, I expect B to be listed as possible previous state under A.

**Comment by rejhgadellaa** [comment]
I also think the diagram could be slightly improved by moving the indicator for multiple next-state possibilities (yellow) to where the lines actually split up (red). 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/4703109/215258360-2cae7e3e-1c0c-449c-a6c4-d8b694223571.png">

**Comment by tunetheweb** [comment]
@rejhgadellaa it looks like it is listed as a previous state for Hidden, but I agree it is nor listed for Active and Passive. I also agree the positioning of the decision point could be better place (possibly need two of these - one for each junction points).

@domenic / @spanicker do you agree that Frozen should be a previous state of Active/Passive as the diagram suggests? If so I'm happy to update the post.
