### ISSUE TITLE
Background worker won't get registered if it's not in a project root

### ISSUE THREAD

**Issue by ihorbond** [GoogleChrome/developer.chrome.com#507]
**Describe the bug**
Docs don't specify that worker script HAS to be in the root of the project unlike it was with manifest V2

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tophf** [comment]
Sounds like #228.

**Comment by ihorbond** [comment]
> Sounds like #228.

Agreed
