### ISSUE TITLE
Remove hardcoded old version once not needed anymore  

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#5086]
Roll back once this vulnerability / regression is resolved: https://github.com/GoogleChrome/developer.chrome.com/pull/5085

**Comment by matthiasrohmer** [comment]
Fixed by [8ee8cf5](https://github.com/GoogleChrome/developer.chrome.com/commit/8ee8cf579ca357dc49efb3663a5a594a4c8ad9c0).
