### ISSUE TITLE
History api added twice in the same page

### ISSUE THREAD

**Issue by yashgkar** [GoogleChrome/developer.chrome.com#51]
**Describe the bug**
The website contains the same api link twice for history API

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dotproto** [comment]
What page did this occur on?

**Comment by yashgkar** [comment]
Its on documentation page, please check this (https://developer.chrome.com/docs/extensions/reference/)

**Comment by vapier** [comment]
similar to issue #45
