### ISSUE TITLE
raster font（simsun/宋体）broken in 109

### ISSUE THREAD

**Issue by ahdung** [GoogleChrome/developer.chrome.com#5117]
chrome: 109
os: Windows7
108 no problem. Not only broken in web page, even in `DevTools`. `Simsun`（宋体 in chinese） is a base, default, very important font in chinese Windows, so please fix it.

![微信截图_20230202142934](https://user-images.githubusercontent.com/12094247/216248794-268e8257-7f1a-4309-895d-52ced73eb98a.png)

**Comment by matthiasrohmer** [comment]
Thanks for reporting that issue. Unfortunately this repository is solely related to work for the site developer.chrome.com. For bug reports towards Chromium browsers please use https://bugs.chromium.org/p/chromium/issues/list

**Comment by ahdung** [comment]
Thanks.
