### ISSUE TITLE
ChromeOS-only APIs not displaying ChromeOS only warning

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#513]
Certain APIs are ChromeOS only, and previously would display a ChromeOS only warning.  This isn't the case on the new docserver.

New Server:
https://developer.chrome.com/docs/extensions/reference/enterprise_deviceAttributes/

Old Server:
https://3-72-0-dot-chrome-apps-doc.appspot.com/extensions/enterprise_deviceAttributes

**Comment by samthor** [comment]
This might be a regression from last week. I'll look next week when I'm
back.

**Comment by samthor** [comment]
The new server logs deviceAttributes as ChromeOS only. There might be other discrepancies, but that specific one is resolved.
