### ISSUE TITLE
"getting-started" extension throws error

### ISSUE THREAD

**Issue by vgzhn** [GoogleChrome/developer.chrome.com#514]
**Describe the bug**
Following the steps led to my Version throwing an error.
The completed example also gave a(different) error.

**To Reproduce**
1. download https://storage.googleapis.com/chrome-gcs-uploader.appspot.com/file/WlD8wC6g8khYWPJUsQceQkhXSlv1/SVxMBoc5P3f6YV3O7Xbu.zip
2. add to chrome
3. click symbol and green box
4. see error in extension manager

**Expected behavior**
no error
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 20H2
 - Browser Chrome
 - Version 89

**Additional context**
Errors:
**my version:**

Errors
Uncaught (in promise) TypeError: Cannot read property 'executeScript' of undefined
Context
popup.html
Stack Trace
popup.js:13 (anonymous function)

**highlited line:**  ` chrome.scripting.executeScript({`

**prebuilt version:**
Errors
Unchecked runtime.lastError: Cannot access a chrome:// URL
Context
popup.html
Stack Trace
popup.html:0 (anonymous function)
Nothing to see here, move along.

**Comment by dotproto** [comment]
Thanks for the report. The immediate workaround is to use this extension on non chrome:// pages. We will need to update the example to guard against this invocation pattern.
