### ISSUE TITLE
Way to remove an injected content script?

### ISSUE THREAD

**Issue by dbjpanda** [GoogleChrome/developer.chrome.com#5154]
I want to have a toggle button on my popup which allows users to enable or disable the extension though not completely disable the extension but technically control the execution of the content.js or that particular domain. 

Something similar to  

<img width="375" alt="Screenshot 2023-02-05 at 2 59 45 AM" src="https://user-images.githubusercontent.com/17483092/216790340-c1846a37-4d92-4f18-838e-8bb42321ca5e.png">

popup.js
```js
const toggleBtn = document.querySelector(".toggle");

toggleBtn.addEventListener("click", function(){
    if(toggleBtn.checked === true){
        console.log('inject content.js');
    }else{
        console.log('remove content.js');
    }
});
```

I can see there is a way to inject it but there is no way to remove it.
```js
          chrome.scripting.executeScript({
                target: {tabId},
                files: ['content.js'],
            });
```

**Comment by oliverdunk** [comment]
Hey @dbjpanda 👋 

You may be interested in dynamic content script registration: https://developer.chrome.com/docs/extensions/mv3/content_scripts/#dynamic-declarative

However, if you want to disable a content script which has already been injected, a better way to do that may be having the content script still run but having a way to disable its functionality (e.g sending a disable message to it or ignoring messages it sends you).

In the future, the chromium-extensions mailing list is a great place for questions like this: https://groups.google.com/a/chromium.org/g/chromium-extensions
