### ISSUE TITLE
Chromium Projects

### ISSUE THREAD

**Issue by clowndogloko** [GoogleChrome/developer.chrome.com#5162]
![Screenshot_20230206-051721](https://user-images.githubusercontent.com/124565600/216969560-1a2c284c-7395-4625-a4c6-6c82dd2c2002.png)

⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AaronForinton** [comment]
Hi there @clowndogloko and thanks for submitting your issue. 

Since this issue relates to Chromium rather than our documentation base, please submit it at [https://crbug.com/](https://crbug.com/). Thank you.
