### ISSUE TITLE
chrome.gcm method signatures are very, very unreadable

### ISSUE THREAD

**Issue by rdcronin** [GoogleChrome/developer.chrome.com#5176]
The generated signature for [chrome.gcm.register](https://developer.chrome.com/docs/extensions/reference/gcm/#method-register) is extremely unreadable.

I _suspect_ that this is because the signature takes in a single argument, an array with at least one element and no more than 100 elements:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/gcm.json;l=20-31;drc=2857c6b778eb16623281c8e1206ad85baa63cedd

It looks like maybe we're then trying to generate each possible signature?  (array of length one, array of length two, array of length three..., array of length 100).

If this is what's going on, it doesn't scale.  It's an issue in chrome.gcm, and it would also be an issue with any API where there are multiple arguments (since then you have combinatorial signatures).

Instead of this, could we add a tag to the argument indicating the min / max length?

**Comment by AaronForinton** [comment]
Hi there @rdcronin and thanks for submitting your issue.

Since this issue relates to Chromium rather than our documentation base, please submit it at [https://crbug.com/](https://crbug.com/). Thank you.
