### ISSUE TITLE
<enhanced-select> shows long double-line option name like 2 options

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#5186]
List items in the enhanced-select use line-height instead of padding to space items vertically which makes items that span over 2 lines (becasue of long option names) look like they were two items, while they are actually one.

E.g. PointerLock and unadjustedMovement in /fugu-showcase:
https://deploy-preview-5159--developer-chrome-com.netlify.app/fugu-showcase

<img width="355" alt="Screenshot 2023-02-07 at 12 32 28" src="https://user-images.githubusercontent.com/1914261/217233777-4804df63-ac43-4060-9090-4eaff81d8fe1.png">

**Comment by tomayac** [comment]
The `<enhanced-select>` component is also completely broken on Safari (`Version 16.3 (18614.4.6.1.5)`):

- Safari:
   ![Screenshot 2023-02-09 at 16 33 00](https://user-images.githubusercontent.com/145676/217858873-4acf4441-6229-4834-8192-b67803e48427.png)
- Chrome:
   ![Screenshot 2023-02-09 at 16 33 10](https://user-images.githubusercontent.com/145676/217858970-62147f95-a6ec-4877-b1dd-7561b5ef6bee.png)
