### ISSUE TITLE
Fix small design and usability glitches on landing pages

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#5197]
Note, this issue covers the state of things like they were in https://github.com/GoogleChrome/developer.chrome.com/pull/5149#pullrequestreview-1288940331.

The landing pages have some minor design glitches that make them look off in some places. The screenshots are taken from https://developer.chrome.com/en/docs/handbook/content-types/landing/

- The icon in the hero card is directly sticking to the headline as per design there should be a little padding
<img width="382" alt="image" src="https://user-images.githubusercontent.com/12857772/217514224-471ea1f2-8514-4c9d-9c13-e1dc21282d95.png">

- Links are not really discoverable. The headlines do not convey the are clickable, I'd vote for the full "card" to be clickable. (Opinions, @tokyodanj?)
<img width="374" alt="image" src="https://user-images.githubusercontent.com/12857772/217514548-8c8a03c3-56e4-4ab6-a743-6d4d888cacc5.png">

- `.landing-section--right .item__title` does not use `Google Sans` as font
<img width="309" alt="image" src="https://user-images.githubusercontent.com/12857772/217514863-d1293414-2018-4112-b5a9-fe403bcf7df1.png">

- `.landing-section--ordered .landing-section__links h3` does not use `Google Sans` font
<img width="459" alt="image" src="https://user-images.githubusercontent.com/12857772/217515280-09292ca8-11a6-4160-ba46-dd73dfef7e17.png">

**Comment by tokyodanj** [comment]
@matthiasrohmer 

> Links are not really discoverable. The headlines do not convey the are clickable, I'd vote for the full "card" to be clickable. 

As there are multiple links within a card it's going to be tricky to make the full card clickable. An alternative solution would be to add underlines.

e.g.

<img width="1176" alt="Screenshot 2023-02-14 at 17 03 58" src="https://user-images.githubusercontent.com/15090758/218806889-dcf189c7-1d1f-4d9e-bdfc-c1eae609bf18.png">

Let me know what you think.

**Comment by mollietokyo** [comment]
Estimate for dev = 1 day (SPR-3)
