### ISSUE TITLE
Create a design for a Deprecations Calendar

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#5210]
Browser features come, but they also go - via Deprecations. For reference see [Chrome's deprecation policy](https://developer.chrome.com/blog/deps-rems-101/#deprecation-policy) and Tom's talk about [Chrome Feature Deprecations](https://docs.google.com/presentation/d/1W5DeIrr9peA4n4VNHNMctdgS3-6NEP9ADit8oC-xb0U/edit#slide=id.p).

The dates for when those deprecations happen should be surfaced on a filterable dashboard/calendar on developer.chrome.com, with the goal to provide developers with an overview of past and upcoming deprecations, removals, and changes in behavior so developers who want to actively keep up with new deprecations can easily find that information.

To get an idea of upcoming deprecations have a look at https://chrome-status-lite.deno.dev/deprecations

This issue is meant to gather requirements with the help from @andreban, identify meaningful user journeys and then come up with a design that fits the overall look and feel.

**Comment by mollietokyo** [comment]
@andreban / @matthiasrohmer - this will need a design briefing session with Andre to determine requirements.

Estimated 3 days (design SPR-3 only, no dev) for now.

**Comment by andreban** [comment]
Thanks Mollie, Dan and I are meeting tomorrow (Thursday, 16th) to discuss requirement.s

**Comment by tokyodanj** [comment]
Design has been created in Figma. Andre is taking this to a couple of other stakeholders within Chrome for feedback.

**Comment by tokyodanj** [comment]
Initial design work done. Any new requests and/or development work to be opened in a new ticket once Andre has aligned with the other stakeholders.
