### ISSUE TITLE
MV3 migration docs do not mention XMLHttpRequest -> Fetch

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#522]
**Describe the bug**
The Manifest V3 migration resources do not mention that XMLHttpRequest is not available in service workers (or any worker for that matter). This is likely to be a stumbling block for some developers.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/
2. Look for references to XMLHttpRequest or Fetch

**Expected behavior**
Documentation explaining that XMLHttpRequest is not available in worker contexts and that developers must migrate to the Fetch API.

**Comment by tophf** [comment]
Might wanna mention the most popular XHR-based wrappers such as jQuery.ajax (and its alias $.ajax) or axios, maybe a few others if you happen to know the names. Maybe also mention that loading jQuery in the background script makes little to no sense now as this library is hardwired to DOM-related API that aren't present in a worker.
