### ISSUE TITLE
The tests run temporarily 2x rollup because of how trasforms are defined in .eleventy - roll back when possible

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#5244]
The tests run temporarily 2x rollup: https://github.com/GoogleChrome/developer.chrome.com/pull/5220/commits/bc61a13435ad43ee4fa8737bb72716427cb4d522

This is becasue after adding "production" requirement to e2e tests, some tests require `tests/dist/js` to exist
(old rollup call) and the transforms in .eleventy in "production" mode  require files in main `/dist/js`.

It should be fixable by changing the logic in .eleventy transforms method to point to 11ty input/destination directory.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
