### ISSUE TITLE
getFileIcon does not work according to documentation in MV3

### ISSUE THREAD

**Issue by Christoph142** [GoogleChrome/developer.chrome.com#5252]
**Describe the bug**
getFileIcon (called in downloads.onCreated) returns undefined with runtime.lastError { "message": "Filename not yet determined" } until a filename has been determined in MV3. This contradicts the documentation which pretends the icon would be available at this point already. Additionally, once the icon gets returned, the size is 64px although documentation states only 16 and 32 are possible resolutions.

**To Reproduce**
call getFileIcon in downloads.onCreated

**Expected behavior**
Not sure. Is it supposed to work and actually a Chromium bug or a documentation issue?
Surely the possible icon size needs to be adjusted.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 110

**Comment by Christoph142** [comment]
cross-linking https://bugs.chromium.org/p/chromium/issues/detail?id=1414999

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324275825
