### ISSUE TITLE
Local Override 

### ISSUE THREAD

**Issue by rishabhmehta** [GoogleChrome/developer.chrome.com#5259]
After enabling the local override and trying to use the changes tab, there are three issues which are persisting:

1. Page starts reloading instantly the moment I  start typing css properties in the styles tab
2. When I use the changes tab to save file it creates a new folder as show in image and starts saving to that file and not the project file
3. When I use the copy button in the changes tab, it doesn't do anything at all to my local files in the project! 

Is anyone else facing this issue?

<img width="166" alt="Screenshot 2023-02-13 at 6 42 31 PM" src="https://user-images.githubusercontent.com/8098502/218467409-04023be0-5404-46de-8723-df495d86652b.png">

Attached screenshot for reference. It creates a style?cacheoverview and before I could give it the unit chrome refreshed instantly before I typed unit "rem" in the padding 

<img width="421" alt="Screenshot 2023-02-13 at 6 49 06 PM" src="https://user-images.githubusercontent.com/8098502/218468750-db82747b-bffd-48cc-9915-399a33d16e2d.png">

**Comment by AaronForinton** [comment]
Hi there, and thanks for getting in touch. Since this is a feature bug rather than a documentation issue, please direct your query to the [Chromium bugs board](https://bugs.chromium.org/p/chromium/issues/list). Thank you.
