### ISSUE TITLE
Document how to preview Chromium changes in extensions docs

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#527]
**Is your feature request related to a problem? Please describe.**
Chromium extension engineers would like to know how they can preview Chromium changes, both local changes and Gerrit CLs. 

**Describe the solution you'd like**
Ideally this process would be relatively straight forward or easily automatable, and it would be documented in a way that's easy for Chromium engineers to reference. I think this makes sense to either document in READMEs in the repo or in the [dcc handbook](http://developer.chrome.com/docs/handbook). Regardless of where it lives, we should also have a link in an appropriate part of the Chromium repo (possibly in https://source.chromium.org/chromium/chromium/src/+/master:extensions/docs/ ?)

**Describe alternatives you've considered**
The only alternatives I've considered are location. I briefly discussed putting this documentation in the Chromium repo, but I think it makes more sense for the guidance to live in the same location that a) eng would expect to view the output or b) next to the tools that are used to generate the output. 

**Additional context**

**Comment by samthor** [comment]
You can run "node external/build/types.js <path_to_all_d.ts>".

That .d.ts file can be generated by the [chrome-types](https://github.com/GoogleChrome/chrome-types) repo. However, that can only currently generate from git revisions of the main Chromium source.
It could be expanded to fetch from Gerrit.

**Comment by dstmarthe** [comment]
I've moved this issue to the new issue tracker at: https://issuetracker.google.com/issues/324454858
