### ISSUE TITLE
Add support for `projection=PUBLISHED` in the store items. API

### ISSUE THREAD

**Issue by sdesmond46** [GoogleChrome/developer.chrome.com#5270]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**
While trying to set up automated publishing of our extension, I'd like to be able to get information about the currently published version of the extension. The [`Items:GET`](https://developer.chrome.com/docs/webstore/webstore_api/items/get/) endpoint only supports `projection=DRAFT` and gives a 403 if you attempt to use `projection=PUBLISHED`

**Describe the solution you'd like**
`projection=PUBLISHED` should be supported in the API

**Describe alternatives you've considered**
Scraping the html off the public store listing works for public store items, but not for Domain listed extensions.

**Additional context**

**Comment by dstmarthe** [comment]
Hi, this repo is specifically for issues with d.c.c content. You can submit feature requests and feedback to the Chrome Web Store here: https://support.google.com/chrome_webstore/contact/one_stop_support

The "A developer feature suggestion" will be your best bet.

**Comment by muanmanuelmanuel** [comment]
Ggg
