### ISSUE TITLE
Samples page doesn't match structure of samples repo.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#5298]
A few weeks ago, @oliverdunk reorganized the samples repo. None of us knew or remembered that our documentation has a page that links to that repo and describes its contents in detail. It needs to be updated.

https://developer.chrome.com/docs/extensions/mv3/samples/

cc: @IanStanion-google @AmySteam

**Comment by oliverdunk** [comment]
I think this could do with some extra detail, but it has been updated, right? I made sure to fix any broken links there and at least describe the new structure at a high level.

**Comment by AmySteam** [comment]
@jpmedley Are you talking about the links? I just tested them, and they all work. @oliverdunk Also added a description for each section in the samples

<img width="312" alt="Screenshot 2023-02-15 at 10 17 41" src="https://user-images.githubusercontent.com/37001393/219087570-6c882409-b3b0-4637-a3fe-fbd547a20736.png">
<img width="522" alt="Screenshot 2023-02-15 at 10 17 20" src="https://user-images.githubusercontent.com/37001393/219087577-a9416b22-5a91-4a5a-bad4-992f8203fed1.png">

@jpmedley Can you clarify which part you think needs to match the new structure?
