### ISSUE TITLE
The link does not match the content?

### ISSUE THREAD

**Issue by ouweiya** [GoogleChrome/developer.chrome.com#53]
https://developer.chrome.com/docs/extensions/reference/types/

![chrome_duqgOCUekI](https://user-images.githubusercontent.com/28357731/101908493-2645c680-3bf7-11eb-87eb-80932987cf32.png)

**Comment by samthor** [comment]
This is the long-form introduction text for the `chrome.types` namespace. I don't think there's any issue with this page.
