### ISSUE TITLE
Light House Speed Index Report parameters do not match docs

### ISSUE THREAD

**Issue by Amitmodi51** [GoogleChrome/developer.chrome.com#5315]
We have optimized our home page and then we reviewed the page speed score in Light house and we found that our speed Index score is 2.0S [Speed Index Report](https://developer.chrome.com/docs/lighthouse/performance/speed-index/?utm_source=lighthouse&utm_medium=devtools) and in this reference document we can see that under 0 to 3.4 its all good and green (fast), then why it is showing Red in our case.  Please refer to the below screenshot of Lighthouse score.
![image](https://user-images.githubusercontent.com/18240399/219348636-baae7831-d6ba-4e16-9adc-c7503bd0a525.png)

idle score as per the reference link:
![image](https://user-images.githubusercontent.com/18240399/219349173-182cadb7-a828-4d3f-9ff1-e70261aadd16.png)

As per the doc, last updated on June, 2021, so is it required to update the doc as per the current trend and updates?
![image](https://user-images.githubusercontent.com/18240399/219349471-22471bdc-93b8-4225-a8e1-12bec2e02443.png)

Please help me out on this. and If I am wrong please update me where I am doing any wrong. Thanks and Regards

**Comment by tunetheweb** [comment]
That's the mobile speed index score as noted in the docs (though possibly could be made more obvious). The Desktop limit is 1.320 seconds and (looking at your FCP score which has a similar issue), I'm guessing you're looking at Desktop.
