### ISSUE TITLE
[devtools-missing] Remote debugging

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#5349]
As we are working on the [Chrome Headless blog post](https://developer.chrome.com/articles/new-headless/), we realize missing documentation on general remote debugging. At the moment, we only have a [documentation on remote debugging Android device](https://developer.chrome.com/docs/devtools/remote-debugging/).

- Propose to expand the existing docs or have a new page for that. 
- Some details on remote debugging are already mentioned in the [blog post](go/headless:blog-post). We can use that as a base for the docs.
- The content size would be S-M size.
- As this documentation is to support the new feature launch, the priority would be similar to new WNDT documentation.

**Comment by mathiasbynens** [comment]
The PR for the article about new Headless is #5370. In case it helps, we’re still awaiting some internal approvals but we aim to publish it some time in early March (no specific publish date).

Expanding the docs on remote debugging is not blocking the article publication though; it could go live as-is, and we could always link to the updated docs as soon as they're made available.

**Comment by dstmarthe** [comment]
Hi y'all, can this be closed, or should I migrate it as sort of a reminder?

**Comment by sofiayem** [comment]
This was published: https://developer.chrome.com/docs/chromium/new-headless
