### ISSUE TITLE
The "chrome.idle" API doesn't seem to detect screen lockage with KDE or xlockmore

### ISSUE THREAD

**Issue by Xavion** [GoogleChrome/developer.chrome.com#535]
I use [Bitwarden](https://bitwarden.com/) as my password manager.  Its Chrome extension has the ability to lock the database when the system/screen is locked.  As you can see [here](https://github.com/bitwarden/browser/blob/c86151d74f6aab1ac1e935d8f443961d9a788829/src/background/idle.background.ts), the relevant section of code uses "idle.queryState" and "idle.onStateChanged".

A technical support representative confirms that the auto-lock feature works [in Ubuntu] with GNOME.  Unfortunately, I can tell you that it doesn't [in Arch Linux] with either KDE’s ‘kscreenlocker’ (cmd: kscreenlocker_greet) or ‘xlockmore’ (cmd: xlock).  We are both using Chrome v89.0.4389.82.

Are you able to get this working for me (particularly with xlockmore as that's what I use)?  I keep forgetting to lock the password database manually before going out and it's a security hazard (in case someone breaks in).  Let me know if you'd like any further testing done.

**Comment by dotproto** [comment]
Please use https://crbug.com/new to file a bug on the Chromium repository. This repository is for developer.chrome.com and the documentation it hosts.

**Comment by Xavion** [comment]
OK, sorry about that.  I have created the new ticket [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1192396).  It's necessary to mention that as I had notified Bitwarden of this one (and suggested their developers keep an eye on it).
