### ISSUE TITLE
Easily navigate from ≤MV2 to ≥MV3 extension docs

### ISSUE THREAD

**Issue by mrienstra** [GoogleChrome/developer.chrome.com#5355]
**Is your feature request related to a problem?**
If I land on an ≤MV2 availability API, I'd like to be able to easily navigate to the applicable ≥MV3 API, when feasible. E.g. from [docs/extensions/reference/browserAction](https://developer.chrome.com/docs/extensions/reference/browserAction/) I'd like to see links leading to both of the following:
- the [Action API unification](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/#action-api-unification) section of "Migrating to Manifest V3"
- [chrome.action](https://developer.chrome.com/docs/extensions/reference/action/) extension API reference  docs 

**Describe the solution you'd like**
Add an aside at or near the top of pages, probably a [warning aside](https://developer.chrome.com/docs/handbook/components/#warning-asides) to match pages like [docs/extensions/mv2](https://developer.chrome.com/docs/extensions/mv2/) which use [_partials/extensions/mv2-legacy-page.md](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/_partials/extensions/mv2-legacy-page.md), but in this case the asides should contain MV2 ➝ MV3 links specific to the topic.

**Describe alternatives you've considered**
There may be a better format for this than a warning aside, the relevant data could reside in a mapping somewhere and be pulled in somehow, using the same flow that [site/_includes/layouts/namespace-reference.njk](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_includes/layouts/namespace-reference.njk) is a part of, but that doesn't seem quite right to me.

**Additional context**
Mockup, using this HTML (also had to transplant a little CSS from a page with an aside):
```
<div class="aside aside--warning"><div class="aside__label gap-bottom-300"><svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path d="M23 21L12 2 1 21h22zm-12-3v-2h2v2h-2zm0-4h2v-4h-2v4z" fill-rule="evenodd" clip-rule="evenodd"></path></svg><span>Warning</span></div><p>Browser actions are <a href="https://developer.chrome.com/docs/extensions/mv3/mv3-migration/#action-api-unification">not available in Manifest V3</a>, see the <a href="https://developer.chrome.com/docs/extensions/reference/action/"><code>chrome.action</code> API</a> when building new extensions, as the Chrome Web Store no longer accepts Manifest V2 extensions.</p></div>
```
![developer chrome com_docs_extensions_reference_browserAction_ ](https://user-images.githubusercontent.com/669326/219823872-908640b4-86fe-4018-a9ee-7b4366be2243.png)

Willing to open a PR if there is a path forward.

**Comment by matthiasrohmer** [comment]
Thanks for raising this and also offering to contribute! We also started to pick this up internally for discussion and will follow-up in this issue 🙂

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
