### ISSUE TITLE
Extensions CSP page redirects to apps version

### ISSUE THREAD

**Issue by karan173** [GoogleChrome/developer.chrome.com#536]
There used to be an extension specific CSP page, see https://3-72-0-dot-chrome-apps-doc.appspot.com/extensions/contentSecurityPolicy. But I can't find it on the new site. 
https://developer.chrome.com/docs/extensions/contentSecurityPolicy redirects to https://developer.chrome.com/docs/apps/contentSecurityPolicy.

**Comment by dotproto** [comment]
Thanks for calling this out. We can definitely get the old page back. In fact, I think we will need to as we need an MV3-specific page to document how this value has changed in MV3.

**Comment by kospl** [comment]
There is some information available for MV3 at https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#fcontent-security-policy

But still current documentation is misleading on new format used for CSP setting:

1. `"key": "value"` format at https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#fcontent-security-policy
![image](https://user-images.githubusercontent.com/26386660/112738964-562f9480-8f70-11eb-9762-fd517d3c6729.png)

2. but other inline format as mentioned at https://developer.chrome.com/docs/extensions/mv3/manifest/sandbox/
![image](https://user-images.githubusercontent.com/26386660/112738974-647db080-8f70-11eb-87d9-2415e70a4f84.png)

let me know if you can test and tell which format (if any) is correct one.

**Comment by jpmedley** [comment]
This appears to be a duplicate of #247. In any case, undocumented manifest elements are being consolidated under #163.
