### ISSUE TITLE
Arrow displayed for {% Details %} element

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#540]
@samdutton commented on [Thu Mar 18 2021](https://github.com/GoogleChrome/dcc-private/issues/536)

(As discussed in chat:  Could be missing `::-webkit-details-marker`.)

I've used `{% Details %}`, and it works OK, but I see the drop-down arrow at the left of each section, as per the screenshot. 

![image](https://user-images.githubusercontent.com/205226/111675513-1d2b4d80-8815-11eb-9cfe-018da9ef0c52.png)

Chat has link to code. Works fine in the [handbook](https://developer.chrome.com/docs/handbook/components/).

I've tried pulling from main, running `npm ci`, etc.

**Comment by dotproto** [comment]
@samthor I think this is related to the details issue I flagged in #493.

**Comment by robdodson** [comment]
this appears to be fixed

**Comment by samthor** [comment]
Yeah, I fixed this in DCC. I guess I thought the issue was also showing up
on web.dev.
