### ISSUE TITLE
Support `publishTarget=unlisted` in the Store Items API

### ISSUE THREAD

**Issue by philsch** [GoogleChrome/developer.chrome.com#5419]
**Is your feature request related to a problem? Please describe.**

Using the Chrome Item API to publish an item, it is currently only possible to publish `public` (default) or for `trustedTesters` (https://developer.chrome.com/docs/webstore/webstore_api/items/publish/#parameters). The Web Store offers another visibility option **Unlisted**. For automation it would be nice if the API would also support this option.

**Describe the solution you'd like**
The Item Publish API support a parameter `publishTarget="unlisted"`

**Describe alternatives you've considered**
Our only alternative is a manual submit via the Web Interface if we want to publish an unlisted item.

**Additional context**

![Screenshot 2023-02-23 at 10 54 12](https://user-images.githubusercontent.com/5527838/220874226-9376f213-99cd-439a-bee0-dc6e19c46660.png)

**Comment by dstmarthe** [comment]
This tracker is for issues with the content at [developer.chrome.com](http://developer.chrome.com/), please raise Chromium issues at:  https://issues.chromium.org/issues?q=status:open
