### ISSUE TITLE
Design decent looking fallback images for blog heros

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#5427]
https://github.com/GoogleChrome/developer.chrome.com/pull/2723 now enforces the aspect-ratio of blog card images in order to make the blog listing page look neat. Missing images though still make the grid feel off.

Therefore we want to use the background images (the bubbles, get them from Figma) from our new sharing image generator as a fallback.

**Comment by matthiasrohmer** [comment]
In the sprint review today we agreed to design specific fallback images, as the backgrounds from the sharing image generator are tailored to work with text.

**Comment by mollietokyo** [comment]
Matthias needs to pass this onto the wider team before it can be reviewed / approved
