### ISSUE TITLE
Split main.css on template basis for quicker purging

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#5436]
The site has three main CSS build targets: `main.css`, `events-main.css`, `chrome-main.css`. While the later two are specialized stylesheets for the events (/meet-the-team) and the Chrome 100 page (/100) the `main.css` file powers the styling for all other pages of the site.

As it weighs over 200KB unminified and uncompressed this amount of CSS slows down some parts of the build pipeline, the CSS purging process specifically which removes unused CSS from pages whose execution time is dependent on the amount of CSS given in.

Therefore we should try to further split up `main.css` into specific stylesheets for our content types. Stylesheets that *could make sense* are `landing-page.scss`, `fugu-showcase.scss`, `homepage.scss`, `article.scss` (powering both blog articles and docs). Please check those assumptions before getting started.

Those specific stylesheets should only include the blocks/components and utilities that are actually required or can be used on the matching templates.

**Comment by simgobb** [comment]
After a quick document proposal, the idea is to split `main.css` into the following: 

- `home.css`
- `fugu.css`
- `landing.css`
- `overview.css`
- `single-post.css`

To make the implementation and testing easier, it's been decided to split this issue into smaller ones, one for each of the new stylesheets.

**Comment by mollietokyo** [comment]
spoke with Matthias, he's waiting on internal updates prior to marking this one as 'done'

**Comment by matthiasrohmer** [comment]
Fixed up #5554 and merged. We now got distinct CSS files per template/page type
