### ISSUE TITLE
chrome.offscreen doc is missing hasDocument

### ISSUE THREAD

**Issue by sebastianbenz** [GoogleChrome/developer.chrome.com#5437]
Currently, https://developer.chrome.com/docs/extensions/reference/offscreen/ lists only createDocument and closeDocument. `hasDocument` is critical as createDocument for an already existing doc results in an exception. 

It would also be great if we could add a bit more detail to closeDocument, in particular, whether closing is a hard kill or a soft close when the document is idle (this might be relevant if two different operations are active).

**Comment by IanStanion-google** [comment]
@sebastianbenz This was intentionally removed because the method was made for internal debugging.

**Comment by sebastianbenz** [comment]
Oh, interesting! What's the right way then to create a new document? try / catch?

**Comment by IanStanion-google** [comment]
I'll look into a proper best practice for this, as well as answer your question about closeDocument! 
Would be good to have this information clear for developers.

**Comment by sebastianbenz** [comment]
The offscreen doc reference docs have been updated with this.
