### ISSUE TITLE
Lightbox mode for images

### ISSUE THREAD

**Issue by petele** [GoogleChrome/developer.chrome.com#548]
**Is your feature request related to a problem? Please describe.**
When using the `{% Img %}` shortcode, I'd love an option to allow the viewer to be able to click on the image and get a full screen (lightbox) view of the image.

**Additional context**
Not sure if this should be filed here or in the Uploader, apologies if it's the latter.

**Comment by robdodson** [comment]
@petele this is supported if you set `linkTo=true` on the Img shortcode. It's not a true lightbox per se, but it allows the user to open a larger version of the image

**Comment by petele** [comment]
I'd still like to see a lightbox feature so that the user doesn't necessarily have to navigate away, or right click and open in a new tab.
