### ISSUE TITLE
Link causes line break in content

### ISSUE THREAD

**Issue by petele** [GoogleChrome/developer.chrome.com#549]
**Describe the bug**
The link should be inline with the text. From PR #547 ([staged here](https://deploy-preview-547--developer-chrome-com.netlify.app/blog/chromium-chronicle-19/))

<img width="364" alt="Screen Shot 2021-03-23 at 10 06 06 AM" src="https://user-images.githubusercontent.com/718038/112159298-64bc2b80-8bbf-11eb-8412-28d59f6afd9c.png">

**To Reproduce**
See [code](https://github.com/GoogleChrome/developer.chrome.com/pull/547/files#diff-8905182a14f30b61a9bea477ee27bc285faa26f804e61206dc91ae053e207948R20) below:

```
{% Columns %}

{% Column %}
<a href="https://www.jetbrains.com/clion/features/navigation-and-usages-searches.html">Find Usages</a>
of methods. Navigate directly to definitions from the source.
{% endColumn %}

{% Column %}
{% Img src="image/0g2WvpbGRGdVs0aAPc6ObG7gkud2/iQqaFyy8mneSlmR7iNOY.png", alt="Find usage of GetFpMode in Project and Libraries", width="764", height="554" %}
{% endColumn %}

{% endColumns %}
```

**Expected behavior**
No line break

**Comment by petele** [comment]
This affects PR #547

**Comment by robdodson** [comment]
I'm looking into the bug, but I might suggest not doing a two column layout in this case because it makes the images on the right quite hard to read.

![image](https://user-images.githubusercontent.com/1066253/112340965-449f7180-8c7e-11eb-8f94-724080aa8862.png)
