### ISSUE TITLE
WebHID demos url is broken

### ISSUE THREAD

**Issue by nondebug** [GoogleChrome/developer.chrome.com#5504]
Originally reported at https://crbug.com/1420701

**Describe the bug**

The link to the WebHID demos article is broken.

**To Reproduce**
(1) Go to https://developer.chrome.com/articles/hid/#demos
(2) Click on the demos link (https://developer.chrome.com/hid-examples/)
(3) "Aw, Snap! We couldn't find that page"

**Expected behavior**

Either link to the actual demos page (https://web.dev/hid-examples/) or move the demos to developer.chrome.com.

Note that the link's text still has the old web.dev URL but clicking the link navigates to developer.chrome.com

**Comment by AaronForinton** [comment]
I think the demos should be moved to developer.chrome.com, any thoughts? @rachelandrew

**Comment by rachelandrew** [comment]
@AaronForinton yes let's move these, thanks!
