### ISSUE TITLE
Add Chrome platform status component: feature-specific

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/developer.chrome.com#5520]
We now have components for the [Chrome version date](https://pr-4757-static-dot-dcc-staging.uc.r.appspot.com/docs/handbook/components/#chrome-date) and [Browser compat](https://pr-4757-static-dot-dcc-staging.uc.r.appspot.com/docs/handbook/components/#browser-compat). It would be great to have Chrome platform status for specific features, especially for the Privacy Sandbox.

For example, [FedCM docs](https://developer.chrome.com/docs/privacy-sandbox/fedcm/#implementation-status) link to the [Chrome Platform status](https://chromestatus.com/feature/6438627087220736). Rather than just linking out to the status, a widget that updates with the current implementation status, planned milestones, and link to the full status page would be very useful.

```
// Possible mockup with variables to customize: ID, name, milestone platform
{% ChromeStatus 12345, 'Custom feature name', 'all/Desktop/Android/Webview/none' %}
```

Topics API is another great example, which has had changes to implementation status and estimated milestones that are important in the coming months.

```
// Input for Topics API status
{% ChromeStatus 56809230549647368 %}

//Output
The Topics API is in origin trial.
* Desktop from 101 to 113
* Android from 101 to 113
```

To give another example with more content:

```
// Input for CSS "update" media
{% ChromeStatus 5154424982339584, 'CSS update media' %}

//Output
CSS update media is in developer trial (behind a flag).
* Desktop dev trial in 113, shipping in 113
* Android dev trial in 113, shipping in 113
* Webview shipping in 113
```

**Comment by heyawhite** [comment]
@rachelandrew fyi per our TW meeting today!

**Comment by Yaf532** [comment]
#

**Comment by mhumayunsaeed** [comment]
Has this feature been developed? @heyawhite

**Comment by rachelandrew** [comment]
This repo is to be archived. This issue relates to the old platform so closing.
