### ISSUE TITLE
support close to some tag group

### ISSUE THREAD

**Issue by HomyeeKing** [GoogleChrome/developer.chrome.com#5527]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**

I usually use tag groups, it's a very nice feature, sometimes I need to close the pages between a page or a group and the another tag group

**Describe the solution you'd like**
```
// [] = tag group
a  b  c  [d e f]  ....
[a]  b  c  [d e f]    ....
```
right click at `a` or `[a b c]` will show the menu has `close to the cloest group` option, then `b & c ` will be closed

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Comment by matthiasrohmer** [comment]
This repository does only handle feature requests towards the site developers.chrome.com. For feature requests towards Chrome the product please use the [Chromium Bug Tracker](https://bugs.chromium.org/p/chromium/issues/list).
