### ISSUE TITLE
Non-li items inside a list have no top margin

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#554]
When putting an item (screenshot, aside, etc.) between items of a numbered list, the item is rendered with no top margin.

See #545 for a demonstration.

**Comment by awfuchs** [comment]
Notes from discussion in chat thread:

we should probably do something like li > * + * { margin-top: var(--flow-space); }
um.. that may do weird things with lists inside of lists though so gotta think about that

ul * + * might also be an option
that would recursively give everything in side the list top margin

**Comment by devnook** [comment]
Closing design related bugs are obsolete.
