### ISSUE TITLE
"What is the Chrome Web Store?" content is outdated

### ISSUE THREAD

**Issue by PallHaraldsson** [GoogleChrome/developer.chrome.com#556]
It's unclear that "The Chrome Web Store lets you publish apps and games" here https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/docs/webstore/about_webstore/index.md

is still true. It refers to Chrome Apps?! And those on the way out even on Chrome OS, and already stopped accepting new apps?

https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html

**Comment by samthor** [comment]
Thanks for calling this out. We have a quite old PR at this point [over here](https://github.com/GoogleChrome/developer.chrome.com/pull/411) which addresses this issue on another page, but we should discuss the web store too. Much of the content is old and does incorrectly refer to the deprecated Apps platform.

**Comment by AmySteam** [comment]
This issue was solved by #1041 
I removed all mentions of Chrome Apps! Thanks @PallHaraldsson :)
