### ISSUE TITLE
Update popover attribute content

### ISSUE THREAD

**Issue by nt1m** [GoogleChrome/developer.chrome.com#5562]
`popovertoggletarget/popoverhidetarget/popovershowtarget="ID"` have been changed to `popovertarget="ID" popovertargetaction="toggle|hide|show"`

This needs to be updated on blog posts and different documentation pages:

- https://developer.chrome.com/docs/web-platform/popover-api/popover-attribute/
- and all the links in the See Also section: https://developer.chrome.com/docs/web-platform/popover-api/popover-attribute/#see-also

Demos on the blog posts also need updating.

**Comment by AaronForinton** [comment]
Hello @nt1m, please let me know if you have any corrections to my PR.
