### ISSUE TITLE
Create a stylesheet for the homepage for quicker purging

### ISSUE THREAD

**Issue by simgobb** [GoogleChrome/developer.chrome.com#5568]
This issue is linked to [#5436](https://github.com/GoogleChrome/developer.chrome.com/issues/5436).

In the context of splitting up the main.css, we need to create a home.css file to style specifically the homepage template. Each file has been separated from the original issue to keep the PRs more manageable and make the testing easier

**Comment by simgobb** [comment]
The homepage styling and general approach have been approved. 

It's been decided to add all the new stylesheets on this PR incrementally in separate commits in order to avoid introducing too many conflicts and make the whole ticket more manageable. 

All the locally-prepared PRs have already been added to this one.

Once this issue gets resolved, the original issue (#5436) can be closed too.

**Comment by mollietokyo** [comment]
spoke with Matthias, he's waiting on internal updates prior to marking this one as 'done'
