### ISSUE TITLE
Chrome does not disconnect open native messaging ports when MV3 extension is unloaded

### ISSUE THREAD

**Issue by pbernini** [GoogleChrome/developer.chrome.com#559]
**Describe the bug**
I have this small native application that connects to a barcode reader device and outputs read barcodes to stdout.
I hooked up the application to a chrome extension to get chrome to open a company-internal web page related to the code read by the barcode reader, and the integration works just fine.

The problem is that when we disable the extension (via the toggle on extension management) Chrome does not close the IO streams with the native process then the process hangs indefinitely. Then if we re-enable the extension, it starts a new instance of the native application (because the previous port instance is unretrievable) but this fails to connect to the device because it accepts only one connection at a time. 

Furthermore, if we terminate the native application via OS process management Chrome **crashes**.

**To Reproduce**
1. Write a native application waiting for a single message from chrome to quit (below an example in C#).
2. Write a simple extension (MV3) that connects to such native application, for example on action click (example below).
3. Load the extension on Chrome and click the action: the native app is launched and waiting for messages.
4. Disable the extension from extension management: the native application does not terminate because its stdin is still open.
5. Re-enabling the extension will result in the spawning of another instance of the native application.
6. Terminating the application via task manager will result in Chrome crashing.

```C#
// native app stub
using System;
using System.IO;

public class Program {
    static void Main(string[] args) {
        byte[] lengthBytes = new byte[4];
        Console.OpenStandardInput().Read(lengthBytes, 0, 4);

        Console.Error.WriteLine("scanner native app is closing");
    }
}
```

```JS
// background.js
chrome.action.onClicked.addListener(() =>{
    var port = chrome.runtime.connectNative("com.mycompany.myextension");
    port.onMessage.addListener(onNativeMessage);
    port.onDisconnect.addListener(onDisconnected);
});
```

**Expected behavior**
1. Disabling/uninstalling an extension should disconnect its native messaging ports (resulting in native application graceful exit) or at least send an event to the extension where such cleanup is possible.
2. Chrome not crashing if the native application terminates for external reasons.
2. It would be nice to have a place where to save ports if we need to extend their lifetime over the lifetime of a service worker or content scripts 

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome Versione 89.0.4389.90 (Build ufficiale) (a 64 bit)

**Additional context**
We temporarily solved switching back to MV2 extension.

**Comment by dotproto** [comment]
This repository is for [developer.chrome.com](https://developer.chrome.com). Please use https://crbug.com/new to file a bug report on the Chromium project.
