### ISSUE TITLE
Update apple-touch-icon site with manifest.json support

### ISSUE THREAD

**Issue by AaronForinton** [GoogleChrome/developer.chrome.com#5594]
(( Originally raised at https://github.com/GoogleChrome/web.dev/issues/8306 ))

@andylib93 

### What page(s) need to be updated?
[/apple-touch-icon](https://web.dev/apple-touch-icon/)

### Why is this update needed?
Safari on iOS now supports the `"icons": []` attribute in the `manifest.json` file. And given the fact that the lighthouse audit will no longer be present in verison 10.0 as mentioned [here](https://github.com/GoogleChrome/lighthouse/issues/11458#issuecomment-1074670276), I guess the site should be updated in some sort of way. The `apple-touch-icon` can still be used though as explained in their blog.

https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/
https://caniuse.com/mdn-html_manifest_icons

**Comment by AaronForinton** [comment]
cc @adamraine @brendankenny @paulirish

**Comment by paulirish** [comment]
Yup. You did a great job at capturing this one.

We've never really formalized a policy for what we do with the docs when we remove an audit. We wont be linking to it so it'll get less traffic but..

1) we should update the nav within the site to make sure it isn't linked any longer
2) I agree some text updates make sense. "This audit used to xxx. It is no longer necessary as Safari now xxxx"

**Comment by AaronForinton** [comment]
@rachelandrew I know there are deprecations elsewhere on dcc. What's the usual course of action in terms of text updates/nav?

@paulirish This was a community issue originally raised by @andylib93 which I've moved over here from the web.dev repo, since the content itself has since moved over here.
