### ISSUE TITLE
Manifest V3/V2 timeline clarification

### ISSUE THREAD

**Issue by kospl** [GoogleChrome/developer.chrome.com#56]
**Describe the bug**
Documentation mentions some manifest V3, but it's not clear what's status of this new version, and what's the timeline of it's implementation in Chrome. Following that, it's not clear what's timeline of V2 deprecation (this is most important date all developers need to know).

**Comment by dotproto** [comment]
In the current doc set state that "Manifest V3 is available beginning with Chrome 88, and the Chrome Web Store begins accepting MV3 extensions in January 2021" in the [mv3-overview](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/). The old site [had a table](https://web.archive.org/web/20201130053006/https://developer.chrome.com/extensions/migrating_to_manifest_v3#timeline) that outlined notable migration milestones. @awfuchs, do you recall why removed this table?

**Comment by dotproto** [comment]
Closing this out as it's an old issue with no discussion in ~2 months. We will be sharing a fuller timeline in a future update.

**Comment by danielcaldas** [comment]
Hi @dotproto, V3 signifies a great deal of change for a lot of extensions. This work needs to be planned against other stuff that developers might want to do. A timeline for deprecating V2 is critical, in my opinion, and your team should if highlight these timeline details in the migration documentation.

**Comment by anubhavmalik** [comment]
Completely agreed with Daniel. A timeline is absolutely necessary given the amount of breaking changes that V3 brings.

**Comment by Psoffie009** [comment]
> **Describe the bug**
> Documentation mentions some manifest V3, but it's not clear what's status of this new version, and what's the timeline of it's implementation in Chrome. Following that, it's not clear what's timeline of V2 deprecation (this is most important date all developers need to know).

**Comment by Psoffie009** [comment]
> In the current doc set state that "Manifest V3 is available beginning with Chrome 88, and the Chrome Web Store begins accepting MV3 extensions in January 2021" in the [mv3-overview](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/). This is the only migration timeline information I recall that the current site has. The old site [had a table](https://web.archive.org/web/20201130053006/https://developer.chrome.com/extensions/migrating_to_manifest_v3#timeline) that outlined notable migration milestones. @awfuchs, do you recall why removed this table?

**Comment by lucastex** [comment]
Hi guys, will Google Chrome make a timeline available to disable Chrome V2 support? We have some extesions using Manifest V2, and need to know when it will be discontinued, so we can plan our migration.

**Comment by twigs67** [comment]
Any update on this as to when V2 will be officially deprecated? @kospl  @lucastex @dotproto

**Comment by samthor** [comment]
Please see this blog post: https://developer.chrome.com/blog/mv2-transition/
