### ISSUE TITLE
Keyboard lock demo fail

### ISSUE THREAD

**Issue by AaronForinton** [GoogleChrome/developer.chrome.com#5611]
(( Copied from https://github.com/GoogleChrome/web.dev/issues/7630 due to article migration ))

**Describe the bug**
The [demo in the keyboard lock article](https://web.dev/keyboard-lock/#demo) fails.

**To Reproduce**
1. Go to [this page](https://web.dev/keyboard-lock/#demo) and open DevTools.
2. Click 'Enter full screen'. 

The following message appears in the console: "Blocked opening 'https://keyboard-lock.glitch.me/' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set."

**Expected behavior**
The glitch opens in a new window.

**Comment by albajarazeth** [comment]
Okay I'll work on it here now, thanks!

**Comment by albajarazeth** [comment]
I made a pull request with a demo proposal. However if there is a better approach please let me know, thanks.
