### ISSUE TITLE
Disable language-specific approver if post is draft

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#5614]
**Is your feature request related to a problem? Please describe.**
Every month, I will create a base documentation for translation (see #5603) These document has status `draft:true` because it's a template for translators to start working on them. 

It would be great if we only require only one DevRel approver instead of getting approve from multiple language specfic approver, which is unnecessary in this case.

**Describe the solution you'd like**
Disable language-specific approver if post is draft

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
