### ISSUE TITLE
Render descriptions for enum values in extension documentation

### ISSUE THREAD

**Issue by oliverdunk** [GoogleChrome/developer.chrome.com#5619]
**Is your feature request related to a problem? Please describe.**

When viewing an enum in the extensions docs, we currently only show the enum values ([example](https://developer.chrome.com/docs/extensions/reference/offscreen/#type-Reason)):

![image](https://user-images.githubusercontent.com/6097064/224297501-a29dbbc3-0110-49f1-8283-dbd2c10f3169.png)

**Describe the solution you'd like**

We already have detailed descriptions available in the types this output is generated from. Example:

![image](https://user-images.githubusercontent.com/6097064/224297695-11d104ba-80fb-47d7-9d4a-f07149d38b45.png)

We should make sure to render these.

**Describe alternatives you've considered**

We may need to change the types workflow to make this easier on the 11ty side. I'm happy to help with that.

**Additional context**

https://github.com/GoogleChrome/developer.chrome.com/issues/4788

**Comment by jpmedley** [comment]
Any idea how many enums we have? I'd like to review this text before we make it all public. I need to figure out how much time that will take.

**Comment by oliverdunk** [comment]
@jpmedley There are 189 enums, although only a small number have descriptions (I haven't found out how many yet).

**Comment by jpmedley** [comment]
A small number makes this manageable. We can code the rendering to NOT add a blank line if there's no description. I will edit the few we have. Keep an eye our for Chromium PRs.

**Comment by mollietokyo** [comment]
Hey @matthiasrohmer is this one staying with you?
