### ISSUE TITLE
Document bug: `_execute_action` in `commands.getAll()`

### ISSUE THREAD

**Issue by hanguokai** [GoogleChrome/developer.chrome.com#5643]
**Describe the bug**
<img width="792" alt="Screenshot 2023-03-13 at 16 49 58" src="https://user-images.githubusercontent.com/776467/224652268-3474f31d-b964-4a6d-b992-c61a1c6d525d.png">

Above statements in https://developer.chrome.com/docs/extensions/reference/commands/ is not correct.

In MV2, `commands.getAll()` returns `_execute_browser_action` and `_execute_page_action` commands.

In MV3, it is a bug that it didn't return `_execute_action` command. The bug was fixed in Chrome 110. So since Chrome 110, `commands.getAll()` returns `_execute_action` command.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311295603
