### ISSUE TITLE
Broken links for individual scores URLs on Google Lighthouse documentation

### ISSUE THREAD

**Issue by Miliviu** [GoogleChrome/developer.chrome.com#5644]
**Describe the bug**
Broken links for individual scores URLs on https://developer.chrome.com/docs/lighthouse/performance/performance-scoring/

**To Reproduce**
1. Go to https://developer.chrome.com/docs/lighthouse/performance/performance-scoring/
2. Click on any of the individual scores URLs (for example: https://developer.chrome.com/first-contentful-paint/)
3. See error page with 404 status

**Expected behavior**
Clicking on individual scores URLs should redirect to the corresponding page with the correct URL (for example: https://developer.chrome.com/docs/lighthouse/performance/first-contentful-paint/)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
The issue affects the navigation to individual scores URLs on the website.

**Comment by Stronshade** [comment]
Can I work on this issue?

**Comment by Miliviu** [comment]
Sure! I was going to do it in a few days after work, but feel free to fix it :)
