### ISSUE TITLE
Improve documents: [content scripts] dynamic declarations with dynamic host permissions

### ISSUE THREAD

**Issue by hanguokai** [GoogleChrome/developer.chrome.com#5645]
Related documents that need to be improved:

- https://developer.chrome.com/docs/extensions/mv3/content_scripts/#dynamic-declarative
- https://developer.chrome.com/docs/extensions/reference/scripting/#method-registerContentScripts

See this discussion: [scripting.registerContentScripts() when there are no host permissions](https://github.com/w3c/webextensions/issues/356)

There are documents about "Inject content scripts with dynamic declarations". But the doc doesn't say the relationship between `registerContentScripts()` and host permissions. In fact, if there is no host permissions, `registerContentScripts()` still execute successfully, but no content scripts will be injected to pages. Therefore, to use dynamic declarations correctly, it needs to cooperate with `chrome.permissions.contains()` and `chrome.permissions.request()`.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/311090117
