### ISSUE TITLE
Implement layout for Deprecations Calendar

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#5646]
Follow-up to https://github.com/GoogleChrome/developer.chrome.com/issues/5210.

Implement the layout for the new Deprecations Calendar, following the design in Figma, using static, inline dummy data for the table rows.

The implementation should follow the other special pages like the events or fugu-showcase page.

**Comment by simgobb** [comment]
Filter component in progress. Matthias to get started with a sample one in order to get the overall structure right.

**Comment by simgobb** [comment]
Consolidated the Filters as web component approach and went through a round of feedback. Just last few bits of polishing needed. 

Ready to get the data PR merged in order to add actual data to the layout and get everything ready for review.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
