### ISSUE TITLE
Design margin notes to provide context on new terms

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/developer.chrome.com#5653]
The Privacy Sandbox has a large [glossary](https://developer.chrome.com/docs/privacy-sandbox/glossary/) that has many terms new to our developers. In many of our docs, we re-introduce these terms in context or `key-term` asides. It would be very beneficial to have a tooltip mechanism to allow for optional learning and fewer repeated definitions. Our glossary is already made from partials to transition as easily as possible.

The Help Center offers such an option ([example](https://user-images.githubusercontent.com/12857772/225372243-8a419565-0843-48fc-9ab7-6865f829974d.png)), although I'm unsure if this design is fully accessible.

The data we need associated with tooltip:

* Key term, such as "aggregatable reports"
* Partial string, such as `{% Partial 'privacy-sandbox/glossary-entries/aggregatable-reports.njk' %}`
* {Optional} Learn more link that goes to more documentation about the topic. Only some entries will benefit from this option.

Some guides on accessible tooltips:

* https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/
* https://sarahmhigley.com/writing/tooltips-in-wcag-21/

**Comment by heyawhite** [comment]
FYI @nancymic2 @kevinkiklee @rowan-m @rachelandrew, in case I've missed anything or there are any concerns.

**Comment by matthiasrohmer** [comment]
Publicly accessible version of the help center screenshot: 

<img width="475" alt="image" src="https://user-images.githubusercontent.com/12857772/225372243-8a419565-0843-48fc-9ab7-6865f829974d.png">

Visit https://support.google.com/admanager/answer/7067054?hl=en and hover over `traditional`.

**Comment by kevinkiklee** [comment]
So, I've actually started some work on this awhile back on a learning friday, and created a barely-working prototype here: https://github.com/GoogleChrome/dcc-private/pull/605

Maybe the prototype code can be helpful in the design/implementation later, or can even expand from this code.

**Comment by matthiasrohmer** [comment]
Chatted with @devnook and @rachelandrew about this. For accessibility reasons we do not want to introduce tooltips to the site, but instead focus on enabling margin notes, like so: https://gwern.net/sidenote

Or even more elaborated, for example rich-text based and color coded like in an example provided by Ewa: 
![image](https://user-images.githubusercontent.com/12857772/232050807-fe6f15ef-58b0-42e5-b5d7-789e82e290b3.png)

**Comment by heyawhite** [comment]
LOVE the idea of margin notes! Yes, very excited

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
