### ISSUE TITLE
[Design request] Condense large number of authors

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/developer.chrome.com#5662]
Example article: https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting/chrome-shipping/

![Three authors for a doc](https://user-images.githubusercontent.com/2766281/224818030-55cdd5f4-1abf-4a4e-b889-77a66c58dfad.png)

When there are more than two authors, the space the author section takes up can grow substantially. Three is fairly common, though I've seen as many as four or five authors on a single article.

Ideally, there's a "condensed design" when the authors exceed 2.

### Possible solutions

* Move the author section to the bottom of the post.
* Make the grid 3 columns and reduce margins
* Drop the social links
* Drop the "descriptions" from authors so it's just name, image, social
* Drop descriptions AND social.

Another, larger solution could be to create writing standards for what those "descriptions" are. No more than 4 or 5 words, ideally 2 ("Product Manager" and not "Product Manager, Google Chrome", and definitely not "Product Manager for the Privacy Sandbox, security, privacy, and other things too").

That could mean all existing descriptions are left as-is and a new datapoint is created for short descriptions.

**Comment by EduardoMtz1** [comment]
I think the best way to solve it is to make the grid 3 columns, and reduce the gap between the authors and the font-size, so that it keeps all the information.
Can I give it a try to solve the issue?

**Comment by matthiasrohmer** [comment]
@EduardoMtz1, thanks for taking this on in https://github.com/GoogleChrome/developer.chrome.com/pull/5713#issue-1628669494. I think your attempt looks fairly crunched, especially on smaller devices. Passing this on to our design team for a proper mock layout.

**Comment by matthiasrohmer** [comment]
Design ready, implementation will follow in #6009.
