### ISSUE TITLE
content: Update Compute Pressure API content

### ISSUE THREAD

**Issue by arskama** [GoogleChrome/developer.chrome.com#5681]
### Content proposal form for contributors who don't have access to Googlers

Fill out this section ONLY if you want to contribute new content to developer.chrome.com but don't have access to
Googlers.

#### Provide a brief title for your content proposal

Update Compute Pressure API content

#### Provide a brief summary of your content proposal

Since the last time the page was updated, the OT was completed and the feature has been fully redesigned.
The "ownership" of the feature was transferred from Google to Intel and the API was fully redesign.

#### What content already exists on this topic?

w3c design review: https://github.com/w3ctag/design-reviews/issues/795
specifications: https://w3c.github.io/compute-pressure/
explainer: https://github.com/w3c/compute-pressure
article (which I want to update): https://developer.chrome.com/docs/web-platform/compute-pressure/

#### Who will be authoring the content?
@kenchris
@arskama

#### Are there any stakeholders who should be informed when this content changes?

@thomasthedane
@beaufortfrancois
@anssiko
@tomayac (maybe)

#### What area is your content related to?

PWAs/Capabilities, Performance, Other

#### What kind of content are you creating?
Updating the existing article.
https://developer.chrome.com/docs/web-platform/compute-pressure/
No drastic change on the layout, but update on examples, text, and security and privacy.

**Comment by tomayac** [comment]
Thanks for filing the Issue. Please go ahead with a PR, I’m happy to review it.

**Comment by rachelandrew** [comment]
@arskama if this is a complete rewrite rather than a few updates, please do that in a Google doc first rather than making a PR. We can't review content effectively on GitHub.

The existing content was an old article we relocated from web.dev. With the documentation in this section the aim is to put together content that can ultimately be moved to MDN once features ship into stable. We don't want to become the home of canonical web platform documentation. [More information here](https://developer.chrome.com/docs/handbook/web-platform/).

Thank you!

**Comment by tomayac** [comment]
Sorry, skimmed over the “fully redesigned” part. I thought this was an update of just a few sections. Still happy to review the Google doc from a technical perspective.

**Comment by arskama** [comment]
@rachelandrew @tomayac,  thanks for the guidance. I ll follow it.
I thought that it would be a good idea to finally update the existing documentation available on the web before we try to go OT, promote Compute Pressure API and make it more visible to the outside world.

**Comment by beaufortfrancois** [comment]
I'm also happy to review this doc as I've been reviewing Chromium CLs for the Compute Pressure API.

**Comment by arskama** [comment]
@beaufortfrancois @tomayac @rachelandrew 

Hello, I didn't make an official PR out of it, since it was preferred to review it first, but below is what I wrote, based on the guidance you gave and looking at some existing recent docs. Please take a look and let me know how it can be improve to push it to the repo. Thanks in advance.

https://github.com/arskama/developer.chrome.com/commit/242a1b86246093df932f1926ee53cc16ceb35295

The idea would to release also a blog post when/(if) we reach OT. We are working on it and hoping to send the I2E email at beginning of Q2.

**Comment by arskama** [comment]
@tomayac , Thanks for the migration. I can access it.
Sorry I didn't understand the importance of the document format, until I read @rachelandrew s comment again. ("We can't review content effectively on GitHub")

**Comment by rachelandrew** [comment]
Thanks both, I'll take a look at the doc.

**Comment by arskama** [comment]
@rachelandrew Thanks for having a look and fixing the text, I just noticed.
I ll make the changes requested and ping you again.

**Comment by arskama** [comment]
@rachelandrew I addressed your comments.
@beaufortfrancois please feel free to have also a look.

**Comment by rachelandrew** [comment]
@arskama @beaufortfrancois I'm happy with this if you want to make a PR. Please assign it to me when you do.

**Comment by beaufortfrancois** [comment]
I've reviewed https://github.com/GoogleChrome/developer.chrome.com/pull/5887.

**Comment by arskama** [comment]
Thank you for your time! @beaufortfrancois
