### ISSUE TITLE
Unable to navigate to Content Scripts tab present in Source Tab by clicking double right arrow icon

### ISSUE THREAD

**Issue by Badrri-Narayanan** [GoogleChrome/developer.chrome.com#5694]
**Describe the bug**
When I go to Source tab and then to Content Script tab to view my content script for a custom chrome extension I am developing, I am unable to navigate to Content Script tab using the double right arrow icon. But when I expand the panel and make all the tabs visible, I can switch to Content Script tab.

**To Reproduce**
1. Go to Source tab
2. Use the double right arrow icon and choose Content Scripts
3. It won't work.
4.  Now, try expanding the panel to make all the tabs visible. If you switch now, it works!

**Expected behavior**
When I click on the double arrow icon and choose Content Scripts, it should make Content Script tab visible.

**Screenshots**
The issue
![image](https://user-images.githubusercontent.com/26011119/225363579-0d8e1eb7-c724-44f4-a931-c1974ebec3e7.png)
current workaround
![image](https://user-images.githubusercontent.com/26011119/225364495-2b133787-6ec3-4a47-9a0c-3cb73ce368a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 111.0.5563.65 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - haven't tried reproducing it in Smartphone

**Additional context**
none

**Comment by patrickkettner** [comment]
Hi @Badrri-Narayanan!
I am not sure I understand fully - can you explain what you mean when you say "it won't work"? What OS and chrome version are you on?

**Comment by Badrri-Narayanan** [comment]
Hi @patrickkettner 
By "it won't work", I meant that within the source tab, it doesn't switch over to "Content Scripts" tab and it will stay in the "Page"  tab. The OS I am using is windows 10 and my chrome version is Version 111.0.5563.65 (Official Build) (64-bit). I hope this helps!

**Comment by patrickkettner** [comment]
Gotcha, thank you!
This is a repo for documentation related stuff, so unfortunately it isn't the place for this kind of issue. You would want to search for/open-if-new issues at [https://crbug.com](https://crbug.com). I would _highly_ suggest recording a video to show the issue, if at all possible.
