### ISSUE TITLE
chrome.fileSystem is a Chrome Apps API, therefore noted as deprecated

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#57]
this page:
https://developer.chrome.com/docs/extensions/reference/fileSystem/

has this banner:
> Warning
> This API is part of the deprecated Chrome Apps platform. Learn more about migrating your app.

that is incorrect.  the FSP extension APIs will be living longer than the Chrome Apps code.

**Comment by samthor** [comment]
Updated the title a bit. This is technically still a Chrome Apps API according to the Chromium source, so we are reporting it this way.

**Comment by robdodson** [comment]
Should we keep this ticket open or close it?

**Comment by samthor** [comment]
I'm going to close this. Until [this file](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/extensions/common/api/_permission_features.json#265) is updated to say that this API works on extensions, what we're showing is completely valid. cc @rdcronin
