### ISSUE TITLE
chrome.permissions.request opens prompt in non-focused window

### ISSUE THREAD

**Issue by jlabedzki** [GoogleChrome/developer.chrome.com#5721]
**Describe the bug**
I am developing a chrome extension where sometimes I need to use the `chrome.permissions` API to request certain permissions from my users. If the user has multiple chrome windows open, the prompt that chrome.permissions.request opens will open in a non-focused window every single time. I've tried wrapping the request call in `chrome.windows.getCurrent` as well as chrome.windows.getLastFocused` but nothing seems to work.

**Expected behavior**
When a user is using my chrome extension and I need to use the request method from the `chrome.permissions` API, the prompt should open in the same window that the user is using the extension in.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version 111

**Comment by Jad4ever** [comment]
I'm on android

**Comment by Jad4ever** [comment]
All tabs closed

**Comment by dstmarthe** [comment]
Thanks for raising this. We're moving to a new platform and migrating issues. This repo is for d.c.c content issues, so I will have to close this. For help with Chrome extensions, see the resources we recommend at: https://developer.chrome.com/docs/extensions/support-feedback/getHelp/#for-extensions-development
