### ISSUE TITLE
code scope identifiers on code blocks of extensions docs

### ISSUE THREAD

**Issue by arnav-kr** [GoogleChrome/developer.chrome.com#5728]
**Is your feature request related to a problem? Please describe.**
Currently, this a typical code block on the extensions docs. 

<img width="562" alt="Current Code Blocks" src="https://user-images.githubusercontent.com/72879799/226329195-c03fca10-bf24-401f-b6b1-4e0cc60c5d6e.png">

There is no context about where the code is supposed to run, in content scripts or service worker scope or directly on page's scope.
I know people can infer from the code. but still for convenience, it would be useful if there were some identifier for thsoe

**Describe the solution you'd like**
Adding a small chip on top right or anywhere on the code block as an identifier to show the scope in which the code is supposed to run
for example:
`cs` for content scripts
`sw` for service worker scope
`page` for the script that is injected and directly run into page

It could looks something like this in production. Could use the short forms only with maybe a tooltip or use combination of both short and long on hover.
![Prototype 1](https://user-images.githubusercontent.com/72879799/226332967-e95615c5-c731-4f68-9388-cd90cb6fdb6b.png)
![Prototype 2](https://user-images.githubusercontent.com/72879799/226332999-b8a770ab-06fc-4e5b-b1cf-a0300887fc3f.png)

Just a simple suggestion from my side.

**Comment by AmySteam** [comment]
Related PRs:

#5767, #5764,

@IanStanion-google, can you add your PR's as a comment to this issue so we can keep track of our progress?

**Comment by IanStanion-google** [comment]
Related PRs: #5770

**Comment by IanStanion-google** [comment]
Hi Amy!

Can you send me the next 3 for me to work on? I intended to have my final
ready before today, but my grandfather's health went downhill a bit and I
was a bit distracted. If you let me know what my next batch is for this
week I can work on all of them today though, so no time lost!
