### ISSUE TITLE
Chrome Extension Dev Guide page Omnibox link is broken

### ISSUE THREAD

**Issue by lukegeor** [GoogleChrome/developer.chrome.com#5733]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The link to the Omnibox page from https://developer.chrome.com/docs/extensions/mv3/devguide/ has an incorrect link. It points to https://developer.chrome.com/docs/extensions/reference/omnibox%22%3EOmnibox/ when it should point to https://developer.chrome.com/docs/extensions/reference/omnibox.

**To Reproduce**
1. Navigate to https://developer.chrome.com/docs/extensions/mv3/devguide/
2. Click on "Omnibox"
3. Get a 404 error

**Expected behavior**
Link should navigate you to the correct page, https://developer.chrome.com/docs/extensions/reference/omnibox

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 111.0.5563.65

**Comment by AmySteam** [comment]
@lukegeor Thanks for letting us know! 🙂 I just a PR to fix this 👍
