### ISSUE TITLE
Broken Image on Inspect Network Activity Demo

### ISSUE THREAD

**Issue by kchavez05** [GoogleChrome/developer.chrome.com#5746]
Platforms: All supported
Environment: Prod

Steps to Reproduce:
1. Navigate to https://devtools.glitch.me/network/getstarted.html
2. Observe image link endpoint returns 404

Expected Results: Image link would be valid
Screenshot: https://share.getcloudapp.com/8Luqr779

**Comment by AaronForinton** [comment]
@sofiayem The link in the demo also doesn't work. Who can edit this Glitch?

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311276508
