### ISSUE TITLE
Links from MV2 docs to MV3 docs are not specific enough

### ISSUE THREAD

**Issue by cashpipeplusplus** [GoogleChrome/developer.chrome.com#576]
**Describe the bug**
Links from MV2 docs to MV3 should ideally link to a corresponding MV3 doc.  For example, the [manifest format doc for MV2](https://developer.chrome.com/docs/extensions/mv2/manifest/) should link to the [corresponding doc for MV3](https://developer.chrome.com/docs/extensions/mv3/manifest/), not [the general overview of MV3](https://developer.chrome.com/docs/extensions/mv3/intro/) as it does today.

**Expected behavior**
It would be nice if someone could audit all of the links to https://developer.chrome.com/docs/extensions/mv3/intro/ and replace them with more helpful links to the correct docs.

**Comment by AmySteam** [comment]
Fixed in #6872
