### ISSUE TITLE
"Sending a request from the extension to a content script" is vague

### ISSUE THREAD

**Issue by mikemaccana** [GoogleChrome/developer.chrome.com#5778]
**Describe the bug**
From https://developer.chrome.com/docs/extensions/mv3/messaging/#simple

> Sending a request from the extension to a content script is similar, except that you need to specify which tab to send it to. 

This sentence is vague - one cannot write code in 'an extension', but rather its individual components. I am guessing possible meaning for this sentence:

 - "Sending a message from the service worker to a content script"
 - "Sending a message from the popup to a content script" 

(Also using the term 'message' per other google docs and the APIs themselves)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324155748
