### ISSUE TITLE
Formatting for {% Label %} shortcode

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#5785]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
This site has a `Label` shortcode, which the extensions team uses for labeling code samples. (Extensions have distinctive types of js files, which requires samples to be labeled for clarity.) As you can see from the image below, the labels blend too much with the text they introduce. Currently, we use ad-hoc ways of improving this, specifically adding an extra line after the shortcode and ending the label text with a colon. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8204171/227377836-e1945947-295d-4fde-b7f5-8733e82d6e01.png)

**Solution**
Find a way to format these that doesn't disappear into the text that follows.

**Comment by AmySteam** [comment]
If you follow the spacing suggested in the handbook, it works fine. One line in between the label and the code sample. 

https://developer.chrome.com/docs/handbook/components/#labels

<img width="780" alt="Screenshot 2023-03-23 at 18 07 24" src="https://user-images.githubusercontent.com/37001393/227384078-97bfd6a0-6ea4-4128-a95a-75198d6517ed.png">

<img width="742" alt="Screenshot 2023-03-23 at 18 07 49" src="https://user-images.githubusercontent.com/37001393/227384106-6fcd39e9-517a-4e16-acfe-9930b57851c8.png">

**Comment by rachelandrew** [comment]
Yes, I think that's just the markdown parser, add the spacing as recommended.

**Comment by rachelandrew** [comment]
To fix your immediate issue, just add the spacing. Infra might be able to look at it at some point, but I wouldn't make it a priority as we can do what's needed.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
