### ISSUE TITLE
Background scripts Documentation contains Curly Quotation marks

### ISSUE THREAD

**Issue by Prid13** [GoogleChrome/developer.chrome.com#58]
Sample code in docs contains **_curly_ double quotation marks** `“`,`”`/`&ldquo;`, instead of straight quotation marks `"`, like the rest of the samples on that page!

#### Where?
- Page: **["Manage events with background scripts"](https://developer.chrome.com/docs/extensions/mv2/background_pages/)** --> sub-section: **["React to listeners"](https://developer.chrome.com/docs/extensions/mv2/background_pages/#react)**

 - Link: https://developer.chrome.com/docs/extensions/mv2/background_pages/#react

#### Who cares?
I copied and pasted the code directly into Notepad++ and kept getting an error in Chrome about invalid token.<br>Would be nice to prevent others from scratching their heads for a few minutes :)

![chrome docs code](https://user-images.githubusercontent.com/27897747/102000645-ca0f9f00-3ce9-11eb-999d-0ed1d93aaef9.jpg)

**Comment by samthor** [comment]
Ah, thanks for reporting! In the migration we must have missed or accidentally added these.

We'll also add a PRESUBMIT so these don't accidentally get reintroduced once we've removed all of the smart quotes. (This is what Google does for our other documentation sites.)

**Comment by samthor** [comment]
We have 340 violations of the Smart Quotes rules :'(
