### ISSUE TITLE
filename in chrome.downloads.download doesn't work

### ISSUE THREAD

**Issue by xiedeacc** [GoogleChrome/developer.chrome.com#580]
I have a Chrome extension that uses chrome.downloads.download() to download a file, but specified filename not working, 
example:
url:https://git.github.com/user/repo/raw/master/src/content/file.js
filename:master/src/content/file.js
but file.js was downloaded as file.txt, chrome api refered url MIME type? but I don't know how to set MIME type;

below was my download code:

`chrome.runtime.onMessage.addListener(function(request, sender, sendResponse)
{
	sendResponse('I am background, I have recevied your message：' + request.url);
    console.log('now download file: ' + request.filename); 
    chrome.downloads.download({url:request.url, filename:request.filename},function(downloadId){
        console.log("download begin, the downId is:" + downloadId);
    });
});`

**Comment by dotproto** [comment]
This issue appears to describe a Chrome bug rather than a bug report or feature request for the chrome-extensions-samples repository. Please visit https://crbug.com/new to file a bug report.
