### ISSUE TITLE
Chrome Reference Pages URL is Case Sensitive

### ISSUE THREAD

**Issue by AmySteam** [GoogleChrome/developer.chrome.com#5805]
## Problem
Currently, when accessing Chrome reference pages, the URLs are case sensitive. This means that if a user types a URL with different letter case, the page will not be accessible. For example, accessing https://developer.chrome.com/docs/extensions/reference/topSites works, but not https://developer.chrome.com/docs/extensions/reference/topsites.

It would be convenient for developers if the URLs were not case sensitive. This would allow for easier access to the pages without having to remember the exact letter case used in the URL.

## Steps to Reproduce:

1. Type in the URL https://developer.chrome.com/docs/extensions/reference/topsites in the browser
2. The page is not accessible and results in a 404 error.

**Expected Result:**

The URL should not be case sensitive and both https://developer.chrome.com/docs/extensions/reference/topSites and https://developer.chrome.com/docs/extensions/reference/topsites should lead to the same page.

**Actual Result**:

The URL is case sensitive and only https://developer.chrome.com/docs/extensions/reference/topSites is accessible.

## Additional Information:

This issue affects all developers accessing Chrome reference pages and can cause confusion and frustration when trying to access specific pages.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS, where this likely won't be an issue.
