### ISSUE TITLE
Implement navigation buttons at the end of the pages

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#5809]
Implementation follow-up for https://github.com/GoogleChrome/developer.chrome.com/issues/5633. Carefully consider where this feature makes sense apart from blog articles.

**Comment by nhaan01** [comment]
Vào 04:49 PM, T.2, 27 Th3, 2023 Matthias Rohmer ***@***.***>
đã viết:

**Comment by simgobb** [comment]
UI implemented for both desktop and mobile. 

Already ran the idea I had to get the posts data with Matthias and got green light with that.

Next steps will be adding dynamic data and submit the new component to Dan for internal design QA.
