### ISSUE TITLE
"Verify commands registered" provides (slightly) incorrect sample code

### ISSUE THREAD

**Issue by bsilverthorn** [GoogleChrome/developer.chrome.com#5815]
**Describe the Bug**

Chrome documentation provides a helpful snippet under ["Verify commands registered"](https://developer.chrome.com/docs/extensions/reference/commands/#verify-commands-registered):

```javascript
chrome.runtime.onInstalled.addListener((reason) => {
  if (reason === chrome.runtime.OnInstalledReason.INSTALL) {
    checkCommandShortcuts();
  }
});
```

However, it's not quite correct. The `onInstalled` [event](https://developer.chrome.com/docs/extensions/reference/runtime/#event-onInstalled) provides a `details` object with a `reason` property, rather than providing a `reason` value directly. The corrected snippet might look like this:

```javascript
chrome.runtime.onInstalled.addListener((details) => {
  if (details.reason === chrome.runtime.OnInstalledReason.INSTALL) {
    checkCommandShortcuts();
  }
});
```

**To Reproduce**

1. Tweak the original snippet to report the callback argument, e.g.:

```javascript
chrome.runtime.onInstalled.addListener((reason) => {
  if (reason === chrome.runtime.OnInstalledReason.INSTALL) {
    console.log('install event');
  }
  else {
    console.log('other event', reason);
  }
});
```

2. Include the modified snippet in a Chrome extension.
3. Install the extension.
4. Check the extension console output.

**Expected Behavior**

Extension installation should be understood as an install event.

**Desktop**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: 111.0.5563.64 (Official Build) (64-bit)

**Comment by bsilverthorn** [comment]
One other small bug in the same section: the docs state that

> _execute_action will not appear in the list of commands returned by commands.getAll().

but that isn't consistent with observed behavior. (I _do_ see `_execute_action` returned.)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311099431
