### ISSUE TITLE
Fix memory problems is way out of date

### ISSUE THREAD

**Issue by randomascii** [GoogleChrome/developer.chrome.com#5820]
**Describe the bug**
The "Fix memory problems" article at https://developer.chrome.com/docs/devtools/memory-problems/ is way out of date. It showed up second in a search for how to track memory leaks in Chrome but it is too out of date to be usable. In particular it refers to a Profiles panel and that panel no longer exists.

**To Reproduce**
1. Open DevTools (F12)
2. Look for a Profiles Panel
3. Go to the Memory panel and look for Record Allocation Timeline
4. Note that https://developer.chrome.com/docs/devtools/memory-problems/ mentions the Profiles Panel and Record Allocation Timeline

**Expected behavior**
The documented tools should exist

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - Chrome
 - Version Version 111.0.5563.111 (Official Build) (64-bit)

If there is an updated article then this article should include a link to the updated one and should probably have its obsolete content deleted.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311095569
