### ISSUE TITLE
Exercises not showing up

### ISSUE THREAD

**Issue by martino2436** [GoogleChrome/developer.chrome.com#584]
Hi there,

The CSS tutorial is not working properly. The elements to select such as 'Inspect Me!' or `Add background color` are not showing up.

Could you please check or advise on the issue?

Thanks,
Martin

**Comment by martino2436** [comment]
All good, thanks.

**Comment by kostasx** [comment]
The elements are still not showing. How did you manage to find a solution @martino2436 ?
