### ISSUE TITLE
Typescript needs updating

### ISSUE THREAD

**Issue by johnrich85** [GoogleChrome/developer.chrome.com#5841]
The current version of typescript does not contain the correct definitions for HTMLDialogElement. 

To reproduce the issue:

- Open `/site/_js/events.js`
- Remove the `// @ts-ignore` declarations related to showModal() and close() 

According to [this comment](https://stackoverflow.com/a/74074649) the issue is fixed as of 4.8.3

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
