### ISSUE TITLE
It should be possible to share/link to events and filtered lists of events

### ISSUE THREAD

**Issue by johnrich85** [GoogleChrome/developer.chrome.com#5842]
Roughly speaking the requirements are understood to be as follows:

- User selections are to be stored in the query string
- On page load, the selections are to be parsed and applied.
- The current tab should be stored as well as the filters
- It should be possible to link directly to a specific event

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
