### ISSUE TITLE
Damaged Links

### ISSUE THREAD

**Issue by Jemeni11** [GoogleChrome/developer.chrome.com#5846]
**Describe the bug**
There are two damaged links in the [Stable APIs table](https://developer.chrome.com/docs/extensions/reference/#stable_apis) of the [API Reference page](https://developer.chrome.com/docs/extensions/reference/).

**To Reproduce**
1. Go to the [Stable APIs table](https://developer.chrome.com/docs/extensions/reference/#stable_apis) located on the [API Reference page](https://developer.chrome.com/docs/extensions/reference/)
2. Scroll down to the `tts` and the `ttsEngine` fields of the table.
3. See the damaged links.

**Screenshots**
![chrome docs error](https://user-images.githubusercontent.com/52603291/228566701-bb2ec7c6-8811-4f8d-ae28-514f77c7f8cb.png)

**Desktop (please complete the following information):**
- OS: Linux (Lubuntu 20.04)
- Browser: Microsoft Edge
- Version: Version 111.0.1661.51 (Official Build) (64-bit)

**Additional context**
> [tts](https://developer.chrome.com/docs/extensions/reference/tts)	
Use the chrome.tts API to play synthesized text-to-speech (TTS). See also the related {@link ttsEngine} API, which allows an extension to implement a speech engine.

> [ttsEngine](https://developer.chrome.com/docs/extensions/reference/ttsEngine)	
Use the chrome.ttsEngine API to implement a text-to-speech(TTS) engine using an extension. If your extension registers using this API, it will receive events containing an utterance to be spoken and other parameters when any extension or Chrome App uses the {@link tts} API to generate speech. Your extension can then use any available web technology to synthesize and output the speech, and send events back to the calling function to report the status.

**Comment by Jemeni11** [comment]
Hey @AmySteam , I just want to point out that this bug hasn't been fixed yet

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005453

**Comment by Jemeni11** [comment]
Thanks for the update! I'll keep an eye on the new tracker
