### ISSUE TITLE
Project card styling and icons broken on Safari

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#5893]
The project cards on https://developer.chrome.com/docs/ are broken for Safari 16.4 (17615.1.26.101.9, 17615) (but probably other versions too). See the following screenshots for a Chrome/Safari comparison:

**Chrome**
![developer chrome com_docs_(iPad Air)](https://user-images.githubusercontent.com/12857772/229727446-3e5f6aa6-49af-49f3-9489-96c9f9f03f5d.png)

**Safari**
<img width="964" alt="image" src="https://user-images.githubusercontent.com/12857772/229727830-b7583dcf-a2ed-4f5f-81e1-154e0e3d9b57.png">

Note that the Privacy Sandbox SVG is broken in particular and needs fixing.

**Comment by mcastillobalderas** [comment]
Instalar

**Comment by myakura** [comment]
It works as expected in Safari Technology Preview (166) so it'll be okay (hopefully) in the next few versions, I guess.
