### ISSUE TITLE
web-otp documentation: referenced demo not working

### ISSUE THREAD

**Issue by sulyok-daniel** [GoogleChrome/developer.chrome.com#5902]
In https://developer.chrome.com/articles/web-otp/ you link to a demo at https://web-otp.glitch.me/ .

The page suggests that sending an arbitary message is enough for the example to work, as long as it contains the given string in the last line:

> Send an SMS that includes
> @web-otp.glitch.me #12345
> at the last line to this phone.

That is not correct - the information is missing, that the SMS **must** also contain the code once more above this line

...as step 2 in https://developer.chrome.com/articles/web-otp/ states correctly ( partly true - the code above should be **12345** , not 123456 ):

> Send your phone the following SMS text message from the another phone.
> Your OTP is: 123456.
> 
> @web-otp.glitch.me #12345

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310269206
