### ISSUE TITLE
Android Chrome mobile malfunction with Adobe publish online document browsing.

### ISSUE THREAD

**Issue by aalve1964** [GoogleChrome/developer.chrome.com#592]
Hi there, 
   it's been more than two months  I am trying with Adobe support to solve this issue that has been existing for years and I have given up. Please note that this issue is only on Android>mobiles>chrome.

**Descibe the bug**
Although it is working fine with chrome on desktop, on mobile devices, arrow keys and control bar appear about 3-4 sec. If I click quickly on a button they are staying visible and working 9(temporary). After about 4 sec of inactivity control bar and arrows disappear and can't bring it back. The document freeze and can't browsing the document. I tried this many times and I am getting the same behavior.  

**To reproduce**
Here is a link for your mobile phone to reproduce the error the first link created as document (for pdf purposes) the second created with all digital publications in mind.
https://indd.adobe.com/view/80b7917b-13ad-40fb-89ad-9900f61b2fe7
https://indd.adobe.com/view/dfaa84d1-a59d-4d77-b41d-5b71fec71146
I am using Windows10 x64/ Indesign 16.0.1x64 to publish the document. 

**Smartphone**
My mobile is Redmi note 8. Os is MIUI Global 12.0.4 stable.
It's working fine on my mobile with Mi browser or Firefox and on Iphone but not with Android chrome.
I tried many times to: delete history, delete cookies, delete cache, uninstall/install chrome with no luck.

Expected the control bar to appear when tapping the smartphone and/or swipe to browsing pages normally , without freezing.

Any help will be much appreciated.
Could you help me please?

Links describing almost the same issue in adobe forum
https://community.adobe.com/t5/indesign/re-publish-online-problem-in-chrome/td-p/9901779
https://indesign.uservoice.com/forums/601180-adobe-indesign-bugs?query=chrome%20issue

**Comment by dotproto** [comment]
This issue appears to describe a Chrome bug rather than a bug report or feature request for the developer.chrome.com repository. Please visit https://crbug.com/new to file a bug report.
