### ISSUE TITLE
Content list in the sidebar is not localized

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#5926]
**Describe the bug**
When a localized content is displayed, some of the contents list items on the left side is not localized.

**To Reproduce**
Go to https://developer.chrome.com/ja/docs/privacy-sandbox/feedback/

**Expected behavior**
"What is the Privacy Sandbox?" is translated and displayed as "プライバシー サンドボックスとは何か？".

**Screenshots**
<img width="673" alt="Screenshot 2023-04-06 at 22 23 04" src="https://user-images.githubusercontent.com/218144/230391566-0496a960-5116-4736-93a0-7347acaeb685.png">

**Additional context**
I presume these translation are done through the combination of:
1. site/_data/docs/privacy-sandbox/toc.yml
2. site/_data/i18n/docs/privacy-sandbox.yml

So they are translated properly on https://developer.chrome.com/ja/docs/privacy-sandbox/ but the same logic does not seem to be applied to the content list of the left nav.

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
