### ISSUE TITLE
chrome.identity.launchWebAuthFlow close event closes extension window prematurely

### ISSUE THREAD

**Issue by meropis** [GoogleChrome/developer.chrome.com#5959]
**Describe the bug**
I use an interactive `chrome.identity.launchWebAuthFlow` to gain a token which is then used for API calls to the Microsoft Graph API.
The web auth flow is called from a persistent service worker (indicated properly in my manifest file). 

For a reason I cannot work out, when the web auth flow window closes and successfully starts its callback, the code execution is cut short with no error and the extension window closes too. This behaviour is not documented anywhere and my code is properly formatted with async/await to force the extension to stay open.

**To Reproduce**
1. Create a basic extension
2. Add a service worker that makes a `launchWebAuthFlow` call to any API that returns a token (and redirects to the extension properly using `chrome.identity.getRedirectURL()`) through a message listener and sends back its token to the main content script
3. Call the service worker using `sendMessage` from the main content script and await the response
4. Watch the web auth flow window close, and subsequently the extension window close

**Expected behavior**
Once the web auth window closes, the token should be sent back to the content script and the extension window should stay open for further code execution.

**Screenshots**
I'm unsure how to include screenshots of the windows closing simulataneously. I could create a gif if anyone requests it.

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser: chromium for linux
 - Version: 112.0.5615.50

**Comment by jpmedley** [comment]
Thank you for letting us know. Unfortunately, this channel is for submitting problem with developer.chrome.com, not Chrome itself, and we have no way to transfer it. Can you please help us by reposting here: https://crbug.com

Thank you.
