### ISSUE TITLE
Restore deactivating breakpoints

### ISSUE THREAD

**Issue by tpdietz** [GoogleChrome/developer.chrome.com#5990]
I would like to request that the options, 'Deactivate Breakpoint' and 'Deactivate All Breakpoints' be restored to the debugger.  They were very helpful.

Thank you.

Tim Dietz

**Comment by AaronForinton** [comment]
Hi there Tim and thanks for submitting your issue. You can still [deactivate all breakpoints using the context menu there](https://developer.chrome.com/docs/devtools/javascript/breakpoints/#manage-loc) in the DevTools debugger. If you're referring to an option that was removed in a particular version of Chrome, please let me know and I can direct you to the appropriate places.
