### ISSUE TITLE
Page describing Lighthouse audit for front-end JavaScript libraries with known security vulnerabilities is out of date

### ISSUE THREAD

**Issue by cqueern** [GoogleChrome/developer.chrome.com#5997]
Lighthouse [no longer flags](https://github.com/GoogleChrome/lighthouse/discussions/14961) front-end JavaScript libraries with known security vulnerabilities. Suggest updating [this page](https://developer.chrome.com/docs/lighthouse/best-practices/no-vulnerable-libraries/) to reflect the change.

**Comment by AaronForinton** [comment]
Thank you @cqueern. I've made sure the content is clearly labelled, but I'll wait from input on the Lighthouse side to see if there's anything more they'd like for the page.
