### ISSUE TITLE
several broken links across extension developer guides

### ISSUE THREAD

**Issue by camhashemi** [GoogleChrome/developer.chrome.com#60]
1. Go to https://developer.chrome.com/static/images/index/hello_extensions.png, which is linked from the https://developer.chrome.com/docs/extensions/mv3/overview/ page
2. see 404 error

**Expected behavior**
no 404 error, and I can download the image

**Comment by camhashemi** [comment]
same with [this link](https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/images.zip) from the [Getting Started](https://developer.chrome.com/docs/extensions/mv3/getstarted/) page

**Comment by camhashemi** [comment]
same with seemingly all links from [the Extension Development Overview page](https://developer.chrome.com/docs/extensions/mv3/devguide/)

**Comment by camhashemi** [comment]
[same here](https://developer.chrome.com/docs/extensions/declarepermissions)

**Comment by doc-han** [comment]
Adding to the list of broken links.
[https://developer.chrome.com/docs/extensions/mv2/declare_permissions/](https://developer.chrome.com/docs/extensions/mv2/declare_permissions/)

Links under the background permission description

**Comment by fabioselau077** [comment]
same problem.
Multiples links of documentation about extensions of Chrome is 404.
https://developer.chrome.com/docs/extensions/mv2/overview/

**Comment by jantaja** [comment]
Same here https://developer.chrome.com/docs/extensions/reference/declarativeContent/

**Comment by samthor** [comment]
We appreciate the reports but having one issue for many broken links is actually a pain for us to action. To resolve the initial issue, we're missing the png file which is actually still in the previous repo here; https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/docs/examples/tutorials/hello_extensions/hello_extensions.png

**Comment by Rudxain** [comment]
The CSP link is broken here: https://developer.chrome.com/docs/extensions/mv3/xhr/
Current URL: https://developer.chrome.com/docs/extensions/mv3/contentSecurityPolicy/
Correct URL: https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#content-security-policy

I made a PR that fixes the issue, I'll edit this comment to link it

**Comment by jpmedley** [comment]
It looks like all the broken links mentioned here are fixed.
