### ISSUE TITLE
Not posible to stop download in small files

### ISSUE THREAD

**Issue by jcarlosgarciaa** [GoogleChrome/developer.chrome.com#6018]
**Describe the bug**
It is not possible to stop a small file download using chrome.downloads.pause in Chrome extensión manifest version 3. It works with files bigger than 1MB aproximately, but with smaller ones the download ends before it is stopped

**To Reproduce**
Everything is explained properly here (considering the answer too): https://stackoverflow.com/questions/75997147/i-am-not-able-to-stop-a-small-file-download-with-chrome-downdloads-api-in-chrome
Please contact me to add more info if needed. I hope this link is enough to explain the issue.

**Expected behavior**
I was expecting to be able to pause every file download for after some analysis restart it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 100+

**Comment by jcarlosgarciaa** [comment]
Please contact me if more information is needed.

**Comment by AaronForinton** [comment]
Hi there @jcarlosgarciaa. Please submit your bug to the [Chromium board](https://bugs.chromium.org/p/chromium/issues/list) in order to get an answer (and a fix!) about functionality. This repository only handles issues relating to the documentation at developer.chrome.com. Thank you.
