### ISSUE TITLE
Is chrome.loginState a Chrome OS specific API?

### ISSUE THREAD

**Issue by ouweiya** [GoogleChrome/developer.chrome.com#607]
Is chrome.loginState a Chrome OS specific API?
Didn't mention in the document is a specific platform API?
A warning was generated when used in Windows.
`'loginState' is not allowed for specified platform.`

If it is a specific platform API, the documentation may be negligent.

Document link:
https://developer.chrome.com/docs/extensions/reference/loginState/#type-SessionState

**Comment by dotproto** [comment]
Per [Chromium source](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/extensions/api/_permission_features.json;l=495;drc=ba4cc4353e4048c46d51ffbbf461de1fa7fa0e79), this API is restricted to Chrome OS. 

@samthor, could you take a look at this to see why the doc page isn't noting that this API is Chrome OS only?

**Comment by samthor** [comment]
Yes, this is a mistake, and the API is only supported on Chrome OS. We'll
get to this soon.

**Comment by samthor** [comment]
This correctly reports as Chrome OS only now.
