### ISSUE TITLE
chrome.windows.update(windowId, {   drawAttention: true }); removes earlier highlighting of taskbar icon

### ISSUE THREAD

**Issue by vasudevac** [GoogleChrome/developer.chrome.com#6087]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Updating the window drawAttention property removes the earlier attention added

**To Reproduce**
Try to update the windows attention property multiple times it removes the highlighting randomly sometime odd number updates

chrome.windows.update(windowId, {   drawAttention: true });

**Expected behavior**

drawAttention should not remove any earlier attention set. It just need to blink again and highlight the taskbar icon.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [111.0.1661.41]

**Additional context**
We wanted to blink the windows taskbar icon for new notification received in chrome/edge extension. This api allows us to blink/highlight the taskbar icon for edge for new notification. It also removes any earlier highlighting added if we use multiple times.

**Comment by AaronForinton** [comment]
Hello @vasudevac. Since this is an issue related to Chromium, please redirect this query to [crbug.com](https://crbug.com/.). This GitHub repo only handles documentation issues related to [developer.chrome.com](https://developer.chrome.com/).
