### ISSUE TITLE
[nodoc] in IDL/JSON API files is not taken into account.

### ISSUE THREAD

**Issue by karan173** [GoogleChrome/developer.chrome.com#61]
When a node is marked as "nodoc" in the JSON or IDL schema file for an API, it shouldn't be visible on the site documentation. However the nodoc annotation doesn't seem to be respected currently. 

Example: See https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/api/declarative_net_request.idl. Nodes marked as [nodoc] are visible in the served documentation at https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/

**Comment by samthor** [comment]
None of the current model code considers nodoc—I guess it was never intended to generate live published data.

We'll incorporate this.
