### ISSUE TITLE
Cookie banner should not be permanently shown when JavaScript is disabled

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/developer.chrome.com#6120]
I browse the desktop web with JavaScript disabled by default (via uBlock Origin). I have noticed that the cookie banner on your website cannot be closed (see screenshot below). When I allow JavaScript, the cookie banner is not displayed. 

<img width="1280" alt="Screenshot 2023-04-26 at 14 49 15" src="https://user-images.githubusercontent.com/716405/234580041-4f53d8c9-a86b-4f65-a64e-7a05190c87a4.png">

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.
