### ISSUE TITLE
Missing platform data for input.ime extension API

### ISSUE THREAD

**Issue by oliverdunk** [GoogleChrome/developer.chrome.com#6129]
**Describe the bug**

We don't show any platform compatibility data for the input.ime extension API.

**To Reproduce**

Visit https://developer.chrome.com/docs/extensions/reference/input_ime/ and see that there is no platform data.

**Expected behavior**

It's unclear to me if this is ChromeOS only or also supported on Windows, but it definitely doesn't work on macOS.

**Additional context**

In the [chrome-types](https://unpkg.com/chrome-types@0.1.188/index.d.ts) package we have data showing that it works on Chrome OS, Windows and Linux but our docs don't currently supporting showing that.

We could fix that, but we should first see if that is even right.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/311438151
