### ISSUE TITLE
Support RSS feed by tags

### ISSUE THREAD

**Issue by chybie** [GoogleChrome/developer.chrome.com#613]
Should we should support RSS feed by tag? For example, users might be interested in `New in Chrome` blog posts but not others. @robdodson @samthor 

**Additional context**
Twitter feedback: https://twitter.com/mrleblanc101/status/1379622739867209729

**Comment by robdodson** [comment]
Related to https://github.com/GoogleChrome/web.dev/issues/5036

@chybie you can generate an RSS feed for a tag by adding it to this array https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_collections/feeds.js#L32

We should also add an RSS feed icon to the tag pages so folks can discover the feed.
