### ISSUE TITLE
[devtools-docs] Fix incorrect screenshots in source maps & add link to web.dev

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#6135]
1. `/docs/devtools/javascript/source-maps/` In the "Check if source maps load successfully" section, Step 3 - 7 screenshot s are still incorrect with index.hash.css... plus the localhost is inconsistent from localhost:1234 to 127.0.0.1:8081
2. add a mention to DevTools source maps docs in https://web.dev/source-maps/

**Comment by sofiayem** [comment]
I've moved the section from source maps doc to developer resources doc. Added the link.

As for the port inconsistencies, that's how I deliberately broke the source map loading to showcase a failed state for the [developer resources doc](https://developer.chrome.com/docs/devtools/developer-resources/).
