### ISSUE TITLE
Display other post types in the feeds section on the author page.

### ISSUE THREAD

**Issue by mamieorine** [GoogleChrome/developer.chrome.com#6162]
There are many content types could be shown in the feeds section.

- articles
- documents
- blog posts
- pattern
- external presentations
- events
- videos (youtube shows, youtube playlists)
- RSS/JSON feed 

![Image](https://user-images.githubusercontent.com/45324326/235575896-974faa02-dd22-42d4-8da3-21a9e032a01b.png)

**Comment by DjCash43** [comment]
Ok

**Comment by iamshife** [comment]
> There are many content types could be shown in the feeds section.
> 
> - articles
> - documents
> - blog posts
> - pattern
> - external presentations
> - events
> - videos (youtube shows, youtube playlists)
> - RSS/JSON feed 
> 
> 
> ![Image](https://user-images.githubusercontent.com/45324326/235575896-974faa02-dd22-42d4-8da3-21a9e032a01b.png)
> 
> 
>

**Comment by iamshife** [comment]
> > There are many content types could be shown in the feeds section.
> > 
> > - articles
> > - documents
> > - blog posts
> > - pattern
> > - external presentations
> > - events
> > - videos (youtube shows, youtube playlists)
> > - RSS/JSON feed 
> > 
> > 
> > ![Image](https://user-images.githubusercontent.com/45324326/235575896-974faa02-dd22-42d4-8da3-21a9e032a01b.png)
> > 
> > 
> > 
> 
> ashraf515470@gmail.com
