### ISSUE TITLE
`new_available_content_url` only accepts an internal URL

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/developer.chrome.com#6168]
**Describe the bug**
When I try to set `is_outdated` on a blog post and assign a new `new_available_content_url`, an external URL specification didn't work. In my case, `https://web.dev/security-credential-management/`. This is a potential link destination as features graduate from Chrome-only. We should be able to link to external URLs.

https://github.com/GoogleChrome/developer.chrome.com/pull/6167/files#diff-17479bcd90d1fb1cba628905500e531a0c635a6e3436a340afd744e328258622R11

**Comment by dstmarthe** [comment]
Going to close this as I don't think it will be an issue after the migration. Then we will be dealing with Cider.
