### ISSUE TITLE
The problem of being able to register as a developer without paying $ 5

### ISSUE THREAD

**Issue by narikakun** [GoogleChrome/developer.chrome.com#619]
**Explanation**
I paid $ 5 because I had to pay $ 5 to publish the app on the Chrome Web Store, but I said I could publish it for free without anyone else paying.
(App published by the user who says: https://chrome.google.com/webstore/detail/ligkpmbekohamaijpdfgplnkefamiohm)

With this, I think that anyone can publish it.

I have not reproduced this phenomenon.

**Comment by samthor** [comment]
My understanding is that [the policy recently changed](https://blog.chromium.org/2020/03/new-developer-dashboard-and.html) (in 2020) that requires everyone to pay a fee.

That user might be mistaken or perhaps exempt from that new policy.
