### ISSUE TITLE
YouTube embed should show fallback link when JavaScript is disabled

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/developer.chrome.com#6193]
Steps to reproduce:

1. disable JavaScript in your browser
2. go to https://developer.chrome.com/blog/new-in-chrome-113/

There will be a large gap where the video would normally render. There is no “Watch on Youtube” link or anything like that.

<img width="1280" alt="Screenshot 2023-05-04 at 00 20 47" src="https://user-images.githubusercontent.com/716405/236062508-ad4483bb-d3d8-42db-a625-99e303a8731f.png">

**Comment by JohnPaulGummapu** [comment]
If the video link disappears when JavaScript is turned off in your browser, it is likely that the link is being dynamically generated or modified using JavaScript.

When JavaScript is turned off, any JavaScript code on the page will not be executed, which means that any dynamically generated content will not be displayed. This can include links, images, and other elements that are generated or modified using JavaScript.

To ensure that your page is still usable and accessible when JavaScript is turned off, it's a good idea to provide alternative content or functionality that does not depend on JavaScript. This can include providing static links or content that is displayed regardless of whether JavaScript is enabled or not.

You can also use techniques such as progressive enhancement or graceful degradation to provide a more robust and inclusive user experience that works well regardless of the user's browser or settings.

**Comment by tunetheweb** [comment]
Youtube does not work without JavaScript enabled. So a link would be of limited use IMHO.

The space at least shows that something as missing which indicates the full contents have not loaded.

**Comment by simevidas** [comment]
> Youtube does not work without JavaScript enabled. So a link would be of limited use IMHO.

If the user

1. blocks scripts from youtube.com when YouTube is embedded on another site, but
2. allows scripts from youtube.com when opening YouTube in a browser tab,

then the user would find the fallback link useful.
