### ISSUE TITLE
Maskable icons are broken in android 13

### ISSUE THREAD

**Issue by Guid21** [GoogleChrome/developer.chrome.com#6270]
**Describe the bug**
The description in the [article](https://web.dev/i18n/en/maskable-icon/) about maskable icons is not correct for android 13

Application version: 103.0.5060.71
Operating system: android 13; sdk_gphone_x86_64 Build/TE1A.220922.025

**To Reproduce**
1. Go to [twitter](https://twitter.com/)
2. Click "Install app"

**Expected behavior**
The square of the icon is cut as a circle

**Actual result**
The square icon is in a white circle

**Screenshots**
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/16309665/b8174668-d959-4ae8-a4a3-e70107f32fdc)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android 13
 - Browser Chrome
 - Version 103.0.5060.71

**Additional context**
The purpose property has no effect on android 13. If you try to do the same with telegram, the result will be correct, and this is due to the fact that telegram icon is cut in a circle

**Comment by myakura** [comment]
@Guid21 you might want to file a bug against https://crbug.com/new as this repository is for the developer.chorme.com _website_, not for Chrome itself.
