### ISSUE TITLE
PressureObserver.supportedSources is not a method, it is an attribute

### ISSUE THREAD

**Issue by opusonline** [GoogleChrome/developer.chrome.com#6284]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
In the description of Compute Pressure API, in section Methods, supportedSources is listed as a static method, which it isn't.

**To Reproduce**
Open the link https://developer.chrome.com/docs/web-platform/compute-pressure/ and scroll down to section "Methods" to find the description
> `static PressureObserver.supportedSources()` (read only): Returns supported source types by the hardware.

**Expected behavior**
It should be listed only as parameter, referring to the spec (https://w3c.github.io/compute-pressure/#the-supportedsources-attribute)
`static PressureObserver.supportedSources` (read only): Returns supported source types by the hardware.

**Comment by Ansh101112** [comment]
Hello there, I am working on this bug. Hope I will submit my PR very soon.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. Note that content is frozen at this time and we will be using an internal content publishing system. I’ve moved the pertinent parts of issue to our new tracker and you can see it at: https://b.corp.google.com/issues/310280334

**Comment by Ansh101112** [comment]
But what to enter on the SSO username and password? And also you can connect me on LinkedIn to share these credentials.

**Comment by dstmarthe** [comment]
@Ansh101112 I pust the wrong link. my apologies! Here is the public link: https://issuetracker.google.com/issues/310280334
