### ISSUE TITLE
[EXT-TUTORIAL] <Gerenciamento de cores do browser>

### ISSUE THREAD

**Issue by Joao-Victor1** [GoogleChrome/developer.chrome.com#6307]
### What would this tutorial do?

O tutorial deve ensinar como criar uma extensão para gerenciar cores, iluminação e contraste para que o usuário tenha a melhor acessibilidade possível enquanto navega pelos sites.

### What lessons would this tutorial teach?

1 - Importância da Acessibilidade e UX.
2 - Como a extensão irá executar a tarefa.
3 - Instruções passo a passo sobre como desenvolver/criar a extensão.
4 - Como carregar e testar a extensão.

### Extension components

Any

### Anything else?

Algo parecido com o Color Enhancer, porém com mais opções de configuração

**Comment by oliverdunk** [comment]
We don't aim to cover all possible extensions with our tutorials, so I'm going to close this one. Appreciate the suggestion though and we'll keep it in mind. There are also many existing extensions that provide functionality like this if you're looking for one.
