### ISSUE TITLE
"Overriding Chrome Pages" is missing an example

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#6314]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
[This text](https://developer.chrome.com/docs/extensions/mv3/override/#:~:text=Here%27s%20an%20example%20of%20specifying%20the%20title%3A%20%3Ctitle%3ENew%20Tab%3C/title%3E) refers to an example that isn't there.

**Comment by AmySteam** [comment]
I'm closing since this article was reviewed recently
