### ISSUE TITLE
Largest Contentful Paint element Error!

### ISSUE THREAD

**Issue by zhouguomai** [GoogleChrome/developer.chrome.com#6327]
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/71681451/d48ba9b3-d26f-472d-b8a2-7d9a8dca8e6d)
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/71681451/55079761-b651-4f0b-a0db-9550ae70f336)
Largest Contentful Paint element Error!

**Comment by DaveSkender** [comment]
Duplicate of https://github.com/GoogleChrome/lighthouse/issues/15075
