### ISSUE TITLE
Serious issue with live caption in Chrome, causing significant difficulties for users

### ISSUE THREAD

**Issue by minhaics** [GoogleChrome/developer.chrome.com#6328]
dear Chrome Dev Team,

I am using the live caption feature and have noticed that it is not working well, unlike the automatic captioning feature on YouTube. In the live caption feature of Chrome, every time a sentence ends or there is a pause in speech, it automatically inserts punctuation marks, causing the text to jump, become disorganized, and constantly flicker. This creates a visually unpleasant experience for users. Please consider adding an option to disable the automatic insertion of punctuation marks and automatic capitalization of the first letter of each sentence.

I hope that Chrome's live caption can function similarly to what YouTube has implemented.

Thank you!

Best regards,

**Comment by matthiasrohmer** [comment]
Thank you for your feedback, @minhaics! Could you please raise it in the [Chromium bug tracker](https://bugs.chromium.org/) instead? This repository is only handling bug reports towards the site developer.chrome.com.

**Comment by minhaics** [comment]
hi @matthiasrohmer 
I visited the 'bugs.chromium.org' page, where should I report the issue? There are many areas listed there. I hope the issue regarding the live caption feature's subtitle generation will be addressed. I really need this feature when watching videos on certain websites that do not support standard captions
