### ISSUE TITLE
Update compute pressure to Origin Trial stage.

### ISSUE THREAD

**Issue by arskama** [GoogleChrome/developer.chrome.com#6341]
#### Provide a brief title for your content proposal
ComputePressure was promoted to Origin Trial stage.
https://developer.chrome.com/origintrials/#/view_trial/1196831600973709313

#### Provide a brief summary of your content proposal
We need to update https://developer.chrome.com/docs/web-platform/compute-pressure/

#### What content already exists on this topic?
https://developer.chrome.com/docs/web-platform/compute-pressure/

#### What kind of content are you creating?
just updating.

**Comment by arskama** [comment]
I m not sure what I need to change to get my link inside the origin trial section in: 
https://developer.chrome.com/docs/web-platform/

**Comment by rachelandrew** [comment]
It's in https://github.com/GoogleChrome/developer.chrome.com/tree/main/site/_data/docs/web-platform

**Comment by arskama** [comment]
> It's in https://github.com/GoogleChrome/developer.chrome.com/tree/main/site/_data/docs/web-platform

right! thanks, I ll make a new PR then. 
Do I need to open a new issue? @rachelandrew

**Comment by rachelandrew** [comment]
No I don't need a new issue, if you assign the PR to me I'll come and approve it.

**Comment by arskama** [comment]
@rachelandrew, it seems that I don't have the rights to add a reviewer.
Here is the PR:

https://github.com/GoogleChrome/developer.chrome.com/pull/6344

Thanks for your help!

**Comment by arskama** [comment]
It seems that both patch were merged. 
#6344 
#6342 

@rachelandrew  if that s ok I m closing this. Thank you.
