### ISSUE TITLE
No "Inspect Me!" element in CSS tutorial

### ISSUE THREAD

**Issue by AkashaRojee** [GoogleChrome/developer.chrome.com#635]
**Describe the bug**
The tutorial at https://developer.chrome.com/docs/devtools/css/ says to right-click the "Inspect Me!" text but the text is not there.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/devtools/css/ 
2. Scroll down to the first line under [View an element's CSS](https://developer.chrome.com/docs/devtools/css/#view). 
3. See error

**Expected behavior**
There should be an "Inspect Me!" text to right-click on.

**Screenshots**
![dev chrome bug - css - inspect me](https://user-images.githubusercontent.com/81232315/114576246-02b98800-9c8c-11eb-82c6-4ed32e1c288f.PNG)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 89

**Comment by robdodson** [comment]
Merging in to #606
