### ISSUE TITLE
Author profile social links don't wrap on narrow viewports

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/developer.chrome.com#6350]
I guess this screenshot illustrates the problem well enough:

![Screenshot 2023-05-17 at 17 45 00](https://github.com/GoogleChrome/developer.chrome.com/assets/145676/12414dc9-f2c2-42d1-8828-b93a188ac028)

**Comment by Dogscat3831** [comment]
GitHub 
Microsoft edge
