### ISSUE TITLE
Writing a blog post for Compute Pressure OT on M115

### ISSUE THREAD

**Issue by arskama** [GoogleChrome/developer.chrome.com#6381]
#### Provide a brief title for your content proposal
"Get informed about your system compute pressure."

#### Provide a brief summary of your content proposal
Writing a blog post to https://developer.chrome.com/blog/ because Compute Pressure goes OT and it was advised to make a blog post. Compute pressure is going for OT between M115-M118(inc)

#### What content already exists on this topic?
No page in "blogs", but in web-platform yes.
https://developer.chrome.com/docs/web-platform/compute-pressure/

#### Who will be authoring the content?
@kenchris @arskama 

#### Are there any stakeholders who should be informed when this content changes?
@beaufortfrancois @PaulKinlan @tomayac 

#### What area is your content related to?
Performance, API, chrome-115, monitoring, capabilities.

#### What kind of content are you creating?
Blog post

**Comment by arskama** [comment]
@rachelandrew, I ll make a google doc first and send you a link when I m ready

**Comment by rachelandrew** [comment]
@arskama are you working with someone from Chrome DevRel on this already?

**Comment by arskama** [comment]
@rachelandrew 
I received an automatic email "Compute Pressure origin trial is branching" to kindly tell me that I should make a blog post. I knew that I had to make a blog post.

The email mentioned @PaulKinlan in case I would need help for writing the post.

I realized that it would be nice to have a recorded video of our demo, like in:
https://developer.chrome.com/blog/background-blur/

**Comment by arskama** [comment]
@ThomasTheDane who is supervising this feature from Google side just mentioned also @tomayac and @petele if I would need any help for the post.

**Comment by tomayac** [comment]
I can definitely help. The first step is to write and get reviewed a Google Docs version.

**Comment by rachelandrew** [comment]
@arskama no problem, it's just the first time I've been made aware of this automated email! For video, unless it's very small, it's usually best to host it on YouTube, but we can take a look. Anyway, once you have a draft in a doc let @tomayac and I know, and we will take it from there.

**Comment by arskama** [comment]
@tomayac @rachelandrew 
You should have editor accesses to the following document:
https://docs.google.com/document/d/1798PiWC2K7iIGDawrzvXttoxWyyFwOUziyEl6-tiFH8

Thanks

**Comment by tomayac** [comment]
This was fixed via #6381.
