### ISSUE TITLE
Dead link in site/en/blog/removing-document-write/index.md

### ISSUE THREAD

**Issue by sidusnare** [GoogleChrome/developer.chrome.com#6388]
**Describe the bug**
developer.chrome.com/site/en/blog/removing-document-write/index.md lines 92 and 99 refer to 
https://developers.google.com/web/fundamentals/primers/async-functions 
which redirects to 
https://web.dev/javascript-async-functions/ 
which displays a 404 message

**To Reproduce**
1. Go to DevTools console
2. Click on link in line " [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write"
3. scroll to line "This simple answer is don't inject scripts using document.write(). We are [maintaining a set of known services that provide asynchronous loader support](https://developers.google.com/web/fundamentals/primers/async-functions) that we encourage you to keep checking"
4. Click link
5. See error

**Expected behavior**
See a maintained set of known services that provide asynchronous loader support

**Screenshots**
![Screen 2023-05-22 1684789099 492388076](https://github.com/GoogleChrome/developer.chrome.com/assets/906792/b29e8309-cba1-49d0-99c5-f590982a08bb)
![Screen 2023-05-22 1684789117 984514354](https://github.com/GoogleChrome/developer.chrome.com/assets/906792/ded494fc-54e2-4107-85bd-ade6cd663cf5)
![Screen 2023-05-22 1684789124 193839588](https://github.com/GoogleChrome/developer.chrome.com/assets/906792/418c846f-abe5-4aa3-988a-35bbe5c345ee)

**Desktop (please complete the following information):**
 - OS: Gentoo Linux 2.13
 - Browser: Google Chrome Version 113.0.5672.126 (Official Build) (64-bit)

**Additional context**
I checked out the repo, did a quick grep, don't see the link anywhere else. I don't know where this information has moved yet. If I find an updated link I'll add it to the issue.

**Comment by heyawhite** [comment]
I believe this article should be the link to use: https://web.dev/efficiently-load-third-party-javascript/#use-async-or-defer

I'll replace accordingly.
