### ISSUE TITLE
Add linting for `date` and `updated` date

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/developer.chrome.com#6392]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**

I'm an idiot and have often got dates wrong but forgetting to update month on a copy or paste or just typing it wrong. Latest example is #6391

**Describe the solution you'd like**

Linting should catch if date is more than a month in advance as probably means it's a typo. We do allow advance posts IIRC so need some leeway so a month seems fair.

**Describe alternatives you've considered**

Stopping being an idiot, but that seems unlikely to happen...

**Additional context**

We probably don't want to insist on a date being updated each time an article is updated, as some minor typos don't really warrant an updated date.

**Comment by tunetheweb** [comment]
Another thing would be good is a a date IS updated, then maybe should be within a month of PR date?

See https://github.com/GoogleChrome/web.dev/pull/10090

**Comment by rachelandrew** [comment]
Closing as the move to a new platform will raise different issues :)
