### ISSUE TITLE
Please look into the suggestion given

### ISSUE THREAD

**Issue by pritamrajput** [GoogleChrome/developer.chrome.com#6404]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**
There should be guide regarding how one can build extension from scratch. I am always frustrated from where to start

**Describe the solution you'd like**
You can make a video on how to navigate through the documentation as for new beginner like me I don't know how to navigate and just keep running in loop without getting any results from reading the documentation.

**Describe alternatives you've considered**
Maybe you can have one extra tutorial guide for navigating through docs.

**Comment by AmySteam** [comment]
Hi @pritamrajput 

Thank you for your feedback on our documentation. I wanted to share with you a dedicated [Getting Started](https://developer.chrome.com/docs/extensions/mv3/getstarted/) section with [step-by-step tutorials](https://developer.chrome.com/docs/extensions/mv3/getstarted/#tutorial) specifically designed for beginners like yourself to help you get started 😃.

These tutorials will walk you through the process of creating an extension and provide you with a solid foundation. We recognize the need for additional assistance, and while we do not currently have a video tutorial on how to navigate the documentation, it's a great idea to consider. Thanks for the suggestion! 💯 

Hope this helps! 
Amy

**Comment by pritamrajput** [comment]
thank you for considering the feedback
