### ISSUE TITLE
Chrome Dev version & HTTP response show Unicode bug

### ISSUE THREAD

**Issue by xgqfrms** [GoogleChrome/developer.chrome.com#641]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xgqfrms** [comment]
# Chrome Dev version & HTTP response show Unicode bug


Google Chrome is up to date
Version 91.0.4469.4 (Official Build) dev (x86_64)


![](https://img2020.cnblogs.com/blog/740516/202104/740516-20210414143258163-74725166.png)


![](https://img2020.cnblogs.com/blog/740516/202104/740516-20210414143333659-1855776429.png)

```js
{"status": 200, "msg": "\u8bf7\u6c42\u6210\u529f"}

```

can not preview response

![](https://img2020.cnblogs.com/blog/740516/202104/740516-20210414143637018-968088437.png)


```js
str = "\u8bf7\u6c42\u6210\u529f";
// "请求成功"

```

![](https://img2020.cnblogs.com/blog/740516/202104/740516-20210414143913979-1317622106.png)

**Comment by xgqfrms** [comment]
# os

![image](https://user-images.githubusercontent.com/7291672/114665344-82e4f980-9d2f-11eb-9f71-ce844aea1e89.png)

**Comment by robdodson** [comment]
@xgqfrms if you're having issues with Chrome then you'll need to file them over at crbug.com. This repo is only for the documentation that appears on developer.chrome.com.
