### ISSUE TITLE
Version history Chrome Enterprise Win64 not in sync with web download page...

### ISSUE THREAD

**Issue by petscho56** [GoogleChrome/developer.chrome.com#6429]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.

Not a bug, but why is the win64 version at https://versionhistory.googleapis.com/v1/chrome/platforms/win64/channels/stable/versions/all/releases?order_by=version%20desc not in sync with the downloadable version at https://chromeenterprise.google/browser/download/#windows-tab?

We are automating the download of the enterprise version and and rely on that the release version history is in sync with the download site, and it's not... Why?

Regard,
Peter

![chrome_enterprise_version](https://github.com/GoogleChrome/developer.chrome.com/assets/134689824/70708ce2-1c61-4027-ae3b-569160359335)

![chrome_enterprise_versionhistory](https://github.com/GoogleChrome/developer.chrome.com/assets/134689824/c824bd56-e551-40a3-836b-682e02efe35b)

**Comment by FilipeNas** [comment]
same issue

**Comment by dstmarthe** [comment]
Thanks for raising this. I have close it because it's not an issue with the d.c.c. site. Chrome Enterprise has a community board  here: https://support.google.com/chrome/a/community
