### ISSUE TITLE
Clarify purpose of OPFS in article

### ISSUE THREAD

**Issue by morsssss** [GoogleChrome/developer.chrome.com#6459]
**Is your feature request related to a problem? Please describe.**
When I read [this helpful article on OPFS](https://developer.chrome.com/articles/origin-private-file-system/), I don't get a sense of what problem this was really created to solve.

**Describe the solution you'd like**
I think it would be great if the introduction talked about:
* OPFS allows a web app to store and manipulate files in its very own origin-specific virtual filesystem
* It lets you do low-level file manipulation, byte by byte, implementing (I think) part of the standard POSIX file interface
* Those are both new things on the web. File streams!
* Oh, and this is available cross-browser.

(Since it's cross-browser, should this be on developers.google.com?)

**Comment by beaufortfrancois** [comment]
@tomayac FYI
