### ISSUE TITLE
Extensions docs mentions chrome.runtime.lastError, but it's undefined

### ISSUE THREAD

**Issue by NV** [GoogleChrome/developer.chrome.com#6476]
**Describe the bug**
https://developer.chrome.com/docs/extensions/reference/storage/#property-sync-sync-QUOTA_BYTES_PER_ITEM says
> Updates containing items larger than this limit will fail immediately and set [runtime.lastError](https://developer.chrome.com/docs/extensions/reference/runtime/#property-lastError).

This is not what happens, at least not in the MV3 Promise land.

**To Reproduce**
```
let overflow = new Array(chrome.storage.sync.QUOTA_BYTES_PER_ITEM + 1).fill(".").join("");
chrome.storage.sync.set({overflow}).catch(function(er) {
    console.warn("catch", er); // Error: QUOTA_BYTES_PER_ITEM quota exceeded
    console.warn("lastError", chrome.runtime.lastError); // undefined
});
```

**Expected behavior**
Behaves as expected, but the documentation should be updated.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 113.0.5672.126

**Comment by oliverdunk** [comment]
Thanks! This is definitely a good callout. I think we need to put some thought in to how we document the difference between the promise/non-promise way of handling errors.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312321263
