### ISSUE TITLE
val name is incorrect

### ISSUE THREAD

**Issue by DDavoH** [GoogleChrome/developer.chrome.com#648]
⚠️ This is for issues with the https://developer.chrome.com/docs/android/custom-tabs/integration-guide/ site, not Chromium itself.

**Describe the bug**
*incorrect val name*
int coolorInt = Color.parseColor("#FF0000"); //red
builder.setToolbarColor(colorInt);

**Expected behavior**
int colorInt = Color.parseColor("#FF0000"); //red
builder.setToolbarColor(colorInt);

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.128

**Comment by robdodson** [comment]
assigning to @andreban
