### ISSUE TITLE
Document topSites behaviour in incognito

### ISSUE THREAD

**Issue by oliverdunk** [GoogleChrome/developer.chrome.com#6480]
For a [split-mode](https://developer.chrome.com/docs/extensions/mv3/manifest/incognito/#split) extension in incognito, the [topSites API](https://developer.chrome.com/docs/extensions/reference/topSites/) returns an error when called. We should confirm this is the intended behaviour and document it if so.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/310164050
