### ISSUE TITLE
Keyboard focus order is incorrect

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/developer.chrome.com#6487]
Steps to reproduce:

1. use a desktop browser
1. open https://developer.chrome.com/blog/how-boxysvg-uses-the-local-font-access-api/
1. scroll down to the section Conclusions
1. select some text *between* the links in the paragraph
1. press Tab

What should have happened:

The link “Zapf Dingbats” should have received focus.

What happened: 

The “Watch now” button at the top of the page received focus.

Tested in Chrome 114 on macOS 13.3.1.

https://github.com/GoogleChrome/developer.chrome.com/assets/716405/d8e60b06-992a-4d05-ae49-57baa99fd09e

**Comment by dstmarthe** [comment]
Thanks for raising this. The video shows you highlighting the text which is different from focusing. This can be replicated on any article. Pressing tab if nothing is focused will just jump to the first focusable element.

Try right-clicking on a link  -> clicking the page to get rid of the options window -> and then pressing tab.

You will see the focus working in order correctly.

**Comment by dstmarthe** [comment]
Upon a second look, you are right that after highlighting the test it should jump to the next focusable element when tab is pressed, my bad on that. But, it is like this on all other d.c.c/blog posts. We will be moving to a new platform, hence me closing and migrating issues, and I doubt this will still be a problem.
