### ISSUE TITLE
eleventyIgnore script should pull from .gitignore

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#65]
@robdodson commented on [Mon Dec 14 2020](https://github.com/GoogleChrome/dcc-private/issues/518)

We have a script in tools/eleventyignore that will dynamically generate an .eleventyignore file for us. We do this so we can toggle folders off with .env vars.

Currently this script has a `ignores` array with a set of items that should always be ignored. Ideally we should just pull this from `.gitignore` instead of having an array.

**Comment by w0rstpr0grammer** [comment]
I would like to work on it, would you please assign it to me.

**Comment by w0rstpr0grammer** [comment]
Have submitted a PR for this (#761)

**Comment by robdodson** [comment]
Ah thanks @w0rstpr0grammer.

I merged your PR but had to revert it in aa13762ed7972a618db9f84c087c62cdef0d12c4 because it seemed to be breaking the build (https://github.com/GoogleChrome/developer.chrome.com/pull/845#pullrequestreview-674159275).

![image](https://user-images.githubusercontent.com/1066253/120525360-e8974e80-c38c-11eb-9c60-299b2bc57320.png)

**Comment by matthiasrohmer** [comment]
Everything that is in .gitignore is automatically ignored by 11ty. Also see https://www.11ty.dev/docs/ignores/.
