### ISSUE TITLE
should relocate caption for figure <inside look at modern web browser (part 3)>

### ISSUE THREAD

**Issue by al-bur** [GoogleChrome/developer.chrome.com#6518]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
with desktop viewport, caption for figure 10 is located in wrong position (in mobile viewport, it looks good)

*error occurs in inside look at modern web browser (part 3) page

**To Reproduce**
1. Go to [#updating-rendering-pipeline](https://developer.chrome.com/blog/inside-browser-part3/#updating-rendering-pipeline-is-costly)
2. Scroll down to 'figure 10.'

**Expected behavior**

**Screenshots**

<img width="748" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/64825713/4d52cd7d-c019-431a-adf4-b7ff18a56a08">

**Desktop (please complete the following information):**
 - OS: MACos (13.1)
 - Browser: chrome
 - Version: 113.0.5672.126

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/311468173
