### ISSUE TITLE
Typo in .js filename

### ISSUE THREAD

**Issue by milobravman** [GoogleChrome/developer.chrome.com#6534]
**Describe the bug**
A typo in the name of a javascript file 

**To Reproduce**
1. Go to tut-quick-reference or https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-quick-reference/
3. Scroll down to the final part of step 7 
4. See the error, which is just a typo. I think 'sw-api.js' should be 'sw-tips.js' since 'sw-api.js' is not in the file structure image below

**Comment by AmySteam** [comment]
Thanks for reporting this @milobravman. 😃

There's an open [PR#6507](https://github.com/GoogleChrome/developer.chrome.com/pull/6507) for this. We are waiting for the contributor to sign the CLA.
