### ISSUE TITLE
Beginner tutorials for Chrome extensions

### ISSUE THREAD

**Issue by 123ABC-zhao** [GoogleChrome/developer.chrome.com#6555]
### What would this tutorial do?

一个新人开发chrome插件所需要的教程

### What lessons would this tutorial teach?

需要清楚的知道chrome开发的流程及其API的功能的详细描述

**Comment by AmySteam** [comment]
Thanks @123ABC-zhao! We have a few beginner tutorials in the [Getting Started](https://developer.chrome.com/docs/extensions/mv3/getstarted/) section.
