### ISSUE TITLE
fix broken hyperlink for "Explanation" under dev tools -> network -> waterfall

### ISSUE THREAD

**Issue by aishwarya4444** [GoogleChrome/developer.chrome.com#656]
**Describe the bug**
wrong hyperlink for "Explantion" in waterfall option present in Network tab
Incorrect broken hyperlink = https://developer.chrome.com/docs/devtools/network-performance/reference#timing-explanation
Correct hyperlink = https://developer.chrome.com/docs/devtools/network/reference/#timing-explanation

**To Reproduce**
1. Go to Chrome
2. Right click and select "Inspect"
3. Click on "Network" tab
4. For requests that are sent , check time taken by hovering over "Waterfall" column
5. "Explanation" has a broken hyperlink.
6. Replace it with correct hyperlink https://developer.chrome.com/docs/devtools/network/reference/#timing-explanation

**Expected behavior**
Hyperlink is broken. Needs to be replaced with a correct one mentioned above.

**Screenshots**
<img width="1168" alt="Screenshot 2021-04-19 at 1 02 59 PM" src="https://user-images.githubusercontent.com/2221237/115198361-96b5a480-a10f-11eb-91c6-c888c30902b8.png">

<img width="1069" alt="Screenshot 2021-04-19 at 1 05 39 PM" src="https://user-images.githubusercontent.com/2221237/115198673-f57b1e00-a10f-11eb-90dd-d691c1bb7143.png">

<img width="1160" alt="Screenshot 2021-04-19 at 1 06 15 PM" src="https://user-images.githubusercontent.com/2221237/115198746-0af04800-a110-11eb-9c5d-0977dcce75b6.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Version 89.0.4389.114 (Official Build) (x86_64)

**Additional context**

**Comment by robdodson** [comment]
@kaycebasques this seems like maybe we should add a redirect to the site?

**Comment by kaycebasques** [comment]
Just put in PR #705 to fix it now. Thank you for the detailed report, @aishwarya4444 and sorry for the broken experience.
