### ISSUE TITLE
Lighthouse docs "any maskable" recommendation

### ISSUE THREAD

**Issue by ekafyi** [GoogleChrome/developer.chrome.com#6562]
## Scope

[Lighthouse doc page](https://developer.chrome.com/docs/lighthouse/pwa/maskable-icon-audit/#how-to-add-maskable-icon-support-to-your-pwa) has the following recommendation. 

> Add the purpose property to one of the icons objects in your [web app manifest](https://developer.chrome.com/add-manifest/). Set the value of purpose to `maskable` or `any maskable`.

The accompanying code sample uses the value `any maskable`.

## Issue

- Chrome DevTools now shows a warning in the "Manifest" section when `purpose` value is `any maskable` - [source](https://chromium.googlesource.com/devtools/devtools-frontend/+/fbb2247690508693d6087245e4073e77222c22d3/front_end/panels/application/AppManifestView.ts#206)
- The [web.dev article](https://web.dev/maskable-icon/) on Maskable Icon also advises against it (quote at the end of article).

> While you can specify multiple space-separated purposes such as "any maskable", in practice you shouldn't. Using "maskable" icons as "any" icons is suboptimal as the icon is going to be used as-is, resulting in excess padding, making the core icon content smaller. 

## Proposed solution

Not recommend `any maskable` altogether going forward

PR: https://github.com/GoogleChrome/developer.chrome.com/pull/6508

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/312321269
