### ISSUE TITLE
Embedded CodePen demo for scrollend event broken in Chrome 114

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/developer.chrome.com#6575]
**To Reproduce**
1. Go to https://developer.chrome.com/en/blog/scrollend-a-new-javascript-event/
2. Scroll down to embedded CodePen after “Try it!”
3. Scroll the embedded page

**Expected behavior**

There should be a magenta “scroll end” toast notification. The scrollend event shipped in Chrome 114.

**Desktop (please complete the following information):**
 - OS: macOS 13.4
 - Browser: Chrome 114

**Comment by dstmarthe** [comment]
Closing this because it's been a while and it's working on later versions from what I can see.
