### ISSUE TITLE
404 error found on clicking specification in 'Stream video using the Media Source API'

### ISSUE THREAD

**Issue by Krishnak07Git** [GoogleChrome/developer.chrome.com#6596]
Open url - (https://developer.chrome.com/blog/stream-video-using-the-mediasource-api/) **Stream video using the Media Source API**. Click on hyperlink [specification ](http://html5-mediasource-api.googlecode.com/svn/trunk/draft-spec/mediasource-draft-spec.html) and observe.

**To Reproduce**
1. Go to 'Stream video using the Media Source API'
2. Click on 'Specification'
3. See error 404

**Expected behavior**
Clicking on specification should open the page.

**Screenshots**
Screenshot added 

**Desktop**
![404](https://github.com/GoogleChrome/developer.chrome.com/assets/125964110/3a5e03e8-634c-4960-b578-b0f1cbedac9d)

 - Version 114.0.5735.110 (Official Build) (64-bit)

**Comment by Krishnak07Git** [comment]
@GoogleChrome

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310169999
