### ISSUE TITLE
content: Document clearly that DevTools Snippets aren't synced or accessible outside of DevTools

### ISSUE THREAD

**Issue by varenc** [GoogleChrome/developer.chrome.com#6603]
#### Provide a brief title for your content proposal
Add a small note on the [DevTools "Run snippets of JavaScript" page](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/devtools/javascript/snippets/index.md) documenting that snippets aren't synced and aren't accessible outside of DevTools.

#### Provide a brief summary of your content proposal
see title.  It's very unclear that JS snippets are locked inside of DevTools and aren't included in [DevTools settings sync](https://developer.chrome.com/docs/devtools/customize/#sync).  I assumed they would be and ended up on chrome://sync-internals trying to debug why my snippets weren't syncing.

 There's meaningful interest and confusion about this. See these StackOverflow posts:
 - https://stackoverflow.com/questions/34044334/can-chrome-devtools-preferences-be-set-automatically-or-imported
 - https://stackoverflow.com/questions/13653047/can-i-access-javascript-snippets-using-chrome-devtools-api
 - https://stackoverflow.com/questions/19025718/which-file-does-snippets-of-chrome-dev-tool-saved-at
 - https://stackoverflow.com/questions/64046070/js-snippet-reading-from-local-file

#### What content already exists on this topic?
There's a page on [DevTools snippets](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/devtools/javascript/snippets/index.md) already that is entirely silent on the topic of storing/syncing/accessing snippets outside of DevTools.

#### Who will be authoring the content?
@varenc  (I can write it, but will need lots of feedback! Rough draft at the end of this issue)

#### Are there any stakeholders who should be informed when this content changes?

Maybe the recent committers to the JS Snippets DevTools page? The only meaningful contributor to the Snippets DevTools page from the [commit history](https://github.com/GoogleChrome/developer.chrome.com/commits/main/site/en/docs/devtools/javascript/snippets/index.md) seems to be: @sofiayem

#### What area is your content related to?

Choose from one of the following: **Other** (DevTools)

#### What kind of content are you creating?

Choose from one of the following: **Other** (minor addition to the [DevTools Snippets page](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/devtools/javascript/snippets/index.md))

#### @varenc's rough draft of a note to be added on the [DevTools Snippets page](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/devtools/javascript/snippets/index.md) clarifying snippet syncing.
> **NOTE:** Snippets are stored as part of your local preferences. They aren't [synced](https://developer.chrome.com/docs/devtools/customize/#sync) with DevTools settings nor are they accessible via the filesystem.

**Comment by varenc** [comment]
If this is reasonable, and my 2 sentence rough draft looks promising enough, I can open a PR adding a clarify note to the snippets page and we can go from there. Just wanted to make sure this all seemed reasonable for before doing that.

**Comment by rachelandrew** [comment]
@varenc thanks for raising this issue, I'm assigning it to the people who can take a look. cc @sofiayem @jecfish

**Comment by varenc** [comment]
thank you!! 🙏🙏🙏
