### ISSUE TITLE
chrome.clipboard is documented as part of the extension api

### ISSUE THREAD

**Issue by jacksteamdev** [GoogleChrome/developer.chrome.com#661]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The docs include a page for `chrome.clipboard`, which was a Chrome Apps API, and is not available for Chrome extensions.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/reference/clipboard/
2. See the deprecation notice that mentions Chrome Apps, yet the url and breadcrumbs indicate that this a Chrome extension API.

**Expected behavior**
This page should be removed, or better yet, this feature should implemented for MV3, since the Clipboard API is not available for CRX service workers.

**Screenshots**
![image](https://user-images.githubusercontent.com/23390212/115301370-b4dacf00-a126-11eb-954d-83139329b04f.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Browser: Chrome
 - Version: 90.0.4430.72

**Additional context**

**Comment by dotproto** [comment]
All extensions and app APIs are listed under `/docs/extensions/reference`. The decision to use this structure was heavily influenced by the public app deprecation timeline when this site was published and the complexity of maintaining two different generated sets of API documentation when they were so closely related. Both of these are still relevant concerns when considering possible changes to how we structure API documentation. As such, for the moment I don't think deleting this page, changing the URL, or changing the breadcrumbs are compelling options (cc @samthor to keep me honest).

Our thought was that the header at the top of the page sufficient to clearly identify the API as app-only. @jacksteamdev, do you have an other thoughts on ways that we could make the app-only nature of this API more evident?

**Comment by jacksteamdev** [comment]
> the complexity of maintaining two different generated sets of API documentation

I understand the need to reduce complexity here. It doesn't present a good user experience, though.

The concern is the confusion presented when searching for a solution for using the clipboard in a Chrome extension.

The presence of apps documentation in the extensions docs space implies that a mistake was made, thus reducing developer confidence in the Google docs overall.

### Suggestions

> the header at the top of the page sufficient to clearly identify the API as app-only

The deprecation header doesn't come through on a Google search, and it requires a complete reading of the description to see that this is an app API.

![image](https://user-images.githubusercontent.com/23390212/116256661-01329a00-a739-11eb-9a3f-53d48036af31.png)

IMO, deprecated platforms should be very "deprecation forward" in search results. Some refactoring to get that deprecation notice into search results would go a long way in improving the user experience.
