### ISSUE TITLE
Example in Popover API Blog Post have non-closed elements

### ISSUE THREAD

**Issue by notchris** [GoogleChrome/developer.chrome.com#6635]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
(https://github.com/GoogleChrome/developer.chrome.com/tree/main/site/en/blog/introducing-popover-api)

This is a solid article @una - though I noticed in the examples, many of the <p> tags are not closed. Not a big deal, just wanted to let you know.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005455
