### ISSUE TITLE
Incorrect Cookie Max-Age Values 

### ISSUE THREAD

**Issue by ArthurYidi** [GoogleChrome/developer.chrome.com#6640]
https://developer.chrome.com/blog/cookie-max-age-expires/

Currently examples with `Max-Age` are passing a timestamp in seconds (e.g. `1704085200`), when it should be seconds from the time the cookie was set.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005452
