### ISSUE TITLE
Clarify extension behaviors that signal "wants to run" and "requires reload"

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#6661]
**Is your feature request related to a problem? Please describe.**
Current documentation on [migrating to runtime host permissions](https://developer.chrome.com/docs/extensions/mv3/runtime_host_permissions/) obliquely describes what extension behaviors trigger "access requested" and "requires reload". 

**Describe the solution you'd like**
Currently, this information is spread across several Q&A entries. As a developer, I would find it more useful to see this described from the point of view of X behavior appears in Chrome and an explanation of why. 

**Describe alternatives you've considered**
IMO the current documentation is the main alternative. 

**Additional context**
I use "access requested" to refer to situations where Chrome places a background behind an extension's action icon and places the extension "Access requested" group in the extensions menu. There is currently no description of what causes an extension's action to be highlighted like this or guidance on how/when an extension might want to intentionally trigger this behavior.

![A screenshot of a test extension's pinned action in the toolbar. A white circle appears behind the extension icon, drawing attention to it.](https://github.com/GoogleChrome/developer.chrome.com/assets/1047763/77ed4d43-49d8-4957-94f3-91e275400146)

![A screenshot showing the extension menu with with a single extension under the "Access requested" group.](https://github.com/GoogleChrome/developer.chrome.com/assets/1047763/93699ac8-8dd5-4680-bebd-a905e869a10f)

I use "requests reload" to refer to situations where the user clicks the extension's action, then Chrome displays a prompt bubble that says "To apply your updated settings to this site, reload the page". There is currently no description of what triggers this prompt or guidance on how to avoid it.

![Screenshot of the prompt that appears](https://github.com/GoogleChrome/developer.chrome.com/assets/1047763/576721b6-7542-4f81-b615-fdbf5297a7d4)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/309981770
