### ISSUE TITLE
Long object names cause text overlapping.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#668]
This page shows an example: https://developer.chrome.com/docs/extensions/reference/action/#method-getUserSettings

![image](https://user-images.githubusercontent.com/1066253/115442669-1fdbe280-a1c7-11eb-9a78-873ffac8beb6.png)

Instead of having the text on the right in a two column layout, would it be possible to put it underneath?

![image](https://user-images.githubusercontent.com/1066253/115442771-44d05580-a1c7-11eb-8c95-b6e2555ce3ab.png)

**Comment by samthor** [comment]
We do this now.
