### ISSUE TITLE
Mac Chrome Extension shortcut recognize BUG from address menu

### ISSUE THREAD

**Issue by ghdic** [GoogleChrome/developer.chrome.com#6681]
Hello, I am a developer who makes Chrome extensions as a hobby.
When [MacCtrl](https://developer.chrome.com/docs/extensions/reference/commands/#supported-keys) is assigned as a hotkey on Mac,
there is a bug where Control and Command cannot be distinguished in the address bar.
I created an extension app that automatically scrolls webpages by pressing control + c.

Chrom Extension's `manifest.json` codes related to shortcut keys in file
```
"commands": {
    "Toggle Autoscroll": {
      "description": "Pauses/Resumes Autoscroll on the current page",
      "suggested_key": {
        "default": "Alt+C",
        "mac": "MacCtrl+C"
      }
    }
  }
```

I attach a video for your understanding
You can see the keys I press on the `bottom left`
If I press `command + c` on the usual screen, automatic scrolling does not work,
When the address bar is focused, the shortcut key is automatic
[here's a video](https://github.com/GoogleChrome/developer.chrome.com/assets/28496724/b6116187-df1e-42c5-adc8-c5ea7eead7d0)

if your need source code [here](https://github.com/ghdic/simple-autoscroll-chrome-extension)

**Comment by dstmarthe** [comment]
Hi, thanks for bringing this issue. This repo is only for content issues with developer.chrome.com, so I have to close this. To report Chrome extension bugs, chromium has an issue tracker at https://bugs.chromium.org/p/chromium/issues/list
or talk to the community at https://groups.google.com/a/chromium.org/g/chromium-extensions
