### ISSUE TITLE
font size should be boosted on method signatures

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#669]
This page shows an example: https://developer.chrome.com/docs/extensions/reference/action/#method-getUserSettings

The code text is only 11px and quite hard to read. We should probably bump this up a tad
![image](https://user-images.githubusercontent.com/1066253/115442934-71846d00-a1c7-11eb-83e0-f60d4bb53769.png)

**Comment by endacrossan** [comment]
Changing the font-size of the _.type--label_ class at: developer.chrome.com/dist/css/main.css to 0.8275 will change the appearance as below, this is slightly smaller that other code elements on the page when compared with "setBadgeText" as a reference in the screen shot.

![image](https://user-images.githubusercontent.com/48137079/123788541-0b594c00-d8d4-11eb-95eb-59d507078a53.png)


Or changing to font-size: 0.9375rem; will match the size of existing code, as below:

![image](https://user-images.githubusercontent.com/48137079/123788758-49ef0680-d8d4-11eb-8c40-6fe82225df18.png)

I wanted to investigate this to approve and add a comment before attempting to make any changes.

**Comment by robdodson** [comment]
@endacrossan If you search the code do you see any other uses of `.type--label`? I'd be ok changing it so long as it only affects these API pages

**Comment by endacrossan** [comment]
@robdodson I did check this last week and could not find any instances but I was having problems finding other strings when looking at other issues so I need to recheck this. 

Let me clone the codebase again over the weekend and I will update this issue by Monday and mention you. 

What would your preference be for the change, 0.875rem or 0.9375rem based on screen shots above?

**Comment by endacrossan** [comment]
@robdodson type--label is used in other elements within the build and is referenced in 5 files.
![image](https://user-images.githubusercontent.com/48137079/124396713-1c0a2780-dd03-11eb-89fa-9d6169a62483.png)
The main impact of making the change would also effect other parts of this page and the styling of the search results when using the search box functionality on each page across the site. As you can see search-box.js includes type-label which impacts both the Blog and Documentation search box result headers within the search results.

**Comment by robdodson** [comment]
@samthor maybe these strings shouldn't use .type--label, but another class that we can bump up a bit?

**Comment by samthor** [comment]
Sounds good, although I will call out that I have an open design thread with @jimoong about this page generally.
