### ISSUE TITLE
Best practices for DevTools

### ISSUE THREAD

**Issue by akmiecik** [GoogleChrome/developer.chrome.com#674]
I've been using DevTools for a while.  It's a known problem that DevTools is a "simulator" but that does not excuse how far off DevTools view is from what you see on the mobile.

Here's a short list of CSS that does not work well with DevTools and mobile:
padding - calling out left, right, top, bottom
background-attachment: fixed
Seem like any kind of background-positioning or background-size
background-position: left top; did not work

It would go a long way if Google DevTools could come up with a list of CSS that does not play well between DevTools and mobile.

Thanks.

I'm willing to help

**Comment by dotproto** [comment]
@kaycebasques, do you know who should take this issue?

**Comment by robdodson** [comment]
@akmiecik I think it might be better to file this as a crbug.com issue.
