### ISSUE TITLE
Aside component background collides with the left-aligned images

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/developer.chrome.com#6782]
Aside component background collides with the left-aligned images on desktop screen sizes. Text wraps as expected, but the background goes full article width.

1. Go to ['...'](https://developer.chrome.com/docs/privacy-sandbox/fedcm/#use-cases)

<img width="1405" alt="Screenshot 2023-07-07 at 16 24 37" src="https://github.com/GoogleChrome/developer.chrome.com/assets/17127567/d05bb407-a7b0-4ef8-84f1-d3a6c5bc8420">

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
