### ISSUE TITLE
Removed feature still in docs

### ISSUE THREAD

**Issue by jvinceller** [GoogleChrome/developer.chrome.com#6801]
**Describe the bug**
While adding a shortcut in the manifest of a Chrome extension, the OS specific "Option" value does not work, the extension did not install, an error was displayed. I tried "mac": "Option+Comma", it did not work. With "mac": "Alt+Comma" it does.

**To Reproduce**
Build a small Chrome extension and add this to the manifest.json:

    "commands": {
      "foo": {
        "suggested_key": {
          "default": "Alt+Comma",
          "mac": "Option+Comma"
        },
        "description": "Bar"
      }
    },

**Expected behavior**
Extension should install even when I use "Option+Comma" in the "mac" specific line.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4.1
 - Browser Chrome
 - Version (german)    114.0.5735.198 (Offizieller Build) (arm64)

**Labels**
extensions

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310197451
