### ISSUE TITLE
Add definition of composited animations to 'Avoid non-composited animations' page

### ISSUE THREAD

**Issue by RDjarbeng** [GoogleChrome/developer.chrome.com#6816]
**Is your feature request related to a problem? Please describe.**
This page on "Avoid non-composited animations" talks about composited animations without defining them. After reading the information on the page, visitors may have to go figure out what composited animations are from a different site which could be avoided by just including a definition.  
https://developer.chrome.com/docs/lighthouse/performance/non-composited-animations/?utm_source=lighthouse&utm_medium=lr

For me, I reached that page from the site pagespeed.web.dev after analyzing a website's performance. From the explanation I think composited animations are animations that change the layout of the page🤷🏽‍♂️. However, I would like this clarified.

**Describe the solution you'd like**
A definition of what a composited animation is should be included on that page to aid understanding, 

Specific page in this repository:
https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/lighthouse/performance/non-composited-animations/index.md

**Describe alternatives you've considered**
Alternatives could use a link to an explanation of composited animations.
There is a link at the bottom [Stick to compositor-only properties and manage layer count](https://web.dev/stick-to-compositor-only-properties-and-manage-layer-count/) but that page does not exactly define what a composited animation is either.

**Additional context**
This is an image of where I got redirected from on pagespeed.web.dev

![image](https://github.com/GoogleChrome/developer.chrome.com/assets/57795443/2368dc44-401c-4af8-8c10-a80d00f46d0b)

Also, when I clicked on' improve article' I didn't expect to be sent to the markdown file on github. Just wanted to give a small comment, now I'm opening an entire issue. Maybe a simple form or text box will do.🙂
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/57795443/6dc53893-56e4-468a-814a-5ea39bc117c7)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/309981767
