### ISSUE TITLE
Scroll-driven animations case study demos should feature detect in non-supporting browsers

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/developer.chrome.com#6817]
**Describe the bug**

It got raised to me that in the [scroll-driven animations performance case study article](https://developer.chrome.com/blog/scroll-animation-performance-case-study/), there are a number of demos of this new API, but they require Chrome 115 to work. The case study does not state this and the demos don't show a message when the API is not supported.

One of the demos does show a message when using Chrome and < 115 but this is not present on the other demos, nor for other browsers:

<img width="556" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/10931297/941b2db9-76a0-4678-b2ac-ef5e70065ad1">

**To Reproduce**
1. Go to https://developer.chrome.com/blog/scroll-animation-performance-case-study/#:~:text=The%20following%20demo%20shows%20an%20application%20of%20scroll%20driven%20animation on Firefox or Safari
2. Note demo doesn't work
3. Be confused
4. Go to https://developer.chrome.com/blog/scroll-animation-performance-case-study/#:~:text=Also%2C%20this%20new%20API%20works%20in%20conjunction%20with%20the%20existing on Chrome < 115
5. Note demo doesn't work
6. Be confused

**Expected behavior**

We should feature detect this API and show an error message for all the embedded demos when the API is not supported. Ideally mention this in the article too.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005451
