### ISSUE TITLE
Damaged Link in the Stable APIs table

### ISSUE THREAD

**Issue by Jemeni11** [GoogleChrome/developer.chrome.com#6818]
**Describe the bug**
There is a damaged link in the [Stable APIs table](https://developer.chrome.com/docs/extensions/reference/#stable_apis) of the [API Reference page](https://developer.chrome.com/docs/extensions/reference/).

**To Reproduce**
1. Go to the [Stable APIs table](https://developer.chrome.com/docs/extensions/reference/#stable_apis) located on the [API Reference page](https://developer.chrome.com/docs/extensions/reference/).
2. Scroll down to the `enterprise.platformKeys` field of the table.
3. See the damaged link.

**Expected behavior**

**Screenshots**

![Enterprise](https://github.com/GoogleChrome/developer.chrome.com/assets/52603291/639f9bfe-0123-4f72-bb4b-01e4a6be7a67)

**Desktop (please complete the following information):**
 - OS: Linux (Lubuntu 22.04.2 LTS x86_64) 
 - Browser: Vivaldi
 - Version: Version 6.1.3035.111 (Official Build) stable (64-bit)

**Additional context**
> [enterprise.platformKeys](https://developer.chrome.com/docs/extensions/reference/enterprise_platformKeys)
> Use the chrome.enterprise.platformKeys API to generate keys and install certificates for these keys. The certificates will be managed by the platform and can be used for TLS authentication, network access or by other extension through {@link platformKeys chrome.platformKeys}.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005450

**Comment by Jemeni11** [comment]
Thanks for the update! I'll keep an eye on the new tracker
