### ISSUE TITLE
Damaged Link in the Stable APIs table

### ISSUE THREAD

**Issue by Jemeni11** [GoogleChrome/developer.chrome.com#6819]
**Describe the bug**
There is a damaged link in the [Stable APIs table](https://developer.chrome.com/docs/extensions/reference/#stable_apis) of the [API Reference page](https://developer.chrome.com/docs/extensions/reference/).

**To Reproduce**
1. Go to the [Stable APIs table](https://developer.chrome.com/docs/extensions/reference/#stable_apis) located on the [API Reference page](https://developer.chrome.com/docs/extensions/reference/).
2. Scroll down to the `platformKeys` field of the table.
3. See the damaged link.

**Expected behavior**

**Screenshots**

![platformKeys](https://github.com/GoogleChrome/developer.chrome.com/assets/52603291/bab20bcb-312a-4748-a11e-e28b9802ad3c)

**Desktop (please complete the following information):**
 - OS: Linux (Lubuntu 22.04.2 LTS x86_64) 
 - Browser: Vivaldi
 - Version: Version 6.1.3035.111 (Official Build) stable (64-bit)

**Additional context**
> [platformKeys](https://developer.chrome.com/docs/extensions/reference/platformKeys)
> Use the chrome.platformKeys API to access client certificates managed by the platform. If the user or policy grants the permission, an extension can use such a certficate in its custom authentication protocol. E.g. this allows usage of platform managed certificates in third party VPNs (see {@link vpnProvider chrome.vpnProvider}).

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005450
