### ISSUE TITLE
Phantom redirect affects Google Analytics

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#6820]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Google analytics for extensions has an entry for `/docs/extensions/reference/automation/`. There is no such page, but navigating to the URL redirects to [`https://developer.chrome.com/tags/automation/`](https://developer.chrome.com/tags/automation/). This page doesn't have anything to do with extensions.

There are no entries for these urls in the `redirects.yaml` file.

Whatever is creating this noise in our analytics could be affecting more than just extensions.

**Expected behavior**
navigating to [`https://developer.chrome.com/docs/extensions/reference/automation/`](https://developer.chrome.com/docs/extensions/reference/automation/) returns a [404](https://developer.chrome.com/docs/extensions/mv3/xx)

cc: @oliverdunk

**Comment by oliverdunk** [comment]
I spent a bit of time here and this is happening because of [`uniqueRedirect.js`](https://github.com/GoogleChrome/developer.chrome.com/blob/main/server/handlers/redirects/uniqueRedirect.js):

```
/**
 * @fileoverview Provides a runtime redirect handler that, for missing pages, finds the nearest
 * matching URL and sends the user there instead. This helps deal with a large number of 404's
 * found due to the site's relaunch in 2020.
 */
```

It seems like this is working as intended and "fixing" it would just mean disabling this functionality.
