### ISSUE TITLE
Possible documentation error in sample code

### ISSUE THREAD

**Issue by cltompkins0720** [GoogleChrome/developer.chrome.com#6823]
Description:
There appears to be an issue with the sample code provided on page https://developer.chrome.com/docs/extensions/mv3/a11y/. Under the Shortcuts section of the documentation, the HTML sample includes the value 'button1' for all three image tag id attributes, when the id attribute is expected to be unique in the document.

Steps to locate the incorrect code sample:
1. Go to 'https://developer.chrome.com/docs/extensions/mv3/a11y/#shortcuts'
2. Scroll down to HTML code sample
3. See code error

Expected code sample:
As used in a different HTML sample code on the same page, the expected image tag id attributes should read 'button1', 'button2', and 'button3'.

Screenshot:
<img width="722" alt="Screenshot 2023-07-13 at 5 59 38 PM" src="https://github.com/GoogleChrome/developer.chrome.com/assets/46688936/66710ecd-722d-4b45-b0b6-167eaf4d4881">

Laptop OS and browser:
 - OS: macOS Ventura 13.4
 - Browser: Chrome 114.0

**Comment by AmySteam** [comment]
@patrickkettner Do you have a minute to look at this? =)
