### ISSUE TITLE
Dead link at site/en/docs/lighthouse/performance/uses-webp-images/index.md

### ISSUE THREAD

**Issue by DubbaThony** [GoogleChrome/developer.chrome.com#6838]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
In the [site/en/docs/lighthouse/performance/uses-webp-images/index.md](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/lighthouse/performance/uses-webp-images/index.md) there is a dead link in the resources section, this part:

"Source code for Serve images in modern formats audit".

**To Reproduce**
1. Go to [site/en/docs/lighthouse/performance/uses-webp-images/index.md](https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images)
2. Scroll to last section - resources and click "Source code for Serve images in modern formats audit"
3. Observe error 404.

**Expected behavior**
Link should not be provided or point to something that does not return error 404

**Screenshots**

**Desktop (please complete the following information):**
(does not matter)

**Smartphone (please complete the following information):**
(does not matter)

**Additional context**

**Comment by tunetheweb** [comment]
Looks like this was fixed in #7652
