### ISSUE TITLE
Broken link to common-test-selector in Recorder Features Reference

### ISSUE THREAD

**Issue by Quiigi** [GoogleChrome/developer.chrome.com#6856]
**Describe the bug**
Recorder Features Reference has a broken link

**To Reproduce**
1. Go to '[Features Reference](https://developer.chrome.com/docs/devtools/recorder/reference/)'
2. Click on '[common test attributes](https://developer.chrome.com/docs/devtools/recorder/reference/common-test-selector)'
3. See error 404: "Aw Snap!  We couldn't find that page"

**Expected behavior**
A page explaining common test selectors (or attributes)

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: irrelevant ( Ubuntu 22.04.2 LTS)
 - Browser: irrelevant (Google Chrome Beta)
 - Version: irrelevant (115.0.5790.90 (Official Build) beta (64-bit) )
 
**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310006207
