### ISSUE TITLE
If possible then try to make a function that will allows us to open default_popup without clicking the icon.

### ISSUE THREAD

**Issue by devlopersabbir** [GoogleChrome/developer.chrome.com#6861]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**
Our client want to make automatically open our default_popup when perform any task on the webpage. Mainly they want, without clicking the extension icon it should be open default_popup.

**Describe the solution you'd like**
I hope you are add this function that will be very helpful.

**Describe alternatives you've considered**
I saw that, currently have an API which is `chrome.action.openPopup()` method. But it's not able to open also it's says this error.
 ```
Error in event handler: TypeError: chrome.action.openPopup is not a function
```

**Additional context**
Check out this screenshot.
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/82939905/9e1dff8a-0fb4-4fc0-9861-65539d0d3453)

**Comment by matthiasrohmer** [comment]
> ⚠️ This is for feature requests with the https://developer.chrome.com/ site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com/.
