### ISSUE TITLE
Script to detect & list changed developer.google.com content

### ISSUE THREAD

**Issue by dmdabbs** [GoogleChrome/developer.chrome.com#6867]
I could swear that I encountered a script/utility to check for devolper.chrome.com site changes. 
If I am not imagining this, would someone kindly please point me to its repo?

TY

**Comment by matthiasrohmer** [comment]
Can you specify what exactly you are looking for? Content-wise our RSS feeds should be a good source for at least new content:

- https://developer.chrome.com/feeds/blog.xml
- https://developer.chrome.com/feeds/articles.xml

Tracking smaller updates also across the auto-generated parts of the site is trickier and I am not aware of any tool that does this so far.

**Comment by dmdabbs** [comment]
Yes. Those are great. Appreciate the separation of articles from blog. I am looking for a feed to see new/changed _docs_ content. In my case I am specifically interested in Privacy Sandbox (https://developer.chrome.com/docs/privacy-sandbox/) content updates.

AIUI, the _all_ feed is the union of the blogs and articles feed, but not docs.

**Comment by dmdabbs** [comment]
Ah ha! I found the repo script I had seen and bookmarked:

[https://github.com/GoogleChromeLabs/privacy-sandbox-explainer-updates](https://github.com/GoogleChromeLabs/privacy-sandbox-explainer-updates)

**Comment by myakura** [comment]
> In my case I am specifically interested in Privacy Sandbox (https://developer.chrome.com/docs/privacy-sandbox/) content updates.

GitHub commit history might be useful.

History for site/en/privacy-sandbox - GoogleChrome/developer.chrome.com
https://github.com/GoogleChrome/developer.chrome.com/commits/main/site/en/privacy-sandbox

History for site/en/docs/privacy-sandbox - GoogleChrome/developer.chrome.com
https://github.com/GoogleChrome/developer.chrome.com/commits/main/site/en/docs/privacy-sandbox
