### ISSUE TITLE
[devtools] Missing docs on the Network panel search pane

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#6884]
Type Command + F in the Network panel to start searching. Missing docs in the Network reference guide and can briefly mention in the search tab docs as well.

<img width="609" alt="network-search-pane" src="https://github.com/GoogleChrome/developer.chrome.com/assets/5917927/8112586a-4a7f-4973-9510-6a11d82a018f">

I know we mention that in the [search tab docs](https://developer.chrome.com/docs/devtools/search/#built-in-search-bars) however, we should mention that in the network reference docs as well as there is where developer look for network related feature.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/312298384
