### ISSUE TITLE
[ru] Wrong link to LCP source file

### ISSUE THREAD

**Issue by rustam-mukhametshin** [GoogleChrome/developer.chrome.com#6885]
**Describe the bug**
Wrong link to LCP source file

**To Reproduce**
1. Go to [LCP ru](https://developer.chrome.com/ru/docs/lighthouse/performance/lighthouse-largest-contentful-paint/)
2. Click on [Исходный код проверки LCP](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/metrics/largest-contentful-paint.js).
3. See 404 error

**Expected behavior**
Should locate to [LCP source from EN version](https://github.com/GoogleChrome/lighthouse/blob/main/core/audits/metrics/largest-contentful-paint.js)

**Screenshots**
<img width="1022" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/34323404/5f1a8313-1b58-4092-9961-11d003354056">

**Comment by rustam-mukhametshin** [comment]
> @rustam-mukhametshin Thanks link is fixed and merged 👍

why you copied my PR if it was already created?
That's not make any sense. 😄

**Comment by yagiz-aydin** [comment]
We wrote same thing it's easy and I think you are the Product Owner not the issue creator and a dev :D 
@rustam-mukhametshin

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311049377
