### ISSUE TITLE
[extension-docs] Enable content script for debugging

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#6888]
DevTools 116 will [ignore content scripts by default](https://developer.chrome.com/blog/new-in-devtools-115/#content-script) during debugging. 

This is a critical workflow for extension developer debugging. This should be added in the extension debugging docs.

**Comment by jpmedley** [comment]
Thanks for sending this over. The link says 115. Can you please verify that it's 115 and that the link content didn't get published too early?

**Comment by dstmarthe** [comment]
I've moved this issue here: 
https://issuetracker.google.com/issues/324483259
