### ISSUE TITLE
[extension-docs] View extension requests in the Network panel

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#6889]
DevTools will soon have an option to hide network requests from Chrome extensions. This is the critical debugging workflow for extension developers. This should be documented in the extension docs.

**Comment by jpmedley** [comment]
Who do I talk to to get more information?

**Comment by dstmarthe** [comment]
I've moved this issue here: https://issuetracker.google.com/issues/324331437
