### ISSUE TITLE
Broken link in Documentation, No Integration Guide Link

### ISSUE THREAD

**Issue by stot3** [GoogleChrome/developer.chrome.com#689]
**Describe the bug**

The link is broken in the What's Next portion of the documentation: 

**To Reproduce**

1.  Go to https://developer.chrome.com/docs/android/trusted-web-activity/overview/
2. In the What's Next Portion, click Integration Guide.
3. Enjoy the Confusion.

**Expected behavior**
I expected to land at the Integration guide, instead it's a broken page. 

**Desktop (please complete the following information):**
-Browser Chrome 89.0.4389.128

**Comment by robdodson** [comment]
@andreban can you take a look?
