### ISSUE TITLE
The content of "Check the service worker status" will become obsolete

### ISSUE THREAD

**Issue by hanguokai** [GoogleChrome/developer.chrome.com#6896]
The content of "[Check the service worker status](https://developer.chrome.com/docs/extensions/mv3/tut_debugging/#sw-status)" will become obsolete. Especially for this part:

> Also, if you have made changes to the service worker code, you can use the Update button and skipWaiting to apply the changes immediately.
<img width="695" alt="Screenshot 2023-07-21 at 23 13 14" src="https://github.com/GoogleChrome/developer.chrome.com/assets/776467/287a4efe-fc4f-46d4-a6fb-67436ecac509">

Because it will not work in Chrome 117 due to the change https://chromiumdash.appspot.com/commit/b8b06b6b8071b96e3f76858d662d8991ba3b3374

Also see this [discussion](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/Z-H3IkRODpQ/m/3KDQUddEBgAJ).

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005448
