### ISSUE TITLE
Content Feedback: Unexpected link in MV3 extensions overview

### ISSUE THREAD

**Issue by rseabrook** [GoogleChrome/developer.chrome.com#692]
The [MV3 extensions overview](https://developer.chrome.com/docs/extensions/mv3/overview/#policy) has a link that says "Google Similar Pages" with a matching screenshot, but the link points to [a completely different extension called PackageTrack](https://chrome.google.com/webstore/detail/packagetrack-package-trac/hoipjclokbelgffomjhhiflphegpmlpe). The Google Similar Pages extension can be found [here](https://chrome.google.com/webstore/detail/google-similar-pages/pjnfggphgdjblhfjaphkjhfpiiekbbej).

**Comment by dotproto** [comment]
Thanks for the report & for making the fix super easy 😄

**Comment by QuentinGibson** [comment]
#712
Here's a quickfix.
