### ISSUE TITLE
Latvia missing from the countries list while "Register as Chrome Web Store Deveoper" add credit card dialog

### ISSUE THREAD

**Issue by vbarzana** [GoogleChrome/developer.chrome.com#6928]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
I tried to add my credit card while registering as chrome extension developer, but my country Latvia is not in the list of countries, can you guys please add that?

**To Reproduce**
Creating this issue again as problem is still there.
1. Go to 'https://chrome.google.com/u/1/webstore/devconsole/register' try to add a credit card
2. Click on 'country' and you will not find latvia in the list.

**Expected behavior**
Latvia should appear in the list of countries.

**Screenshots**
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/3055285/d733b0fb-dcac-4680-b1dd-3f0a3d49a1ca)

**Desktop (please complete the following information):**
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by oliverdunk** [comment]
Hi @vbarzana! We do only support a limited list of countries there, but I understand wanting to be able to sign up. If you could reach out on the One Stop Support form (https://support.google.com/chrome_webstore/contact/one_stop_support), that's the best place for questions like this :)
