### ISSUE TITLE
content: Record screen and camera with Document Picture-in-Picture and Insertable Streams

### ISSUE THREAD

**Issue by Volcomix** [GoogleChrome/developer.chrome.com#6931]
#### Provide a brief title for your content proposal

Record screen and camera with Document Picture-in-Picture and Insertable Streams

#### Provide a brief summary of your content proposal

We implemented a screen and camera recorder and we would like to share how we leveraged the latest features of Chrome to achieve this result: https://github.com/contrastio/recorder

The article would guide the reader through the implementation of a basic screen recorder that allows to:
* interact with a browser tab or software window while seeing the camera in a Picture-in-Picture window
* control the recording (start/stop) from the Picture-In-Picture window
* combine the screen sharing and camera streams through Insertable Streams
* save and download the recording thanks to MediaStream Recording API

#### What content already exists on this topic?

* https://developer.chrome.com/docs/web-platform/document-picture-in-picture
* https://developer.chrome.com/articles/mediastreamtrack-insertable-media-processing

#### Who will be authoring the content?

* @volcomix
* @sailor

#### What area is your content related to?

Frontend

#### What kind of content are you creating?

Article

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310005447.
