### ISSUE TITLE
Content feedback on OAuth for Extensions Guide

### ISSUE THREAD

**Issue by JordanSucher** [GoogleChrome/developer.chrome.com#6935]
The current [OAuth for Extensions](https://developer.chrome.com/docs/extensions/mv3/tut_oauth/) guide indicates that it is possible to make an OAuth call with an empty 'scopes' field in the manifest.json file - however, without a valid scope this call results in a bad request

Can fix by having user select a Scope during credential setup & including in manifest.json

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311086590
