### ISSUE TITLE
Could not decode image: 'icons.png'

### ISSUE THREAD

**Issue by rijusougata13** [GoogleChrome/developer.chrome.com#6936]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
I am installing an extension from chrome store, but it appears its throwing this issue and blocking me from installing. 
I tried to manually upload it from local and it works perfectly fine. 

**To Reproduce**
1. visit https://chrome.google.com/webstore/detail/whatsapp-web-status-saver/hdmjijcododdikjeibeneigchpaeoebk?hl=en&authuser=0 and try to add in chrome

**Expected behavior**
It should be added in chrome without any error

**Screenshots**
<img width="1008" alt="Screenshot 2023-07-27 at 2 16 11 AM" src="https://github.com/GoogleChrome/developer.chrome.com/assets/52108435/266da32f-b061-4086-b54e-ba8c60982ddb">

Here is the source code for it 
https://github.com/rijusougata13/wa-web-status-downloader/tree/main/icons

**Comment by adminvns** [comment]
HI @rijusougata13 
are  these requirements getting fulfilled?
these are from official chrome dev page

https://developer.chrome.com/docs/webstore/images/#icons
