### ISSUE TITLE
in chrome with javascript "video.audioTracks.length" is "1" even if video has 2 or more audio tracks

### ISSUE THREAD

**Issue by maxstrambini** [GoogleChrome/developer.chrome.com#6947]
**Describe the bug**

In Chrome using javascript the value of "video.audioTracks.length" is "1" even if video has 2 or more audio tracks

Chrome Version 115.0.5790.110 (Official Build) (64-bit)

'Experimental Web Platform features' are enabled!

Previously it worked correctly!

Example code:

        function displayAudioTracks {
            var video = document.getElementById("myvideo");
            console.log("video:");
            console.log(video);

    	   for (let i = 0; i < video.audioTracks.length; i += 1) {
                console.log(video.audioTracks[i]);
           }         
        }

Playing a video with 2 audio tracks the video.audioTracks returns always 1 and switching audio is impossible.
Used to work in previous versions.

**Comment by matthiasrohmer** [comment]
This repo is for issues with the https://developer.chrome.com/ site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com/.
