### ISSUE TITLE
chrome.windows API: broken "current window" link

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#6989]
on this page:
https://developer.chrome.com/docs/extensions/reference/windows/#method-getCurrent

has this short text:
> Gets the [current window](https://developer.chrome.com/docs/extensions/reference/windows/#current-window).

it's a broken link.  it should be anchored to `the-current-window` instead of `current-window`.  or maybe the anchored text should be using `current-window`.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/309981771
