### ISSUE TITLE
No INP data

### ISSUE THREAD

**Issue by craigbilner** [GoogleChrome/developer.chrome.com#7011]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
INP data regardless of specifying: no metric, `experimental_interaction_to_next_paint` or `interaction_to_next_paint` returns `null` for percentile data and `NaN` for histogram densities for the last 2 weeks.

**To Reproduce**

```bash
curl -s --request POST 'https://chromeuxreport.googleapis.com/v1/records:queryHistoryRecord?key=API_KEY' \
    --header 'Accept: application/json' \
    --header 'Content-Type: application/json' \
    --data '{"formFactor":"PHONE","origin":"https://www.example.com","metrics":["interaction_to_next_paint"]}'
```

**Expected behavior**
Non `null` values to appear in `percentilesTimeseries.p75s` and non `NaN` values to appear in `histogramTimeseries` for the last two values (as of today)

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by matthiasrohmer** [comment]
Sorry, this repo is for issues with the https://developer.chrome.com/ site only.
