### ISSUE TITLE
chrome.contextMenus.create contexts value: "browser_action" to "action"

### ISSUE THREAD

**Issue by lp177** [GoogleChrome/developer.chrome.com#7057]
**Describe the bug**

On page https://developer.chrome.com/docs/extensions/reference/contextMenus/#type-ContextType

ContextType section reference to old value to use in chrome.contextMenus.create contexts value: "browser_action"
which no longer works with manifest v3 and seem not indicate in migration section of manifest v2 to v3 at https://developer.chrome.com/docs/extensions/migrating/api-calls/#replace-the-browseraction-and-pageaction-apis-with-the-action-api

The value that currently works is "action"

**Expected behavior**
Replace "browser_action" to "action", or add deprecation notice in documentation and add this change in migration section.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311471189
