### ISSUE TITLE
F

### ISSUE THREAD

**Issue by thamer19833** [GoogleChrome/developer.chrome.com#707]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wntiv-main** [comment]
This is just spam.

**Comment by dotproto** [comment]
Closing as this issue does not contain a bug report.
