### ISSUE TITLE
Wrong language info

### ISSUE THREAD

**Issue by Christoph142** [GoogleChrome/developer.chrome.com#7105]
**Describe the bug**
The info at https://developer.chrome.com/docs/extensions/reference/i18n/#supported-locales is wrong

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/reference/i18n/#supported-locales
2. Find "You can use any of the [locales that the Chrome Web Store supports](https://developer.chrome.com/docs/webstore/i18n/#choosing-locales-to-support)."

**Expected behavior**
This is not the language list that Chrome supports; probably a subset thereof. For example de_CH is missing.

**Comment by jpmedley** [comment]
@Christoph142 I did some research on this. The text isn't entirely wrong, it just says something very badly. None of our current engineers have worked on the relevant code, but I'll give you our understanding of what it does. Let me know if this matches your experience.

I'm probably going say some things you already know. That's jut  to make sure we're both talking about the same thing.

The manifest file has a `"default_locale"` field and a `"description"`. These should match. Web Store reads the description field and displays it to potential users. An extension can use a messages.json file to provide descriptions for other locals. But it has a limitation. Web Store supports a smaller list of locals than Chrome does. Imagine an extension with strings for en and de_CH. If Web Store doesn't support de_CH, it will fall back to the default (en, in this case). The solution is to include language strings for de. Then de_CH will fall back to de. (I'm using de_CH as an example, whether Web Store supports it or not.)

I plan to update the documentation to explain all this. I'm told the Web Store list is out of date. I'm working on updating that as well.

**Comment by Christoph142** [comment]
Hi Joe, thanks for the detailed answer. We're on the same page. But i was looking for a comprehensive list of languages that are available to extensions for localizations entirely unrelated to the Chrome Web Store, i.e. valid values for default_locale and part of the issue being that the above page is linked at https://developer.chrome.com/docs/extensions/mv3/manifest/default_locale/ and the only available info in terms of supported languages.
I extracted this list directly from the Chromium source code:
af, af_NA, af_ZA, am, am_ET, ar, ar_AE, ar_BH, ar_DJ, ar_DZ, ar_EG, ar_EH, ar_ER, ar_IL, ar_IQ, ar_JO, ar_KM, ar_KW, ar_LB, ar_LY, ar_MA, ar_MR, ar_OM, ar_PS, ar_QA, ar_SA, ar_SD, ar_SO, ar_SS, ar_SY, ar_TD, ar_TN, ar_YE, az, az_Cyrl, az_Cyrl_AZ, bg, bg_BG, bn, bn_BD, bn_IN, bs, bs_Cyrl, bs_Cyrl_BA, ca, ca_AD, ca_ES, ca_FR, ca_IT, cs, cs_CZ, da, da_DK, da_GL, de, de_AT, de_BE, de_CH, de_DE, de_IT, de_LI, de_LU, el, el_CY, el_GR, en, en_AE, en_AG, en_AI, en_AS, en_AT, en_AU, en_BB, en_BE, en_BI, en_BM, en_BS, en_BW, en_BZ, en_CA, en_CC, en_CH, en_CK, en_CM, en_CX, en_CY, en_DE, en_DG, en_DK, en_DM, en_ER, en_FI, en_FJ, en_FK, en_FM, en_GB, en_GD, en_GG, en_GH, en_GI, en_GM, en_GU, en_GY, en_HK, en_IE, en_IL, en_IM, en_IN, en_IO, en_JE, en_JM, en_KE, en_KI, en_KN, en_KY, en_LC, en_LR, en_LS, en_MG, en_MH, en_MO, en_MP, en_MS, en_MT, en_MU, en_MV, en_MW, en_MY, en_NA, en_NF, en_NG, en_NL, en_NR, en_NU, en_NZ, en_PG, en_PH, en_PK, en_PN, en_PR, en_PW, en_RW, en_SB, en_SC, en_SD, en_SE, en_SG, en_SH, en_SI, en_SL, en_SS, en_SX, en_SZ, en_TC, en_TK, en_TO, en_TT, en_TV, en_TZ, en_UG, en_UM, en_US, en_US_POSIX, en_VC, en_VG, en_VI, en_VU, en_WS, en_ZA, en_ZM, en_ZW, es, es_419, et, et_EE, fa, fa_AF, fa_IR, fi, fi_FI, fil, fil_PH, fr, fr_BE, fr_BF, fr_BI, fr_BJ, fr_BL, fr_CA, fr_CD, fr_CF, fr_CG, fr_CH, fr_CI, fr_CM, fr_DJ, fr_DZ, fr_FR, fr_GA, fr_GF, fr_GN, fr_GP, fr_GQ, fr_HT, fr_KM, fr_LU, fr_MA, fr_MC, fr_MF, fr_MG, fr_ML, fr_MQ, fr_MR, fr_MU, fr_NC, fr_NE, fr_PF, fr_PM, fr_RE, fr_RW, fr_SC, fr_SN, fr_SY, fr_TD, fr_TG, fr_TN, fr_VU, fr_WF, fr_YT, gu, gu_IN, he, he_IL, hi, hi_IN, hi_Latn, hi_Latn_IN, hr, hr_BA, hr_HR, hu, hu_HU, id, id_ID, it, it_CH, it_IT, it_SM, it_VA, ja, ja_JP, kn, kn_IN, ko, ko_KP, ko_KR, lt, lt_LT, lv, lv_LV, ml, ml_IN, mr, mr_IN, ms, ms_BN, ms_ID, ms_MY, ms_SG, nb, nb_NO, nb_SJ, nl, nl_AW, nl_BE, nl_BQ, nl_CW, nl_NL, nl_SR, nl_SX, nn, nn_NO, no, pl, pl_PL, pt, pt_AO, pt_BR, pt_CH, pt_CV, pt_GQ, pt_GW, pt_LU, pt_MO, pt_MZ, pt_PT, pt_ST, pt_TL, ro, ro_MD, ro_RO, ru, ru_BY, ru_KG, ru_KZ, ru_MD, ru_RU, ru_UA, sd, sd_Deva, sd_Deva_IN, sk, sk_SK, sl, sl_SI, sr, sr_Cyrl, sr_Cyrl_BA, sr_Cyrl_ME, sr_Cyrl_RS, sr_Cyrl_XK, sr_Latn, sr_Latn_BA, sr_Latn_ME, sr_Latn_RS, sr_Latn_XK, sv, sv_AX, sv_FI, sv_SE, sw, sw_CD, sw_KE, sw_TZ, sw_UG, ta, ta_IN, ta_LK, ta_MY, ta_SG, te, te_IN, th, th_TH, tr, tr_CY, tr_TR, uk, uk_UA, ur, ur_IN, ur_PK, uz, uz_Cyrl, uz_Cyrl_UZ, vi, vi_VN, yo, yo_BJ, zh, zh_CN, zh_Hans, zh_Hans_HK, zh_Hans_MO, zh_TW 
But I don't know where to find this list as a resource that's automatically kept up to date.

**Comment by Christoph142** [comment]
No, I don't. This list is a manual console printout from the chromium source code I have been working on. I don't know about any readily available list. Hence this issue with the documentation. 🙈

**Comment by jpmedley** [comment]
#7110 updates the list of language code supported in Chrome Web Store. There are more improvements to come.

**Comment by Christoph142** [comment]
@AmySteam the info at https://developer.chrome.com/docs/extensions/reference/i18n/#supported-locales is still wrong / misleading.

**Comment by jpmedley** [comment]
@AmySteam I have an update that I can't seem to get back to.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at[https://issuetracker.google.com/issues/309981764]( https://issuetracker.google.com/issues/309981764).
