### ISSUE TITLE
Cannot clear HSTS settings in Chrome.  (version 116)

### ISSUE THREAD

**Issue by luasyang0626** [GoogleChrome/developer.chrome.com#7111]
**Describe the bug**
Removing HSTS settings in Chrome was possible in version 115 of Chrome, since updating to version 116 removing HSTS settings in Chrome does not work.

**To Reproduce**
1. Go to chrome://net-internals/?#hsts
2. Delete the domain security policy.
3. Clear cache
4. Reconnect the site you just deleted. (the site is http only)
5. See error "ERR_CONNECTION_TIMED_OUT".

**Expected behavior**
HSTS settings can be removed.

**Desktop (please complete the following information):**
 - OS: [Windows, MacOS]
 - Browser [chrome]
 - Version [116.0.5845.96 ((official version)) (arm64)]

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
