### ISSUE TITLE
[EXT-TUTORIAL] <pop up messages>

### ISSUE THREAD

**Issue by codingmuse** [GoogleChrome/developer.chrome.com#7121]
### What would this tutorial do?

I want to make a google extension that motivates students. So I basically want to the google extension to work by having motivational messages pop up on the corner of the screen every 30 or so minutes. I want the messages to be randomly picked from a list that has about 75+ motivational quotes and messages.

### What lessons would this tutorial teach?

first i want to understand how to design the box that will contain the message
secondly how to add a timer to a google chrome extension
lastly dealing with the extensions permissions, details, icons etc

### Extension components

Popup

### Anything else?

![popupexample](https://github.com/GoogleChrome/developer.chrome.com/assets/142631323/d50105df-6acb-4aa7-8bff-a3f7f7c374a7)

something like this popping up at the bottom right corner of the screen. this should also be something that the student can switch on and off

**Comment by AmySteam** [comment]
Thanks @codingmuse for this tutorial suggestion! Great idea :) We will add it to our list for a full tutorial or a sample.

**Comment by oliverdunk** [comment]
Closing this since we don't really track specific tutorial suggestions, but as Amy mentioned, we'll definitely keep this in mind.
