### ISSUE TITLE
"supportsNofityTag" typo

### ISSUE THREAD

**Issue by brycethorup** [GoogleChrome/developer.chrome.com#7122]
**Describe the bug**
Found a typo in the `chrome.fileSystemProvider` API documentation.

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/reference/fileSystemProvider/#method-notify'
2. Notice the reference to `supportsNofityTag` in the second sentence.

**Expected behavior**
This should read `supportsNotifyTag` not `supportsNofityTag` .

**Comment by jpmedley** [comment]
Here's the CL: https://chromium-review.git.corp.google.com/c/chromium/src/+/4989653

**Comment by jpmedley** [comment]
The fix has deployed.
