### ISSUE TITLE
My theme got destroyed by the newest Chrome update

### ISSUE THREAD

**Issue by mikulabc** [GoogleChrome/developer.chrome.com#7127]
**The bug**
Here is how [the theme](https://chrome.google.com/webstore/detail/redhat-seo-theme/ekepcnlcedknbaimlkfobjjkijlidcdb) used to look before the newest Chrome update:
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/423215/b428165c-ec07-43fc-b8f5-8c94d145e202)

And here is how it looks in Version 116.0.5845.97 (the second red line below the active tab was never there before):
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/423215/566bec21-793d-4e7e-8874-6be6e0159d44)

it should only be a red line on top of the active tab, as seen here:
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/423215/ab06c5c5-0fae-499f-85ce-ee8326c7e900)

To Reproduce, install this chrome theme https://chrome.google.com/webstore/detail/redhat-seo-theme/ekepcnlcedknbaimlkfobjjkijlidcdb

**Desktop:**
 - OS: Windows 10 Pro with the newest updates
 - Browser: Google Chrome Version 116.0.5845.97 (Official Build) (64-bit)

**Comment by mikulabc** [comment]
Could you please take a look? @jecfish @jakearchibald @heyawhite @dotproto @sebastianbenz @ericlaw1979 @matthiasrohmer @devnook @rachelandrew @awfuchs thanks a lot, I appreciate all the hard work you do!

**Comment by mikulabc** [comment]
I believe this update here destroyed my theme https://chromereleases.googleblog.com/2023/08/stable-channel-update-for-desktop_15.html

**Comment by rachelandrew** [comment]
@mikulabc this repo is for issues with the site or content at developer.chrome.com and not for Chrome issues, or those with themes. I would suggest trying some of the places listed here https://developer.chrome.com/docs/extensions/gethelp/

**Comment by mikulabc** [comment]
ok thanks @rachelandrew i just dont see hope that my issue will be looked at in the next few years unless someone can push it forward to the right people, as this is something that worked and now got destroyed by the newest update, maybe i did the right thing by posting it here? https://bugs.chromium.org/p/chromium/issues/detail?id=1474158
