### ISSUE TITLE
Incorrect description for the CSSInjection object

### ISSUE THREAD

**Issue by materialknight** [GoogleChrome/developer.chrome.com#7141]
In the page "https://developer.chrome.com/docs/extensions/reference/scripting/#type-CSSInjection", in the section describing the properties of the CSSInjection object, the descriptions of the "css" and "file" properties incorrectly state:

(`css` string optional) "A string containing the CSS to inject. _Exactly one of `files` and `css` must be specified_."
(`file` string[] optional) "The path of the CSS files to inject, relative to the extension's root directory. _Exactly one of `files` and `css` must be specified_."

They should say instead:

(`css` string optional) "A string containing the CSS to inject. **Either `css` or `files` must be specified**."
(`file` string[] optional) "The path of the CSS files to inject, relative to the extension's root directory. **Either `css` or `files` must be specified**."

I wanted to submit a pull request myself, but I couldn't find the page to be edited 😅, would it be possible for each page in the API reference to have a direct link to edit that specific page, as it's already done for articles with the link that says "improve article"?

**Comment by jpmedley** [comment]
CL here: https://chromium-review.git.corp.google.com/c/chromium/src/+/4988056

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. Joe seems to be handling so I’ve moved the issue to our new tracker and assigned it to him. You can see it at: https://issuetracker.google.com/issues/310277006
