### ISSUE TITLE
Support granting read-only permissions to specific Chrome Web Store group members.

### ISSUE THREAD

**Issue by cb-bradbeebe** [GoogleChrome/developer.chrome.com#7147]
_⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com._

**Is your feature request related to a problem? Please describe.**
Chrome Web Store has an all-or-nothing permission model so if we want to grant a group member read-only permissions to our Chrome Web Store account w/o any write/publishing capabilities, we currently do not have that ability.

It is also called out as a warning in the [official documentation](https://developer.chrome.com/docs/webstore/group-publishers/#adding-developers-to-or-removing-them-from-the-group-publisher) given the all-or-nothing permissions model.

**Describe the solution you'd like**
As an engineer part of a team that owns Google Chrome Extension(s), it would be helpful if read-only permissions could be granted to specific team members within our Google Chrome Web Store account.

This would allow team members to be able to independently look up the statuses and timestamps of each Chrome Web Store submission (e.g. when trying to come up with timelines for a incident report) without needing to constantly go through a sometimes small subset of team members to always retrieve that information.

Google already allows such granular read-only permissions with the Play Store for teams that own native Android apps.

**Describe alternatives you've considered**
The permissions model is all-or-nothing so only alternative to manually request from our team's Chrome Web Store account admins to look up information for us.

**Additional context**
N/A

**Comment by AmySteam** [comment]
This is a great idea and your use case makes sense. Just so this suggestion goes straight to the Chrome Web Store team, I would recommend submitting it to the [One Stop Support](https://support.google.com/chrome_webstore/contact/one_stop_support), under "feature suggestion" 
![Screenshot 2023-10-06 at 17 13 46](https://github.com/GoogleChrome/developer.chrome.com/assets/37001393/f70b2df9-61ca-4c02-ae42-f70429d2239a)
