### ISSUE TITLE
Content Feedback: Clarify what "handling" user data means

### ISSUE THREAD

**Issue by vdsabev** [GoogleChrome/developer.chrome.com#715]
Hi Chrome dev team 👋 I'm the developer of [Image Downloader](https://github.com/PactInteractive/image-downloader), an open-source extension for Google Chrome.
I'm having some trouble interpreting the [Privacy Policy & Secure Handling Requirements](https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/docs/webstore/user_data/index.md), more specifically this part:

> Generally, by "handle" we mean collecting, transmitting, using, or sharing user data.

Followed by this:

> Clipping or scraping content from a website that the user visits, such as taking screenshots or capturing data from a web page

Obviously Image Downloader needs to extract the images from the web page content to allow users to download them. However, the extension does not modify, store, or send that content to a remote server in any way - it processes everything internally, and once it's done downloading the content there's no trace of it anywhere (other than the user's computer).

Do I need to disclose that the extension "handles" the content of the web page, seeing as:
1. Accessing that content is the primary purpose of this extension (not much of an image downloader if you can't get the images from a page's content)
2. The content doesn't go anywhere outside the extension
3. The content is only accessed when users explicitly click on the extension popup icon (not passively in a background script)
4. An explicit disclosure may lead users to incorrectly believe their data is being misused

Finally, is it possible to further clarify the [Privacy Policy & Secure Handling Requirements](https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/docs/webstore/user_data/index.md) so that this is clearer in the future?
I'd appreciate your help in clarifying this use case.

**Comment by robdodson** [comment]
tagging @awfuchs for their thoughts. I do know that we have some upcoming policy page updates but I don't know off the top of my head if they will address this issue.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311793829
