### ISSUE TITLE
Missing brackets on code snippet

### ISSUE THREAD

**Issue by santiago-salinas** [GoogleChrome/developer.chrome.com#7155]
In https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/
Step 4 the following code snippet is shown:

```
const extensions = 'https://developer.chrome.com/docs/extensions'
const webstore = 'https://developer.chrome.com/docs/webstore'

chrome.action.onClicked.addListener(async (tab) => {
  if (tab.url.startsWith(extensions) || tab.url.startsWith(webstore)) {
    // Retrieve the action badge to check if the extension is 'ON' or 'OFF'
    const prevState = await chrome.action.getBadgeText({ tabId: tab.id });
    // Next state will always be the opposite
    const nextState = prevState === 'ON' ? 'OFF' : 'ON'

    // Set the action badge to the next state
    await chrome.action.setBadgeText({
      tabId: tab.id,
      text: nextState,
    });
...
```

If this code is added to the background.js script it won't compile when reloading the extension
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/48341470/5877be2c-91c7-45b8-b53e-ba67c98ab5ab)
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/48341470/ce2e8f77-7760-48eb-8b15-94c35c3d1066)

**Comment by dstmarthe** [comment]
Thanks for raising this. cWe are moving to a new platform and content on this site is now frozen. Since this seems to have been resolved in the pr, I'll be closing this.
