### ISSUE TITLE
Accessibility issue with Codepen sample in style queries article

### ISSUE THREAD

**Issue by SimonVanherweghe** [GoogleChrome/developer.chrome.com#7158]
**Describe the bug**
Dear @una, it almost feels like nitpicking, but it is not possible to click the label for the radio buttons in the 'Dynamic Style Queries' example in the [Getting Started with Style Queries](https://developer.chrome.com/blog/style-queries/) article. The "for" attribute in the `label` is present, but the `input` tags are missing an "id" attribute.

**To Reproduce**
1. Go to [Dynamic Style Query](https://codepen.io/web-dot-dev/pen/GRXZLvW) on codepen
2. Click on a label
3. The radio button is not selected

**Expected behavior**
The radio button should be selected

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310006206
