### ISSUE TITLE
Error 404 Page not found!

### ISSUE THREAD

**Issue by Anuragd275** [GoogleChrome/developer.chrome.com#7173]
I'm trying to develop a Chrome extension and I got an error, here is the link I was displayed on my browser's console which says that the page I'm trying to access, can not be found!

Link: https://developer.chrome.com/docs/extensions/manifest.html#permissions
My browser: Chrome (Version 116.0.5845.110)

**Comment by tlstommy** [comment]
What manifest version are you using? 

If its v3, try this link: https://developer.chrome.com/docs/extensions/mv3/manifest/#permissions

here is the link to the permissions page: https://developer.chrome.com/docs/extensions/mv3/declare_permissions/

**Comment by Anuragd275** [comment]
Hey @tlstommy! I'm using the manifest version **3**.

Thanks for providing the links they were very useful, I got what I was looking for.
