### ISSUE TITLE
Move frameId reference to a separate page

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#719]
We should pull frame IDs and tab IDs into a central article; both are used far more broadly than just the tabs / webNavigation APIs

_Originally posted by @rdcronin in https://github.com/GoogleChrome/developer.chrome.com/pull/663#r620699119_

**Comment by robdodson** [comment]
@dotproto would this be something you or andy would own?

**Comment by dstmarthe** [comment]
I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/312258027
