### ISSUE TITLE
Table of Contents covers table content

### ISSUE THREAD

**Issue by AdamRaichu** [GoogleChrome/developer.chrome.com#7198]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Table of contents covers table content on https://developer.chrome.com/docs/extensions/mv3/match_patterns/.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/match_patterns/.
2. Scroll down to the `✅ Valid patterns` heading.
3. Scroll down until the header row of the table is no longer visible.

**Expected behavior**
The table of contents should not cover the table.

**Screenshots**

![image](https://github.com/GoogleChrome/developer.chrome.com/assets/91494019/582b3c4d-05b2-4e2b-81cf-d7fedd57ae95)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 116.0.5845.111 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
I did not check to see if this was a problem on other pages.

**Comment by AdamRaichu** [comment]
Note: `window.innerWidth` had a value of 1536 when issue was present.

**Comment by AmySteam** [comment]
This will be fixed one PR #7215 is merged
