### ISSUE TITLE
Event section is missing return types and filters

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#72]
@samthor commented on [Mon Dec 07 2020](https://github.com/GoogleChrome/dcc-private/issues/464)

The historic event section describes the function that is announced completely.

It also often has a section on filters which we aren't rendering properly.

**Comment by robdodson** [comment]
this is a migrated issue from the old repo and I think it relates to API reference so tentatively assigning to Sam

**Comment by samthor** [comment]
Closing in favor of #285. (Yes I know that came later, but it's clearer)
