### ISSUE TITLE
Chrome for Testing: Stable (upcoming) version is not available and shows 404 http error when try to download this

### ISSUE THREAD

**Issue by maksr13** [GoogleChrome/developer.chrome.com#7205]
**Describe the bug**
Stable (upcoming) version is not available and shows 404 http error when try to download this

**To Reproduce**
1. Go to https://googlechromelabs.github.io/chrome-for-testing/#stable
2. Observe  Stable (upcoming)

**Expected behavior**
Status should show green tick

**Actual behavior**
Status shows 'Red cross' and it cases issues with running auto-tests

**Screenshots**
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/22858879/8b2deb5e-1c9e-433e-b1a1-71a5f601c9c0)

**Comment by myakura** [comment]
@maksr13 you might want to ask the question in the dedicated repository https://github.com/GoogleChromeLabs/chrome-for-testing/

**Comment by thiagowfx** [comment]
Closing as https://github.com/GoogleChromeLabs/chrome-for-testing/issues/54 was also closed.
