### ISSUE TITLE
Chrome Browser 116 will crash when trying to copy large objects from console using copy() function

### ISSUE THREAD

**Issue by kumar-dheemanth** [GoogleChrome/developer.chrome.com#7220]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PrakashC1** [comment]
Hi,
I am also facing same issue recently. When I trying to copy any large object from sessionStorage my chrome window getting closed. Even if i use copy command of developer tool, it crashes.

Chrome version: Version 118.0.5993.118 (Official Build) (64-bit)

**Comment by rachelandrew** [comment]
This is for issues with the https://developer.chrome.com/ site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com/.
