### ISSUE TITLE
Content feedback (extensions): focus_mode `manifest.json` does not match code on github

### ISSUE THREAD

**Issue by Noko-Rammutla** [GoogleChrome/developer.chrome.com#7227]
While going through the focus mode tutorial, I discovered that the manifest on the site does not match the manifest on github. Which caused the extension to throw an error on initial load.

Tutorial Page: https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-focus-mode/
Github Page: https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/functional-samples/tutorial.focus-mode/manifest.json

**Error Message:**
```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'setBadgeText')
    at chrome-extension://mndgigiljalfkdpbahkkedjpbhapkhik/background.js:2:19
```

I believe the contents of the `manifest.json` file in step 1 should be change to:

```
{
    "manifest_version": 3,
    "name": "Focus Mode",
    "description": "Enable focus mode on Chrome's official Extensions and Chrome Web Store documentation.",
    "version": "1.0",
    "icons": {
      "16": "images/icon-16.png",
      "32": "images/icon-32.png",
      "48": "images/icon-48.png",
      "128": "images/icon-128.png"
    },
    "background": {
      "service_worker": "background.js"
    },
    "action": {}
    }
  }
```

**Comment by AmySteam** [comment]
Hi @Noko-Rammutla! Thanks for the feedback :)

The idea behind this step-by-step tutorial is that you complete all the steps before loading the extension. This is one of many ways to write a tutorial :)

But it's probably a good idea to be able to load the extension on each step without getting an error! Great suggestion 💯
