### ISSUE TITLE
[suggestion] close tabs within a tabs group

### ISSUE THREAD

**Issue by its-dibo** [GoogleChrome/developer.chrome.com#7240]
I hope this is the right place to issue a suggestion for improving the Google Chrome browser, if not, accept my apologizes and let me know where to issue such requests

modify the behavior of 'close tabs to right' and 'close other tabs' inside a tabs group to work within the group itself instead of closing all other tabs

you may add a feature to press and hold 'shift' to run these commands globally instead of within the current group 

![image](https://github.com/GoogleChrome/developer.chrome.com/assets/57308531/d257e958-db8f-4774-8d50-7a22988e5337)

**Comment by tophf** [comment]
This repository is for the documentation. For the browser problems use https://crbug.com.
