### ISSUE TITLE
Does not show how to "getTabId". It's just left for the user to guess how to fill in this code

### ISSUE THREAD

**Issue by greggman** [GoogleChrome/developer.chrome.com#7250]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

Examples are unclear. The example should be functional, not left with parts to be filled in

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/reference/scripting/#injection-targets
2. Try to use the example code

**Expected behavior**

The example code runs

**What happens instead**

The example code is incomplete and assumes the user is already an expert in extension creation

**Comment by AmySteam** [comment]
@greggman Thanks for this! I cannot agree more :) I am working on redoing the examples on this API. I will make sure all the code is included and even link to a sample if it exists.
