### ISSUE TITLE
Chrome DevTools "Log.LogEntry" Protocol is not capturing normal logs but able to capture error and warning logs.

### ISSUE THREAD

**Issue by Shitanshu-CS** [GoogleChrome/developer.chrome.com#7254]
**Describe the bug**
Chrome DevTools "Log.LogEntry" Protocol is not capturing normal logs but able to capture error and warning logs.

**To Reproduce**
We are using https://chromedevtools.github.io/devtools-protocol/tot/Log/#type-LogEntry to get the console logs in our website through chrome plugin. Some weeks back we were able to log normal debug logs/ warnings and Error logs coming in the console panel. But now "Log.LogEntry" event does not throw event for normal logs which are not warning on error.

**Expected behavior**
"Log.LogEntry" event should throw Normal Debug Console Logs 

**Screenshots**
I am able to get the normal logs using https://chromedevtools.github.io/devtools-protocol/tot/Console/ protocol but this is depricated. In the screenshot you can see console logs getting captured in yellow color using "Console.messageAdded" protocol but not getting event for "Log.LogEntry"
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/129953944/8f2a3915-11c1-4caa-8c60-eace3aac9fab)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chrome
 - Version116.0.5845.141

**Smartphone (please complete the following information):**
NA

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
