### ISSUE TITLE
Missing function call in code example

### ISSUE THREAD

**Issue by stoph** [GoogleChrome/developer.chrome.com#7295]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
It seems you are missing the call to fetch in the code example on https://developer.chrome.com/docs/extensions/mv3/tut_analytics/#toc-tracking-pageviews

Currently you have...
window.addEventListener("load", () => {
  ${GA_ENDPOINT}?measurement_id=${MEASUREMENT_ID}&api_secret=${API_SECRET}`,
  {...

It seems like it should be...
window.addEventListener("load", () => {
  fetch(
  `${GA_ENDPOINT}?measurement_id=${MEASUREMENT_ID}&api_secret=${API_SECRET}`,
    {...

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/tut_analytics/#toc-tracking-pageviews
2. Scroll down to the code block
3. See error

**Expected behavior**
The code should include the call to fetch.

**Screenshots**
https://www.christophkhouri.com/tmp/chrome-dev.png

**Desktop (please complete the following information):**
 - OS: macOS 13.5.1
 - Browser: Chrome
 - Version: 116.0.5845.179 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: 16.6.1
 - Browser stock browser, safari

**Additional context**

**Comment by AmySteam** [comment]
Thanks @stoph for reporting this!! 💯 🙂
