### ISSUE TITLE
Videos in multiple articles are not playable in Firefox

### ISSUE THREAD

**Issue by pepelsbey** [GoogleChrome/developer.chrome.com#7317]
**Describe the bug**

The following articles have videos that could not be played in Firefox on any platform because they’re encoded as HEVC/H.265:

- [Four new CSS features for smooth entry and exit animations](https://developer.chrome.com/blog/entry-exit-animations/)
- [New in Chrome 117](https://developer.chrome.com/blog/new-in-chrome-117/)

**To Reproduce**

1. Go to [the article](https://developer.chrome.com/blog/new-in-chrome-117/) in the latest Firefox (119)
2. See “No video with supported format found” error

**Expected behavior**

Videos available in Firefox

**Screenshots**

<img width="700" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/105274/c3d46358-879a-420c-b91a-47430fdced5e">

<img width="300" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/105274/f1bf160e-c416-406c-9a1e-5049fd7af386">

**Desktop:**

 - OS: macOS 14.0
 - Browser: Firefox
 - Version: 119.0 (64-bit)

**Smartphone:**

 - Device: Pixel 3a
 - OS: Android 12
 - Browser: Firefox
 - Version: 119.0

**Additional context**

Firefox [doesn’t support](https://caniuse.com/hevc) HEVC/H.265 format yet. For better compatibility, it’s better to encode videos to H.264.

**Comment by pepelsbey** [comment]
@tropicadri, I believe you’re the author of the article

**Comment by tropicadri** [comment]
I am the author of the article, however I don't own the videos, they come from this article: https://developer.chrome.com/blog/entry-exit-animations/ I'm guessing they don't work there either? I'll pass the issue to Una in case she can fix them. Thanks.

**Comment by pepelsbey** [comment]
Yes, the pictures are broken in another article, too.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue and relevant comments to our new tracker and you can see it at: https://issuetracker.google.com/issues/309981768
