### ISSUE TITLE
Chrome DevTools logo missing on tutorial demo pages

### ISSUE THREAD

**Issue by dege13** [GoogleChrome/developer.chrome.com#7353]
**Describe the bug**
Many DevTools Tips tutorials use live demo pages (https://devtools.glitch.me/). The Chrome DevTools logo on these pages appears to be missing from the server.
Image URL: https://raw.githubusercontent.com/ChromeDevTools/devtools-logo/master/96.png

**To Reproduce**
1. Go to https://devtools.glitch.me/
2. Notice that the logo image is missing.

**Expected behavior**
The logo should be on the web server and accusable.

**Screenshots**
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/3587941/3507d161-4e2d-4c79-8d02-defd78356e68)
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/3587941/7e16c2eb-aee0-49a6-b542-5b5b38ce3f2d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 116.0.5845.188 (Official Build) (64-bit)

**Comment by jecfish** [comment]
Fixed.
