### ISSUE TITLE
Update link to include scheme

### ISSUE THREAD

**Issue by charisTheo** [GoogleChrome/developer.chrome.com#7384]
Update link to include scheme like so `https://form-problems.glitch.me/`

https://github.com/GoogleChrome/developer.chrome.com/blob/7770349adb7df729ebe3afd60ba36fcef6c6dfcf/site/en/blog/devtools-autofill/index.md?plain=1#L132

Currently the above resolves to `https://developer.chrome.com/blog/devtools-autofill/form-problems.glitch.me` when deployed.

**Comment by rachelandrew** [comment]
This is fixed, thanks!
