### ISSUE TITLE
devtools from chromebook to remote debug webapps ( pixel 5 ) - no device in chrome://inspect

### ISSUE THREAD

**Issue by rowntreerob** [GoogleChrome/developer.chrome.com#7385]
this is standard , remote debugging and has never worked on a new chromebook w crostini, linux and ADB setup. 

The usb cable is good. dev options on the device are set for usb debug is ON

phone is at chrome 117 while laptop is on 116 ( stabile ) . this may be issue if the rule is that laptop's chrome MUST be newer release than on the device. 

IMO , per the docs , all i have todo is follow [this](https://support.google.com/chromebook/answer/9770692?hl=en) to get/install ADB on the laptop as all other testing/dev stuff has been fine on the laptop. 

may not be relevant but in term, there is no evidence of SDK or ADB packages according to "dpkg --get-selections"  but i dont think its relevant.

What do i need todo in order to get my phone to show up in "inspect devices" in chrome?

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
