### ISSUE TITLE
WebdriverIO not avaialbe in Recorder Test

### ISSUE THREAD

**Issue by nair-sumesh** [GoogleChrome/developer.chrome.com#7396]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Export and Code does not list the WebDriverIO extension.

<img width="640" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/12034160/cb149ccb-de68-47bc-b5f3-aafb3b770732">

**Expected behavior**
Should be able to export or view the Code version for Webdriver IO

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOs
 - Browser : Chrome
 - Version : 117.0.5938.92

**Additional context**

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
