### ISSUE TITLE
Oversized 9 MB image served to Safari on "We are Chrome for Developers" blogpost

### ISSUE THREAD

**Issue by rcaliman-apple** [GoogleChrome/developer.chrome.com#7403]
**Describe the bug**

The blog post [We are Chrome for Developers](https://developer.chrome.com/blog/we-are-chrome-for-developers/) serves a 9 megabytes webp/gif? animated image to Safari.
Chrome receives a ~200 KB AVIF.

Probably a misconfiguration of the imgix image server.

**To Reproduce**
1. Use Safari and go to https://developer.chrome.com/blog/we-are-chrome-for-developers/
2. Open Safari Web Inspector (CMD+Option+I or right-click > Inspect Element)
3. Switch to the Network tab
4. Select the URL for the image: https://wd.imgix.net/image/kheDArv5csY6rvQUJDbWRscckLr1/ijjUVcPHYBhjZeNMud6n.gif 
You may have to reload the page and/or enable "Disable caches" at the top of the Network tab
5. Look in the Response section at Content-Length and Content-Type headers

**Expected behavior**

A reasonably sized image should be served.

**Screenshots**

Safari Web Inspector
<img width="1277" alt="Screenshot 2023-09-28 at 12 22 01" src="https://github.com/GoogleChrome/developer.chrome.com/assets/105809798/c6f2d1f7-0f76-4ddd-86e8-b73db37b3ab2">

Chrome DevTools:
<img width="1273" alt="Screenshot 2023-09-28 at 12 22 11" src="https://github.com/GoogleChrome/developer.chrome.com/assets/105809798/ffe53c9a-d8b0-42d2-8cf4-fbbf77355b3e">

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/310197452
