### ISSUE TITLE
chrome prefilled password hiding after password hide/show button clicked.

### ISSUE THREAD

**Issue by manishShaw01** [GoogleChrome/developer.chrome.com#7411]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
hi, we are using react with typescipt for our frontend app, noticed this bug only in chrome not in other browsers, as the login form's prefiled password is getting hidden(value is persistent/still there) on toggle show/hide password button. seems like chrome is hiding it, when the password type is changing from 'password' to 'text'. see the video below
and this is happening only for the chrome prefilled password, not otherwise. user Enter passwords are working fine.

https://github.com/GoogleChrome/developer.chrome.com/assets/127931500/6f38e841-b6c3-480c-b092-9a0dee555c9f

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser :chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manishShaw01** [comment]
this issue was for chrome.

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
