### ISSUE TITLE
Anchor links not behaving correctly across developer.chrome.com

### ISSUE THREAD

**Issue by oliverdunk** [GoogleChrome/developer.chrome.com#7412]
**Describe the bug**
Anchor links are not going to the correct place across a number of pages. Examples:

- https://developer.chrome.com/docs/privacy-sandbox/proposal-lifecycle/#scaled-adoption
- https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#property-MAX_NUMBER_OF_ENABLED_STATIC_RULESETS

**To Reproduce**

CMD + click on any of the links above.

**Expected behavior**

Page scrolls to expected position.

**Desktop (please complete the following information):**

Seems to only impact Chrome.

**Additional context**

This seems interestingly similar to the following bugs:

- https://github.com/mdn/yari/issues/8049
- https://bugs.chromium.org/p/chromium/issues/detail?id=1417660

**Comment by Jamal985610** [comment]
> **বাগ বর্ণনা করুন** অ্যাঙ্কর লিঙ্কগুলি বেশ কয়েকটি পৃষ্ঠা জুড়ে সঠিক জায়গায় যাচ্ছে না। উদাহরণ:
> 
> * https://developer.chrome.com/docs/privacy-sandbox/proposal-lifecycle/#scaled-adoption
> * https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#property-MAX_NUMBER_OF_ENABLED_STATIC_RULESETS
> 
> **বংশবৃদ্ধি**
> 
> CMD + উপরের যে কোনো লিঙ্কে ক্লিক করুন।
> 
> **প্রত্যাশিত আচরণ**
> 
> পৃষ্ঠা প্রত্যাশিত অবস্থানে স্ক্রোল করে।
> 
> **ডেস্কটপ (অনুগ্রহ করে নিম্নলিখিত তথ্য সম্পূর্ণ করুন):**
> 
> মনে হচ্ছে শুধুমাত্র Chrome কে প্রভাবিত করে।
> 
> **অতিরিক্ত প্রসঙ্গ**
> 
> এটি নিম্নলিখিত বাগগুলির সাথে আকর্ষণীয়ভাবে অনুরূপ বলে মনে হচ্ছে:
> 
> * [ইউআরএলে স্ক্রোল করুন ফ্র্যাগমেন্ট আর ক্রোমিয়াম ব্রাউজারে কাজ করে না  mdn/yari#8049](https://github.com/mdn/yari/issues/8049)
> * https://bugs.chromium.org/p/chromium/issues/detail?id=1417660
