### ISSUE TITLE
Affordances misaligned in samples search box

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#7414]
This image shows the problem.

![image](https://github.com/GoogleChrome/developer.chrome.com/assets/8204171/d9a05e6c-de84-410e-884a-0685cf92ee6c)

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.

**Comment by jpmedley** [comment]
@oliverdunk Is this a problem on the new site and if so, is this issue captured anywhere?

**Comment by oliverdunk** [comment]
@jpmedley This is fixed on the current site: https://developer.chrome.com/docs/extensions/samples/. Has this been migrated to the new site yet? I hadn't seen it if so.

**Comment by jpmedley** [comment]
I don't know either.

**Comment by dstmarthe** [comment]
Not sure if this is done, so I'll be migrating it soon unless there is no need.

**Comment by dstmarthe** [comment]
The issue has been moved. I omitted my comments and the mentions if that's okay. 
https://issuetracker.google.com/issues/324482151
