### ISSUE TITLE
404 in Chrome 117 deprecations and removals page

### ISSUE THREAD

**Issue by NicoDelgadoReservo** [GoogleChrome/developer.chrome.com#7428]
**Describe the bug**
The link [Desuso y eliminaciones de Chrome 117](https://developer.chrome.com/es/blog/deps-rems-117/) is broken in spanish page

**To Reproduce**
1. Go to https://developer.chrome.com/es/blog/new-in-chrome-117/
2. Click on "[Desuso y eliminaciones de Chrome 117](https://developer.chrome.com/es/blog/deps-rems-117/)"
3. See error 404

**Expected behavior**
Can see the Chrome 117 deprecations and removals

**Screenshots**
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/101582104/37c4f2ba-1999-4bcb-8f17-04ec75624d13)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS 
 - Browser chrome
 - Version Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by chrisl-syscon** [comment]
The link from both english and spanish pages is still broken.
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/57502575/aad6e3d2-4e6e-4887-ba8d-eaafdf49371f)

![image](https://github.com/GoogleChrome/developer.chrome.com/assets/57502575/280c4a0c-2bb3-48dc-85b7-4db26cce40cc)
