### ISSUE TITLE
Wrong right-to-left display with <bdo>

### ISSUE THREAD

**Issue by Prilop** [GoogleChrome/developer.chrome.com#7443]
[bdo.html.txt](https://github.com/GoogleChrome/developer.chrome.com/files/12814264/bdo.html.txt)

   <p><bdo dir='rtl'>xyz</bdo> 0</p>
is displayed as
    0 zyx

The display shall be
    zyx 0

Android 11
Chrome 117

**Comment by Prilop** [comment]
＜p＞＜bdo dir='rtl'＞xyz＜/bdo＞ 0＜/p＞
is displayed as
    0 zyx
 
The display shall be
    zyx 0

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
