### ISSUE TITLE
Navigation drawer is missing the full logo lockup

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#747]
![image](https://user-images.githubusercontent.com/1066253/117492229-2b007380-af26-11eb-812c-5f734abe7fb6.png)

I think this is supposed to be showing the chrome logo and the 'developers' text

**Comment by samthor** [comment]
I intentionally did this to reduce the size of every page's payload. We're duplicating the same SVG many times. My 2c is that it's just obvious what site you're on already.

**Comment by robdodson** [comment]
I'm not much of an svg expert, but do you know if it's possible to use `<use>` to reference one of the SVGs that we've already inlined? From a design perspective I felt like it looked broken, almost like we forgot to include the rest of our site logo.
