### ISSUE TITLE
Font-size changes after scrolling down on pages with no CSS and no JS

### ISSUE THREAD

**Issue by ChrisRadny** [GoogleChrome/developer.chrome.com#7470]
Font-size changes to a smaller size after reloading and scrolling down on pages with no CSS and no JS.

I have uploaded a video on X: [https://x.com/ChrisRadny/status/1710997689335173559](https://x.com/ChrisRadny/status/1710997689335173559)

Chrome 117.0.5938.153
Android 13
Galaxy Tab A7 Lite
SM-T225

UPDATE:
I investigated further. Removing the viewport meta tag from the head fixes the issue:
`<meta name="viewport" content="width=device-width, initial-scale=1.0" />`

**Comment by myakura** [comment]
@ChrisRadny you might want to open an issue against https://crbug.com/new as this repository is for https://developer.chrome.com/ _website_ and not for Chrome (or Chromium) browser itself.

**Comment by ChrisRadny** [comment]
Sorry -> [https://bugs.chromium.org/p/chromium/issues/detail?id=1490898](https://bugs.chromium.org/p/chromium/issues/detail?id=1490898)
