### ISSUE TITLE
Rename Twitter to X

### ISSUE THREAD

**Issue by mcmd** [GoogleChrome/developer.chrome.com#7481]
In the post author macro, different socials are shown. One of them is [Twitter](https://github.com/GoogleChrome/developer.chrome.com/blob/1d4616cecea1b977484a43406cb18a52081d0cc7/site/_includes/macros/post-author.njk#L37C75-L37C82), which was rebranded to X.

Should the macro be modified to show "_X_" instead of "_Twitter_" (this could be done by just changing the String, no need to change author.twitter if you don't want to)?

**Comment by rachelandrew** [comment]
Closing as this relates to the old infrastructure.
