### ISSUE TITLE
Devtools performance crashes when assigning a javascript expression to window.location.href

### ISSUE THREAD

**Issue by Brielleowl** [GoogleChrome/developer.chrome.com#7486]
**Describe the bug**
The devtools performance crashes with error "Recording Failed" when recording a site that contains js script assigning javascript expression to `winodw.location.href`(etc. `window.location.href="javascript:\"console.log(1)\""`)

**To Reproduce**
1. Create a html file with     `<script> window.location.href =  "javascript:\"console.log(1)\"" </script>`
2. Start local server and open http://localhost:${port_number}
3. Open devtools then go to performance and click reload button
4. It will pop up the error "Recording Failed" as described below

**Expected behavior**
It should be able to record performance without error

**Screenshots**
Error:
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/49528865/2bff3ccb-d678-46d9-a552-aba4e3541d14)
screen recording:
https://github.com/GoogleChrome/developer.chrome.com/assets/49528865/706f1911-a5c2-4b09-9760-534b13314af5

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: Chrome
 - Version: 116.0.5845.140

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
