### ISSUE TITLE
Performance - Line Profiling Documentation 

### ISSUE THREAD

**Issue by GlacialBoy** [GoogleChrome/developer.chrome.com#7495]
**Describe the bug**
I've followed the tutorial described in https://developer.chrome.com/docs/devtools/performance/#find_the_bottleneck and I found some inconsistencies with the current version of DevTools Chrome 117

"For CPU, select 2x slowdown. DevTools throttles your CPU so that it's 2 times slower than usual." 
I have only 4x and 6x slowdown

And in the "Find the bottleneck" on point 7
"In the Summary tab, click the app.js:70 link under Layout Forced. DevTools takes you to the line of code that forced the layout."

I cannot see the line profiling expressed in the image
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/2997749/b31c9749-0df3-4a96-a0c1-a922e565d31f)

**To Reproduce**
1. Go to https://googlechrome.github.io/devtools-samples/jank/
2. Perform a Performance Profile
3. Go to Source Code

**Expected behavior**
See the line profile (time spent on executing the single line) or having an updated documentation is the feature is not available anymore

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GlacialBoy** [comment]
@matthiasrohmer Why this issue has been closed?

**Comment by matthiasrohmer** [comment]
Sorry, I closed this accidentally.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’ve moved to a new platform and so we’ll address this over there (hence why I will be closing this here now). I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324311902
