### ISSUE TITLE
Issue(s) with docs/extensions/mv3/tut_oauth/

### ISSUE THREAD

**Issue by JellySlater** [GoogleChrome/developer.chrome.com#750]
https://developer.chrome.com/docs/extensions/mv3/tut_oauth/

Under <h1>Initiate first OAuth flow</h1> header the codeblock has the name as
`{
  "name": "OAuth Tutorial FaceBlcok",
  ...`
  
  Where nearly everywhere else prior has it as: ` "OAuth Tutorial FriendBlock", `
  
I feel like this page is bit out of date: 

Another example being under the <h1>Upload to the developer dashboard</h1>header where it's the process to obtain the key field is 

`Find the extension under Your Listings and click on more info. From the popup, copy the public key and add it to the manifest inside the unzipped directory under the "key" field.`

In actuality it's on: https://chrome.google.com/webstore/devconsole/ (On the lefthand side there exists a menu where `Store listing` is the default option selected and `package` the menu item above it is actually where you need to click to obtain the public key.

<h1>Create first API request</h1>

The writeup says ``The extension should log a JSON object that includes an array of people/account_ids under the memberResourceNames field.``; but upon execution the JSON object returned looks as follows:

`
{
    "resourceName": "contactGroups/all",
    "groupType": "SYSTEM_CONTACT_GROUP",
    "name": "all",
    "formattedName": "All Contacts"
}
`

and I am failing to see this memberResourceNames field, only resourceName: contactGroups/all which is not an array. So, when it the proceeding lines of code in oauth.js
`let returnedContacts = data.memberResourceNames;
            for (let i = 0; i < returnedContacts.length; i++)`
            
I attempt to reference a field that doesn't exist and try to read the property (length) of undefined I'm throwing an error.
Furthermore when attempting to click the hyperlink in the 

<h1> Block faces </h1> 
Now that the extension is returning a list of the user's contacts, it can make additional requests to <a href="https://developers.google.com/people/v1/read-people">retrieve those contact's profiles and information</a>. The extension will use the memberResourceNames to retrieve the photo information of user contacts. Update oauth.js to include the following code.

I'm hyperlink leads to a 404. https://developers.google.com/people/v1/read-people

**Comment by JellySlater** [comment]
Update: I am a baboon. I was not removing the `<>` in `<API_Key_Here>` and instead was inserting my API Key between `<` `>`

**Comment by tannerdolby** [comment]
Issues mentioned above that are fixed: (2/4 I think?)
- [x] - "I'm hyperlink leads to a 404." https://developers.google.com/people/v1/read-people  (Fixed in #1454)
- [x] - Fix typo in the `name` field within example code snippet
- [ ] - Question on data returned from an extension? OP expects to see `memberResourceNames` field?
- [ ] - Question on instructions to obtain public key

**Comment by AmySteam** [comment]
Hey @tannerdolby! I failed to see your PR #1478 and I fixed the `name` field in PR #1678. Sorry!  😳 

FYI PR #1678 fixes the 4th item on your list

- [X] Question on instructions to obtain public key in developer dashboard

**Comment by tannerdolby** [comment]
Hey @AmySteam! I just had a look at #1678 and it indeed does fix some of the stuff mentioned in the list here. No worries at all 😅 

I will update my PR and remove the commit that fixes the `name` field and disregard item 4 since that is fixed with 1678 as well. That just leaves list item 3 for us to tackle.
