### ISSUE TITLE
`BrowserCompat` widget should break out mobile Chrome separately

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/developer.chrome.com#7506]
For [`ContactManager`](https://developer.mozilla.org/en-US/docs/Web/API/ContactsManager/select#browser_compatibility), compare… 

![Screenshot 2022-10-06 at 11 49 38](https://user-images.githubusercontent.com/145676/194283359-9040dfae-53ef-439d-a2c1-3196e4a6adef.png)

…to…

![Screenshot 2022-10-06 at 11 53 13](https://user-images.githubusercontent.com/145676/194283584-cb0f387d-b180-44c2-9583-8532c59b302c.png)

**Comment by jpmedley** [comment]
+

> Still worthwhile to have.

+1

**Comment by dstmarthe** [comment]
I've moved this to the new issue tracker. See here: https://issuetracker.google.com/issues/324154913
