### ISSUE TITLE
Anchors on developer.chrome.com don't work when opened in a background tab

### ISSUE THREAD

**Issue by bakkot** [GoogleChrome/developer.chrome.com#7540]
**Describe the bug**
When you open a link to a specific section in a background tab, [like this one](https://developer.chrome.com/blog/smooshgate/#why-dont-we-just-keep-the-existing-name-and-break-the-web), it doesn't always scroll to the linked section, and instead remains at the top.

**To Reproduce**
As above.

**Expected behavior**
It should scroll to the correct section even when loaded in the background.

**Screenshots**

https://github.com/GoogleChrome/developer.chrome.com/assets/1653598/99f89eb6-fd02-41c3-bb8e-0e99b148a77d

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 118

**Additional context**
It doesn't always happen. In particular it seems not to happen with links from Github. I dunno.

**Comment by tunetheweb** [comment]
Fixed by #7637
