### ISSUE TITLE
Full screen bug, trigger click, auto running capture screen, etc.

### ISSUE THREAD

**Issue by anwar907** [GoogleChrome/developer.chrome.com#7550]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Lots of bugs when opening Chrome in full screen like functionality event trigger, can't right click, auto-running capture screen after minimising, sometimes audio recording runs after finish capture screen is finished.

**To Reproduce**
1. Go to 'Full Screen'
2. Click on 'New Tab'
3. Action to '`esc`'

**Expected behavior**
After click `New Tab` trigger click auto focus, after minimize full-screen disable auto capture window

**Screenshots**

https://github.com/GoogleChrome/developer.chrome.com/assets/35429445/652c8bfa-1ff4-45b9-9884-53763690e823

https://github.com/GoogleChrome/developer.chrome.com/assets/35429445/6fd26a65-3aab-4ee0-a085-3548fef6b6bd

**Desktop (please complete the following information):**
 - Version 118.0.5993.70 (Official Build) (arm64)
 - OS: macOS
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**
- Can't right-click
- After minimize full screen auto running capture window
- can't functionality click in full screen

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
