### ISSUE TITLE
chrome.debugger canceled_by_user

### ISSUE THREAD

**Issue by santarosalia** [GoogleChrome/developer.chrome.com#7568]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
i use chrome.debugger api in extension, attached two tab and close one tab but another tab's debugger session canceled.

**To Reproduce**
1. attach debugger two tab each {tabId: 829882371}, {tabId: 829882258}
2. close tab {tabId: 829882371} then can see onDetach target closed {tabId: 829882371}
3.  can see onDetach canceled_by_user {tabId: 829882258}

test code :
const debuggerTest = async () => {
    const tabs = await chrome.tabs.query({});
    const tab1 = tabs.find(tab => tab.title.includes('google1'));
    const tab2 = tabs.find(tab => tab.title.includes('google2'));
    await chrome.debugger.attach({tabId : tab1.id}, '1.3');
    await chrome.debugger.attach({tabId : tab2.id}, '1.3');

    await chrome.debugger.detach({tabId : tab2.id});
}

**Expected behavior**
 close tab {tabId: 829882371} then just onDetach target closed {tabId: 829882371} not canceled_by_user

**Desktop (please complete the following information):**
 - OS: Window11
 - Browser : chrome
 - Version : 118.0.5993.71

**Additional context**

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
