### ISSUE TITLE
scripting is not working in chrome 118 as described in release notes

### ISSUE THREAD

**Issue by dzienisz** [GoogleChrome/developer.chrome.com#7576]
**Describe the bug**
scripting is not working in chrome 118 as described in release notes: https://developer.chrome.com/blog/new-in-chrome-118/#new-media-queries

Check here: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/scripting

**To Reproduce**
1. Go to https://developer.mozilla.org/en-US/docs/Web/CSS/@media/scripting
2. Click on [Results](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/scripting#result)
3. or Scroll down to Results
4. See that You have scripting enabled! :-) is not red

**Expected behavior**
You have scripting enabled! :-) should be red

**Screenshots**
<img width="640" alt="Screenshot 2023-10-18 at 17 01 52" src="https://github.com/GoogleChrome/developer.chrome.com/assets/3521624/8160f768-e2a2-48fd-a771-87fd8f815ec6">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser Chrome
 - Version 118
 
**Additional context**
Maybe I am wrong but when something is in release notes I understand it's enabled.

**Comment by dzienisz** [comment]
Ok I think the issue is that there is lack of information about release schedule in the release notes. As described here it will be released on 120 version: https://chromestatus.com/feature/5075009105559552

**Comment by lukewarlow** [comment]
Apologies this was my error there was a bug in the core that meant scripting was reliant on two flags rather than just 1. That's been fixed in 120. I only found this out after 118 released so unfortunately lots of developer documentation still says 118. It would be good to remove the scripting mention and/or add a note that mentions it's in 120 instead.
