### ISSUE TITLE
Embedded GraalVM debugging not working 

### ISSUE THREAD

**Issue by avantra-mis** [GoogleChrome/developer.chrome.com#7599]
Starting with Chrome 118.0.5993.88 the debugging feature does not work anymore. With older version it worked.

**Current behaviour**

Steps to reproduce the behaviour:
1. Run the Java application in [chrome-debugger-bug.zip](https://github.com/GoogleChrome/developer.chrome.com/files/13044005/chrome-debugger-bug.zip)
2. a JavaScript program will be started in Graal in debug mode. Copy the printed url and try to open it in Chrome to debug it.
3. Starting with Chrome 118.0.5993.88 there is no source code visible and no debugging is possible.

**Expected behaviour**
Debugging should be possible.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Chrome
 - Version 118.0.5993.88
 - GraalVM 21.3.8

**Screenshots**

Working WebSocket Messages (older Chrome version):
<img width="1564" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/61981540/91873a91-0576-4b11-8467-fbd15ea8d314">

Broken version:
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/61981540/46060bf4-7955-4722-8cbd-cf6560b00664)

**Notes**
 - https://www.graalvm.org/latest/tools/chrome-debugger/

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.

**Comment by avantra-mis** [comment]
Did so: https://bugs.chromium.org/p/chromium/issues/detail?id=1494298
