### ISSUE TITLE
Content feedback - tutorial incomplete/ incorrect

### ISSUE THREAD

**Issue by Wuzla** [GoogleChrome/developer.chrome.com#7601]
https://developer.chrome.com/docs/extensions/mv3/getstarted/tut-tabs-manager/

Just above Test that it works section ..........
-- CURRENT -- 
const button = document.querySelector("button");
button.addEventListener("click", async () => {
  const tabIds = tabs.map(({ id }) => id);
  const group = await chrome.tabs.group({ tabIds });
  await chrome.tabGroups.update(group, { title: "DOCS" });
});

-- SHOULD BE -- 
const button = document.querySelector('button');
button.addEventListener('click', async () => {
  const tabIds = tabs.map(({ id }) => id);
  if (tabIds.length) {
    const group = await chrome.tabs.group({ tabIds });
    await chrome.tabGroups.update(group, { title: 'DOCS' });
  }
});

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at [https://issuetracker.google.com/issues/309981761](https://issuetracker.google.com/issues/309981761)
