### ISSUE TITLE
chrome tab not working. 

### ISSUE THREAD

**Issue by achu3397** [GoogleChrome/developer.chrome.com#7607]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**The chrome tab not working in Mac m1**
hi team google chrome suddenly  stuck not working cursers its frizing  in to latest update inside browser not working search box 

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1400" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/75801513/c287d988-b309-494f-ad1b-24ab75571fd5">

**Desktop (please complete the following information):**
 - OS: [Apple M1]
 - Browser [chrome]
 - Version [Version 118.0.5993.88 (Official Build) (arm64)]

**Comment by achu3397** [comment]
I am try to move YouTube but not open its frizzing for above snapshot

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
