### ISSUE TITLE
Justification for 'downloads' permission gets cleared when submitting new extension version

### ISSUE THREAD

**Issue by tamius-han** [GoogleChrome/developer.chrome.com#764]
**Describe the bug**
When a package with a new version of the extension is submitted, the justification for 'download' permission gets cleared.

**To Reproduce**
0. Have an extension that (optionally) requires 'download' permission. (Other permissions my extension has that require explaining: activeTab, storage, host/all sites)
1. Go to developer dashboard
2. Go to the part of the page where you need to explain why you need the permissions your extension requires
3. Fill out the permission boxes, click 'save draft'
4. Upload your extension (or a new version of it)
5. Click 'save draft' again
6. Click 'send to review'

**Expected behavior**
Extension gets sent to review without errors.

**Actual behaviour**
Get an error message along the lines of:

> you didn't provide any justification for why you need a download permission
> you need to tell us why you need the 'download' permission
> I recognize that you've provided the explanation six times in the last two months, but I'm related to Beinoff, Wise and DeBlois and "kinda forgot"

And the 'downloads' permission box is now empty.

**Desktop (please complete the following information):**
 - OS: Linux/Manjaro
 - Browser: Firefox AND Chrome both
 - Version: All versions that were current in the past two months, for both

**Comment by tophf** [comment]
This repository is for the documentation on https://developer.chrome.com, it's not about the web store or general extensions support.

**Comment by robdodson** [comment]
https://stackoverflow.com/ may be a good place to go for implementation questions. If you think you've found a bug in the Chrome extensions platform you can file those at crbug.com.
