### ISSUE TITLE
Chrome 118.0.5993.88: iframe's localStorage can't synced with normal page.

### ISSUE THREAD

**Issue by hello-chenchen** [GoogleChrome/developer.chrome.com#7663]
when i try to save some data to iframe localStorage. for example: localStorage.a = 1 to https://google.com in iframe. 
the normal page in https://google.com(in new tab) the data is undefined localStorage.a = 1.
this issue will not happened in Microsoft EdgeVersion 118.0.2088.69 but only in latest chrome: 118.0.5993.88

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
