### ISSUE TITLE
CustomChromeTabs (Chrome)  are running the same request twice

### ISSUE THREAD

**Issue by dora-emo** [GoogleChrome/developer.chrome.com#7672]
■Organizing key points

<Environment>
・OS: Android12 (API Level31 S(Snow Cone))
・AndroidX.Browser：1.0.0.1
・IdentityModel.OidcClient: 3.1.2

<Procedure>
Login with OIDC using CustomChromeTabs.

1. Enter the following on the login screen
 ·USER ID
 ·password
2. Get authorization code
3. redirect to app
4. Get refresh token using authorization code (IdentityModel.OidcClient)

<Question details>
It looks like you are running the same request twice.

I am displaying the login screen with CustomChromeTabs (Chrome).
1 described in <Procedure>. ~3. It looks like you are trying to execute it twice.

Therefore, the app stores the first refresh token and proceeds to the next process, but
On CustomChromeTabs (Chrome) 1. ~3. Because I am trying to repeat
A second refresh token request is made on the browser, and the refresh token held by the app is outdated.
Using a refresh token will result in an error.

The problem does not occur if you use Safari as your browser.

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.

**Comment by dora-emo** [comment]
I was raise issues with Chrome itself in the Chromium issue tracker

[https://bugs.chromium.org/p/chromium/issues/detail?id=1497355](https://bugs.chromium.org/p/chromium/issues/detail?id=1497355)
