### ISSUE TITLE
User want to allow the location sharing for a specific website using selenium chrome options driver

### ISSUE THREAD

**Issue by sharutkarsh** [GoogleChrome/developer.chrome.com#7685]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

Use case:

On your computer, open Chrome.
At the top right, click More More and then Settings.
Click Privacy and security and then Site settings.
On Site settings page, click on location.
Then want to add a website under "Allowed to see your location"

![image](https://github.com/GoogleChrome/developer.chrome.com/assets/38309256/f3b8a226-0af4-4417-be54-1d45b018c489)

I have tried all this with chrome options but nothing worked, so I think it should be a new feature

   ` contentSettings.put("geolocation", 1);
    contentSettings1.put("notifications", 1);
    contentSettings1.put("geolocation", 1);

    profile.put("managed_default_content_settings", contentSettings);
    profile.put("default_content_setting_values", contentSettings1);
    
    prefs.put("googlegeolocationaccess.enabled", true);
    prefs.put("profile.default_content_setting_values.geolocation", 1); // 1:allow 2:block
    prefs.put("profile.default_content_setting_values.notifications", 1);
    prefs.put("profile.managed_default_content_settings", 1);

    prefs.put("profile", profile);
	
	ChromeOptions options = new ChromeOptions();

	options.setExperimentalOption("prefs", prefs);`
	
`

Initially i had raised it here: https://github.com/SeleniumHQ/selenium/issues/13061#issuecomment-1783624478

**Comment by dstmarthe** [comment]
Thanks for raising this, but since this is not an issue with the d.c.c website I will have to close it. A more appropriate place to put this issue would be in the ChromeDriver issue tracker: https://bugs.chromium.org/p/chromedriver/issues/list
