### ISSUE TITLE
Images of Performance metrics are outdated

### ISSUE THREAD

**Issue by konfirmed** [GoogleChrome/developer.chrome.com#7697]
**Describe the bug**
On a few pages where performance metrics are defined and discussed, the images on them are outdated. The images of the Lighthouse report still have **Time to Interactive** on them.

**To Reproduce**
1. Go to '[Speed Index](https://developer.chrome.com/docs/lighthouse/performance/speed-index/)'
2. Scroll down to the image below the text "Lighthouse displays Speed Index in seconds:"

**Expected behavior**
This image should not have Time to Interactive on it.

**Screenshots**
<img width="746" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/9829274/776cef8b-10c2-4d2d-8d3d-61a6c8ce9ffc"> I would change the images myself, but I was not sure of that the procedure to do so is. 

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional context**
n/a

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/311086574
