### ISSUE TITLE
fixed postition for left sidebar

### ISSUE THREAD

**Issue by akaashvaa** [GoogleChrome/developer.chrome.com#7735]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

### Problem
I'm always frustrated when i have to select another chapter or section to read more documentation

### Solution
Just fixing the position of the left sidebar can make this site more user-friendly.

here is the url link:
[url link](https://developer.chrome.com/docs/extensions/mv3/manifest/#manifest-examples)

### Please watch the below screencast for more precise observation of the issue. 

[Screencast from 03-11-23 09:44:43 AM IST.webm](https://github.com/GoogleChrome/developer.chrome.com/assets/98875003/53b13a1a-044c-4ee7-9658-061d89397cb0)

**Comment by akaashvaa** [comment]
## _### **Help Needed**_ 
I don't know whether I'm in the right place to raise this issue or not. If I'm wrong, please suggest where I can open this issue.
Also, as a front-end developer, I can easily fix this, but I didn't find the git repository for it.

**Comment by akaashvaa** [comment]
### Help Needed
I don't know whether I'm in the right place to raise this issue or not. If I'm wrong, please suggest where I can open this issue.
Also, as a front-end developer, I can easily fix this, but I didn't find the git repository for it.

**Comment by rachelandrew** [comment]
Hi @akaashvaa - we're actually migrating to a new platform shortly so we won't be making changes to the code here. Thanks!
