### ISSUE TITLE
Issue in Chrome Incognito Session Creation Using Webdirectional BIDI

### ISSUE THREAD

**Issue by PavanKumarS25** [GoogleChrome/developer.chrome.com#7739]
The Scenario is when we try to set capabilities to launch the Chrome browser in Incognito Using Webdriver BiDi it is throwing Error Massage
{
    "value": {
        "error": "unknown error",
        "message": "unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"Failed to open new tab - no browser is open\"}\n  (Session info: chrome=118.0.5993.117)",
        "stacktrace": "\tGetHandleVerifier [0x01144DE3+43907]\n\t(No symbol) [0x010D0741]\n\t(No symbol) [0x00FC33ED]\n\t(No symbol) [0x00FB5C90]\n\t(No symbol) [0x00FB450F]\n\t(No symbol) [0x00FB4C1A]\n\t(No symbol) [0x00FB4BB8]\n\t(No symbol) [0x00FAAC40]\n\t(No symbol) [0x0101A49D]\n\t(No symbol) [0x01018F2C]\n\t(No symbol) [0x01012956]\n\t(No symbol) [0x00FEE17E]\n\t(No symbol) [0x00FEF32D]\n\tGetHandleVerifier [0x013F5AF9+2865305]\n\tGetHandleVerifier [0x0143E78B+3163435]\n\tGetHandleVerifier [0x01438441+3138017]\n\tGetHandleVerifier [0x011CE0F0+605840]\n\t(No symbol) [0x010DA64C]\n\t(No symbol) [0x010D6638]\n\t(No symbol) [0x010D675F]\n\t(No symbol) [0x010C8DB7]\n\tBaseThreadInitThunk [0x75D17BA9+25]\n\tRtlInitializeExceptionChain [0x772FBD3B+107]\n\tRtlClearBits [0x772FBCBF+191]\n"
    }
}

**Comment by dstmarthe** [comment]
Closing because this repo is for issues with developer.chrome.org and not Web/ChromeDriver. I'd suggest submitting an issue to https://bugs.chromium.org/p/chromedriver/issues/list
