### ISSUE TITLE
indexeddb-durability-mode-now-defaults-to-relaxed has incorrect summary

### ISSUE THREAD

**Issue by jjlin** [GoogleChrome/developer.chrome.com#7743]
In https://developer.chrome.com/en/blog/indexeddb-durability-mode-now-defaults-to-relaxed/, the first sentence reads

> The default durability mode in IndexedDB is changing **_from relaxed to strict_** from Chrome 121."

It seems to me this should actually read

> The default durability mode in IndexedDB is changing **_from strict to relaxed_** from Chrome 121."

**Comment by RByers** [comment]
FYI @tomayac - I noticed this too.

**Comment by rachelandrew** [comment]
Fixed in https://github.com/GoogleChrome/developer.chrome.com/pull/7746
