### ISSUE TITLE
LightHouse execution error on chrome 119 and LHCI/CLI npm node version 0.12.0

### ISSUE THREAD

**Issue by sumantap** [GoogleChrome/developer.chrome.com#7751]
**Describe the bug**
Hi I am trying to run my internal or any open source website in my project using LHCI 0.12.0 and chrome version 119. But I am getting  DNS server could not resolve the provided domain error 

**To Reproduce**
1. Write the github action
2. Place the lighthouserc.json file in ./github/workflows floder
3. Install the LHCI CLI using node
4. Then run the LHCI command - lhci autorun --collect.settings.chromeFlags="--no-sandbox" --collect.url="your url" --outputDir=./lhreport
5. Below is the GHA flow
    
<img width="1049" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/11904191/2ef7c3bb-706f-4c25-b79c-fd255805d7d2">

6. Below is the error screenshot

<img width="950" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/11904191/fe7b01e3-d72d-4a8c-a49b-25c27a6d35fd">

**Expected behavior**
Lighthouse report should suppose to be generated but it's not generating the report.

**Comment by sumantap** [comment]
Hi Team,

Any update on this?

Regards,
Sumanta

**Comment by sumantap** [comment]
Hi Team,

Any update on this?

Regards,
Sumanta

**Comment by dstmarthe** [comment]
Hi, this repo is for issues with the developer.chrome.google site, so I have to close this, sorry. A better place for this would be the LightHouse repo here: 
https://github.com/GoogleChrome/lighthouse/issues
