### ISSUE TITLE
DevTools no longer shows all valid values for white-space CSS property

### ISSUE THREAD

**Issue by KomarovS** [GoogleChrome/developer.chrome.com#7767]
**Describe the bug**
Options/values list no longer offers all valid values when adding/editing "white-space" CSS property in Styles tab in Chrome DevTools.

In latest Chrome ver. 119.0.6045.124 x64 (all extentions disabled)
![Clipboard01](https://github.com/GoogleChrome/developer.chrome.com/assets/73106796/3b0e2305-8c74-48fa-9327-85269f07939c)

I have portable version of older Chrome (ver. 112.0.5615.138 x64) and it looks fine there
![Clipboard02](https://github.com/GoogleChrome/developer.chrome.com/assets/73106796/63e0e781-5b8a-4007-95ec-a898e44b81b6)

I do rely on this list of values for many CSS properties when I create styles for web sites.

**To Reproduce**
1. Disable all extentions
2. Open any web site
3. Press F12 / Open DevTools
4. Switch to Elements tab
5. Select any HTML element
6. Try to add white-space CSS property and check list of values offered by DevTools

**Expected behavior**
List of values contains "normal", "nowrap", "pre", "pre-wrap", "pre-line", "break-spaces" values

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Google Chrome
 - Version 119.0.6045.124 (Official Build) (64-bit)

**Comment by rachelandrew** [comment]
This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.
