### ISSUE TITLE
Update speculation rules document rules href_matches examples to no longer have ?*#*

### ISSUE THREAD

**Issue by domenic** [GoogleChrome/developer.chrome.com#7794]
https://developer.chrome.com/blog/debugging-speculation-rules/ has this example:

```html
<script type="speculationrules">
{
  "prerender": [
    {
      "source": "document",
      "where": {
        "and": [
          {"href_matches": "/*\\?*#*"},
          {"not": { "href_matches": "/not-safe-to-prerender/*\\?*#*"}}
        ]
      },
      "eagerness": "moderate"
    }
  ]
}
</script>
```

and a sentence afterwards explaining the `\\?*#*` part.

As of https://github.com/whatwg/urlpattern/commit/ed205a47785a5483106b5bb59bd3f4834785f923, landed in Chromium 121, this is not necessary anymore! You can just do `/*` and `/not-safe-to-prerender/*`.

Chromium 121 hits stable in January 23, so maybe this should not be changed until then?

@tunetheweb

**Comment by tunetheweb** [comment]
Yeah let's wait until Chrome 121 hits stable. Hopefully can also remove the fact it's an OT then!

I've raised this as d.c.c. is in the middle of migration (another reason we don't want to update existing content unless we have to): https://issuetracker.google.com/issues/310861373. Also CCed you on that.
