### ISSUE TITLE
Issue with chrome.declarativeNetRequest Not Blocking Requests Over Time

### ISSUE THREAD

**Issue by tombenattar** [GoogleChrome/developer.chrome.com#7799]
Hi there, 

I'm working on an email tracking extension for Gmail, utilizing the chrome.declarativeNetRequest API. Our extension Manifest V3 aims to block certain network requests when users open emails, ensuring these opens aren't counted by our tracking system.

We employ both Dynamic and Static Rules for this purpose. The Static Rules are a fallback to handle scenarios where the JavaScript might not be loaded.

However, we've encountered a recurring issue reported by several users. After Chrome has been open for an extended period, it appears that our blocking rules stop functioning, and the requests that should be blocked are getting sent.

Here are some specific details:

- Rule Example: { id: 2, priority: 1, action: { type: "block" }, condition: { urlFilter: "*pixel*user=" + [user.id](http://user.id/) + "&end=1*", resourceTypes: ["image"] } }
- Issue Observation: The rule works as expected initially but fails after Chrome has been active for a long time.
- Configuration: We're using a mix of Dynamic and Static Rules, with the latter as a backup.

I'm looking for insights or suggestions on the following:

1. Are there known issues with chrome.declarativeNetRequest in relation to browser uptime?
2. Could this be related to rule limits, caching, or service worker interactions?
3. Any best practices or troubleshooting steps recommended for such a scenario?

Any assistance or guidance would be greatly appreciated.

**Comment by dstmarthe** [comment]
Hi there. This repo is specifically for d.c.c content issues. Also, we're moving to a new platform and issue tracker soon, so I'll be migrating relevant topics. Sorry, but I have to close this thread. For help with Chrome extensions, check out our recommendations here: https://developer.chrome.com/docs/extensions/support-feedback/getHelp/#for-extensions-development

**Comment by ghostwords** [comment]
@tombenattar You could raise this issue in the [W3C WebExtensions community group](https://github.com/w3c/webextensions/issues) and/or the [Chromium issue tracker](https://crbug.com/).

**Comment by tombenattar** [comment]
Thanks!
