### ISSUE TITLE
Percy and LHCI shouldn't snapshot live data

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#78]
@robdodson commented on [Thu Dec 03 2020](https://github.com/GoogleChrome/dcc-private/issues/392)

Percy is snapshotting live data on the home page and elsewhere. This means every day we'll "fail" percy tests because things like our twitter card will update hourly.

Similarly, LHCI will always fail the responsive images check on the homepage because twitter does not send back responsive image sizes (we just get a small, medium, and large and currently we're only using the small).

We already rely on the `CI` env var when running percy, so we should do the same when we run LHCI and:
- Give the page placeholder data so percy doesn't fail
- Disable the twitter card so LHCI doesn't fail.

---

@robdodson commented on [Mon Dec 07 2020](https://github.com/GoogleChrome/dcc-private/issues/392#issuecomment-740191739)

#460 fixes this for the twitter card on the home page.

**Comment by robdodson** [comment]
@samthor this might be a good item to fix soon(ish) just so folks don't grump about failing percy tests all the time

**Comment by samthor** [comment]
Don't we use dummy data for Twitter now?

**Comment by samthor** [comment]
Oh, is your point that we don't set `CI` when running Lighthouse?

**Comment by robdodson** [comment]
I think Percy is currently snapshotting the homepage, but that will always be different because it shows the most recent article and twitter card.

I think it may also be snapshotting the actual /docs/extensions/ page which will change whenever they add a new doc.

And I suspect it may also be snapshotting /blog and not trimming the collection to only the 1st six posts, but I'm not 100% sure on that one.

**Comment by robdodson** [comment]
@samthor this bit @awfuchs today because the featured article on the homepage changed. If you're free next week maybe you can add this to your queue?
