### ISSUE TITLE
Text is missing

### ISSUE THREAD

**Issue by def00111** [GoogleChrome/developer.chrome.com#7817]
**Describe the bug**
Text is missing.

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/reference/offscreen/#type-Reason'
2. Scroll down to 'DOM_PARSER', 'WEB_RTC' and 'CLIPBOARD'
3. See error

**Expected behavior**
No text missing.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version [119.0.6045.160]

**Comment by dstmarthe** [comment]
Whoa, thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/312974148
