### ISSUE TITLE
Chrome DevTools detects device only when device is plugged out/disconnected

### ISSUE THREAD

**Issue by nemanjarogic** [GoogleChrome/developer.chrome.com#7840]
Short summary:

Chrome **DevTools doesn't detect my device** (Google Pixel 7 Pro) **when device is plugged in**. The interesting thing is that the **device is recognized when I disconnect it from the cable**. When that happens, I am able to see pages opened in a browser on my device for a short period of time (5 seconds) before they disappear. Of course, in that scenario pages are not interactive, so If you click "Inspect" option before it dissapear nothing will happen.

Some useful information:

- Chrome DevTools and device detection worked for me in the past. Therefore, I am not trying this for the very first time.
- USB debugging is enabled on the phone
- I tried setting USB preferences to "File transfer", "MIDI", "No data transfer", etc. It behaves the same for every mode.
- I am able to see my device from File explorer. I can copy photos from the phone to laptop, etc.
- When I run adb devices command my device is recognized (and it is not in the offline mode)
- I followed [the troubleshooting instructions](https://developer.chrome.com/docs/devtools/remote-debugging/#troubleshooting) from the official page. My device is connected to the machine directly, I tried unplugging the USB cable multiple times and USB cable definitely works.
- I tried to [install OEM USB driver manually](https://developer.android.com/studio/run/oem-usb), but I am not allowed to replace the driver. This happens after I choose a new driver location
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/12249325/a097672c-51f2-4227-baa9-1e3f953f2eb6)

- Chrome **DevTools recognize a device from my college.** So, the problem is probably somehow related to specific device model, not to machine settings. In my case the device is Google Pixel 7 Pro

Any ideas?

**Comment by nemanjarogic** [comment]
Is this bad place for the bug report, since this is not feature request?
Template mentioned https://bugs.chromium.org/p/chromium/issues/list, but [the documentation](https://developer.chrome.com/docs/devtools/remote-debugging/#troubleshooting) said it should be reported on the repo.

**Comment by dstmarthe** [comment]
Hey @nemanjarogic 
Yea https://bugs.chromium.org/p/chromium/issues/list?q=&can=2 would be the place to go for bugs.
 
The documentation is more saying that if you have a solution that can be added to the doc itself then open the issue here.

**Comment by rodsotdia** [comment]
@nemanjarogic Did you find the solution? I'm having the same issue.

**Comment by nemanjarogic** [comment]
> @nemanjarogic Did you find the solution? I'm having the same issue.

@rodsotdia No, I haven't found the solution so far. I also asked the question on [stackoverflow](https://stackoverflow.com/questions/77523820/chrome-devtools-detects-device-only-when-device-is-plugged-out-disconnected), but no answers.
