### ISSUE TITLE
chrome devtool: when select one long url and override content , it will change other url icon to purple 

### ISSUE THREAD

**Issue by XueMeijing** [GoogleChrome/developer.chrome.com#7845]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

chrome devtool: when select one long url and override content , it will change other url icon by add a  purple  dot , seems like it overrided the other url too, but infact it didn't.

for example, when i override the long url, it is normal to add purple dot to left icon and response，to represent it was overrided
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/35559153/2ef591d7-8d12-40ac-8983-d2b8cbc1f70f)

but at the same time, it changed the other url left icons to purple, but their response didn't have purple dot, their content didn't change either, which makes me weird
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/35559153/ba48e504-e4e5-405a-9505-3612d0a55722)

in the overrided folder, the url changed to /longurls ,  i assume that is why caused the above case
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/35559153/3aff3d87-0662-4edf-b8a0-dde21435c9f4)

besides, when i override the short url, it works normal.
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/35559153/0484aab0-3e0c-4d7b-ae20-691d122165a0)

**To Reproduce**
1. create server.js && node server.js
```javascript
var http = require('http');

http.createServer(function (request, response) {
    response.setHeader('Access-Control-Allow-Origin', '*')
    response.writeHead(200, {'Content-Type': 'text/plain'});
    response.end('Hello World11\n2');
}).listen(8888);

console.log('Server running at http://127.0.0.1:8888/');
```
2. create test.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    fetch('http://127.0.0.1:8888/api/web/system/env/EI2023110B4022F9/connector/ECI202311A0733EA6?envId=EI2023110B4022F9&id=ECI202311A0733EA6&fields=VIEW_DATA%2CTRIGGER%2CARGUMENT%2CACCOUNT')

    fetch('http://127.0.0.1:8888/api1/web/system/env/EI2023110B4022F9/connector/ECI202311A0733EA6?envId=EI2023110B4022F9&id=ECI202311A0733EA6&fields=VIEW_DATA%2CTRIGGER%2CARGUMENT%2CACCOUNT')

    fetch('http://127.0.0.1:8888/api1?envId=EI2023110B4022F9')
  </script>
</body>
</html>
```
3. open test.html with chrome
4. override the long url as normal
5. refresh html

**Expected behavior**
override content only change the selected long url

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macos Big Sur v11.5.2]
 - Browser [chrome 119.0.6045.159 (Official Build) (arm64)]
 - Version [119.0.6045.159]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dstmarthe** [comment]
Hello, this repo is specifically for issues with the https://developer.chrome.com/ website, not Chromium or Devtools itself.
You will more likely get answers here: https://crbug.com/
