### ISSUE TITLE
Blank page after restoring the closed windows, but resume after several mins

### ISSUE THREAD

**Issue by Xiaod0ng** [GoogleChrome/developer.chrome.com#7847]
**Observed behavior:**
Windows after restoring are all blank. Refresh doesn't work.

**Expected behavior:**
The pages should load. Or at least load after refreshing the page.

**Steps to reproduce:**
1. Open several tabs in chrome;
2. Restart the computer without closing the tabs;
3. After restarting the computer, open chrome, click the three dots button ->History. Find the x tabs under recently closed and restore them;
4. All the tabs are blank (no content shows, totally white page). Refreshing the page doesn't work.
5. They will resume after several mins.

**Environment:**
OS: Windows 11 23H2, 22631.2715
Chrome: Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by dstmarthe** [comment]
Hi, this repo is for issues with the https://developer.chrome.com/ site, not Chromium itself.
Please use https://crbug.com/ for issues with the browser.
