### ISSUE TITLE
Local Storage is not getting sync between the tabs even if the origin is same. This issue is noticed in new chrome version 119.0.6045.105 (Official Build) (x86_64)

### ISSUE THREAD

**Issue by Parvgour98** [GoogleChrome/developer.chrome.com#7848]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**I faced an issue with Chrome Local Storage the issue is that Local Storage is not getting synced between the tabs even if the origin is same. This issue is noticed in new chrome version 119.0.6045.105 (Official Build) (x86_64)**

**To Reproduce**
**Open a new tab from the origin tab (Parent tab) may be try to perform an OAuth and try to set some local storage values in the new tab that is opened from the parent tab now the local storage values that we have added in new tab should sync with the parent tab (origin tab) because they share the same origin.**

**Expected behavior**

**Local Storage values should sync between the tabs if the origin is same.** 

**Screenshots**

**Adding screenshots for the problem**

![image (1)](https://github.com/GoogleChrome/developer.chrome.com/assets/46477131/ae2d015d-dbf1-4697-a787-d8f3f925174f)

![image (2)](https://github.com/GoogleChrome/developer.chrome.com/assets/46477131/45b5641d-d4e9-4261-acc3-034fbb05777d)

**Desktop (please complete the following information):**
 - OS: IOS, MacBook Pro Intel Chip, macOS version 14.1.1 
 - Browser:- Chrome 
 - Version:- version 119.0.6045.105 (Official Build) (x86_64)

**Smartphone (please complete the following information):** **Issue appears on Desktop, so leaving the below information blank.**

**Additional context**

**Please fix this issue on priority.**

**Comment by dstmarthe** [comment]
Hi thanks for rasing this, but I have to close it because - to reiterate the warning - this repo is for issues with the https://developer.chrome.com/ site, not Chromium itself. https://crbug.com/ <--- Is is the place for issues with Chrome.
