### ISSUE TITLE
Chrome Store API docs no longer work, due to OAuth OOB being deprecated

### ISSUE THREAD

**Issue by joeldenning** [GoogleChrome/developer.chrome.com#7851]
**Describe the bug**
[This section](https://developer.chrome.com/docs/webstore/using_webstore_api/#test-oauth) of the Use the Chrome Web Store Publish API page suggests pasting an OAuth OOB url into the browser to retrieve a Code and refresh token. OOB OAuth flows have been blocked as of January 31, 2023, according to [this document](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration). I am unsure how to retrieve a refresh token for my Chrome Store application, since the documentation no longer works.

**To Reproduce**
1. Go to [Chrome Web Store Publish API](https://developer.chrome.com/docs/webstore/using_webstore_api/#test-oauth)
2. Scroll down to "Testing your OAuth application"
4. Copy the URL in that section into a new browser tab. Replace `$CLIENT_ID` with a valid client id. Note that error message as shown below

**Expected behavior**
The steps in the documentation should be valid to create a refresh token for Chrome Web Store apps.

**Screenshots**
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/5524384/8f9e515b-d009-4a28-a41f-78e571f1b7de)

**Additional context**
I publish the single-spa-inspector Chrome extension via `@wext/shipit`, which requires a refresh token.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at 
https://issuetracker.google.com/issues/324144580
