### ISSUE TITLE
"Document.cookie" is wrong, should be "document.cookie"

### ISSUE THREAD

**Issue by jasonjiicloud** [GoogleChrome/developer.chrome.com#7852]
**Describe the bug**
In "https://developer.chrome.com/docs/privacy-sandbox/chips/", an example says 
```js
Document.cookie="__Host-name=value; Secure; Path=/; SameSite=None; Partitioned;"
```
It's wrong, should be:
```js
document.cookie="__Host-name=value; Secure; Path=/; SameSite=None; Partitioned;"
```

**To Reproduce**
Open https://developer.chrome.com/docs/privacy-sandbox/chips/

**Screenshots**
<img width="761" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/106730421/646ce5ac-439e-4cd3-85fb-dd97aab4588b">

**Comment by rachelandrew** [comment]
I've sent in a fix for this to the new owner of this content.
