### ISSUE TITLE
Twice calls chrome.tabs.onUpdated.addListener when use document.write

### ISSUE THREAD

**Issue by semiromid** [GoogleChrome/developer.chrome.com#786]
**Describe the bug**
When I use in the script `content.js`

```
document.open();
document.write(http.responseText);
document.close();
```

in the script `background.js` twice calls `chrome.tabs.onUpdated.addListener`

```
chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {

});
```

**To Reproduce**

1. Set in `background.js`  `chrome.tabs.onUpdated.addListener`
2. In `content.js` call

```
document.open();
document.write('<!DOCTYPE html><html lang="en"><head><title>Test</title></head><body></body></html>');
document.close();
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Win 10 x64 build latest
 - Browser [chrome]
 - Version [90.0.4430.212 ]

**Additional context**

**Comment by tophf** [comment]
This repository is for the documentation on https://developer.chrome.com, it's not about general extensions support.

**Comment by robdodson** [comment]
@semiromid https://stackoverflow.com/ may be a good place to go for implementation questions. If you think you've found a bug in the Chrome extensions platform you can file those at crbug.com.
