### ISSUE TITLE
SIGILL crash when executing wasm and dom manipulation

### ISSUE THREAD

**Issue by alvarolm** [GoogleChrome/developer.chrome.com#7860]
**Describe the bug**
wasm and dom manipulation execution triggers SIGILL

**To Reproduce**
can't share since to much since I don't have permission to share specifics but after a golang wasm executes:
```
str := `
let e = document.getElementById("fecha-creacion");
if (e) {
	$("#fecha-creacion-wrap > div.ui.icon.input.date-input > i.icon.iconz.calendar.link").click();console.log("Q",2);
	$("body > div.flatpickr-calendar.hasTime.animate.open.arrowBottom.arrowLeft > div.flatpickr-innerContainer > div > div.flatpickr-days > div > span:nth-child(12)").click();console.log("Q",3);
	e.value = '';console.log("Q",4);
	$("#submit").click();console.log("Q",5);
	$("#main > div > div > div:nth-child(1) > h2").click();console.log("Q",6);
	e.value = '10/10/1989 12:00 PM';
}
`
app.Window().Call("eval", str)
```
we are currently using go-app package https://github.com/maxence-charriere/go-app/issues/908
js libraries are flatpickr, imask and fomantic latest stable relelases to the date
css uses tailwind latest stable release

so far I have been able to retrieve the crash files but had no luck loading the symbols to the dump file, the browser screen reports SIGILL, and the dump file indicates a SIGTRAP signal.

**Expected behavior**
not to crash

**Screenshots**
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/2561547/565371bb-8c54-4d41-a2f2-d707efaeddac)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: google-chrome
 - Version:  119.0.6045.159 (Official Build) (64-bit)

**Additional context**
I have isolated to the fault to the wasm execution. so far I have been able to retrieve the crash files but had no luck loading the symbols to the dump file, the browser screen reports SIGILL, and the debug file indicates a SIGTRAP signal.

I have attached:

- crash files (.dmp and .meta in a zip file) 
- minidump output of the dump file.

[minidump_output.txt](https://github.com/GoogleChrome/developer.chrome.com/files/13465586/minidump_output.txt)
[crash_files.zip](https://github.com/GoogleChrome/developer.chrome.com/files/13465590/crash_files.zip)

any help is appreciated !

- able to semi-reliable reproduce the crash
- can't share the code since I have no permission to do so
- crash only happens in google-chrome with versions 118+ so far confirmed
- not-crashing in latest stable versions of firefox, chromium, opera

**Comment by rachelandrew** [comment]
This repo was for reporting content issues. To report issues with Chrome itself us crbug.com.
