### ISSUE TITLE
"Override web content and HTTP response headers locally" may point to https://developer.chrome.com/docs/devtools/overrides/

### ISSUE THREAD

**Issue by benyue1978** [GoogleChrome/developer.chrome.com#7877]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
In this page https://developer.chrome.com/docs/devtools/overview/
this link "Override web content and HTTP response headers locally" is pointing to https://developer.chrome.com/blog/new-in-devtools-65#overrides

**To Reproduce**
1. Go to '[DevTool Overview site](https://developer.chrome.com/docs/devtools/overview/)'
2. Click on 'Override web content and HTTP response headers locally'

**Expected behavior**
Jump to https://developer.chrome.com/docs/devtools/overrides/

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dstmarthe** [comment]
Hey, thanks for raising this issue! We've moved to a new issue tracker, but I've migrated this issue here: [link ](https://issuetracker.google.com/issues/324103333)and it is being worked on now. Thanks again.
