### ISSUE TITLE
No mention of removal of allow-insecure-localhost flag in Chrome 119 release notes

### ISSUE THREAD

**Issue by cseas** [GoogleChrome/developer.chrome.com#7885]
* Use this template to propose new content.
* Delete any fields that aren't relevant to your issue.
* Update the title of this issue with a brief summary of the work to be done.

### Content proposal form for contributors who don't have access to Googlers

Fill out this section ONLY if you want to contribute new content to developer.chrome.com but don't have access to
Googlers.

#### Provide a brief summary of your content proposal

This flag is extensively used by the engineering team in my org for local development and testing our application. This change should be explicitly called out in the release notes. Hundreds of other developers have also complained that their engineering teams are affected by this change:
https://support.google.com/chrome/thread/241869686/allow-insecure-localhost-has-been-removed-as-of-chrome-119

#### What content already exists on this topic?

https://developer.chrome.com/en/blog/new-in-chrome-119/

#### Are there any stakeholders who should be informed when this content changes?

Developers

#### What area is your content related to?

Local development using Chrome

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll resolve this over there. I’ve moved the issue to our new tracker and you can see it at: https://issuetracker.google.com/issues/324159801
