### ISSUE TITLE
Update links in preconnect documentation

### ISSUE THREAD

**Issue by webtrainingwheels** [GoogleChrome/developer.chrome.com#7888]
In this article: https://developer.chrome.com/docs/lighthouse/performance/uses-rel-preconnect/
These 2 links are pointing to the wrong place: 
<img width="798" alt=" Annotation 2023-11-30 at 7 58 13 AM" src="https://github.com/GoogleChrome/developer.chrome.com/assets/1043076/27bf3d11-1789-408b-b9c2-bc77cd7237f4">

Currently they go to:

- https://developers.google.com/web/fundamentals/performance/resource-prioritization#use-case_knowing_where_from_but_not_what_youre_fetching
- https://developers.google.com/web/fundamentals/performance/resource-prioritization#use-case_knowing_where_from_but_not_what_youre_fetching

They should link to: 
- https://web.dev/articles/preconnect-and-dns-prefetch#knowing_where_from_but_not_what_youre_fetching
- https://web.dev/articles/preconnect-and-dns-prefetch#streaming_media

Thanks!

**Comment by rachelandrew** [comment]
Thanks, I've submitted a fix which should be live shortly.
