### ISSUE TITLE
Need Guidance on Targeting Specific Tabs with chrome.userScripts.register() in MV3 Extension Migration

### ISSUE THREAD

**Issue by karanshukla430** [GoogleChrome/developer.chrome.com#7891]
Hello community,

I'm currently migrating an extension from Manifest V2 to Manifest V3, and I've encountered a challenge with the chrome.userScripts.register() API. The extension includes custom JavaScript code, and I want to ensure it runs on a specific tab rather than applying it globally to all tabs.

Here's a snippet of the code I'm currently using:

chrome.userScripts.register({
  ...
  ...
});

The issue is that this code is being applied to the entire website across all tabs. If someone has a specific tab ID and wants to run the code only on that tab, how can this be achieved within the context of Manifest V3?

I'd greatly appreciate any insights or code examples that demonstrate how to target a specific tab using the chrome.userScripts.register() API in the MV3 extension environment.

Thank you in advance for your assistance!

**Comment by dstmarthe** [comment]
This tracker is for issues with the content at [developer.chrome.com](http://developer.chrome.com/), please raise Chromium issues at: https://issues.chromium.org/issues?q=is:open
or
https://groups.google.com/a/chromium.org/g/chromium-extensions
