### ISSUE TITLE
chrome.windows.create createData should warn about type for offsets

### ISSUE THREAD

**Issue by GaurangTandon** [GoogleChrome/developer.chrome.com#7901]
**Describe the bug**

Link to documentation: https://developer.chrome.com/docs/extensions/reference/windows/#type-CreateType

It states the offset properties `left` and `top` can be `number` type. But, passing a fractional value will create an error. 

**To Reproduce**

For example, passing `window.screen.width / 2` to the `left` offset property is a common pattern. I did the same as [this SO poster](https://stackoverflow.com/q/71715344/2181238) - and we both got the same error:

> Error in invocation of windows.create(optional object createData, optional function callback): Error at parameter 'createData': Error at property 'left': Invalid type: expected integer, found number. 

**Expected behavior**

The documentation should show an explicit warning for integer types.

**Comment by dstmarthe** [comment]
Hi, thanks for raising this. We've moved to a different issue reporting platform. You can reproduce this issue here if you'd like: https://issuetracker.google.com/issues/new?component=1400036&template=1897236
