### ISSUE TITLE
a slight issue with converting large numbers

### ISSUE THREAD

**Issue by 5soros** [GoogleChrome/developer.chrome.com#7902]
A little thing  here
I have noticed that if CSS properties like width and height exceed 16 digits in Google Chrome's developer tools, the displayed values become inaccurate. For example, if I set width to 9999999999999999px, the developer tools would display it as width: 10000000000000000px
LOL
**FIREFOX** browser does not have this issue
<img width="587" alt="Snipaste_2023-12-04_17-10-27" src="https://github.com/GoogleChrome/developer.chrome.com/assets/87423801/2b100d0f-c4a7-42d1-8f2e-e88faf170dd5">

**Comment by rachelandrew** [comment]
This repo was for issues with the site at developer.chrome.com, please report Chrome issues at crbug.com
