### ISSUE TITLE
getUserMedia media streams capturing issue in MV3 (chrome extension) with respect to constraints

### ISSUE THREAD

**Issue by Nitesh2503** [GoogleChrome/developer.chrome.com#7903]
**Bug Description**
When using the `getUserMedia` API in Chrome to capture audio from specific Chrome tabs using the chromeMediaSource and chromeMediaSourceId constraints, the API is not behaving consistently. The issue manifests as the error "Uncaught (in promise) DOMException: Invalid state error."

**To Reproduce**
1. Get the streamId from the desktopCapture API 
```
chrome.desktopCapture.chooseDesktopMedia(
      ["tab", "audio"],
      tab,
      (streamId, options) => {});
```
Here,  tab` argument consists of the tab info

2. Use the getUserMedia API to get the streams
```
navigator.mediaDevices.getUserMedia({
  audio: {
    mandatory: {
      chromeMediaSource: "desktop",
      chromeMediaSourceId: streamId,
    },
  },
  video: {
    optional: [],
    mandatory: {
      chromeMediaSource: "desktop",
      chromeMediaSourceId: streamId,
    },
  },
}).then((streams)=>{});;
```
Here, the "Uncaught (in promise) DOMException: Invalid state error." will occur

**Expected behavior**
The `getUserMedia` API should consistently capture audio from Chrome tabs using the specified chromeMediaSource and chromeMediaSourceId constraints without resulting in an "Invalid state error."

**Screenshots**
These are the expected beahavior :
<img width="1309" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/72183768/36f140c8-0b70-45fb-9ced-ac2c51a81aa6">

<img width="1309" alt="image" src="https://github.com/GoogleChrome/developer.chrome.com/assets/72183768/7ad7e299-a50d-4942-9601-5890bfc222ea">

**Desktop (please complete the following information):**
 - OS :  iOS
 - Browser : chrome
 - Version : 119.0.6045.199 

**Additional context**
I am working on the chrome extension (Manifest Version-3) so using the `getUserMedia` API to get the streams from the particular streamId and as mentioned above facing the Issues while capturing the media.

For reference use the below doc for more info on the errors for the different constraints of the `getUserMedia` API tried
[getUserMedia-DOC](https://docs.google.com/document/d/1CQXxIqrd5WS0sDzHr5douaino35Iwm8aq7cQLn7-HFc/edit)

**Comment by dstmarthe** [comment]
This tracker is for issues with the content at [developer.chrome.com](http://developer.chrome.com/), please raise Chromium issues at: https://issues.chromium.org/issues?q=is:open
