### ISSUE TITLE
mv3 sidepanel awareness

### ISSUE THREAD

**Issue by KnIfER** [GoogleChrome/developer.chrome.com#7905]
**Describe the bug**
My extension is using the same page for popup mode, normal tab mode, and side panel mode.

The problem is that when I use the following manifest : 

```
"side_panel": {
        "default_path": "file.html?sidepanel=true"
    },

   "action": {
      "default_popup": "file.html?popup=true"
   },
```

browser complains :  

> Side panel file path must exist.

where the 'file.html'  **does exit**, it just contains url parameters .  without it, how can the extension page know it's opened in side-panel mode ?

**Expected behavior**
either allow url parameters or provide method/property of `is_side_panel`

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H2
 - Browser Google Chrome dev 
  - Version 121.0.6156.3

**Comment by dstmarthe** [comment]
This tracker is for issues with the content at [developer.chrome.com](http://developer.chrome.com/), please raise Chromium issues at: https://issues.chromium.org/issues?q=is:open
