### ISSUE TITLE
"Suggest changes on GitHub" link on all posts

### ISSUE THREAD

**Issue by karlhorky** [GoogleChrome/developer.chrome.com#7911]
**Is your feature request related to a problem? Please describe.**

1. I was reading [the New in Chrome 120 post](https://developer.chrome.com/blog/new-in-chrome-120) (thanks @tropicadri !) just now and I noticed an error
2. I wanted to contribute a fix to the project but did not know where to look
3. The only buttons on the page are "Was this helpful?" (thumbs-up or thumbs-down)
   <img src="https://github.com/GoogleChrome/developer.chrome.com/assets/1935696/92e9cc58-84b4-45f7-a02b-ebb9d73cab71" width=130 />
4. I ended up searching for information about the author @tropicadri, looking through her history of commits and then finding the pull request in question, which led me to find the content in the repo
5. I eventually opened #7910 once I figured everything out

**Describe the solution you'd like**

This process would be made much easier with a link to GitHub eg. "Suggest changes on GitHub", which would directly open an "edit" link such as:

https://github.com/GoogleChrome/developer.chrome.com/edit/main/site/en/blog/new-in-chrome-120/index.md

**Describe alternatives you've considered**

A full WYSIWYG / CMS experience built into the page with multi-language support

**Additional context**

--

**Comment by rachelandrew** [comment]
Thanks - but we have now moved off GitHub so there isn't a way to suggest changes. Issues will need to be reported on the issue tracker linked from the site.

**Comment by karlhorky** [comment]
Oh, that's too bad to hear. Hope that the team reconsiders moving back to GitHub.

Openness to community being able to suggest changes and improvements is great.

In the meantime, maybe you or someone from the team could copy my issue over to the issue tracker, so that I don't need to re-do it.
