### ISSUE TITLE
What are the webrequestblocking exceptions on mv3?

### ISSUE THREAD

**Issue by Lucienest** [GoogleChrome/developer.chrome.com#7912]
The https://developer.chrome.com/docs/extensions/reference/api/webRequest states that

> As of Manifest V3, the "webRequestBlocking" permission is no longer available for most extensions. Consider "declarativeNetRequest",

but it doesn't say all (it's saying `most`), that means there are exceptions or maybe whitelisting programs that 
allow certain extensions to use the API
please tell me more about it
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/61408704/2a790140-d36c-4715-b4ea-12097132b021)

**Comment by dstmarthe** [comment]
Hi, thanks for raising this issue. We've moved to a new issue tracking platform so I urge you re-create this issue there to receive an answer. Visit: https://issuetracker.google.com/issues/new?component=1400036&template=1897236
