### ISSUE TITLE
ctrl+f in console will find results inside console.table() generated cells, but will not properly highligh those results

### ISSUE THREAD

**Issue by yg-i** [GoogleChrome/developer.chrome.com#7918]
**Describe the bug**
ctrl+f in console will find results inside console.table() generated cells, but will not properly highlight those results

**To Reproduce**
1. Go to devtools console
2. Evaluate the expression: `console.table(Object.getOwnPropertyDescriptors(Node.prototype))`
3. Bring up the find panel by pressing Ctrl+f

4. First, try to find "getOwn" and verify that (at least) one result is found, and has the proper highligh color. In my dark theme the highlight color looks like this: 

- ![image](https://github.com/GoogleChrome/developer.chrome.com/assets/148152939/93cb5c6b-80eb-4b3d-81ab-ed474aedfc08)

6. Next, try to find "isConnected", and verify that at least 1 result can be found:

- ![image](https://github.com/GoogleChrome/developer.chrome.com/assets/148152939/43324198-1ee3-41ec-b14d-8081781312b6) 

7. Now let's go and *visually* try to find the search results ...

- ![image](https://github.com/GoogleChrome/developer.chrome.com/assets/148152939/3b0e9bc7-abe6-45db-8048-4d145ad8501e)

**Expected behavior**
Search results should be highlighted:

- ![image](https://github.com/GoogleChrome/developer.chrome.com/assets/148152939/41471e51-563c-4a7b-b4ca-293f74b4b6c6)

After all, if you open a "meta" devtool, you can see that 'isConnected' is indeed wrapped in a span with the .highlighted-search-result class.

- ![image](https://github.com/GoogleChrome/developer.chrome.com/assets/148152939/2c28dbce-c626-4b2e-8498-7f7339c29207)

**Observed behavior**
Search results are not highlighted

**Comment by rachelandrew** [comment]
This repo was for issues with the site at developer.chrome.com, please report Chrome issues at crbug.com
