### ISSUE TITLE
Allow webSerial for Chrome Android

### ISSUE THREAD

**Issue by hpssjellis** [GoogleChrome/developer.chrome.com#7948]
As far as I know, on old Android Pixel phones version 119 and earlier of Chrome allowed webSerial through polyfill.

https://github.com/google/web-serial-polyfill/issues/54#issue-1746740080

I think after chrome version 120 released in Nov 2023 webSerial stopped working.

Subject: Feature Request - Implementation of WebSerial in Chrome for Android

Dear Chrome Development Team,I am writing to request the inclusion of the WebSerial API in Google Chrome for Android. As a developer working with microcontrollers (MCUs) and machine learning, the ability to interact with serial devices directly through a web browser is invaluable. The integration of WebSerial would greatly enhance the capabilities of Chrome on Android, especially for those of us in the fields of machine learning and hardware development.Currently, Chrome for Android lacks this functionality, limiting the scope of creative and professional projects that can be developed and deployed on this platform. 

The implementation of WebSerial would not only bring Chrome for Android in line with its desktop counterpart but also open up new avenues for innovation and development in machine learning and hardware interfacing.Thank you for considering this request. 

The addition of WebSerial to Chrome for Android would be a significant step forward in supporting a broader range of applications and users in the technology community.

Thank you, Jeremy Ellis

@hpssjellis

**Comment by reillyeon** [comment]
Android does not provide the platform API which we need to allow us to implement the Web Serial API in Chrome. The polyfill provides this API by using the WebUSB API, which uses the Android USB Host API under the hood, to provide its own implementation of the low-level USB serial drivers which Android devices sometimes ship with but the platform doesn't expose to applications. The consequences of these drivers being present cause some serial devices to be inaccessible to Chrome on some Android devices. The work necessary to resolve that is tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=1099521.

To my knowledge there aren't any changes in Chrome 120 which would have changed this behavior, but it might've been affected by an Android update.
