### ISSUE TITLE
Make responsive tables more accessible

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#80]
@robdodson commented on [Wed Dec 02 2020](https://github.com/GoogleChrome/dcc-private/issues/378)

We're already doing some of this, but Adrian has a good post on some additional things we can do to make our overflow tables more accessible.

https://adrianroselli.com/2020/11/under-engineered-responsive-tables.html

**Comment by samthor** [comment]
Rob, what do you think of this vs #38? Should we instead try to prevent overflow tables where possible?

If we stick with overflow tables, it seems like we should have them intentionally extend _more_, as right now it's possible for some columns to be very tiny and make text hard to read.

**Comment by robdodson** [comment]
Commented over in https://github.com/GoogleChrome/developer.chrome.com/issues/38#issuecomment-764158386
