### ISSUE TITLE
Debugger keeping machine awake

### ISSUE THREAD

**Issue by richtera** [GoogleChrome/developer.chrome.com#803]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

The recent versions of the debugger keep machines awake.

This was originally apparent for windows in both Chrome and Edge, and has now made it over to the Mac as well. This means that for a normal developer workflow the debugger is no longer an application you can keep open the same way as any other web page. I constantly have to make sure I close down all debug windows and losing current debugging context, just because I want the machine to go to sleep. Many times I get back to my machine in the middle of the night and both screens are awake and it's just sitting there. This is not good and I do not understand why this is a new thing that was added, I have been using chrome for development for years and never had such problems.

**To Reproduce**
1. Open chrome
2. Open the debugger
3. Wait

**Expected behavior**
The computer should go to sleep after the normal idle timeout but it stays away for days.

**Desktop (please complete the following information):**
 - OS: Windows and Mac
 - Browser: Chrome and Edge
 - Version lastest (currently on mac Version 90.0.4430.212 (Official Build) (x86_64))

**Additional context**
I tried to file this previously, but I think it didn't go into this github repo.

**Comment by robdodson** [comment]
@richtera this repo is only for the documentation at developer.chrome.com. For Chrome bugs, please file them at crbug.com
