### ISSUE TITLE
Search results should filter out shortcodes and markdown.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#807]
Try searching for something on the site and you'll see a bunch of markup in the description:

![image](https://user-images.githubusercontent.com/1066253/119062553-eea02f00-b98b-11eb-956b-7c952c253bca.png)

the markup is a mixture of eleventy shortcodes and some of our markdown-it extensions like `{: #foo }`

**Comment by robdodson** [comment]
@MichaelSolati would you be cool taking this ticket?

**Comment by samthor** [comment]
This is #924
