### ISSUE TITLE
Search has horizontal shift

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#82]
@robdodson commented on [Wed Dec 02 2020](https://github.com/GoogleChrome/dcc-private/issues/361)

When typing in the search box you'll notice a little horizontal shift on mobile. This is because we set the body to overflow hidden which causes the pages scrollbar to disappear and the page expands to fill in that missing space.

Some possible fixes would be to set the body to position fixed, width: 100vw or always set the page to have a body width of 100vw (which ignores scrollbar but feels dangerous)

**Comment by samthor** [comment]
Can't repro this.

**Comment by robdodson** [comment]
I believe it's still there (anytime the scrollbar disappears you get this effect). In this video, keep your eye on the magnifying glass icon and notice how it shifts to the right when it becomes an X.

https://user-images.githubusercontent.com/1066253/129816284-35388a15-4765-4631-adec-493ba18d1b62.mp4

I want to say that there's some new CSS thing that's supposed to fix this issue. @argyleink do you know what i'm talking about?
