### ISSUE TITLE
"magic" `getTabId()` method in the docs

### ISSUE THREAD

**Issue by AntonOfTheWoods** [GoogleChrome/developer.chrome.com#822]
**Describe the bug**
A `getTabId` method is referenced as if it were a method available in the default extension execution context

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/reference/scripting/'
2. Reproduce `const tabId = getTabId();` code in a V3 extension
3. See error "ReferenceError: getTabId is not defined" in your code
4. Go to Google Search and find no help on the error.

**Expected behavior**
I expect that examples that are used will clearly show the code required (possibly via a link to an external page), and not assume that "it's obvious that you have to implement this yourself, and you will obviously know how to because you were in my head when I was writing the documentation"

**Comment by dotproto** [comment]
Thanks for the report. I see how this approach can be confusing. 

For context, the pattern you've highlighted is attempting abstract away parts of the example that are not relevant to the specific example being shown. In this case, there are a variety of ways an could get a tab's ID and we did not want to assume any specific use case. I don't see a way to provide "examples that … clearly show the code required" as some of that code is necessarily out of scope of the embedded code blocks.

At the moment I see two ways that we could address this. 

### Solution 1

Remove the `getTabId` reference and leave tabId undefined. This approach trades an implicit function for an implicit variable.

```js
chrome.scripting.executeScript(
  {
    target: { tabId: tabId },
    files: ["script.js"],
  },
  () => { /* … */ }
);
```

### Solution 2

Add a function definition for `getTabId` to indicate that implementation of this function is left as an exercise for the reader. While this more clearly sets expectations, the sample is still not usables as is.

```js
function getTabId() { /* … */ }
chrome.scripting.executeScript(
  {
    target: { tabId: getTabId() },
    files: ["script.js"],
  },
  () => { /* … */ }
);
```

@robdodson, do you have any thoughts?

**Comment by AntonOfTheWoods** [comment]
Thanks for your feedback @dotproto. I guess this is a somewhat typical example of what those who are new to JS and/or part-timers get so frustrated about. Such things might seem utterly obvious if you spend 40 hours p/w developing JS but they are utterly not for us. I fully realise a balance needs to be reached between putting obvious stuff and brevity but definitely have a personal preference for at least the `{ /* … */ }` version. 

Particularly for those of us who are not full-time JS devs but want to migrate to V3 and adopt best practices, slightly more hand-holding can significantly reduce the "%#@#"-JS factor. It looks like I was able to migrate to V3 very easily (there might still be some bugs...) and apart from the two minor docs issues I have submitted it was actually a pleasure!

**Comment by robdodson** [comment]
> I fully realise a balance needs to be reached between putting obvious stuff and brevity but definitely have a personal preference for at least the { /* … */ } version.

I also prefer this approach. @awfuchs would you be able to make this update in `site/en/docs/extensions/reference/scripting/index.md` ?

**Comment by tophf** [comment]
The examples in the documentation and in [the comment above](https://github.com/GoogleChrome/developer.chrome.com/issues/822#issuecomment-848340880) above are confusing the newcomers by implying that the tab id can be obtained synchronously, which is only true for listeners like chrome.tabs.onUpdated or chrome.action.onClicked, but even then there's no need for the function.

The best solution would be to fix executeScript in MV3, which has broken the ability to omit the tab id, and then remove tabId from all the examples except one that shows how to supply it, maybe in two flavors: one for a listener like the above, another one using chrome.tabs.query.

A more practical solution would be to remove getTabId and show all the examples as async functions:

```js
async function inject() {
  const [tab] = await chrome.tabs.query({active: true, currentWindow: true});
  const results = await chrome.scripting.executeScript({
    target: {tabId: tab.id},
    ..........
```

**Comment by tophf** [comment]
Here's evidence that people just can't grasp the concept of getting the tab id properly:
https://stackoverflow.com/questions/67432398/how-to-load-content-script-in-chrome-extension-v3

Also note how the answer didn't reuse the tab parameter of the listener.
