### ISSUE TITLE
Developer fee

### ISSUE THREAD

**Issue by qayyumabro** [GoogleChrome/developer.chrome.com#825]
Hi, I cant see Pakistan in the country list on webstore payment form.

![image](https://user-images.githubusercontent.com/9138521/119498837-7e285200-bd7f-11eb-905f-216bee2979d1.png)

**Comment by dotproto** [comment]
Hey @qayyumabro. Unfortunately the payment platform used by CWS does not support payments in all countries. You may want to try to reach out to the [CWS Developer Support team](https://support.google.com/chrome_webstore/contact/one_stop_support) about this issue to see if they have any guidance.
