### ISSUE TITLE
New in Chrome 91 - Deprecations and removal link broken

### ISSUE THREAD

**Issue by fedejousset** [GoogleChrome/developer.chrome.com#833]
**Describe the bug**
The **New in Chrome 91** documentation page displays a link to documentation related to Deprecations and Removals which is not working.

**To Reproduce**
1. Go to https://developer.chrome.com/blog/new-in-chrome-91/
2. Click on _Chrome 91 deprecations & removals_ (https://developer.chrome.com/blog/deps-rems-91/)
3. See error

**Expected behavior**
Links redirects to the correct documentation page.

**Screenshots**
![image](https://user-images.githubusercontent.com/20836210/120049990-ba73e080-c013-11eb-85d9-668c6f4508f6.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by myakura** [comment]
It looks like there's no post yet.
https://github.com/GoogleChrome/developer.chrome.com/pulls?q=is%3Apr+91

There's a branch working on it, so hopefully we'll see it soon.
https://github.com/GoogleChrome/developer.chrome.com/compare/deprems91

**Comment by fedejousset** [comment]
Thanks for the update @myakura !
