### ISSUE TITLE
Display + link to blog post tags from blog post detail pages

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChrome/developer.chrome.com#835]
**Is your feature request related to a problem? Please describe.**

Whenever I’m reading a “what’s new in DevTools” blog post like https://developer.chrome.com/blog/new-in-devtools-89/, I want to click through to read other posts in this series.

We have several pages for that:

- https://developer.chrome.com/tags/new-in-devtools/ (the tag page)
- https://developer.chrome.com/docs/devtools/updates/ (the DevTools-specific overview page)

However, the blog post template doesn't link to any of these.

**Describe the solution you'd like**
It'd be nice if blog post tags were displayed + linkified on blog post detail pages. This would address the problem in a generic way, that's useful beyond just the DevTools posts.

Alternatively, we could add a link to https://developer.chrome.com/docs/devtools/updates/ to blog post detail pages if and only if the blog post has the “what’s new in DevTools” tag.

**Comment by mathiasbynens** [comment]
cc @chybie

**Comment by chybie** [comment]
@robdodson , at the moment, the What's New blog post inherited from the `blog-post.njk` layout. Is that okay if I create a new layout for the `What's New in DevTools` series?

Related to this, there are a couple of headers (e.g. ux survey link, announcement) and footer (e.g. link to other post in the series, link to DevTools social media) I would like to put in to all What's New in DevTools blog posts.

**Comment by robdodson** [comment]
> It'd be nice if blog post tags were displayed + linkified on blog post detail pages

We should be able to do this (it looks like we already do it on web.dev). @MichaelSolati or @devnook, do either of y'all have bandwidth to add this feature to the `blog-post.njk` template?

![Screen Shot 2021-06-01 at 5 08 46 PM](https://user-images.githubusercontent.com/1066253/120404878-2a2be900-c2fc-11eb-960d-c8f9e44b7e42.png)

> @robdodson , at the moment, the What's New blog post inherited from the blog-post.njk layout. Is that okay if I create a new layout for the What's New in DevTools series?

I would recommend against creating custom page templates for posts. We did this (briefly) on web.dev for web vitals and found that it was very easy for us to make changes to the blog post template which were then not reflected in the vitals template.

> Related to this, there are a couple of headers (e.g. ux survey link, announcement) and footer (e.g. link to other post in the series, link to DevTools social media) I would like to put in to all What's New in DevTools blog posts.

Can you create tickets for each item that you would like to add. My thinking is that these should be things that any post author can have access to in their posts' yaml frontmatter. For what it's worth, I tried to design the announcement banner with this in mind, so I think it may be possible (or close to possible) to have a custom banner at the post level.

**Comment by chybie** [comment]
Created: #842 #843 #844

**Comment by mathiasbynens** [comment]
@chybie @robdodson

> > Related to this, there are a couple of headers (e.g. ux survey link, announcement) and footer (e.g. link to other post in the series, link to DevTools social media) I would like to put in to all What's New in DevTools blog posts.
> 
> Can you create tickets for each item that you would like to add. My thinking is that these should be things that any post author can have access to in their posts' yaml frontmatter. For what it's worth, I tried to design the announcement banner with this in mind, so I think it may be possible (or close to possible) to have a custom banner at the post level.

Have you considered not creating a separate template, but rather adding one or more conditionals to the `blog-post.njk` template? The logic would be “if the list of tags includes “What’s new in DevTools”, then output this extra stuff”.

**Comment by robdodson** [comment]
> Have you considered not creating a separate template, but rather adding one or more conditionals to the blog-post.njk template? The logic would be “if the list of tags includes “What’s new in DevTools”, then output this extra stuff”.

Yeah, I think making the blog-post template configurable would be ideal. I definitely don't want to have a "extremely similar but slightly different" page template because it's so easy for those to get out of sync when we do bug fixes and new features.
