### ISSUE TITLE
"background window" link on Declare Permissions page is obsolete.

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#840]
**Describe the bug**
The description for the "background" permission on the [Declare Permissions](https://developer.chrome.com/docs/extensions/mv3/declare_permissions/) page links to [developers.google.com/chrome/apps/docs/background.html](http://developers.google.com/chrome/apps/docs/background.html), which in turn redirects to [docs/apps/manifest/](https://developer.chrome.com/docs/apps/manifest/). The final page does not contain any relevant information about the background permission.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/mv3/declare_permissions/
2. Search for "background"
3. Click the last link the permission's description.
4. Look for any information on the background permission on the next page

**Expected behavior**
The linked page should provide a clear and concise description of the background permission.

**Screenshots**
![Screen Shot 2021-06-01 at 1 08 20 PM](https://user-images.githubusercontent.com/1047763/120384098-94cc2d00-c2da-11eb-86e1-3de0d92a6d83.png)

**Desktop (please complete the following information):**

**Additional context**
* The original link points to `http://developers.google.com/chrome/apps/docs/background.html`
* 307 redirects to `https://developers.google.com/chrome/apps/docs/background.html`
* 301 redirects to `https://developers.google.com/chrome/apps/docs/background.html`
* 307 redirects to `http://developer.chrome.com/apps`
* 301 redirects to `https://developer.chrome.com/apps`
* 301 redirects to `https://developer.chrome.com/docs/apps/manifest`
* 301 redirects to `https://developer.chrome.com/docs/apps/manifest/`

We can cut out a lot of these unnecessary hops by updating the link in `/docs/extensions/mv3/declare_permissions/`

**Comment by robdodson** [comment]
@dotproto are you proposing creating a new page or updating an existing one? Would that work usually go to you or Andy?

**Comment by dotproto** [comment]
@robdodson It looks like this issue has been addressed in #791 by dropping the link entirety. As such, I'm assigning this to @awfuchs and closing.
