### ISSUE TITLE
The completed extension can be downloaded here. doesn't work 

### ISSUE THREAD

**Issue by NatnaelSisay** [GoogleChrome/developer.chrome.com#853]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
I have downloaded the finished file and see an error when I click the button

**To Reproduce**
1. got to extensions
2. add the finished extension ( download and unzip first)
3. click the extension icon
4. click the green button
5. error: Uncaught (in promise) Error: Cannot access a chrome:// URL

**Expected behavior**
To change the background color of the page

**Screenshots**
https://drive.google.com/file/d/1KBOdfNxCZSO-bvTb3ZmIeUhPa-mucHqe/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser chrome

**Additional context**
Am getting started and don't know what to do about it

**Comment by robdodson** [comment]
@NatnaelSisay which page did you download the extension from?

**Comment by NatnaelSisay** [comment]
https://developer.chrome.com/docs/extensions/mv3/getstarted/

**Comment by dotproto** [comment]
The extension (mostly) works, but extensions cannot to inject scripts on `chrome://` URLs. Since this is a barebones extension, it doesn't have any error handling. We either need to make the demo more robust, mention this limitation in the getting started guide and/or the extension source, or some a combination of these.

**Comment by AmySteam** [comment]
This was fixed in PR https://github.com/GoogleChrome/developer.chrome.com/pull/3328
