### ISSUE TITLE
chrome.storage API References erroneously mark `get` and `set` as returning Promises

### ISSUE THREAD

**Issue by alex-laties** [GoogleChrome/developer.chrome.com#874]
**Describe the bug**
Current documentation for `get` and `set` functions on the [`chrome.storage` API Reference](https://developer.chrome.com/docs/extensions/reference/storage/) page mark each function with a little green `Promise` badge with helptext showing that these functions can return Promise objects. As of the filing of this issue and as of Chrome version `91.0.4472.101`, this does not appear to be the case. Further documentation on the function signatures of `get` and `set` on the [`chrome.storage` page](https://developer.chrome.com/docs/extensions/reference/storage/) shows that these functions indeed do not return Promise objects. However, without comparison to APIs that _do_ actually return Promises like [`chrome.tabs.create`](https://developer.chrome.com/docs/extensions/reference/tabs/#method-create), the omission of a Promise return type in the function signature is hard to notice.

As it currently stands, the documentation conflicts with itself and is confusing to me.

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/reference/storage/'
2. Scroll down to the function reference for `get` or `set`.
3. Hover over the green `Promise` pill placed below the function name and signature.
4. See helptext `Can return its result via Promise`.

**Expected behavior**
No green pill text advertising `Promise` return values.

**Screenshots**
![example2](https://user-images.githubusercontent.com/361825/121638942-c8852080-ca59-11eb-8531-0f201fa42671.png)
![example1](https://user-images.githubusercontent.com/361825/121638961-d0dd5b80-ca59-11eb-9351-5a9ae93fe605.png)

**Comment by samthor** [comment]
Thanks, I'm not sure why this is occuring. The [underlying source indicates that these methods are async](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/extensions/common/api/storage.json) but it's not even appearing in Canary.

cc @chromatim

**Comment by chromatim** [comment]
Ah, thanks for bringing this one up. I missed that this schema is using the
Custom Types special case in the API bindings, which we've not added
promise support on yet. I'll revert the CL which changed it to use
returns_async (which essentially was a no-op other than being falsely
marked in the docs as you mentioned). This will at least mark it correctly
in the docs for now to avoid confusing, and then I'll reland the change
once we get to adding in the support for Custom Types.

Sorry for the confusion.

**Comment by chromatim** [comment]
FYI these APIs now support promises and are marked as such again in the docs 🙂
