### ISSUE TITLE
Option to automatically increment through mobile views

### ISSUE THREAD

**Issue by johnobrien8642** [GoogleChrome/developer.chrome.com#884]
I think this is a pretty simple feature request so I'll keep it brief.

What about an option to automatically increment through each mobile view option? Right now I have to manually click through each mobile view option to see each CSS style in each mobile view. It would be awesome to maybe have a checkbox and an interval to just begin automatically incrementing through each mobile view, would save a lot of clicks.

That's it!

**Comment by robdodson** [comment]
@johnobrien8642 This sounds like a DevTools feature request? If so, I think those should be filed at http://crbug.com/
This site is really only for documentation. Tentatively going to close but I also want to tag in @chybie in case they have any thoughts on where best to file devtools feature request.
