### ISSUE TITLE
Code returns errors [or] unexpected results  when the same code is executed continously

### ISSUE THREAD

**Issue by Dhar45** [GoogleChrome/developer.chrome.com#885]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
If the java script code is executed multiple times in the source tab(snippet) then it will return unexpected results [or] errors. 

**To Reproduce**
1. Open the chrome developer tools in incognitive mode(To ensure, the issue is not because of cache )
2. Click on 'Source tab' and then click on 'New Snippet'
3. Create a snippet file for example: report.js
4. Paste the following code as an example:

```
var what =[0,1];
function computer(h){
    for(c=2; c<h; c++){
        what.push(what[c-2] + what[c-1]);
    }
    return what;
}
```

5. In the console, 
  execute ---------> `computer(5);` 
  It will return. ----> (5) [0, 1, 1, 2, 3]

6. Repeat step 5, but this time, it will return different result
  execute ---------> `computer(5);` 
  It will return. ----> (8) [0, 1, 1, 2, 3, 1, 2, 3]

**Expected behavior**
As we are executing the same code without doing any modifications to the main code, the output should return the same results.

**Screenshots**
<img width="1680" alt="Screenshot 2021-06-14 at 1 05 07 AM" src="https://user-images.githubusercontent.com/59304392/121819806-c535a300-ccac-11eb-9792-f5bce0c606d9.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: chrome
 - Version : 10.14.6

**Additional context**
If this is not a bug, then please let us know the reason behind it.

**Comment by dotproto** [comment]
This issue appears to describe a Chrome bug rather than a bug report or feature request for the developer.chrome.com repository. Please visit https://crbug.com/new to file a bug report.
