### ISSUE TITLE
Broken links on the webRequest page

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#890]
_This issue was originally submitted to the chromium issue tracker: [crbug.com/1177653](https://crbug.com/1177653)_

Some links in WebRequest page are pointing to nonexistent headings.

https://developer.chrome.com/docs/extensions/reference/webRequest/#implementation 

^like this one. The appropriate section is called "implementation details"

**Comment by jpmedley** [comment]
I can't find instances of the suggested broken link anywhere in our documentation. This must have been fixed by some other effort. Closing the ticket.
