### ISSUE TITLE
A title is being cut off on the blog landing page

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#891]
I think this image speaks for itself.

![image](https://user-images.githubusercontent.com/8204171/122146864-a2ba9b80-ce0c-11eb-84be-bad820c538e9.png)

**Comment by robdodson** [comment]
I think the issue is because there is text in the blog post image. We use `object-fit: cover` on that thumbnail.
@chybie what do you think about not using text in those images? It is also duplicated because right below it we show the title of the post.

**Comment by robdodson** [comment]
OK I think we can work around this by setting the images to auto height and just using a max-height to constrain things.
