### ISSUE TITLE
Check for orphaned links due to cruft purges

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#898]
In the review of #749 @dotproto suggested checking the corpus for discrepancies similar to those they picked up in the review:

I noticed that within this PR we have pages that we're keeping that link to pages we're deleting. It may be worth searching through the corpus for other links to ensure that we're not trying to link to unreachable content.

This ticket is a reminder to execute that when time permits.

**Comment by devnook** [comment]
Duplicate #100
