### ISSUE TITLE
Add reusable tabs component

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#90]
@robdodson commented on [Tue Oct 27 2020](https://github.com/GoogleChrome/dcc-private/issues/184)

There are multiple places where we'll need to use a tabs component in our markup. I think we might be able to steal the one from web.dev

**Comment by robdodson** [comment]
This is implemented in web.dev as a pretty complex shortcode and I think it might be good for us to revisit that and see if we can simplify it.

It's not uncommon for authors to want to do tabs for comparing code in different languages or versions of a library.

**Comment by dotproto** [comment]
Off the top of my head, a few extensions use cases come to mind.

* Promises & callbacks snippets
* MV2 & MV3 manifest/scripts
* Multiple files shown together in a walkthrough, especially for embedding the final version in the page.
