### ISSUE TITLE
`Search Next` in DevTools' 'Sources' tab skips results when navigating minified code

### ISSUE THREAD

**Issue by mikekoscinski** [GoogleChrome/developer.chrome.com#902]
**Describe the bug**

This bug occurs in the DevTools `Sources` tab, when searching in minified JavaScript files **before** they are pretty-printed.

Within a minified JS file, I searched for `.submit` in the `Sources` tab of Chrome DevTools. There are eight matching results. However, when I select `Search Next` to navigate to the next matching result, I am only able to navigate to results 1/8, 3/8, 5/8, and 7/8.

However, if I use DevTools to pretty-print the relevant (minified) file, I no longer experience this issue and am able to navigate all search results as expected.

Note that, when experiencing this issue, I did not have the `Match Case` or `Use Regular Expression` search options enabled.

**To Reproduce**
1. Go to walmart.com
2. Open DevTools
3. Navigate to `Sources` tab
4. Expand the drop-down folder for `walmart.com`
5. Click on `sw-check.js`
6. Confirm that the file has not yet been pretty-printed
7. Search (Ctrl-F) for `addEventListener`
8. You will see there are two matches (as of 6/18/21 at 2:59 PM EDT)
9. Click `enter`. You will see the error. 
10. See error

**Expected behavior**
When I click `enter` within the search box, I would expect to navigate among all matching instances of my search parameter. However, this does not occur if the minified code has not yet been pretty-printed.

This issue no longer occurs once the code is pretty-printed.

**Screenshots**

Before navigating to the next search result:
![Before hitting `enter` on search results](https://user-images.githubusercontent.com/59475481/122605963-2dd2a600-d046-11eb-8460-2022a422f8d3.png)

After navigating to the next search result (unsuccessfully):
![image](https://user-images.githubusercontent.com/59475481/122606049-50fd5580-d046-11eb-803d-820e41a685b1.png)

**Desktop:**
 - OS: macOS Catalina - Version 10.15.7
 - Browser: Brave - Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (x86_64)
 - Device: MacBook Pro (Retina, 15-inch, Late 2013)

**Comment by MichaelSolati** [comment]
This would be an issue probably better suited to the [chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list), rather than the chrome developer site.
