### ISSUE TITLE
Allow users to specify the color used to highlight DevTools search results

### ISSUE THREAD

**Issue by mikekoscinski** [GoogleChrome/developer.chrome.com#903]
**Is your feature request related to a problem? Please describe.**
My computer's blue light filter makes it impossible to read yellow highlights. This makes it difficult for me to use the search functionality within Chrome's `Elements` tab in DevTools.

**Describe the solution you'd like**
I want to be able to specify the color used to highlight DevTools search results.

This setting could be contained in the `Appearance` section of `Preferences` in DevTools `Settings`:
![image](https://user-images.githubusercontent.com/59475481/122607146-21e7e380-d048-11eb-9fae-6aa88b2daac0.png)

**Describe alternatives you've considered**
Currently, I disable my blue light filter when I need to make heavy use of DevTools search. This leads to eye strain, though, and is not ideal.

**Additional context**
N/A

**Comment by MichaelSolati** [comment]
This would be an issue probably better suited to the [chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list), rather than the chrome developer site.

**Comment by mikekoscinski** [comment]
Ah, sorry about that. Thanks, I'll post there.
