### ISSUE TITLE
mv3 docs manifest_version page still says to use "2"

### ISSUE THREAD

**Issue by phoenixeliot** [GoogleChrome/developer.chrome.com#906]
**Describe the bug**
This page: https://developer.chrome.com/docs/extensions/mv3/manifest/manifest_version/
Is still a copy of the mv2 contents. It should be updated to recommend using Manifest v3, and update the paragraph describing the deprecation status of mv2.

**Screenshots**
<img width="875" alt="Screen Shot 2021-06-20 at 15 15 49" src="https://user-images.githubusercontent.com/491376/122688609-8470e900-d1da-11eb-8ac8-e1fc70c65746.png">

**Desktop (please complete the following information):**
N/A, applies to all.

**Comment by robdodson** [comment]
@awfuchs are you cool taking a look at this?

**Comment by robdodson** [comment]
It looks like #662 and #907 are both trying to address this. @awfuchs can you help make a call on what the right next steps are?
