### ISSUE TITLE
Search results show raw content of {% Img %} shortcode

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/developer.chrome.com#924]
Search results show raw content of {% Img %} shortcode - seems like algolia is getting raw content instead of already rendered html.

**Comment by devnook** [comment]
<img width="505" alt="Screenshot 2021-06-25 at 11 45 40" src="https://user-images.githubusercontent.com/1914261/123406315-11d18600-d5ab-11eb-94e2-6bd302dfd643.png">

**Comment by MichaelSolati** [comment]
The `item.template.frontMatter.content` is problematic as legit just pulls the md as it is without parsing it. I wish we could have access to `item.templateContent` during collection initialization, but we don't. What we would need is some code/logic to strip all shorctodes/macros/not html or md from `item.template.frontMatter.content` when we go to index the data. @robdodson if you have any thoughts that would be awesome!

**Comment by robdodson** [comment]
This person seems to be accessing templateContent here:

![image](https://user-images.githubusercontent.com/1066253/123494447-ba481000-d5d4-11eb-8f51-8dd00e4b7616.png)

https://www.raymondcamden.com/2020/06/24/adding-algolia-search-to-eleventy-and-netlify

Would something like that work?

**Comment by MichaelSolati** [comment]
I think i can do something like this. This is a really good idea 😁, I'll work on this next week.
