### ISSUE TITLE
Inspect Network Activity Demo isnt working

### ISSUE THREAD

**Issue by adrianmcg85** [GoogleChrome/developer.chrome.com#925]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The link from the youtube description or developer.chrome tutorial goes to a 403 Forbidden error.
https://www.youtube.com/watch?v=e1gAyQuIFQo
https://developer.chrome.com/docs/devtools/network/

**To Reproduce**
1. Go to links above
2. Click on link for demo

**Expected behavior**
To see a demo.

**Comment by MichaelSolati** [comment]
@robdodson I think this glitch is the issue => https://devtools.glitch.me/network/getstarted.html

I'm not sure who's in charge of glitch stuff, but I do think you'd know better than me.

**Comment by robdodson** [comment]
I'll email Kayce to see if he knows what happened to it.

**Comment by robdodson** [comment]
This app should be running again. I've asked Kayce to transfer ownership to me so we can make sure it stays boosted.

**Comment by Hatch11251** [comment]
Mind sharing the vid? I'm trying to catch up

**Comment by AaronForinton** [comment]
Can't replicate so closing.
