### ISSUE TITLE
Add twitter, github etc attribution to posts, just like web.dev does

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/developer.chrome.com#926]
Can we add these attribution links to the author section at the top of blog posts? e.g.

https://developer.chrome.com/blog/renderingng/

has no attribution, but I'm pretty sure @rachelandrew added them in the metadata. My understanding is that this feature isn't part of the template for rendering posts yet.

**Comment by mollietokyo** [comment]
**Estimate** - 1 day (design & dev time combined)

**Comment by MichaelSolati** [comment]
@devnook you didn't have to unassign me, if there's a design I wouldn't mind implementing this 😅

**Comment by devnook** [comment]
@MichaelSolati Ah, sorry, I was unassigning all stale tickets as part of the cleanup. I think the design is pretty much "like in web.dev" since they're just plain links.

**Comment by MichaelSolati** [comment]
> @MichaelSolati Ah, sorry, I was unassigning all stale tickets as part of the cleanup. I think the design is pretty much "like in web.dev" since they're just plain links.

Got it, well I'll add this next week then.
