### ISSUE TITLE
missing SSML support for speech synthesis

### ISSUE THREAD

**Issue by malo1972** [GoogleChrome/developer.chrome.com#934]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
SSML is not supported leading to misinterpretations for move announcements on lichess.org

**To Reproduce**
see issue https://github.com/ornicar/lila/issues/9222

**Expected behavior**
configuration of spelling charcters like 
`<speak> <say-as interpret-as="characters">can</say-as> </speak>`

**Screenshots**
see issue https://github.com/ornicar/lila/issues/9222 (videos with audio)

**Desktop (please complete the following information):**
 - OS: WIn 10
 - Browser chrome
 - Version  91.0.4472.114

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android
 - Browser chrome

**Additional context**
speech synthesis is different over broswers and platforms and even not clearly reproducble sometimes.
SSML would make cdistinct definition of how to speak. Lichess is open source and speech synthesis is used by disabled persons

**Comment by robdodson** [comment]
Hi there 👋

This repo is only for the documentation on developer.chrome.com. For Chrome bugs or feature requests, please file those at crbug.com.
