### ISSUE TITLE
webview documentation has incorrect url.

### ISSUE THREAD

**Issue by karan173** [GoogleChrome/developer.chrome.com#937]
The webview documentation has the url https://developer.chrome.com/docs/extensions/reference/webviewTag/. Navigating to https://developer.chrome.com/docs/apps/reference/webviewTag/ redirects to the extensions url as well. 

However this is incorrect as webviews are only relevant for chrome apps. So the documentation should live at https://developer.chrome.com/docs/apps/reference/webviewTag/ and the extensions url should redirect to the apps one.

**Comment by robdodson** [comment]
I think this is an unfortunate side effect of merging the extensions and the apps API reference because they were mostly identical. I think @samthor understands this better than me, but he's currently out on leave so we probably can't dig into this until after mid July.

**Comment by samthor** [comment]
We discussed this a bit when we migrated everything over. It's a bit of a pain to put this under the /apps/ URL, and these are a _type_ of extensions API. We do make it very clear that this is a deprecated Apps-only API in the page.
