### ISSUE TITLE
Link from console.log examples to new debugging discussion

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#947]
In the review of #943, [@tophf noted](https://github.com/GoogleChrome/developer.chrome.com/pull/943/files#r661616320) that console.log output isn't in a place that is obvious to beginners unfamiliar with DevTools. This is a good point.

Action: link this (and perhaps many other places) to the new debugging article in development.

**Comment by heyawhite** [comment]
@sofiayem is this still relevant? Or can we close out?

**Comment by dstmarthe** [comment]
I'd also like to know whether to close or migrate this to the new tracker!
@awfuchs @sofiayem @dotproto

**Comment by sofiayem** [comment]
Please migrate this. I'll investigate there.

**Comment by dstmarthe** [comment]
Great - I've migrated the main parts here: 
https://issuetracker.google.com/issues/324436855
