### ISSUE TITLE
Establish a retention plan for information about historical platform changes

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#949]
While discussing #934, @awfuchs [raised a question](https://github.com/GoogleChrome/developer.chrome.com/pull/943#discussion_r661848436) about keeping, "Beginning in Chrome 35".

To that end, we should document how long retain this kind of information either in the extension platform documentation itself or at least in the [dcc handbook](https://developer.chrome.com/docs/handbook/).

**Comment by robdodson** [comment]
@dotproto who should own this issue?

**Comment by dotproto** [comment]
Thanks for assigning it to me. I'm probably a good owner for this.

**Comment by dstmarthe** [comment]
Moved this issue here: https://issuetracker.google.com/issues/312790942
