### ISSUE TITLE
Links provided in the Chrome developers website are dead

### ISSUE THREAD

**Issue by hmffa** [GoogleChrome/developer.chrome.com#964]
The links provided in below page are all dead:
https://developer.chrome.com/docs/extensions/mv3/tut_oauth/

**Comment by samthor** [comment]
The specific broken links are:

* download links for sample source files (should go to samples repo)
* a link to "retrieve those contact's profiles and information" which should probably go to https://developers.google.com/people/api/rest/v1/contactGroups/get
