### ISSUE TITLE
Audit Tab missing in Chrome DevTools

### ISSUE THREAD

**Issue by SubraGomz** [GoogleChrome/developer.chrome.com#966]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**
1. Go to [LightHouse](https://developers.google.com/web/tools/lighthouse)
2. Scroll down to https://developers.google.com/web/tools/lighthouse#devtools
3. Click `Open Chrome DevTools.`
4. Check for `Audit` Tab

**Expected behavior**
Audit Tab should be shown

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser  [chrome]

**Comment by myakura** [comment]
>  Audit Tab should be shown

Sadly you cannot open DevTools (or a specific tab in DevTools) via a link. yeah that page looks unhelpful.

And the Audit Tab is now replaced with the Lighthouse tab. (yes the document should be updated.)
To open the Lighthouse tab, open DevTools an find the tab:

1. open DevTools (from the context menu → Inspect or menu → More Tools → Developer Tools)
    (you can open DevTools with some more other ways. check out https://developer.chrome.com/docs/devtools/open/ )
2. look for the Lighthouse tab in the toolbar

You still might not be able to find the Lighthouse tab in the toolbar. In that case, try looking for it in the console drawer.

1. select "Show console drawer" from DevTools menu or hit Esc
2. look for the Lighthouse tab in the console drawer
3. (optionally) right click on the Lighthouse tab and select "Move to top" to move it to the top toolbar
