### ISSUE TITLE
Make the diagram on docs/webstore/authentication accessible

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#97]
@kaycebasques commented on [Mon Nov 16 2020](https://github.com/GoogleChrome/dcc-private/issues/268)

The image in `localhost:8080/docs/webstore/authentication#sample-workflow` should be converted to text. There is a lot of important information in there that is not accessible.

**Comment by robdodson** [comment]
This would be nice but I can definitely understand if there are higher priorities

**Comment by jpmedley** [comment]
There is a closed PR, so closing this ticket.
