### ISSUE TITLE
ClickJacking on developer.chrome.com

### ISSUE THREAD

**Issue by spinel007** [GoogleChrome/developer.chrome.com#971]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
This [https://developer.chrome.com/] domain can be browsed through Clickjacking completely 

**To Reproduce**
1. use this code 
```
<html><head>
<title>Click Jacking</title>
<style>
body{
background:black;
text-align:center;
}
frame {
opacity: 0.5;
border: none;
position: absolute;
top: 0px;
left: 0px;
z-index: 1000;
}
</style>
</head>
<body>
<script>
</script>
<p> <h1 style="color:red;">Sensetive ClickJacking</h1></p>
<iframe id="frame" width="95%" height="80%" src="https://developer.chrome.com/">
</html>
```
**Expected behavior**
the web site can be browsed inside an iframe

**Screenshots**
https://i.imgur.com/Xi3Lr7T.png

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelSolati** [comment]
@samthor or @robdodson do you guys have thoughts on how you'd like this to be addressed (and if it should be addressed).

**Comment by samthor** [comment]
I sent a PR for this.
