### ISSUE TITLE
typo with "chrome" trademark

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#976]
this page:
https://developer.chrome.com/docs/extensions/reference/signedInDevices/

has this description:
```
Use the chrome.signedInDevices API to get a list of devices signed into
chrome with the same account as the current profile.
```

it should be `Chrome`, not `chrome`.

**Comment by MichaelSolati** [comment]
This is pulled directly from the chromium source code by a tool, for this to be fixed it would need to be [fixed here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/signed_in_devices.idl;l=6?q=se%20the%20chrome.signedInDevices%20API%20to%20get%20a%20lis&ss=chromium).

**Comment by vapier** [comment]
posted a CL for it then, thanks
https://crrev.com/c/3036170
