### ISSUE TITLE
paren mismatch in chrome.runtime API descriptions

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#977]
these 2 API descriptions:
https://developer.chrome.com/docs/extensions/reference/extension/#method-isAllowedFileSchemeAccess
https://developer.chrome.com/docs/extensions/reference/extension/#method-isAllowedIncognitoAccess

is missing a closing paren:
```
Retrieves the state of the extension's access to the 'file://' scheme
(as determined by the user-controlled 'Allow access to File URLs' checkbox.
```
```
Retrieves the state of the extension's access to Incognito-mode
(as determined by the user-controlled 'Allowed in Incognito' checkbox.
```

although it seems like we could just delete the `)`.

**Comment by MichaelSolati** [comment]
@samthor I'm not sure if this is an issue with the actual code comments or your parser, would you mind taking a look?

**Comment by samthor** [comment]
This is an issue with the underlying source.

https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/common/extensions/api/extension.json

**Comment by vapier** [comment]
okiedokie, i can send them a CL
