### ISSUE TITLE
Commands API document coding error

### ISSUE THREAD

**Issue by a90120411** [GoogleChrome/developer.chrome.com#980]
**Describe the bug**
commands basic example coding error.
Page Link : https://developer.chrome.com/docs/extensions/reference/commands/#basic-command

//Error
```
chrome.commands.onCommand.addListener((command) => {
  console.log(`Command "${command.name}" triggered`);
});
```

//Fix
```
chrome.commands.onCommand.addListener((command) => {
  console.log(`Command "${command}" triggered`);
});
```

**Comment by robdodson** [comment]
@dotproto is this related to your recent work on the commands api examples?

**Comment by samthor** [comment]
This seems fixed.
