### ISSUE TITLE
# symbol after heading creates an extra line space when on a line on its own

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/developer.chrome.com#982]
Tiny buglet: if the # for a heading is pushed onto a new line on its own, an extra line space is displayed.

You can see this in the screenshot below (but also when the # is not displayed).

<br><br>

---

![image](https://user-images.githubusercontent.com/205226/125518109-95928ccb-c859-4968-8be3-3f76467162e5.png)

**Comment by samthor** [comment]
This is #476.
