### ISSUE TITLE
[CWS CUJs] Creating a MV3 Chrome Extension

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#983]
- [Friction Log](https://docs.google.com/document/d/10XtamVuu5FEUL20m9tCqRMl9cga_-XGe7PVB2gKXozw/edit?ts=60ee0d24#)

**Comment by kien161632** [comment]
> CONTRIBUTING.md

**Comment by kien161632** [comment]
#1828
