### ISSUE TITLE
chrome.extension.getBackgroundPage() is undefined

### ISSUE THREAD

**Issue by changyongyong** [GoogleChrome/developer.chrome.com#986]
![image](https://user-images.githubusercontent.com/10693934/125617167-83b63e3c-fd03-4581-af1f-5da4c0f792cc.png)

bug in imgage

**Comment by MichaelSolati** [comment]
This looks like an issue specific to Chrome and not the Chrome Developers documentation site. This would probably better suited to the [chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list), rather than the here.
